### ISSUE TITLE
Clearing cache when saving globals

### ISSUE THREAD

**Issue by riasvdv** [putyourlightson/craft-blitz#1]
Might be a good idea to clear all the caches when a global is saved/changed or at least an option for it.

Example use case:

We have a site where we allow the client to post a notice that is shown on every page, if this would be cached and the client changes it in the globals, it won't show up until they would manually clear the cache.

**Comment by putyourlightson** [comment]
I have plans for improving the cache busting and will keep this use case in mind, thanks.

**Comment by putyourlightson** [comment]
Added in https://github.com/putyourlightson/craft-blitz/commit/99356a7b2a03160e9c11e61a9824e70e3383cd62
