### ISSUE TITLE
cURL malformed when using aliases?

### ISSUE THREAD

**Issue by thaoms** [putyourlightson/craft-blitz#10]
When using this is site url: `@web/`

I get this error:

```
Warming Blitz cache – this may take some time.
Exception 'GuzzleHttp\Exception\RequestException' with message 'cURL error 3: <url> malformed (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)'
```

**Comment by putyourlightson** [comment]
Is this happening on Blitz version 1.4.0?

**Comment by thaoms** [comment]
Yes, when I output the url I get this '`/`'.

I'm using the console command:
` ./craft blitz/cache/warm`

**Comment by putyourlightson** [comment]
Ah I see, the `@web` alias is not available in the console as it is dynamically generated by the requested URL in a web request. I'm not sure what the best course of action is in this situation.

**Comment by thaoms** [comment]
Good point, It's just a small inconvenience to use a fixed url! No big problem.
Maybe just add a small notice in the readme for console use.

Thank you!

**Comment by putyourlightson** [comment]
Done and fixed the error in https://github.com/putyourlightson/craft-blitz/commit/3b7e11ad47ae21c056690f619afb65355a6941d6
