### ISSUE TITLE
Problems using Blitz on a Windows machine

### ISSUE THREAD

**Issue by jerseycloud** [putyourlightson/craft-blitz#100]
I am using the latest and the greatest Craft CMS (3.1.23) and Blitz (2.0.8). I can install the plugin successfully, but when I try to visit any of the pages, I get an error that says the following:

Next yii\base\Exception: Failed to create directory "C:\Programs\wamp64\my_sites\precio_local\web\cache\blitz\http:": mkdir(): No such file or directory in C:\Programs\wamp64\my_sites\precio_local\craft_rompeprecio_gupeet\vendor\yiisoft\yii2\helpers\BaseFileHelper.php:633

My question is: Has Blitz been tested on a Windows 10 machine before? If yes, anybody else reporting any issues while running Blitz on a Windows machine?

**Comment by putyourlightson** [comment]
What is your site base URL set to? Sounds like the folder path cannot be determined correctly.

**Comment by jerseycloud** [comment]
The site base URL is set to "/" value. Just a single forward slash. I agree that Blitz is getting confused with a single slash as the value of the base URL. Other aspects of CraftCMS have no issues with the single slash as the value of the base URL.

**Comment by jerseycloud** [comment]
I solved the problem temporarily by creating an environmental variable called "MY_BASE_URL" and setting the value of this variable to http://my-domain.com.

This seems to make Blitz happy. (I haven't discovered any issues with this approach yet.)

**Comment by putyourlightson** [comment]
Ok cool. What was the site base URL set to previously in the CP?

**Comment by jerseycloud** [comment]
Please see my previous comment in the thread; it goes into the details about the previous value.

**Comment by putyourlightson** [comment]
Ah I missed that comment. Yes that was likely the issue. I believe an absolute URL, whether set in the field, in an environmental variable or the general config file, is the recommended approach.

**Comment by keyurshah** [comment]
I'm receiving this same error as well on Windows 10 as well. Into which field setting did you apply the `MY_BASE_URL` field? I tried in some places but no luck. 

Thanks.

**Comment by putyourlightson** [comment]
@keyurshah An absolute URL in the `Base URL` field under _Sites > Settings_ should do the trick. If not then what errors are you seeing?

**Comment by keyurshah** [comment]
thanks for that. I was looking for the field in the Blitz settings area. It works great now!

**Comment by putyourlightson** [comment]
Excellent!
