### ISSUE TITLE
getcsrfinput only working on initial page load and not rendering input field from cache.

### ISSUE THREAD

**Issue by brianrivet** [putyourlightson/craft-blitz#102]
Hi,

I'm having a problem where I'm trying to use a getcsrfinput tag to render a csrf input into a slot for a Vue component. I'm noticing that when I initially load a page (cache empty or first time loading the page) I see the span tag for the Blitz injection and the CSRF input is inside it, but then if I refresh the page and it loads from the Blitz cache the span for the injection is there but it is empty.

The code that loads the Vue component is pretty basic:

```
<contact-form>
    {{ craft.blitz.csrfInput() }}
</contact-form>
```
 and here's the output I'm seeing when the cache is empty:

`<span id="blitz-inject-1" class="blitz-inject"> <input type="hidden" name="CRAFT_CSRF_TOKEN" value="foSuPQ8x9UCdseO_w5LhneCQ13W9NzRqqHBWlYiq6mjTvByaFMCfPB3wtiE3MlxYPxUDNKA3eZfz0xnKvo1hh_Zwd_h609buRlnIpmHGvt3LZKYlxlMWY-X5M52pHzO53WmNsgANFbpbOGdeX40uiVM1uDgw6WwOsb16Cer_K0e3gkbaXUxnHMzEjIaRMLXVDOiakbSGJe3nBpnDBBjwycUac_Qlm2Xlh1jU-SRe1s-u_Rds0ZlZCkeKU6RkoEREsA2ZVmkDVm66bUdxt4t6ZAnD32h2HL4S8v2PyK7Wq97T57snyW98PfkHJ_Cl3qUwkYorqEKf_Fhhk9AYUgtrYQkgMweTVk-ux-p_rt-6VbfERkCbQuLl3nU9_8ID84vo-lzHEPRnLlDWnFL_zH4BgexbvoUwNXCJaE8gLwr0A8IBWvRUR4QoRPKODWW4i3MP4NMxqzhhE1OUhrqxo2bqtmiUq-2QtFzJ1jW9kWp_lbqObBzHTP8ps8o1gql9MpD9gIonJavBE1k_uzzvHpkSLIlP7jgjcmYH7hsqHI67Sic="></span>`

and when loaded from the cache:

`<span id="blitz-inject-1" class="blitz-inject"></span>`

Here's the component vue file is you need it

```
<template>
    <div>
        <div v-if="!isSubmitted">
            <form @submit.prevent="submit" id="contact-form" method="post" novalidate>

                <slot></slot>
                <div class="row">
                    <div class="form-group px-4 w-full">
                        <label for="fromName">{{ $t('contactForm.firstName') }}*</label>
                        <input type="text" class="form-control" id="fromName" v-model.lazy.trim="form.fromName" @blur="onFieldBlur('fromName')" v-bind:class="getFieldClasses('fromName')">
                        <div v-if="isErrorField('fromName')" class="error-messages">{{ $t('error.fieldRequired', { field: $t('contactForm.fromName') }) }}</div>
                    </div>

                </div>

                <div class="row">
                    <div class="form-group px-4 w-full">
                        <label for="fromEmail">{{ $t('contactForm.fromEmail') }}*</label>
                        <input type="email" class="form-control" id="fromEmail" v-model.lazy.trim="form.fromEmail" @blur="onFieldBlur('email')" v-bind:class="getFieldClasses('fromEmail')">
                        <div v-if="isErrorField('fromEmail')" class="error-messages">{{ $t('error.fieldInvalid', { field: $t('contactForm.fromEmail') }) }}</div>
                    </div>
                </div>

                <div class="row">
                    <div class="form-group px-4 w-full">
                        <label for="subject">{{ $t('contactForm.subject') }}*</label>
                        <input type="text" class="form-control" id="subject" v-model.lazy.trim="form.subject" @blur="onFieldBlur('subject')" v-bind:class="getFieldClasses('subject')">
                        <div v-if="isErrorField('subject')" class="error-messages">{{ $t('error.fieldInvalid', { field: $t('contactForm.subject') }) }}</div>
                    </div>
                </div>

                <div class="row">
                    <div class="form-group px-4 w-full">
                        <label for="message">{{ $t('contactForm.message') }}*</label>
                        <textarea
                                type="message"
                                class="form-control"
                                id="message"
                                v-model.trim="form.message"
                                v-bind:class="getFieldClasses('message')"
                                @blur="onFieldBlur('message')">
                 </textarea>
                        <div v-if="isErrorField('message')" class="error-messages">{{  $t('error.fieldInvalid', { field: $t('contactForm.message') }) }}</div>
                    </div>
                </div>
                <div class="row" v-if="isError">
                    <div class="error-messages w-full px-4">
                        <p class="mb-0">
                            <strong>{{ $t(errorHeader) }}</strong>
                        </p>
                        <ul class="mb-0 pl-3" v-if="errors.length > 0">
                            <li v-for="error in errors" v-bind:key="error.field">
                                <span v-if="error.field">{{ $t('contactForm.'+error.field) }}<span v-if="error.message">: {{ $t(error.message) }}</span></span>
                                <span v-else-if="error.message">{{ $t(error.message) }}</span>
                            </li>
                        </ul>
                    </div>
                </div>
                <submit-button labelText="Submit" v-bind:submitting="submitting"></submit-button>
            </form>
        </div>
        <div v-else>
            <div class="row">
                <div class="w-full text-center px-4">
                    <h2 class="text-center mb-4 text-blue font-bold uppercase text-3xl">{{ $t('contactForm.submitted' ) }}</h2>
                </div>
                <div class="w-full px-4 pb-8 text-center">
                    <p class="mb-4">{{ $t('contactForm.sentInfo' ) }}</p>
                    <p class="mb-6">
                        <strong>Name: </strong> {{form.fromName}}<br>
                        <strong>Email Address: </strong> {{form.email}}<br>
                        <strong>Subject: </strong> {{form.subject}}<br>
                        <strong>Message: </strong> {{form.message}}
                    </p>

                    <p class="text-center">
                        <a href="#" class="btn btn-medium btn-outline-blue" @click.prevent="reload()">{{ $t('contactForm.return' ) }}</a>
                    </p>

                </div>

            </div>
        </div>
</div>
</template>


<script src="./Contactform.js"></script>
```

**Comment by putyourlightson** [comment]
The `{{ craft.blitz.csrfInput() }}` tag should output an empty `span`, along with a `script` tag that populates the `span` tag after the completion of an AJAX request. Can you please check whether the AJAX request is working by opening the Network tab of your browser's dev tools?

**Comment by putyourlightson** [comment]
Also, the `{{ craft.blitz.csrfInput() }}` tag should generally be placed within the `form` tags. Since you are using Vue it may not be necessary, but you will need to ensure that the dynamically loaded value is submitted along with the POSTed request.

**Comment by brianrivet** [comment]
The csrfinput does get dropped inside the form tags when it loads via the slot in Vue. I checked the Network tab, the xhr request is being made, but it doesn't appear to be succeeding consistently. I did some more tests and it doesn't look like the cache being empty or not has anything to do with it. I refreshed the page a bunch of times without doing cache clears and every few refreshes the input tag would be there, but more often the span tag was empty. When it is empty, I see the following error in the console:

Uncaught TypeError: Cannot set property 'innerHTML' of null
    at XMLHttpRequest.xhr.onload

And when I check the line number it is the line where it tries to write inside of the injection span tag.

**Comment by putyourlightson** [comment]
Hmm, this inconsistency seems rather strange. Can you test it in a template that does _not_ load Vue to help narrow it down?

**Comment by brianrivet** [comment]
It looks like it is some sort of conflict either with Vue itself or with Twigpack possibly? I set up a basic template at https://myhy.sassoagency.com/formtest that doesn't use Vue or anything else and it loads the csrf input every time.

**Comment by putyourlightson** [comment]
Yeah that's what I suspected. There was someone in the Discord channel that said they had solved something similar, perhaps you can ask them about it?
