### ISSUE TITLE
Blitz Encoding Apostophes?

### ISSUE THREAD

**Issue by ryanmasuga** [putyourlightson/craft-blitz#103]
### Description
Seems Blitz is making our content look a little weird by encoding some characters - notably apostrophes and quotes. I had a user send me a note saying this page was hard to read: https://gomasuga.com/blog/deploying-craft-cms-with-gulp-deployhq-build-ssh-commands

Image:
![blitzed_content](https://user-images.githubusercontent.com/988995/57113217-96008980-6d11-11e9-8dfd-8b2cfa9c0d8c.png)

When I look at the actual html file in the Blitz cache, it appears as if the apostrophes are smart quotes:

![smart_quotes02](https://user-images.githubusercontent.com/988995/57113486-c7c62000-6d12-11e9-81e3-617070e6d3e6.png)

We're using Blitz with the htaccess server rewrite. Bottom of the page source has this comment:

`<!-- Cached by Blitz on 2019-05-02T19:29:08-04:00 -->`

Maybe this isn't a Blitz issue, but if I disable Blitz and load the page normally, it's fine.

### Steps to reproduce

1. Visit Blitz'ed page with apostrophes, see encoded characters
2. Clear Blitz cache
3. Reload page, looks file
4. Reload again (now from Blitz) and encoded characters are back

### Additional info

- Craft version: 3.1.22
- PHP version: 7.2.3
- Blitz version: 2.0.8
- Page where this is happening: https://gomasuga.com/blog/deploying-craft-cms-with-gulp-deployhq-build-ssh-commands

**Comment by ryanmasuga** [comment]
Seems that if I get rid of the htaccess RewriteRule and serve the cached page from Blitz, the quotes are fine:

`<!-- Cached by Blitz on 2019-05-02T19:53:39-04:00 --><!-- Served by Blitz -->`

I'll stick with that for now as a solution - pages are still fast.

**Comment by putyourlightson** [comment]
Can you try declaring the encoding with a `meta` element in the `head` tag? It should be near the top of the template.

```
<meta charset="utf-8"/>
```

**Comment by ryanmasuga** [comment]
Thanks Ben, adding that meta tag does fix the issue. Apparently we were not declaring that anywhere, either like `<meta charset="utf-8">` or `<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />`

I added the latter to our layout and now all the pages are caching and displaying fine using the server re-write. Thanks!
