### ISSUE TITLE
Feature Request: Permissions for cache actions (at least in CP)

### ISSUE THREAD

**Issue by mildlygeeky** [putyourlightson/craft-blitz#104]
It would be great if Craft permissions were available for the various actions on the Blitz utilities page (as sub-permissions of Access cache utility).

As is, that page can be a little overwhelming for non-developers (and even for myself, it can be hard to know the difference between Clear Cache and Flush Cache), but I do want to give them access to it in case they ever need to refresh the cache themselves.

I would love to be able to use permissions to show them just one or two options (i.e., just Refresh Entire Cache), similar to how SEOmatic or Freeform handle permissions.

**Comment by putyourlightson** [comment]
Thanks for the suggestion Patrick, I'll add it to "the list".

**Comment by putyourlightson** [comment]
Added for the 2.1.0 release in https://github.com/putyourlightson/craft-blitz/commit/b7646c7a61d06db6fb746823cae56583edf5930f

**Comment by putyourlightson** [comment]
<img width="210" alt="Screenshot 2019-07-10 at 23 02 26" src="https://user-images.githubusercontent.com/2318222/61004715-e6761200-a366-11e9-97d7-24e5a788f620.png">

**Comment by mildlygeeky** [comment]
Looks great - thanks!
