### ISSUE TITLE
Error when caching long URIs

### ISSUE THREAD

**Issue by jondialpad** [putyourlightson/craft-blitz#105]
Blitz version: 2.0.8
Craft version: 3.1.20
DB: PostgreSQL 9.6.10
PHP: 7.1.29
Nginx: 1.15.12
Debian: stretch
Running on Google App Engine in flex environment with a Docker container.

Getting the following error when I hit a URL longer than 255 characters.
`SQLSTATE[22001]: String data, right truncated: 7 ERROR: value too long for type character varying(255)
The SQL being executed was: INSERT INTO "dp_blitz_caches" ("siteId", "uri") VALUES (1, 'products/sales-dialer/?utm_source=db_talk&utm_medium=email&utm_campaign=dp_sell_launch&utm_content=productpage&mkt_tok=eyJpIjoiTm1ZME1HTTBaV00zWXpNMCIsInQiOiIxVUZKdUtsbHlrWEgyVlNPcGF5aURkOU1SS1ZPblwvRkttU1lUS2txSk5ENll6NStwNHlqcTF2djFwZk0walpwMTJYYXpWNGc0NTNZREpwZDVRaTg5aUE9PSJ9')`

I am wondering if you guys are planing to increase the character limit for URIs. The IETF states that the support for request-line lengths should be much higher than 255. (https://tools.ietf.org/html/rfc7230#section-3.1.1)

**Comment by putyourlightson** [comment]
We could indeed consider increasing the character limit for URIs. In your specific case though, I wonder if you even want to be caching URIs along with the query strings, as I assume they are used for tracking purposes only? You could change the _Query String Caching_ setting to _Cache URLs with query strings as the same page_, for example.
See https://putyourlightson.com/craft-plugins/blitz/docs#/?id=query-string-caching

**Comment by jondialpad** [comment]
We have also considered that approach as well but it didn't work well for our site as we have some pages displaying content based on the the query parameters. For a temporary workaround, we have added a rule to exclude URIs with more than 255 characters in the Blitz's exclude URI's setting.

**Comment by putyourlightson** [comment]
We'll fix the error in the next release, but I wonder what the character limit should be set to. In this case do you even want that URI to be cached? Another workaround would be to add a rule to exclude all URIs containing the `mkt_tok=` query parameter.

**Comment by putyourlightson** [comment]
Fixed for 2.1.0.
