### ISSUE TITLE
Licensing issue notification

### ISSUE THREAD

**Issue by walshmichael** [putyourlightson/craft-blitz#106]
When we sync down a database from production to another environment, the licensing issue notification displays prominently in the admin despite the plugin being disabled via the blitz.php configuration file.

A small inconvenience, however it would be nice if the plugin honoured the plugin state.

"There’s a licensing issue with the Blitz plugin."

**Comment by putyourlightson** [comment]
Could it be that you're confusing the _Caching Enabled_ setting with the plugin being disable? Setting _Caching Enabled_ to `false` doesn't actually disable the plugin, it just prevents new pages from being cached.

**Comment by walshmichael** [comment]
Absolutely, you are correct of-course.

I do understand that setting *Cache Enabled* to `false` does not disable the plugin.

Thanks.
