### ISSUE TITLE
Blitz does not cache paginated subages during cache warming

### ISSUE THREAD

**Issue by piotrpog** [putyourlightson/craft-blitz#108]
To cache paginated page i need to visit it. In "URI Pattern" setting of blitz, i have `.*`.

I sent you my project config file to info@putyourlightson.net, maybe it will help if you need to peek into my URL structure.

**My system info:**
Application Info
PHP version	7.2.12
OS version	Linux 3.10.0-862.14.4.el7.x86_64
Database driver & version	MySQL 5.5.5
Image driver & version	GD 7.2.12
Craft edition & version	Craft Solo 3.1.27
Yii version	2.0.17
Twig version	2.8.1
Guzzle version	6.3.3
Imagine version	0.7-dev
Plugins
Blitz	2.0.8
Campaign	1.9.1
Contact Form	2.2.4
Contact Form Extensions	1.1.6
Content Stats	2.1.1
Entry Instructions	1.0.4
Enupal Translate	1.2.0
Imager	v2.1.10
Image Resizer	2.0.4
Imager Pretransform	2.0.2
Position Fieldtype	1.0.14
Queue Manager	1.1.0
Redactor	2.3.3.2
Retour	3.1.14
Searchit	1.0.8
SEOmatic	3.1.50
Smart Map	3.2.2.1
Super Table	2.1.19
Typed link field	1.0.19

**Comment by putyourlightson** [comment]
That is actually the expected behaviour. When Blitz warms an empty cache, it warms all element URIs. As new pages are visited (including index pages, paginated pages, etc.), Blitz keeps track of the page URIs (provided they match the include rules). The next time the cache is refreshed or warmed, those URIs are also warmed. It's just that first time when Blitz is unable to know about every possible URL on the site that the cache will be warmed more organically. Hope that makes sense.

**Comment by piotrpog** [comment]
@putyourlightson 
I get it. But could adding pagination support be possible? Blitz would scan entry template for paginate tags, see what element is paginated, calculate number of pages.

If you have content heavy website,  paginated lists of entries could be big portion of your website. So it would be great if these pages were not excluded from caching.

**Comment by putyourlightson** [comment]
This doesn't feel like a feature that should be added as scanning templates for tags is not part of what Blitz does. An extra plugin could be built to do this, or a third-party tool to crawl the entire site could be used. But generally speaking, allowing the cache to fully warm organically the first time seems reasonable to me.

**Comment by bymayo** [comment]
I'm having this issue also. It seems that if we have a blog that shows pagination links up to 4 (1, 2, 3, 4) on the first page. It only caches these pages even if there is 8 or 20 or 40 pages of pagination.

This is causing major issues on our SEO when deploying to Netlify as redirects are happening all over the place to get to these pages.

From reading this issue, I'm unsure why warming all paginated pages is not feasible in Blitz? It seems like it does some, then why not all?

**Comment by bencroker** [comment]
@bymayo The paginated pages that are cached must have been visited in the past.

I'm reopening this issue and will look into adding support for warming paginated pages.

**Comment by bencroker** [comment]
After reviewing this, it does not seem feasible for Blitz to determine all paginated URLs. The issue stems from the fact that there is no way of knowing how many paginated pages there are. So even if there is only one page of results, `domain.com/entries/p1`, there are an infinite number of pages that will display no results, `domain.com/entries/p2`, `domain.com/entries/p3`, etc.

For the case of deploying to a static site @bymayo, I would recommend using the `Commands Before` setting in the Git Deployer to manually warm the paginated pages, for example:

```shell
for i in {1..5}; curl -s https://domain.com/entries/p$i > /dev/null;
```

Set the range `{1..5}` high enough to capture all paginated pages.

**Comment by bymayo** [comment]
Just coming back to this @bencroker as still hitting a bit of an issue with it and the range solution isn't viable.

Is it possible to maybe add a pagination option to blitz options? Similar to:

```
{% do craft.blitz.options({
    cachingEnabled: true,
    pagination: [1, 4]
}) %}
```

Then Blitz would check that same template, but for p1, p2, p3,p4 etc?

We could then make this dynamic:

```
{% do craft.blitz.options({
    cachingEnabled: true,
    pagination: [1, pagination.totalPages]
}) %}
```

**Comment by bencroker** [comment]
Please create a feature request @bymayo and we'll look into whether this would be feasible to add.
