### ISSUE TITLE
Admin version of a page gets cached

### ISSUE THREAD

**Issue by luke-nehemedia** [putyourlightson/craft-blitz#109]
Hello

I use a plugin called "AdminBar" on a clients system. In addition, there are contextual links/buttons like "Change item" on the page that are only visible for logged in users.

Sometimes, those elements get cached by the blitz plugin. 

Is there a way to ensure, that only the "public" version of the page gets cached? 

On the other hand: If a site is in the cache, the cached site is always served, also for logged in users. Is there a way to enable caching only for guests?

**Comment by luke-nehemedia** [comment]
> On the other hand: If a site is in the cache, the cached site is always served, also for logged in users. Is there a way to enable caching only for guests?

Okay, I could solve this part by disabling the rewrite rules, which is not optimal, but I guess that's necessary if I want to use these tools. 

However, the other part of the problem is still there. However, I was not able to replicate the behavior.

**Comment by putyourlightson** [comment]
You can use [Page Specific Options](https://putyourlightson.com/craft-plugins/blitz/docs#/?id=page-specific-options) to disable caching when a user is logged in, which sounds like it might solve the issue for you?

```
{% if currentUser %}
    {% do craft.blitz.options().cachingEnabled(false) %}
{% endif %}
```

You can use this in page specific templates or in layout templates to apply it to larger sections or the entire site.

**Comment by luke-nehemedia** [comment]
Thank you, that helps.
