### ISSUE TITLE
Blitz adds 404s to blitz_caches table

### ISSUE THREAD

**Issue by riasvdv** [putyourlightson/craft-blitz#11]
Every time a 404 is triggered with a new url, Blitz adds this to the blitz_caches table, as a lot of bots seem to target our website, the table grows immensely.

This also causes the cache/warm function to warm unnecessary urls.

**Comment by putyourlightson** [comment]
Fixed in https://github.com/putyourlightson/craft-blitz/commit/3b7e11ad47ae21c056690f619afb65355a6941d6
