### ISSUE TITLE
Delay cache update after Feed Me import completed

### ISSUE THREAD

**Issue by keyurshah** [putyourlightson/craft-blitz#110]
I had a large commerce products import running through Feed Me. It's taken many hours to execute and it's still going. I then see that there are many pending processes for `Refreshing Blitz Cache`.

Inside the queues table, I see over 3000 entries for the Blitz Cache Refresh (one for each product item it seems)

Wondering if running Feed Me, if the cache update can happen until the very end of the feed? I'm currently using pagination of 100 items in my feed because it's so large.

Thanks!

**Comment by putyourlightson** [comment]
You would probably want to disable Blitz (in _Settings → Plugins_) while performing imports of elements such as Commerce products, assuming it's a one off thing?

**Comment by keyurshah** [comment]
yes, i'll have to keep note of the plugins that update indexes upon update and disable before importing. this happened with seomatic as well.

I guess there's no way to know on the plugin side that the update was triggered by feed me. 

thank you.

**Comment by putyourlightson** [comment]
We'll look into whether the plugin can detect a Feed Me import and see if it can deal with that situation better.

**Comment by putyourlightson** [comment]
Added in https://github.com/putyourlightson/craft-blitz/commit/8a02d078fa74b75106cad33ee6b4f2119cc69a01, coming in 2.1.0.
