### ISSUE TITLE
Cache dynamic routes for tags/categories?

### ISSUE THREAD

**Issue by matthillco** [putyourlightson/craft-blitz#111]
Is it possible for Blitz to cache "pages" generated by a dynamic route? I send Tags and Categories to a specific template using wildcard routing, but obviously Blitz doesn't know about these. 

It would be cool if I could, for example, generate a page that displays all the available tags and categories, and get Blitz to pick up all the URLs of the generated routes within that page, then add those to the cache.

Is this possible at all? Thanks.

**Comment by putyourlightson** [comment]
Blitz caches pages based on URLs rather than templates or routes, so it will cache pages that it doesn't know about the first time they are visited and store the URLs for future warming and refreshing. Make sense?

**Comment by matthillco** [comment]
Yep, makes sense. I was just wondering if there might be a way to tell Blitz about pages it doesn't know about *before* they're visited for the first time. The reason I need this is I'm using Craft + Blitz as a kind of static-site generator, hence needing to cache all these things _before_ they're visited.

I think I can get around it though: I can remove the dynamic routes for categories and tags, and use the standard category setup (using URLs) to cache category pages. I can then replace my tags with categories instead and use the same setup. Tags are the main problem, since Craft doesn't supply a default way to create URLs for tags, so Blitz never knows about them.

**Comment by putyourlightson** [comment]
You could write a custom module/plugin to tell Blitz to cache the dynamic routes for you. If you need any help with that then please contact us directly at info@putyourlightson.net.
