### ISSUE TITLE
Suggestion: Add a configurable header to Blitz responses

### ISSUE THREAD

**Issue by michaelhue** [putyourlightson/craft-blitz#112]
It would be great to have a configurable header which is added to every response that went through Blitz.

An example use case would be service workers: I'd like to add any response from a route handled by Blitz to the service worker cache. The easiest why to identify these responses would be a custom header, for example `X-Is-Cacheable: true`. The header would be sent with every response generated by Blitz, even if the page has just been added to the Blitz cache.

The setting for this feature could look like this:

```php
return [
    'sendCustomHeaders' => [
        'X-Is-Cacheable' => 'true'
    ],

    // or simpler:
    'sendCustomHeaders' => 'X-Is-Cacheable: true'
];
```

Currently I'm using the `Cache-Control` header to identify Blitz responses but a more robust solution would be appreciated (in case the cache control changes but the service worker doesn't).

There is also the `X-Powered-By` header but it is only set for pages that are already cached (not for cache-warming requests).

I hope this isn't too confusing, let me know if there are any questions.

**Comment by putyourlightson** [comment]
Thanks for the suggestion. The `Cache-Control` header is customisable using the `cacheControlHeader` config setting, so that is something you can control and be sure that it won't change. Would this be a sufficient solution for your use case rather than introducing a new header?

    // The value to send in the cache control header.
    'cacheControlHeader' => 'public, s-maxage=0',

**Comment by michaelhue** [comment]
That's certainly possible, maybe it's just my personal need to "decouple" the headers for browser cache-control from service worker caching.

Is there a "blitz handled response" event or something similar I could use to set the header myself?

**Comment by putyourlightson** [comment]
There isn't, but we will add an event in the next release which will allow you to set your own custom headers.

**Comment by putyourlightson** [comment]
Added a `beforeOutput` event in version 2.1.0 that you can use to add any headers you wish.
https://github.com/putyourlightson/craft-blitz/blob/v2/CHANGELOG.md#210---2019-07-10

**Comment by putyourlightson** [comment]
Sample usage for reference:

```
use putyourlightson\blitz\events\OutputEvent;
use putyourlightson\blitz\services\OutputCacheService;

...

Event::on(OutputCacheService::class, OutputCacheService::EVENT_BEFORE_OUTPUT,
    function(OutputEvent $event) {
       header('X-Blitz-Cache: 1');
    }
);
```

**Comment by michaelhue** [comment]
Perfect, thank you very much!
