### ISSUE TITLE
Changes to project config not possible in read-only mode when upgrading to 2.1.3

### ISSUE THREAD

**Issue by sm9** [putyourlightson/craft-blitz#114]
I upgraded Blitz to 2.1.3 locally (as I don't use Composer, so use Beanstalk for deployments to live servers, one plugin or CMS update at a time) and this went fine. However, when I pushed this Blitz upgrade to live, I got the following error:

> Not Supported: Changes to the project config are not possible while in read-only mode.

To get around this, I had to restore my database, enable 'allowAdminChanges' and 'allowUpdates' in the config (maybe just one would have worked but I enabled both anyway), then open the control panel again to trigger the update, which worked fine this time.

If I hadn't enabled the admin changes via FTP in the config, I would have been stuck in an endless loop of Craft restoring the database, trying to upgrade, having this error, then restoring the database, etc.

The full errors are below:

> Not Supported: Changes to the project config are not possible while in read-only mode.
> 
> Migration: putyourlightson\blitz\migrations\m190525_120000_add_non_cacheable_element_types
> 
> Output:
> 
> Exception: Changes to the project config are not possible while in read-only mode. (/home/accountname/craft/vendor/craftcms/cms/src/services/ProjectConfig.php:354)
> #0 /home/accountname/craft/vendor/craftcms/cms/src/services/Plugins.php(702): craft\services\ProjectConfig->set('plugins.blitz.s...', Array)
> #1 /home/accountname/craft/vendor/putyourlightson/craft-blitz/src/migrations/m190525_120000_add_non_cacheable_element_types.php(27): craft\services\Plugins->savePluginSettings(Object(putyourlightson\blitz\Blitz), Array)
> #2 /home/accountname/craft/vendor/craftcms/cms/src/db/Migration.php(56): putyourlightson\blitz\migrations\m190525_120000_add_non_cacheable_element_types->safeUp()
> #3 /home/accountname/craft/vendor/craftcms/cms/src/db/MigrationManager.php(243): craft\db\Migration->up(true)
> #4 /home/accountname/craft/vendor/craftcms/cms/src/db/MigrationManager.php(163): craft\db\MigrationManager->migrateUp(Object(putyourlightson\blitz\migrations\m190525_120000_add_non_cacheable_element_types))
> #5 /home/accountname/craft/vendor/craftcms/cms/src/services/Updates.php(225): craft\db\MigrationManager->up()
> #6 /home/accountname/craft/vendor/craftcms/cms/src/controllers/BaseUpdaterController.php(521): craft\services\Updates->runMigrations(Array)
> #7 /home/accountname/craft/vendor/craftcms/cms/src/controllers/UpdaterController.php(208): craft\controllers\BaseUpdaterController->runMigrations(Array, 'restore-db')
> #8 [internal function]: craft\controllers\UpdaterController->actionMigrate()
> #9 /home/accountname/craft/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
> #10 /home/accountname/craft/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
> #11 /home/accountname/craft/vendor/craftcms/cms/src/web/Controller.php(187): yii\base\Controller->runAction('migrate', Array)
> #12 /home/accountname/craft/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('migrate', Array)
> #13 /home/accountname/craft/vendor/craftcms/cms/src/web/Application.php(298): yii\base\Module->runAction('updater/migrate', Array)
> #14 /home/accountname/craft/vendor/craftcms/cms/src/web/Application.php(652): craft\web\Application->runAction('updater/migrate')
> #15 /home/accountname/craft/vendor/craftcms/cms/src/web/Application.php(250): craft\web\Application->_processUpdateLogic(Object(craft\web\Request))
> #16 /home/accountname/craft/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
> #17 /home/accountname/public_html/index.php(21): yii\base\Application->run()
> #18 {main}

Also as an aside (but I haven't got all the info for this), I somehow ended up with about 4,000 tasks in the Craft Queue after upgrading. Some of these were SEOmatic sitemaps auto-generating but I think the bulk of them were Blitz tasks for warming the cache for about 200 entries, over and over again. I deleted 99% of these in the craft_queue table and let the remaining tasks run, and that seemed to fix that.

**Comment by putyourlightson** [comment]
Thank you for reporting this! We have added a fix for the project config issue in the next release.

As for the large number of tasks, Blitz added integration with SEOmatic in 2.1.0. If SEOmatic regenerates a sitemap then it will trigger to refresh the cache, which may be what you were seeing. If the issue persists then please let us know.

**Comment by mildlygeeky** [comment]
@putyourlightson I believe the massive number of Blitz refresh cache tasks has to do with 3.2 — we're seeing thousands of queue jobs for Blitz kick off as 3.2's `ConvertEntryRevisions` task runs.

**Comment by putyourlightson** [comment]
What version of Blitz @mildlygeeky? Blitz 2.1.0 introduced compatibility with drafts and revisions in Craft 3.2.

**Comment by mildlygeeky** [comment]
2.1.3 — everything works now, except the `ConvertEntryRevisions ` kicked off tens of thousands of `Refreshing Blitz Caches` jobs, to the point where our `queues` table got into the hundreds of megabytes and took down the site. Just spent 30 minutes manually deleting refresh queue DB rows, trying to keep it from going down again

**Comment by putyourlightson** [comment]
So what I'm guessing happened is that you updated Craft to 3.2 before updating Blitz to 2.1 (which itself requires Craft ^3.2.0). Since the new Blitz features were not yet in place Craft ran its migration that kicks off the `ConvertEntryRevisions`. Updating Blitz to 2.1 via composer before running the Craft 3.2 migrations should help prevent this from happening. I do apologise though, I'm sure this was frustrating!

**Comment by putyourlightson** [comment]
Added a warning to the changelog: 
https://github.com/putyourlightson/craft-blitz/blob/v2/CHANGELOG.md#210---2019-07-10

**Comment by putyourlightson** [comment]
Released version 2.0.9 (for Craft 3.1.x) which adds better handling of drafts and revisions for the update process to Craft 3.2.
https://github.com/putyourlightson/craft-blitz/blob/v2/CHANGELOG.md#209---2019-07-16

**Comment by keyurshah** [comment]
fyi, I received this error when upgrading to 2.1.5. I had to click 'restore database' and ssh into the server and change `config/general.php` and set `allowAdminChanges=true`

```
Not Supported: Changes to the project config are not possible while in read-only mode.

Migration: putyourlightson\blitz\migrations\m190525_120000_add_non_cacheable_element_types

Output:

Exception: Changes to the project config are not possible while in read-only mode.
```

**Comment by putyourlightson** [comment]
I think this might be expected behaviour in Craft and that you should update plugins only in environments where `allowAdminChanges` is enabled. See https://github.com/craftcms/cms/issues/3653.
