### ISSUE TITLE
Craft header tags don't work on cached pages

### ISSUE THREAD

**Issue by idawgik** [putyourlightson/craft-blitz#118]
We have a site where we're setting headers in the template using the Craft {% header %} tags. This is currently used to set the content-type header since the craft pages are then sent to another application that requires the content come in as a different content type.

When the page is cached, it ignores whatever was part of the set headers and always returns it as text/html. 

Is there any way this can track the assigned headers in the template and use that when returning the cached page?

**Comment by putyourlightson** [comment]
Not currently, as Blitz assumes the output will be HTML, however I see how your use-case applies. If we do add this, then Blitz will only be able to assign the correct headers on responses that it serves, meaning that using server rewrites will not be possible unless you specify the headers in the `.htaccess` file (or Nginx configuration file), which you can already do.

**Comment by idawgik** [comment]
Yeah, understand that other requests that Blitz isn't involved in would have to be handled separately. I think that's fine.

**Comment by putyourlightson** [comment]
Ok, we'll look into if and how we can make this work and give you an update when we have one.

**Comment by idawgik** [comment]
Thank you. Let me know if there's anything I can help test if/when you something implemented.

**Comment by putyourlightson** [comment]
Can you post some examples of the types of headers you are setting?

**Comment by idawgik** [comment]
Here's an example of the one we're most frequently using:

`{% header "Content-Type: application/liquid" %}`

**Comment by putyourlightson** [comment]
Thanks!

**Comment by putyourlightson** [comment]
We’ve looked into the implementation details of this and have come to the conclusion that it is not feasible to add custom headers to statically cached pages as it will add complexity and bloat. How are the contents of the cached pages being sent to the other application you mentioned. Would it not be possible to change the content-type header at that stage?

**Comment by idawgik** [comment]
Thanks for looking into this. Totally understand it not being possible.

I'll look into some other ways to accomplish this instead.

**Comment by putyourlightson** [comment]
Ok, let me know if there's any other way we can help.
