### ISSUE TITLE
Exception when running in the console.

### ISSUE THREAD

**Issue by thaoms** [putyourlightson/craft-blitz#12]
Might be related to the previous issue:

`remote: Exception 'yii\base\UnknownMethodException' with message 'Calling unknown method: yii\console\Response::getHeaders()'
`

I'm using a protocol relative url:
`'siteUrl' => '//xxxyyyyy.be/',`

**Comment by putyourlightson** [comment]
I can't replicate this, are there any other errors or anything else that might help me troubleshoot the issue?

**Comment by thaoms** [comment]
Sorry, I did read the stack trace wrong, it's a Sherlock issue.

`/vendor/putyourlightson/craft-sherlock/src/services/SherlockService.php(51): yii\base\Component->__call('getHeaders', Array)`

But doesn't matter, I wont be using Sherlock now.

**Comment by putyourlightson** [comment]
That has already been fixed in the latest version of Sherlock.
