### ISSUE TITLE
Cache is being refreshed too early during commerce checkout

### ISSUE THREAD

**Issue by stenvdb** [putyourlightson/craft-blitz#120]
I've noticed a race condition error in the cache refreshing process. I'm using commerce with the commerce-mollie plugin (all latest versions, including Craft).

When I click the pay button and get redirected to the mollie pay screen, then already the blitz command to refresh the cache is already added to the queue. But that's too soon, because the product's stock is only updated **after** the payment webhook is triggered (aka the user has paid). 

After the user has paid, and is being redirected back to the site, only then is the product's stock updated. The blitz command to refresh the cache is being triggered too early. Resulting in my products' cache not getting refreshed properly, and a user might add a product to his cart that's actually already out of stock.

**Comment by stenvdb** [comment]
I noticed in the job that the refresh is being triggered by a new order, and not even for the product.

I would say there are 2 things wrong here:

- The cache is being triggered to refresh for a new order, but before it has been marked as paid.
- Secondly, when the product's stock is updated, no new queue job is being triggered.

**Comment by putyourlightson** [comment]
Thanks for the detailed report. Blitz doesn't integrate with Commerce directly, rather it listens for changes to any element type, so we'll need to dig into the checkout process that Commerce uses and see if we can simulate it. Will give you an update when we have one.

**Comment by stenvdb** [comment]
Thanks for the quick response. What's the easiest way to refresh the entire cache via a custom module? I could build a temporary fix to clear the cache in the meantime. Because I already have some custom logic being executed when a new order is in.

**Comment by putyourlightson** [comment]
That would be as simple as calling the following:

```
Blitz::$plugin->refreshCache->refreshAll();
```

**Comment by bencroker** [comment]
I looked into this and a product's stock is determined by its variants, each of which is a Variant Element. Therefore the product's cached pages _should_ be automatically cleared when one or more of the stock values of it's variants is updated. 

Since a lot has changed in Blitz version 3, can you please let me know if this is still an issue? And did manually refreshing the cache solve the issue for you?

**Comment by stenvdb** [comment]
Hi @bencroker , yes the manual fix is working for me:

```
Event::on(Order::class, Order::EVENT_AFTER_ORDER_PAID, function(Event $e) {
    Blitz::$plugin->refreshCache->refreshAll();
});
```

I will let you know if this is still an issue in version 3 in the coming days, when I'll find some time for this 👍
