### ISSUE TITLE
Advanced Element Queries causes internal server error

### ISSUE THREAD

**Issue by jayhlee** [putyourlightson/craft-blitz#121]
Any page that has an advanced element query seems to throw an internal server error. For example, with the inclusion of `.select` method in the element query, an error is thrown using Blitz. Without the `.select` method, the page works properly.

```
{% set allServices = craft.entries()
	.section('service')
	.select('uri, elements_sites.siteId, entries.sectionId, entries.typeId, content.id, content.title')
	.orderBy('title asc')
	.all() %}
```

At the end of the day, I know that optimizing my element queries won't matter because of Blitz's caching. But it'd be nice to get advanced element queries to play nice with Blitz (in case I need to disable Blitz, so I don't have to change existing code, etc.). Any way to get this to work? Thanks!

**Comment by putyourlightson** [comment]
Thanks for reporting this, we'll look into it and let you know what we find.

**Comment by putyourlightson** [comment]
An element query must return an `id` field that represents the element ID. You are selecting `content.id` which is causing a database integrity constraint violation. Updating your query to the following should work. Can you test it and let me know?

```
{% set allServices = craft.entries()
    .section('service')
    .select('uri, elements_sites.siteId, entries.id, entries.sectionId, entries.typeId, content.id as contentId, content.title')
    .orderBy('title asc')
    .all() %}
```

**Comment by jayhlee** [comment]
Thanks, Ben! That fixed the issue.

**Comment by putyourlightson** [comment]
Excellent!
