### ISSUE TITLE
Caching Enabled Setting set from ENV 

### ISSUE THREAD

**Issue by bballenn** [putyourlightson/craft-blitz#122]
Between dev and production environments I need to constantly change this setting, as I don't allow settings changes in production.

It would be nice to have the 'Caching Enabled' setting to be set by an environment variable

**Comment by putyourlightson** [comment]
You can do this using the config file provided by Blitz, which is environment aware, for example:

```
return [
    '*' => [
        'cachingEnabled' => false,
    ],

    'production' => [
        'cachingEnabled' => true,
    ],
]
```

See the docs here: https://putyourlightson.com/craft-plugins/blitz/docs#/?id=config-settings
