### ISSUE TITLE
server rewrites and query strings

### ISSUE THREAD

**Issue by webtrend** [putyourlightson/craft-blitz#124]
I just downloaded the plugin and am playing around with it. I have a question about some settings. 

If the blitz settings is set to cache pages with unique query string as same page and I have some exclude URI patterns for certain query strings, how should I create rewrite codes in nginx?

I guess I have to add exceptions for those exclusions in the nginx config file otherwise it will serve an incorrect page.

**Comment by putyourlightson** [comment]
In theory, if the URLs are not cached then the nginx redirect will be ignored, if I understand you correctly.

**Comment by webtrend** [comment]
Oh....I see args are part of the folder structure. I somehow missed that. Thanks for your quick response.
