### ISSUE TITLE
Blitz caches HTML with urls to "generate-transform actions"

### ISSUE THREAD

**Issue by ostark** [putyourlightson/craft-blitz#125]
Hi Ben

One of our (fortrabbit) clients reported traffic spikes (10K instead of 100K requests per hour) recently. We noticed massive requests to urls like `/index.php?p=actions/assets/generate-transform&transformId={transformId}`.

When having a look at the html responses, we noticed that Blitz was the reason, since the URLs were cached.
 
The Craft `{% cache %}` prevents it actively 
https://github.com/craftcms/cms/blob/3.1/src/services/TemplateCaches.php#L272

Is this implemented in Blitz as well? Is there a setting? 
Or should the "template developer"  take care of it?

Cheers,
Oli

**Comment by putyourlightson** [comment]
Hi Oliver, as you correctly noticed, Blitz caches pages even if they contain URLs with the `assets/generate-transform` action. One workaround could be to enable the `generateTransformsBeforePageLoad` config setting, but it would probably make sense to prevent Blitz from caching such pages by default. Do you see any possible downsides to this?

**Comment by ostark** [comment]
I'm not a fan of `generateTransformsBeforePageLoad`. Async calls make much more sense.
I'd suggest preventing caching if `assets/generate-transform` is in the response body, like Craft does.

**Comment by putyourlightson** [comment]
Agreed, will look into adding this in the next release. Thanks for reporting it!

**Comment by putyourlightson** [comment]
One issue I can see is that warming the cache will not be as predictable, as Blitz currently uses Guzzle to make calls to the pages that need warming, so no AJAX requests. I'll need to consider either a workaround or maybe make this an opt-in config setting.

**Comment by putyourlightson** [comment]
Changed the behaviour in version 2.2.0 
https://github.com/putyourlightson/craft-blitz/blob/v2/CHANGELOG.md#220---2019-09-14
