### ISSUE TITLE
Option to set clearCacheAutomatically conditionally

### ISSUE THREAD

**Issue by stenvdb** [putyourlightson/craft-blitz#126]
It would be handy to set this option conditionally. For example only clear the cache automatically when entries in section 'news', 'events' or 'faq' are updated, but not when entries in section 'sitemap' is updated.

This would be handy because I work a lot with a 'pages' section that is used for site navigation. Saving an element in this section clears the entire cache (because the nav is on every page). The clearCacheAutomatically could perhaps be an array containing both the element type + options? 

The conditional options should be per element type (entries, but also commerce products, globals, ...). For entries the section's handle could be used as an extra filter. For products maybe product type. Etc.

Maybe there are better ways of achieving this? An option to exclude entry id's/slugs from clearing the cache when updated would also be very handy. WDYT?

**Comment by putyourlightson** [comment]
Since sections, product types, etc. are not easily segmented in Craft, this could be a bit tricky.

Per your use-case, surely updating a page in your site navigation section _should_ clear the entire cache, otherwise a change to the navigation would not have an affect on the site? The `clearCacheAutomatically` setting is intended to be used with cron jobs that regularly refresh expired cache.

**Comment by stenvdb** [comment]
Your right that it _should_ clear the cache, but an option to prevent certain entries from clearing the cache automatically could still be usefull I think.

Changing a nav section is something that clears the entire cache, and can benefit from having someone clear the cache manually during non peak times in the site. While sub pages can still be cleared automatically because they don't force the entire cache to be refreshed.

If it's not something that gets implemented, would there be a way to achieve this via a module?

**Comment by putyourlightson** [comment]
I think that this level of customisation is probably beyond the scope of the plugin. Also doing this via a module is not really feasible since Blitz works with `cacheIds` as well as `elementIds`, so you'd have to do a lot of reverse engineering to figure out the section or product type.

**Comment by stenvdb** [comment]
Ok well I'll go with a cron job that clears everything once a day, and turn off the clearCacheAutomatically setting then. Thanks for the input!

**Comment by putyourlightson** [comment]
Sure thing and thanks for the suggestion nevertheless!
