### ISSUE TITLE
Cache not being cleared for entries pulled in via Entry field

### ISSUE THREAD

**Issue by dhmax88** [putyourlightson/craft-blitz#127]
I have a section for Team Members, and an Entry field on a Single (Team Listing) that pulls in entries from this Team Members section. When updating an entry in the Team Members section (in this case changing its status from 'Live' to 'Disabled'), the cache of the Team Listing page is not being cleared...

Instead a user have to then go into the Team Listing entry and re-save it to force the cache to update.

**Comment by dhmax88** [comment]
The same seems to happen when re-ordering entries in a section. The queue pops up saying the cache is being cleared and warmed, but visiting the front-end, those changes aren't reflected.

**Comment by putyourlightson** [comment]
This should _not_ be the case if everything is functionaing as it should. Are you on the latest version of Blitz? Are you overriding any config settings?

**Comment by putyourlightson** [comment]
The issue turned out to be that the Element API was being used in the template rather than the `craft.entries` tag, which Blitz cannot know about.
