### ISSUE TITLE
Multiple cache components with YiiCacheStorage

### ISSUE THREAD

**Issue by michaelhue** [putyourlightson/craft-blitz#128]
## Problem

The `YiiCacheStorage` driver uses Craft's default cache component via `Craft::$app->getCache()`.
Yii allows setting up multiple caching strategies for different purposes.

> Tip: You can register multiple cache application components. The component named cache is used by default by many cache-dependent classes
> https://www.yiiframework.com/doc/guide/2.0/en/caching-data

For example, my setup uses the Memcache adapter for the default cache and a seperate database cache for larger data. Example `app.php` config:

```php
<?php
return [
	'components' => [
		'cache' => [
			'class' => yii\caching\MemCache::class,
			// ...
		],
		'dbcache' => [
			'class' => yii\caching\DbCache::class,
		],
	],
];

```

It would be great to have a config option in `YiiCacheStorage` for changing the caching component that is used.

## Solution

1. Add a `$cacheComponent` public property to `YiiCacheStorage` with initial value `'cache'`.
2. Replace every instance of `Craft::$app->getCache()` with `Craft::$app->get($this->cacheComponent)`.

**Comment by michaelhue** [comment]
I'd be happy to implement the change. Let me know if you would consider a pull request.
Thank you!

**Comment by putyourlightson** [comment]
How does this look to you? https://github.com/putyourlightson/craft-blitz/commit/961e8f7c584cf8468be07fc207381235d716eab9

**Comment by michaelhue** [comment]
Perfect, thank you!

**Comment by putyourlightson** [comment]
Great, will add in the next release.

**Comment by putyourlightson** [comment]
Added in version 2.2.0.
