### ISSUE TITLE
Cache warming and excluded URI patterns

### ISSUE THREAD

**Issue by bleepsandblops** [putyourlightson/craft-blitz#130]
Hi there,

Is the cache warming meant to skip the excluded URI patterns? As it's currently not the case it looks like... Tried in the console and in the admin area. Also tested one of those excluded pages by loading it and confirmed that it's not cached.

Seb

**Comment by bleepsandblops** [comment]
Looking in the code, I can see that the warm cache function uses getAllSiteUris which doesn't seem to take into account excluded patterns. But I'm guessing that then during the cache process it just skips those. So we're good. It's just the entries / progress number that's a bit confusing.

**Comment by putyourlightson** [comment]
It calls the `getAllSiteUris` method with the `$cacheableOnly` parameter set to `true`, so only cacheable (non-excluded) URIs should be called by the cache warming function. Can you outline the steps you are using to test this so we can look into it further?
https://github.com/putyourlightson/craft-blitz/blob/2.2.3/src/helpers/SiteUriHelper.php#L25

**Comment by bleepsandblops** [comment]
@putyourlightson correct me if I'm reading this wrong but it looks like it's not setting `$cacheableOnly` for the main site:
https://github.com/putyourlightson/craft-blitz/blob/5174e6771b7b8893beb4436d454a0f9140d00b02/src/helpers/SiteUriHelper.php#L33

**Comment by putyourlightson** [comment]
Correct you are, fixed in https://github.com/putyourlightson/craft-blitz/commit/cc7d2a0a1fe2475a3db6e01e5187e97cb9262211, thanks!
