### ISSUE TITLE
Bad request for ajax calls

### ISSUE THREAD

**Issue by focalinteractive** [putyourlightson/craft-blitz#132]
Hello,

We just purchased Blitz for a website running Craft v.3.4 Pro. Everything seems to be working fine expect for a page that has a conditional as follows:

```
{% if craft.app.request.isAjax %}
  {% include "collection/templateA" %}
{% else %}
  {% include 'collection/templateB' %}
{% endif %}
```

Blitz doesn't seem to cache calls to `collection/collection/templateA` but when caching with Blitz is turned ON the the URL https://mysite/collection/templateA returns `400` errors. 

Can you please help?

**Comment by putyourlightson** [comment]
Hi there. You cannot have a condition based on something dynamic in the request for a statically cached page. Instead I would recommend that you use separate templates for AJAX and non-AJAX requests. Alternatively, you can look into the [dynamic content](https://putyourlightson.com/plugins/blitz#dynamic-content) feature in Blitz:

**Comment by focalinteractive** [comment]
Thank you! I think I found the reason. The CSRF token wan't produced as soon as it should. I used the ajax method to request it and it was resolved.

**Comment by putyourlightson** [comment]
Great!
