### ISSUE TITLE
.htaccess rules are ignored

### ISSUE THREAD

**Issue by hiasl** [putyourlightson/craft-blitz#134]
What can be reasons that my .htaccess rules are ignored, and caching only works though Blitz serving the cached htmls? Below is my .htaccess (and pretty urls work, so I know rewriting in general is ok). All sources contain the "Served by blitz" html comment. I also tried removing the HTTPS redirect as well as the one for stamped css/js. And I did not change the path to the cached htmls, they are in <DocRoot(/web)>/cache/blitz (default). I am on Mamp Pro 5.4 using Apache.

```

<IfModule mod_rewrite.c>
    RewriteEngine On

    RewriteCond %{HTTPS} !=on
    RewriteCond %{HTTP_HOST} !^local\. [NC]
    RewriteRule ^ https://%{HTTP_HOST}%{REQUEST_URI} [L,R=301]

    # Remove timestamps from CSS/JS requests
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteRule ^(.+)\.(\d{10})\.(js|css)$ $1.$3 [L]  # /assets/build/js/scripts.1399647655.js

    #- Blitz cache rewrite
    RewriteCond %{DOCUMENT_ROOT}/cache/blitz/%{HTTP_HOST}/%{REQUEST_URI}/%{QUERY_STRING}/index.html -s
    RewriteCond %{REQUEST_METHOD} GET
    #- Required as of version 2.1.0
    RewriteCond %{QUERY_STRING} !token= [NC]
    RewriteRule .* /cache/blitz/%{HTTP_HOST}/%{REQUEST_URI}/%{QUERY_STRING}/index.html [L]

    # Send would-be 404 requests to Craft
    RewriteCond %{REQUEST_FILENAME} !-f
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_URI} !^/(favicon\.ico|apple-touch-icon.*\.png)$ [NC]
    RewriteRule (.+) index.php?p=$1 [QSA,L]
</IfModule>
```

**Comment by putyourlightson** [comment]
Are you running the latest version 2.3.3 of Blitz? Is the `Served by Blitz` timestamp changing each time you refresh the page?

Have you selected `Blitz File Storage` as the storage type in the plugin settings?

**Comment by hiasl** [comment]
- At the time when I was posting the question I was running 2.3.2 of Blitz. But I just updated to 3.3.3 and it does not make a difference
- The "Served by Blitz" timestamp changes every time I refresh.
- "Blitz File Storage" is selected and I can also see the cache files appear in the cache path.

BUT I just found the problem: Blitz is creating one additional directory layer in the cache path. This is what my directory structure looks like when at least one URL was cached by Blitz:
`web/cache/blitz/http:/<hostname here>/index.html`
So as you can see there is one dir layer for the protocol (**_http:_**)

But the .htaccess condition and rule does not have this layer, it will not look for a dir **_http:_**

So I just manually moved the <hostname> dir one level up putting it on the same layer as http:
And suddenly it works, I do not get the  "Served by Blitz" comment anymore (and everything is much faster), but I still get the "Cached by Blitz" comment, so I get a cached version.

So for some reason Blitz is considering the protocol when writing the cache or serving from the cache. I also cleared the cache again by removing everything from the cache dir and also B3.3.3 creates a directory layer **_http:_**

Any idea why?

**Comment by hiasl** [comment]
Some further observations:
- I have 9 sites in 3 groups in my Craft installation. The "http:" directory level in the Blitz cache dir only appears for sites, where the base URL does not contain a domain e.g. "/" or "/en". 
- For the sites where the base URL DOES contain a domain, e.g. "local.testdomain.com/" the "http:" will not be created and therefor the cache will work fine via .htaccess.

So it seems to be related to Craft detecting the domain itself when it is not specified in the base URL of the configured website.

**Comment by putyourlightson** [comment]
Yeah it sounds like you solved it. Blitz fetches the site's base URL, which if set to a relative URI such as `/` or `/en` cannot be correctly determined.

Out of curiosity, why would you set a site's base URL to `/`, is that not rather meaningless?

**Comment by hiasl** [comment]
OK, first the answer to your question: Let's say you have an simple website, one domain, 2 languages, main language english available at `/` and second language german available at `/de`. In this case I would configure 2 websites in Craft for the languages, primary/english with a base URL of `/` and german with a base URL of `/de`. Of course I could add the domain, but this would just blow up my website's source code whenever I use `<whatever>.url` because the domain is always prefixed if it's part of the base URL, although it's completely useless in this case (and even ugly for me).

That brings me to Blitz behavior: Why not check if a domain is present in the base URL and if not, prefix the HTTP_HOST or something like that? Or is there some technical reason to not do that? (Am I the only one not using domains in baseUrls if not necessary?)

**Comment by putyourlightson** [comment]
Using relative URLs in the site base URL sounds like it could create issues down the road. It is fine for simple web requests, but may cause issues any time Craft has to generate a URL for a different site or run any console commands (since in this case there is no web request).

The docs on the [site URL](https://docs.craftcms.com/v3/sites.html#site-url) give the following warning:
> Don’t ever use the @web alias when defining your sites’ Base URLs. It could introduce a cache poisoning vulnerability, and Craft won’t be able to reliably determine which site is being requested. 

I'm not sure if using a relative URL might introduce the same vulnerability, it may be worth asking @pixelandtonic about this. Additionally, the [UrlHelper](https://github.com/craftcms/cms/blob/3.3/src/helpers/UrlHelper.php#L622-L624) class will inject a scheme into URLs if not is defined, so it seems risky to not explicitly set this.

Blitz uses the base site URL to determine the cache folder in which to store the cached page and it looks like the UrlHelper may be adding the scheme which is throwing things off.

If you _really_ don't want the full URL in your html then you could replace it, but that seems a bit over the top:
```
{{ entry.url | replace({"http://domain.com": ""})
```

To be honest, with gzip and standard HTTP compression, having the full URL in your HTML will make only the tiniest of difference in the payload.

**Comment by hiasl** [comment]
Fair enough and thanks a lot, Ben, for your support! I already changed my baseURLs. Maybe it would be worth a warning in the plugins' settings, if the baseURL is relative, but of course that's up to you!

**Comment by hiasl** [comment]
we can close this of course.
