### ISSUE TITLE
Questions regarding craft blitz/cache/refresh-expired and /warm

### ISSUE THREAD

**Issue by hiasl** [putyourlightson/craft-blitz#135]
In our production environment we have set
`'runQueueAutomatically' => false,`
and have a Cron job handling the queue in the background.

Many times when I am logged in CP I can see that the queue is processing "Warming Blitz cache".  

1.) That makes me believe that I do not need to explicitly use the command craft `blitz/cache/warm`, since it seems to be triggered automatically. Is that correct? If yes, by what event is this triggered?
2.) According do the docs I believe that I still have to manually (cron) call `blitz/cache/refresh-expired`. Correct?
3.) If I understand correctly, calling `blitz/cache/refresh-expired` or `warm` will immediately execute this immediately and not add a job to the queue, correct? 
4) And if 3==yes, would adding a job to the queue be an option? The reason I am asking this is that I do not want to manually (cron) start too many jobs in parallel.

Thank you!

**Comment by putyourlightson** [comment]
1. A warm job is triggered after the cache is refreshed _if_ the `Warm Cache Automatically` advanced setting is switched on, which it is by default.
2. Correct, you need to manually call it or set up a cron job to do so.
3. Correct, commands run through the console execute immediately.
4. I don't believe adding a job through the console is possible. You should be able to run `blitz/cache/refresh-expired` once an hour without any issues.

**Comment by hiasl** [comment]
Thanks!
