### ISSUE TITLE
SQL Exception: : 1406 Data too long for column 'params' at row 1 The SQL being executed was: INSERT INTO `craft_blitz_elementqueries` (`index`, `type`, `params`) 

### ISSUE THREAD

**Issue by umkasanki** [putyourlightson/craft-blitz#136]
After updating the plugin, an error appeared on the pages of one of the channels

```Database Exception – yii\db\Exception
SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'params' at row 1
The SQL being executed was: INSERT INTO `craft_blitz_elementqueries` (`index`, `type`, `params`) ...
```
Craft Pro 3.3.11
Blitz 2.3.3
MySQL 5.7.25

I have sent my logs and db-backup on info@putyourlightson.net

**Comment by putyourlightson** [comment]
Thanks, the logs were very helpful. Could you please send the twig template(s) that the page that has the error uses?

**Comment by umkasanki** [comment]
Sure. Sent by mail

**Comment by putyourlightson** [comment]
Thanks, received. I see that you're using passing the element query `categoryQr` into the `relatedTo` parameter. 

```
{% set categoryQr = entry.category %}

{% set relatedEntriesQr = craft.entries({
    section: entry.section.handle,
    limit: 4,
    id: 'not ' ~ entry.id,
    relatedTo: categoryQr
}) %}
```

As per the [docs](https://docs.craftcms.com/v3/relations.html#the-relatedto-parameter), the `relatedTo` parameter can accept an element, an element ID, or an array of element objects and/or IDs. So changing to this should work:

```
{% set categories = entry.category.all() %}

{% set relatedEntriesQr = craft.entries({
    section: entry.section.handle,
    limit: 4,
    id: 'not ' ~ entry.id,
    relatedTo: categories
}) %}
```

**Comment by putyourlightson** [comment]
After looking through the `relatedTo` parameter source code, we see that it is possible to pass it an element query, even if this is not documented (and therefore not recommended). We have released version 2.3.4 which will be able to handle your template code, but for performance reasons still highly recommend you avoid process the same element query multiple times in the same template.

**Comment by umkasanki** [comment]
thanks so much

**Comment by umkasanki** [comment]
P.S.

> for performance reasons still highly recommend you avoid process the same element query multiple times in the same template.

i.e. using code like this:
```
{% set categoryQr = entry.category %}
{% if categoryQr|length > 4 %}
	{% for item in categoryQr.all() %}
		{% include 'someSnippet' %}
	{% endfor %}
{% endif %}

{% if categoryQr|length > 8 %}
	<div class="class">
		{% for item in categoryQr.all() %}
			{% include 'anotherSnippet' %}
		{% endfor %}
	</div>
{% endif %}
```
also is the bad practice?
Sorry for dummy question

**Comment by putyourlightson** [comment]
In your code you are calculating the length twice:
```
categoryQr|length
```

And fetching all categories twice:
```
categoryQr.all()
```

So in total make 4 round trips to the database, when once would be enough:
```
{% set categories = entry.category.all() %}
{% if categories|length > 4 %}
	{% for item in categories %}
		{% include 'someSnippet' %}
	{% endfor %}
{% endif %}
```

**Comment by umkasanki** [comment]
Got it. Thank you.
Have a nice day

**Comment by engram-design** [comment]
Got a similar error with using [View Count](https://plugins.craftcms.com/view-count), removing it fixed this. Fortunately, we aren't actually using the plugin anymore, but for people who are, further investigation is required.

**Comment by putyourlightson** [comment]
Thanks for the heads up Josh!

**Comment by putyourlightson** [comment]
Was that with the latest version of Blitz 2.3.4?

**Comment by engram-design** [comment]
It was with 2.3.3, but will try again with 2.3.4

**Comment by putyourlightson** [comment]
Great thanks!
