### ISSUE TITLE
Debugger Toolbar does not show

### ISSUE THREAD

**Issue by dsteinel** [putyourlightson/craft-blitz#14]
Hey,

If I enable caching on my template files, the CraftCMS debugger toolbar does not show up anymore. If I disable it, it shows again (so I know it is not an issue with my settings).

The expected behavior would be, that the CraftCMS debugger toolbar still shows after I enabled caching. 

I'm not really sure if this is a bug or if there is a workaround.

thanks in advance!

**Comment by putyourlightson** [comment]
A cached static file will never show the debug toolbar for obvious reasons. If you need the toolbar then you'll need to  disable caching.
