### ISSUE TITLE
Refreshing Blitz cache failed due to "SQLSTATE[23000]: Integrity constraint violation"

### ISSUE THREAD

**Issue by naboo** [putyourlightson/craft-blitz#140]
After deleting a set of entries I get this error from Blitz console command trying to refresh cache:

```SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'id' in field list is ambiguous The SQL being executed was: SELECT `elements`.`id`, `id` FROM (SELECT `elements`.`id` AS `elementsId`, `elements_sites`.`id` AS `elementsSitesId`, `content`.`id` AS `contentId`, `structureelements`.`structureId` FROM `elements` `elements` INNER JOIN `entries` `entries` ON `entries`.`id` = `elements`.`id` INNER JOIN `elements_sites` `elements_sites` ON `elements_sites`.`elementId` = `elements`.`id` INNER JOIN `content` `content` ON (`content`.`elementId` = `elements`.`id`) AND (`content`.`siteId` = `elements_sites`.`siteId`) LEFT JOIN `structureelements` `structureelements` ON (`structureelements`.`elementId` = `elements`.`id`) AND (EXISTS (SELECT * FROM `structures` WHERE (`id` = `structureelements`.`structureId`) AND (`dateDeleted` IS NULL))) WHERE (`entries`.`sectionId`='2') AND (0=1) AND (`elements_sites`.`siteId`='8') AND (`elements`.`archived`=FALSE) AND ((((`elements`.`enabled`=TRUE) AND (`elements_sites`.`enabled`=TRUE)) AND (`entries`.`postDate` <= '2019-11-05 06:55:22') AND ((`entries`.`expiryDate` IS NULL) OR (`entries`.`expiryDate` > '2019-11-05 06:55:22'))) OR (((`elements`.`enabled`=TRUE) AND (`elements_sites`.`enabled`=TRUE)) AND (NOT (`entries`.`expiryDate` IS NULL)) AND (`entries`.`expiryDate` <= '2019-11-05 06:55:22'))) AND (`elements`.`dateDeleted` IS NULL) AND (`elements_sites`.`enabled`=TRUE) AND (`elements`.`draftId` IS NULL) AND (`elements`.`revisionId` IS NULL) ORDER BY `structureelements`.`lft`, `entries`.`postDate` DESC) `subquery` INNER JOIN `entries` `entries` ON `entries`.`id` = `subquery`.`elementsId` INNER JOIN `elements` `elements` ON `elements`.`id` = `subquery`.`elementsId` INNER JOIN `elements_sites` `elements_sites` ON `elements_sites`.`id` = `subquery`.`elementsSitesId` INNER JOIN `content` `content` ON `content`.`id` = `subquery`.`contentId` LEFT JOIN `structureelements` `structureelements` ON (`structureelements`.`elementId` = `subquery`.`elementsId`) AND (`structureelements`.`structureId` = `subquery`.`structureId`) ORDER BY `structureelements`.`lft`, `entries`.`postDate` DESC```

**Comment by putyourlightson** [comment]
Hmm, do you have any custom element types installed? The element query appears to be doing something incorrectly by selecting the ID twice:
```
SELECT `elements`.`id`, `id`
```

**Comment by naboo** [comment]
That's strange Ben. So this section has 4 entry types, all native Craft entry types. I tried deleting one entry from a separate section with the same result:

```SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'id' in field list is ambiguous The SQL being executed was: SELECT `elements`.`id`, `id` FROM (SELECT `elements`.`id` AS `elementsId`, `elements_sites`.`id` AS `elementsSitesId`, `content`.`id` AS `contentId`, `structureelements`.`structureId` FROM `elements` `elements` INNER JOIN `entries` `entries` ON `entries`.`id` = `elements`.`id` INNER JOIN `elements_sites` `elements_sites` ON `elements_sites`.`elementId` = `elements`.`id` INNER JOIN `content` `content` ON (`content`.`elementId` = `elements`.`id`) AND (`content`.`siteId` = `elements_sites`.`siteId`) LEFT JOIN `structureelements` `structureelements` ON (`structureelements`.`elementId` = `elements`.`id`) AND (EXISTS (SELECT * FROM `structures` WHERE (`id` = `structureelements`.`structureId`) AND (`dateDeleted` IS NULL))) WHERE (`entries`.`sectionId`='2') AND (0=1) AND (`elements_sites`.`siteId`='8') AND (`elements`.`archived`=FALSE) AND ((((`elements`.`enabled`=TRUE) AND (`elements_sites`.`enabled`=TRUE)) AND (`entries`.`postDate` <= '2019-11-05 13:24:52') AND ((`entries`.`expiryDate` IS NULL) OR (`entries`.`expiryDate` > '2019-11-05 13:24:52'))) OR (((`elements`.`enabled`=TRUE) AND (`elements_sites`.`enabled`=TRUE)) AND (NOT (`entries`.`expiryDate` IS NULL)) AND (`entries`.`expiryDate` <= '2019-11-05 13:24:52'))) AND (`elements`.`dateDeleted` IS NULL) AND (`elements_sites`.`enabled`=TRUE) AND (`elements`.`draftId` IS NULL) AND (`elements`.`revisionId` IS NULL) ORDER BY `structureelements`.`lft`, `entries`.`postDate` DESC) `subquery` INNER JOIN `entries` `entries` ON `entries`.`id` = `subquery`.`elementsId` INNER JOIN `elements` `elements` ON `elements`.`id` = `subquery`.`elementsId` INNER JOIN `elements_sites` `elements_sites` ON `elements_sites`.`id` = `subquery`.`elementsSitesId` INNER JOIN `content` `content` ON `content`.`id` = `subquery`.`contentId` LEFT JOIN `structureelements` `structureelements` ON (`structureelements`.`elementId` = `subquery`.`elementsId`) AND (`structureelements`.`structureId` = `subquery`.`structureId`) ORDER BY `structureelements`.`lft`, `entries`.`postDate` DESC```

**Comment by putyourlightson** [comment]
What versions of Craft and Blitz?

**Comment by naboo** [comment]
So it's Craft 3.3.2.1 and Blitz 2.3.4. Thanks.

Den tis 5 nov. 2019 17:22Ben Croker <notifications@github.com> skrev:

**Comment by putyourlightson** [comment]
Um, 3.3.14 is the latest version of Craft...

**Comment by putyourlightson** [comment]
My previous question was about custom "element types" (as opposed to entry types) that may have been created from a module/plugin.

**Comment by naboo** [comment]
Sorry there mate, mixed the numbers. It's Craft 3.3.1.2.

No custom element types from any Plugin.

I do have a module which updates related entries whenever an entry is saved
in a specific section but this issue happens on all channels with entries
in them. It doesn't seem to happen for assets though.

Den tis 5 nov. 2019 19:20Ben Croker <notifications@github.com> skrev:

**Comment by putyourlightson** [comment]
Ok, can you please update Craft to the latest version 3.3.15 and retest so we can rule out that it is a Craft issue?

**Comment by naboo** [comment]
Hi Ben

I've updated to  Craft CMS 3.3.15 but the problem is exactly the same.

Some more info (I don't know if this does anything). I'm running in dev
with devMode on and `'cachingEnabled' => false,` but
`'clearCacheAutomatically' => true,`.

*JOHAN STRÖMQVIST*
*INTERACTIVE DIRECTOR*

Naboovalley AB
Palmaers gata 28
584 37 Linköping

*PHONE *+46 (0)70 377 13 80
*EMAIL *johan@naboovalley.com
*WWW *www.naboovalley.com

**Comment by putyourlightson** [comment]
Ok so I've tracked this down to an element query somewhere in your templates that contains `indexBy('id')` and that is throwing off the query. I've submitted a [bug report in Craft](https://github.com/craftcms/cms/issues/5216) and will wait to see what they say.

**Comment by putyourlightson** [comment]
This has been fixed in https://github.com/craftcms/cms/commit/4a9fa99ca3a088bbeed705145d6ab0d579603505!
