### ISSUE TITLE
cacheDuration setting is not getting respected

### ISSUE THREAD

**Issue by nettum** [putyourlightson/craft-blitz#141]
Howto reproduce: 
1.Get fresh install of craft, `composer create-project craftcms/craft craft_20191109`
2 Setup craft `./craft setup`
3. Install plugin, `composer require putyourlightson/craft-blitz` and `./craft install/plugin craft-blitz`
4. Enable plugin and add routes to admin:  
![image](https://user-images.githubusercontent.com/798156/68525678-52946280-02d4-11ea-883e-0973d93fdf4c.png)
5. Verify in the html that cache is working
`<!-- Cached by Blitz on 2019-11-09T00:37:42-08:00 --><!-- Served by Blitz on 2019-11-09T00:38:58-08:00 -->`
6. Set cacheDuration in `blitz.php`:
```
<?php
    return [
        'cacheDuration' => 600,
    ];
```
I did also try
```
<?php
    return [
        '*' => [
            'cacheDuration' => 600,
        ],
    ];
```
7. Flush and clear blitz cache (and all craft cache just in case). Verify that `blitz_caches`-table is empty and verify that cache timestamp is updated in template after page refresh:  
`<!-- Cached by Blitz on 2019-11-09T00:42:16-08:00 --><!-- Served by Blitz on 2019-11-09T00:43:40-08:00 -->`
8. Check expiryDate column in `blitz_caches`-table:
```
mysql> select * from blitz_caches;
+----+--------+-----+------------+
| id | siteId | uri | expiryDate |
+----+--------+-----+------------+
|  1 |      1 |     | NULL       |
+----+--------+-----+------------+
1 row in set (0.00 sec)
```

Craft CMS Pro trial 3.3.15
Blitz trial 2.3.4
PHP 7.3.11

**Comment by putyourlightson** [comment]
Thank you for the excellent bug report, fixed in https://github.com/putyourlightson/craft-blitz/commit/acdf17829e93a890d7117f627cd647fb4e00052e which will be available in the next release.
