### ISSUE TITLE
Using Blitz with Country Redirect plugin

### ISSUE THREAD

**Issue by twosixcode** [putyourlightson/craft-blitz#142]
Hi, we were hoping to use Blitz on a Craft 3 site, but we are finding that it interferes with the Country Redirect plugin. 
https://superbig.co/plugins/country-redirect
https://github.com/superbigco/craft-countryredirect

We use Country Redirect to redirect a user to a localized version of the Craft site based on the user's IP address (IP to nation functionality). For example, if a user is visiting https://example.com/ with an IP address that is from Singapore, the user is redirected to https://example.com/en-sg. Each site has its own base URL (eg, the Australian site is https://example.com/en-au).

This redirect behavior works fine when Blitz is disabled. But when Blitz is enabled, the country redirect stops working and all users are served the default (English) site at https://example.com/

Do you expect Blitz to be incompatible with Country Redirect?

Do you have any suggestions for what to try so that we can use Blitz and Country Redirect together on the same site?

Please let me know if I can provide more specific information.

Thanks!

**Comment by bencroker** [comment]
Hi Alex. Being a full page static caching plugin, Blitz will indeed output cached versions of your pages before the Country Redirect plugin has had a chance to initialise and perform the redirect.

What you could perhaps do, is use [banner prompts](https://superbig.co/plugins/country-redirect#banner-prompts) to prompt visitors to their matching locale instead of redirecting them. You would load this from another template using the [dynamic content](https://putyourlightson.com/plugins/blitz#dynamic-content) tags that Blitz provides. 

If automatically redirecting the user if important, then perhaps you could achieve it using Javascript on page load using the [visitor information](https://superbig.co/plugins/country-redirect#visitor-information) tags.

Maybe @superbigco has some other ideas as well?

**Comment by bencroker** [comment]
Alternatively, if you are comfortable creating a simple module/plugin then you could take advantage of the `OutputCacheService::EVENT_BEFORE_OUTPUT` event in Blitz to perform the country redirect _before_ outputting the cached page.

**Comment by sjelfull** [comment]
Hey Alex,

There is an undocumented feature that makes it possible to pull in the redirect & banner info with JS.

```javascript
fetch('/country-redirect/info?currentUrl=' + currentUrl + '&currentSiteHandle=' + currentSiteHandle).then(response => {
    response.json().then(json => {
        if (json.banner) {
            
        }
    });
}).catch(error => console.log);
```

This is the method a client of mine is using with Blitz. They use it to prompt the user to go to the relevant country page.

**Comment by twosixcode** [comment]
Thanks for the replies, Ben and Fred!

Good to have confirmation that this is the expected behavior. And, yes, if we decide to use Blitz and let go of the automatic redirection feature, that's pretty much the route we are considering, but did not want to go down that road if there were other options. Thanks again!

**Comment by twosixcode** [comment]
Oooh! I missed your reply there, Ben, where you said

> Alternatively, if you are comfortable creating a simple module/plugin then you could take advantage of the OutputCacheService::EVENT_BEFORE_OUTPUT event in Blitz to perform the country redirect before outputting the cached page.

That is great to know! No problem to create a module if that is an option.

**Comment by bencroker** [comment]
Great, it looks like calling [`maybeRedirect()`](https://github.com/superbigco/craft-countryredirect/blob/v2/src/services/CountryRedirectService.php#L59) might be the way to do it.
```
CountryRedirect::$plugin->countryRedirectService->maybeRedirect();
```

**Comment by twosixcode** [comment]
@bencroker I'm finally getting a chance to revisit this. I'm using this in a custom module
```
Event::on(OutputCacheService::class, 
     OutputCacheService::EVENT_BEFORE_OUTPUT,
     function($event) {
        CountryRedirect::$plugin->countryRedirectService->maybeRedirect();
     }
);
```
Which is working, but it seems to only be called on the first request before the page is cached. After that page is cached with Blitz I do not see this event firing again. Is that the case?

For this to be a solution I'd need to evaluate each request for possible redirection prior to serving up the cached page. Can I do that with this Blitz event?

Looking at the latest version of Blitz, it seems like I should use the `EVENT_BEFORE_GET_RESPONSE` event. Is that right? And would this event fire on every request, giving me a chance to evaluate and redirect if needed before Blitz serves the cached page?

**Comment by bencroker** [comment]
Yup, `EVENT_BEFORE_GET_RESPONSE` is the event you want in the current version of Blitz:
https://github.com/putyourlightson/craft-blitz/blob/3eee542d2d12fb13dfbf0e444c87f045eda908cc/src/services/CacheRequestService.php#L235

**Comment by twosixcode** [comment]
Thanks @bencroker  It does indeed fire the code in my custom module when that event is triggered. But it only fires once! When the page is uncached. The code in my module is never triggered again until I clear the Blitz cache. Is that the expected behavior? I need to run this redirection check on each request.

**Comment by bencroker** [comment]
You won't be able to use additional caching methods such as [server rewrites](https://putyourlightson.com/plugins/blitz#server-rewrites) or a reverse proxy such as Cloudflare set to cache HTML, since you need the request to reach the Craft script.

**Comment by twosixcode** [comment]
> You won't be able to use additional caching methods such as server rewrites or a reverse proxy such as Cloudflare set to cache HTML

We're not using either of those.

Should the `EVENT_BEFORE_GET_RESPONSE` event be triggered each request? It only seems to be triggered once, the first time an uncached page is requested. Then never fires again until I clear the cache.

**Comment by bencroker** [comment]
It looks like the `maybeRedirect()` method returns a `Response` or `false`, so you may need to do something like this to force the redirect.

```php
Event::on(CacheRequestService::class, CacheRequestService::EVENT_BEFORE_GET_RESPONSE,
     function (ResponseEvent $event) {
         $response = CountryRedirect::$plugin->countryRedirectService->maybeRedirect();

         if ($response) {
             $response->send();
         }
     }
);
```

**Comment by twosixcode** [comment]
Thanks @bencroker I believe it _was_ in fact the server rewrites interfering. The EVENT_BEFORE_GET_RESPONSE fires on every request now. Thanks!

**Comment by bencroker** [comment]
Glad to hear it!
