### ISSUE TITLE
Need help to have craft.blitz.getTemplate() working

### ISSUE THREAD

**Issue by LouisCuvelier** [putyourlightson/craft-blitz#144]
### Question
I have 3 questions about craft.blitz.getTemplate()

1. In definitive, does it support hidden templates ? #129 
2. Can I add params to the template included, as mentioned in [this issue](https://github.com/putyourlightson/craft-blitz/issues/129#issuecomment-528595366) ?
3. I tried to use it but I'm having an error 500 returned in the JS console. The code I'm using is this : `{{ craft.blitz.getTemplate('includes/_equipmentsList') }}`

**Comment by bencroker** [comment]
Hi Louis,

1. Yes, this was added in version [2.3.0](https://github.com/putyourlightson/craft-blitz/blob/develop/CHANGELOG.md#230---2019-10-05).
2. This functionality is coming very soon in Blitz 3.
3. Is there any error message in the console? Turning on `devMode` might help to troubleshoot this.

**Comment by LouisCuvelier** [comment]
Hi Ben,

I was already in `devMode` and there's no more error.

The only error that the JS console shows is :
`GET https://xxxxxx.test/actions/blitz/templates/get/?template=d54e2420577593b810d94ed1a7ab58ac91c39646efd933e4fb42acf0406d42a1/includes/_equipmentVotes.twig&params[equipmentId]=503 500`

File structure is : 
```
templates
├── includes
│   └── _equipmentVotes.twig
└── fileCallingGetTemplate.twig
```

**Comment by bencroker** [comment]
Have you updated to version 3?
https://putyourlightson.com/plugins/blitz#craft.blitz.gettemplatetemplate-name-params

**Comment by LouisCuvelier** [comment]
Yup !
Can this be the same kind of issue that encountered in the past ? Something related with trailing slash ? See [here](https://github.com/doublesecretagency/craft-starratings/issues/8#issuecomment-462994020)

Maybe a misconfiguration with NGINX ?

**Comment by bencroker** [comment]
Can you show me your template code as it is now?

**Comment by LouisCuvelier** [comment]
I identified that the problem come from my included template.
Something is messing up with [Upvote](https://github.com/doublesecretagency/craft-upvote) because when I remove mentions of upvote, It just works fine.

```twig
{{ craft.blitz.getTemplate('/includes/_equipmentVotes.twig', { equipmentId: equipment.id }) }}
```

File included :
```twig
{% do craft.upvote.disable(['css']) %}
{% do craft.upvote.setIcons({
    up   : '<i class="fas fa-thumbs-up fa-fw"></i>',
    down : '<i class="fas fa-thumbs-down fa-fw fa-flip-horizontal"></i>',
}) %}

{{ craft.upvote.upvote(equipment.id)|retconChange(".upvote-vote", "button")|retconAttr(".upvote-upvote", {class: "vote vote-upvote"}, false) }}
<div>{{ craft.upvote.tally(equipment.id) }}</div>
{{ craft.upvote.downvote(equipment.id)|retconChange(".upvote-vote", "button")|retconAttr(".upvote-downvote", {class: "vote vote-downvote"}, false) }}
```

**Comment by bencroker** [comment]
It's important to consider that the `craft.blitz.getTemplate` outputs JavaScript that fetches the template with an AJAX call and injects it into a `div` using `innerHTML `. The Upvote tags output `<script>` tags which are being injected into the `div` node and therefore not executing.

 > HTML5 specifies that a <script> tag inserted with innerHTML should not execute.

Source: https://developer.mozilla.org/en-US/docs/Web/API/Element/innerHTML

There doesn't seem to be any obvious way to make this work, although there are lots of [suggestions](https://stackoverflow.com/questions/2592092/executing-script-elements-inserted-with-innerhtml). The way I think of this is, should a page that contains vote counts really be statically cached? It seems like a very _dynamic_ type of page to me. Could it be excluded from caching using a URI pattern or page specific option?

**Comment by bencroker** [comment]
Alternatively, since the Upvote tags output JavaScript anyway, why not leave them in the template being cached? I realise that the vote counts needs to be dynamic but perhaps there is a way that you can pull them in using an AJAX call?

**Comment by LouisCuvelier** [comment]
Yes, this is what a tried to explain [here](https://github.com/doublesecretagency/craft-upvote/issues/13), but I had no clear response ...

**Comment by bencroker** [comment]
The tags are documented here: 
https://www.doublesecretagency.com/plugins/upvote/docs/getting-vote-totals

**Comment by LouisCuvelier** [comment]
Oh thank you !
