### ISSUE TITLE
Blitz Git Deployer keeps deleting my Netlify "_redirects" file

### ISSUE THREAD

**Issue by cmalven** [putyourlightson/craft-blitz#147]
### Describe the bug
I'm using the Git Deployer to deploy a site to Netlify. As a part of that setup, I've manually created and committed a `_redirects` file to the static repo. The next 1-3 auto deploys via Blitz work as expected, but inevitably there will be a future commit where Blitz will delete this file as a part of its `Blitz auto commit`.

I've also manually added a `.gitignore` in the same way and this file has never been deleted by Blitz.

The file was originally created directly in the static repo on the server where Blitz is running, but I've also tried creating it through Github and had the same issue.

### Versions
- Plugin version: 3.0.1
- Craft version: 3.3.18.1

**Comment by bencroker** [comment]
The Git Deployer should not delete any files that were not created by Blitz. Can you check the commit history of your repo and look at the details of the commit in which the `_redirects` file was deleted? Does anything stand out about it? Perhaps a screenshot would help in troubleshooting.

**Comment by cmalven** [comment]
I wanted to make sure I'd looked into everything possible in my setup before responding to this, but I'm still seeing the issue, even after blowing away the repo and recreating the `_redirects` file multiple times.

I'm not seeing anything obviously strange about the Blitz removal commits other than the deleted `_redirects`. I'm attaching a screenshot of the latest removal commit.

Here are the Blitz `Commands Before` I'm using to copy certain files over prior to commit:

```
cp -r /srv/users/serverpilot/apps/nehbc/web/dist /srv/users/serverpilot/apps/nehbc/static-repo/;
cp -r /srv/users/serverpilot/apps/nehbc/web/favicons /srv/users/serverpilot/apps/nehbc/static-repo/;
```

I appreciate any suggestions you have for additional places to look. Thanks!

![blitz-commit](https://user-images.githubusercontent.com/610118/71315068-53173180-241a-11ea-9016-c4b7bc018c2e.png)

**Comment by bencroker** [comment]
The only time the entire cache folder is cleared is when the clear/refresh utility, controller action or console command is run. Are you ever running one of these two commands?

What you could do, to ensure that the `_redirects` file remains intact, is store it somewhere else and add another command to copy it into the repo:
```
cp /srv/users/serverpilot/apps/nehbc/web/_redirects /srv/users/serverpilot/apps/nehbc/static-repo/_redirects;
```

**Comment by cmalven** [comment]
Yes, I'm running `blitz/cache/refresh` during non-static deployments, to ensure that the static deployment gets the latest Templates/JS/CSS/Etc from the codebase.

So that's almost certainly what's happening. I'll move the redirects file into the non-static codebase and copy it over as you suggested. Thanks @bencroker

**Comment by bencroker** [comment]
Ok, great!
