### ISSUE TITLE
Per url setting for Query String Caching setting would be nice

### ISSUE THREAD

**Issue by johnwbaxter** [putyourlightson/craft-blitz#148]
I have a site that outputs a lot of products (just entries) onto one page that I want cached (not a craft commerce site) and there is a js driven filter thing that lets the user choose options that match data-foo type attributes on each product. As you select your filter options, it adds to the URL i.e example.com/products?size=large&height=tall but it doesn't actually refresh the page.

So, what the client likes to do is to send out URL's to customers which have all these options pre-loaded in the URL and when the page is visited, the js sees the params and applies the filters. The get params *do not* modify the underlying twig code at all.

On a different part of the site, in the blog section, users can filter the blog by clicking on categories that are driven with query strings i.e example.com/blog?category=foo and I would want these query string pages to be cached.

I *think* I would want different query string caching config options for either....however, I'm still mulling over that in all honesty!

**Comment by bencroker** [comment]
It sounds like you want to set the [Query String Caching](https://putyourlightson.com/plugins/blitz#query-string-caching) setting to `Cache URLs with query strings as the same page` for the `products` page and to `Cache URLs with query strings as unique pages` for the `blog` page. What seems apparent is that you are using query strings for different things on different pages – for JavaScript filtering in the former and for Twig filtering in the latter. 

The approach that I would probably take is to switch the `blog` page to use URI segments for filtering. That way you will end up with prettier URLs that more precisely match how filtering works in the templates, so `example.com/blog/foo` and `example.com/blog/bar` for example. This requires setting up a [dynamic route](https://docs.craftcms.com/v3/routing.html#dynamic-routes) for `blog/{slug}` and updating your templates accordingly.

How does that sound?

**Comment by johnwbaxter** [comment]
Hey Ben, yeah, i certainly could do that, it's a site we took over, so we're not able to change url's right now, but certainly it's something I'm going to look at! Thanks for coming back to me :)

**Comment by bencroker** [comment]
Ok great! I realise that if Blitz had the ability to set the setting based on the URL that it would save you a bit of time, but it doesn't seem like a feature that would really bring much value to the plugin. Thanks for the suggestion and let me know if you run into any issues with the implementation.
