### ISSUE TITLE
How does blitz determine cacheable content?

### ISSUE THREAD

**Issue by webtrend** [putyourlightson/craft-blitz#149]
### Question
Where does Blitz gets the URLs for cacheable content when we issue cache warming command?

### Additional context
I am asking this question because on our site many URLs are not detected even when they were part of previous version of cache and we try to refresh the cache. Is it using sitemap? Is there a way to upload the sitemap content directly into Blitz?

**Comment by bencroker** [comment]
Initially, Blitz will look for all elements that have URIs and warm them based on their URLs. As other pages in the site are visited, Blitz will keep track of them in the database and include them when warming the cache. 

As of version 3.0.0, it is possible to add custom site URIs in the `Cache Warming` tab which will be also be included when warming the entire cache. This can also be populated with the `customSiteUris` config setting:

```
return [
    'customSiteUris' => [
        [
            'siteId' => 1,
            'uri' => 'pages/custom',
        ],
    ],
]
```
