### ISSUE TITLE
Scheduled Posts do not seem to be purged/deployed in CloudFlare

### ISSUE THREAD

**Issue by MattWilcox** [putyourlightson/craft-blitz#150]
### Describe the bug
When an Entry with a Post Date in the future should be published, the page does not become publicly available, even when the CRON task runs and reports a success.

Running the CRON task manually will also report a success, but does not result in a public page - eg;

`/usr/bin/php /home/PROJECT/craft/craft blitz/cache/refresh-expired`
Expired Blitz cache successfully refreshed.

Refreshing the URL at which the new post should be available results in 404.

### Setup
The local servers .htaccess is NOT using the settings to punt pages to the HDD cache.

### Plugin Settings
Caching Enabled
URI Pattern: .*
Cache Storage: Blitz File Storage
Folder Path: @webroot/cache/blitz
Cache Warming: Guzzle
Concurrency: 3
Reverse Proxy Purger: Cloudflare Purger
Zone ID, Email, Global API Key: all provided
Warm Cache Delay: 5
Clear Cache Automatically: ON
Warm Cache Automatically: ON
Query String Caching: Do not cache URLs with query strings

### Cloudflare Page Rules
PROJECTURL/index.php?p=secretadmin* (Cache Level: Bypass)
PROJECTURL/secretadmin* (Cache Level: Bypass)
PROJECTURL/* (Cache Everything, Edge Cache TTL: 2hrs)

### Versions
- Plugin version: 3.0.1
- Craft version: 3.3.18.2

### Sidenote
Utilities > Blitz > Refresh Cache
does seem to work and result in the page being visible on the front end.

**Comment by bencroker** [comment]
Can you look inside the `blitz_elementexpirydates` database table? It should contain all elements that have a future post or expiry date. If any are missing then run the console command and check again:
```
./craft blitz/cache/generate-expiry-dates
```

**Comment by MattWilcox** [comment]
It does contain one element, and the correct expiryDate.

**Comment by MattWilcox** [comment]
This just worked. Twice. It hadn't all day.

Must have been something I'd cleared up earlier, or perhaps the system needing to work through a bunch of background tasks. 

This was from a single "save Entry"...
<img width="404" alt="Screen Shot 2019-12-17 at 11 57 27" src="https://user-images.githubusercontent.com/814039/71016350-f4d21200-20ec-11ea-930f-9f05637260b0.png">

This project was an older install that we updated the other day, and this morning it had been making huge repeating queues of jobs when saving a page (they all completed, it was just a full screen of tasks every time I saved a single page, and the issue of not publishing pages on a schedule). Since then I've killed the htaccess, manually cleared out the cache folder, etc. I've poked around at a lot. Maybe it's caught up.

Sorry Ben, this appears to be working as it should now.

**Comment by MattWilcox** [comment]
Huh. But deleting two test pages has not worked right. One is now a 404, correctly. The other is not.

in one step I deleted both test pages, and only one has gone from the front end.
https://burghley-horse.co.uk/scheduled-publication is now a 404.
https://burghley-horse.co.uk/scheduled-publication-2 should be 404 now as it no longer exists. But it's not 404ing. CloudFlare is serving the page still.

**Comment by bencroker** [comment]
It looks like something is not quite right with your 404 pages...
https://burghley-horse.co.uk/404
<img width="843" alt="Screenshot 2019-12-17 at 18 49 12" src="https://user-images.githubusercontent.com/57572400/71021111-ef30f800-20fd-11ea-862a-e87b9039f4fb.png">

**Comment by MattWilcox** [comment]
Ah, the developer who built most of this had the 404 template but not a 404 Entry in the CMS. I've now created that - though the 404 page was already throwing a 404 header so I'm confused if there is anything here that would impact Blitz/Cloudflare from turning what was a working URL into a 404 URL because pages were deleted.

I see that the second URL is (this morning) properly a 404.

### Another test

I've just done a new test where I had two pages set to publish at 9:30am, the CRON job runs at 9:31 so both pages should become visible around 9:35 at the latest... Those both worked. I then waited a minute and deleted both... neither page was removed from the front end after Blitz's queues had finished and an additional minute elapsed. Same result trying to load both of the now deleted URLs on a different browser. They seem to stay in the CF cache. The next time the CRON job ran (9:46), they were still visible. ( https://burghley-horse.co.uk/test-schedule-one and https://burghley-horse.co.uk/test-schedule-two )

**Comment by bencroker** [comment]
What is `Browser Cache TTL` set to in the _Cloudflare > Caching_ tab? It should ideally be set to `Respect Existing Headers`. To ensure that Blitz is sending the correct headers, add this to a `blitz.php` config file:
```
return [
    // The value to send in the cache control header.
    'cacheControlHeader' => 'public, s-maxage=31536000, max-age=0',
];
```

Once that's done, refresh the entire cache and that should hopefully resolve the issue.

**Comment by bencroker** [comment]
Anything still not working @MattWilcox?

**Comment by MattWilcox** [comment]
Sorry Ben, only just seen this - will test...

**Comment by MattWilcox** [comment]
It was set to 30m... that may have been the problem. I'll see how this does once things have taken... Thanks Ben!

**Comment by MattWilcox** [comment]
Hi Ben, thanks - that seems to have fixed the issue.
