### ISSUE TITLE
Inject cart Button into blitz template

### ISSUE THREAD

**Issue by kaspar-allenbach** [putyourlightson/craft-blitz#152]
### Question

Is it possible to inject dynamic twig code?
```
<a class="commerceBtn overalCart" href="{{ url('shop/cart') }}">
	<i class="fa fa-shopping-cart"></i>
	({{ craft.commerce.carts.cart.lineItems|length }})
</a>
```

Is it possible to inject this with the [Template Params](https://putyourlightson.com/plugins/blitz#craft.blitz.gettemplatetemplate-name-params)?

### Additional context
I'm fiddling around with Blitz. It is super cool so far.

I wonder if it is possible to inject dynamic twig code into the templates still?
I have an example of a cart button which shows dynamically how many items there are currently in the cart:

![Bildschirmfoto 2019-12-27 um 21 51 02](https://user-images.githubusercontent.com/762213/71532379-510a1280-28f3-11ea-8dc0-6021387d43d4.png)

I don't understand how to do this with ajax. Is it possible to do this in twig somehow?

**Comment by bencroker** [comment]
This is exactly what dynamic content tags are for:
https://putyourlightson.com/plugins/blitz#dynamic-content

You can put the dynamic code in a template and then have it injected dynamically, for example:

```twig
<a class="commerceBtn overalCart" href="{{ url('shop/cart') }}">
	<i class="fa fa-shopping-cart"></i>
	{{ craft.blitz.getTemplate('cart/items') }}
</a>
```

The `cart/items` template would only contain this:
```twig
({{ craft.commerce.carts.cart.lineItems|length }})
```
