### ISSUE TITLE
How to best invalidate cache on a per page basis

### ISSUE THREAD

**Issue by kaspar-allenbach** [putyourlightson/craft-blitz#153]
### Question
How do I best create a setup for invalidating a cached page in a regular interval
(And then warm it again)?

I thought about putting a tag on said page like this:

`{% do craft.blitz.options().cacheDuration('P1D').tags(['newsletter']) %}`

- Does this override settings in the blitz.php config?
- If I add `'warmCacheAutomatically' => true,` does this warm the entire site or just those pages who are invalidated? (In this case the newsletter page)

### Additional context

I have a newsletter subscription page where I also have some entries which are loaded randomly:

`{% set randomShopEntry = craft.products.orderBy('RAND()').limit(4).all() %}`

So I'd like those to be changed on a regular basis.

**Comment by bencroker** [comment]
Using [page specific options](https://putyourlightson.com/plugins/blitz#page-specific-options), you can either set `cacheDuration` or `tags` and refresh using one of the [console commands](https://putyourlightson.com/plugins/blitz#console-commands) with a cron job set at regular intervals.

Using `cacheDuration`:
```twig
{# This page will automatically expire after 1 day #}
{% do craft.blitz.options().cacheDuration('P1D') %}
```

set up a cron job to refresh expired pages:
```
./craft blitz/cache/refresh-expired
```

OR

Using `tags`:
```twig
{% do craft.blitz.options().tags(['newsletter'])%}
```
set up a cron job to refresh tagged pages:
```
./craft blitz/cache/refresh-tagged newsletter
```
