### ISSUE TITLE
Remote deployment not working with gitRepositories using env variables/aliases in blitz.php

### ISSUE THREAD

**Issue by zsackett42** [putyourlightson/craft-blitz#155]
### Describe the bug
When using ```deployerSettings``` in ```blitz.php```, all env variables seem to be represented through the control panel correctly, except those associated with "Git Repositories". Blitz will successfully warm the cache, and log "Blitz cache successfully queued for deployment.", but the cached files are not copied to the repository path. The issue is the same whether using ```@alias``` or ```getenv('VARIABLE')``` syntax for ```gitRepositories``` settings.

Without using ```deployerSettings``` in ```blitz.php```, but using the same settings saved through the plugin control panel instead, the deployment will queue, copy the correct files, and push successfully.

### To reproduce
Steps to reproduce the behaviour:
1. Configure ```gitRepositories``` in ```blitz.php``` with env variables or aliases
2. Refresh cache
3. Blitz warms cache, queues for deployment, but never copies files or pushes 

### Expected behaviour
Expect "Git Repositories" to inherit the correct blitz.php data, and complete a full deployment.

### blitz.php configuration
```php
<?php

return [
    // All environments
    '*' => [
        'cacheFolderPath' => 'cache/blitz',
        'refreshCacheAutomaticallyForGlobals' => true,
        'clearCacheAutomatically' => true,
        'warmCacheAutomatically' => true,
        'includedUriPatterns' => [
            [
                'uriPattern' => '.*',
            ],
        ],

        // The deployer type to use.
        'deployerType' => 'putyourlightson\blitz\drivers\deployers\GitDeployer',

        // The deployer settings.
        'deployerSettings' => [
            'gitRepositories' => [
                'site-uid-1' => [
                    'repositoryPath' => getenv('STATIC_REPO_PATH'),
                    'branch' => 'master',
                    'remote' => 'origin',
                ],
            ],
            'commitMessage' => getenv('BLITZ_COMMIT_MESSAGE'),
            'username' => getenv('GIT_ACCOUNT_USERNAME'),
            'personalAccessToken' => '@gitAccountUserToken',
            'name' => getenv('BLITZ_COMMIT_NAME'),
            'email' => getenv('EMAIL_SYSTEM_EMAIL_ADDRESS'),
            'commandsBefore' => 'rsync -avzhL --safe-links ' . realpath(dirname(__DIR__)) . getenv('BASE_PATH') . 'uploads' . ' ' . getenv('STATIC_REPO_PATH') . ' && ' .
                                'rsync -avzhL --safe-links ' . realpath(dirname(__DIR__)) . getenv('BASE_PATH') . 'resized/uploads' . ' ' . getenv('STATIC_REPO_PATH') . '/resized' . ' && ' .
                                'rsync -avzhL --safe-links ' . realpath(dirname(__DIR__)) . getenv('BASE_PATH') . 'css' . ' ' . getenv('STATIC_REPO_PATH') . ' && ' .
                                'rsync -avzhL --safe-links ' . realpath(dirname(__DIR__)) . getenv('BASE_PATH') . 'fonts' . ' ' . getenv('STATIC_REPO_PATH') . ' && ' .
                                'rsync -avzhL --safe-links ' . realpath(dirname(__DIR__)) . getenv('BASE_PATH') . 'favicon' . ' ' . getenv('STATIC_REPO_PATH') . ' && ' .
                                'rsync -avzhL --safe-links ' . realpath(dirname(__DIR__)) . getenv('BASE_PATH') . 'icon' . ' ' . getenv('STATIC_REPO_PATH') . ' && ' .
                                'rsync -avzhL --safe-links ' . realpath(dirname(__DIR__)) . getenv('BASE_PATH') . 'img' . ' ' . getenv('STATIC_REPO_PATH') . ' && ' .
                                'rsync -avzhL --safe-links ' . realpath(dirname(__DIR__)) . getenv('BASE_PATH') . 'js' . ' ' . getenv('STATIC_REPO_PATH') . ';',
        ],
    ],

    // Production (live) environment
    'live' => [
        'cachingEnabled' => true,
    ],

    // Staging (pre-production) environment
    'staging' => [
        'cachingEnabled' => true,
    ],

    // Local (development) environment
    'local'  => [
        'cachingEnabled' => false,
    ],
];
```
Repository path format for reference:
```env
STATIC_REPO_PATH="/home/forge/static.website.net"
```

### Versions
- Plugin version: 3.0.3
- Craft version: 3.3.18.4
- PHP version: 7.2.20

**Comment by bencroker** [comment]
In your environment, have you changed `site-uid-1` to the site's actual `UID`? It should look like `2c712e86-4aa7-4294-a69e-f6f554e01435` and you can find it either in the `sites` database table or in the `project.yaml` file.

**Comment by zsackett42** [comment]
Yes, I've tried it with the site's correct uid; same behavior.

**Comment by bencroker** [comment]
So just to clarify, the `Git Repository` settings are not appearing in the control panel at all when using the config settings?

**Comment by zsackett42** [comment]
That's correct, sorry for any confusion with the description. All other settings appear correctly according to the config file.

**Comment by bencroker** [comment]
I cannot replicate this behaviour locally, so can you please do the following:

1. Comment out the config settings.
2. Add the settings in the CP and save.
3. Look for `gitRepositories` in the `project.yaml` file and compare the values to the config settings.

My guess is that the site `UID` is incorrect, but you said you already checked that, so I'm not sure.

**Comment by zsackett42** [comment]
I was hoping it would be something simple I missed like this. In the `blitz.php` config I was using the format "site-uid-xxxx" literally. I didn't realize to remove the "site-uid-" prefix, but I see in the `project.yaml` it saves out as the `UID` only.

Thanks @bencroker! Closing this as it's not actually a bug.

**Comment by bencroker** [comment]
Excellent!
