### ISSUE TITLE
Does the Warmer show up in Google Analytics

### ISSUE THREAD

**Issue by kaspar-allenbach** [putyourlightson/craft-blitz#156]
### Question
Since the Guzzle warmer does send a get request is it possible that these requests show up in Google Analytics?

### Additional context
I've just launched a web page and the clicks are insane. This is very unlikely after 24h of the launch. So I'm suspecting the cache warmer which I triggered a few times over the whole site counts towards the analytics metrics

**Comment by bencroker** [comment]
Not likely, since a page view in Google Analytics is triggered by a Javascript event, which the Guzzle warmer would not execute. Do the geolocations or timestamps of the visits reveal anything about the metrics?

**Comment by kaspar-allenbach** [comment]
I use [Instant Analytics](https://plugins.craftcms.com/instant-analytics) from nystudio107.
This plugin does not track via the classic google js snippet but it uses the Google measurement protocol. I don't know how it works but js is not involved like this. 

I thought maybe I see some sort of url string from blitz in the analytics panel. But to be honest I haven't jet figured out where to find the origin of each request.

**Comment by kaspar-allenbach** [comment]
Okay I'm pretty sure it does count.

If I hit Refresh cache:

![Bildschirmfoto 2020-01-04 um 16 32 36](https://user-images.githubusercontent.com/762213/71767774-19612300-2f10-11ea-90da-55ffe751ab9d.png)

Then in Analytics Realtime view the count shoots up in an instant:

![Bildschirmfoto 2020-01-04 um 16 33 39](https://user-images.githubusercontent.com/762213/71767782-2da52000-2f10-11ea-8435-98ee13c29e6f.png)

Is there some warming url available

**Comment by bencroker** [comment]
You can disable automatic cache warming in the plugin settings (under Advanced) if you want to avoid it affecting your analytics.

**Comment by kaspar-allenbach** [comment]
No, I find that feature great. Is there an identifiable blitz warming URL?
Then it would be easy to filter out the blitz traffic.

**Comment by bencroker** [comment]
I could add a header tag to requests that come from the Guzzle warmer but I’m not sure if Instant Analytics provides a way of excluding requests based on headers. Perhaps @nystudio107 can weigh in here?

```twig
{% if craft.app.request.getHeaders()->get('X-Blitz-Warmer') is null %}
    {% do myAnalytics.sendEvent() %}
{% endif %}
```

**Comment by bencroker** [comment]
Added a `X-Blitz-Warmer` header to cache warming requests in 3.1.0:
https://github.com/putyourlightson/craft-blitz/blob/develop/CHANGELOG.md

**Comment by kaspar-allenbach** [comment]
This line

`{% if craft.app.request.getHeaders()->get('X-Blitz-Warmer') is null %}`

returns 

> Unexpected token "operator" of value ">"

why?

**Comment by kaspar-allenbach** [comment]
I  think it should be like this, no?

```
{% if craft.app.request.getHeaders().get('X-Blitz-Warmer') is null %}
  {% hook 'iaSendPageView' %}
{% endif %}
```

testing this stuff is pretty hard.

**Comment by bencroker** [comment]
Yes, sorry, I switched between the Twig and PHP formats :)

**Comment by bencroker** [comment]
Although you’ll most likely want to check that it `is not defined`.

**Comment by kaspar-allenbach** [comment]
So, after testing 🙈 testing 🙈 testing this is the code:

```
{% if craft.app.request.getHeaders().get('X-Blitz-Warmer') is null %}
  {% hook 'iaSendPageView' %}
{% endif %}
```
thank you for your help 🎉

**Comment by bencroker** [comment]
Great! Testing is hard :)
