### ISSUE TITLE
Error when defining includedUriPatterns and/or excludedUriPatterns in configfile after upgrade from v2 to v3

### ISSUE THREAD

**Issue by nettum** [putyourlightson/craft-blitz#157]
### Describe the bug
Not really a bug, but since the blogpost about blitz v3 says "Blitz 3 contains no breaking changes" I think this is worth mentioning:
If you used a configfile to define uri patterns in v2 as described here: https://github.com/putyourlightson/craft-blitz/blob/3c71195b8f61f8e25173a7f48228bda41b3c5596/src/config.php#L25-L28  
you will now need to change this to the v3 format, as described here: https://github.com/putyourlightson/craft-blitz/blob/6b1387379c7e9d0eefe6ac57d68d06cc3b7d706d/src/config.php#L29-L46  
  
If not, you will get the following error:  
`[error][yii\base\ErrorException:8] yii\base\ErrorException: Undefined index: uriPattern in .../vendor/putyourlightson/craft-blitz/src/services/CacheRequestService.php:253`  
   
I got that error at least and had to do the following changes to the config:  
![image](https://user-images.githubusercontent.com/798156/71818159-797ad500-3088-11ea-948e-793b63b85491.png)
 
Can't seem to find any information about this on https://github.com/putyourlightson/craft-blitz/blob/develop/CHANGELOG.md#300---2019-12-10

Apart from that, the upgrade went smooth :tada: 

### Versions
- Plugin version: 3.0.3
- Craft version: 3.3.19

**Comment by bencroker** [comment]
You're right Marius. The migration process converted the URI pattern setting values in the database, but if you had a config file then those would have to be converted. 
Next time I'll be sure to document this better :)

**Comment by engram-design** [comment]
@bencroker For future reference, I think its worth updating the changelog to mention this change. Didn't get caught out with this, because I looked at the updated sample config, but I enjoy reading through changelog's for changes.

**Comment by bencroker** [comment]
Thanks for the feedback @engram-design, added to the changelog so it doesn't trip anyone else up.
https://github.com/putyourlightson/craft-blitz/blob/develop/CHANGELOG.md#300---2019-12-10
