### ISSUE TITLE
How does cache busting work with import of data from custom plugin?

### ISSUE THREAD

**Issue by johnwbaxter** [putyourlightson/craft-blitz#158]
So, we have a custom plugin on a site that consumes a json feed every 30 minutes and adds new entries to one section and then deletes any existing entries that aren't currently in the json feed form that section.

It's holiday package deals in the feed for reference. 

So there could potentially be 500 changes every 30 minutes. What would Blitz do in this scenario? Would it bust the cache each time the plugin adds a new entry and then try and rewarm the cache? So 500 times potentially within a few seconds?

The site also has content added/changed in other sections by the staff, so normal cache busting stuff would need to go on everywhere else.

Thanks!

**Comment by bencroker** [comment]
Since this is your own custom plugin, you can do the following:

```php
// Before processing the feed
Blitz::$plugin->refreshCache->batchMode = true;

// Process the feed

// After processing the feed
Blitz::$plugin->refreshCache->refresh();
```

This will enable `batchMode` before processing the feed, which forces Blitz to wait until the `refresh` method is manually called until refreshing the cache. In other words, only a single refresh cache job will be created even if 500 elements are updated.

Alternatively, you could create an integration for Blitz, like the [FeedMeIntegration](https://github.com/putyourlightson/craft-blitz/blob/develop/src/drivers/integrations/FeedMeIntegration.php). Here is some sample code.

```php
<?php
namespace my\plugin\namespace\integrations;

use putyourlightson\blitz\Blitz;
use putyourlightson\blitz\drivers\integrations\IntegrationInterface;
use yii\base\Event;

class MyPluginIntegration implements IntegrationInterface
{
    public static function getRequiredPlugins(): array
    {
        return [];
    }

    public static function registerEvents()
    {
        Event::on(MyPlugin::class, MyPlugin::EVENT_BEFORE_PROCESS_FEED,
            function() {
                Blitz::$plugin->refreshCache->batchMode = true;
            }
        );
        Event::on(MyPlugin::class, MyPlugin::EVENT_AFTER_PROCESS_FEED,
            function() {
                Blitz::$plugin->refreshCache->refresh();
            }
        );
    }
}
```

You would then add the integration to Blitz in the `blitz.php` config file:

```php
return [
    // The integrations to initialise.
    'integrations' => [
        'my\plugin\namespace\integrations\MyPluginIntegration',
    ],
];
```

**Comment by johnwbaxter** [comment]
Hey Ben, that's really really awesome!!

Thank you!!

Is there any real difference between methods 1 and 2?

Method 1 looks brilliant to me, but can go with either depending on the pro's and con's if there are any?

Thanks :)

**Comment by bencroker** [comment]
I'd go with method 1 if this is a custom plugin that you don't plan on distributing.

I've documented this here, thanks for the nudge :)
https://putyourlightson.com/plugins/blitz#integrations

**Comment by johnwbaxter** [comment]
That's awesome, thanks so much Ben, I'm super stoked with this!! :D

**Comment by bencroker** [comment]
Great, let me know if you run into any issues.
