### ISSUE TITLE
Warm cache in background and when complete replace existing cache files?

### ISSUE THREAD

**Issue by johnwbaxter** [putyourlightson/craft-blitz#159]
Hey Ben,

Is it possible with Blitz, that when the cache needs to be cleared and then warmed, that it actually just warms a new cache file(s) in the background, and then when that new cache has been built, it atomically replaces the existing cache files so that a user never gets served an uncached page?

**Comment by bencroker** [comment]
This is possible with atomic deployment setups such as Netlify, but that requires setting up Netlify as your hosting environment and using the Git deployer:
https://putyourlightson.com/plugins/blitz#remote-deployment

To do it with a regular LAMPstack setup is not possible.

**Comment by bencroker** [comment]
If you have cache warming enabled then the chances of a user actually hitting an uncached page are very slim. That first visit would also cache the page, so it would happen to at most one visitor.

**Comment by johnwbaxter** [comment]
It's a fairly high traffic site, so I was just trying to avoid that chance as much as humanly possible. We can at least try it and see how it goes! Thanks!
