### ISSUE TITLE
Admin page gets cached sometimes

### ISSUE THREAD

**Issue by riasvdv** [putyourlightson/craft-blitz#16]
We have a site where the admin page gets cached sometimes. So `https://example.com/admin` returns the homepage.

It seems to be because `https://example.com/index.php` gets cached, which then results in all requests to there returning the homepage. We do have a rule setup to just cache everything with then some exceptions.

I've added it manually in the exceptions now, but it might be something you could solve in the plugin somehow?

**Comment by putyourlightson** [comment]
Ok will look into it, thanks for posting.

**Comment by putyourlightson** [comment]
I've been unable to figure out why this might be happening. A call to `https://example.com/index.php?p=admin` does not return the cached version of `https://example.com/index.php` in my tests. Any idea as to what might be causing it in your specific case?

**Comment by riasvdv** [comment]
So I don't know *why* this happens, but the `blitz_caches` will get a row in it with `/index.php` as the url.

After this one is cached, it seems like our apache decides that everything that accesses `/index.php` or a variation of it with query parameters, gets served the cached html version.

Adding a rule to exclude `index.php` solves it for us.

**Comment by putyourlightson** [comment]
Ah yes, with `mod_rewrite` I'm now seeing this too.

**Comment by putyourlightson** [comment]
So the issue is that `mod_rewrite` ignores the query string. I will add an exception for `/index.php` to the plugin, but I'm wondering whether query strings should be cached at all. If they are then each of the following URLs will be cached in a separate file:

    https://example.com/page?x=1
    https://example.com/page?x=2
    https://example.com/page?x=3

Which could lead to a huge number of files being generated. Since Craft uses an appended string for pagination (`http://example.com/news/p2`), I'm considering disregarding the query string completely. Any thoughts?

**Comment by riasvdv** [comment]
I'd keep the query string personally as we use it on some sites to filter things like categories, which would still benifit greatly from caching.

**Comment by putyourlightson** [comment]
Ok, I'll need to modify the `mod_rewrite` code in that case then.

**Comment by putyourlightson** [comment]
This should work, can you please test on your end too?

```
RewriteCond %{REQUEST_METHOD} GET
RewriteCond %{DOCUMENT_ROOT}/cache/blitz/%{HTTP_HOST}/%{REQUEST_URI}%{QUERY_STRING}/index.html -f
RewriteRule .* /cache/blitz/%{HTTP_HOST}/%{REQUEST_URI}%{QUERY_STRING}/index.html [L]
```

**Comment by putyourlightson** [comment]
That should actually solve your `index.php` caching issue too.

**Comment by riasvdv** [comment]
Seems to work! Thanks for helping out :)

**Comment by putyourlightson** [comment]
Great, thanks for helping troubleshoot!!

**Comment by putyourlightson** [comment]
FYI there's a new setting in 1.5.0 that you'll want to enable and update your `mod_rewrite` as described in the docs: 
https://github.com/putyourlightson/craft-blitz#server-rewrite
