### ISSUE TITLE
Exclude URI pattern does not work on url parameters

### ISSUE THREAD

**Issue by webtrend** [putyourlightson/craft-blitz#162]
I would like to use the option "Cache URLs with unique query string as same page" with a few exceptions.

I tried to enlist these exceptions in exclude URI pattern list for example `q=.*`

However, it seems like these patterns are not being applied to the query string. So I am forced to use "Cache URLs with unique sting as unique pages" which is not efficient at all. 

Is there a better alternative?

**Comment by bencroker** [comment]
What is your use-case for wanting to be able to create exceptions?

Have you considered using [page specific options](https://putyourlightson.com/plugins/blitz#page-specific-options) to achieve this? For example:

```twig
{# Disable caching if a query string exists #}
{% if craft.app.request.get('q') %}
    {% do craft.blitz.options.cachingEnabled(false) %}
{% endif %}
```

**Comment by webtrend** [comment]
oh...I did not know that I could disable in twig template. That should work.
Basically for search pages, I am passing the search parameter via URL so I cannot use cached page for such cases.

**Comment by bencroker** [comment]
Right, in that case you should exclude the search results page either using the method above or an exclude URI pattern.
