### ISSUE TITLE
Caching clearing and warming doesn't seem to be working

### ISSUE THREAD

**Issue by philipzaengle** [putyourlightson/craft-blitz#163]
I'm having trouble with cache being cleared after an entry is saved.

**Things I've looked at:**
- I've enabled debugging in the blitz.php config file, but I don't see any messages regarding the caching being cleared/invalidated or warmed after save. The only way to get blitz to log events is to visit a page with the debug toolbar enabled or run one of the blitz utilities.
- Files are being written to `cache/blitz` and then served via Nginx just fine
- There are lots of records in my blitz_* tables

**Env details that could be relevant:**
- The blitz cache location is being set via a symbolic link 
cache/blitz -> public/cache/blitz
- The queue is being run by a daemon 
- env: staging

Any ideas?

could be related to #160

**Comment by bencroker** [comment]
Are `Clear Cache Automatically` and `Warm Cache Automatically` enabled under _Advanced Settings_? 
Does refreshing the URL in the _Blitz Utility_ clear and warm the cached page?

**Comment by philipzaengle** [comment]
Yes, both of those are set via config variables to `true`. I've also confirmed they are set to on in the CP.

Yes, clearing the URL in the Blitz Utility clears and warms the page.

**Comment by bencroker** [comment]
Let's see if we can narrow down the issue a bit. Can you test the following scenario?

1. Visit an entry that has its own URL so the cached `.html` file is generated in `cache/blitz` and note the date modified. 
2. Check that the entry ID exists in the `blitz_elementcaches` table. You can also check if the corresponding URI exists in the `blitz_caches` table if you like.
3. Update the entry in the CP and look for a _Refreshing Blitz Cache_ queue job. 
4. Check if the file's modified date was changed in in `cache/blitz`.

**Comment by philipzaengle** [comment]
Done.

- I see the html file with a cache date of yesterday. 
- Confirmed that element is in the `blitz_elementcaches` table
- Update the entry, the queue job runs
- checked the raw HTML file on the server, still old date. 

If I go to the blitz utility and clear the url the file gets burned and warmed.

**Comment by philipzaengle** [comment]
Clues!

on line ~107 of `RefreshCacheJob.php` I added a log:
```php
if (empty($this->cacheIds)) {
            Blitz::$plugin->log("No Cache Ids Found");

            return;
        }
```

After I saved my entry that message was written to the file.

the queue job looks like this 
```
O:42:"putyourlightson\blitz\jobs\RefreshCacheJob":6:{s:8:"cacheIds";a:0:{}s:8:"elements";a:1:{s:20:"craft\elements\Entry";a:2:{s:10:"elementIds";a:1:{i:0;s:1:"2";}s:9:"sourceIds";a:1:{i:0;s:1:"1";}}}s:10:"clearCache";b:1;s:11:"description";N;s:30:"
```

which is referencing the correct elements/entry_id.

**Comment by bencroker** [comment]
Ok, so can you double check that the entry ID exists in the `blitz_elementcaches` table and that the corresponding URI exists in the `blitz_caches` table, after the page has been cached?

Also, is this a multi-site setup? What version of Blitz are you running?

**Comment by philipzaengle** [comment]
Yes, the entry ID is in the `blitz_elementcaches` table, and it matches an entry in `blitz_caches` -- however, the uri is blank because the page I'm testing is the homepage. I've also tested the /about page which results in the string `about` in the `URI` column.

**Comment by philipzaengle** [comment]
This is a single site, running blitz 3.1.1 and Craft 3.3.20.1

**Comment by bencroker** [comment]
Tested locally with Blitz 3.1.1 and Craft 3.3.20.1 and I cannot replicate. This line should fetch the `cacheIds` affected by the `elementId`, perhaps you can add some debug code there to narrow it down? Otherwise you can email me access credentials and I'll be happy to take a look.
https://github.com/putyourlightson/craft-blitz/blob/3.1.1/src/jobs/RefreshCacheJob.php#L57-L60

**Comment by philipzaengle** [comment]
I added a load of logging to the `FileStorage` class and the thing I've got it narrowed a little more... Narrowed down all the way to an empty `.env` value for `@web` ... when `@web` wasn't being set it was falling back to an auto-detected url... 🤦‍♂ 🤦‍♂ 🤦‍♂ 🤦‍♂ 

**Things I learned:**
1. It appears that some of the jobs may not actually be async as the system was able to delete uris using the blitz utility. The queue should not have been able to find the files it needed to delete, maybe the paths are somehow pre-processed? 

2. I found this by adding logging to the `FileStorage` class to output that path for every write, check and read. I instantly noticed the discrepancy in the `write` location vs the `read` or `check` locations used in the queue. 

3. Sometimes fallback configurations are a bad thing

**Comment by philipzaengle** [comment]
@bencroker -- thanks for bearing with me as I stumble around pretending to be a developer 😉

**Comment by bencroker** [comment]
Ah of course! I should have spotted it when you said:
> The queue is being run by a daemon

That is why it worked using the Blitz utility but not a queue job!!

See the warning about avoiding the use of `@web` here:
https://docs.craftcms.com/v3/sites.html#creating-a-site
