### ISSUE TITLE
Using Blitz with 'Ajax' page loads

### ISSUE THREAD

**Issue by jamielaughton** [putyourlightson/craft-blitz#164]
### Question
My site uses XMLHttpRequest to load each page. 

Blitz is currently only caching the requested page content used through the request (e.g without header, footer, css, js etc) so when i reload the page it is only serving the content of the page.

Is there a setting i am missing to fix this?

Cheers,
Jamie

**Comment by bencroker** [comment]
> My site uses XMLHttpRequest to load each page.

Can you expand on this a bit? Are you using Twig templates to generate pages?

**Comment by jamielaughton** [comment]
Thank you for the incredibly fast reply.

I am using:

{% extends (craft.app.request.isAjax and not craft.app.request.isLivePreview) ? "_skeleton-layout" : "_layout" %}

To recognise how the page is loaded. 

If the page is loaded using the nav or any other internal links an Ajax request will be triggered through JS, TWIG will recognise the page is loading via AJAX and extend the skeleton layout, replacing only the page content. If the page is refreshed or loaded using the browser it will trigger the full layout including all css, js, headers etc.

When i navigate using internal links Blitz is only caching the content using the skeleton layout. 

Thinking about it a bit more i can understand this may be a fairly complex issue to workaround as the caching would have to be dependent on how the page is loaded.

**Comment by bencroker** [comment]
Blitz statically caches pages based on thier URI and once cached (whether with the skeleton or regular template), the Twig tags on the page will _not_ be parsed again. It sounds like you might be using a dynamic approach to loading statically cached pages, so you'll need to keep this in mind. 

My suggestion would be to use a different set of templates for your skeleton layouts as for your regular layouts (you should be able to use includes to avoide code duplication), which should avoid the issue you are experiencing.

**Comment by jamielaughton** [comment]
Thanks again. I understand what you're saying.

That sounds like a reasonable approach. I'll set up a directory for skeleton and reg with includes pointing to the twig files which i currently use for both. I'll let you know if i run into any issues.

Cheers,
Jamie

**Comment by bencroker** [comment]
Great, good luck!

**Comment by bkmorse** [comment]
@jamielaughton I am running into the same issue. Did you ever resolve this? If so, could you explain? Thank you.

**Comment by jamielaughton** [comment]
@bkmorse Honestly, i gave up after a few go's due to tight deadlines. I'm now just using the cache tag and Eager Loading which his working fine for now. Sorry i cannot be of any help.

**Comment by bencroker** [comment]
There is a related PR that is currently in review which may help you both: https://github.com/putyourlightson/craft-blitz/pull/184
