### ISSUE TITLE
Caching works only for the primary site on a multisite setup

### ISSUE THREAD

**Issue by luke-nehemedia** [putyourlightson/craft-blitz#166]
I am testing blitz right now for a new client and have used it on two other sites for quite a while. Until now without major problems. 

This time, however, the site has multiple languages with multiple domains. I have et it up to include all urls of the 3 main languages (by choosing the site and entering `.*`. I have excluded some sites that include forms. I also added the Rewrite rules to the .htaccess file. 

![screen1](https://user-images.githubusercontent.com/7863273/73584581-a2309780-4499-11ea-9a0a-fe14eb90fe30.png)

I visited the site on multiple devices and clicked on "warm cache." As a result, it cached the first language, but left the other sites untouched. 

![screen2](https://user-images.githubusercontent.com/7863273/73584617-d2783600-4499-11ea-8fdb-a146511c40fc.png)

**I tried a couple of things:**
- loggin in into the CP on the other domains
- using the cronjob/console
- added a custom URI of one of the translated pages to settings  → cache warming
- flushing and warming the cache over and over again

However, I could not get the plugin to cache the other language versions.

Any idea how to solve this?

### Versions
- Plugin version: 3.1.1
- Craft version: 3.4.1 and still after updating to 3.4.2

**Comment by bencroker** [comment]
First check the [common issues](https://putyourlightson.com/plugins/blitz#common-issues) and if you don't find a solution there then enabling the [debug config setting](https://putyourlightson.com/plugins/blitz#debugging) should help you figure out why pages are not being cached.

**Comment by luke-nehemedia** [comment]
Thanks for the answer. I already went through the **common issues**, but nothing helped.

Enabling the **debug setting** results in messages stating, that...
`Page not cached because it does not match an included URI pattern.`

However, as stated above, _everything_ is included in the URI pattern. I also removed the exceptions temporarily, which did not resolve the problem. 

I have tried out a couple of other things:
- changing the include patterns to `All sites => .*` works for all but one site. However, I do not want to cache all sites, but only three of them.
- changing the pattern to `*` did not help

**Comment by bencroker** [comment]
What is the base URL set to in the site settings for the secondary site? Is it an absolute URL? Can you compare it to the exact URL in the log file message?

**Comment by luke-nehemedia** [comment]
The base URLs of the secondary sites are all absolute URLs set via the CP, not via environmental variables etc. 

They do match exactly the URLs given in the Log-file.

**Comment by bencroker** [comment]
Ok, can you send the log file to info@putyourlightson.net and we'll take a closer look?

**Comment by luke-nehemedia** [comment]
I just mailed the log-files and screenshots (without blacked-out parts) of the Blitz-Settings and Site-Settings.

**Comment by sarahschuetz** [comment]
I have the same/similar Problem. Only the primary site gets cached when prewarming. However, single pages of all sites are cached when visited.

Plugin version: 3.1.0
Craft version: 3.3.18.2

**Comment by bencroker** [comment]
@sarahschuetz Have you tried enabling the [debug config setting](https://putyourlightson.com/plugins/blitz#debugging) and what is the result of the log?

**Comment by bencroker** [comment]
Also, is the base URL in the site settings for the secondary site an absolute URL? Please ensure that you are not using `@web` (without defining it explicitly).

**Comment by bendesilva** [comment]
I was also similar experiencing issues with Blitz on a multi-site website yesterday, but instead it was returning stale cached versions for pages, and whatever I did I wasn't able to clear the cache for the localised site.

I realised the issue was with my config settings as I was using a relative path ('folderPath' => 'cache/blitz') as per the v2 config file. There seemed to be a discrepancy between the files being stored in the web root for the primary site (/web/cache/blitz/example.com) and the web root for the localised site (/web/zh-hans/cache/blitz/example.com/zh-hans). After changing this to an absolute folder path rather than relative in the config via an ENV variable (e.g. /home/user/example.com/web/cache/blitz) it appeared to work as expected and all cached files were being stored in the primary web root rather than in any additional sites' web root. It seems the v3 config now uses ['folderPath' => '@webroot/cache/blitz'].

It could be because I'm using a nested web root for the localised site that this occurred in the first place, it may not be the case for separate web roots, or multi site where there's a single web root.

Not sure if that's applicable for any other cases here, but that certainly helped my issue. FYI the above config was seemingly working fine for a while until I recently updated Blitz.

**Comment by bencroker** [comment]
@bendesilva Thank you for your input. You're right that the folder path was changed from a relative path to an absolute path , so in version 3 it should be `@webroot/cache/blitz` or similar.

The update migration from v2 to v3 automatically added the `@webroot` prefix to the folder path, but the setting probably got overwritten when you performed a more recent update to Blitz and saved the settings with the old  folder path value set in your config file.

I'm not sure if this is the same issue that @luke-nehemedia and @sarahschuetz are facing, but it would be worthwhile double checking.

**Comment by sarahschuetz** [comment]
@bencroker sorry, for my late response and thank you for your effort. I just had time to review the issue again and came up with the following results:

- I had a relative path for my folder path indeed, I now changed it to `@webroot/blitz/cache`
- Prewarming when visiting pages (of all sites) works fine
- Prewarming via Utilities doesn't work at all (Queue is startet, but runs through very quickly without producing any html files)
- Prewarming via console works for primary site, for all other sites the blitz logs a template not found message
- My site urls are set via custom aliases like `@baseUrl` and resolve to `http://xxx.test/`, `http://xxx.test/r/`, `http://xxx.test/en/r` etc.

**Comment by sarahschuetz** [comment]
Here is an excerpt of the logs:
```
2020-02-11 11:15:48 [][][debug] Template not found: c/datenschutzbestimmungen
2020-02-11 11:15:48 [][][debug] Template not found: c/termine-und-preise-1
2020-02-11 11:15:48 [][][debug] Template not found: c/anmeldebestaetigung-ausbildungsplatz
2020-02-11 11:17:16 [][][debug] Page not cached because it matches an excluded URI pattern. [http://xxx.test/csrf/]
2020-02-11 11:20:50 [][][debug] Page not cached because it matches an excluded URI pattern. [http://xxx.test/csrf/]
```

**Comment by bencroker** [comment]
@sarahschuetz where exactly are you defining `@baseUrl` for the various sites? Can you show the specific code sample?

**Comment by sarahschuetz** [comment]
@bencroker the aliases are defined in `config/general.php`:
```
'aliases' => [
            '@baseUrl' => getenv('SITE_URL'),
            '@baseUrlEn' => getenv('SITE_URL') . 'en/',
            '@baseUrlB2b' => getenv('SITE_URL') . 'r/',
            '@baseUrlB2bEn' => getenv('SITE_URL') . 'en/r/',
            '@baseUrlxxxDe' => getenv('SITE_URL') . 'c/',
            '@baseUrlxxxEn' => getenv('SITE_URL') . 'en/c/',
        ],
```
... and `SITE_URL` in my `.env` file is:
```
SITE_URL="http://xxx.test/"
```

**Comment by bencroker** [comment]
That looks good @sarahschuetz. Can you send the log file (be sure to enable the debug config setting first), detailing what URL specifically is not being warmed, to info@putyourlightson.net and I'll take a closer look? If you are able to send login credentials then that would be helpful too.

**Comment by bencroker** [comment]
Please test using the Guzzle warmer, which is the recommended warmer. The Local warmer is not as stable for multi-site setups.

**Comment by sarahschuetz** [comment]
@bencroker Thanks for all your help. Using Guzzle Warmer all our multi-sites are cached now 🎉

**Comment by bencroker** [comment]
Great, glad to hear it!

**Comment by luke-nehemedia** [comment]
Hello again

I am very sorry to answer that late, but due to personal circumstances I wasn't able to work on this project in the meantime. 

Sadly enough, the problem is still there.

Some stuff I have tried with regard to the conversation:
- I am using the Guzzle warmer
- I have installed version 3 (no update from version 2). The path is correctly set in the settings to `'cacheStorageSettings' => ['folderPath' => '@webroot/cache/blitz']`
- Also in the overview it shows the folder paths nicely for each url: `webroot... /cache/blitz/  domain`
- I am using a single webroot for all the sites, so the webroot is defined via the site settings, not the .ENV
- when I set "folderPath" to the absolute path (instead of `@webroot/...`) and then warm the cache, it caches the main site (as supposed to), not the other language versions (which is should cache) and it caches a secondary site, for which caching is _not_ enabled! Even when I explicitly put that site into the exclude rules. Really strange! 
- using the "local Warmer" instead of Guzzle: Only pages from the main site are cached after they are visited. All other sites are not cached.

I have really no idea why it behaves so strange. On all other sites it works just fine. However, none of the other ones is a multisite.

**Comment by bencroker** [comment]
@luke-nehemedia Please email credentials to the site to info@putyourlightson.net and we'll take a closer look.

**Comment by luke-nehemedia** [comment]
You should have received the credentials now.

**Comment by luke-nehemedia** [comment]
Latest update solved the issue! Thank you!

**Comment by belkin** [comment]
@bencroker I have the same problem on multisite setup. Blitz caching is enabled and 'Included URI Patterns' left empty only to cache the homepage. It caches only the primary website but not the other websites. I've tried with `.*` but no difference there.

`Craft version: 3.4.27`
`Blitz version: 3.8`

Urls are generated via .env file and general.php.
ENV:
`BASE_URL="https://local.page.com/"`
general.php:
`'aliases' => [
            'baseUrl' => trim(getenv('BASE_URL'), '/'),
],`

![image](https://user-images.githubusercontent.com/3419659/115668489-740dd080-a347-11eb-8f44-066f57036024.png)

When I enable the debug mode then I'm just getting:
`2021-04-22 08:41:43 [][6][debug] Page not cached because it does not match an included URI pattern. [https://local.page.com/nl]`

**Comment by bencroker** [comment]
@belkin this issue is closed and over a year old. Please create a new issue with some more details/screenshots of your settings and we'll take a look.
