### ISSUE TITLE
How to not cache some optional display?

### ISSUE THREAD

**Issue by scandella** [putyourlightson/craft-blitz#169]
### Question
Hi,
I have a footer menu on a website where some links are displayed only for any Craft's user logged.
`{% if currentUser %}`
The footer appears on all the web site pages.
How can I use Blitz for caching if this element can't be cached?
Do I have to use your "Dynamic content" technic or the "Page Specific Options" ? 
I'm confused.
Thanks for your help.

**Comment by bencroker** [comment]
Yes, you'll want to use [Dynamic Content](https://putyourlightson.com/plugins/blitz#dynamic-content) tags to inject a template, and in that template you can use `{% if currentUser %}` or any other non-cached tags.

**Comment by scandella** [comment]
Thanks for your answer.
So I try to use:
`{{ craft.blitz.getTemplate('/partials/myTemplate' ) }}`

And I get a:
`GET http://localhost:8888/actions/blitz/templates/get?template=da886f3e6a65b53c9433359f702e24990e29f561dccdc0404558717ed3f70b78%2Fpartials%2FmyTemplate 404 (Not Found)`

So it seems that the call to the template script does not have a correct URL. It lack the website root and I don't see any 'actions' folder anywhere.

Then I try to use `craft.blitz.getUri` and it worked.

**Comment by bencroker** [comment]
It expects a template rather than a URI, so this should work:

```
{{ craft.blitz.getTemplate('partials/myTemplate' ) }}
```

But you can use `getUri` with a URI as well if it is publicly accessible.
