### ISSUE TITLE
`blitz/cache/warm` doesn't warm any files

### ISSUE THREAD

**Issue by Tam** [putyourlightson/craft-blitz#17]
As part of our deployment process we run `./craft blitz/cache/warm`, but every time we do we get the following response:

```bash
Warming Blitz cache – this may take some time.
Blitz cache successfully warmed 0 files.
```

I'm using the `blitz.php` config file, currently with the following patterns:
```php
return [
  // ...
  'includedUriPatterns' => [
    '/',
    'team.*',
  ]
];
```

The cache is cleared correctly but the pages only re-cache upon first visit by a user, never by the command.

**Comment by putyourlightson** [comment]
Is warming the cache working using the utility in the control panel?

**Comment by Tam** [comment]
Seems to be, yeah.

**Comment by putyourlightson** [comment]
Ok, will look into it and let you know what I find.

**Comment by Tam** [comment]
I've since updated my `includedUriPatterns` to:
```php
'includedUriPatterns' => [
	'/',
	'team.*',
	'shop.*',
],
```

I also added some debug code to [`CacheService.php#L384-L403`](https://github.com/putyourlightson/craft-blitz/blob/v1/src/services/CacheService.php#L384-L403):
```bash
Warming Blitz cache – this may take some time.
# print_r($urls);
Array
(
    [0] => /product-categories/book
    [1] => /product-categories/food
    [2] => /product-categories/kitchenware
    [3] => /partners/guittard-chocolate
    [4] => /team/person
    [5] => /shop
    [6] => /news
    [7] => /team
    [8] => /cookery-courses
    [9] => /apprenticeships
    [10] => /
    [11] => /chefs-table
    [12] => /courses/mexican-fiesta
    [13] => /shop/infused-oils
    [14] => /shop/cooking-showdown
)
# Empty catches replated w/ echo $e->getMessage() . PHP_EOL;
cURL error 3: <url> malformed (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)
cURL error 3: <url> malformed (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)
cURL error 3: <url> malformed (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)
cURL error 3: <url> malformed (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)
cURL error 3: <url> malformed (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)
cURL error 3: <url> malformed (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)
cURL error 3: <url> malformed (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)
cURL error 3: <url> malformed (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)
cURL error 3: <url> malformed (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)
cURL error 3: <url> malformed (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)
cURL error 3: <url> malformed (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)
cURL error 3: <url> malformed (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)
cURL error 3: <url> malformed (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)
cURL error 3: <url> malformed (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)
cURL error 3: <url> malformed (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)
Blitz cache successfully warmed 0 files.
```

There are two clear issues here:
1. Blitz is matching all URLs seemingly regardless of the URI patterns.
2. The URLs are all relative.

The second issue is an easy fix. We were using `@web` in our siteUrl and as you mentioned in the readme that won't work in the console, so I've fixed that by hard-coding the siteUrl in `general.php`.

The first issue however, is a bug in the code. You are only getting the first character of the URI patterns ([`CacheService.php#L83`](https://github.com/putyourlightson/craft-blitz/blob/v1/src/services/CacheService.php#L83)) meaning all the patterns are being read incorrectly (it also means empty patterns throw a PHP notice causing the command to fail).

Next, you are trimming `/` when checking if the URI is a match ([`CacheService.php#L449`](https://github.com/putyourlightson/craft-blitz/blob/v1/src/services/CacheService.php#L449)). So when Blitz recieved a pattern starting with `/` it was becoming an empty regex, hence all URLs being matched. `/` becoming empty isn't really an issue, just something it might be worth making people aware of.

Another thing worth noting is that `__home__` becomes an empty string ([`CacheService.php#L124`](https://github.com/putyourlightson/craft-blitz/blob/v1/src/services/CacheService.php#L124)) so `/` wouldn't have worked any way.

(If anyone's interested, to match the home page a negative look ahead for any char `^(?!.)` is needed.)

Long story longer, I've made a [pull request with a fix](https://github.com/putyourlightson/craft-blitz/pull/18).

**Comment by putyourlightson** [comment]
I'm not sure your assumption is correct. Your `includedUriPatterns` config setting should contain an array of arrays. I realise this may be counter-intuitive but it is how the table field stores its data, so that is how Blitz expects to find it. I may update the code for the next release but in the meantime can you try this with the original code?

```php
'includedUriPatterns' => [
	['/'],
	['team.*'],
	['shop.*'],
],
```

**Comment by Tam** [comment]
Yep, that makes sense! Also explains why the table in the settings was all empty rows. That's definately something worth mentioning in the docs as well.

**Comment by putyourlightson** [comment]
I've updated Blitz in https://github.com/putyourlightson/craft-blitz/commit/94eddbb7fe2ae4ca1a5f6945854e17c4f2efacef to normalize patterns to strings, so this should now work for you as well:

```php
'includedUriPatterns' => [
	'/',
	'team.*',
	'shop.*',
],
```
