### ISSUE TITLE
Warming Cache queue gets stuck during backend actions

### ISSUE THREAD

**Issue by Paulexe** [putyourlightson/craft-blitz#171]
Hi,

i bought blitz for a craft project and it works fine in my local XAMPP environment. On my shared hosting something weird is happening:

"Warming cache" (~500 pages) works fine **as long as i do nothing** in the backend. As soon as i do anything, like switching to a different page in the backend or just refreshing, the "warming cache" queue task gets immediately stuck. Even if i restart the queue it works again (with animation in the Queue Manager), but as soon as i refresh the page the animation freezes and the job never gets done. 
It works though if i press "warm cache" and do nothing for 5 minutes. Then Blitz shows all pages as cached and the task is finished/gone.

Stuck Queue Job:
![queue-stuck](https://user-images.githubusercontent.com/38528017/74605877-21de7900-50cc-11ea-9a35-c729df4207f0.png)

I dont know that much about servers and stuff here are some infos:

blitz.log is fine:
2019-12-22 15:16:03 [][1][info] Blitz cache successfully queued for warming.

phperrors.log:
no new entries

Craft System Requirements:
all checked green

I already did this:
"For large sites we recommend increasing max_execution_time to 300 and memory_limit to 1024M."

### Versions
PHP version : 7.4.2 (same as local)
phpinfo here: `removed`
Blitz: 3.2.0
Craft CMS: 3.4.5

**Comment by bencroker** [comment]
Thanks for the info. I've removed your phpinfo link as it contains information that shouldn‘t be made public.

Can you test if the issue has to do with the queue job by running an _Update asset indexes_ task in the _Asset Indexes_ utility and then visiting another page? Do you get a similar result or does it not happen here?

**Comment by bencroker** [comment]
Closing as no response.

**Comment by Paulexe** [comment]
Hey, sorry for not following up. Didn't work on that site for quite some time.

Tried again with Updates to Craft 3.4.17 and Blitz 3.6.4, but still the same behaviour on my server as described above. In my local environment with Laragon and php 7.4.4 it works fine. And i copied that one to my server just before testing.

I tried _Update asset indexes_ and it keeps working fine, even if i do other things in the CP at the same time. But i have to stay on the page with the progress bar, otherwise it will disappear as a task. But i think this is normal behavior, as i tested it on another craft install with a working Blitz Plugin.

**Comment by bencroker** [comment]
My guess is that your shared hosting plan is limiting the number of processes so that when a background job is running, your browser session is blocked. Other users can likely still use the site. My advice would be to upgrade to VPS hosting.

**Comment by Paulexe** [comment]
Couldn't update right now, but will try a VPS for future projects. With your hint on the number of processes I got it working on my server with the [Craft Async Queue Plugin](https://github.com/ostark/craft-async-queue). This works great and it even handles initial Blitz warming with 500 pages and creating 5k image transforms over a few minutes while i can do whatever i want in the backend or frontend.

Thank you!

**Comment by bencroker** [comment]
Excellent!
