### ISSUE TITLE
Integrity constraint violation

### ISSUE THREAD

**Issue by john-henry** [putyourlightson/craft-blitz#174]
### Describe the bug

Since turning on ` these errors are popping up very frequently.

I tried to use `./craft blitz/cache/generate-expiry-dates` but I think this generated the same error

> SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`acrafta`.`blitz_elementquerycaches`, CONSTRAINT `blitz_elementquerycaches_queryId_fk` FOREIGN KEY (`queryId`) REFERENCES `blitz_elementqueries` (`id`) ON DELETE CASCADE ON UPDATE CASCAD)
> The SQL being executed was: INSERT INTO `blitz_elementquerycaches` (`cacheId`, `queryId`) VALUES (231, 1207), (231, 893), (231, 2), (231, 1208), (231, 896), (231, 1209), (231, 903), (231, 45), (231, 1210), (231, 1211), (231, 914), (231, 1213), (231, 916), (231, 917), (231, 918), (231, 919), (231, 920), (231, 921), (231, 17)
> 

### Versions
- Plugin version: 3.2.0
- Craft version: Craft CMS 3.4.5

**Comment by bencroker** [comment]
Thanks for the issue. Is this happening on a regular page view? Anything unusual about the page? 

As an aside, from the SQL query there seem to be a lot of element queries being executed on that page, perhaps there's an opportunity to use eager-loading?

**Comment by john-henry** [comment]
Hi Ben,

Nothing unusual other than a high volume of traffic and a lot of entries being edited all the time

**Comment by bencroker** [comment]
Improved foreign key constraint checks before writing to the database in 3.3.0.
https://github.com/putyourlightson/craft-blitz/blob/develop/CHANGELOG.md#330---2020-02-18
