### ISSUE TITLE
cacheElements and cacheElementQueries...how does it work?

### ISSUE THREAD

**Issue by webtrend** [putyourlightson/craft-blitz#175]
### Question
I understand the concept of elements and element queries from the standpoint of using craft but I am not sure how exactly does it work in blitz cache and what are the ramifications of changing the values of these two flags. There is not much on documentation page that explains this. So can you tell me what exactly does it do?

### Additional context
An example in my situation would be our company blog. Our blog articles once published are unlikely to change. Should I have both these flags set to `false` for an individual blog entries?

Another scenario is our blog listing page which will need to be recached when a new article gets published. I am assuming that if I set `cacheElementQueries = true`, the plugin will recache this page when a new article is published. Is my assumption correct?

**Comment by bencroker** [comment]
As documented [here](https://putyourlightson.com/plugins/blitz#cacheelements), setting `cacheElements` to `false` will disable caching the elements  in the database, setting `cacheElementQueries` to `false` will disable caching the element queries in the database. Both of these settings are used for the automatic cache invalidation of pages when elements are updated (`cacheElements`) and when new elements are added (`cacheElementQueries`). They should be left as `true`, their default values, unless you have a good reason to disable them.

See this [common issue](https://putyourlightson.com/plugins/blitz#the-refresh-cache-queue-jobs-run-for-long-periods-of-time-and-sometimes-pile-up) for why you might want to disable them.
