### ISSUE TITLE
Assets not registering on FE

### ISSUE THREAD

**Issue by jsmrtn** [putyourlightson/craft-blitz#176]
### Describe the bug
We are using Blitz Cache to import our include that loads a plugin called adWizard `{{ craft.blitz.getTemplate('ism/includes/_adwizard') }}`. The include is pretty much some divs and the init for adWizard i.e. `{{ craft.adWizard.randomizeAdGroup('leaderboard') }}`

However, it's not registering the asset bundles correctly on the front end. If I default back to the standard `{% include %}` tags the assets get loaded in correctly, so I can only assume Blitz is doing something weird when it runs the `getTemplate` code. 

Thanks!

### To reproduce
Steps to reproduce the behaviour:
1. Use a plugin that registers assets onto the front end
2. Include a template that calls said plugin through `getTemplate`

### Expected behaviour
Assets to be registered on the front end

### Versions
- Plugin version: 3.4.1
- Craft version: 3.4.6.1

**Comment by bencroker** [comment]
How are the asset bundles being generated? Can you show the code of your injected template?

I'm not sure if this is related, but note that a limitation of injecting the result of an AJAX request into HTML is that any script tags will not be executed. This may have adverse effects on injected content that includes JavaScript code to be run.

**Comment by jsmrtn** [comment]
They're added by the plugin using `$view->registerAssetBundle(FrontEndAssets::class);`

Our include is super simple, and doesn't register the asset bundle itself directly.

```
<div class="adpanel mt--large pt--xlarge pr--medium pb--xlarge pl--medium">
    <div class="site-content">
        {% if craft.app.request.isMobileBrowser %}
            {% if craft.adWizard.randomizeAdGroup('mpu') | length %}
                {{ craft.adWizard.randomizeAdGroup('mpu') }}
            {% else %}
                {{ craft.adWizard.randomizeAdGroup('leaderboard') }}
            {% endif %}
        {% else %}
            {{ craft.adWizard.randomizeAdGroup('leaderboard') }}
        {% endif %}
    </div>
</div>
```
Ref your second point, we've made use of your `afterBlitzInject` call before, but these assets don't run on runtime, they contain functions that gets referenced by the output of the `randomizeAdGroup` variable.

**Comment by bencroker** [comment]
Just ran some tests and I see that the asset bundles are indeed not returned when using `craft.blitz.getTemplate`, but they are returned when using `craft.blitz.getUri` (provided there are `body` tags in the template, works with public templates only). Even when they are returned though, this doesn't help the fact that the asset bundles are JavaScript files that, as noted above, will not run after being injected into the DOM. 

I know that @lindseydiloreto has been adding cache-proofing to his plugins lately and have asked him if Ad Wizard might get an update soon.

**Comment by jsmrtn** [comment]
>Even when they are returned though, this doesn't help the fact that the asset bundles are JavaScript files that, as noted above, will not run after being injected into the DOM.

Ah yes, of course.

I did have a request open over at the repo for this doublesecretagency/craft-adwizard#9, I guess this is more an adwizard issue than a Blitz issue, as this is just how Blitz works?

**Comment by bencroker** [comment]
Yes, the way you've manually hooked it up on the front-end is probably your best bet for now.
