### ISSUE TITLE
any changes

### ISSUE THREAD

**Issue by Djive** [putyourlightson/craft-blitz#178]
### Question
We have 130 multisite setup using same templates
we tryed Blitz before worked OK. 
but after hour or two we get couple GB DB growth and things get slow 

was there any changes how things work 
does CLoudflare setup generate big DB too. 
or i see now there will be template cache .. does that can help our setup..in any way

**Comment by bencroker** [comment]
What version of the plugin are you running? Did you refresh the cache after updating? Which of the Blitz tables are the largest? If the `blitz_elementqueries` is very large then it may be necessary to set the `cacheElementQueries` config setting to `false` (followed by refreshing the cache). See this [common issue](https://putyourlightson.com/plugins/blitz#the-refresh-cache-queue-jobs-run-for-long-periods-of-time-and-sometimes-pile-up) for more details.

**Comment by Djive** [comment]
now i dont run any.. last time i tried about 2-3 month ago..
blocked  entire dedicated server..  
so i did not tryed after that..

**Comment by bencroker** [comment]
We've discussed your setup of 130 sites in the past. I think it might be worth trying again, with a fresh install, setting `cacheElementQueries` to `false` and using [source tags](https://putyourlightson.com/plugins/blitz#source-tags) to help with cache clearing.
