### ISSUE TITLE
Craft Commerce - Cache refresh issue

### ISSUE THREAD

**Issue by lenvanessen** [putyourlightson/craft-blitz#180]
Hi There,

We use blitz with Craft Commerce. And we see our queue filling up all the time with "refreshing blitz cache" for models that we don't want to be cached. Any way to avoid this?

As an example, you see it's caching the "order" queries every time someone creates or changes a cart (which are actually orders). On a busy site this leads to a queue longer than Santa Claus' beard:
![unnamed](https://user-images.githubusercontent.com/23024452/75671756-9e9e5500-5c7f-11ea-9be8-9b8a2b336b3c.jpg)

**Comment by bencroker** [comment]
You can select which element types should not be cached using the `nonCacheableElementTypes` [config setting](https://github.com/putyourlightson/craft-blitz/blob/3.4.1/src/config.php#L141-L144).

```
'nonCacheableElementTypes' => [
    'craft\commerce\elements\Order',
],
```

I wonder if orders should be excluded by default, is there any use-case for linking them to cached pages?

Santa would be proud :)

**Comment by lenvanessen** [comment]
@bencroker whoops, didn't catch that.

I can't think of any usecase where you want orders to be cached.

**Comment by bencroker** [comment]
Added in https://github.com/putyourlightson/craft-blitz/commit/ea8dd7a3ecdc37421149f36152a5891e27972f9e
