### ISSUE TITLE
How to work with Gzip feature on Apache?

### ISSUE THREAD

**Issue by johndwells** [putyourlightson/craft-blitz#181]
### Question
With the 3.4.0 release came the ability to generate gzipped caches, though the docs don't talk about how to work with the feature. In the case of Apache, I assume it's down to some rewrite magic - can you add some details about how to get the best out of this feature?

Thanks!

**Comment by bencroker** [comment]
I've been meaning to document this, so thanks for the poke @johndwells!

See the end of the [Apache server rewrites](https://putyourlightson.com/plugins/blitz#apache) for the code to use. Note that if using Cloudflare or another CDN, this won't really have any performance benefits as Cloudflare uses Brotli to compress data.
