### ISSUE TITLE
Cache Commerce Checkout templates

### ISSUE THREAD

**Issue by kaspar-allenbach** [putyourlightson/craft-blitz#182]
### Question
Is it possible to cache the checkout pages of the craft commerce plugin?
I tried the same approach like I [asked here](https://github.com/putyourlightson/craft-blitz/issues/152)

#### Example:

Inject the content of the current Cart into the template `shop/cart`

- I add `{{ craft.blitz.getTemplate('shop/_includes/cartItemContent') }}`

which contains the items of the cart:
```
{% for item in cart.lineItems %}
 {# items names, descriptiosn usw #}
{% endfor %}
```

But this doesn't work. There is just an empty inject span where the cart content should be:
`<span class="blitz-inject" id="blitz-inject-1"></span>`

What do I miss? Is blitz even compatible with commerce?

### Additional context
I try to cache the default checkout templates of the commerce 3 plugin

**Comment by bencroker** [comment]
It should work. Can you try this using the `craft.blitz.getUri` tag?
https://putyourlightson.com/plugins/blitz#craft.blitz.geturi-page-name-params

**Comment by kaspar-allenbach** [comment]
If I try with the getUri tag the markup looks like this:

```
{% extends "shop/_layouts/main" %}
{% import '_incl/docMacros' as macro %}
{% block main %}

    <h1>{{ "Dein Warenkorb" | t }}</h1>
    {{ craft.blitz.getUri('/shop/_includes/cartInjector') }}
    
{% endblock %}
```

 I see this in the console:

![Bildschirmfoto 2020-03-10 um 15 58 47](https://user-images.githubusercontent.com/762213/76325841-173c8b80-62e8-11ea-8bb5-f8006596b921.png)

What does `no-chache=1` that mean?

**Comment by bencroker** [comment]
The `getUri` tag makes an AJAX request to the URI, therefore it must be publicly accessible. Since `/shop/_includes/cartInjector` contains an underscore, I'm guessing it is not. Can you try it with a public template?

`no-cache=1` tells Blitz to serve a dynamic template and not a cached one.

**Comment by kaspar-allenbach** [comment]
I don't get it. I made the includes public
```

{% extends "shop/_layouts/main" %}
{% import '_incl/docMacros' as macro %}
{% block main %}

    <h1>{{ "Dein Warenkorb" | t }}</h1>
    {{ craft.blitz.getUri('/shop/includes/cartInjector') }}
    
{% endblock %}
```

Then inside the the `cartInjector`  I write some string `Hello`.
`Hello` displayed nice and well.

Now if I write any twig tag like:
```

{{ entry.title }}
```

The Ajax request is returning an error 500.

In the blitz.log there is an entry: 

> 2020-03-12 12:35:39 [][][debug] Page not cached because a `no-cache` request parameter was provided. [domain.com/shop/includes/cartInjector?no-cache=1]

Why is there a no cache tag on the included file? This is nowhere specified.

**Comment by bencroker** [comment]
I assume `entry` is not defined in the `cartInjector` template. 

It is important to realise that `craft.blitz.getUri` is _not_ a regular Twig include, instead it is loaded via an AJAX request and then injected into the HTML using Javascript.

What happens if you put this in the `cartInjector` template?
```
{% set cart = craft.commerce.carts.cart %}
Cart Total: {{ cart ? cart.itemTotal : 0 }}
```

**Comment by kaspar-allenbach** [comment]
Jup. That was it. Everything is scoped so cart is not available. I didn't understand that. Thanks.
