### ISSUE TITLE
Consider supporting IE11?

### ISSUE THREAD

**Issue by lenvanessen** [putyourlightson/craft-blitz#183]
Currently, fetching dynamic templates is broken if in IE11.
This is due to the Event constructor used in blitzInjectScript.

Can you change these to CustomEvent? Like the implementation in other parts of the same script. This will allow us to polyfill the constructor and make it work in IE11.

**Comment by bencroker** [comment]
Added in https://github.com/putyourlightson/craft-blitz/commit/87afafb8ed9e03c1096e5893ccc50365b579a7ef and version 3.5.0.
