### ISSUE TITLE
Using Blitz with Language Redirector plugin

### ISSUE THREAD

**Issue by pierrestoffe** [putyourlightson/craft-blitz#185]
Posting this for posterity, since I had the issue:

If you are using Blitz and the Language Redirector plugin at the same time, you might want to read this wiki page: https://github.com/pierrestoffe/craft-language-redirector/wiki/Use-with-blitz.

**Comment by bencroker** [comment]
Thanks for posting the link. It may be worth noting that the method you describe will _not_ work if server redirects or a reverse cache proxy is used, as both of these methods will return the cached version of the page _before_ the `EVENT_BEFORE_GET_RESPONSE ` event is triggered.

**Comment by pierrestoffe** [comment]
Indeed, I'll add it to the wiki page of Language Redirector as well. Nice catch!
