### ISSUE TITLE
GitDeployer → Failed to connect to port 443

### ISSUE THREAD

**Issue by jdsimcoe** [putyourlightson/craft-blitz#186]
### Describe the bug
I get an `Failed to connect to port 443: Connection refused` error when trying to connect to a local GitHub repo via Git Deployer. Here is the full error output:

```
Error connecting to repository: fatal: unable to access 'https://jdsimcoe:$GITHUB_TOKEN@/': Failed to connect to port 443: Connection refused
```

### To reproduce
Steps to reproduce the behaviour:
1. Go to `Remote Deployment` tab.
2. Add a valid `Repository Path` pointed to a locally cloned SSH private GitHub repo.
3. Add a valid `$GITHUB_TOKEN` environmental variable saved to `.env`.
3. Hit `Save`.
4. Observe error.

### Expected behaviour
I would expect the `Save` button to successfully save my local repo connection.

### Screenshots
![image](https://user-images.githubusercontent.com/275617/76245542-4d4f1200-61f9-11ea-8692-d0ee40bd8214.png)

### Versions
- Plugin version: 3.5.0
- Craft version: Pro 3.4.9

**Comment by bencroker** [comment]
Does the `origin` remote exist in your repo? You can test a `push` to see if it exists. 
You can also check in the `.git/config` file for the following:

```
[remote "origin"]
	url = https://jdsimcoe:$GITHUB_TOKEN@github.com/jdsimcoe/...
```

**Comment by jdsimcoe** [comment]
so @bencroker I found that turning on Git Deployer changed the `.git/config [remote "origin"]` URL in two repos: the current repo, and my static site repo.

It changed both to this:

```
[remote "origin"]
  url = https://jdsimcoe:<TOKEN>@
``` 

The GitHub, path, and `.git` suffix were stripped off, both in the static repo, but also in the repo that my main project was in. I was able to manually repair it in both places by hard-coding the token in. One question that arises though, is do I really need GitHub tokens if I have valid SSH keys set up in both repos? Both were cloned via SSH.

Thanks for your help!

**Comment by bencroker** [comment]
Yup, as per the article:

> It is important to clone the repository using a HTTPS URL and not SSH.

https://putyourlightson.com/articles/deploying-a-craft-site-to-netlify-with-blitz-3#1.-create-a-git-repository

**Comment by jdsimcoe** [comment]
Hmm. But it shouldn't have affected the repo I was in, right? That was more concerning to me. I understand it trying to parse the URL in the static repo.

**Comment by bencroker** [comment]
It shouldn't have. The repo paths are different, right?

**Comment by jdsimcoe** [comment]
Yes, they are different. Adjacent, but different.

`~/Sites/atheycreek/` (main repo)
`~/Sites/atheycreek-static/` (static)

**Comment by bencroker** [comment]
Let me know if it happens again, as that would be a bug.
