### ISSUE TITLE
Refresh Expired Cache stuck when using Redis and Yii Cache Storage

### ISSUE THREAD

**Issue by lenvanessen** [putyourlightson/craft-blitz#188]
### Describe the bug
For some reason, Refresh Expired Cache stalls with only 4 posts in the job. It just keeps going and going and going until it hits the 300second limit.

When using the file storage type, this issue does not occur. But I'm using Heroku, I can't use this one.

### Versions
- Plugin version:3.5.0
- Craft version: 3.4.9

**Comment by bencroker** [comment]
> For some reason, Refresh Expired Cache stalls with only 4 posts in the job.

Can you clarify what you meab by `4 posts in the job`? And what happens when the job fails?

**Comment by lenvanessen** [comment]
Sorry, it means that it just has to refresh the cache for 4 entries (on 2 sites)

**Comment by bencroker** [comment]
> And what happens when the job fails?

Is there any further information you can provide to help us troubleshoot? What caching mechanism are you using?

**Comment by lenvanessen** [comment]
Hi @bencroker,

Sure, we're using:
- Redis as a Caching engine;
- A worker dyno that runs `queue/listen --verbose`
- A cronjob that calls ` ./craft blitz/cache/refresh-expired` every 10 minutes

Jobs just seem to be stuck at 100%, unsure why this is happening. If we switch back to the file based storage, not issues with stuck queue tasks.

Job status example:
![Schermafbeelding 2020-03-18 om 14 33 00](https://user-images.githubusercontent.com/23024452/76965923-753f2380-6925-11ea-9373-0b655ace19d5.png)

**Comment by lenvanessen** [comment]
@bencroker it looks like it was just to heavy to execute. Optimized the front-end a bit and now it doesn't get stuck anymore.

**Comment by bencroker** [comment]
Glad to hear it!
