### ISSUE TITLE
Plug-in breaks Geomate

### ISSUE THREAD

**Issue by lenvanessen** [putyourlightson/craft-blitz#189]
Hi There,

As soon as Blitz is enabled, Geomate stops working. Not sure if this is on your end or on Geomates, but it would be great if this can be resolved!

**Comment by lenvanessen** [comment]
Ps, we're not using nginx or apache te server files, so the request is coming to Craft

**Comment by bencroker** [comment]
How are you using Geomate, with template tags or using the `redirectMap` config option? Since Blitz intercepts the request as early as possible, it is likely that Geomate is not performing the redirect early enough.

**Comment by lenvanessen** [comment]
@bencroker I'm using it with the redirectMap. So this is something that Geomate needs to resolve?

**Comment by bencroker** [comment]
We're looking into a workaround to make this work.

**Comment by lenvanessen** [comment]
@bencroker cool. I know that on the other thread you mentioned a fix is ready on dev. When will this be released?

**Comment by bencroker** [comment]
Likely today.

**Comment by bencroker** [comment]
Released in 3.5.1.

**Comment by tihoq** [comment]
Hi @bencroker ,
I have the same problem. When I enable cache in Blitz plugin settings then redirection from geomate no longer works for me. I use Blitz v3.11.1 and Geomate v1.3.1.2. Redirection setup is in geomate.php and I use redirectMap. 
On urls that are excluded from caching geomate redirection works well.
Is there a solution for this problem?

**Comment by bencroker** [comment]
@tihoq if Geomate was installed after Blitz then it may not be firing early enough. The simple workaround is to uninstall and then reinstall Blitz in the plugin settings page.

**Comment by tihoq** [comment]
@bencroker 
I uninstalled and removed both plugins. After that I installed geomat first, then blitz, but that didn't help.

**Comment by bencroker** [comment]
Did you clear the Blitz cache after reinstalling them? And are you using server redirects with Blitz?

**Comment by tihoq** [comment]
@bencroker 
Yes, I deleted the Blitz cache before and after the reinstallation, I also deleted the craft cache. Yes, we use server redirects with Blitz.

**Comment by bencroker** [comment]
Ok, so the server redirects will kick in before Geomate has had a chance to do its thing. Removing the server redirects should solve this for you.
