### ISSUE TITLE
Refreshing cache doesn't work on non-primary site

### ISSUE THREAD

**Issue by lenvanessen** [putyourlightson/craft-blitz#190]
Hi @bencroker,

We run the following set-up:
1. Heroku as a platform
2. Redis + Yii Cache Storage for the saving of the Blitz cache
3. A worker dyno that listens to the queue
4. A scheduler that calls `blitz/cache/refresh` every 10 minutes.

We schedule quite a few posts in advance. And they should show up on our homepage, and their category page. On our primary site. It works like a charm, the homepage and category pages get refreshed when a new post is supposed to show up. But for some reason, on our german site, this doesn't happen. The task runs, the row gets removed from blitz_elementexperydates, but it doesn't refresh the pages where it's supposed to show up.

Do you have any idea why this might be happening?

**Comment by bencroker** [comment]
First of all, you shouldn't be running `blitz/cache/refresh` every 10 minutes. That command will refresh the entrie cache. Instead, you should be running the `blitz/cache/refresh-expired` command, which will refresh the expired cached pages of all expired entries (I assume that is what you mean when you say "posts"). Can you try that and see if it makes any difference?

**Comment by lenvanessen** [comment]
HI @bencroker,

Sorry about, we are in fact running `refresh-expired`;) It's still early here. So the situation is already as you described, and it works like a charm for one site, but not for the other.

**Comment by bencroker** [comment]
Ok I see. Can you do a test using the `Refresh Expired Cache` utility to see if it refreshes the expired entries?

**Comment by lenvanessen** [comment]
@bencroker just changed to tags, working much better, my guess is just to many relations to be checked dynamically

**Comment by bencroker** [comment]
Refreshing expired cache shouldn't be process intensive as expiry dates of elements and pages are stored when saved. Glad to hear it's working better now, let me know if any other issues come up.
