### ISSUE TITLE
How to pass site to getTemplate

### ISSUE THREAD

**Issue by lenvanessen** [putyourlightson/craft-blitz#191]
Hi,

We're using blitz in a site with multiple languages. But the dynamic templates we're loading include a string that utilizes `|t`. But since it's an ajax request, the translation for the default site is loaded.

Any way to avoid this?

**Comment by bencroker** [comment]
Hmm we should probably make that a feature request. In the meantime, using `getUrl` should work since the URL will indicate the site. Can you try that?

**Comment by focalinteractive** [comment]
Same issue here with a multilingual site. 
By using getUrl we can't use _templateName so it is unnecessarily exposed. Is there a way to avoid that?

**Comment by bencroker** [comment]
Added this and you can test it using the `develop` branch.
https://github.com/putyourlightson/craft-blitz/blob/develop/CHANGELOG.md#360---unreleased

**Comment by focalinteractive** [comment]
Thank you @bencroker!

**Comment by bencroker** [comment]
Is this working as you expect @focalinteractive?

**Comment by bencroker** [comment]
Waiting for your response before I release.

**Comment by lenvanessen** [comment]
@bencroker just tested and works as expected

**Comment by bencroker** [comment]
Glad to hear it!
