### ISSUE TITLE
Cache not warming

### ISSUE THREAD

**Issue by bymayo** [putyourlightson/craft-blitz#193]
We spoke briefly on Discord the other day, but i'm having issues still with cache not warming. 

When I do `Refresh` option in Utilities, it shows that cache is being warmed, but the counter for the amount of warmed pages is `0`. When I turn `debug` on in Blitz I get the error:

```
2020-03-28 11:49:36 [][][debug] Page not cached because it does not match an included URI pattern. [https://cms.website.co.uk/]
```

I traced this issue back to when I'd updated Blitz from `3.4.1` to `3.5.0`. Even now on the latest version (`3.6.0`) I am still having this issue. I've tried resaving the settings like you said but still not luck.

The URI pattern i'm using is also just the one you mention in the docs `.*`, so not sure why this error would appear. The site URL is set to `$SITE_URL` in `.env` and this matches the site that i'm accessing the CMS on, just incase that was a thought of conflict. My Blitz config is as follows:

```
return [
    '*' => [
        'cachingEnabled' => false,
        'includedUriPatterns' => [
            [
                'siteId' => getenv('SITE_UID'),
                'uriPattern' => '.*',
            ]
        ],
        'excludedUriPatterns' => [],
        'cacheStorageSettings' => ['folderPath' => '@root/static/cached'],
        'clearCacheAutomatically' => true,
        'warmCacheAutomatically' => true,
        'refreshCacheAutomaticallyForGlobals' => true,
        // Deployments
        'deployerType' => 'putyourlightson\blitz\drivers\deployers\GitDeployer',
        'deployerSettings' => [
            'gitRepositories' => [
                getenv('SITE_UID') => [
                    'repositoryPath' => getenv('BLITZ_DEPLOYMENT_REPO_PATH'),
                    'branch' => 'master',
                    'remote' => 'origin',
                ],
            ],
            'commitMessage' => getenv('BLITZ_DEPLOYMENT_COMMIT_MESSAGE'),
            'username' => getenv('BLITZ_DEPLOYMENT_USERNAME'),
            'personalAccessToken' => getenv('BLITZ_DEPLOYMENT_ACCESS_TOKEN'),
            'name' => getenv('BLITZ_DEPLOYMENT_NAME'),
            'email' => getenv('BLITZ_DEPLOYMENT_EMAIL'),
            'commandsBefore' => 'cp -r ' . getenv('SITE_BASE_PATH') . '/' . getenv('PUBLIC_FOLDER') . '/dist ' . getenv('BLITZ_DEPLOYMENT_REPO_PATH') . ';'
        ]
    ],
    'production' => [
        'cachingEnabled' => true,
        'debug' => true
    ]
];
```

### Versions
- Plugin version: 3.6.0
- Craft version: 3.4.10.1
- PHP: 7.2.24
- MySQL: 5.7.29

**Comment by bencroker** [comment]
It looks like the issue might be that you are passing a UID to the `siteId` property. Can you try it with a site ID instead of UID?

```
        'includedUriPatterns' => [
            [
                'siteId' => getenv('SITE_UID'),
                'uriPattern' => '.*',
            ]
        ],
```

**Comment by bymayo** [comment]
@bencroker That works now! Can't believe I missed that. It's correct that the `siteId` for `gitRepositories` is the UID though right?

Also, it might be worth adding in a bit of error handling in to the CMS when warming, as I did get another error saying that it couldn't warm due to it having transform URL's in the templates. But in the CMS it looks like it has warmed successfully, when it hasn't.

**Comment by bencroker** [comment]
Not warming due to having transform URLs in the templates is not considered an error, that's why it appears in the logs only. If there was a way to show warnings in the CP then we would consider that, but there isn't.
