### ISSUE TITLE
Non-HTML content types

### ISSUE THREAD

**Issue by tom-id-au** [putyourlightson/craft-blitz#194]
Our sitemap.xml and robots.txt appear to be served by Blitz as text/html on cached requests.

It appears their folder is saved as the correct extension, but the file inside is index.html.

Is there an option / plan to make this save as index.xml / index.txt so that the correct format can be more easily served by nginx?

**Comment by bencroker** [comment]
Blitz should serve cached pages using a mime type if the URI has an extension:
https://github.com/putyourlightson/craft-blitz/blob/3.6.0/src/services/CacheRequestService.php#L248-L254

If you're using server rewrites then you may need to add code to handle the mime types, see https://github.com/putyourlightson/craft-blitz/issues/167#issuecomment-581686821 for some Nginx rewrite rules.
