### ISSUE TITLE
excludedUriPatterns being ignored when warming

### ISSUE THREAD

**Issue by kiwidood** [putyourlightson/craft-blitz#195]
### Describe the bug
When running a cache warm via command line (./craft blitz/cache/warm), URI patterns matching excludedUriPatterns are still being warmed. The same behaviour happens when updating an entry on the control panel.

I assume these URI's shouldn't even be attempted to be warmed? This is causing unnecessary load on pages that are 500/404ing as they're not intended to be called directly (e.g. related FAQs).

I was able to fix the issue on the command line by adding true as a parameter to the getAllSiteUris call below.

https://github.com/putyourlightson/craft-blitz/blob/8850532dd5c25bd16f87deae57a88f104f0c7e00/src/console/controllers/CacheController.php#L147

### Versions
- Plugin version: 3.6
- Craft version: 3.4.10.1

**Comment by bencroker** [comment]
Is this happening on a multi-site setup? If yes then can you try saving the plugin settings from the control panel to ensure that the included/excluded URI patterns are applied to the correct sites?

**Comment by kiwidood** [comment]
> Is this happening on a multi-site setup? If yes then can you try saving the plugin settings from the control panel to ensure that the included/excluded URI patterns are applied to the correct sites?

No, this is not a multi-site setup.

**Comment by bencroker** [comment]
Ok, yes you were right, fixed in https://github.com/putyourlightson/craft-blitz/commit/1157e8581737feeacd69eb2dd962a7d1ad9fd0ec, thanks!
