### ISSUE TITLE
customSiteUris not working via console

### ISSUE THREAD

**Issue by kiwidood** [putyourlightson/craft-blitz#196]
### Describe the bug
customSiteUris aren't warmed via the console warm command (./craft blitz/cache/warm). The "Warm Cache" in the cp is working fine.

Below has no reference to customSiteUris as it calls getAllSiteUris directly.

https://github.com/putyourlightson/craft-blitz/blob/8850532dd5c25bd16f87deae57a88f104f0c7e00/src/console/controllers/CacheController.php#L139-L150

### Versions
- Plugin version: 3.6
- Craft version: 3.4.10.1

**Comment by bencroker** [comment]
Is the site’s Base URL using the `@web` alias? See the common issue here (may also apply to https://github.com/putyourlightson/craft-blitz/issues/195): https://putyourlightson.com/plugins/blitz#the-site-is-not-being-cached-when-using-console-commands

**Comment by kiwidood** [comment]
> Is the site’s Base URL using the `@web` alias? See the common issue here (may also apply to #195): https://putyourlightson.com/plugins/blitz#the-site-is-not-being-cached-when-using-console-commands

No it's not, the Base URL is defined as a string in the .env file via DEFAULT_SITE_URL.

**Comment by bencroker** [comment]
Fixed in https://github.com/putyourlightson/craft-blitz/commit/5694f2dcc422839334cf8b72c8b2a8458fcbf0f2, thanks!
