### ISSUE TITLE
Netlify duplicate content

### ISSUE THREAD

**Issue by bymayo** [putyourlightson/craft-blitz#197]
We've got our site running on Blitz and deploying to Netlify. This is working amazingly well and the site is RAPID. But now is the tricky bit... We've had a marketing / SEO team look over the site.

They mentioned that because we've got the site running on a subdomain (`https://cms.website.com`) and deploying to `https://website.com` which is on Netlify, that users could still get to the `cms.` version.

Obviously we need this subdomain version so the company can update their content and it deploy to Netlify easily. But the SEO team are concerned about duplicate content etc.

We've added a `robots.txt` to `cms.` to stop Google indexing this version, but they aren't happy with this and are still finding issues.

Is there a way around this - Maybe having `isSystemOn` as `false` and only allowing Blitz to cache the site if someone is logged in to the CMS. 

You raised the problem about Freeform submissions - But in this case the form submissions go to a 3rd party anyway. Similar, this solution would work on 2 other sites we're trying to run Blitz on.

If you know a solution around this i'd love to hear it.

**Comment by bencroker** [comment]
Provided you don't need `cms.website.com` to be publicly available, to handle form submissions for example, then you should be able to turn off the site and use the [Local Warmer](https://putyourlightson.com/plugins/blitz#cache-warming). Due to the nature of how it works, it is still considered "experimental", but it should allow you to warm and deploy the site even when the CMS is switched off or if redirecting to the naked `website.com` domain. I do recommend doing some testing before using it in production.

**Comment by bymayo** [comment]
Okay, I'll give that a go. Didn't see that your docs say `A ​“Local Warmer” is also available for situations in which the site is not publicly accessible.`

What issues am I likely to run in to?

**Comment by bencroker** [comment]
Some people have had issues with multi-site setups in the past. Look out for URLs that have query params in them too.

**Comment by bymayo** [comment]
Okay I've tried this, but for some reason Blitz seems to be taking priority over if the `systemIsLive` setting is `false`. I clear the cache on the site and I can see the offline message, but when Blitz caches it then shows these cached files instead of the offline message.

**Comment by bencroker** [comment]
Have you disabled the server rewrite?

**Comment by bymayo** [comment]
Sorry, I don't know what you mean?

**Comment by bencroker** [comment]
Oh, I meant to ask if you have server rewrites (Nginx config or .htaccess) set up on the server on which Craft is hosted?

**Comment by bencroker** [comment]
Closed due to inactivity.
