### ISSUE TITLE
blitz/cache/refresh-expired doesn't work for non-primary site

### ISSUE THREAD

**Issue by lenvanessen** [putyourlightson/craft-blitz#199]
### Describe the bug
So, after searching long and wide I've found a culprit.

When you call `./craft/cache/refresh-expired` it calls the ElementsService right here:
https://github.com/putyourlightson/craft-blitz/blob/develop/src/services/RefreshCacheService.php#L470

But the ElementsService needs a siteId, because if it's null it defaults to the primary site.
And of course, if your expired entry is not on the primary site but on another site, this fails.

I currently see no option to have this working with the ElementsService, as it doesn't allow for a wildcard for the site.

PR incoming

**Comment by bencroker** [comment]
Thanks for the PR. It would be much nicer if Craft's elements service allowed us to do this:

```php
$element = $elementsService->getElementById($elementExpiryDate->elementId, null, '*');
```

At the moment however, the third parameter (site ID), must be an integer or null. I've submitted the a PR https://github.com/craftcms/cms/pull/5861 but will probably fix this as per your code.

**Comment by bencroker** [comment]
@lenvanessen Can you please check if https://github.com/putyourlightson/craft-blitz/commit/94d8b7dd582e18df621e8dd06ff0829602e7e76d works for you as expected?

**Comment by lenvanessen** [comment]
Works as expected!

**Comment by bencroker** [comment]
Great, thanks!
