### ISSUE TITLE
[FR] Console command for warming cache

### ISSUE THREAD

**Issue by riasvdv** [putyourlightson/craft-blitz#2]
Might be a good idea to have a Craft console command that allows you to warm the cache, for example after a deployment.

**Comment by putyourlightson** [comment]
Yes, good idea. A controller action that can be pinged with a cron job is also something I am considering.

**Comment by putyourlightson** [comment]
Added in https://github.com/putyourlightson/craft-blitz/commit/c4ab1d5918e0df0f8e5fea68ba5a1d5baf82d3fb

**Comment by riasvdv** [comment]
Thanks!

The command you added, while useful, is for clearing the cache.

I'd also like one for warming it (for example a command that loops all elements with URI's and does a GET request to them)

**Comment by putyourlightson** [comment]
Ah right, I forgot to address that as clearing the cache was the priority for 1.1.1. 

I've reopened the issue and will add it into the next release.

**Comment by putyourlightson** [comment]
Added in https://github.com/putyourlightson/craft-blitz/commit/d8788066fb2f056e8793d714e845ad93e340b04b

`./craft blitz/cache/warm`
