### ISSUE TITLE
Cache Warming gets URL incorrect with site_url

### ISSUE THREAD

**Issue by roberttolton** [putyourlightson/craft-blitz#20]
Just looked at the logs after wondering why a Cache Warming job had failed, and saw that the URL was incorrect:

`https://-removed-.com/en/en/posts` where it should be `https://-removed-.com/en/posts`

My site's URLs all end in a locale slug, including the default site, in this case `/en` - but looks like Blitz might be using another URL from somewhere, and concatenating? Not sure how to check for duplicates like this.

I have my `site_url` set to `https://-removed-.com/en/` which you could say is essentially like running Craft in a sub-folder, though it's not - I'm doing it to have the default site URL include a locale slug.

**Comment by putyourlightson** [comment]
Can you try warming the cache using the Blitz utility and see if that raises any issues? Then if you can, please check the database table called `blitz_caches` for incorrect URIs.

**Comment by putyourlightson** [comment]
Closing as there was no response.

**Comment by jan-dh** [comment]
@putyourlightson I did as above and ran into the same problem. 

My site base url is `@web/nl`. When I delete all caches and warm the cache from the admin panel, uri's of the entry are `nl/someuri`. However the file structure in my cache folder is like this:

`cache/Blitz/siteName/nl/nl/uri/index.html`

**Comment by putyourlightson** [comment]
This was fixed in 1.6.0 and the bug was reintroduced in 1.6.7... a permanent fix is coming, I promise 🤞

**Comment by putyourlightson** [comment]
Fixed in 1.6.8 https://github.com/putyourlightson/craft-blitz/commit/221b0ba57b11c391c6eb88bb4c6e78ffa4142dcb
