### ISSUE TITLE
Excluded pages get cached

### ISSUE THREAD

**Issue by focalinteractive** [putyourlightson/craft-blitz#202]
### Describe the bug
Blitz is caching pages that are excluded from the plugin's settings on the CP

### To reproduce
Steps to reproduce the behaviour:
1. Go to a page that should be excluded by Blitz
2. Open the Inspector
3. Confirm that the page is cached whereas it shouldn't 

### Expected behaviour
The page should not be cached. The pages are checkout pages used by craft commerce

### Screenshots
<img width="1006" alt="Screenshot 2020-04-02 at 20 51 56" src="https://user-images.githubusercontent.com/46625687/78281968-35329000-7524-11ea-8b53-25c84e165ec8.png">

<img width="903" alt="Screenshot 2020-04-02 at 20 51 48" src="https://user-images.githubusercontent.com/46625687/78281976-38c61700-7524-11ea-8acd-7ad2aed15318.png">

### Versions
- Plugin version: 3.6.2 (Pro)
- Craft version: 3.4.12 Pro with Craft commerce v.2 Pro (v.3.0.12)

**Comment by bencroker** [comment]
Can you please double check and then save the includes and excludes on the settings page? If after refreshing the cache you still have this issue, please share the URI patterns you are using in the settings.
