### ISSUE TITLE
Netlify error caused by Blitz creating folders named '?'

### ISSUE THREAD

**Issue by iamtompickering** [putyourlightson/craft-blitz#203]
### Describe the bug
I was unable to deploy my site through Netlify because a number of folders had been created with the name `?`. This was the result of a URL which included a ? but without a query string. I have prevented this from happening again in my twig files, but because these folders were somehow created previously, when Netlify tries to deploy, it fails and comes up with the following error: 

`Invalid filename 'news/p8/?/index.html'. Deployed filenames cannot contain # or ? characters`

I had to clone the repo to desktop, delete the folders causing the issue and push the change in order to fix this, but that's obviously not a viable solution for if it happens again and again. 

### To reproduce
Steps to reproduce the behaviour:
1. Try and deploy a folder called `?` through Netlify

### Versions
- Plugin version: 3.4.1
- Craft version: 3.4.9

**Comment by bencroker** [comment]
Can you try refreshing the cache and see if the folders with `?` are recreated? This may have been resolved a few versions ago and these may just be leftover folders.

**Comment by bencroker** [comment]
Any update on this @iamtompickering?

**Comment by bencroker** [comment]
Closing due to lack of response.
