### ISSUE TITLE
Cache is cleared upon creating / saving an entry

### ISSUE THREAD

**Issue by martinhellwagner** [putyourlightson/craft-blitz#204]
### Describe the bug
Even though we have the `Clear Cache Automatically` parameter disabled and no Cron Job or Daemon running to clear/refresh the cache, they get refreshed whenever an entry is created or saved. We're still using Craft template caching in the project (even sites that are actually cached in Blitz still have `{% cache %}` tags in their templates) though, and are running the queue in Redis. This might be related to issue https://github.com/putyourlightson/craft-blitz/issues/70.

### To reproduce
Steps to reproduce the behaviour:
1. Create or save entry

### Expected behaviour
Caches of sites that are cached (but not edited) should not rebuild.

### Versions
- Plugin version: `develop` Branch
- Craft version: 3.4.10.1

**Comment by bencroker** [comment]
How exactly are you seeing that the cached pages are being refreshed?

**Comment by martinhellwagner** [comment]
I'm checking the number of cached pages in the `/admin/utilities/blitz-cache` utility as well as the number of HTML files on the server. This number drops to zero when an entry is created/saved and is then slowly "rebuilt" when the users visit the cached sites.

**Comment by martinhellwagner** [comment]
With the timestamps of the HTML files on the server, I can see a clear correlation between creating/saving an entry and the files being created anew.

**Comment by bencroker** [comment]
Hmm very strange, can you share a screenshot of the advanced settings in the Blitz plugin settings?

**Comment by bencroker** [comment]
And are you definitely seeing this when an entry is updated, not a global?

**Comment by martinhellwagner** [comment]
![Screenshot 2020-04-06 at 13 13 17](https://user-images.githubusercontent.com/19146752/78552785-65ba4880-7808-11ea-9330-0c773f89ec63.png)

**Comment by martinhellwagner** [comment]
Is it possible that all of our entries contain a global field, resulting in this cache refresh?

**Comment by martinhellwagner** [comment]
For example, have a section called "Contacts" in each entry, for which you can select a person in a channel that's propagated across all sites. Also, a category (`/admin/categories/articleTopic`) is fetched for each entry.

**Comment by bencroker** [comment]
No, the question is whether you are seeing cached pages being cleared specifically when an "entry" is saved (not when a "global set" is saved).

**Comment by bencroker** [comment]
Looking at the code, the entire cache is refreshed regardless of the value of the "Clear Cache Automatically" setting if:

- A global set is saved.
- SEOmatic invalidates container caches.
- The `refresh` console command or utility is triggered.

**Comment by martinhellwagner** [comment]
This happens if an entry is saved or a new one created. Never touched the global sets during this test. The `refresh` console command is only triggered during deploy, not during a save. So I'm guessing SEOmatic might actually be the culprit.

**Comment by martinhellwagner** [comment]
Is it possible that the automatic metadata rendering of SEOmatic triggers the full cache rebuild?

![Screenshot 2020-04-06 at 14 08 20](https://user-images.githubusercontent.com/19146752/78556924-2bed4000-7810-11ea-9d6c-5172f19496f3.png)

**Comment by bencroker** [comment]
Yes, that's probably it. Can you confirm whether disabling that setting makes a difference? If it does then we'll add some logic so that it respects the setting.

**Comment by martinhellwagner** [comment]
Only the toggle itself doesn't make a difference, but disabling SEOmatic does. Something in SEOmatic (or at least in our usage of it) is triggering this cache refresh. 🤔

**Comment by bencroker** [comment]
Ok, I'll look into and let you know what I find.

**Comment by martinhellwagner** [comment]
@bencroker 

For testing purposes, I've removed _all_ of the code that is referencing SEOmatic, for example `seomatic.meta` – the cache was still refreshing. Only when I'm disabling SEOmatic, the cache stays "stable".

**Comment by bencroker** [comment]
Fixed in https://github.com/putyourlightson/craft-blitz/commit/5d585ae5085931f5c13c083bdcb0d89b3d945cfe, can you please test on the `develop` branch?

**Comment by martinhellwagner** [comment]
Unfortunately, the cache is still refreshed automatically. Is it necessary to disable the "Automatic Render Enabled" lightswitch in SEOmatic?

**Comment by bencroker** [comment]
What specific action in the control panel is triggering the refresh? Do you by any chance have any custom plugins installed that are listening for saved element events?

**Comment by martinhellwagner** [comment]
It's hard to say because a lot of Content Editors are using the Control Panel. I've tested by creating an entry and saving one – with these actions, the cache stays the same.

**Comment by martinhellwagner** [comment]
These are all the plugins we have on the Craft install:

![Screenshot 2020-04-08 at 14 14 34](https://user-images.githubusercontent.com/19146752/78783120-66d3ad00-79a3-11ea-8d4f-23d8a59cb18f.png)

![Screenshot 2020-04-08 at 14 14 41](https://user-images.githubusercontent.com/19146752/78783131-6a673400-79a3-11ea-988e-8d91ac8b1a6b.png)

![Screenshot 2020-04-08 at 14 14 47](https://user-images.githubusercontent.com/19146752/78783137-6dfabb00-79a3-11ea-8c82-d7bdb98bdaed.png)

![Screenshot 2020-04-08 at 14 14 52](https://user-images.githubusercontent.com/19146752/78783143-6fc47e80-79a3-11ea-9215-905c6fa4bf36.png)

![Screenshot 2020-04-08 at 14 15 06](https://user-images.githubusercontent.com/19146752/78783149-718e4200-79a3-11ea-9e67-92b6ad6e8b02.png)

**Comment by bencroker** [comment]
FYI I just deleted your last comment because you were exposing plugin license numbers in plaintext.

You can safely get a list of installed plugins at `/admin/utilities/system-report`.

**Comment by martinhellwagner** [comment]
Yes, wanted to do the same when you saw it. 😛 Thanks!

**Comment by bencroker** [comment]
> It's hard to say because a lot of Content Editors are using the Control Panel. I've tested by creating an entry and saving one – with these actions, the cache stays the same.

Firstly, you should really be testing on a non-production environment. The `develop` branch is intended, as the name suggests, for development purposes only.

Something else must be triggering the refresh. Do your content editors have the ability to edit the SEOmatic settings? Updating some global settings will cause the entire cache to be refreshed.

**Comment by martinhellwagner** [comment]
I actually deployed it on Stage before, but couldn't reproduce it there because I seem to be missing some things the Content Editors are doing.

I'll make sure to ask what exactly they are doing that will refresh the cache.

**Comment by martinhellwagner** [comment]
The problem seems to be related to queue jobs as well. Whenever I "pause" the queue, the cache stays the same. So something SEOmatic-related is thrown into the queue, and the cache rebuilt when the queue job is executed. 🤔

**Comment by martinhellwagner** [comment]
One more lead that we're following is related to this plugin: verbb.io/craft-plugins/comments

Whenever a comment is inserted by using a custom-built form, a redirect to the page is happening. Is it possible that the caching of CSRF tokens or something like that results in the cache being rebuilt, even though the respective page with the form is not Blitz-cached and the URI pattern `/csrf` is excluded from the cache?

![Screenshot 2020-04-08 at 17 24 21](https://user-images.githubusercontent.com/19146752/78802354-02721700-79be-11ea-979f-cfcd3f3f01e1.png)

**Comment by bencroker** [comment]
> Whenever a comment is inserted by using a custom-built form, a redirect to the page is happening. 

Have you tested that this leads to the cached page being refreshed in your staging environment? And what specifically does the custom form do?

**Comment by martinhellwagner** [comment]
Yes, this leads to a cache refresh also on the Staging environment. But on both environments, it doesn't happen all the time.

The custom form has a post action which looks like this: `<input type="hidden" name="action" value="comments/comments/save">`. Whenever a comment is added, Craft redirects the user back to the page where the comment is then displayed.

What might be interesting is that `{{ csrfInput() }}` is included on the page. Maybe it has something to do with CSRF tokens?

**Comment by bencroker** [comment]
> Yes, this leads to a cache refresh also on the Staging environment. But on both environments, it doesn't happen all the time.

That's strange that it would happen only sometimes. Is `Clear Cache Automatically` definitely disabled in the staging environment? If you can send credentials to the staging server to info@putyourlightson.net along with the exact steps to reproduce then we'll take a closer look.

It shouldn't have anything to do with CSRF tokens. More likely, the comment, which is an element ty

**Comment by martinhellwagner** [comment]
I'll see to it that you get access to the Staging environment.
The parameter is disabled here, yes:

![Screenshot 2020-04-08 at 20 44 12](https://user-images.githubusercontent.com/19146752/78821407-ba60ed80-79d9-11ea-8f11-342500b0b6e1.png)

**Comment by martinhellwagner** [comment]
One more idea: I was looking through the global sets and saw that we have a global set that is used in the index template of some of the sub sites – where it's used, it's also cached by Craft. Even though it's not changed, might this still be an issue every time the cache is expiring for the index template?

**Comment by martinhellwagner** [comment]
In general, could it help to set this parameter to false in the config file?

`'refreshCacheAutomaticallyForGlobals' => true,`

**Comment by bencroker** [comment]
Unless the global set is being _saved_, it shouldn't make a difference.

**Comment by martinhellwagner** [comment]
I don't think it is, actually.

**Comment by martinhellwagner** [comment]
Just confirmed that on another project of ours, this is happening as well with the combination Blitz + SEOmatic.

**Comment by martinhellwagner** [comment]
@bencroker 

Yes, this is definitely the problem. When I comment out this line in the SEOmatic integration (line 42 in `Seomaticintegration.php`), everything works as expected:

```
Blitz::$plugin->refreshCache->refreshAll();
```

Seems like the a `nystudio107\seomatic\events\InvalidateContainerCachesEvent` doesn't send any data about its URI, Site ID, Source or Source Type, thus leading to a full cache refresh?

**Comment by bencroker** [comment]
Paging @khalwat of @nystudio107 for input.

**Comment by martinhellwagner** [comment]
I've already opened an issue there as well with my above comment. 🙂

**Comment by bencroker** [comment]
No need to open 2 issues for the same issue, which we are already troubleshooting here.

@khalwat  to summarise, @martinhellwagner is claiming that SEOmatic is triggering an `EVENT_INVALIDATE_CONTAINER_CACHES` event with all values set to `null` when an entry is saved, thereby triggering Blitx to refresh the entire cache:
https://github.com/putyourlightson/craft-blitz/blob/5d585ae5085931f5c13c083bdcb0d89b3d945cfe/src/drivers/integrations/SeomaticIntegration.php#L38-L43

**Comment by martinhellwagner** [comment]
We could also reproduce the refresh when creating an entry and posting a comment, using this plugin:
https://verbb.io/craft-plugins/comments

**Comment by khalwat** [comment]
Here are the 3 places where `EVENT_INVALIDATE_CONTAINER_CACHES` is triggered:

https://github.com/nystudio107/craft-seomatic/blob/v3/src/services/MetaContainers.php#L687

https://github.com/nystudio107/craft-seomatic/blob/v3/src/services/MetaContainers.php#L726

https://github.com/nystudio107/craft-seomatic/blob/v3/src/services/MetaContainers.php#L753

Only in `MetaContainers::invalidateCaches()` does is pass in `null` for all of these things. `MetaContainers::invalidateCaches()` is only called in two places:

https://github.com/nystudio107/craft-seomatic/blob/v3/src/Seomatic.php#L369

https://github.com/nystudio107/craft-seomatic/blob/v3/src/Seomatic.php#L521

So if I had to guess... if `TemplateCaches::EVENT_AFTER_DELETE_CACHES` is being thrown after saving an element, this could cause it to happen. Thoughts @bencroker ?

**Comment by khalwat** [comment]
In thinking about it, `TemplateCaches::deleteCacheById()` (which is what triggers `TemplateCaches::EVENT_AFTER_DELETE_CACHES` ) is called via a Queue Job that's triggered by saving an entry. I'm wondering if my clearing the caches here is necessary.

I've removed it in `dev-develop` so you can test to see if it has fixed the issue for you -> https://github.com/nystudio107/craft-seomatic/commit/0f891bee83f451ef5bba4f3c6a208ba0795ff388

**Comment by khalwat** [comment]
lmk @martinhellwagner

**Comment by martinhellwagner** [comment]
Will test and let you know. Thanks in advance, @khalwat! And thanks to @bencroker as well! 👍

**Comment by khalwat** [comment]
Cool yep ping me when you've tested it @martinhellwagner

**Comment by martinhellwagner** [comment]
@khalwat 

I've watched the cache for an hour and it hasn't been refreshed (as it should). Thanks again! As well to @bencroker. I'm watching it a little more, but I think this ticket can be closed. 🙂

**Comment by bencroker** [comment]
Glad to hear it!
