### ISSUE TITLE
Cloudflare caches dynamic content

### ISSUE THREAD

**Issue by redkrupp** [putyourlightson/craft-blitz#206]
{{ craft.blitz.getTemplate('_partials/nav-main') }}

contains dynamic menu stuff like

                {% if currentUser %}
                    <a href="{{ url('logout') }}" class="nav-link w-nav-link{% if craft.app.request.segment(1) == 'login' %} w--current{% endif %} last">Sign Out</a>
                {% else %}
                    <a href="{{ url('dashboard') }}" class="nav-link w-nav-link{% if craft.app.request.segment(1) == 'login' %} w--current{% endif %} last">Sign In</a>
                {% endif %}

and does work even when blitz is enabled but when I apply cloudflare rule according to the docs

    domain.com/*
    Cache Level - Cache Everything

it get's ignored. Is there a workaround to make it work even with html caching enabled?

**Comment by bencroker** [comment]
As per the [docs](https://putyourlightson.com/plugins/blitz#reverse-proxy-purging), did you set “Browser Cache TTL” to ​“Respect Existing Headers” in the ​“Caching” page of the domain in your Cloudflare account?

**Comment by redkrupp** [comment]
Ben,

yes, this setting is in there.

**Comment by bencroker** [comment]
What do you have `Caching Level` set to under `Caching` in Cloudflare?

**Comment by redkrupp** [comment]
Caching level is set to standard.

**Comment by bencroker** [comment]
Are you able to see the response of the AJAX request in the console? 
Can you perhaps share a public URL here or send to info@putyourlightson.net so we can take a closer look?

**Comment by johndwells** [comment]
Came here to report a similar experience. Same setup as @EmptyStreets:

Caching Level: Standard
Browser Cache TTL: Respect Existing Headers

I can see 2 options:

- add a 2nd Page Rule that bypasses the cache for any actions* URLs, or
- Change Caching Level to "No query string"

In my case both should actually work OK. But I was really surprised this happened in the first place.

@bencroker would there be a drawback to making these ajax requests POSTs instead?

Any idea why CF would have decided to not respect the Browser Cache TTL?

**Comment by bencroker** [comment]
After our conversation, Cloudflare went back to respecting the headers and correctly caching and not caching dynamic pages. Maybe you can update us if you discover the reason @johndwells.

Regarding your question about POST requests, they are generally slower and Craft requires a CSRF token for all posted requests. This behaviour could be disabled but I don't think it would provide any obvious benefits.

**Comment by johndwells** [comment]
@bencroker Will do, and good point about POSTs. Thanks again for your time, I really appreciate it!
