### ISSUE TITLE
Error connecting to repository: Unable to find the Git executable.

### ISSUE THREAD

**Issue by kayqq** [putyourlightson/craft-blitz#207]
### Question
`Error connecting to repository: Unable to find the Git executable.`

We are unsure what permissions the plugin needs and where to even grant the permissions that will enable the plugin to be able to find the git executable. We have Craft deployed on AWS EC2 instances.

When the plugin runs the GitDeployer.php as root, it is able to do both `type -p git` and `which git`. However when we have a non root user run the GitDeployer.php, the commands `type -p git` and `which git` do not work.

**Comment by bencroker** [comment]
Does explicitly setting the path to the git executable in the config file help?
https://github.com/putyourlightson/craft-blitz/blob/3.6.2/src/config.php#L184-L187

**Comment by kayqq** [comment]
So I tried just setting these settings via config file and am now getting an internal server error when visiting /admin/settings/plugins/blitz.

```
return [
  '*' => [
    'cachingEnabled' => true,
    'commands' => [
      'git' => '/usr/bin/git',
    ],
  ]
];
```

Edit: I commented out the commands snippet and the settings stopped erroring. So it seems like there is some issue using PHP accessing /usr/bin/git

**Comment by kayqq** [comment]
I actually figured it out, there was some white spacing added when I copied and pasted code over.

**Comment by bencroker** [comment]
Ok, so is it working for you now?
