### ISSUE TITLE
Cache files not creating, directory permissions related maybe

### ISSUE THREAD

**Issue by kayqq** [putyourlightson/craft-blitz#208]
### Question
Blitz plugin is not creating cache files in @webroot/cache/blitz. The blitz.log shows a message saying `Blitz cache successfully refreshed and queued for warming.` and the queue table  in the database shows a job made and then cleared out which shows that it is working but I do not see any cache files outputted. I am assuming that there is some sort of permission needed but I am at a loss to where to grant it and what the plugin needs. 

I have already tried chmod'ing the @webroot folder to be 777

### Additional context
AWS EC2 instance (Linux 4.14.171-105.231.amzn1.x86_64)
PHP 7.3.15
putyourlightson/craft-blitz: ^3.6
craftcms/cms: 3.3.16.1,

**Comment by bencroker** [comment]
Can you show me your Blitz plugin settings page (general, cache storage and advanced tabs)?

**Comment by kayqq** [comment]
I am using the console UI for configuring the settings and the blitz.php config file for setting the git binary. 
Here are the settings in blitz.php format:

```
  '*' => [
    // General Settings
    'cachingEnabled' => true,
    'includedUriPatterns' => [
      [
        'siteId' => '1',
        'uriPattern' => '.*',
      ],
    ],

    // Cache Storage Settings
    'cacheStorageType' => 'putyourlightson\blitz\drivers\storage\FileStorage',
    'cacheStorageSettings' => ['folderPath' => '@webroot/cache/blitz'],

    // Cache Warming Settings
    'cacheWarmerType' => 'putyourlightson\blitz\drivers\warmers\GuzzleWarmer',
    'cacheWarmerSettings' => ['concurrency' => 8],

    // Remote Deployment Settings
    'deployerType' => 'putyourlightson\blitz\drivers\deployers\GitDeployer',
    'deployerSettings' => [
      'gitRepositories' => [
        '3e946e73-c719-4581-b519-b2fbac3d93a4' => [
          'repositoryPath' => '/var/www/html/static-site',
          'branch' => 'development',
          'remote' => 'origin',
        ],
      ],
      'commitMessage' => 'Blitz auto commit',
      'username' => 'git_username',
      'personalAccessToken' => 'GIT_PERSONAL_ACCESS_TOKEN',
      'name' => 'Blitz',
      'email' => 'gituser@email.com',
      'commandsBefore' => '',
      'commandsAfter' => '',
    ],

    // Advanced Settings
    'clearCacheAutomatically' => true,
    'warmCacheAutomatically' => true,
    'queryStringCaching' => 0,

    // Other settings
    'commands' => [
      'git' => '/usr/bin/git',
    ],
  ]
```

**Comment by wihodges** [comment]
I'm having this same issue, I updated my bltiz.php config to the new version and still no result. The queue runs [appears successful] but then no pages show being cached.

So I've got Blitz running on couple other sites in production and it works - trying to figure out what is different in this build and I can't find anything.

**Comment by bencroker** [comment]
Can you both perhaps try setting the cache storage path to an absolute path? If not explicitly defined, `@webroot` is determined by Craft at run-time and the method of doing so is rather simplistic: 
https://github.com/craftcms/cms/blob/3.4.15/src/console/Request.php#L29-L41

**Comment by kayqq** [comment]
I actually found your debug mode config and tried that which showed me: 
```
Client error: `GET https://subdomain.domain.com/slug/slug-slug/` resulted in a `401 Unauthorized` response:
```

I think I'm getting this because I have an .htaccess auth wall blocking the requests. Is there anyway to set the username/password to request with?

**Comment by wihodges** [comment]
Ok so couple things, I noticed that on my other two installs that work in production, I actually haven't updated in a bit.I see there was a possibly a bigger update in 3.5.2. 

Also since you mentioned setting an absolute path I noticed on the working production version it appears as: "//home/user/webapplications/site-root-folder/web/cache/blitz/sitename.com"
The non working [current/up to date version] appears as:
"//home/user/webapplications/site-root-folder/web/cache/blitz"
And is missing the sitename from automatically showing.

I set the cache storage path to absolute path but still same result. Warming cycles, but then still shows 0 pages cached. I played aroud with URI pattern to store but have the all page wildcard in .*

**Comment by bencroker** [comment]
@kayqq The Guzzle warmer needs your site to be publicly accessible. If it is not (although I don't see why you'd need to cache a non-public site) then you can try using the Local warmer.

@wihodges Can you also try enabling `debug` mode (see https://putyourlightson.com/plugins/blitz#debugging)? 
And do you have an absolute URL in the site's base URL? See the note about using `@web` here:
https://putyourlightson.com/plugins/blitz#the-site-is-not-being-cached-when-using-console-commands

**Comment by kayqq** [comment]
@bencroker We need to cache non-public sites as we have other environments for development and testing. We would need to test out the plugin and figure out the setup before applying on a production level site. 

What main differences are there with the local warmer and guzzle warmer? I can see that the docs say 

>  This warms the cache by mocking requests and having Craft handle them without making any external requests.

But what does "external requests" refer to specifically?

**Comment by kayqq** [comment]
Just tried the Local Warmer setting and and am getting the following error for every page:

> Page not cached because a `blitz:cacheRecords` mutex could not be acquired.

@bencroker Any suggestions for this issue as well?

**Comment by wihodges** [comment]
@bencroker Well my issue was kinda dumb in retrospect. So not sure why but with PHP 7.4, I was'nt seeing any errors in blitz.log other than client errors for pages of categories that didnt have templates associated with views. But once I switch to PHP 7.3 saw server 500 get error, which led me down the siteid and url path. I finally saw that **my 'siteurl'  in general.php config was set to null** - oddly this has no other concequences that I noticed. 

Apologies for hijacking this issue.

**Comment by bencroker** [comment]
@wihodges Glad to hear you managed to figure out the issue!

> What main differences are there with the local warmer and guzzle warmer?

@kayqq The guzzle warmer sends a request out over HTTP to the site, as if an anonymous visitor was requesting a site URL. The local warmer instead mocks a server request to Craft from withing a server request.

> Just tried the Local Warmer setting and and am getting the following error for every page:
> Page not cached because a blitz:cacheRecords mutex could not be acquired.

I haven't come across this issue before. Can you try setting the [mutexTimeout](https://github.com/putyourlightson/craft-blitz/blob/3.6.2/src/config.php#L181-L182) config setting to a higher value like `5` and see if that helps?

**Comment by kayqq** [comment]
Gotcha, we just decided to just make the site public which now works well. We didn't dive too deep in the Local Warmer error as we are still trying to see if this plugin will work for our use case.

Thanks for the all the help Ben.

**Comment by bencroker** [comment]
Ok, sure thing!
