### ISSUE TITLE
Option to disable auto-caching

### ISSUE THREAD

**Issue by thaoms** [putyourlightson/craft-blitz#21]
We have a site with a lot of urls (including a calendar with clickable days..) and when the user adds new events to the calendar, it warms all links to that calendar.

This builds up after a while in the queue, so is there any way to disable the auto-cache so the user can do all his changes and then start the warming just once.

We also do cache warming after each site deploy with SSH.

**Comment by putyourlightson** [comment]
I could add a setting to disable auto warming of the cache, would that work for you?

**Comment by thaoms** [comment]
That would be great.

Thank you

**Comment by putyourlightson** [comment]
Added in https://github.com/putyourlightson/craft-blitz/commit/b669f343012daa9a9a6afff742a4cacc8562858e
