### ISSUE TITLE
Possible to extend the EVENT_BEFORE_WARM_CACHE event?

### ISSUE THREAD

**Issue by kayqq** [putyourlightson/craft-blitz#210]
Hey Ben would it be possible to extend the EVENT_BEFORE_WARM_CACHE event? If so do you have any examples of writing a module doing this? I want to use the GuzzleWarmer but I want to add a custom pre-warm event.

**Comment by bencroker** [comment]
Sure, here's an example:

```php
Blitz::$plugin->cacheWarmer->on(BaseCacheWarmer::EVENT_BEFORE_WARM_CACHE, 
    function(RefreshCacheEvent $event) {
         // your code here
    }
);
```
