### ISSUE TITLE
Add ability to rewrite site URLs

### ISSUE THREAD

**Issue by bencroker** [putyourlightson/craft-blitz#211]
Feature request to add the ability to rewrite site URLs, either during warming or deployment, TBD.

**Comment by kayqq** [comment]
Initially I thought doing a headers check in the general.php for X-Blitz-Warmer and switching the siteUrl based on the result would work, however it seems like when I switch out the siteUrl the plugin stops working.

```
// config/general.php

$isBlitzWarmer = $request->getHeaders()->has('X-Blitz-Warmer');

return [
  'dev' => [
    ...
    ...
    'siteUrl' => $isBlitzWarmer ? 'https://blitz.static-site.com' : 'https://internal.cms-site.com',
  ]
]

```

Ideally we want a custom siteUrl to override the siteUrl in general.php for only when Blitz makes a request during the cache building process.

**Comment by bencroker** [comment]
@kayqq I'm wondering how necessary this feature is, as I think most of the configuration of site URLs should be doable via Craft. Can you explain your use-case, and why neither setting the base site URL to `https://blitz.static-site.com` nor only using relative URLs in your templates is a sufficient solution?

**Comment by bencroker** [comment]
Any update on this @kayqq?

**Comment by bencroker** [comment]
Closing due to lack of response.
