### ISSUE TITLE
Timeout saving Entry Types with large element caches table

### ISSUE THREAD

**Issue by john-henry** [putyourlightson/craft-blitz#213]
### Describe the bug
When adding a new entry type or saving an entry type we are receiving a time out. granted the time out is from CF max amount of seconds.

After a bit of troubleshooting I am concluding this is only when the `blitz_elementcaches` is full. So I'm talking like 1 million +

If I clear Blitz cache records then the saving of entry types happens instantly

So question is, are both directly related and does Blitz run routines here when adding new fields to layouts or saving sections etc?

### Versions
- Plugin version:3.6.2
- Craft version:.4.15

**Comment by bencroker** [comment]
When you save an entry type, Craft resaves every single entry in that entry type. I added a check and am forcing batch mode when a section or entry type is saved in https://github.com/putyourlightson/craft-blitz/commit/038261ce574a62eb032be9b203e05eba6059b41f. Are you able to test the effects of this in a development environment or your issue happening only in production?

**Comment by john-henry** [comment]
This is a brand new Entry type with no entries associated with it yet. So no job is triggered as far as I'm aware. 

Section has existed for a while and there are 10+ types

So try to create a new entry type and it times out. I clear Blitz db cache and I can save entry type. I let cache build up again substantially and I cant add another field to Entry type as it times out also. Still no entries for entry type.

I will test change in our dev environment. I will wait for live to build up cache table again and then sync with dev so I mightn't get back to you straight away but in the next day or two for sure

**Comment by bencroker** [comment]
Yeah that's strange. Let me know how it goes in your local test and we can take it from there.

**Comment by bencroker** [comment]
@john-henry Can you please take a look at https://github.com/putyourlightson/craft-blitz/issues/215#issuecomment-621141360 and see if this might be the same issue as you are having?

**Comment by john-henry** [comment]
@bencroker Looks like it could be it

**Comment by bencroker** [comment]
Is the site in question running SEOmatic?

**Comment by bencroker** [comment]
I've just released Blitz 3.6.5 which fixes an issue with the SEOmatic integration and, I believe, the cause of this issue.
