### ISSUE TITLE
(re-)saving a single section entry type throws an error

### ISSUE THREAD

**Issue by billythekid** [putyourlightson/craft-blitz#215]
### Describe the bug

I've come across a bug where if you go in to a single entry type and try to save it it'll throw an error about elementIds (/services/RefreshCacheService.php:210)

I initially thought this was a Craft bug as it was happening with "normal" site stuff. Here's what I wrote to them:

I'm having a weird issue where I can't save or delete a single section on this site we're developing at the moment. It feels like something's gotten orphaned or something here but I'm not sure where to start digging. 

I've tried some cli stuff like fix-element-uids, rebuild project config and clearing all the caches but nothing's fixing it.

Anyway, when attempting to delete it I get this error in the XHR to https://ma.test/index.php?p=admin/actions/sections/delete-section : {"error":"Trying to access array offset on value of type null"}

...and it doesn't get removed.

[here's the stacktrace](https://github.com/putyourlightson/craft-blitz/files/4550933/stacktrace.txt)

The weird thing was that locally the fields on the field layout were there, but when I pushed to staging (which then pulls the project yaml in and syncs everything up) the entry section was there but there were no fields in it. When pushing to staging after deleting the section on staging it appeared in the trash! It's like it's half-working somehow!

I've disabled blitz and everythign works fine and I'm pretty sure I can re-enable it when we're ready to put the site out, this is just a bug that'll only happen during development I think.

### To reproduce
Steps to reproduce the behaviour, obviously have blitz enabled for these, debug mode on:
1. Go to any "single" section and add some fields to the field layout
2. Save it
3. See error message yii\base\ErrorException: Undefined index: elementIds in /Users/billythekid/Sites/m-g/ma.test/vendor/putyourlightson/craft-blitz/src/services/RefreshCacheService.php:210 [rest f stack trace]

1. Go to singles section and open dev tools, network tab (There's no visual feedback otherwise)
2. Delete the section, confirm
3. Observe JSON error in network response {"error":"Trying to access array offset on value of type null"}
4. Refresh the page or go to the single section and see the entry is not deleted.

### Expected behaviour
1. For the entry to save without errors
2. For the entry to delete without errors

### Versions
- Plugin version: 3.6.3
- Craft version: 3.4.17.1

**Comment by bencroker** [comment]
Thanks for reporting this. After some investigating, I believe this may be an issue with the SEOmatic integration in Blitz. Can you please confirm whether you have SEOmatic installed? If so then https://github.com/putyourlightson/craft-blitz/commit/a0fcd17b170f7b9a6e51e52b101600aa7bcb9c82 should fix it.

**Comment by billythekid** [comment]
@bencroker ah cheers Ben, yeah I can confirm this site has SEOmatic in it as well. Sorry, I should have given you the full plugin list at the time.

Cheers for the answer.

**Comment by bencroker** [comment]
Just released 3.6.4 with the fix.
