### ISSUE TITLE
Blitz slows CP down, more than 300.000 jobs in Queue-Manager

### ISSUE THREAD

**Issue by DavidKabelitz** [putyourlightson/craft-blitz#217]
### Describe the bug
For a couple of weeks Blitz is slowing down CP in an extrem way, it was needed to turn off "Clear Cache Automatically" and "Warm Cache Automatically"... more than 300.000 jobs were generated in less than 12 hours.

Don't know what this caused.

### Versions
- Plugin version: 3.6.4
- Craft version: Craft Solo 3.4.17.1

**Comment by bencroker** [comment]
Have you looked at the common issue here?
https://putyourlightson.com/plugins/blitz#the-refresh-cache-queue-jobs-run-for-long-periods-of-time-and-sometimes-pile-up

> For very large sites, sites that don’t use eager-loading of elements in the templates, or sites that contain many relationships between elements, Blitz may need to check against thousands of element queries each time a refresh cache queue job is run.

**Comment by DavidKabelitz** [comment]
Hi, in this case we do not run a large site, but i will try to change the php.ini settings. Thanks für the advice, maybe it's already the solution

**Comment by bencroker** [comment]
Ok, let me know how it goes.

**Comment by DavidKabelitz** [comment]
Hi, the settings change helped a bit but still at lot in queue. So the problem is not solved. We disabled auto updates again.

**Comment by bencroker** [comment]
What exactly did you change?

**Comment by DavidKabelitz** [comment]
max_execution_time and memory_limit

**Comment by bencroker** [comment]
I was referring to the common issue entitled “The refresh cache queue jobs run for long periods of time and sometimes pile up”. That should give you some direction in terms of steps you can take to improve the situation.

**Comment by DavidKabelitz** [comment]
Yes but it is not a complex or large site, that's why i was wondering. We will look into it again. Thx

**Comment by bencroker** [comment]
Maybe I misunderstood the issue. What kinds of jobs are in the queue? And what version of Blitz and Craft are you running?

**Comment by DavidKabelitz** [comment]
Version details are at the first comment. With the old settings there were more than 300.000 "Warm Cache Automatically" jobs at the list. Now we are talking about 12.000 jobs after less a day. And by the way there are 110 cached pages.

**Comment by bencroker** [comment]
Something doesn't seem to be right. Do you have FeedMe importing entries or any other automated method entry updating happening? If you send credentials to info@putyourlightson.net then we can take a look in the control panel to see if anything stands out.

**Comment by DavidKabelitz** [comment]
Indeed there are FeedMe Entries but those are not running. I can delete those, not needed anymore

**Comment by DavidKabelitz** [comment]
Nope, even after removing feedMe were 27.000 jobs in list in less an hour

**Comment by bencroker** [comment]
Something must be spawning those jobs. Do they ever complete? And what actions queue them up? Do you have any cron jobs set up?

**Comment by DavidKabelitz** [comment]
nope never complete...most of them are "warm ups" jobs...with warm up disabled everything is fine. No cron jobs are set up. Because it's related to the CP i guess template Cache settings are not the problem or? At our config is still enableTemplateCaching on true. Just because we never had problems with both.

**Comment by bencroker** [comment]
I would try setting `enableTemplateCaching` to `false` to narrow down the issue.

**Comment by DavidKabelitz** [comment]
ok i will test it later today, because we have traffic on the site. Fingers crossed ;)

**Comment by bencroker** [comment]
Do you have SEOmatic installed and if yes then at what version?

**Comment by DavidKabelitz** [comment]
Yes, we are using 3.3.1 but will later update to 3.3.2

**Comment by bencroker** [comment]
I've just released Blitz 3.6.5 which fixes an issue with the SEOmatic integration and, I believe, the cause of this issue.

**Comment by DavidKabelitz** [comment]
awesome
