### ISSUE TITLE
When you delete a template, does the template get deleted from the deployment repo

### ISSUE THREAD

**Issue by richardfrankza** [putyourlightson/craft-blitz#218]
### Question

When you delete a template, does the template get deleted from the deployment repo?

I seem to have a lot of stale templates in my git repo which gets deployed to Netlify. So for instance, if I created a section called "news" and then deleted it later, it appears as if the folder is correctly cleared from the Blitz cache directory but not from the related git repo specified in the Git Deployer settings. 

I would rather Blitz include only files that are explicitly cached and not leave stale directories in the git repo, otherwise I run the risk of serving stale content to my users?

### Additional context
Craft version: 3.4.17.1
Blitz version:3.6.4

**Comment by bencroker** [comment]
I agree that this could work better, marking as a feature request.

**Comment by bencroker** [comment]
Added in https://github.com/putyourlightson/craft-blitz/commit/ac97bee9dda37749bec3be3dc98045294f3b8e4e for the next release.

**Comment by bencroker** [comment]
Released in 3.7.0.
