### ISSUE TITLE
Setting unknown property: putyourlightson\blitz\drivers\purgers\DummyPurger::zoneIds

### ISSUE THREAD

**Issue by michaeljoy** [putyourlightson/craft-blitz#219]
### Describe the bug
While blitz is disabled, I selected clear and warm all pages in the cache. Realizing that it was disabled and nothing was in the work queue, I quickly went to enable blitz cache setting. I enabled, but it did not appear to save the setting and the toggle was still in the disabled setting so I force refreshed the page and it was still disabled. I navigated back to the main admin dashboard and then went to enable the toggle again. Afterwards I navigated back to the main control panel. When I finally went back to check if the setting had changed I got a stack trace debug message : 

Setting unknown property: putyourlightson\blitz\drivers\purgers\DummyPurger::zoneIds

I am now completely unable to enter any Blitz setting or menu item without throwing this error.

### To reproduce
Steps to reproduce the behaviour:
1. Go to blitz settings menu and verify cache disabled. 
2. Go to blitz menu. 
3. Select clear and warm all pages in the cache.
4. Go to blitz settings menu and verify cache disabled. Enable cache and save.
5. Go to admin menu.
6. Go to blitz menu and enable cache and save.
7. Go to admin menu.
8. Go to blitz menu and enable cache and save.
9. Go to blitz menu and get debug stack trace error:

Setting unknown property: putyourlightson\blitz\drivers\purgers\DummyPurger::zoneIds

### Expected behaviour
Enabling cache and saving, actually enables the cache and does not completely break blitz plugin entirely. (Note: this appears to be browser caching/timing related. I suspected that Firefox 76 was caching something, although I was accessing the server directly not through our usual CDN cache paths) This was all done very quickly as I was impatient, so some incomplete state change must have placed things in an indeterminate state somehow.

### Screenshots
admin/utilities/blitz-cache
<img width="1653" alt="Screen Shot 2020-05-06 at 11 59 16 AM" src="https://user-images.githubusercontent.com/1153676/81206139-493d3780-8f91-11ea-8425-4d26709d652a.png">

### Versions
- Plugin version: 3.6.4
- Craft version: 3.4.18

**Comment by bencroker** [comment]
It sounds like you may have saved the settings while they were still in the process of loading. Either way, your purger settings are out of sync. Try adding the following [config settings](https://putyourlightson.com/plugins/blitz#config-settings) in a `blitz.php` config file:

```
return [
    '*' => [
        // The purger settings.
        'cachePurgerSettings' => [],
    ]
];
```
