### ISSUE TITLE
./craft blitz/cache/clear not deleting files

### ISSUE THREAD

**Issue by thaoms** [putyourlightson/craft-blitz#22]
`./craft blitz/cache/clear` with ssh doesn't work, it shows:

```
Clearing Blitz cache.
Blitz cache successfully cleared.
```

but the files are still there.

Using the button in the control panel does work and clears the files.

**Comment by putyourlightson** [comment]
I can't replicate the issue locally, are you using version 1.5.2?

**Comment by thaoms** [comment]
Yes, I'm trying to make it work with a cronjob.

For now I'm using `/craft blitz/cache/warm` which seems to work.

**Comment by putyourlightson** [comment]
The `warm` command calls the `clear` command to begin with so I'm not sure how that could work and clearing not work. Have you tested it by running the command on the server?

**Comment by thaoms** [comment]
I was wrong, warm does work but clearing does not (only through console commands, CP is fine).
I've noticed in CacheController.php these rules:
```

$cacheFolders = Craft::$app->getRequest()->getBodyParam('caches');

        if (is_array($cacheFolders)) {
            foreach ($cacheFolders as $cacheFolder) {
                try {
                    FileHelper::removeDirectory(FileHelper::normalizePath($cacheFolder));
                }
                catch (ErrorException $e) {}
            }
        }
        else {
            Blitz::$plugin->cache->clearCache();
        }

```
Does `Craft::$app->getRequest()->` work with console commands? The clearing through console doesn't work for me locally and on a remote server.

**Comment by thaoms** [comment]
I noticed that this gives me a wrong url:
`FileHelper::normalizePath(Craft::getAlias('@webroot').'/'.$settings->cacheFolderPath)`

It seems that `@webroot` is returning me this:
`/checkout/master/11cb01b5f03a37017c2a289d0acde2525592fa2a/cache/blitz
`
while it needs to be this:
`/checkout/master/11cb01b5f03a37017c2a289d0acde2525592fa2a/www/cache/blitz`

I have this in the CP settings:
Cache Folder Path: cache/blitz

My public folder is `www`

This might have something to do with that my index.php file lives in www, but console commands go through ./craft which is one level higher. That explains why CP commands are working and console's are not.

I fixed it by replacing all `@webroot` instances by `@root` inside `CacheService.php` and adding my www folder to my Cache Folder Path in the CP: www/cache/blitz.

But I'm no php developer so this might be wrong.


**On another note:** 
I also noticed a fair amount of records in the blitz DB tables, even after clearing through the CP.
Do those tables ever get cleared?

**Comment by putyourlightson** [comment]
Craft will detect your web root even in console commands, if it is one of `web`, `public` or `public_html`. Since you are using `www`, it is not being detected. The best way to fix this is to define the `@webroot` alias using the [aliases](https://docs.craftcms.com/v3/config/#aliases) config setting in your general config file.

Regarding your note, the database tables can get quite large as the plugin is tracking what elements and element queries affect what URLs. They are kept as up to date as possible and will rarely be completely cleared as otherwise you would lose the cache busting functionality.

**Comment by thaoms** [comment]
Thanks! I did not know that.

Just for the sake of it, my solution:

```
‘aliases’ => [
   ‘@webroot’ => ‘@root/www/’
 ]
```

**Comment by putyourlightson** [comment]
Thanks for posting that!
