### ISSUE TITLE
No plugin exists with the handle "blitz"

### ISSUE THREAD

**Issue by kayqq** [putyourlightson/craft-blitz#220]
### Describe the bug
Getting the error: `No plugin exists with the handle "blitz".` when trying to install blitz.

### To reproduce
1. Install Blitz via composer install or plugin store install
2. Go to Control Panel->Settings->Plugins and click 'Install Plugin' to enable the plugin.
3. See error message `No plugin exists with the handle "blitz`

### Expected behaviour
Should be seeing an enabled Blitz plugin

### Versions
- Plugin version: 3.6.3, tried 3.6.4 as well
- Craft version: 3.4.17.1

**Comment by bencroker** [comment]
Just did a test locally installing a fresh copy of Blitz without any issues. Can you run `composer remove putyourlightson/craft-blitz`, then `composer require putyourlightson/craft-blitz` again and see if that makes any difference? If not then please check the logs for any more descriptive error messages or a stack trace.

**Comment by kayqq** [comment]
I ran the remove command then did a require command, same result.
I did forget to mention earlier is that my url goes to `admin/settings/plugins/blitz?welcome=1` 
But browser shows me this error:

<img width="1324" alt="Screen Shot 2020-05-07 at 1 10 03 PM" src="https://user-images.githubusercontent.com/19341583/81340507-d1d8d800-9064-11ea-9bd4-4616f9b098a7.png">

I checked the DB after a fresh install and can confirm that the blitz tables are created and the plugins table shows a row for blitz.

**Comment by bencroker** [comment]
If you go to the _Settings → Plugins_ page, is Blitz listed as installed?

**Comment by kayqq** [comment]
No it still says "Not installed"

**Comment by bencroker** [comment]
Can you check for errors in the logs when you try to install? Maybe also try manually deleting the Blitz database tables before installing again.

**Comment by kayqq** [comment]
Okay so I think what worked was doing `composer clear-cache` while ssh'ed into my Vagrant box and doing `composer install` from there. 

It seemed like my composer autoload files were out of sync some how. 
Anyways thanks Ben and sorry for troubling you!

**Comment by bencroker** [comment]
Glad to hear you got it working!
