### ISSUE TITLE
Server rewrite with unicode in slug dont get served

### ISSUE THREAD

**Issue by espensgr** [putyourlightson/craft-blitz#222]
### Describe the bug
I have a page in Norwegian and we use characters like æ, ø and å in the slug of pages.
So one page has `/miljø-samfunnsansvar` and another has `/interior`.
The folder for the first one is saved as `milj%C3%B8-samfunnsansvar` and the other `interior`.
So when i visit the site i get `<!-- Served by Blitz on [timetamp] -->` on the first one.

If i manually rename the folder to `miljø-samfunnsansvar` it works.
This is an issue for both the apache and nginx config, with the example code in the documentation. And i have this issue on both my local Mamp and my Forge server.

So i dont know if this is a server translation of the folder, or if the folder has to get saved with another name.

### Versions
- Plugin version: 3.6.5
- Craft version: 3.4.20

**Comment by bencroker** [comment]
Fixed in https://github.com/putyourlightson/craft-blitz/commit/7be9930bd912f1489b16813cf8d4579605823d51, feel free to test before the next release.
