### ISSUE TITLE
Query string with encoded characters doesn't get served by .htaccess rewrite

### ISSUE THREAD

**Issue by Antimated** [putyourlightson/craft-blitz#224]
### Describe the bug
When entering a query string with **multiple** parameters and at least 1 encoded character you get served by a 404-message whenever that page is **_already cached_** AND you have **server rewrites enabled** (in our case we used .htaccess rewrites). Maybe not relevant but we have a multi-site setup (with multiple languages)

### To reproduce
As an example we'll use the character `,` (encoded to `%2C`). I'll show some examples of query strings that **_do_** and **_don't_** work

Query strings that **_do_** work after the page is already cached (a.k.a. after a page refresh)

1. `?param=foo%2Cbar`
2. `?param=foo%2Cbar%2C=john`

Query strings that **_don't_** work after the page is already cached (a.k.a. after a page refresh)

1. `?param=foo%2Cbar%2Cjohn&otherparam=`
2. `?param=foo%2Cbar%2Cjohn&otherparam=test`
3. `?param=foo%2Cbar%2Cjohn&otherparam=test%2Ctest2`
4. `?param=foo%2Cbar%2Cjohn&otherparam=test&anotherparam=xxx%2Cyyy`

### Expected behaviour
No 404 error should be given when using more than 1 query parameter

### Screenshots
**Error after refresh/cache: (`?param=foo%2Cbar%2Cjohn&otherparam=`)**

![Image 2020-05-28 at 10 47 37 AM](https://user-images.githubusercontent.com/2869409/83121816-13dcc300-a0d3-11ea-9a10-7bc8064c5fc7.png)

**Error after refresh/cache: (`?param=foo%2Cbar%2Cjohn&otherparam=test`)**

![Image 2020-05-28 at 10 49 06 AM](https://user-images.githubusercontent.com/2869409/83122105-73d36980-a0d3-11ea-86d8-3f402c648691.png)

**Error after refresh/cache: (`?param=foo%2Cbar%2Cjohn&otherparam=test%2Ctest2`)** 

![Image 2020-05-28 at 10 49 48 AM](https://user-images.githubusercontent.com/2869409/83122173-89489380-a0d3-11ea-8510-ece14d1083cf.png)

**Error after refresh/cache: (`?param=foo%2Cbar%2Cjohn&otherparam=test&anotherparam=xxx%2Cyyy`)**

![Image 2020-05-28 at 10 52 06 AM](https://user-images.githubusercontent.com/2869409/83122287-b09f6080-a0d3-11ea-8be2-3b9ecda1bc55.png)

**.htaccess rewrites**

![Image 2020-05-28 at 10 54 44 AM](https://user-images.githubusercontent.com/2869409/83122331-c2810380-a0d3-11ea-9936-b567ddde81dd.png)

### Blitz settings

- Include URI patterns: ` ` and `.*`
- Query String Caching: Cache URLs with unique query strings as unique pages

### Versions
- Plugin version: 3.6.5
- Craft version: Craft Pro 3.4.9

**Comment by bencroker** [comment]
Fixed in https://github.com/putyourlightson/craft-blitz/commit/7be9930bd912f1489b16813cf8d4579605823d51, feel free to test before the next release.
