### ISSUE TITLE
Blitz will not cache page if page has not been shared to social media previously

### ISSUE THREAD

**Issue by benjamin-smith** [putyourlightson/craft-blitz#226]
### Describe the bug

Many pages on my site have the following `og:image` tag in the HTML, presumably output because SEOmatic's "Transform Facebook OpenGraph Image" setting is enabled:

```
<meta content="https://www.example.com/index.php?p=actions/assets/generate-transform&amp;transformId=162" property="og:image">
```

The page is thus not a candidate for caching as per the change introduced in #125.

However, until that asset transform URL is hit and the asset transform is performed, that URL remains in the page's HTML. The only/most natural way that asset transform URL would be hit is when shared on social media.

### To reproduce
Steps to reproduce the behaviour:
1. Set `og:image` meta tags to use Craft asset transforms using SEOmatic
2. Attempt to load a page that is configured for Blitz caching
3. See that the page is not cached (via HTML comments in footer).

Note I was able to determine this is the actual cause by stepping through the cache logic in the source code until I narrowed down the source of the problem; this isn't a case of a misattributed logic error or something else.

### Expected behaviour
Pages can be cached by Blitz even if they have not been shared on social media. I am honestly not sure what is the best way to go about this, or if the native `{% cache %}` tags have some means to sidestep this issue.

### Versions
- Plugin version: 3.6.5
- Craft version: 3.3.17
- SEOmatic version: 3.2.35
- PHP: 7.4.x

**Comment by benjamin-smith** [comment]
I also found https://github.com/nystudio107/craft-seomatic/issues/490 with the tip to enable `generateTransformsBeforePageLoad`. I will do that to sidestep this.

Would limiting the Blitz logic (https://github.com/putyourlightson/craft-blitz/blob/9795a1d965ed5c94c047fabe958d340b7cb58e2f/src/services/GenerateCacheService.php#L170-L174) to parsing only the `<body>` tag be beneficial? The spirit of the logic in place makes sense, but since the `<head>` assets might not be loaded for a long time (until a social media share), it blocks Blitz from doing its thing in the meantime.

**Comment by bencroker** [comment]
The issue with caching pages that have the asset transform URL in them, even if in the `head` tag, is that the transform generation URL will be cached and used by social media on all subsequent requests. While I reaIise that these are not as crucial as image tags, what we really want to achieve is only caching pages with zero asset transform URLs in them. I think that enabling the `generateTransformsBeforePageLoad` config setting is the best overall solution at the moment and not sure how I feel about changing the current logic based on where in the document the asset transform tag is located.

**Comment by benjamin-smith** [comment]
That's a great point, you're right, we don't want those transform URLs cached anywhere, including social. Yes it sounds like `generateTransformsBeforePageLoad` is really the best bet here when doing full page caching. Will close this GH issue.

Thanks again!

**Comment by khalwat** [comment]
So SEOmatic does this:

https://github.com/nystudio107/craft-seomatic/blob/v3/src/helpers/ImageTransform.php#L120

```php
            // If we're not in local dev, tell it to generate the transform immediately so that
            // urls like `actions/assets/generate-transform` don't get cached
            $generateNow = Seomatic::$environment === EnvironmentHelper::SEOMATIC_DEV_ENV ? null : true;
            if ($volume instanceof Local) {
                // Preflight to ensure that the source asset actually exists to avoid Craft hanging
                if ($volume !== null && !$volume->fileExists($asset->getPath())) {
                    $generateNow = false;
                }
            } else {
                // If this is not a local volume, avoid a potentially long round-trip by
                // being paranoid, and defaulting to not generating the image now
                $generateNow = false;
            }
```

It does this weird dance to avoid a state where Craft would hang waiting for the pending image to transform.
