### ISSUE TITLE
Plugin not installing when removed earlier because of "Duplicate key name"

### ISSUE THREAD

**Issue by niekvandael** [putyourlightson/craft-blitz#227]
### Describe the bug
When installing the plugin, the error message "Couldn't install plugin" appears.
Already installed it using composer, trying to install via admin panel, settings, plugins, settings-icon on the right from 'Blitz', install.

Note: i have installed/uninstalled this plugin a few times in the past.

### To reproduce
Steps to reproduce the behaviour:
1. Go to Settings
2. Click on Plugins
3. Install Blitz plugin
4. see error message

### Expected behaviour
Blitz should install

### Screenshots
![image](https://user-images.githubusercontent.com/9558193/84570108-549f3200-ad8b-11ea-8a06-029847efdaaf.png)

### Versions
- Plugin version: 3.6.5
- Craft version: 3.4.23

### Log

2020-06-13 15:25:27 - warning - craft\db\mysql\Schema::rollBackSavepoint
Tried to roll back a savepoint, but it does not exist: SQLSTATE[42000]: Syntax error or access violation: 1305 SAVEPOINT LEVEL1 does not exist
The SQL being executed was: ROLLBACK TO SAVEPOINT LEVEL1
2020-06-13 15:25:27 - error - craft\db\MigrationManager::migrateUp
Failed to apply Install (time: 0.004s). Output:
    > create unique index blitz_caches_siteId_uri_unq_idx on {{%blitz_caches}} (siteId,uri) ...Exception: SQLSTATE[42000]: Syntax error or access violation: 1061 **Duplicate key name 'blitz_caches_siteId_uri_unq_idx'**
The SQL being executed was: ALTER TABLE `blitz_caches` ADD UNIQUE INDEX `blitz_caches_siteId_uri_unq_idx` (`siteId`, `uri`) (/opt/approot/build.20200613-152412-bb4ab90a/vendor/yiisoft/yii2/db/Schema.php:674)
#0 /opt/approot/build.20200613-152412-bb4ab90a/vendor/yiisoft/yii2/db/Command.php(1298): yii\db\Schema->convertException(Object(PDOException), 'ALTER TABLE `bl...')
#1 /opt/approot/build.20200613-152412-bb4ab90a/vendor/yiisoft/yii2/db/Command.php(1093): yii\db\Command->internalExecute('ALTER TABLE `bl...')
#2 /opt/approot/build.20200613-152412-bb4ab90a/vendor/yiisoft/yii2/db/Migration.php(495): yii\db\Command->execute()
#3 /opt/approot/build.20200613-152412-bb4ab90a/vendor/craftcms/cms/src/db/Migration.php(385): yii\db\Migration->createIndex('blitz_caches_si...', '{{%blitz_caches...', Array, true)
#4 /opt/approot/build.20200613-152412-bb4ab90a/vendor/putyourlightson/craft-blitz/src/migrations/Install.php(145): craft\db\Migration->createIndex('blitz_caches_si...', '{{%blitz_caches...', Array, true)
#5 /opt/approot/build.20200613-152412-bb4ab90a/vendor/putyourlightson/craft-blitz/src/migrations/Install.php(33): putyourlightson\blitz\migrations\Install->createIndexes()
#6 /opt/approot/build.20200613-152412-bb4ab90a/vendor/craftcms/cms/src/db/Migration.php(52): putyourlightson\blitz\migrations\Install->safeUp()
#7 /opt/approot/build.20200613-152412-bb4ab90a/vendor/craftcms/cms/src/db/MigrationManager.php(233): craft\db\Migration->up(true)
#8 /opt/approot/build.20200613-152412-bb4ab90a/vendor/craftcms/cms/src/base/Plugin.php(140): craft\db\MigrationManager->migrateUp(Object(putyourlightson\blitz\migrations\Install))
#9 /opt/approot/build.20200613-152412-bb4ab90a/vendor/craftcms/cms/src/services/Plugins.php(517): craft\base\Plugin->install()
#10 /opt/approot/build.20200613-152412-bb4ab90a/vendor/craftcms/cms/src/controllers/PluginsController.php(50): craft\services\Plugins->installPlugin('blitz', 'standard')
#11 [internal function]: craft\controllers\PluginsController->actionInstallPlugin()
#12 /opt/approot/build.20200613-152412-bb4ab90a/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#13 /opt/approot/build.20200613-152412-bb4ab90a/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#14 /opt/approot/build.20200613-152412-bb4ab90a/vendor/craftcms/cms/src/web/Controller.php(178): yii\base\Controller->runAction('install-plugin', Array)
#15 /opt/approot/build.20200613-152412-bb4ab90a/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('install-plugin', Array)
#16 /opt/approot/build.20200613-152412-bb4ab90a/vendor/craftcms/cms/src/web/Application.php(291): yii\base\Module->runAction('plugins/install...', Array)
#17 /opt/approot/build.20200613-152412-bb4ab90a/vendor/craftcms/cms/src/web/Application.php(559): craft\web\Application->runAction('plugins/install...', Array)
#18 /opt/approot/build.20200613-152412-bb4ab90a/vendor/craftcms/cms/src/web/Application.php(270): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#19 /opt/approot/build.20200613-152412-bb4ab90a/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#20 /opt/approot/build.20200613-152412-bb4ab90a/web/index.php(21): yii\base\Application->run()
#21 {main}

**Comment by bencroker** [comment]
It sounds like the plugin may not have been correctly uninstalled. Are you able to (force) delete all of the Blitz tables from the database before trying to install the plugin?

**Comment by niekvandael** [comment]
@bencroker Thank you for your response, no i did force delete any blitz tables.
I will try that next. (tables starting with blitz_)

**Comment by bencroker** [comment]
Any update @niekvandael?

**Comment by niekvandael** [comment]
Removing tables indeed worked! Thanks!
