### ISSUE TITLE
Commerce + Currencies

### ISSUE THREAD

**Issue by usefull-snippets** [putyourlightson/craft-blitz#228]
### Question
Does Blitz supports multi-currencies caching on Craft Commerce-v3?

### Additional context
Hello,

We installed Blitz plugin on our Craft Commerce-v3 site: everything works fine and the plugin looks really great.

We read the DOCs from https://putyourlightson.com/plugins/blitz and successfully excluded the /cart, /checkout and /customer pages; we implemented your solution for csrfInput() tokens; and managed to display the non-cached cart items count.

But we are facing an issue with the currencies that we don’t know how to resolve:

Our store has 3 different currencies set up: https://docs.craftcms.com/commerce/v3/payment-currencies.html

The issue is that we are not able to differentiate the cached pages by currency.
You always see the prices/currency in the currency that was set at the moment the page was cached, no matter which is your current currency selection.

Is there a way that we can sort this out? Like Blitz saving different cache per currency?

Thanks in advance.

**Comment by bencroker** [comment]
How exactly are you displaying the currency amounts in the templates? You'll likely have to do one of 2 things. You could use some JavaScript to switch the currency amounts on a user action, or you could use the [dynamic content](https://putyourlightson.com/plugins/blitz#dynamic-content) feature in Blitz to dynamically update the amount based on the current currency.

**Comment by usefull-snippets** [comment]
> How exactly are you displaying the currency amounts in the templates?

We display the currency amounts in Twig like this: 
`{{ defaultVariant.price | commerceCurrency(cart.paymentCurrency,convert=true,stripZeros=true) }}`

This is how CraftCommerce currencies work by default. When you change the site's main currency, a form is submitted and the page is refreshed setting up the new currency in a cookie or session variable. This way the next time you access the site the currency you have chosen is selected by default.

> you could use the dynamic content feature in Blitz to dynamically update the amount based on the current currency

We thought about this option but it will add dozens of ajax calls to get each price, on each page. 


Isn't it possible for you to save a different page cache according to the currency cookie? 

Ps. I sent you by email the link to our staging website so you can have a preview of how the currency switcher works.

Thanks again.

**Comment by bencroker** [comment]
> Isn't it possible for you to save a different page cache according to the currency cookie?

Blitz caches pages based on their URL alone, independently of cookies. One workaround could be to include the currency in the URL, for example `domain.com/shop?currency=usd`.

Alternatively, you could output all of the currencies for each product and then, as I mentioned above, use JavaScript to switch the currency amount based on the selected currency.

Here is an example of outputting all currencies from the [docs](https://docs.craftcms.com/commerce/v3/twig-filters.html#commercecurrency):
```twig
{% for currency in craft.commerce.paymentCurrencies %}
    Total in {{ currency.iso|upper }}: {{ cart.totalPrice|commerceCurrency(
        currency,
        convert=true
    ) }}<br>
{% endfor %}
```

**Comment by usefull-snippets** [comment]
> One workaround could be to include the currency in the URL

This option implicates that we override all the links of the page and doesn't looks nice to add the currency on each URL of the site.

> Alternatively, you could output all of the currencies for each product and then, as I mentioned above, use JavaScript to switch the currency amount based on the selected currency.

This implicates to add a JavaScript layer on top of the default way of showing prices on CraftCommerce, having potential issues like the price being empty at first sight, until JavaScript insert the real price.


As you mention, both option are workarounds. Don't you consider to extend Blitz functionality in order to be compatible with CraftCommerce Currencies.
Blitz is a super powerful, complete and great plugin. I was excited when I read about it since it resolves the caching on Craft as none other plugin does. Would be great if you can extend its support to CraftCommerce Currencies as well.


Another possible workaround would be to prevent a page to be cached and/or to serve the cached version of it, if there is a cookie set in the visitor's browser. Something similar to the current _**Exclude URI Patterns**_ but applied to cookies.
This way, Blitz will cache the page for the default currency and if the visitor changes into another currency a non-cached version of the page will be shown (based on the currency cookie).

I'm not sure if you are familiar with WP-Rocket, which is a similar cache plugin for WordPress. This is how WP-Rocket manage this:
<img width="699" alt="Screen Shot 2020-06-17 at 11 42 57" src="https://user-images.githubusercontent.com/33757930/84913350-d5627480-b090-11ea-870d-03b9c14e8739.png">

Can something similar be done with Blitz.

Thanks again for your support.

**Comment by bencroker** [comment]
Disabling caching based on specific cookies is not a feature that I'd like to build in to core. Besides added complexity, it would not work when server rewrites are used and would result in a large portion of your site being uncached. I realise that it might solve your use-case, but one could also argue that Craft Commerce could handle multiple currencies better. Note that you could add this functionality with a custom plugin/module.

I think, given what you have to work with, that the second suggestion I gave would work best in this case, namely outputing the amounts for each currency in the template (showing the default currency initially) and then using JavaScript to switch the amount based on the currently selected currency. I expect there to be very little if any noticable flicker.

**Comment by bencroker** [comment]
Another option might be to look into whether [Sprig](https://putyourlightson.com/plugins/sprig) could help out with this.
