### ISSUE TITLE
Does blitz/refresh use the warmCacheAutomatically setting?

### ISSUE THREAD

**Issue by iainhenderson** [putyourlightson/craft-blitz#229]
The './craft blitz/cache/refresh' command will clear, flush, purge, warm and deploy all of the pages. Does this command respect Blitz warmCacheAutomatically setting? or should I be running:

./craft blitz/cache/clear
./craft blitz/cache/flush
./craft blitz/cache/purge

To refresh the cache without warming? I'm running into problem with the process exceeding the timeout in a buildkite deployment script.

**Comment by bencroker** [comment]
Yes, the `refresh` command will only warm the cache if the `warmCacheAutomatically` setting is set to `true`.

**Comment by iainhenderson** [comment]
Thanks for clarifying @bencroker . I did set warmCacheAutomatically to false while testing but it was still timing out, I guess I will have to investigate increasing the timeout limit on that server.
