### ISSUE TITLE
Not consistently clearing caches using console commands after deploy.

### ISSUE THREAD

**Issue by cmalven** [putyourlightson/craft-blitz#231]
### Describe the bug
Several of my sites are occasionally failing to clear caches after deploy using the `./craft blitz/cache/refresh` console command. As a result, all references to revisioned, static files on the site (e.g. `main-b62b3afe44.css`) become outdated and broken. This _does not_ happen on every deploy, but does seem to occur roughly every 2-3 deployments.

### To reproduce
Unfortunately, the issue does not occur 100% of the time, is likely somewhat dependent on my server/deploy setup, and there are very few logs or other clues available to narrow things down.

Here are specific steps I can take to verify that the issue is a cached template:

**1. The deployment process runs the following after all files have been uploaded:**

```
Connected. Executing commands...
Executing command: '[' '!' -d releases ']'
Executing command: '[' -d releases/dde1d6f7becdd67468d1df8a05041c98ddbdc1cd ']'
Executing command: '[' '!' -d releases/dde1d6f7becdd67468d1df8a05041c98ddbdc1cd ']'
Executing command: echo 'Creating: releases/dde1d6f7becdd67468d1df8a05041c98ddbdc1cd'
Creating: releases/dde1d6f7becdd67468d1df8a05041c98ddbdc1cd
Executing command: cp -dR deploy-cache releases/dde1d6f7becdd67468d1df8a05041c98ddbdc1cd
Executing command: echo 'Linking current to revision: dde1d6f7becdd67468d1df8a05041c98ddbdc1cd'
Linking current to revision: dde1d6f7becdd67468d1df8a05041c98ddbdc1cd
Executing command: rm -f current
Executing command: ln -s releases/dde1d6f7becdd67468d1df8a05041c98ddbdc1cd current
Executing command: echo 'Linking web root to current'
Linking web root to current
Executing command: rm -f public_html
Executing command: ln -s current public_html
Executing command: echo 'Linking .env'
Linking .env
Executing command: rm -f current/.env
+Executing command: realpath shared/.env
Executing command: ln -s /www/shared/.env current
Executing command: echo 'Linking storage'
Linking storage
Executing command: rm -rf current/storage
+Executing command: realpath shared/storage
Executing command: ln -s /www/shared/storage current
Executing command: echo 'Linking web to public'
Linking web to public
Executing command: cd current
Executing command: rm -rf public
Executing command: ln -s web public
Executing command: chmod +x ./craft
Executing command: echo 'Running Craft migrations'
Running Craft migrations
Executing command: ./craft migrate/all
Yii Migration Tool (based on Yii v2.0.35)
Migrated up successfully.
Executing command: echo 'Clearing Craft cache'
Clearing Craft cache
Executing command: ./craft blitz/cache/refresh
Blitz cache successfully cleared.
Blitz cache successfully flushed.
Blitz cache successfully purged.
Executing command: cd ..
Executing command: echo 'Removing old releases'
Removing old releases
Executing command: cd releases
Executing command: tail -n +11
Executing command: ls -t
Executing command: xargs rm -rf
Commands accomplished, great!
```

According to the above, Blitz successfully cleared caches, but the browser dev tools console indicates that the linked `.css` file can't be found, and viewing the cached template in `/web/caches/sitename.com/index.html` reveals that the `link` is still pointing to the old filename, and the cached file's `<!-- Cached by Blitz on 2020-06-27T05:51:46-07:00 -->` indicates that the cache was created prior to the recent run of `blitz/cache/refresh`.

**2. Check the logs**

`/storage/logs/blitz.log` doesn't list any executions run via the console, so the logs aren't helpful in determining whether the `refresh` command actually ran successfully.

**3. Manually clear caches**

At this point, clearing the caches from within the CP will reliably clear them and the site will be back in working order with all linked files found. Refreshing from the command line using `./craft blitz/cache/refresh` at this point does seem to also clear the cache.

We also have a staging environment that is configured identically to production, and the same issue can be seen there, with roughly the same frequency.

### Additional details

- Server rewrite is disabled
- I've tried with cache warming both enabled and disabled. The issue occurs in either case, but the issue is more obvious with cache warming disabled because you'd expect the `/web/cache` directories to be nearly empty after deploy, and they are not.

### Versions
- Plugin version: `
- Craft version: `3.4.22.1`

**Comment by bencroker** [comment]
What kind of deployment setup are you using? And are you using a cache purger?

Can you run the following command on your staging server to get logging of console commands in https://github.com/putyourlightson/craft-blitz/commit/a0940a782173cd02451a1d2291cf54cf9a9ebe4d and retest?
```
composer require putyourlightson/craft-blitz:dev-develop
```

**Comment by cmalven** [comment]
@bencroker After spending way too much time investigating this, I still have no idea what is going on, but I'm no longer confident enough that the issue is related to Blitz to keep wasting your time. I think it is just as likely an issue with the asset-revving setup. I'm going to close this until I have more insight into specifically how Blitz is involved in the issue. I appreciate your time.

**Comment by bencroker** [comment]
Ok sounds good.
