### ISSUE TITLE
unable to trigger injectScriptEvent

### ISSUE THREAD

**Issue by bkmorse** [putyourlightson/craft-blitz#232]
### Question
I acquired an existing craft site and I am trying to set up blitz on it. It uses a javascript framework that makes xhr requests to update a portion of the site. (see partials in the first code example)

When I click a link in the navigation, it loads the page as expected, when I do a refresh (reload the page) it only shows the portion that was loaded in the xhr response.

I know there is a blitzInject function that you can make a call to the event you set in the blitz.php config: injectScriptEvent

The js framework replaces the element, without forcing the user to do a page load. Here is an example of how that is done:
```
$router.pjax({
    bind: {
        click: 'a',
    },
    partials: ['title', 'main'],
}).map([
    { path: '/', handler: common },
    { path: '/about', handler: about },
]).run();
```
Where you see partials, it replaces the title and main elements.
```
<main role="main">
    {{ block('content') }}
</main>
```

It replaces that content with the response. I am trying to trigger the event I set in the blitz.php config file without any luck. I looked at https://github.com/putyourlightson/craft-blitz/blob/develop/src/resources/js/blitzInjectScript.js#L25 and I think the <main> element expects data attributes, like so:
```
<main role="main" data-blitz-id="someid" data-blitz-uri="someuri" data-blitz-params="someparams">
    {{ block('content') }}
</main>
```
or maybe I am completely off, that is why I am at the point of reaching out. 

I am unable to trigger the injectBlitz event from my js code, any guidance is appreciated.

### Additional context
plugin 3.6.5
craft 3.4.24
php 7.1
apache 2

**Comment by bencroker** [comment]
I'm not sure what your actual question is. If you want to use the [dynamic content](https://putyourlightson.com/plugins/blitz#dynamic-content) feature that Blitz provides, then this is the tag you are looking for:
`{{ craft.blitz.getUri('/page/name', params) }}`

That will set up an element that the `blitzInject()` will use to fetch the dynamic content. Although it is possible, I would stay away from hacking your element to match what the `blitzInject()` function expects (it looks like you are missing the `blitz-inject` class by the way).

**Comment by bkmorse** [comment]
I have a similar setup, I am just unsure how it needs to be implemented in this situation https://github.com/putyourlightson/craft-blitz/issues/179#issuecomment-594678365

I will add blitz-inject to the `<main class="content blitz-inject">`

**Comment by bencroker** [comment]
Can you show a stripped down version of your modified code?

**Comment by bkmorse** [comment]
In the pjax part below, you will see partials, it replaces the content for the title element and replaces the content within the .content element

See partials part here: https://www.weepower.com/v4/script/routes.html#router-pjax (I originally thought I included a link to this).

```
import $events from 'wee-events';
import $ from 'wee-dom';
import NProgress from 'nprogress';
import $router from 'wee-routes';
import './bootstrap';
import setCookie from '../components/cookie';
import disclaimer from '../components/cookie-disclaimer';
import header from '../components/header';
import image from '../components/image';
import search from '../components/search';
import { localeSetValue } from '../components/logo-group';

const common = [header, image, setCookie, disclaimer, search];

$router({
	transition: {
		leave(to, from, next) {
			NProgress.start();

			next();
		},
		enter() {
			NProgress.done();
		}
	}
}).pjax({
	partials: ['title', '.content']
}).map([
	{
		path: '/',
		handler: [setCookie, disclaimer]
	}
]).beforeEach((to, from, next) => {
	localeSetValue();
	next();
}).afterEach((to) => {
	const event = new Event('blitzUpdate', { 'detail': 'Blitz Update Event' });
	document.dispatchEvent(event);
}).notFound({ handler: common })
	.run();

```

```
{% set conf = craft.config %}
{% set entry = entry is defined ? entry : craft.app.config.general.entryDefaults -%}
{% import '_macros/macros' as component %}

{%- spaceless %}
{% set pageNum = craft.app.request.pageNum %}
{% set pageNumTitle = pageNum > 1 ? ' | Page ' ~ pageNum %}

<main role="main" class="content blitz-inject" id="main-pjax-block">
	{{ block('content') }}
</main>
{% endspaceless %}
```
This is templates/_layouts/pjax.twig, similar to what he said here: https://github.com/putyourlightson/craft-blitz/issues/179#issuecomment-593838735

set in config/blitz.php
`'injectScriptEvent' => 'blitzUpdate',`

**Comment by bencroker** [comment]
Just tested locally and this works for me:

```twig
<main role="main" class="content blitz-inject" id="main-pjax-block" data-blitz-id="someid" data-blitz-uri="someuri" data-blitz-params="someparams">
	{{ block('content') }}
</main>
```

```js
const event = new Event('blitzUpdate', { 'detail': 'Blitz Update Event' });
document.dispatchEvent(event);
```

If you expect the event to be fired multiple times then probably better to avoid using `const`. The code can be reduced to the following:

```js
document.dispatchEvent(new Event('blitzUpdate'));
```

**Comment by bkmorse** [comment]
Does it require the links to use this? https://putyourlightson.com/plugins/blitz#dynamic-content

I am not using that to make xhr requests, it is using https://www.weepower.com/v4/script/routes.html#router-pjax to replace the .content element, within the partials array of pjax.

**Comment by bencroker** [comment]
Yes, the Blitz script is only loaded into the page when required, so not using the Blitz tags is likely the issue here.

**Comment by bkmorse** [comment]
That makes sense, this post made me think it was possible, as it was a similar setup but I did not know it required the links to be created by https://putyourlightson.com/plugins/blitz#dynamic-content

I went thru some other issues on your plugin's repo to see if I could have that 'aha' moment but I am still unsure where I should implement this blitz variable in my setup:
`{{ craft.blitz.getUri('/page/name') }}`

**Comment by bencroker** [comment]
I'm still not following why, if you're using pjax, you need Blitz to load dynamic content.

> When I click a link in the navigation, it loads the page as expected, when I do a refresh (reload the page) it only shows the portion that was loaded in the xhr response.

If I'm understanding correctly then this appears to be the source of your issue, which should be fixable with pjax. In case you're looking at alternatives, there is [Sprig](https://putyourlightson.com/plugins/sprig) for Craft.

**Comment by bkmorse** [comment]
Thanks for leading me to figure out the root cause. I appreciate it!

**Comment by bencroker** [comment]
Sure thing and best of luck with the acquired project!

**Comment by bkmorse** [comment]
Last question, is it possible to do this with blitz?

They create a separate "group" and directory to cache for that group, see https://github.com/lewiscommunications/craft-presto#parameters 
```
{% craft.presto.cache({
	group: 'pjax',
	static: false
}) %}
```

and the server rewrite: 
```
RewriteCond %{REQUEST_FILENAME} !\.(css|eot|gif|ico|jpe?g|otf|png|svg|ttf|webp|woff2?)$ [NC]
RewriteCond %{HTTP:X-PJAX} true
RewriteCond %{REQUEST_METHOD} GET
RewriteCond %{DOCUMENT_ROOT}/cache/%{HTTP_HOST}/presto/pjax%{REQUEST_URI}/index.html -f
RewriteRule .* /cache/%{HTTP_HOST}/presto/pjax%{REQUEST_URI}/index.html [L,E=nocache:1]]
```

**Comment by bencroker** [comment]
You can customise the directory into which Blitz writes the cached files, but not on a per template basis. It follows the URL structure though, so if your "groups" all share the same URI path then it might be possible.

**Comment by bkmorse** [comment]
Ok, I lied. One more question, is there an event I could listen for in php that gets triggered everytime before a page is cached? I was thinking maybe I could build a module that listens for that event, allowing me the ability to disable that page/request from being cached by blitz?

**Comment by bencroker** [comment]
Yes, but there are much simpler ways to exclude pages from being cached by Blitz...
https://putyourlightson.com/plugins/blitz#included-excluded-uri-patterns
and 
https://putyourlightson.com/plugins/blitz#cachingenabled

**Comment by bkmorse** [comment]
I need to check for a specific thing, it's not based off the uri. I want to analyze if the page is calling a specific template and/or something in the request.

**Comment by bkmorse** [comment]
Tried a couple of the events, noticed none of them get triggered when the site makes an xhr request.

**Comment by bencroker** [comment]
`EVENT_BEFORE_SAVE_CACHE` should let you prevent the page from being cached:
```php
        Event::on(GenerateCacheService::class, GenerateCacheService::EVENT_BEFORE_SAVE_CACHE,
            function(SaveCacheEvent $event) {
                if ( ... ) {
                    $event->isValid = false;
                }
            }
        );
```
https://github.com/putyourlightson/craft-blitz/blob/develop/src/services/GenerateCacheService.php#L38

**Comment by bkmorse** [comment]
I tried that, didn't work in my case, probably because events that trigger your cache plugin are not triggered during the xhr request my application makes.

Thanks for the help though! Really appreciate how helpful and quick you were to respond!

**Comment by bencroker** [comment]
Sure thing, I'd be happy to help more but I'm still a bit confused by what you're attempting to do, so I'll just wish you the best of luck!
