### ISSUE TITLE
Enabling Blitz debugging causes Debug Toolbar to stop rendering

### ISSUE THREAD

**Issue by simonleadbetter** [putyourlightson/craft-blitz#233]
### Describe the bug
Configuring blitz.php with `'debug' => true` stops the debug toolbar rendering. The console reports 404 error for the xhr request. I assume this is not expected behaviour.

### Versions
- Plugin version: 3.65
- Craft version: 3.4.25

**Comment by bencroker** [comment]
This was a bug in the Log To File helper, fixed in https://github.com/putyourlightson/craft-log-to-file/commit/5dcd436d53c87ba81d19c4ef5a8c107feff1e27f.

To get the fix, run this:
```
composer require putyourlightson/craft-log-to-file
```
