### ISSUE TITLE
Pages with extends tag not caching

### ISSUE THREAD

**Issue by jayhlee** [putyourlightson/craft-blitz#234]
### Question
Hi Ben, I'm having problems with my pages not caching. I tried to narrowed the issue down, and it seems pages that have an `{extends}` tag aren't caching. The Blitz log reads `Page not cached because it contains transform generation URLs.` Although I do use image transforms (imager) on my site, I don't think that's the issue because I've enabled `generateTransformsBeforePageLoad`. Furthermore, I reduced the parent and child template down to the bare bones (see image below) and the page still won't cache if the `{extends}` tag is in the child template. There's definitely no image transforms in my test example, but I still get the same Blitz log statement about the page not caching because of transform generation URLs

### Additional context
Caching is enabled in my Blitz config, the include URI pattern is set (`.*`), and `enableTemplateCaching` is disabled in my general config. Running Craft 3.4.26, Blitz 3.6.5.

![templates](https://user-images.githubusercontent.com/25807445/86492314-984de180-bd22-11ea-8e1c-85e80036b0ae.png)

**Comment by bencroker** [comment]
Have you checked off _everything_ from this common issue in the docs?
https://putyourlightson.com/plugins/blitz#the-site-is-not-being-cached-when-i-visit-it

> Ensure that the Caching Enabled setting is enabled and that the page you are visiting matches an Included URI Pattern (and not an Excluded URI Pattern). Blitz will not cache pages that display the debug toolbar so check that you are not logged in as an admin with the debug toolbar enabled on the front-end. Blitz will also not cache pages that contain asset transform generation URLs, as doing so can lead to cached pages that perform poorly (see this issue). To work around this, you can set enable the generateTransformsBeforePageLoad config setting.

And if yes then can you try enabling the `debug` config setting?
https://putyourlightson.com/plugins/blitz#debugging

**Comment by jayhlee** [comment]
Yes, everything is checked off from the common issue section in the docs. I also enabled the debug config and get this log when I try to load the test page of the screenshot I included:

`2020-07-03 11:12:13 [][][debug] Page not cached because it contains transform generation URLs. [https://mydomain.com/mypage]`

**Comment by bencroker** [comment]
Can you paste the HTML output of the page here?

**Comment by bencroker** [comment]
Or search for `assets/generate-transform` in it.

**Comment by jayhlee** [comment]
Ah, I think I know what's going on. I have SEOMatic installed, and although I have all my "Transform Image" settings disabled on SEOMatic, SEOMatic still prints an image transform generation URL in the LD+JSON script. Here's the culprit.

`{"@type":"ImageObject","height":"60","url":"https://mydomain.com/index.php/actions/assets/generate-transform?transformId=3","width":"361"},` 

When I completely disable SEOMatic, Blitz starts to cache again. I'm figuring I should bring this issue up with Andrew at NYStudio107. But I'm also figuring I'm not the only person who uses both Blitz and SEOMatic. Do you know how other people have managed to get both plugins working? I guess enabling `generateTransformsBeforePageLoad` doesn't apply to SEOMatic image transforms?

**Comment by bencroker** [comment]
Here you go: https://github.com/nystudio107/craft-seomatic/issues/490
