### ISSUE TITLE
Editing asset inline does not clear Blitz cache

### ISSUE THREAD

**Issue by jsmrtn** [putyourlightson/craft-blitz#235]
I'm not sure if this would be possible to introduce, as I'm not sure how Blitz determines when it should clear a cache. 

When editing an asset directly on a cached entry page by double clicking the asset field and on clicking _Edit_, if you update the Focal Point (for example) and press 'Save', you get the _Asset Saved_ flash message, but the cache for that page isn't cleared (presumably because they're not intrinsically linked), but also if I save that page then it still doesn't clear the cache (again, presumably because Blitz or Craft uses a diff to determine whether or not caches should be cleared?)

Is there any method whereby Blitz would know to clear the cache when an asset is modified in this way? Or is this more an issue with how Craft operates and Blitz cannot know it needs to clear a cache when an asset is modified.

Thanks!

**Comment by bencroker** [comment]
After doing some investigating (thanks to Xdebug) I can say that when you update the focal point of an image, the asset is _not_ marked as dirty (maybe it should be?), so Blitz assumes that nothing has changed and therefore doesn't clear the cache. For now the best workaround would be to change something in the title or another custom field on the asset, which should force the refresh.

**Comment by jsmrtn** [comment]
> the asset is not marked as dirty (maybe it should be?)

I would suggest so, yeah. Presumably this is something that P&T would need to change in core?

Yeah for now we've opted for now to suggest using 'Save as a new asset' and swapping out the image to the newly created asset, though maybe untenable as the assets could get swollen just to swap a focal point.

**Comment by bencroker** [comment]
> Presumably this is something that P&T would need to change in core?

Yes, it is.

> Yeah for now we've opted for now to suggest using 'Save as a new asset' and swapping out the image to the newly created asset, though maybe untenable as the assets could get swollen just to swap a focal point.

Maybe add a custom field with a version number or a datetime field to the asset that they could change to force the refresh?

**Comment by jsmrtn** [comment]
Or as you have so kindly pointed out, force Blitz to clear when nothing has changed using `refreshCacheWhenElementSavedUnchanged`.

Thanks Ben!

**Comment by bencroker** [comment]
Exactly: https://github.com/putyourlightson/craft-blitz/blob/3.6.5/src/config.php#L120-L121

**Comment by darinlarimore** [comment]
> After doing some investigating (thanks to Xdebug) I can say that when you update the focal point of an image, the asset is _not_ marked as dirty (maybe it should be?), so Blitz assumes that nothing has changed and therefore doesn't clear the cache. For now the best workaround would be to change something in the title or another custom field on the asset, which should force the refresh.

Just want to add to these findings. I've also discovered that replacing an image using the "Replace File" button in the assets manager, or changing the file name as show in the screenshot below does not mark the image "dirty" and no caches are purged.

The same solution, setting the `refreshCacheWhenElementSavedUnchanged => true` fixes this for us too!
<img width="1375" alt="Screen Shot 2021-06-03 at 1 33 35 PM" src="https://user-images.githubusercontent.com/20300635/120708528-aa338980-c489-11eb-9a93-73c2cec56758.png">
