### ISSUE TITLE
Blitz brings the server down due to too many Refresh jobs

### ISSUE THREAD

**Issue by focalinteractive** [putyourlightson/craft-blitz#236]
### Describe the bug
For no apparent reason Blitz starts generating hundreds of refresh jobs that make the CPU of the server reach 100%. Is this expected? Is it possible to avoid or control?

<img width="1158" alt="Screenshot 2020-07-17 at 12 48 56" src="https://user-images.githubusercontent.com/46625687/87787956-2c509a80-c845-11ea-8ff1-5a7e31efd53d.png">

From the job data the jobs seem to be unique (not a duplicate of the same). For the most part they seem to be related to Craft Commerce elements (categories, entries, assets, variants)

<img width="768" alt="Screenshot 2020-07-17 at 15 51 57" src="https://user-images.githubusercontent.com/46625687/87788104-73d72680-c845-11ea-8b54-94db00487c20.png">

### Environment
Craft Pro 3.4.27
Craft Commerce 3.1.12
PHP 7.3
Blitz 3.6.5
Caching enabled
Cache Storage: Blitz File Storage
Create Gzip Files: ON
Cache Warmer: Guzzle
Concurrency: 1
Reverse Proxy Purger: None
Remote Deployer: None
Clear cache Automatically: ON
Warm cache Automatically: OFF
Query String Caching: Cache URLs with unique query strings as unique pages

**Comment by bencroker** [comment]
Have you tried the suggestions on how to deal with refresh cache queue jobs piling up here?
https://putyourlightson.com/plugins/blitz#the-refresh-cache-queue-jobs-run-for-long-periods-of-time-and-sometimes-pile-up

**Comment by focalinteractive** [comment]
Hi @bencroker ! Thank you for the recommendations. Currently working on applying as many as possible and I will get back to you on the results. 🙏

**Comment by bencroker** [comment]
Did you land on a workaround or solution to this?

**Comment by focalinteractive** [comment]
@bencroker Apologies for the delay. The issue seems to be caused by navigation elements and elements that are included in multiple pages, so the first solution wouldn't work.
The use of a dedicated plugin for Navigation requires significant refactoring as the are 5 navigation menus. 
This suggestion "Disable cacheElements and cacheElementQueries using page specific options" would result in pages not being cached at all.
Even though we disabled "Clear Cache Automatically" we keep getting thousands of jobs after certain edits.

**Comment by bencroker** [comment]
> This suggestion "Disable cacheElements and cacheElementQueries using page specific options" would result in pages not being cached at all.

These settings do not disable caching. As stated in the [docs](https://putyourlightson.com/plugins/blitz#the-entire-cache-is-cleared-and-warmed-when-only-one-entry-is-updated):

_The consequence of this is that the cached page will not be cleared when elements in the global navigation are updated (unless they are used elsewhere on the page)._

**Comment by focalinteractive** [comment]
@bencroker That's what we expected too but we noticed that pages took longer to load and they wouldn't be cached.  (Checking the signature comment at the end of the page "Cached by....") 
Perhaps we did something wrong? We can give it another try.

**Comment by bencroker** [comment]
If you can recreate the issue and post some details then I'll gladly look into it.
