### ISSUE TITLE
Blitz static urls getting picked up by google

### ISSUE THREAD

**Issue by vibe9** [putyourlightson/craft-blitz#239]
### Describe the bug
I am not sure exactly how it's getting these URLs, but they seem to be generated by Blitz at some point and Google is finding them. They look like this:

https://www.mydomain.com/cache/blitz/www.mydomain.com////index.html.gz

### To reproduce
Steps to reproduce the behaviour:
Really not sure, this is part of the mystery! How and where are these links being generated?

### Expected behaviour
If there's no way around this then it would be good to know if it would be safe to create an htaccess redirect or something to stop google from archiving these links.

### Versions
- Plugin version: 3.6.5
- Craft version: 3.4.24

**Comment by bencroker** [comment]
You can put the following in a `robots.txt` file in your public `web` folder to prevent search engines indexing the `cache` folder.

```
User-agent: *
Disallow: /cache/
```
