### ISSUE TITLE
Too many entries in blitz tables

### ISSUE THREAD

**Issue by thaoms** [putyourlightson/craft-blitz#24]
1. I had to disable Blitz because there was too much data in the tables. (Over 1 million records - 500 MB)

Im using this regex for caching my whole site` .*`

2. After uninstalling and reinstalling the plugin (to try emptying the tables) I'm getting an extra error in my logs (not sure if this is relevant):
```

[warning][craft\db\mysql\Schema::releaseSavepoint] Tried to release a savepoint, but it does not exist: SQLSTATE[42000]: Syntax error or access violation: 1305 SAVEPOINT LEVEL1 does not exist
The SQL being executed was: RELEASE SAVEPOINT LEVEL1
```

**Comment by putyourlightson** [comment]
1. Yes, Blitz requires a lot of rows in the database to keep track of elements and element queries for cache invalidation. Is the size of the database causing issues? And do you need to cache the entire site or would it be possible to make the regex more specific?

2. I don't think this warning is related to Blitz, although I can't say for sure from the error message.

**Comment by thaoms** [comment]
500mb is actually the max size of the DB I have access to, so the site was pretty much broken.

Most of the time a full site doesn't go over 10-20mb

**Comment by putyourlightson** [comment]
That's the drawback of automatic caching invalidation. Do you need to cache the entire site or would it be possible to make the regex more specific?

**Comment by thaoms** [comment]
I could leave some basic pages out, like a contact page, about,.. 
But the more intensive pages need caching. 

Probably because I have a calendar, alot of links.
https://www.ticketsgent.be

**Comment by thaoms** [comment]
Wouldn't it be an option to truncate all those tables when you clear the cache?

For now I have a cronjob that clears every day at 4am the complete site (so my calendar has actually the right active day)

**Comment by putyourlightson** [comment]
If you delete the tables then you lose all of the valuable cache invalidation criteria. I might consider adding a setting for disabling the element query caches.

**Comment by thaoms** [comment]
Thanks for bearing with me.

**Comment by putyourlightson** [comment]
Thank you for reporting this and helping me understand the issue!!

**Comment by putyourlightson** [comment]
Added optimisations in 1.6.0 https://github.com/putyourlightson/craft-blitz/commit/393ebb6e824c9a1ff66734a3fb7afd4c7e26aeec which should help with caching large sites.

**Comment by seandelaney** [comment]
> If you delete the tables then you lose all of the valuable cache invalidation criteria. I might consider adding a setting for disabling the element query caches.

I'm facing the same issue. See:

![Screenshot 2021-09-01 at 11 30 52](https://user-images.githubusercontent.com/580403/131656423-0ab111a7-699b-4602-9a32-189cbf104880.png)

@thaoms

How did you resolve this in the end?

@bencroker 

I don't cache all pages, just the main sections, which have lots of entries.

In my config, both `cacheElements` and `cacheElementQueries` are set to `true`.

This might be a silly or obvious question to some, but what happens if I set these config options to `false` ?

**Comment by bencroker** [comment]
@seandelaney Please refer to [this section of the docs](https://putyourlightson.com/plugins/blitz#the-refresh-cache-queue-jobs-run-for-long-periods-of-time-and-sometimes-pile-up) and open a new issue if the issue persists as this one is long closed.

> This might be a silly or obvious question to some, but what happens if I set these config options to false ?

As per [this section of the docs](https://putyourlightson.com/plugins/blitz#page-specific-options), setting these to false will prevent Blitz from tracking elements and element queries respectively.
