### ISSUE TITLE
Cache not clearing on index page when deleting entry

### ISSUE THREAD

**Issue by jayhlee** [putyourlightson/craft-blitz#241]
I have an "index" page that lists a channel's entries. When an entry is deleted, the cache isn't refreshed and the entry continues to show on the index page. Strangely, when the entry is disabled (or edited), the cache is refreshed and the modification is reflected on the index page. 

If I manually update the Blitz cache via CP, the entry is deleted on the index page.

`.*` is set as the included URI pattern. Running Craft 3.4.26 and Blitz 3.6.5.

Any idea what I need to do to resolve this? Thanks!

**Comment by bencroker** [comment]
Have you modified any of the config settings in the `blitz.php` config file?

Before you delete an entry on the index page, can you first check if it exists in the `blitz_elementcaches` table and if the `cacheId` maps to the correct page URI in the `blitz_caches` table?

**Comment by jayhlee** [comment]
**Have you modified any of the config settings in the blitz.php config file?**
The blitz.php config hasn’t been modified. The [recommended server rewrites](https://putyourlightson.com/plugins/blitz#server-rewrites) have been implemented, however.

**Before you delete an entry on the index page, can you first check if it exists in the blitz_elementcaches table and if the cacheId maps to the correct page URI in the blitz_caches table?**
The entries in my channel exist in the `blitz_elementcaches` table. The entries' `cacheId` in the `blitz_elementcaches` table also map to the right `id`/`uri` in the `blitz_caches` table.

**Comment by bencroker** [comment]
In that case it _should_ just work. Do you have any plugins/modules installed that might be interfering? If you want us to take a closer look then please send credentials (preferable to a staging environment) to info@putyourlightson.net.

**Comment by jayhlee** [comment]
Just emailed you a list of plugins.

**Comment by bencroker** [comment]
Thanks, I notice you are using Redis. Which cache storage type do you have selected in the Blitz settings? If it's not the `Blitz File Storage` then can you retest the issue with this selected?

**Comment by jayhlee** [comment]
The cache storage type is `Blitz File Storage`.

**Comment by bencroker** [comment]
Then things should work as expected. As I said previously, I can take a closer look with credentials.

**Comment by jayhlee** [comment]
I just sent you the credentials.

**Comment by bencroker** [comment]
Thanks, fixed in https://github.com/putyourlightson/craft-blitz/commit/67b9258ea8b7d4f184ff451462d93a9ae170d382 for the next release.

**Comment by bencroker** [comment]
Released in version 3.6.7.
