### ISSUE TITLE
Handling CSRF token/400 error

### ISSUE THREAD

**Issue by rgbjay** [putyourlightson/craft-blitz#242]
### Question
We have a Trip Planner on our site that posts data to the Craft session via an Ajax request. Since installing Blitz we now get a 400 error for every post request. It isnt feasible for us to conditionally cache the templates that use the Ajax request as the button that instigates the request is on a card component that sits on almost every page on the site.

I have tried using the `{{ craft.blitz.csrfToken() }}` approach but this seems to just output a span tag rather than the raw csrf token.

Previously we have been appending the CSRF token to the Ajax request using the following method on the `_layout` twig file:

```
{% set csrfToken = {
    csrfTokenName: craft.app.config.general.csrfTokenName,
    csrfTokenValue: craft.app.request.csrfToken,
} %}

<script type="text/javascript">
    window.Craft = {{ csrfToken|json_encode|raw }};
</script>
```
However as our templates are now cached this is not going to work.

Any help on this would be appreciated.

**Comment by bencroker** [comment]
Have you seen the AJAX examples in the docs at https://putyourlightson.com/plugins/blitz#csrf-controller-actions? Something like this should do the trick.

```javascript
fetch('/actions/blitz/csrf/token')
    .then(result => { return result.text(); })
    .then(result => { window.Craft.csrfToken = result; })
```

**Comment by rgbjay** [comment]
Hi Ben,

Thanks for this. It seems to half work. 

When i load the initial page and fire a request, it works no problem. If I then navigate to a new page and fire another request, I get the 400 error again.

**Comment by rgbjay** [comment]
Just to add to this - it seems that it is sporadic. We have seen it throw a 400 error the first time the request is sent and then work for the second time. Also the token that is returned in the promise does not match the token that I can see in the session in developer tools.

**Comment by bencroker** [comment]
Can you share a link to an example of this? If not then post your source code?

**Comment by rgbjay** [comment]
Hi Ben,

Here is a snippet of the function that fires the Ajax request when the 'Add To Trip' button is clicked, your promise suggestion is at the top and sets the value of the csrf token that is then appended to the data object for the Ajax request:

```
fetch('/actions/blitz/csrf/token')
    .then(result => { 
      return result.text(); 
    })
    .then(result => { 
      window.Craft.csrfToken = result; 
    })

$(document).on('click', '.itinerary_button' , function (e) {

  e.preventDefault();
  let data = {
    id: $(this).data('id'),
    entryId: $(this).data('entry-id'),
    title: $(this).data('title'),
    url: $(this).data('url'),
    section: $(this).data('section'),
    category: $(this).data('category'),
    address: $(this).data('address'),
    lat: $(this).data('lat'),
    lng: $(this).data('lng'),
    logo: $(this).data('logo'),
    image: $(this).data('image'),
    startDate: $(this).data('start-date'),
    endDate: $(this).data('end-date'),
  };

  data[window.Craft.csrfTokenName] = window.Craft.csrfToken;
  

  $.ajax({
    url: '/actions/itinerary-builder/itinerary-builder/add-item',
    type: "POST",
    data: data,
    dataType: "json",
    success: function (result) {

      console.log('success');
      $(this).addClass('ib_item-added');

    },
    error: function (result) {

      console.log('error');
    }
  });

});
```

**Comment by bencroker** [comment]
That looks in general good to me, is it working and if not then open the network tab in the browser dev tools and check if the payload is correctly formatted. 

If you want the form to submit multiple times then you may need to refresh the csrfToken after each AJAX request, but this is unrelated to Blitz.

**Comment by rgbjay** [comment]
Thanks Ben, I will give that a try.

**Comment by bencroker** [comment]
Any update on this?
