### ISSUE TITLE
Blitz + Freeform

### ISSUE THREAD

**Issue by mmorkt** [putyourlightson/craft-blitz#244]
### I'm converting my static forms to Freeform
I've been using the {{ craft.blitz.csrfInput() }} tag for generating the CSRF. But I'm not sure how to integrate it with Freeform. I want to render the fields dynamically like:

{% set form = craft.freeform.form('contact') %}
{{ form.render() }}

### Additional context
I've seen some examples like the one bellow. But that wont loop out fields. Is there an easy workaround?
{{ form.renderTag }} {{ craft.blitz.csrfInput() }} ... {{ form.renderClosingTag }}

**Comment by bencroker** [comment]
I'm not aware of any way to manipulate the form content while using the `form.render()` function.
You could however make your own AJAX request and inject the result into the form, for example:

```javascript
fetch('/actions/blitz/csrf/input')
    .then(result => { return result.text(); })
    .then(result => { 
        document.getElementById('my-form').innerHTML += result;
});
```
    
See https://putyourlightson.com/plugins/blitz#csrf-controller-actions
