### ISSUE TITLE
Clear Cache Automatically

### ISSUE THREAD

**Issue by bengreenbank** [putyourlightson/craft-blitz#247]
Hi.

When I enbale the 'clear cache automatically' feature, I understand that it is meant to clear and purge the cache when elements are updated.

Does this mean that it will clear the entire site cache, or just the single page for the entry that has been updated?

Thanks for your help.

**Comment by bencroker** [comment]
It will clear the single page for the entry that has been updated, as well as any other pages that reference that entry, for example a listing page. Make sense?

**Comment by bengreenbank** [comment]
Yes, thanks very much.
