### ISSUE TITLE
Getting an error on saving content with a matrix field

### ISSUE THREAD

**Issue by wbrowar** [putyourlightson/craft-blitz#25]
I'm getting an error upon saving an entry. Here are some lines from stack trace:

```
Unknown Property – yii\base\UnknownPropertyException

Getting unknown property: yii\db\ActiveQuery::uri

in SITEPATH/vendor/putyourlightson/craft-blitz/src/services/CacheService.php at line 281 – yii\base\Component::__get('uri')

in SITEPATH/vendor/putyourlightson/craft-blitz/src/Blitz.php at line 117 – putyourlightson\blitz\services\CacheService::cacheByElementId(2893)
```

I'm using Blitz 1.5.3 on Craft 3.0.25.

My URI pattern is just `.` so I can cache the entire site (side note, is this the best way to do so?).

The error occurs upon save and from what I can tell it's trying to delete the URL based on ID, but it's using the ID of a matrix block (2893) instead of the ID of the page itself (2892).

Maybe a fix could be to detect if the element that's being saved is a Matrix and delete the page cache based on owner id.

**Comment by wbrowar** [comment]
Sorry it looks like this is happening when saving a MatrixBlock (2893 is the block, and 2892 is the owner)

**Comment by wbrowar** [comment]
Okay, it looks like it's because `$cacheRecord->uri` and `$cacheRecord->siteId` are the problem. 

Changing 
```
$cacheRecord = $elementQueryCacheRecord->getCache();
```
to
```
$cacheRecord = $elementQueryCacheRecord->getCache()->one();
```
allows me to save. I don't know what this will affect otherwise, though.

**Comment by putyourlightson** [comment]
Sorry about the delay in getting to this but am at DotAll conference, will get a fix out as soon as possible.

**Comment by wbrowar** [comment]
Not a problem! I knew you'd be there, but I wanted to document it. Have a good time and good luck tomorrow!

**Comment by putyourlightson** [comment]
Fixed in https://github.com/putyourlightson/craft-blitz/releases/tag/1.5.4
