### ISSUE TITLE
Dynamic content returning by wrapping a span tag which is unwanted

### ISSUE THREAD

**Issue by sThilakasiriMitra-zz** [putyourlightson/craft-blitz#250]
### Question
`{% set dataSet = craft.blitz.getUri('/page/name') %}`

{{ dataSet }} 
// `<span id="blitz-inject-1" class="blitz-inject">the results</span>`

After receiving the data I cant use twig data manipulation tags to iterate the code. Is there a reason to return with a span tag or any workaround get rid of this unwanted span?

### Additional context
How do I return data without wrapping to a ` <span>` tag?

**Comment by bencroker** [comment]
The span tag is required by Blitz to do the dynamic replacement. What is it preventing you from doing exactly?

**Comment by sThilakasiriMitra-zz** [comment]
Thanks, I get an array as the result, I want to iterate through.

**Comment by bencroker** [comment]
What you get back is HTML, it cannot be an array. If you'd like to iterate through an array then you should be doing that in your injected template at `/page/name`.

**Comment by nitech** [comment]
Actually this is kind of a problem. Take this instance: 

I have a toolbar with "always on items" such as the language selector. Other items, such as the "account" button should only be visible to those that have logged on the backend.

When using getTemplate thus, the `<li>` from back end is wrapped in a `<span>`.

```twig
<ul class="toolbar">
  <li class="language">Select language</li>
  {{ craft.blitz.getTemplate('/ax/toolbar-items-for-authenticated-users') }}  
</ul>
```

**Comment by bencroker** [comment]
In this case I would suggest adding the entire `<ul>` to the fetched template.
