### ISSUE TITLE
[FR] Allow include / exclude URI pattarn in Utility Tab WITHOUT changing the project config

### ISSUE THREAD

**Issue by hongc-cc** [putyourlightson/craft-blitz#253]
### Is your feature request related to a problem? Please describe.
UX issues:
1. We dont want to change project config on production environment
2. We might need to disable the caching for particular page for some reason
3. Adding exclude URI in `Utility` is the quickest solution when some urgent thing happens and we need to quickly shut down cache without coding

### Describe the solution you would like
Allow  include / exclude URI pattarn in Utility Tab WITHOUT changing the project config
Or "Temporary disable caching for these URI patterns"...etc

One use case is we just activate blitz but get CSRF issues with freeforms. 
We are doing code change to address these while dont want to shut down all the caches.
Meanwhile the editor might want to keep adding forms for the content.

Our quickest solution will be to add URI pattern on `Utility` first while we work on the fix.

**Comment by bencroker** [comment]
What I would suggest in your use-case is that you use the [config settings](https://putyourlightson.com/plugins/blitz#config-settings) to modify the [excludedUriPatterns](https://github.com/putyourlightson/craft-blitz/blob/3.6.8/src/config.php#L41-L46) in your production environment. That would be the quickest way to disable caching of specific pages.

The Excluded URI Patterns setting is considered a plugin setting that should be available to admins only in the CP, therefore it is not something we would be likely to add to the utility page. Ideally the plugin would be installed and tested in a development/staging environment before being pushed to production.
