### ISSUE TITLE
HTTP2 push Support

### ISSUE THREAD

**Issue by hiasl** [putyourlightson/craft-blitz#254]
### Question
Hi Ben,

I'm currently spending a lot of time with web vitals and considering http2 push as an option (we sometimes use it when not using blitz). On the server side this is done with a special header I set in PHP. I guess, this will not work anymore when using blitz cache, as I see no way to set additional files being pushed when accessing a static cached html file. Is this correct? The advantage of http2 push vs. inline certain content like critical styles is that browsers can cancel the pushed additional content which is not possible when inlining it.

thanks for your thoughts about this.
Matthias

**Comment by bencroker** [comment]
Assuming you are using Apache, you can specify which assets should be pushed via `httpd.conf` or `.htaccess`. Since this is also how server rewrites are handled with Blitz, I don't any reason why the two could not be used together.

**Comment by hiasl** [comment]
ok. but httpd.conf is nothing dynamic, it needs to be configured in advance.
but is Blitz capable of rewriting additional headers set in PHP/Twig as corresponding Apache commands in .htaccess?

**Comment by bencroker** [comment]
> but is Blitz capable of rewriting additional headers set in PHP/Twig as corresponding Apache commands in .htaccess?

No, Blitz cannot do anything if server rewrites are in effect.

I'm not following what you are trying to do so am struggling to help you here. I am assuming that you want to preload assets such as CSS files using HTTP/2 server push on every request. Is this the case?

**Comment by hiasl** [comment]
yes exactly.

initial uncached request:
- php sets an additional http header which causes apache to http2 push e.g. a css file with the main document
the request gets cached by Blitz. a static html file is written. 

second and further requests:
- the static file is loaded, but the additional header from the first request will not be sent (my assumption, I guess you confirmed)

what it would need for something like this to work is an .htaccess file setting the additional header in addition to the static file being served, if I understood your previous reply. 

any plans on your side in this direction? or something else coming close?

thanks!

**Comment by bencroker** [comment]
Oh I see what you mean now, you were setting the header in PHP, not in `.htaccess`. Your options in this case would be to either _not_ use server rewrites, in which case you can continue setting your headers in PHP (using a Craft plugin/module I assume), or to use server rewrites and set the headers using `.htaccess`.

**Comment by hiasl** [comment]
just to confirm: without rewriting Blitz would take care of additional headers when sending out the cached file? 

thanks!

**Comment by bencroker** [comment]
That depends, how you are setting the headers?

**Comment by hiasl** [comment]
currently with PHP's header(..) command, guess that would NOT be cached :-)
But I can change that or manually modify my .htaccess (for rewriting support).
thanks!

**Comment by bencroker** [comment]
If you're setting it in a Craft plugin/module then you can continue doing that provided you are _not_ using Blitz server rewrites. If however you are using server rewrites then adding it to `.htaccess` will set it everywhere for you.

**Comment by hiasl** [comment]
thanks again!
