### ISSUE TITLE
Refreshing Blitz cache task hanging forever

### ISSUE THREAD

**Issue by nflorentin** [putyourlightson/craft-blitz#256]
Hi,

Multiple times per day, "Refreshing Blitz cache" tasks are stuck and prevent following tasks to be executed. Most of the time (but not always), they are stuck at a progression of 100% but sometimes they are also stuck in state "waiting".

Sometimes, deleting the task which causes the problem and restarting the server helps but not always. Sometimes, I have to delete all blitz tasks by hand and trigger a refresh manually. 

In my queue log, I can see that the task starts:
`[23515] Refreshing Blitz cache (attempt: 1) - Started`

But I rarely see the message (which is logical):
`[xxxxx] Refreshing Blitz cache (attempt: 1) - Done (X s)`

My settings are the following:
```
  '*' => [
    'cachingEnabled' => true
    'includedUriPatterns' => [
      [
        'siteId' => '',
        'uriPattern' => '.*'
      ],
    ],
  ]
```

My queue TTR is 600 and the process of the queue is run by the following command:
`nice -n 10 /usr/local/bin/php /usr/src/app/craft queue/listen --verbose`

### Screenshots

![Capture d’écran 2020-09-09 à 11 32 39](https://user-images.githubusercontent.com/5750349/92581807-6b70fa00-f290-11ea-8db6-80aa58619e86.png)

### Versions
- Plugin version: 3.6.8
- Craft version: 3.5.8

Thanks for your help!

**Comment by bencroker** [comment]
Is there anything in your daemon log file that might help explain why the queue jobs are not completing?

**Comment by nflorentin** [comment]
Unfortunately, there is no error in my queue log.

I reproduced the error juste updating an entry (going to the entry form and clicking save button), and got this following task stuck:
![Capture d’écran 2020-09-09 à 13 45 15](https://user-images.githubusercontent.com/5750349/92594301-e3482000-f2a2-11ea-82cd-a8e4889ebe26.png)

**Comment by bencroker** [comment]
> Unfortunately, there is no error in my queue log.

I don't mean the queue log, I mean the daemon log file that is listening for queue jobs.

**Comment by nflorentin** [comment]
Ops, sorry I mean the deamon log file (`nice -n 10 /usr/local/bin/php /usr/src/app/craft queue/listen --verbose`), no error at all. The blitz tasks are always running without error, but sometimes they got stuck (something like 25% of the time).

**Comment by nflorentin** [comment]
I'm going crazy with this. 

Here is more info if it can help us find the origin of the bug:
- I'm having the issue in dev and production environment
- I tried various concurrency values (from 1 to 5), it didn't help
- I tried to manually run the queue with `./craft queue/run` instead of `./craft queue/listen`, it didn't help
- no error in queue.log
- no error in blitz.log (debug mode on)
- I tried to uninstall the plugin and reinstall it, it didn't help
- I tried to install plugin craft-async-queue instead of running my process ./craft queue/listen, it didn't help
- it only concerns the Blitz tasks "Refreshing Blitz cache"

**Comment by bencroker** [comment]
Have you tested it with `runQueueAutomatically` set to `true` in the general config settings? So the default value that Craft ships with?

How many rows are in your `blitz_elementqueries` database table?

**Comment by bencroker** [comment]
Any update on this?

**Comment by nflorentin** [comment]
Sorry for the delay, I'm on holiday at the moment.
We have 676 rows in the blitz_elementqueries;

I tried runQueueAutomatically set to true without any effect.

Thanks!

**Comment by nflorentin** [comment]
Hmm I gave another try to runQueueAutomatically set to true and it seems to solve the problem.

Do you know what could be the reason ? As far as I understood, it's better to handle the queue in another process than having runQueueAutomatically set to true.

**Comment by bencroker** [comment]
Sometimes it is, but that depends on your hosting setup. In this case it appears that the queue listener you set up is not working as expected.
