### ISSUE TITLE
Refresh cache on FreeForm form save

### ISSUE THREAD

**Issue by mark-chief** [putyourlightson/craft-blitz#259]
### Question
Please bear with me as this is my first module for Craft. I am attempting to refresh the Blitz cache when any freeform form is saved. (or even better, id like to refresh the cache of pages with a tag "has-form"??)

It is saving the form but the Blitz cache is not being triggered. ANY guidance would be greatly appreciated as i'm a n00b to this! Thankyou!

```
use Solspace\Freeform\Services\FormsService;
use Solspace\Freeform\Events\Forms\SaveEvent;
use putyourlightson\blitz\Blitz;

    public function init()
    {
        parent::init();
        self::$instance = $this;

        if (Craft::$app->getRequest()->getIsCpRequest()) {
                                   
            // start the freeform event
	        Event::on(
			  FormsService::class,
			  FormsService::EVENT_AFTER_SAVE,
			  function (SaveEvent $event) {
				  Blitz::$plugin->refreshCache->batchMode = true;
			          Blitz::$plugin->refreshCache->refresh();
			  } 
			);            
        }

}
```

### Additional context
Client adds fields to a form and hits save -> cache is refreshed and new fields show on front end

**Comment by bencroker** [comment]
Something like this should work:

```php

public function init()
{
    parent::init();

    Event::on(
        FormsService::class,
        FormsService::EVENT_AFTER_SAVE,
        function () {
            Blitz::$plugin->refreshCache->refreshCacheTags(['has-form']);
        }
    );
}
```

**Comment by mark-chief** [comment]
Perfect, thanks Ben. Out of interest how would I have found out about `refreshCacheTags`, I cannot see that referenced in the docs, if I had looked elsewhere in the plugin code could that have helped me?

**Comment by bencroker** [comment]
The `RefreshCacheService` class provides an API through its public methods for modules/plugins to use for anything related to refreshing of the Blitz cache:
https://github.com/putyourlightson/craft-blitz/blob/develop/src/services/RefreshCacheService.php

**Comment by mark-chief** [comment]
Thankyou!
