### ISSUE TITLE
Error when uploading/deleting asset

### ISSUE THREAD

**Issue by riasvdv** [putyourlightson/craft-blitz#26]
Can't really figure out why this is happening.

2018-09-26 13:03:46 [-][1][-][error][craft\controllers\AssetsController::actionSaveAsset] An error occurred when saving an asset: Getting unknown property: yii\db\ActiveQuery::uri

Full log:
<details>
<pre>
2018-09-26 13:03:46 [-][1][-][error][craft\controllers\AssetsController::actionSaveAsset] An error occurred when saving an asset: Getting unknown property: yii\db\ActiveQuery::uri
2018-09-26 13:03:46 [-][1][-][error][yii\base\UnknownPropertyException] yii\base\UnknownPropertyException: Getting unknown property: yii\db\ActiveQuery::uri in /var/www/vhosts/marbles.be/httpdocs/releases/edb60c3edcec5479080815dd70830894e5cf0448/vendor/yiisoft/yii2/base/Component.php:154
Stack trace:
#0 /var/www/vhosts/marbles.be/httpdocs/releases/edb60c3edcec5479080815dd70830894e5cf0448/vendor/putyourlightson/craft-blitz/src/services/CacheService.php(281): yii\base\Component->__get('uri')
#1 /var/www/vhosts/marbles.be/httpdocs/releases/edb60c3edcec5479080815dd70830894e5cf0448/vendor/putyourlightson/craft-blitz/src/Blitz.php(117): putyourlightson\blitz\services\CacheService->cacheByElementId(3289)
#2 [internal function]: putyourlightson\blitz\Blitz->putyourlightson\blitz\{closure}(Object(craft\events\ElementEvent))
#3 /var/www/vhosts/marbles.be/httpdocs/releases/edb60c3edcec5479080815dd70830894e5cf0448/vendor/yiisoft/yii2/base/Event.php(310): call_user_func(Object(Closure), Object(craft\events\ElementEvent))
#4 /var/www/vhosts/marbles.be/httpdocs/releases/edb60c3edcec5479080815dd70830894e5cf0448/vendor/yiisoft/yii2/base/Component.php(636): yii\base\Event::trigger('craft\\services\\...', 'afterSaveElemen...', Object(craft\events\ElementEvent))
#5 /var/www/vhosts/marbles.be/httpdocs/releases/edb60c3edcec5479080815dd70830894e5cf0448/vendor/craftcms/cms/src/services/Elements.php(542): yii\base\Component->trigger('afterSaveElemen...', Object(craft\events\ElementEvent))
#6 /var/www/vhosts/marbles.be/httpdocs/releases/edb60c3edcec5479080815dd70830894e5cf0448/vendor/craftcms/cms/src/controllers/AssetsController.php(118): craft\services\Elements->saveElement(Object(craft\elements\Asset))
#7 [internal function]: craft\controllers\AssetsController->actionSaveAsset()
#8 /var/www/vhosts/marbles.be/httpdocs/releases/edb60c3edcec5479080815dd70830894e5cf0448/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#9 /var/www/vhosts/marbles.be/httpdocs/releases/edb60c3edcec5479080815dd70830894e5cf0448/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#10 /var/www/vhosts/marbles.be/httpdocs/releases/edb60c3edcec5479080815dd70830894e5cf0448/vendor/craftcms/cms/src/web/Controller.php(103): yii\base\Controller->runAction('save-asset', Array)
#11 /var/www/vhosts/marbles.be/httpdocs/releases/edb60c3edcec5479080815dd70830894e5cf0448/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('save-asset', Array)
#12 /var/www/vhosts/marbles.be/httpdocs/releases/edb60c3edcec5479080815dd70830894e5cf0448/vendor/craftcms/cms/src/web/Application.php(282): yii\base\Module->runAction('assets/save-ass...', Array)
#13 /var/www/vhosts/marbles.be/httpdocs/releases/edb60c3edcec5479080815dd70830894e5cf0448/vendor/craftcms/cms/src/web/Application.php(541): craft\web\Application->runAction('assets/save-ass...', Array)
#14 /var/www/vhosts/marbles.be/httpdocs/releases/edb60c3edcec5479080815dd70830894e5cf0448/vendor/craftcms/cms/src/web/Application.php(266): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#15 /var/www/vhosts/marbles.be/httpdocs/releases/edb60c3edcec5479080815dd70830894e5cf0448/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#16 /var/www/vhosts/marbles.be/httpdocs/releases/edb60c3edcec5479080815dd70830894e5cf0448/web/index.php(21): yii\base\Application->run()
#17 {main}
</pre>
</details>

**Comment by riasvdv** [comment]
Seems like this is the same as #25

**Comment by putyourlightson** [comment]
Likely yes, will fix as soon as I can, currently at DotAll...

**Comment by putyourlightson** [comment]
Fixed in https://github.com/putyourlightson/craft-blitz/releases/tag/1.5.4
