### ISSUE TITLE
Console commands spawns queue/run

### ISSUE THREAD

**Issue by paweltatarczuk** [putyourlightson/craft-blitz#260]
### Describe the bug
Multiple console command runs the queue the same way as the `queue/run`.

This is unexpected because:
- Stopping the queue processing service does not necessarily mean the queue is not being processed
- Restarting the queue processing service does not necessarily mean all queue processes are restarted

### To reproduce
Steps to reproduce the behaviour:
1. Diable all `queue/run` processes
2. Ensure there are jobs waiting to be processed in the queue
3. Run `blitz/cache/refresh-expired`
4. There are no waiting jobs in the queue any more

### Expected behaviour
Console commands should not process queue by it's own.

### Versions
- Plugin version: 3.6.9
- Craft version: 3.5.5

**Comment by paweltatarczuk** [comment]
Here's a similar issue I have created in another Craft's module:
https://github.com/nystudio107/craft-seomatic/issues/759

It was resolved by adding a `--queue` flag to the console command. Can we have something similar for this module? I can provide a pull request.

**Comment by bencroker** [comment]
Thanks, have added a similar `--queue` flag in https://github.com/putyourlightson/craft-blitz/commit/432715f73b516a7e38fbac1d789c4946435f6a16.

**Comment by bencroker** [comment]
Released in 3.6.11.
