### ISSUE TITLE
More Control Over Query String Caching

### ISSUE THREAD

**Issue by sarahschuetz** [putyourlightson/craft-blitz#262]
### Our Problem
We have developed a site where wie implemented a search using query strings.
We also want to use query params for tracking purposes.
For this non of the _Query String Caching_ settings seem ideal for us:

**Do not cache URLs with query strings:**
Currently we are using this setting which works for our search results but results in long loading times for urls with tracking parameters.

**Cache URLs with query strings as unique pages:**
This would work, but result in many unnecessary pages and the pages with tracking params would not be prewarmed except if we include all of them in the _Custom Site URIs_. Correct?

**Cache URLs with query strings as the same page:**
This would be ideal for the tracking parameters. However, this would break our search page.

### Solution
Can you think of a way to make this setting more flexible?
Maybe by providing exceptions when using _Cache URLs with query strings as the same page_, to set this setting per entry type or overwrite the setting for specified urls/entries/entry types?

Another solution I can think of can would be to have a list of parameters which will be ignored and urls containing only these strings will be treated as if there were no query strings present.

### Alternatives we have considered
Alternatively we have to reimplement our search not to use query strings.
However, I think this feature could be helpful for different projects and use cases as well.

**Comment by bencroker** [comment]
There is an `excludedQueryStringParams` config setting that might help solve this for you by excluding tracking parameters:
https://github.com/putyourlightson/craft-blitz/blob/3.6.11/src/config.php#L145-L146

**Comment by sarahschuetz** [comment]
Oh didn't know this one, this might solve our problem. I'll give that a try!

**Comment by sarahschuetz** [comment]
@bencroker this works perfectly for us, thank you!

**Comment by bencroker** [comment]
Glad to hear it!
