### ISSUE TITLE
Error on Cache Refresh / When Blitz is enabled

### ISSUE THREAD

**Issue by mark-chief** [putyourlightson/craft-blitz#265]
### Describe the bug
Apologies, I dont really know how to describe these errors, but I seem to be getting a few when Blitz is enabled and I refresh the cache.

The reason I am posting this here is because when Blitz is disable it dont get these errors.

### To reproduce
Steps to reproduce the behaviour:
1. Go to Blitz in CP 
2. Click on refresh Cache
3. See error message:

**Craft error message at top:** 
Internal Server Error

**Dev console message**
Failed to load resource: the server responded with a status of 500 (Internal Server Error)  /index.php?p=admin/actions/queue/get-job-info&limit=50&dontExtendSession=1:1 

**Other:**
And then when I click to another page in the CP I get:
PHP Core Warning – yii\base\ErrorException
Module 'ftp' already loaded
yii\base\ErrorHandler::handleFatalError()

**Front end templates:**
Fatal error: Uncaught yii\web\HeadersAlreadySentException: 
Headers already sent in /home/runcloud/webapps/-hosp/app/craft/vendor/yiisoft/yii2/web/Response.php on line 430. in /home/runcloud/webapps/hosp/app/craft/vendor/yiisoft/yii2/web/Response.php:366 Stack trace: #0 /home/runcloud/webapps/hosp/app/craft/vendor/yiisoft/yii2/web/Response.php(339): yii\web\Response->sendHeaders() #1 /home/runcloud/webapps/hosp/app/craft/vendor/yiisoft/yii2/web/ErrorHandler.php(136): yii\web\Response->send() #2 /home/runcloud/webapps/hosp/app/craft/vendor/craftcms/cms/src/web/ErrorHandler.php(139): yii\web\ErrorHandler->renderException() #3 /home/runcloud/webapps/hosp/app/craft/vendor/yiisoft/yii2/base/ErrorHandler.php(288): craft\web\ErrorHandler->renderException() #4 [internal function]: yii\base\ErrorHandler->handleFatalError() #5 {main} thrown in /home/runcloud/webapps/hosp/app/craft/vendor/yiisoft/yii2/web/Response.php on line 366

### Screenshots
<img width="1458" alt="Screenshot 2020-10-13 at 13 18 43" src="https://user-images.githubusercontent.com/18699249/95860532-12492a00-0d58-11eb-9dea-ea47d31621fa.png">

### Versions
- Plugin version: 3.6.11
- Craft version: 3.5.12.1
- Digital Ocean + Runcloud 
- php 7.4.11

Apologies it vague, if you need more info please let me know and I'll get it for you. thanks!

**Comment by mark-chief** [comment]
Fixed, after some rummaging I had to 
```
apt update
apt upgrade runcloud-agent
systemctl restart runcloud-agent
```

**Comment by bencroker** [comment]
Great, it anyway didn't sound like a Blitz issue. Probably a system caching issue that was resolved by restarting the app.
