### ISSUE TITLE
Reverse proxy purge does not occur automatically after warming

### ISSUE THREAD

**Issue by markdrzy** [putyourlightson/craft-blitz#266]
I'm using the Guzzle warmer and the CloudFront purger. When I warm the cache, either via saving an entry or "Warm Cache" in the utility, the purger does not run automatically — I must trigger the purge manually in the utility. The [documentation](https://putyourlightson.com/plugins/blitz#reverse-proxy-purging) states that:

> Selecting a purger will tell Blitz to automatically purge the appropriate pages whenever they are updated.

This is not happening for me. Watching `blitz.log` with debug enabled does not indicate that the purger is triggered until I manually trigger it via the utility. Is my understanding of this feature accurate? Should I expect that configuring and selecting a purger will cause Blitz to automatically trigger the purger when cache is warmed?

**Comment by bencroker** [comment]
No, the cache will be purged whenever pages are updated, so when elements are modified (at least one value must be changed unless you disable the `refreshCacheWhenElementSavedUnchanged` [config setting](https://github.com/putyourlightson/craft-blitz/blob/3.6.11/src/config.php#L133-L134)). Warming the cache will not automatically purge the cache. Refreshing the cache however, will purge the cache before warming.

**Comment by markdrzy** [comment]
@bencroker Thanks for clarifying that the purger doesn't run when only the "Warm Cache" task is run. However, I'm still not seeing the purger run when I save an entry with content changes. The purger _does_ run when I manually trigger the "Purge Cache" task via the utility, so it must be configured correctly…

Craft 3.5.12.1
Blitz 3.6.11
Blitz CloudFront Purger 2.0.4

**Comment by bencroker** [comment]
How are you verifying whether the cache is being purged when an entry is updated? Note that no messages are logged to `blitz.php` when this happens. 

To verify, you can add a log message to the following line:
https://github.com/putyourlightson/craft-blitz-cloudfront/blob/2.0.4/src/CloudFrontPurger.php#L150

```php
\putyourlightson\blitz\Blitz::$plugin->log('Cache purged.');
```

**Comment by markdrzy** [comment]
I'd been watching for the invalidations to appear in the Cloudfront console — when doing a full purge I would see the '/*' invalidation request come through just fine, but on entry updates I didn't see any invalidations happening.

After doing a few more tests with more logging inserted, I was able to get multi-URI invalidations to work on element save by matching the `Quantity` value in the invalidation request to the length of the `Items` array (https://github.com/putyourlightson/craft-blitz-cloudfront/blob/2.0.4/src/CloudFrontPurger.php#L231-L240):

```
$result = $client->createInvalidation([
    'DistributionId' => Craft::parseEnv($this->distributionId),
    'InvalidationBatch' => [
        'CallerReference' => time(),
        'Paths' => [
            'Items' => $paths,
            'Quantity' => count($paths),
        ],
    ]
]);
```

This would explain why the purge request worked when doing a full purge — there was only one item in the path: '/*'.

Also, when logging inside the `purgeUris` method, I notice that the method is being called twice. I think that both the "Clear Cache" and "Refresh Cache" tasks are being run when an entry is saved, and since both tasks call the `clearUris` method (which triggers a purge) the purge happens twice.

**Comment by bencroker** [comment]
Thanks for explaining and for the PR at https://github.com/putyourlightson/craft-blitz-cloudfront/pull/4.

Yes, the cache is cleared (and purged) twice, the first time just for the pages that are directly affected by the update and the second time if there are others that might be. Since the refresh process can take a bit of time, this was the smoothest way of making the refresh process feel fast even it is isn't exactly. This workaround will be overhauled in Blitz 4, we have big plans!
