### ISSUE TITLE
Blitz is checking all pages although I just specified 3 pages. 

### ISSUE THREAD

**Issue by outline4** [putyourlightson/craft-blitz#268]
### Describe the bug

I just want to cache 3 pages. 

In the URI patterns to include in caching I've specified the following pages: 
/work  
/projects  
/clients  

Alternatively I've tried:  
^/work$
^/projects$  
^/clients$  

### To reproduce
Now when I create a new entry it tries to warm all ~2500 entries of the "work" channel. 

Most of the times it tries to do this, the task crashes and repeats. 
It's like an endless loop and unnecessary since it should just warm and cache these 3 entries. 

Is there a way to just warm and cache those 3 entries? 

### Screenshots
<img width="1552" alt="Bildschirmfoto 2020-10-30 um 19 01 04" src="https://user-images.githubusercontent.com/145828/97746708-b6fe9200-1ae2-11eb-9856-719e40743dd9.png">

<img width="1552" alt="Bildschirmfoto 2020-10-30 um 19 01 19" src="https://user-images.githubusercontent.com/145828/97746777-d3023380-1ae2-11eb-8250-b747420839c9.png">

### Versions
- Blitz version: 3.6.11
- Craft version: Craft Solo 3.5.13.2

**Comment by bencroker** [comment]
Can you try this?

```
^work$
^projects$
^clients$
```

**Comment by outline4** [comment]
I think that did the trick! 

Now it's only warming and refreshing 3 pages as expected! 

Thanks a lot!

**Comment by bencroker** [comment]
Sure thing!
