### ISSUE TITLE
CSRF Inject not always working

### ISSUE THREAD

**Issue by luke-nehemedia** [putyourlightson/craft-blitz#269]
I have a website that has a form to register for a newsletter (via Campaign plugin). The whole site is cached by Blitz and I inserted the CSRF input field via `{{ craft.blitz.csrfInput() }}`. So far everything has worked fine.

Lately the client complained about too many bounced emails from spam-bots trying to register. Therefore they asked by to implement Google reCaptcha. I tried to do so with the following code, which is basically 1:1 from the [Google docs](https://developers.google.com/recaptcha/docs/v3).

```
<div class="col-sm-2">
    <button class="g-recaptcha btn btn-primary" 
	data-sitekey="6LdkaXcUAAAAAGfKHpvHAOeaiEHupsZ9kC6LNQbc" 
	data-callback='newsletterSubmit' 
	data-action='submit'>Anmelden</button>
</div>
<script>
	function newsletterSubmit(token) {
		document.getElementById("newsletter-subscribe").submit();
	 }
</script>
```

After deleting the Blitz and craftcms cache, everything works as expected for the first time. However, after some more times (and randomly on some other pages) it fails to work. Google reCaptcha does work fine, but the CSRF-token is not injected (no error message, but also no Ajax request or anything called). 

Strangely, after deleting the caches again, a simple reload of the page solves the issue again for a couple of times before it fails on some sites, while keeps working on other sites. I think the failure is not browser-related, since opening the same site in a different browser shows the same behaviour. 

Any ideas what the problem could be?

### Versions
- Plugin version: 3.6.11 (current)
- Craft version: 3.5.15.1 (current)

**Comment by bencroker** [comment]
If it only happens when Google reCaptcha is added then it sounds like it may be interfering. How are you verifying the response from reCaptcha (https://developers.google.com/recaptcha/docs/verify) in Craft?

If you want a Craft plugin solution for preventing spam, then check out [Snaptcha](https://putyourlightson.com/plugins/snaptcha), which has integration instructions for Blitz:
https://putyourlightson.com/plugins/snaptcha#ajax-requests

**Comment by luke-nehemedia** [comment]
So far I don't validate it since I stopped after trying to setting it up ;-)

I wonder where it interferes. After deleting the cache it will work at least once (often multiple times) nicely together with Google. Afterwards, Google will work fine but the blitz injection won't. 

Snaptcha is a good tip and I will look into that since I feel it might be faster than solving this issue. It would still be interesting to find out where the problem is located.

**Comment by bencroker** [comment]
Ok, let me know if you discover the issue.
