### ISSUE TITLE
Not seeing any blitz action

### ISSUE THREAD

**Issue by jhealey5** [putyourlightson/craft-blitz#27]
Hi, I'm trying this out locally, but I'm not seeing it take effect. Is there anything I have to do that I'm missing? I've installed it and enabled it, warmed up the cache and switch the environment to production. I'm not seeing any HTML comments from blitz or any cache folder being created in `@webroot`

The server config is optional, isn't it?

Looks great, hopefully I can get it to work!

**Comment by putyourlightson** [comment]
Blitz doesn't assume anything about which URLs you want to cache, so you'll need to add a URI pattern to include if you haven't already.

**Comment by jhealey5** [comment]
Ah my bad, no idea how I missed that!

Thanks, really great work, static caching is so needed for craft :)
