### ISSUE TITLE
Exclude parts in template

### ISSUE THREAD

**Issue by thomasgoemaere** [putyourlightson/craft-blitz#270]
### Question
I was wondering if it is possible to exclude certain template parts from being cached. For example a cookie consent banner or a popup modal with a newsflash that are hidden after user interaction, so they don't popup on every page load but only on the first request by the user. Those elements doesn't need to be in the cached html (otherwise those elements keep showing up every time the cached page gets loaded).

I'm not finding anything about this in the docs, or am I missing something?

Thanks in advance,
Kind regards, 
Thomas

**Comment by bencroker** [comment]
Blitz supports full page caching only so you can't exclude partials. For that, you'll probably want to reach for the dynamic content feature (https://putyourlightson.com/plugins/blitz#dynamic-content), or use Sprig (https://putyourlightson.com/plugins/sprig).
