### ISSUE TITLE
Refresh Blitz Cache jobs are executed very slowly

### ISSUE THREAD

**Issue by wei2go** [putyourlightson/craft-blitz#271]
### Question
The symptom of my issue is very similar to [this closed issue](https://github.com/putyourlightson/craft-blitz/issues/256). However, I don't use a separate process to handle the queue, and I have the 'runQueueAutomatically' set to true already.

The queue shows 1800+ queued jobs for "Refreshing Blitz cache", and each one just runs very slowly (e.g. Checking 103 of 321 entry queries), which takes about a few minutes to finish just a single job. Also the number of the jobs gradually goes up rather than coming down - seems like new jobs have been added in for some reasons.

blitz.log doesn't really give errors or warnings regarding this issue. queue.log doesn't complain either.

Is that because I'll need to optimize my front end template rendering, or optimize the database somehow?

I would really appreciate your advise. Let me know if you need other information.

### Additional context
`{
    "cacheIds": [],
    "elements": {
        "craft\\elements\\Entry": {
            "elementIds": [
                227069
            ],
            "sourceIds": [
                "2"
            ]
        }
    },
    "clearCache": true,
    "description": null
}`

**Comment by bencroker** [comment]
Have you tried the recommendations in the common issue "The refresh cache queue jobs run for long periods of time and sometimes pile up"?
https://putyourlightson.com/plugins/blitz#the-refresh-cache-queue-jobs-run-for-long-periods-of-time-and-sometimes-pile-up
