### ISSUE TITLE
Config setting to turn of Warm Cache Functionality?

### ISSUE THREAD

**Issue by Osze** [putyourlightson/craft-blitz#275]
### Is your feature request related to a problem? Please describe.
I would like a feature to turn off the warm cache feature on a site that is to big to warm cache. (takes to much server capacity)
Removing the buttons "Warm Cache" "Refresh Cash" would be enough. 

I have administrator that are super admins but I would like a setting in the config file so they don't warm their 30 000 entries sites.

**Comment by bencroker** [comment]
Instead of a config setting, I would probably opt to allow setting the `Cache Warmer` to `None`, what do you think?

![Screenshot 2020-12-14 at 15 38 26](https://user-images.githubusercontent.com/57572400/102094322-7b195500-3e22-11eb-9b52-c4bcca08a297.png)

**Comment by Osze** [comment]
That would be perfect! 👍

**Comment by bencroker** [comment]
Added in https://github.com/putyourlightson/craft-blitz/commit/4c0bbdb0ed9d83e7d895985204ca575397d74766 for the next release.

**Comment by bencroker** [comment]
Released in 3.7.0.
