### ISSUE TITLE
Cache is being cleared every few minutes

### ISSUE THREAD

**Issue by michaelramuta** [putyourlightson/craft-blitz#276]
### Question
Blitz caches are not lasting more than 5-15 minutes on all pages of our site, according to the `<!-- Cached by Blitz on 2020-12-16T14:50:25-06:00 -->` elements on pages. There are no entries being updated and `cacheDuration` is not set (so it shouldn't be refreshing). We do have regular Freeform submissions coming in but not much else is changing. Any ideas on what could be going wrong?

### Additional context
Craft Version: 3.5.14
Blitz Version: 3.6.11

**Comment by michaelramuta** [comment]
I took a look at the Blitz File Storage directory and indeed all my cached pages are getting wiped out pretty regularly. Trying to figure what could be triggering this...

**Comment by bencroker** [comment]
Anything showing up in the `blitz.log` file that could give you a clue?

**Comment by michaelramuta** [comment]
Nope, no logs there for the past few days

**Comment by bencroker** [comment]
Enabling the `debug` config setting should populate the log file more verbosely.

**Comment by michaelramuta** [comment]
@bencroker Ah! I found a cron job that is saving a global, that must be doing it! Is there a hook I can use to avoid clearing cache on that specific element save?

**Comment by michaelramuta** [comment]
Update: I'm going to try to use something besides a global for this.

**Comment by bencroker** [comment]
That sounds wise!

**Comment by michaelramuta** [comment]
Thanks for your help @bencroker!
