### ISSUE TITLE
Warmer only working on the homepage

### ISSUE THREAD

**Issue by benjaminleonard** [putyourlightson/craft-blitz#277]
### Describe the bug
When I run the warmer through either the utilities tab or the terminal, the only page that gets cached is the homepage. The others I can only cache manually by visiting the pages.

When I run `./craft blitz/cache/warm` – it correctly shows the number of pages (12/12) by the loader but still only one shows in the admin panel.

I've tried manually adding the URIs to the "Custom Site URIs" with no luck.

Changing the cache warmer to "Local Warmer" gives me all 12 pages, however, they aren't rendered correctly.

### Expected behaviour
All pages should be warmed when I run the utility.

### Versions
- Plugin version: 3.6.12
- Craft version: Craft CMS 3.5.15.1

Thanks!

**Comment by bencroker** [comment]
There are a few reasons why pages might not be cached, start with the [common issues](https://putyourlightson.com/plugins/blitz#common-issues).

If that doesn't help then you can enable the [debug](https://putyourlightson.com/plugins/blitz#debugging) config setting that should help troubleshoot why pages are not being cached.

**Comment by benjaminleonard** [comment]
Hey Ben, thanks for the response. I managed to get it working by removing part of the layout that checked if a user had access to the page:

```
{% if privacy.makePrivate %}
  {% requireLogin %}

  <!-- Get list of user ids from authenticated users field and set into an array -->
  {% set loggedInUser = currentUser.id ?? null %}

  {% set noAccess = not craft.authenticatedUser.getAllUsers(entry.id ?? null,currentUser.id ?? null) %}

  {% if noAccess %}
    {% redirect "denied" %}
  {% endif %}
{% endif %}
```

**Comment by bencroker** [comment]
Glad to hear it!
