### ISSUE TITLE
GetTemplate helper is using 'http' instead 'https'.

### ISSUE THREAD

**Issue by OneX** [putyourlightson/craft-blitz#278]
### Describe the bug
[GetTemplate](https://putyourlightson.com/plugins/blitz#craft.blitz.gettemplatetemplate-name-params) helper is using 'http' instead 'https'.

I can confirm that this is not happening on my local environment, but only on our fortrabbit staging environment.

You can see error here.
https://stg-goodsoil.frb.io/resources/gaining-ground-as-a-truly-evangelistic-church/

Helper should use https to avoid mixed content warning.

<img width="1248" alt="Slika zaslona 2020-12-23 u 13 15 27" src="https://user-images.githubusercontent.com/3229119/102995333-1c8a6000-4521-11eb-8f27-abb6f9de59d8.png">

### Versions
- Plugin version: 3.6.12
- Craft version: 3.4.9

**Comment by bencroker** [comment]
Can you show me your Twig code that generates that request?

**Comment by bencroker** [comment]
It looks like the request goes out as `https` but that the response contains a redirect to a `http` URL, so most likely an issue with your response or a server configuration issue.

<img width="710" alt="Screenshot 2020-12-23 at 13 37 46" src="https://user-images.githubusercontent.com/57572400/102996964-5315aa00-4524-11eb-8052-7508e236c44a.png">

**Comment by OneX** [comment]
I will check with my hosting provider. Do you still need twig code that generates request?

**Comment by bencroker** [comment]
No, I'm confident that it is either to do with the code in the template you are including, or with the server.
