### ISSUE TITLE
Split URL patterns for cache invalidation and warming

### ISSUE THREAD

**Issue by wbrowar** [putyourlightson/craft-blitz#28]
I've got a site that includes lots of pages that I want cached by Blitz, but the task of warming the cache takes a while because my URL pattern causes all URLs to be invalidated and warmed again upon save. 

On my site where performance is critical, I'm trying cut down as many unnecessary processes as possible. I could turn off cache warming, but I really like the feature in general.

It would be great to be able to set up separate rules for cache invalidation and warming. For example, to set a rule based on sections so if I save an entry in the `Blog` section, invalidate and warm `blog` and `blog/.*` URLs.

**Comment by putyourlightson** [comment]
You really only need to warm the cache when you make changes to multiple template files. For content changes, Blitz is intelligent enough to only clear and warm the cache for the URLs affected by the changes, so that aspect should already by optimised. In what situation are you finding that all URLs are being invalidated?

**Comment by wbrowar** [comment]
Ben, sorry I didn't respond back before.. I got really busy and couldn't find time to look into it until now. 

Your recent changes seem to have made an improvement to my site in question. I'm not sure what specific changes fixed it, but warming and invalidating the cache seem to be less taxing than before. Thanks!

**Comment by putyourlightson** [comment]
No problem Will. I moved the clearing of cache into a queue job and optimised the entire process, glad to hear it has helped!
