### ISSUE TITLE
Adding Entry ID to element source ID attributes used in Source Tags functionality

### ISSUE THREAD

**Issue by bryantAXS** [putyourlightson/craft-blitz#280]
### Describe the solution you would like
It would be great to add entryId to the supported element source ID attributes used in the Source Tags functionality. That way, you can refresh the cache on an individual entry when it is saved.

### Describe alternatives you have considered
The existing tags are broad and don't let you refresh on entry per entry basis, so that wouldn't work in this case. I use a custom module to do this currently, but it seems like something that could pretty easily be done natively within the plugin.

**Comment by bencroker** [comment]
> That way, you can refresh the cache on an individual entry when it is saved.

Blitz already does this by default. What benefit would there to being able to manually refreshing an entry using a tag?

**Comment by bryantAXS** [comment]
Does this happen if you have `cacheElementQueries` and `cacheElements` set to false?

**Comment by bencroker** [comment]
No it does not. I would offer the same advice here as in https://github.com/putyourlightson/craft-blitz/issues/279#issuecomment-757707820, since it sounds like you're looking for workarounds rather than dealing with the root issue directly.
