### ISSUE TITLE
Reverse Proxies Cache not clearing upon entry update

### ISSUE THREAD

**Issue by ljclark** [putyourlightson/craft-blitz#281]
### Describe the bug
When updating an element (i.e an asset field), it isn't clearing the Cloudflare cache, which results in the changes not being shown on the front end where that element is used. 

I'm currently having to manually hit the Purge Cache (Deletes all cached pages in the reverse proxy) button in the utilities for this to clear CF's caches. 

There's also an edge case where you sometimes have to clear the default craft caches to get things to show too, although this is intermittent (I'm not using any craft cache tags in my templates). 

### To reproduce
Steps to reproduce the behaviour:
1. Change the image in an asset field within an entry.
2. Save the entry, and try preview those changes on the front end. They'll likely not be updated. 
3. Hit the Purge Cache and it usually sorts it out

### Versions
- Plugin version: 3.7.0
- Craft version: Craft Pro 3.5.17.1

**Comment by bencroker** [comment]
Your title says "upon entry update" but there is no mention of updating an entry in your steps to reproduce. Can you please clarify so I can better help troubleshoot?

**Comment by ljclark** [comment]
So if you update an image in an asset field on an entry, then save that entry with the new changes.

**Comment by ljclark** [comment]
Closing this as it seems to be working now!
