### ISSUE TITLE
Commands before/after execution folder

### ISSUE THREAD

**Issue by kobeaerts** [putyourlightson/craft-blitz#282]
### Question
I'm using the Git Deployer commands to copy some files over to the git folder of my static files.

The command is `./post-static-deploy.sh`, this works fine when I execute ./craft blits/cache/refresh from the command line. 
But when Blitz updates the cache after an entry change I get queue errors that it couldn't execute the script. 

This is the error I get:
```The command "./post-deploy.sh;" failed. Exit Code: 127(Command not found) Working directory: /home/runcloud/webapps/webosaurusbeta/public Output: ================ Error Output: ================ sh: 1: ./post-deploy.sh: not found```

It seems like it want to execute the script from the public folder instead of the project root?

**Comment by bencroker** [comment]
There are two entry points to the script depending on where it is executed from (web or console). For that reason it is best to change the directory to the project root before running any commands.

```shell
cd \path\to\project\root;
```
