### ISSUE TITLE
Lscache?

### ISSUE THREAD

**Issue by ursbraem** [putyourlightson/craft-blitz#284]
### Question
Do you support or plan to support Litespeed Cache? 

### Additional context
https://plugins.craftcms.com/lite-speed-cache is EOL and recommends blitz

**Comment by bencroker** [comment]
Blitz supports caching to the file system as well as any cache storage driver that Yii supports. There are no plans to support LiteSpeed Cache or any other server-specific caches, however I think you're find that what Blitz offers is sufficiently fast and much more efficient.
