### ISSUE TITLE
Error: Call to undefined method craft\elements\Entry::lowerDisplayName()

### ISSUE THREAD

**Issue by alexroper** [putyourlightson/craft-blitz#285]
### Describe the bug

When the Refreshing Blitz Cache task runs, it fails with this error: 

> Call to undefined method craft\elements\Entry::lowerDisplayName()

I'm guessing the reason this is happening is that I'm running an older install of Craft 3.2.8. According to the Craft API docs, the lowerDisplayName() method wasn't added till Craft 3.3.17.

https://docs.craftcms.com/api/v3/craft-elements-entry.html#method-lowerdisplayname

Looks like Blitz only requires Craft 3.2.1. That might need to be upped to at least 3.3.17.

### To reproduce

Steps to reproduce the behaviour:

1. Update an entry.
2. Watch the task queue start up and immediately fail.
3. Check the queue table in the database, error column for the error "Call to undefined method craft\elements\Entry::lowerDisplayName()"

### Versions
- Plugin version: 3.6.5
- Craft version: 3.2.8

**Comment by bencroker** [comment]
Fixed in https://github.com/putyourlightson/craft-blitz/commit/46f9895ad8425d4cb709d7dcc1acdfbc792893ee for the next release, thanks!

**Comment by bencroker** [comment]
Released in 3.8.0.
