### ISSUE TITLE
Configurable Log Output

### ISSUE THREAD

**Issue by mattgrayisok** [putyourlightson/craft-blitz#286]
### Is your feature request related to a problem? Please describe.

Outputting logs to the disk is a pain in load balanced or trendy Docker based environments as they either become fragmented over multiple disks or are just lost on ephemeral systems.

### Describe the solution you would like

A config option to send logs to Craft's default log output (normally this would be stdout when using docker etc)

### Describe alternatives you have considered

¯\_(ツ)_/¯

### Additional context

Servd doesn't allow direct access to filesystems because of its ephemeral container setup so clients can struggle to find Blitz logs.

Cheers

**Comment by bencroker** [comment]
Blitz uses the [Log To File](https://github.com/putyourlightson/craft-log-to-file) helper, which by default will log to Craft in addition to `blitz.log`, so all logs should be available to servd users in the Craft logs.
https://github.com/putyourlightson/craft-log-to-file/blob/c03aec429710e9b3d54392cd75881090ae1c6457/src/LogToFile.php#L159

**Comment by mattgrayisok** [comment]
Ok, I'll have a closer look to see what's going on there then 👍

**Comment by bencroker** [comment]
Ensure that the user has the latest version of the Log To File helper installed. Let me know if you discover otherwise.
