### ISSUE TITLE
Custom ResourceBaseUrl config causes 500 error in the CacheRequestService

### ISSUE THREAD

**Issue by lenvanessen** [putyourlightson/craft-blitz#287]
### Describe the bug
If you create a custom value for the resourceBaseUrl, with the protocol included, Blitz will break the site causing all requests to generate this error.

![Schermafbeelding 2021-01-31 om 18 05 48](https://user-images.githubusercontent.com/23024452/106391759-43289a00-63ef-11eb-8e11-5d6ed748660f.png)

**Comment by bencroker** [comment]
You've closed this issue twice, has the problem gone away?

**Comment by lenvanessen** [comment]
Hi Ben,

Yes, kind of, I forgot to add a path. My setting was:
https://domainname.com/

instead of
https://domainname.com/cpresources.

Nevertheless, it might still be something you want to check out, it should not produce a 500 error.

Cheers;)

**Comment by bencroker** [comment]
Agreed that it should not throw an exception, fixed in https://github.com/putyourlightson/craft-blitz/commit/cb7c6be6a8fd0ada28a1facf98111e6f8c25bf06 for the next release.

**Comment by bencroker** [comment]
Released in 3.8.0.
