### ISSUE TITLE
Image asset urls in templates are cached with my local development url

### ISSUE THREAD

**Issue by gkpo** [putyourlightson/craft-blitz#288]
I have a page that I want to remote deploy to Netlify.
My issue is that image urls in that page are kept as full urls of my development environment: `http://localhost:8888/assets/pages/_medium/image.jpg` and so obviously when it's online it doesn't work anymore.
I'd like to remove the prefix so that the url starts with `/assets/` then it should also work when deployed online.
Not even sure this is a Blitz related question, but i'm thinking maybe someone here has the solution ? I've been pulling my hair out and can't find a way this is frustrating.
Thanks in advance

**Comment by bencroker** [comment]
You should be able to set the asset volume URL to a relative URL, for example `/assets/pages`.

**Comment by gkpo** [comment]
That worked : ) thanks a lot
