### ISSUE TITLE
Blitz not recognizing reordering of structured entries

### ISSUE THREAD

**Issue by ballmannweber** [putyourlightson/craft-blitz#289]
we noticed that blitz, which i love by the way, doesn’t recognize that we reordered structured entries since the frontend doesn’t reflect those changes. is that right or is it an error on our configuration?

**Comment by bencroker** [comment]
That is correct, reordering of elements within a structure does not trigger a cache refresh. The reason for this is that reordering a structure can lead to a large number of cache refresh jobs that pile up and tend to clear more pages than necessary. I will leave this issue open and look into whether we can consider adding this as a feature at some stage in future.

**Comment by bencroker** [comment]
Note to self that implementing this should be possible once the local warmer becomes the default and the stale-while-revalidate pattern becomes available.

**Comment by bencroker** [comment]
Added in https://github.com/putyourlightson/craft-blitz/commit/140378553a73252e55a9b87442b4b31f021f960d for the 4.0.0 release.

**Comment by bencroker** [comment]
Released in version 4.0.0.
