### ISSUE TITLE
EVENT_BEFORE_OUTPUT event

### ISSUE THREAD

**Issue by jasondibenedetto** [putyourlightson/craft-blitz#290]
We have been wanting to set some custom headers for the outputted blitz files. Have checked out this old issue https://github.com/putyourlightson/craft-blitz/issues/112#issuecomment-510363299 which details using the event `EVENT_BEFORE_OUTPUT` in order to achieve this.

Currently running into the following error (assuming because this implementation has changed since)

> Exception 'Error' with message 'Class "putyourlightson\blitz\services\OutputCacheService" not found'

Is there a new recommended way to go about this?

**Comment by bencroker** [comment]
Yes, that does look like an old event. You can use `CacheRequestService::EVENT_AFTER_GET_RESPONSE` in the latest version of Blitz. Here is where it is used:
https://github.com/putyourlightson/craft-blitz/blob/cb7c6be6a8fd0ada28a1facf98111e6f8c25bf06/src/services/CacheRequestService.php#L270

**Comment by jasondibenedetto** [comment]
Thanks @bencroker
