### ISSUE TITLE
SQL errors while  updating Blitz 

### ISSUE THREAD

**Issue by E2design** [putyourlightson/craft-blitz#291]
### Question
While updating Blitz on an existing site I ran into this SQL error. Choosing to restore the DB from the CP  puts me into an endless loop -> database has been restored -> In order to to complete the update... click yes -> back to the error message again.

- Hosted at Arcustech
- Craft 3.4.22.1
- Blitz 3.7.0 (according composer, but that's probably after the failed update)

Database Exception: SQLSTATE[HY000]: General error: 1025 Error on rename of './av04135b/#sql-242_2c38' to './av04135b/blitz_elementcaches' (errno: 150 - Foreign key constraint is incorrectly formed)
The SQL being executed was: DROP INDEX `blitz_elementcaches_cacheId_elementId_unq_idx` ON `blitz_elementcaches`

Migration: putyourlightson\blitz\migrations\m200721_120000_add_primary_keys

Output:

    > drop index blitz_elementcaches_cacheId_elementId_unq_idx on {{%blitz_elementcaches}} ...Exception: SQLSTATE[HY000]: General error: 1025 Error on rename of './av04135b/#sql-242_2c38' to './av04135b/blitz_elementcaches' (errno: 150 - Foreign key constraint is incorrectly formed)
The SQL being executed was: DROP INDEX `blitz_elementcaches_cacheId_elementId_unq_idx` ON `blitz_elementcaches` (/storage/av04135/www/public_html/vendor/yiisoft/yii2/db/Schema.php:674)
#0 /storage/av04135/www/public_html/vendor/yiisoft/yii2/db/Command.php(1298): yii\db\Schema->convertException(Object(PDOException), 'DROP INDEX `bli...')
#1 /storage/av04135/www/public_html/vendor/yiisoft/yii2/db/Command.php(1093): yii\db\Command->internalExecute('DROP INDEX `bli...')
#2 /storage/av04135/www/public_html/vendor/yiisoft/yii2/db/Migration.php(507): yii\db\Command->execute()
#3 /storage/av04135/www/public_html/vendor/craftcms/cms/src/helpers/MigrationHelper.php(118): yii\db\Migration->dropIndex('blitz_elementca...', '{{%blitz_elemen...')
#4 /storage/av04135/www/public_html/vendor/putyourlightson/craft-blitz/src/migrations/m200721_120000_add_primary_keys.php(28): craft\helpers\MigrationHelper::dropIndexIfExists('{{%blitz_elemen...', Array, true, Object(putyourlightson\blitz\migrations\m200721_120000_add_primary_keys))
#5 /storage/av04135/www/public_html/vendor/craftcms/cms/src/db/Migration.php(52): putyourlightson\blitz\migrations\m200721_120000_add_primary_keys->safeUp()
#6 /storage/av04135/www/public_html/vendor/craftcms/cms/src/db/MigrationManager.php(233): craft\db\Migration->up(true)
#7 /storage/av04135/www/public_html/vendor/craftcms/cms/src/db/MigrationManager.php(153): craft\db\MigrationManager->migrateUp(Object(putyourlightson\blitz\migrations\m200721_120000_add_primary_keys))
#8 /storage/av04135/www/public_html/vendor/craftcms/cms/src/services/Updates.php(233): craft\db\MigrationManager->up()
#9 /storage/av04135/www/public_html/vendor/craftcms/cms/src/controllers/BaseUpdaterController.php(510): craft\services\Updates->runMigrations(Array)
#10 /storage/av04135/www/public_html/vendor/craftcms/cms/src/controllers/UpdaterController.php(203): craft\controllers\BaseUpdaterController->runMigrations(Array, 'restore-db')
#11 [internal function]: craft\controllers\UpdaterController->actionMigrate()
#12 /storage/av04135/www/public_html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#13 /storage/av04135/www/public_html/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#14 /storage/av04135/www/public_html/vendor/craftcms/cms/src/web/Controller.php(178): yii\base\Controller->runAction('migrate', Array)
#15 /storage/av04135/www/public_html/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('migrate', Array)
#16 /storage/av04135/www/public_html/vendor/craftcms/cms/src/web/Application.php(291): yii\base\Module->runAction('updater/migrate', Array)
#17 /storage/av04135/www/public_html/vendor/craftcms/cms/src/web/Application.php(646): craft\web\Application->runAction('updater/migrate')
#18 /storage/av04135/www/public_html/vendor/craftcms/cms/src/web/Application.php(243): craft\web\Application->_processUpdateLogic(Object(craft\web\Request))
#19 /storage/av04135/www/public_html/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#20 /storage/av04135/www/public_html/public/index.php(42): yii\base\Application->run()
#21 {main}

**Comment by bencroker** [comment]
I've never encountered such an error. Since it sounds like this is on a live site, your best bet might be to uninstall Blitz and run a fresh install. You can prevent the DB migration from running by deleting `vendor/putyourlightson/craft-blitz/src/migrations/m200721_120000_add_primary_keys.php` and then perform the reinstall. Note that your plugin settings will be lost unless you have them in config settings.

**Comment by E2design** [comment]
that did the job!

**Comment by bencroker** [comment]
Glad to hear it!
