### ISSUE TITLE
Blitz & Seomatic savings are really slow (several minutes to save one setting)

### ISSUE THREAD

**Issue by davidhellmann** [putyourlightson/craft-blitz#292]
### Describe the bug
With Blitz activated when we save something inside SEOmatic it lasts several minutes to save this page.
When Blitz is deactivated it's fast as usual.

Currently we have a 80 Multisites setup and I think thats the problem here. But in detail it looks like the same behaviour like the `refreshCacheAutomaticallyForGlobals` setting. 

And it's not relevant if `cachingEnabled` is true or false. 

### To reproduce
Steps to reproduce the behaviour:
- Resave SEOmatic SiteSettings (as example)

### Expected behaviour
- normal saving duration

### Versions
- Plugin version: 3.6.5
- Craft version: 3.6.7

**Comment by bencroker** [comment]
When you save a site's SEOmatic settings, it invalidates all of the meta container caches, which in turn refreshes the Blitz cache in https://github.com/putyourlightson/craft-blitz/blob/develop/src/drivers/integrations/SeomaticIntegration.php

This should add a refresh job to the queue though, so not sure why it is affecting the save action. Can you provide a few more specific steps to help reproduce?

**Comment by davidhellmann** [comment]
Hey @bencroker 
Don't have more details about reproducing :(
I just save something within SEOmatic and it lasts round about 7 minutes to save. 

Afterwards when I'm looking into the queue manager there are no jobs
![image](https://user-images.githubusercontent.com/764292/109463695-bf9daf80-7a65-11eb-9a69-8deab78399ff.png)

With Blitz disabled it's fast.

**Comment by bencroker** [comment]
> I just save something within SEOmatic and it lasts round about 7 minutes to save.

Please explain these steps so I can reproduce.

**Comment by davidhellmann** [comment]
I just go to `/admin/seomatic/site/identity` and hit the save Button. Nothing more. But we have a site with 80 Multisites in it. Maybe this is part of the problem. 

And as I wrote above, the same problem was there when `refreshCacheAutomaticallyForGlobals` was set to `true`.
I think it's the same problem maybe?

**Comment by bencroker** [comment]
When you save a site's identity, SEOmatic triggers the `EVENT_INVALIDATE_CONTAINER_CACHES` event with `siteId` set to `null`, which Blitz interprets as refresh the entire cache for _all_ sites. Perhaps @nystudio107 can let us know if SEOmatic is triggering this event correctly or not?

https://github.com/nystudio107/craft-seomatic/blob/c76d832eb8f956b47b0c9176c7d9cfb2381e2174/src/services/MetaContainers.php#L709-L730

**Comment by khalwat** [comment]
The Identity is a global object, so this is expected behavior imo.

**Comment by bencroker** [comment]
Thanks for confirming @khalwat!
