### ISSUE TITLE
index page not cached

### ISSUE THREAD

**Issue by mmorkt** [putyourlightson/craft-blitz#293]
Hi,

Seems like my index page is not cached by Blitz.
Caching has been enabled and URI pattern is set to .*

All other pages is showing:
Cached by Blitz on XXXX-XX-25T15:02:14+01:00 

The cache folder shows that only the subfolders is generated in 'cache › blitz › site' only contains subfolders no root index.html file is added.

Any idea what I'm missing?

**Comment by pelmered** [comment]
I had the same problem. I needed to add another include rule with an empty `uriPattern` like this:

```
        'includedUriPatterns' => [
            [ // Site start/home page
                'siteId' => '',
                'uriPattern' => '',
            ],
            [ // All other pages
                'siteId' => '',
                'uriPattern' => '.*',
            ],
        ],
```

**Comment by mmorkt** [comment]
Thanks! Hmm didn't fix the problem. 

Tried making a blank line in the backend as well as making the changes in config/blitz.php. But the cache file is still not generated. could it be related to the subdomain *.cloudwaysapps.com?

**Comment by bencroker** [comment]
There are a few reasons why a page might not be cached, start with the [common issues](https://putyourlightson.com/plugins/blitz#common-issues).

If that doesn't help then you can enable the [debug](https://putyourlightson.com/plugins/blitz#debugging) config setting that should help troubleshoot why your page is not being cached.

**Comment by mmorkt** [comment]
Thanks Ben.
Seems like the generateTransformsBeforePageLoad is not activated. But it's set to true in my general.php

Getting this error in debug log: 
`2021-02-26 08:05:19 [][][debug] Page not cached because it contains transform generation URLs. Consider setting the 'generateTransformsBeforePageLoad' general config setting to 'true' to fix this. [http://xxx.xx/]`

Haven't experienced this before, and never used generateTransformsBeforePageLoad before eather.

**Comment by bencroker** [comment]
View the HTML source code and look for `assets/generate-transform` which will lead you to the culprit.

**Comment by mmorkt** [comment]
You are a life saver! Changing the Redactor generated images solved it!

**Comment by bencroker** [comment]
Glad to hear it!
