### ISSUE TITLE
Refresh Cache doesn’t work from CLI

### ISSUE THREAD

**Issue by TUSAB-web** [putyourlightson/craft-blitz#295]
### Describe the bug
When running ./craft (or php craft) blitz/cache/refresh - the cache doesn’t actually refresh. This is a linux web app on Azure. Cache refresh works fine when run from the Craft control panel in a web browser.

### To reproduce
Steps to reproduce the behaviour:
1. SSH into server, cd into the site directory.
2. Run ./craft blitz/cache/refresh
3. Check cache directory - files are unchanged from before running the command.

### Expected behaviour
The old cache should be purged, then the warmed cache entries should replace them.

### Actual behaviour
It goes through the motions, and appears to be warming the cache with the progress bar taking its time. But then it gets to the “deploying pages” step and it says 0/0 pages, and says deployment complete. When opening the cache directory, all the old cached files are still in there. I turned on debug and it doesn’t show any errors related to this. (The uncached pages mentioned are intentional exclusions)

### Screenshots
```
Blitz cache successfully cleared.
Blitz cache successfully flushed.
Blitz cache successfully purged.
Warming Blitz cache...
[===================================] 100% (687/687) ETA: 1 sec.
Warmed 685 of 687 pages. To see why pages were not cached, enable the `debug` config setting and then open the `storage/logs/blitz.log` file.
Blitz cache warming complete.
Deploying pages...
[>                                         ] 0% (0/687) ETA: n/a
Deploying complete.
```

### Versions
- Plugin version: 3.7.0
- Craft version: 3.6.8 Pro

**Comment by bencroker** [comment]
Issues with the CLI are often caused by having a `@web` alias in the site’s Base URL. 

See this common issue for more details: https://putyourlightson.com/plugins/blitz#the-site-is-not-being-cached-when-using-console-commands

**Comment by TUSAB-web** [comment]
Thanks for the reply. The Site URL is set by environmental variable: SITE_URL, which doesn’t include an alias; it’s just the url of the site: https://www.mysite.com/

**Comment by bencroker** [comment]
What about in the `Repository Path` in the Git Deployer settings?

**Comment by TUSAB-web** [comment]
I have remote deployer set to none. It is using Blitz cache storage to a folder on the local site: site/wwwroot/cache/blitz/sitename
I did think it was weird for it to list the “Deploying pages” even though there’s nothing to deploy

**Comment by bencroker** [comment]
No, that shouldn't be happening. Can you update to the latest version of Blitz? Version 3.7.1 fixed an issue which might be related: https://github.com/putyourlightson/craft-blitz/blob/develop/CHANGELOG.md#371---2021-01-05

**Comment by TUSAB-web** [comment]
I don’t see 3.7.1 as having been released when viewing it in the CP or in the plug-in store:

https://plugins.craftcms.com/blitz

**Comment by bencroker** [comment]
Ah yes, you're right, this was slated and put into 3.8.0, due to be released next week:
https://github.com/putyourlightson/craft-blitz/blob/develop/CHANGELOG.md#380---unreleased

**Comment by TUSAB-web** [comment]
I updated to 3.8.0 and I am still experiencing the problem. It looks like it is doing the task, but if I look in the cache directory, the old files are still there, and didn’t get updated. I don’t know what it thinks it is purging and recreating, but I cannot find it. The funny thing is - it works perfectly fine from the CP... but I want it to refresh cache every night while I’m sleeping and I need it to run as a cron job to accomplish that.

**Comment by bencroker** [comment]
Does running `./craft blitz/cache/clear` clear the cached files?

**Comment by TUSAB-web** [comment]
No it doesn’t. I also did `./craft clear-caches/all`which doesn’t clear it either, although it does clear craft’s other caches. In both cases, the CLI reports that it did clear the cache successfully, but the files in cache/blitz/sitename are still there, untouched. 

I manually deleted the directory cache/blitz/sitename, then ran `./craft blitz/cache/refresh` to see if that works. Again, it goes through the motions, but it never recreated the ‘sitename' cache directory inside cache/blitz. And I still get the 0% deployed thing at the end each time. Going through the CP - everything works.

**Comment by bencroker** [comment]
Can you try enabling the `debug` config setting and try the `refresh` command? Also, which cache storage driver and which warmer are you using in the settings?

**Comment by TUSAB-web** [comment]
Warmer: Guzzle
Storage: Blitz File Storage

This morning I deleted the cache folder manually and ran the CLI `refresh` command. It created the folder and populated it. A short while later I ran the `refresh` command again. It did not update any of the pages that had been refreshed earlier. I’ve attached the blitz log with debug enabled. (I noted in the debug log that I have a couple entries that shouldn’t have URIs... so I will remedy that - glad this debug caught that for me.)

[blitz.log](https://github.com/putyourlightson/craft-blitz/files/6182896/blitz.log)

**Comment by bencroker** [comment]
So it sounds like an issue with deleting the cache folder. Can you check the `cache` folder's permissions and ensure that the PHP console is allowed to delete it?

It might also be worth trying to refresh a specific cached page to see if that works:
```
./craft blitz/cache/refresh-urls http://domain.com/page
```

**Comment by TUSAB-web** [comment]
The permissions for the Azure linux web app are 777 for everything in the /home directory, which the entire site sits in. I run `composer install` when doing deployments, and I see that it is able to delete files and replace them in the vendor directory, which has the same 777 permissions as the blitz/cache directory.

I attempted to refresh that single url using the CLI without success. It returned:` Cached URLs successfully refreshed.` but the file still has the prior timestamp.

An article from Microsoft talking about permissions in their Linux web apps:

https://docs.microsoft.com/en-us/archive/blogs/waws/things-you-should-know-web-apps-and-linux#CIFS

Also: https://docs.microsoft.com/en-us/archive/blogs/waws/things-you-should-know-web-apps-and-linux#your-environment-variables-wont-appear-in-the-bash-consoleapplies-to-azure-app-service-on-linuxapplies-to-web-app-for-containers

Noting that environmental variables might not be seen by bash based on that link above, I cut and paste the results of `printenv` from the SSH session and am attaching here.

**Comment by bencroker** [comment]
I just removed your attachment as it appeared to have secrets in it. If those were live credentials then please consider resetting them and avoid sharing sensitive information here.

Is your `Cache Folder Path` set to an absolute path? Otherwise I'm running out of ideas.

**Comment by TUSAB-web** [comment]
I went to the settings in the CP and here is the setting for the cache location:

@webroot/cache/blitz

Perhaps the CP can find this, and the CLI cannot? If so, what should I change this to? Do I need to set it with the config file (per environment perhaps) instead?

**Comment by TUSAB-web** [comment]
I changed the setting to the absolute path to test, then ran the CLI refresh tool, and it worked. So, now I think I just need to look through the blitz.config for that setting and set it to an absolute path for staging and production. Does that sound correct?

**Comment by bencroker** [comment]
`@webroot` is an alias that you can define, see https://craftcms.com/docs/3.x/config/#aliases

Also for reference: https://github.com/craftcms/cms/issues/2566

**Comment by TUSAB-web** [comment]
Thanks for the help. I will check that out! Looks like `web/`is a directory Craft looks for automatically when assigning `@webroot` (used on my local dev) but `wwwroot/` (used on staging and live) is not! Thanks again for linking to the critical bit of documentation.
