### ISSUE TITLE
429 response from Cloudflare when Craft resaves section entries

### ISSUE THREAD

**Issue by john-henry** [putyourlightson/craft-blitz#296]
Blitz set up with Cloudflare and all working ok. There is an issue though if one of us makes a change to a section or similar that triggers a resave of all the entries in a section via the queue.

In that instance, it fires off jobs to clear Blitz cache after each entry save. This results in a 429 (too many requests) from Cloudflare

Is there any way to circumnavigate this?

**Comment by bencroker** [comment]
Hmm, this may be a case of exceeding the Clouflare API rate limit. Where exactly are you seeing that 429 error?

**Comment by john-henry** [comment]
I have Sentry setup which caught it

`Client error: `DELETE https://api.cloudflare.com/client/v4/zones/b3a9eedd7dxxxxxxa75e70f033097/purge_cache` resulted in a `429 Too Many Requests` response`

which also triggered 

`[41579] Refreshing Blitz cache (attempt: 1) - Error (time: 1615336211.113s): The process "'/opt/cpanel/ea-php74/root/usr/bin/php' 'craft' 'queue/exec' '41579' '2400' '1' '0' '--color='" exceeded the timeout of 2400 seconds.`

and then 

`Failed to write log to file `/home/site/production/storage/logs/blitz.log`.`

footnote. 2400 is what I set my queues ttr to and also using async-queue with just default concurrency of 2

**Comment by bencroker** [comment]
Thanks, will look into it and let you know what I discover.

**Comment by bencroker** [comment]
I've been scouring the Cloudflare docs and forums and the best I can come up with is suggesting that you add your server's IP address to an “IP Access Rule” that allows all access under _Firewall → Tools_.
https://support.cloudflare.com/hc/en-us/articles/217074967-Configuring-IP-Access-Rules#3RzbhPBhKZ5XiJ3p2uHugs

**Comment by john-henry** [comment]
Ok, Ill give it a go. Thanks @bencroker

**Comment by SETU-WEB** [comment]
Hi, an update on this as Cloudflare as the IP access rule doesn't work in the updated Cloudflare WAF. Instead, you need to do a custom WAF rule for your server IP use the skip action and then choose rate limiting rules. 
![rate-limit](https://github.com/putyourlightson/craft-blitz/assets/8246895/7c778f15-783a-45b5-af29-60580c63fed9)

**Comment by SETU-WEB** [comment]
Hi, an update on this as cloudflare as the IP access rule doesn't work under the latest Cloudflare WAF. Instead, you need to do a custom WAF rule for your server IP use the skip action and then choose rate limiting rules. 

![rate-limit](https://github.com/putyourlightson/craft-blitz/assets/8246895/27feb894-74a2-4883-b212-8cc725b954bb)

**Comment by bencroker** [comment]
Thanks for sharing that, @SETU-WEB     .

**Comment by john-henry** [comment]
FYI : This trick doesn't work anymore, unfortunately

**Comment by bencroker** [comment]
As of [5.12.8](https://github.com/putyourlightson/craft-blitz/releases/tag/5.12.8), the Cloudflare purger now sends requests sequentially rather than in parallel, and can make up to 3 attempts, to help prevent rate limiting when purging a large number of URLs.
