### ISSUE TITLE
Brotli compression

### ISSUE THREAD

**Issue by extensibleseth** [putyourlightson/craft-blitz#297]
### Describe the solution you would like
Serve brotli compressed files over gziped ones if available, and accepted.

**Comment by bencroker** [comment]
Blitz doesn't serve gzipped files, it only creates them. You need to configure your server to serve gzip and brotli files.

**Comment by extensibleseth** [comment]
@bencroker Can Blitz create the brotli files if it's installed?

**Comment by bencroker** [comment]
Just added in https://github.com/putyourlightson/craft-blitz/commit/5ffc71f36a614b0f0eea334c800ff4ddc649a014 for the next release.

**Comment by bencroker** [comment]
Released in 3.8.0.
