### ISSUE TITLE
Dependency abandoned: cpliakas/git-wrapper

### ISSUE THREAD

**Issue by toddprouty** [putyourlightson/craft-blitz#298]
Running `composer install` revealed that one of craft-blitz's dependencies has been abandoned. You may be aware but I'll pass it along just in case:

> Package cpliakas/git-wrapper is abandoned, you should avoid using it. Use symplify/git-wrapper instead.

**Comment by bencroker** [comment]
Am aware of this but thanks for the note. I have requested confirmation that it is safe to migrate to the new package in https://github.com/cpliakas/git-wrapper/issues/225#issuecomment-796888367.

**Comment by bencroker** [comment]
Unfortunately we're stuck with the abandoned package until Craft 4, since the new one requires PHP 7.3 whereas Craft has PHP 7.2.5 as its minimum requirement.
See https://github.com/cpliakas/git-wrapper/issues/225#issuecomment-796905545
