### ISSUE TITLE
Craft Console Command Error

### ISSUE THREAD

**Issue by kylecotter** [putyourlightson/craft-blitz#3]
Hey Ben,

With Blitz installed, and when running a craft console command, such as:
`./craft install/plugin <plugin>` an Exception is thrown in reference to CacheService.php line 57.

Making sure it's not a console command before running
`$uri = $request->getUrl();` solves the issue.

Thanks!

**Comment by putyourlightson** [comment]
Thanks Kyle, fixed in https://github.com/putyourlightson/craft-blitz/commit/c4ab1d5918e0df0f8e5fea68ba5a1d5baf82d3fb
