### ISSUE TITLE
Wildcards on Refresh Cached URLs

### ISSUE THREAD

**Issue by john-henry** [putyourlightson/craft-blitz#300]
A lot of the time it's great on Cloudflare to refresh a whole section for a site using a wildcard like https://mysite.com/articles/*

It would be great to have this feature in Blitz utilities under the '_Refreshes pages with the provided URLs._' section rather than limited to manually adding all URLs

**Comment by bencroker** [comment]
Great idea, will add to the list!

**Comment by bencroker** [comment]
Added in https://github.com/putyourlightson/craft-blitz/commit/0cb5599a2f1dbad7a487db960fd02f91b6a4236f for the next release.

**Comment by bencroker** [comment]
Released in 3.8.0.
