### ISSUE TITLE
nginx brotli

### ISSUE THREAD

**Issue by redkrupp** [putyourlightson/craft-blitz#301]
In the docs, I see a note on activation of brotli instead of gzip there is no information how to modify the rules for nginx server. Please advise.

**Comment by bencroker** [comment]
There is a note in the docs under https://putyourlightson.com/plugins/blitz#apache

> If you have the ​“Create Brotli Files” setting enabled then you can use the code above, swapping in `.br` for `.gz` and `brotli` for `gzip`.

**Comment by redkrupp** [comment]
It applies to apache.

**Comment by bencroker** [comment]
It again involves replacing `gzip` with `brotli`. I've added Nginx specific instructions at https://putyourlightson.com/plugins/blitz#nginx
