### ISSUE TITLE
Respect isSystemLive

### ISSUE THREAD

**Issue by simonleadbetter** [putyourlightson/craft-blitz#303]
Hi

I have just stumbled across a situation where Blitz cache is showing a cached page when the isSystemLive is set to be false.

We are running Craft 3.6.11.1 and Blitz 3.8.0.

Is this a known issue? It would be could if Blitz honoured this setting without having to clear the Blitz cache when working with the isSystemLive config setting.

Simon

**Comment by bencroker** [comment]
Blitz doesn't cache pages nor does it serve cached pages when the system is off. Could it be that you have server redirects set up? If so, then those will be unaware of that Craft system setting.

**Comment by simonleadbetter** [comment]
Thanks for confirming that Blitz honours the isSystemLive setting. We will investigate further why we were seeing the home page (until we cleared the Blitz cache) when we set isSystemLive to false.
