### ISSUE TITLE
Settings Error with cacheStorageType in config

### ISSUE THREAD

**Issue by keyurshah** [putyourlightson/craft-blitz#304]
### Describe the bug
When I use the following line in `app/blitz.php` to switch to the Yii Cache (for redis), 

```
        'cacheStorageType' => 'putyourlightson\blitz\drivers\storage\YiiCacheStorage',
```

I get the following error in the admin panel when trying to view the Bltiz settings page or the Blitz dashboard

```
Unknown Property – yii\base\UnknownPropertyException
Setting unknown property: putyourlightson\blitz\drivers\storage\YiiCacheStorage::folderPath
```

Thank you!

### To reproduce
Steps to reproduce the behaviour:
1. Modify the config file, `app/blitz.php` to use the YiiCacheStorage driver
2. Click on `admin/settings/plugins/blitz#storage`

### Expected behaviour
The file storage path shouldn't be required for the yii cache storage driver so not sure why it is asking for that.

The Yii Cache Storage driver works if I just change it in the settings directly, without modifiying `blitz.php`

### Screenshots

![image](https://user-images.githubusercontent.com/744385/114276644-64ec6180-99dc-11eb-800d-93a8e3146123.png)

full blitz.php file

https://gist.github.com/keyurshah/52b3eade74309781a5fa3fd22e1c100a

### Versions
- Plugin version: 3.8.0
- Craft version: 3.6.10

**Comment by bencroker** [comment]
You'll need to override `cacheStorageSettings` in the config file, otherwise Blitz will use that value that was previously saved.

```
'cacheStorageSettings' => [],
```

**Comment by aaronbushnell** [comment]
Hey @bencroker — it doesn't seem like an empty array is enough here. I get this error when my config looks like the following:

```php
<?php

return [
  '*' => [
    'debug' => false,
    'cachingEnabled' => true,

    'includedUriPatterns' => [
      [ 'uriPattern' => '' ],
      [ 'uriPattern' => '.*' ],
    ],

    // The storage type and settings to use.
    'cacheStorageType' => 'putyourlightson\blitz\drivers\storage\FileStorage',
    'cacheStorageSettings' => [
      'folderPath' => '@webroot/cache/blitz',
      'createGzipFiles' => true,
      'countCachedFiles' => true,
    ],
  ],

  'production' => [
    'cacheStorageType' => 'putyourlightson\blitz\drivers\storage\YiiCacheStorage',
    'cacheStorageSettings' => [],
  ]
];

```

And the error I'm getting is:
```
Unknown Property – [yii\base\UnknownPropertyException](http://www.yiiframework.com/doc-2.0/yii-base-unknownpropertyexception.html)
Setting unknown property: putyourlightson\blitz\drivers\storage\YiiCacheStorage::folderPath
```

## Version info:
- Blitz: 3.11.1
- Craft: 3.7.31
- PHP: 7.4.27
- MySQL: 5.7.37

**Comment by bencroker** [comment]
@aaronbushnell and this is happening in the `production` environment?

**Comment by aaronbushnell** [comment]
That’s correct, @bencroker!

**Comment by bencroker** [comment]
So I discovered that if config values are arrays, that they are _merged_ rather than overwritten. The solution to this is to use a `ReplaceArrayValue` object to overwrite the setting.

```
  'production' => [
    'cacheStorageType' => 'putyourlightson\blitz\drivers\storage\YiiCacheStorage',
    'cacheStorageSettings' => new yii\helpers\ReplaceArrayValue([]),
  ]
```

**Comment by aaronbushnell** [comment]
That works perfect! Thanks a bunch, @bencroker
