### ISSUE TITLE
Looks like Craft's `tokenParam` setting is ignored

### ISSUE THREAD

**Issue by benface** [putyourlightson/craft-blitz#307]
### Describe the bug
It looks like [this line](https://github.com/putyourlightson/craft-blitz/blob/develop/src/services/CacheRequestService.php#L98) assumes that [Craft's `tokenParam` setting](https://craftcms.com/docs/3.x/config/config-settings.html#tokenparam) is set to its default value, but in my project I set it to `_token` to prevent potential conflicts.

### Versions
- Plugin version: 3.8.0
- Craft version: 3.6.12

**Comment by bencroker** [comment]
Thanks, changed to use the value defined in the general config setting in https://github.com/putyourlightson/craft-blitz/commit/b40c721b0c254e6df9a1e7ae9610f3563efc0a56.

**Comment by bencroker** [comment]
Released in version 3.9.0.
