### ISSUE TITLE
Configure queue time to reserve

### ISSUE THREAD

**Issue by jasondibenedetto** [putyourlightson/craft-blitz#308]
### Is your feature request related to a problem? Please describe.
Warming Blitz Cache is failing after it exceeds the default queue timeout.

### Describe the solution you would like
Ability to set queue time to reserve for blitz jobs, similar to Feed Me's `queueTtr` option.

https://docs.craftcms.com/feed-me/v4/get-started/configuration.html
https://github.com/craftcms/feed-me/blob/e68bc785dc869b5151b4ad9d9b11f93f2aae3cd0/src/queue/jobs/FeedImport.php#L52-L55

### Describe alternatives you have considered
Currently we can override the global Craft CMS queue setting, but would be great to isolate this to only Blitz jobs.

**Comment by bencroker** [comment]
The `queueTtr` is only used if the queue job's _progress_ is not updated within the number of seconds defined. Blitz's warm cache process should update the progress after each page is warmed, so it doesn't sound like increasing the `queueTtr` would make a difference. Have you tested whether changing the global `queueTtr` actually helps avoid the issue?

I suspect the root issue might be something else. Can you describe in what scenarios the warm cache job fails and with what errors?

**Comment by jasondibenedetto** [comment]
@bencroker increasing the global `queueTtr` does resolve the issue for us, but just wanted to query if this was something others thought would be worth looking at.

Currently, this occurs after running a Feed Me import of about 400 entries, the Warm Blitz cache job fails part way through with the following error:

```
The process "'/usr/bin/php7.4-zts' 'craft' 'queue/exec' '99128' '300' '1' '2221' '--color='" exceeded the timeout of 300 seconds 

# Job Data
{
    "siteUris": [
        {
            "siteId": "1",
            "uri": "found-pets/251265"
        },
        ...
    ],
    "driverId": "cacheWarmer",
    "driverMethod": "warmUrisWithProgress",
    "delay": 0,
    "description": "Warming Blitz cache"
}
```

The uris for these entries updated by Feed Me are also set in our `excludedUriPatterns` blitz config.

```
# blitz.php

'excludedUriPatterns' => [
    [
        'uriPattern' => '/found-pets/*',
    ],
]
```

Thanks!

**Comment by bencroker** [comment]
Was there just a single site URI in the warm cache job, or did you only show one? A single job should not cause a timeout, so this would be an abnormal scenario if it was the case.

**Comment by jasondibenedetto** [comment]
@bencroker that was an excerpt, there was about 400 siteUris. for example:

```
{
    "siteId": "1",
    "uri": "found-pets/249805"
},
{
    "siteId": "1",
    "uri": "found-pets/249878"
},
{
    "siteId": "1",
    "uri": "found-pets/248254"
},
{
    "siteId": "1",
    "uri": "found-pets/248923"
},
{
    "siteId": "1",
    "uri": "found-pets/248924"
},
{
    "siteId": "1",
    "uri": "found-pets/248925"
}

...
```

**Comment by bencroker** [comment]
So am I correct in understanding that you're expecting those site URIs to not be cached? Can you try this in your `blitz.php` config?

```php
'excludedUriPatterns' => [
    [
        'siteId' => '',
        'uriPattern' => '/found-pets/*',
    ],
]
```

**Comment by jasondibenedetto** [comment]
Sorry for the confusion, the uris are being cached all correctly as expected, no issues in that area (updating our `excludedUriPatterns` to the above also yields the same results).

To clarify, the error only appears to be happening after a Feed Me import is run. A regular blitz action cache refresh works fine.

**Comment by bencroker** [comment]
Ok, added the `queueJobTtr` config setting in https://github.com/putyourlightson/craft-blitz/commit/04e11ecc20798e66a6ceec53759881b5ed40dcd4, for the next release.

**Comment by jasondibenedetto** [comment]
Thank you @bencroker, appreciate it.

**Comment by bencroker** [comment]
Released in version 3.9.0.

**Comment by danethomas** [comment]
@bencroker In `app.php`, we previously had

```
        'queue' => [
            'class' => craft\queue\Queue::class,
            'ttr' => 30 * 60,
        ],
```

Which Blitz would take into consideration for its caching queue jobs. With this recent change I can see that this has moved into a config setting (which I'll add and update). 

Just wondering if the intention was by default to fall back to the ttr in `app.php` or you just plan on keep the default 300 and allowing the override?

**Comment by bencroker** [comment]
By having this as a setting in Blitz, there is no way to fall back to the value set in `app.php`, so you'll need to update the value in `blitz.config` explicitly.
