### ISSUE TITLE
Caching works only for the primary

### ISSUE THREAD

**Issue by belkin** [putyourlightson/craft-blitz#310]
### Describe the bug
Hi, 
I installed Blitz on multisite setup but Blitz is caching only primary website and not the other pages. With debug enabled I'm getting this message: 
`2021-04-22 08:41:43 [][6][debug] Page not cached because it does not match an included URI pattern. [https://local.page.com/nl]` 

All other settings are the recommended ones and there is nothing changed.

### To reproduce
Steps to reproduce the behaviour:
1. Enable Blitz caching
2. Leave blank 'Included URI Patterns' for only homepage caching (this is not working also with filled pattern)
3. Go to homepage of not primary site

### Expected behaviour
To cache every website in my situation only the homepage

### Screenshots
URL's for the projects are set via .env and general.php files: 
ENV:
`BASE_URL="https://local.page.com/"`
general.php:
`'aliases' => [ 'baseUrl' => trim(getenv('BASE_URL'), '/'), ],`

![image](https://user-images.githubusercontent.com/3419659/115708446-4be69780-a370-11eb-90ee-b67f7d350819.png)

### Versions
- Plugin version: 3.8
- Craft version: 3.4.27

**Comment by bencroker** [comment]
Can you please show me the included URI patterns in your settings?

This issue sounds very much like https://github.com/putyourlightson/craft-blitz/issues/309, so I'll test for both included and excluded URI patterns and update here when I have more.

**Comment by bencroker** [comment]
This should hopefully be fixed in https://github.com/putyourlightson/craft-blitz/commit/50a7840440c3ac28b6e1790397f2d4812247bceb. You can either test locally now or wait for the next release.

**Comment by belkin** [comment]
> Can you please show me the included URI patterns in your settings?
> 
> This issue sounds very much like #309, so I'll test for both included and excluded URI patterns and update here when I have more.

They are both left empty for homepage only. 
![image](https://user-images.githubusercontent.com/3419659/115833008-da602500-a413-11eb-8af4-6d40cfed9820.png)


> This should hopefully be fixed in [50a7840](https://github.com/putyourlightson/craft-blitz/commit/50a7840440c3ac28b6e1790397f2d4812247bceb). You can either test locally now or wait for the next release.

It works! I've tested it with empty URI pattern for both websites and with All sites option and it works fine.

Thanks again.

**Comment by bencroker** [comment]
Great, will aim to release this early next week.

**Comment by bencroker** [comment]
Released in version 3.9.0.
