### ISSUE TITLE
No site URI could be determined from the requested URL

### ISSUE THREAD

**Issue by michaelramuta** [putyourlightson/craft-blitz#311]
Hey there! I'm getting these errors rolling in pretty much constantly `No site URI could be determined from the requested URL – ensure that the base site URL is correctly set. [IP-Address-Looking-URL]` 
The site is working fine and things are being cached, so I'm confused as to how the baseUrl would be improperly set. 

The client is hosting this and we have limited access to the server, but it looks like the address it is grabbing is the REMOTE_ADDR from their ENV. I'm sure there is some config I'm missing so I'm going to keep poking around but holler if any of this sounds familiar!

The env `$PRIMARY_SITE_URL` is saved as the Site Base URL through settings, and for good measure I added this to the general config: 
```
'aliases' => [
            '@web' => getenv('PRIMARY_SITE_URL'),
            '@baseUrl' => getenv('PRIMARY_SITE_URL')
        ],
```

**Comment by bencroker** [comment]
Is the site accessible from "`[IP-Address-Looking-URL]`"? If so, then perhaps a redirect would solve it?

**Comment by michaelramuta** [comment]
@bencroker Nope, and it is constantly changing anyways. The site is load balanced and I think this address is the servers.

**Comment by bencroker** [comment]
Are these debug messages (I don't consider them errors) appearing when warming the cache or at random times?

**Comment by michaelramuta** [comment]
It seems like they're just constantly rolling in, like 15x a minute. I don't think it's tied to warming... but I will poke around a bit more over the weekend to see if I can find any common denominators

**Comment by bencroker** [comment]
So that sounds like requests hitting your server's IP address(es), possibly to do with the load-balancer setup. Blitz is correctly ignoring them from caching, all seems well here.

**Comment by michaelramuta** [comment]
Sounds good, thanks!
