### ISSUE TITLE
No site URI could be determined from the requested URL

### ISSUE THREAD

**Issue by jskrivanek** [putyourlightson/craft-blitz#312]
Hi,

I run into a similar issue as here:
https://github.com/putyourlightson/craft-blitz/issues/166

$ tail -f craft/storage/logs/blitz.log
2021-04-23 11:39:07 [][1][debug] No site URI could be determined from the requested URL – ensure that the base site URL is correctly set. [https://www.domain.com/]

Nothing is getting cached.

![Screenshot 2021-04-23 at 11 51 45 am](https://user-images.githubusercontent.com/12047827/115917388-77ec4080-a476-11eb-9565-bcb9471dfc74.png)
![Screenshot 2021-04-23 at 11 51 17 am](https://user-images.githubusercontent.com/12047827/115917392-791d6d80-a476-11eb-98ba-75ae49a0c812.png)
![Screenshot 2021-04-23 at 11 51 10 am](https://user-images.githubusercontent.com/12047827/115917395-79b60400-a476-11eb-847c-ba25901644b0.png)

### Versions
- Plugin version: 3.8
- Craft version: 3.6.11.2

**Comment by bencroker** [comment]
Are your site base URLs set to absolute URLs? And if not, then how are they determined? Check the common issues for ideas of why it might not be caching: https://putyourlightson.com/plugins/blitz#common-issues

**Comment by jskrivanek** [comment]
@bencroker This solved the issue. Wish me luck...

<img width="634" alt="Screenshot 2021-04-24 at 8 24 54 am" src="https://user-images.githubusercontent.com/12047827/115949616-96822400-a4d6-11eb-98ca-65907594bc96.png">
