### ISSUE TITLE
Question: Serving Homepage based on user group

### ISSUE THREAD

**Issue by michaelramuta** [putyourlightson/craft-blitz#313]
Hey there!

I'm working on setting up blitz caching for a homepage. We serve up very different content based on if the user belongs to a certain user group or not. Tried to get the dynamic content piece working, but it's just too sluggish.

Is there a hook/event we can use in a module to render different cached pages based on the user group of the current user? I've been reading through your plugin and `craft\web\View` so I'm sure there's something that will work. Mind pointing me in the right direction?

Thanks!
-Michael

**Comment by bencroker** [comment]
Hi Michael,

Blitz provides [dynamic content](https://putyourlightson.com/plugins/blitz#dynamic-content) tags for this purpose, although it sounds like you want to selectively show different content, which understandably will cause jank. Blitz statically caches full pages so there's no obvious workaround, however you could possibly get away with using query string parameters, for example `?group=1`.

There's a similar issue which was discussed here that you may find helpful:
https://github.com/putyourlightson/craft-blitz/issues/302
