### ISSUE TITLE
Turning OFF devMode on production results in blank pages with "there was an internal server error" when browsing

### ISSUE THREAD

**Issue by chadcrowell** [putyourlightson/craft-blitz#314]
Hey Ben - I just got finished with a new Blitz implementation on www.gcx.com. Such a killer plugin, thanks for releasing it. 

I have a lot of work to do for optimization in the next month or so on this newly launched Craft site, but in the meantime I've gotten Blitz all setup and working. Its perfect when testing on my local, and when deployed and enabled on production. When I deployed it, I also turned on devMode on production so I could check a few things as Blitz began to do its thing. And it did work as expected. I then, via SFTP, changed devMode on production to false, saved the general config file, and went back to browsing the site. The first few pages were fine, all cached and super quick... but then I hit a page that hadn't cached yet and got a white page with simple black text at the top "there was an internal server error" (that may not be exact wording). I quickly turned devMode back on, and the page loaded as expected. I cleared the Blitz cache thinking it was just a blip but I tried 3 or 4 more times and the same thing kept happening. So, I have Blitz enabled but devMode on on production for now.

Nothing in the Blitz log
Nothing in the web log that is obvious

Have you seen this before?

**Comment by bencroker** [comment]
Glad to hear it's working well on the site, Chad!

I have not encountered this before, but you should be able to track down the "internal server error" in the PHP logs. Could it be that OPcache is enabled on the server and that changing the `devMode` setting via FTP is not restarting FPM? Regardless, you should really find the PHP logs to figure out what the error is as a first step.
