### ISSUE TITLE
OpenLiteSpeed

### ISSUE THREAD

**Issue by redkrupp** [putyourlightson/craft-blitz#315]
Hey,

What's the best way to use blitz with openlitespeed? Should we use the .htaccess rewrite rule for best results and just let it run? How does it compare with built-in LS cache module? Anything we need to be worried about? Regards

**Comment by bencroker** [comment]
Yes, Blitz should be sufficiently fast and much more efficient. Please see https://github.com/putyourlightson/craft-blitz/issues/284 about LS cache.
