### ISSUE TITLE
Question regarding the CloudFront Purger's recommended Warmer Delay setting

### ISSUE THREAD

**Issue by markdrzy** [putyourlightson/craft-blitz#316]
In the CloudFront Reverse Proxy Purger, the instructions for the "Warmer Delay" field read as follows:

> It can take up to 30 seconds for cached files to be purged across all edge nodes. Adding a delay between purging the cache and warming it will prevent stale versions of pages from being warmed. A value of 5 [_seconds_] is recommended.

Amazon's recommendation is to allow 60-300 seconds for object invalidations to complete. Should the instructions instead say that a value of 5 _minutes_ is recommended? In my experience that's a very long wait for even a full-site invalidation to occur, but — also in my experience — 5 _seconds_ would be far too short of a delay.

**Comment by bencroker** [comment]
This recommendation is actually based on my experience using Cloudflare. Since I don't use CloudFront, I'm not sure what a good recommendation would be, but 5 minutes sounds insane, even 60 seconds feels excessive. What does your experience say @markdrzy?

I believe @mattstein is using this setup on a site, perhaps he can chime in?

**Comment by markdrzy** [comment]
I agree that 5 minutes would be too long for a default setting. But I _have_ experienced invalidations in the 2-4 minute range, generally during larger invalidation batches (full-site cache refreshes). For now I'll probably just go with 120 seconds and see how that does.

Instead of relying on an arbitrary best guess for a warming delay, it would be more reliable to poll AWS for the invalidation state and trigger the warm after invalidation is finished. The [`createInvalidation`](https://docs.aws.amazon.com/cloudfront/latest/APIReference/API_CreateInvalidation.html) call returns an Invalidation ID, which can be used to check status through a [`getInvalidation`](https://docs.aws.amazon.com/cloudfront/latest/APIReference/API_GetInvalidation.html) call. Obviously that's a pretty significant change to the driver, so I don't present that as an actual request — I'm just thinking out loud.

**Comment by bencroker** [comment]
Let me know how it goes with your experimentation and I'll be happy to adjust the default based on your suggestions.

**Comment by mattstein** [comment]
I can’t offer much help, sorry! We ended up disabling automatic warming on a smallish site where that was ideal for content editors. My experience was that full-site invalidations via `*` were much quicker than any explicit list of URLs, for whatever that’s worth.
