### ISSUE TITLE
Cloudflare Purger not Clearing Cached Homepage that has a Language Segment but no Trailing Slash

### ISSUE THREAD

**Issue by subism-dev** [putyourlightson/craft-blitz#317]
### Describe the bug
We have a craft installation that has around 10 regional sites, each on it's own sub-domain.

Each Regional site has ~500 pages.

The site base urls have long been established, and are in the following representative format:
```https://{regional sub-domain}.{main-domain).{tld}/{lang}```

Some examples, could be:
```
https://www.mycoolsite.com/en
https://gbr.mycoolsite.com/en
https://chn.mycoolsite.com/en
https://chn.mycoolsite.com/zh-hant
```

Please notice that the site urls are defined without a trailing forward-slash.

We are using the Cloudflare Purger, and have the required Cloudflare rule configured to `Cache Everything`.

When we edit the homepage entry, and then save, we can see the Blitz "Clearing Cache" item in the Craft Tasks panel, and can see Blitz checking around ~5000 entries.

Unfortunately, the updates to the home entry never come through on the browser when visiting the home/base url without the training slash _(i.e. https://www.mycoolsite.com/en)_

However, the updates to the home entry *DO* come through on the browser when visiting the home/base url with the trailing slash _(i.e. https://www.mycoolsite.com/en/)_

Manually clearing the Cloudflare Cache does indeed pick up the changes to Blitz's Cahced version.

It's almost as if our home page url is not been reported to Cloudflare for purging, or at least not being reported without the trailing slash.

Additionally, we have tried both with the warmer enabled, and with the warmer disabled.

All our page requests for to check if the updated content had come through were made after waiting to allow the Blitz Tasks to fully complete, and then waiting at least a further 30 seconds.

### Versions
- Plugin version: 3.8.0
- Craft version: Craft CMS Pro 3.6.12

**Comment by bencroker** [comment]
Do your site base URLs correctly reflect the missing trailing slashes that you listed above? Also note that `en` and `en/` can be seen as unique pages, so a permanent redirect from one to the other should ideally be put in place.

**Comment by subism-dev** [comment]
@bencroker Thanks for the advice

We investigated further based on your response and turned up the following related Craft CMS issue: https://github.com/craftcms/cms/issues/5675

Upon adding 301 redirects from `en/` to `en` the home pages were being purged from CloudFlare correctly

**Comment by bencroker** [comment]
Glad to hear it!
