### ISSUE TITLE
Debugging cache clear errors.

### ISSUE THREAD

**Issue by pgrzyb** [putyourlightson/craft-blitz#318]
Hi there! I have searched through all the issues here, looking for something similar and I found nothing. That leads me to believe this is a problem with my template code and not Blitz specifically, but maybe you can help me out anyway. 

I have been getting these errors every time a cache clear is triggered when saving an entry that is displayed via an element query somewhere across the site. The user saves it, cache clear is triggered, and ends in this error:

![image](https://user-images.githubusercontent.com/1277309/117585929-86448880-b115-11eb-8652-25026b33f814.png)

I know what generally causes these types of errors (Array to string conversion) but I am having an insanely hard time debugging this. The only additional information I found was in the queue.log file in /storage, but with my limited Craft backend knowledge, that did not help me much - here it is: 

```log
2021-05-09 10:23:33 [-][2][-][error][craft\queue\QueueLogBehavior::afterError]  [32345] Refreshing Blitz cache (attempt: 1) - Error (time: 0.193s): Array to string conversion
2021-05-09 10:23:33 [-][2][-][error][yii\base\ErrorException:8] yii\base\ErrorException: Array to string conversion in /home/ubuntu/sites/dummy-craft/vendor/yiisoft/yii2/db/QueryBuilder.php:1462
Stack trace:
#0 /home/ubuntu/sites/dummy-craft/vendor/craftcms/cms/src/web/ErrorHandler.php(76): yii\base\ErrorHandler->handleError()
#1 /home/ubuntu/sites/dummy-craft/vendor/yiisoft/yii2/db/QueryBuilder.php(1462): craft\web\ErrorHandler->handleError()
#2 /home/ubuntu/sites/dummy-craft/vendor/yiisoft/yii2/db/QueryBuilder.php(1445): yii\db\QueryBuilder->hasLimit()
#3 /home/ubuntu/sites/dummy-craft/vendor/yiisoft/yii2/db/QueryBuilder.php(1408): yii\db\QueryBuilder->buildLimit()
#4 /home/ubuntu/sites/dummy-craft/vendor/yiisoft/yii2/db/QueryBuilder.php(241): yii\db\QueryBuilder->buildOrderByAndLimit()
#5 /home/ubuntu/sites/dummy-craft/vendor/yiisoft/yii2/db/QueryBuilder.php(1331): yii\db\QueryBuilder->build()
#6 /home/ubuntu/sites/dummy-craft/vendor/yiisoft/yii2/db/QueryBuilder.php(1283): yii\db\QueryBuilder->quoteTableNames()
#7 /home/ubuntu/sites/dummy-craft/vendor/yiisoft/yii2/db/QueryBuilder.php(233): yii\db\QueryBuilder->buildFrom()
#8 /home/ubuntu/sites/dummy-craft/vendor/yiisoft/yii2/db/Query.php(157): yii\db\QueryBuilder->build()
#9 /home/ubuntu/sites/dummy-craft/vendor/yiisoft/yii2/db/Query.php(318): yii\db\Query->createCommand()
#10 /home/ubuntu/sites/dummy-craft/vendor/craftcms/cms/src/db/Query.php(202): yii\db\Query->column()
#11 /home/ubuntu/sites/dummy-craft/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1532): craft\db\Query->column()
#12 /home/ubuntu/sites/dummy-craft/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1572): craft\elements\db\ElementQuery->column()
#13 /home/ubuntu/sites/dummy-craft/vendor/putyourlightson/craft-blitz/src/jobs/RefreshCacheJob.php(221): craft\elements\db\ElementQuery->ids()
#14 /home/ubuntu/sites/dummy-craft/vendor/putyourlightson/craft-blitz/src/jobs/RefreshCacheJob.php(96): putyourlightson\blitz\jobs\RefreshCacheJob->_getElementQueryCacheIds()
#15 /home/ubuntu/sites/dummy-craft/vendor/yiisoft/yii2-queue/src/Queue.php(246): putyourlightson\blitz\jobs\RefreshCacheJob->execute()
#16 /home/ubuntu/sites/dummy-craft/vendor/yiisoft/yii2-queue/src/cli/Queue.php(147): yii\queue\Queue->handleMessage()
#17 /home/ubuntu/sites/dummy-craft/vendor/craftcms/cms/src/queue/Queue.php(121): yii\queue\cli\Queue->handleMessage()
#18 /home/ubuntu/sites/dummy-craft/vendor/craftcms/cms/src/controllers/QueueController.php(84): craft\queue\Queue->run()
#19 [internal function]: craft\controllers\QueueController->actionRun()
#20 /home/ubuntu/sites/dummy-craft/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#21 /home/ubuntu/sites/dummy-craft/vendor/yiisoft/yii2/base/Controller.php(180): yii\base\InlineAction->runWithParams()
#22 /home/ubuntu/sites/dummy-craft/vendor/craftcms/cms/src/web/Controller.php(190): yii\base\Controller->runAction()
#23 /home/ubuntu/sites/dummy-craft/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction()
#24 /home/ubuntu/sites/dummy-craft/vendor/craftcms/cms/src/web/Application.php(274): yii\base\Module->runAction()
#25 /home/ubuntu/sites/dummy-craft/vendor/craftcms/cms/src/web/Application.php(577): craft\web\Application->runAction()
#26 /home/ubuntu/sites/dummy-craft/vendor/craftcms/cms/src/web/Application.php(253): craft\web\Application->_processActionRequest()
#27 /home/ubuntu/sites/dummy-craft/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest()
#28 /home/ubuntu/sites/dummy-craft/web/index.php(21): yii\base\Application->run()
#29 {main}
```

I get no information regarding the template file that is to blame here if that's one of my templates at all. 

I would very much appreciate anything that could at least point me in the right direction while looking for a solution here.

Thanks in advance <3

**Comment by bencroker** [comment]
What versions of Blitz and Craft are you running? And are you using any [page specific caching options](https://putyourlightson.com/plugins/blitz#page-specific-options) in your twig templates?

**Comment by pgrzyb** [comment]
Thanks for the lightning-fast reply!

I am using the page specific options only one one entry type to disable caching on it completely, but that type is not affected by the cache clear in any way (its a simple text page hidden behind a password that is checked from a POST param inside of the twig template, and because of that it can't be cached). 

// EDIT: What I mean by that it's not affected is that it does not get cleared when saving the entry that causes the error. No relations whatsoever.

Craft: 3.5.18
Blitz: 3.7.0

**Comment by bencroker** [comment]
Are you able to update to the latest version of Blitz, currently 3.9.0, to eliminate any issues that have already been addressed?

**Comment by pgrzyb** [comment]
Updating did stop the error from showing up, but it introduced a slightly different issue - the cache clear task gets stuck at around 85% every time. Not on every entry though, which again tells me that it's something in my code - is there a detailed log of what is being done on each of the steps Blitz takes that I could take a look at to narrow it down?

![image](https://user-images.githubusercontent.com/1277309/117613919-df3d0c80-b167-11eb-8cc1-6c336874a9c5.png)
![image](https://user-images.githubusercontent.com/1277309/117613991-f7149080-b167-11eb-9b48-3c8839d75d16.png)

After a while the task gets removed and switched to "Pending" and then restarts itself, getting stuck around 85% again. 

// EDIT: I stand corrected - they don't switch to Pending, or at least not always. They just sit there stuck:

![image](https://user-images.githubusercontent.com/1277309/117616166-0ea14880-b16b-11eb-96db-ee1d4c7e2391.png)

**Comment by pgrzyb** [comment]
Okay, after some more cleanup (cleared all possible caches and re-warmed everything, along with some code tuning) and updates (bumped Craft and all my other plugins to their latest versions), everything seems to work just fine. I would still love to know, if there are ways to debug these kinds of issues with more detail, for future reference :) 

Thanks for the pointers @bencroker!

**Comment by bencroker** [comment]
Glad to hear it!

The [debug config setting](https://putyourlightson.com/plugins/blitz#debugging) can be enabled to help troubleshoot why pages are not being cached. Whether it would have helped in your specific issue, I'm not sure.

**Comment by mildlygeeky** [comment]
Going to jump in - I've been having the same issues, for quite some time.

Ended up digging in deeper, and have been able to (somewhat) figure out where thing are going funny, but I still don't know how to truly diagnose/fix.

It seems that Yii's QueryBuilder->hasLimit() function is being passed an array when it comes to Blitz's `elementqueries` table - here's an example row from `blitz_elementqueries`:

| id | index      | type                 | params                                                                                             |
|----|------------|----------------------|----------------------------------------------------------------------------------------------------|
| 4  | 1884933305 | craft\elements\Entry | {"siteId":4,"relatedTo":["136769"],"limit":{"label":"5","value":"5","selected":true,"valid":true}} |

And here is the stack trace:

```
#0 /app/vendor/yiisoft/yii2/db/mysql/QueryBuilder.php(219): yii\\db\\mysql\\QueryBuilder->hasLimit(Array)
#1 /app/vendor/yiisoft/yii2/db/QueryBuilder.php(1408): yii\\db\\mysql\\QueryBuilder->buildLimit(Array, NULL)
#2 /app/vendor/yiisoft/yii2/db/QueryBuilder.php(241): yii\\db\\QueryBuilder->buildOrderByAndLimit('SELECT `element...', 'ORDER BY `struc...', Array, NULL)
#3 /app/vendor/yiisoft/yii2/db/QueryBuilder.php(1331): yii\\db\\QueryBuilder->build(Object(craft\\db\\Query), Array)
#4 /app/vendor/yiisoft/yii2/db/QueryBuilder.php(1283): yii\\db\\QueryBuilder->quoteTableNames(Array, Array)
#5 /app/vendor/yiisoft/yii2/db/QueryBuilder.php(233): yii\\db\\QueryBuilder->buildFrom(Array, Array)
#6 /app/vendor/yiisoft/yii2/db/Query.php(157): yii\\db\\QueryBuilder->build(Object(craft\\db\\Query))
#7 /app/vendor/yiisoft/yii2/db/Query.php(320): yii\\db\\Query->createCommand(Object(craft\\db\\Connection))
#8 /app/vendor/craftcms/cms/src/db/Query.php(201): yii\\db\\Query->column(NULL)
#9 /app/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1634): craft\\db\\Query->column(NULL)
#10 /app/vendor/craftcms/cms/src/elements/db/ElementQuery.php(1674): craft\\elements\\db\\ElementQuery->column(NULL)
#11 /app/vendor/putyourlightson/craft-blitz/src/jobs/RefreshCacheJob.php(243): craft\\elements\\db\\ElementQuery->ids()
#12 /app/vendor/putyourlightson/craft-blitz/src/jobs/RefreshCacheJob.php(117): putyourlightson\\blitz\\jobs\\RefreshCacheJob->_getElementQueryCacheIds(Object(putyourlightson\\blitz\\records\\ElementQueryRecord), Array, Array)
#13 /app/vendor/yiisoft/yii2-queue/src/Queue.php(246): putyourlightson\\blitz\\jobs\\RefreshCacheJob->execute(Object(craft\\queue\\Queue))
#14 /app/vendor/yiisoft/yii2-queue/src/cli/Queue.php(162): yii\\queue\\Queue->handleMessage('1437797', 'O:42:\"putyourli...', '300', '1')
#15 /app/vendor/yiisoft/yii2-queue/src/cli/Command.php(146): yii\\queue\\cli\\Queue->execute('1437797', 'O:42:\"putyourli...', '300', '1', '1')
#16 [internal function]: yii\\queue\\cli\\Command->actionExec('1437797', '300', '1', '1')
#17 /app/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#18 /app/vendor/yiisoft/yii2/base/Controller.php(181): yii\\base\\InlineAction->runWithParams(Array)
#19 /app/vendor/yiisoft/yii2/console/Controller.php(184): yii\\base\\Controller->runAction('exec', Array)
#20 /app/vendor/yiisoft/yii2/base/Module.php(534): yii\\console\\Controller->runAction('exec', Array)
#21 /app/vendor/yiisoft/yii2/console/Application.php(181): yii\\base\\Module->runAction('queue/exec', Array)
#22 /app/vendor/craftcms/cms/src/console/Application.php(89): yii\\console\\Application->runAction('queue/exec', Array)
#23 /app/vendor/yiisoft/yii2/console/Application.php(148): craft\\console\\Application->runAction('queue/exec', Array)
#24 /app/vendor/yiisoft/yii2/base/Application.php(392): yii\\console\\Application->handleRequest(Object(craft\\console\\Request))
#25 /app/craft(22): yii\\base\\Application->run()
#26 {main}
```

I'm going to assume I can flush out the `blitz_elementqueries` table without consequences? This is the one and only row in that table like this (i.e., with a malformed `limit` query param), and because it has such a low `id`, I'm wondering if there was just something funny in a really old version that has been hanging around and causing these errors?

**Comment by bencroker** [comment]
@mildlygeeky You can flush the entire table, but I'd recommend you do so along with clearing/refreshing the cache, so that the element queries are regenerated the next time pages are cached. I haven't seen this kind of issue before, but as you point out, it may be from an old version of Blitz, or even an old version of another third-party plugin that incorrectly created an element query.
