### ISSUE TITLE
Add Pagination option to craft.blitz.options

### ISSUE THREAD

**Issue by bymayo** [putyourlightson/craft-blitz#319]
Currently paginated pages don't warm like other pages and there's no way of doing this. There is a proposed solution https://github.com/putyourlightson/craft-blitz/issues/108 but this doesn't work very well. Paginated pages only seem to warm AFTER they have been noticed by Blitz, which means most paginated pages on first view without clearing the cache have all the same content.

It would be good to add a pagination option to `craft.blitz.options`:

```
{% do craft.blitz.options({
    cachingEnabled: true,
    pagination: [1, 4]
}) %}
```

This way it can be placed on the paginated pages and Blitz will know how many paginated pages for that template/route it needs to warm.

This can be made dynamic by doing:

```
{% do craft.blitz.options({
    cachingEnabled: true,
    pagination: [1, pagination.totalPages]
}) %}
```

So endless pagination pages don't get warmed.

**Comment by bencroker** [comment]
This is a WIP (see https://github.com/putyourlightson/craft-blitz/commit/8f8f5105387e1fda099742d51085156876d2dfda and https://github.com/putyourlightson/craft-blitz/commit/0b3aa2f8f3fc146d2bbcb2c3aeb1d31db13ea874). The syntax is as follows.

```twig
{% paginate entryQuery as pageInfo, pageEntries %}

{% do craft.blitz.options.paginate(pageInfo.totalPages) %}
```

One caveat is that this page will marked for pagination of `pageInfo.totalPages` pages only when the page is cached. So warming the cache will be necessary after this page has already been cached.

**Comment by bymayo** [comment]
Nice! That will work. Thanks for adding this in, will give it a try.

**Comment by bencroker** [comment]
Released in 3.10.0.

**Comment by leevigraham** [comment]
@bencroker To confirm this functionality, pagination is only about warming? To auto clear the cache we either use `trackElementQueries` or tag with `sectionId`

**Comment by bencroker** [comment]
@leevigraham pagination is used during cache generation (warming is no longer a concept since Blitz 4). This is an old issue.

**Comment by leevigraham** [comment]
@bencroker 

> warming is no longer a concept since Blitz 4

Understood. My point was related to the behaviour. If you're not using cache generation then there's no need to set pagination options.

**Comment by bencroker** [comment]
Yeah, that’s correct.
