### ISSUE TITLE
Undefined index: host

### ISSUE THREAD

**Issue by iammoen** [putyourlightson/craft-blitz#32]
Hey there! Love the plugin. Thanks for working on it. We upgraded this morning and now our site is throwing an error: 

2018-11-02 15:13:12 [-][-][8186168de2bceafcf2a98271e06d6bac][error][yii\base\ErrorException:8] yii\base\ErrorException: Undefined index: host in /srv/app/xxxxxx/htdocs/vendor/putyourlightson/craft-blitz/src/services/CacheService.php:172

When I dive into that file it looks like this:

```php
$parsedSiteUrl = parse_url(Craft::getAlias($site->baseUrl));
 $siteHostPath = trim($parsedSiteUrl['host'].$parsedSiteUrl['path'], '/');
```
Here in the [code](https://github.com/putyourlightson/craft-blitz/blob/v1/src/services/CacheService.php#L171)

It looks like the the parse_url only outputs a ["path"] key in our case, no host.

**Comment by putyourlightson** [comment]
Thanks for reporting this, fixed in 1.6.2 https://github.com/putyourlightson/craft-blitz/commit/233387d67b41a89846be195944eb1f0b609d3915
