### ISSUE TITLE
blitz/cache/refresh-expired --queue=1 does not find expired entries

### ISSUE THREAD

**Issue by leevigraham** [putyourlightson/craft-blitz#320]
### Describe the bug

This [line](https://github.com/putyourlightson/craft-blitz/blob/develop/src/services/RefreshCacheService.php#L559) in `src/services/RefreshCacheService.php`: `$element = $elementType::find()->id($elementId)->site('*')->one();` doesn't take into account an Entries status.

This results in the expired entry not being returned in the query so it is not refreshed.

### To reproduce

Steps to reproduce the behaviour:

1. create an entry with a future expire date
2. visit the url and ensure the url is cached
3. wait until the expiry date has passed
4. run `bin/craft blitz/cache/refresh-expired --queue=1`
5. run queue

Breakpoint should kick in and the results `$element` should be null.

### Expected behaviour

`$element` is no null

### Screenshots

Entry expires:

![image](https://user-images.githubusercontent.com/25124/117916596-d6e0ff00-b32a-11eb-8c24-eebf6e17ba71.png)

Entry  Cached by Blitz on 2021-05-12T14:01:58+10:00:

![image](https://user-images.githubusercontent.com/25124/117916556-bdd84e00-b32a-11eb-8d6b-b7edb2dbd3e3.png)

Entry Expired:

![image](https://user-images.githubusercontent.com/25124/117916686-f2e4a080-b32a-11eb-85a0-555d0a95037b.png)

`$element` is null when running `bin/craft blitz/cache/refresh-expired --queue=1`:

![image](https://user-images.githubusercontent.com/25124/117916808-3212f180-b32b-11eb-97d8-8f780e7addb2.png)

Evaluating the query with `->status(null)` returns the element:

![image](https://user-images.githubusercontent.com/25124/117916897-64bcea00-b32b-11eb-9056-8768266b1182.png)

### Versions

- Plugin version: 3.9.0
- Craft version: 3.6.14

**Comment by leevigraham** [comment]
Related PR: https://github.com/putyourlightson/craft-blitz/pull/321

**Comment by bencroker** [comment]
Merged, thanks!

**Comment by leevigraham** [comment]
Coolio… did the issue description make sense?

**Comment by bencroker** [comment]
It sure did.

**Comment by bencroker** [comment]
Released in 3.10.0.
