### ISSUE TITLE
Break out of blitz-caching mid template for session variables

### ISSUE THREAD

**Issue by joepagan** [putyourlightson/craft-blitz#323]
### Question

Not sure if I'm not doing something right, or, this feature doesn't exist yet, but from your docs I see:

>Because Blitz caches elements and element queries in the same order that twig templates are parsed, you can change the options at various places in your templates.

I would like to just break out of blitz caching for a small part:

```twig
{# Disable page options #}
{% do craft.blitz.options.cachingEnabled(false) %}

{% include '_components/c-flash' with {
      type: 'error',
      icon: 'warning',
      message: craft.app.session.getFlash('error')
  } %}

{# Re-enable page options #}
{% do craft.blitz.options.cachingEnabled(true) %}
```

I presume this is not possible and would need to fetch the session data from some uncached location but just wanted to check, maybe the suggestion in the docs only works with elements and not `cachingEnabled`? 

Let me know, thanks

**Comment by bencroker** [comment]
Correct, this is not possible – Blitz does _not_ provide partial page caching. 
For this you can use the [dynamic content](https://putyourlightson.com/plugins/blitz#dynamic-content) feature or something like [Sprig](https://putyourlightson.com/plugins/sprig).

**Comment by joepagan** [comment]
Hey Ben, thanks for getting back, your docs seem to contradict that though with the quoted part I referenced, to confirm does that only work just for craft elements?

**Comment by bencroker** [comment]
> Because Blitz caches elements and element queries in the same order that twig templates are parsed, you can change the options at various places in your templates.

The above implies that you can change the options for caching _elements_ and _element queries_, which are different from caching the page, which is what you are referring to, but I've made a note at https://putyourlightson.com/plugins/blitz#cachingenabled to clarify.

**Comment by damienbuckley** [comment]
Sorry to reopen this but I'm not fully understanding it either. So, say if I add the two tags as above, the *whole page* should not be cached. Is that correct?

I've done this for a matrix block which contains a subscribe form but the page is still being cached…

**Comment by bencroker** [comment]
Only the following will prevent the page from being cached.

```twig
{# Disables caching of the page #}
{% do craft.blitz.options.cachingEnabled(false) %}
```
