### ISSUE TITLE
Suggestion on caching dev environment with irregular port number

### ISSUE THREAD

**Issue by joepagan** [putyourlightson/craft-blitz#324]
### Question

I'm looking for a suggestion on how best to run blitz and test caching on a dev environment. 
It seems like blitz uses the hostname set by the base url, however, we tend to set the base url to use a browserstack/webpack port like 3000 (`dev.domain.com:3000`). It seems like blitz does not cache pages when using this base url with a consolecommand, or, visting the page directly.
(I am unsure if visiting a page directly would warm the cache, I presume it would?).

Changing the base url to `dev.domain.com` the page does get cached! Though in this scenario I would have to run a production build of our bundler which isn't very productive.

In my example scenario I a request goes through like this:
dev.domain.com:3000 (browserstack) -> dev.domain.com:4040 (webpack dev server) -> dev.domain.com:80 (nginx)
When base url is using port `3000`, with blitz `debug: true`, it appears the requests seemingly get through to port `4040` and fails there, but, it is clearly doing _something_:

```
2021-05-19 18:36:29 [][][debug] No site URI could be determined from the requested URL – ensure that the base site URL is correctly set. [http://dev.domain.com:4040/]
2021-05-19 18:36:49 [][][debug] Page not cached because a query string was provided with the query string caching setting disabled. [http://dev.domain.com:4040/feed/freeform?form=contact]
```
I suspect what blitz is doing is maybe not accounting for a port in the base url, though wondered what could be done here?

Of course I appreciate this blitz is not really intended to be used on a dev environment but there are a few too many manual changes to a setup to ensure it's working it seems.
That being said, I do work on some sites with 20s fttb responses! And with blitz reducing that down to 3s it may make some scenarios way more bearable!

**Comment by bencroker** [comment]
As you correctly pointed out, Blitz is seeing the URL as `http://dev.domain.com:4040/` (as is Craft). If you change your site's base URL to `http://dev.domain.com:4040/` then Blitz should be able to match it with the included site URI patterns and begin caching pages.
