### ISSUE TITLE
LocalWarmer does not keep track of cache elements

### ISSUE THREAD

**Issue by nickdunn** [putyourlightson/craft-blitz#325]
### Describe the bug
When using the LocalWarmer I am finding sporadically that it's returning my cached homepage for all requests.

### To reproduce
Steps to reproduce the behaviour:
1. Enable the LocalWarmer
2. Warm the cache
3. Browse to a site page and see the homepage returned

I know the LocalWarmer is experimental but I figured if I'm getting this then others might be.

I'm running in Docker with Async Queue so debugging this is tricky as I don't have logs coming out of my queue at the moment.

One hunch is it's caused by a local ca certs issue with my employer's locked down machines. I get this when I try to make cURL requests and usually have to disable SSL verification. I wasn't able to get the GuzzleWarmer running locally, not even with a guzzle.php config with `'verify' => false` so this could be a root cause.

I'll keep trying to debug... but I wonder if there's maybe a network error condition Blitz isn't catering for which is causing it to either request and store the incorrect string, or retrieve the incorrect string?

### Versions
- Plugin version: 3.9.0
- Craft version: 3.6.15

**Comment by nickdunn** [comment]
Ah just dug into LocalWarmer and it's not doing any HTTP requests at all, so my hunch about ca certs being out of whack locally is probably barking up entirely the wrong tree.

**Comment by nickdunn** [comment]
Definitely some oddness going on. It has nothing to do with the certs/request issue as it's a local warmer.

If I dump out the querystring params on the page (`{{dump(craft.app.request.getQueryParams())}}`) I can verify that these are correct for each warmed page — the `p` param is showing the correct value. But they all show my homepage content. Which suggests Craft isn't selecting the correct entry for the page?

**Comment by nickdunn** [comment]
If I dump {{ entry.id }} in my layout file I get the same ID, the homepage ID (`7`), across all pages even though the path (`p`) is correct. So somewhere Craft isn't loading the correct entry.

Homepage:
<img width="194" alt="Screenshot 2021-05-22 at 09 02 11" src="https://user-images.githubusercontent.com/39560/119219239-71d09a80-badc-11eb-922f-5cc018224964.png">

Another page:
<img width="320" alt="Screenshot 2021-05-22 at 09 02 04" src="https://user-images.githubusercontent.com/39560/119219241-785f1200-badc-11eb-86af-916cce71b71d.png">

**Comment by bencroker** [comment]
Firstly, as you correctly noted, the local warmer is still not fully stable, so use the Guzzle warmer wherever possible. 

Does your setup have [omitScriptNameInUrls](https://craftcms.com/docs/3.x/config/config-settings.html#omitscriptnameinurls) enabled and are your page URLs correctly rendered (`site.com/my-page` rather than `site.com/?p=my-page`)?

**Comment by nickdunn** [comment]
Yes to both of your questions.

Working through this some more I don’t think it’s actually a bug with LocalWarmer at all. When I log the response body the local warmer is generating it’s correct.

I think the issue is somewhere with stale responses being served and not being purged properly.

I’m using this setup with .htaccess adding an extra querystring parameter to each request (https://github.com/putyourlightson/craft-blitz/issues/302#issuecomment-815310116) which I think may be interfering.

I’ve got more debugging to do but it feels like maybe the cache doesn’t get properly cleared for these pages sometimes. I haven’t worked out why it’s the homepage cache that seems to get returned, nor how I end up with the homepage cache being returned but with the correct page path in it (which I dump the path out). 

I don’t know if it makes any difference but I’m using the Yii default cache store which on my setup is Redis.

**Comment by bencroker** [comment]
When troubleshooting it's often best to disable non-default configurations one at a time until you discover which one is tripping things up. Good luck!

**Comment by nickdunn** [comment]
I think the issue is in clearing the cache. With my .htaccess rule in place, Blitz is correctly building up cached versions of pages with unique querystrings:

<img width="276" alt="Screenshot 2021-05-26 at 10 00 04" src="https://user-images.githubusercontent.com/39560/119633146-5a115300-be09-11eb-90be-e512e6a771ff.png">

* The root version generated by the warmer, which has cookie so no extra `websiteAudienceType` querystring
* Two extra versions for each unique querystring from me browsing the site

When I re-save a page and have `clearCacheAutomatically` and `warmCacheAutomatically` enabled, the bottom `index.html` is deleted and re-generated, but the others are not deleted. I expected all of the files to be removed since they are cached versions of the same page.

Could this be a bug with the cache purger when `queryStringCaching` is set to `1`?

**Comment by nickdunn** [comment]
If I manually hit my page with some custom querystrings e.g. `?test=zombies` then I see the cache file created correctly _and_ I see it being purged, but only sometimes.

**Comment by nickdunn** [comment]
Ok, some steps to recreate:

Using:
* clearCacheAutomatically true
* warmCacheAutomatically true
* queryStringCaching 1
* cacheWarmerType LocalWarmer
* cacheStorageType FileStorage
* no htaccess customisations, just straight out of box

1. Start with an empty cache
2. Visit an entry and see its index.html created on disk
3. Append `?zombies=run` querystring and reload to see this file also created on disk
4. Edit the entry and re-save
5. See both index.html files have updated with new content
6. Edit the entry and re-save again
7. See that only the root index.html for the page has updated, and the `zombies=run` file was not purged

I am only seeing this behaviour with the warmer enabled. When the warmer is DummyWarmer then the files are deleted correctly.

**Comment by nickdunn** [comment]
* Should Blitz be purging all versions of the page including those with querystrings?
* Does Blitz do any magic to re-warm previously cached _querystring_ versions of pages? It feels like it does do this from the steps above... and this is an incredible feature! But I can also think of scenarios where I'd want to disable this e.g. a malicious bot caches a million versions of every URL which then causes my warmer to issue a million requests?

**Comment by nickdunn** [comment]
Digging a bit more, I can see references in the `blitz_caches` table to all of the URLs that contain querystrings. Only the row for my URI that _doesn't_ contain the querystrings is deleted when re-saving the entry. I was expecting all versions of this URI to be deleted.

**Comment by bencroker** [comment]
> Start with an empty cache
Visit an entry and see its index.html created on disk
Append ?zombies=run querystring and reload to see this file also created on disk
Edit the entry and re-save
See both index.html files have updated with new content
Edit the entry and re-save again
See that only the root index.html for the page has updated, and the zombies=run file was not purged

Considering that this only happens when you "re-save again" and "sometimes", my guess would be that perhaps you are not actually changing any content in the entry the second time around, so clearing does not take place because the [refreshCacheWhenElementSavedUnchanged](https://github.com/putyourlightson/craft-blitz/blob/0b3aa2f8f3fc146d2bbcb2c3aeb1d31db13ea874/src/config.php#L133-L134) config setting is set to `false` by default. Can you double check this?

**Comment by nickdunn** [comment]
Thanks Ben. I’ve already been setting this to true during testing to make sure this wasn’t the cause.

**Comment by nickdunn** [comment]
Can you confirm that when an entry is re-saved, the cache for all querystring versions of the page should be deleted?

**Comment by bencroker** [comment]
They should be, yes. Check the `blitz_caches` and `blitz_elementcaches` tables to ensure that they are linked for the page URLs with query strings.

**Comment by nickdunn** [comment]
`blitz_caches` is populated, but `blitz_elementcaches` is empty...

<img width="134" alt="Screenshot 2021-05-26 at 21 49 10" src="https://user-images.githubusercontent.com/39560/119730027-308a1300-be6d-11eb-92f1-ffa061648298.png">

<img width="465" alt="Screenshot 2021-05-26 at 21 49 05" src="https://user-images.githubusercontent.com/39560/119730028-3122a980-be6d-11eb-9476-9c96ab8cb6b6.png">

**Comment by nickdunn** [comment]
The `blitz_elementcaches ` table is correctly populated when I hit an uncached URL for the first time, but it's not populated when the pages are first warmed by the LocalWarmer. If the cache never expires, and the cache isn't generated via a frontend request, then perhaps these rows are never created correctly?

When I hit a frontend page I see `EVENT_AFTER_POPULATE_ELEMENT` callbacks firing which adds the element to the cache generator. I don't see this running when the LocalWarmer warms a page.

**Comment by nickdunn** [comment]
Yeah I think this is likely where the issue lies — I can see all of the event registration callbacks in `_registerCacheableRequestEvents` firing when I hit a URL directly on the frontend, which presumably would also fire when using the GuzzleWarmer like any other request. However when the LocalWarmer renders a page these callbacks aren't firing so `$this->generateCache->addElement($event->element);` isn't populating.

Apologies for the sprawling and changing direction of this thread! I'm debugging this over a number of days when I can find time and I'm deeper than I thought I'd be :-)

**Comment by bencroker** [comment]
I've been testing this locally and am also seeing some unusual results. To be perfectly honest, the local warmer is intended purely for static sites (in which there is no front-end to hit) and, as noted, is still considered experimental. Is there a reason you cannot use the recommended (and stable) Guzzle warmer?

**Comment by nickdunn** [comment]
I spotted a comment that suggested the local warmer might be the default in the future so I'm happy to help digging deeper if it'll help — but I totally understand that it's experimental and shouldn't be relied on.

We struggled with the Guzzle warmer for a couple of reasons: on my local setup I'm using Docker on a fairly locked down corporate-controlled laptop that is throwing up CA cert issues when calling out to external URLs, and I haven't figured out DNS to allow an app in Docker to call itself. Once pushed to dev/qa/uat environments these are either behind IP restrictions or on-premise infrastructure so have access issues. Hence I was hoping local warmer would help me get around these :-)

**Comment by bencroker** [comment]
> I spotted a comment that suggested the local warmer might be the default in the future so I'm happy to help digging deeper if it'll help — but I totally understand that it's experimental and shouldn't be relied on.

Yes, possibly once Craft 4 is released, but not for the meantime.

> We struggled with the Guzzle warmer for a couple of reasons: on my local setup I'm using Docker on a fairly locked down corporate-controlled laptop that is throwing up CA cert issues when calling out to external URLs, and I haven't figured out DNS to allow an app in Docker to call itself. 

With Docker you often need to specify a port number which can be a pain for testing Blitz, so better to test on a staging server.

> Once pushed to dev/qa/uat environments these are either behind IP restrictions or on-premise infrastructure so have access issues.

Since the web server initiates the requests through Guzzle (which I believe uses cURL under the hood), you should be able to figure out its IP address and add it to an allow list.

**Comment by nickdunn** [comment]
Thanks for the pointers. I'll invest a bit of time getting this working so we can use the Guzzle warmer. Thanks for your patience.

**Comment by bencroker** [comment]
Sure thing and let me know if I can help in any way.

**Comment by nickdunn** [comment]
Is it worth keeping this open, or will there be more changes with Craft 4 that make this redundant?

**Comment by bencroker** [comment]
This will be refactored for Blitz 4 and is on my radar, thanks!
