### ISSUE TITLE
Opt-out of warming all querystring versions of a page

### ISSUE THREAD

**Issue by nickdunn** [putyourlightson/craft-blitz#326]
### Is your feature request related to a problem? Please describe.

When using `queryStringCaching` value `1` (Cache URLs with query strings as unique pages) for legitimate use cases, such as caching a paginated set of entries _and_ using a cache warmer, Blitz will attempt to re-warm all tracked versions of the page when an entry is resaved. If you have 10,000 pages of results, then re-saving an entry will warm 10,000 URLs.

This itself is great because it can keep the site extremely fast all the time... but it is a DDOS vector. A malicious user could simply append any number of random querystrings to all pages thereby causing a warmer to issue potentially millions of requests.

### Describe the solution you would like
Ideally an configuration option to opt-out of re-warming querystring versions of pages so that the warmer only requests the canonical version of the page. The cache should still be cleared for the other versions so the next request is a miss and they are re-generated, but Blitz should not attempt to warm them all.

For example, assume we have:

* `/mypage`
* `/mypage?param=1`
* `/mypage?param=2`
* `/mypage?param=3`

When opting out of re-warming URLs with querystrings, when the `mypage` entry is saved, the cache would be cleared for all 4 URIs, but only the first would be warmed again.

### Describe alternatives you have considered
An option might be to provide an `includedQueryStringParams` in addition to `excludedQueryStringParams` so that developers can provide an allow list. However this only reduces the vector slightly since a malicious user would need to use one of the allowed querystring names, which would be easy to do.

**Comment by bencroker** [comment]
You can already use `excludedQueryStringParams` with regular expressions to specify which query strings to allow. See my comment at https://github.com/putyourlightson/craft-blitz/issues/272#issuecomment-786515983

But I think that your feature request is still valid and will consider it for the next release.

**Comment by bencroker** [comment]
Added the `includedQueryStringParams` config setting in https://github.com/putyourlightson/craft-blitz/commit/3eee542d2d12fb13dfbf0e444c87f045eda908cc for the next release.

**Comment by nickdunn** [comment]
Thanks for turning this around so quickly Ben!

However I’m not sure it solves the original issue of cache warming. This new config option gives more flexibility in saying which querystring params will be accepted or ignored, but a malicious attacker could still pump a massive number of values into the accepted params and trigger an equally massive stampede of cache warming requests. We’d still like the pages to be cached on the frontend, just not warmed again when once the cache is deleted.

**Comment by bencroker** [comment]
So are you proposing a config setting for disabling warming the cache for all pages that contain query string params?

**Comment by nickdunn** [comment]
Yep exactly that.

> Ideally an configuration option to opt-out of re-warming querystring versions of pages so that the warmer only requests the canonical version of the page.

**Comment by nickdunn** [comment]
I'd even go as far as to suggest this behaviour should be the _default_ if the config is set to cache querystrings as unique pages in order to protect from the potential vulnerability.

**Comment by bencroker** [comment]
Added the `warmPagesWithQueryStringParams` config setting in https://github.com/putyourlightson/craft-blitz/commit/5ed27ca5d0faa81889d1dccd18d59fd4fbd06ece for the next release.

**Comment by bencroker** [comment]
Released in 3.10.0.
