### ISSUE TITLE
Cloudflare, page rules & blitz

### ISSUE THREAD

**Issue by joepagan** [putyourlightson/craft-blitz#327]
### Is your feature request related to a problem? Please describe.
Forgive me if I am missing something though it doesn't appear that your docs (or the field description on the `reverse proxy purging` tab of the plugin) list all the necessary steps for setting up cloudflare correctly.

### Describe the solution you would like
Highlight the need for setting extra rules in your docs or the plugin settings pages for bypassing caching for the `admin/*` and `actions/*` URLs, maybe mention something on the order also.

### Describe alternatives you have considered
n/a

### Additional context
Just hit a CSRF error because `/actions/blitz/csrf/input` was serving cached content

**Comment by bencroker** [comment]
It shouldn't be necessary to manually exclude `admin/*` and `actions/*` from being cached as the `cache-control` header contains `no-cache` on those pages, telling Cloudflare not to cache them. Can you double check whether the CP is really being cached for you?

**Comment by joepagan** [comment]
Hey Ben, thanks for getting back, 

**RE admin:** 
I personally didn't experience issues with the admin area though I read [a cloudflare article](https://support.cloudflare.com/hc/en-us/articles/200169526-Disabling-Cloudflare-features-on-admin-pages-for-content-management-systems-like-WordPress) which suggested it was necessary. Sorry I wasn't aware this was already handled, I just presumed it needed to be as I don't think I saw it referenced in your docs.

**RE actions:**
Specifically looking at the `/actions/blitz/csrf/input` endpoint.

When the actions bypass cache rule is enabled in cloudflare I get a response header of: `cache-control | no-store, no-cache, must-revalidate`

When the actions bypass cache rule is disabled, eventually it is cached with response headers:
```
HTTP/2 200 OK
date: Tue, 01 Jun 2021 08:20:38 GMT
content-type: text/html; charset=UTF-8
vary: Accept-Encoding
cf-cache-status: HIT
age: 21
cf-request-id: 0a6842269f0000f43be89e8000000001
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
report-to: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v2?s=mavqy4MOuMDUImQkyUZRvRHobpvlU5rv1aIVlKyVpVXOYWF1z0hdQCkk6BGq47CSynviZkmyCKxO3x%2B%2BF1LlDCEyXo2UuuIk7s%2FidtGpq49MVKgGdJZYgNGBFcrByrE%3D"}],"group":"cf-nel","max_age":604800}
nel: {"report_to":"cf-nel","max_age":604800}
server: cloudflare
cf-ray: 6587061dcba3f43b-LHR
content-encoding: gzip
alt-svc: h3-27=":443"; ma=86400, h3-28=":443"; ma=86400, h3-29=":443"; ma=86400
X-Firefox-Spdy: h2
```

Just incase this was some weird caching issue from potentially before blitz was enabled with cloudflare, I have clicked the "Purge everything" button in cloudflare's cache area after disabling the rule (as you suggested) and I get the `cf-cache-status: HIT` headers posted above.

**Comment by bencroker** [comment]
The response from Blitz should contain `cache-control: no-store, no-cache, must-revalidate`, which will tell Cloudflare not to cache the page. I would suggest refreshing the entire cache and retesting, as this has never been an issue in the past.

**Comment by joepagan** [comment]
I do get the header `cache-control: no-store, no-cache, must-revalidate` when the `/actions/* Cache Level: Bypass` rule in cloudflare is enabled.

I just tried:

- Clear cache button in craft backend
- Flush cache button in craft backend
- Purge cache button in craft backend
- Disabled the `/actions/* Cache Level: Bypass` rule in cloudflare

Eventually I get a cached result with a `cf-cache-status: HIT` header on the `/actions/blitz/csrf/input` endpoint.

**Comment by bencroker** [comment]
Are you perhaps using server rewrites? If that is the case then it could be that the server is not sending the correct `cache-control` header in the response.

**Comment by joepagan** [comment]
We are using `YiiCacheStorage` and server rewrites is only suitable for the blitz file storage setting right?

However, I have set the blitz setting to `Cache URLs with query strings as unique pages`

**Comment by bencroker** [comment]
What version of Blitz and Craft are you running?

**Comment by bencroker** [comment]
What version of Blitz and Craft are you running?

**Comment by joepagan** [comment]
Craft 3.6.6
Blitz 3.7.0

**Comment by bencroker** [comment]
Can you send the URL to the site to info@putyourlightson.com and I'll take a look?

**Comment by bencroker** [comment]
On second thought, can you update to Blitz 3.9.0 first and see if that makes any difference?

**Comment by joepagan** [comment]
Yes of course, will report back when I get an opportunity.

**Comment by bencroker** [comment]
Any update on this before I close it out?

**Comment by joepagan** [comment]
Sorry my schedule has not allowed me to jump back on this since your last suggestion, I'll close it and reopen when I next get an opportunity to update and test it's still an issue
