### ISSUE TITLE
Local version of site has Blitz disabled in config file, but cache is constantly warming

### ISSUE THREAD

**Issue by chadcrowell** [putyourlightson/craft-blitz#328]
### Describe the bug
Local version of site has Blitz disabled in config file, but cache is occasionally warming. On my local machine my config file says 
```
 // Local environment settings
    'local' => [
        'debug' => false,
        'cachingEnabled' => false,
    ],
```
(yes, I use `local` for my local environment instead of `dev` and my .env file is set to `local`. Any idea why this may be?

### Versions
- Plugin version: 3.9.0
- Craft version: 3.6.15

**Comment by bencroker** [comment]
Setting `cachingEnabled` to `false` prevents any _new_ pages from being cached. Pages already cached may continue to be warmed. To disable the plugin in `local`, use the [disabledPlugins](https://craftcms.com/docs/3.x/config/config-settings.html#disabledplugins) general config setting.

**Comment by chadcrowell** [comment]
That seems like a good option, however, it doesn't work in this case. Since I use `{{ craft.blitz.getTemplate() }}` on the site, it stops working as well when I use disabledPlugins on local. Is there any way to allow Blitz to work, but disable warming on an environment?

**Comment by bencroker** [comment]
Sure, you can set the [warmCacheAutomatically](https://github.com/putyourlightson/craft-blitz/blob/3eee542d2d12fb13dfbf0e444c87f045eda908cc/src/config.php#L128) config setting to `false` in your dev environment.
