### ISSUE TITLE
Multiple {{ craft.blitz.csrfInput }} should not make multiple XHR requests

### ISSUE THREAD

**Issue by benface** [putyourlightson/craft-blitz#329]
### Is your feature request related to a problem? Please describe.
Yes. I would’ve selected “Bug Report”, but it’s not so much a bug as a sneaky issue that can happen as a result of using `{{ craft.blitz.csrfInput }}`, which the enhancement I’m going to suggest should mitigate considerably.

I have a page with multiple `{{ craft.blitz.csrfInput }}` on it, for different forms. I noticed that triggers as many XHR requests as there are instances of `{{ craft.blitz.csrfInput }}`. That’s probably not optimal in terms of performance, but it would be OK if it wasn’t for the fact that when it’s the user’s first visit on the site (and the page is cached), the CSRF token is (re)generated for *every* XHR request, which means only the last one to execute ends up being valid. So if the user submits any form except the “right” one (which is often the last one but perhaps that depends on the network/race conditions), they get a “Unable to verify your data submission” error.

### Describe the solution you would like
There should be a single XHR request regardless of how many `{{ craft.blitz.csrfInput }}` there are on the page. The returned input can be used for all of them.

I would go even further and say that ideally, there should be a single XHR request for any number of `{{ craft.blitz.csrfParam() }}` and `{{ craft.blitz.csrfToken() }}` as well, otherwise the issue would still happen when using both `{{ craft.blitz.csrfInput }}` and `{{ craft.blitz.csrfToken() }}` on the same page. But I understand that is more complex and potentially a breaking change, because to achieve it, the XHR request would need to return the same data regardless of which `craft.blitz.` is used (and the JS would parse the data and render either the param, the token, or the whole input). Maybe that’s OK, since it doesn’t look like [the public API](https://putyourlightson.com/plugins/blitz#javascript-events) provides a way to get that data?

### Describe alternatives you have considered
I’ve put a single `{{ craft.blitz.csrfInput }}` at the bottom of the `<body>`, and with JS, I clone it inside all the forms on the page. That works well, but I spent a lot of time figuring out what the problem was, and I think this improvement could prevent other users from going through the same thing.

Thank you!

**Comment by bencroker** [comment]
It is important to note that once a CSRF token is used in a form submission, it is no longer valid. So say you had two forms on a page, each of which could be submitted via an AJAX request. If both forms used the same CSRF token to submit, the second one would fail as the token would no longer be valid. That is why we intentionally made each `craft.blitz.csrfInput` return a unique token.

Your workaround sounds fine provided your forms submit via regular (non-AJAX) requests. You could also use Craft's own `users/session-info` controller action to fetch a token if you're anyway using JavaScript to inject the fields.

**Comment by benface** [comment]
> It is important to note that once a CSRF token is used in a form submission, it is no longer valid.

Just for forms that log the user in or out, though, right? I just tested and it seems a CSRF token remains valid for the duration of the session, which is only reset on login/logout (when the `PHPSESSID` cookie changes).

So you’re right that the second form would fail if the first one (a login or register form) was submitted via AJAX (and was successful), but that’s already the case right now. Both CSRF tokens generated on page load would no longer be valid after the user logs in. My suggestion wouldn’t have any effect in this case, unless I’m missing something.

**Comment by bencroker** [comment]
I just tested locally and you are right, CSRF tokens remain valid for the user session duration. We'll look into adding your request, thanks.

**Comment by wei2go** [comment]
Hmm, guys, correct me if I'm wrong. If CSRF tokens remain valid for the user session duration, how would having a single XHR resolve the problem? Theoretically, no matter how many XHRs on the same page, they should all return valid CSRF tokens.

If one of the form can change the user session via AJAX (e.g. a login form), then we should probably write a custom event handler to refresh the CSRF token upon successful login and replace the existing token(s) page-wide?

**Comment by bencroker** [comment]
> Hmm, guys, correct me if I'm wrong. If CSRF tokens remain valid for the user session duration, how would having a single XHR resolve the problem? Theoretically, no matter how many XHRs on the same page, they should all return valid CSRF tokens.

I believe the issue is only if it is the user’s first visit to the site and therefore the user session does not already exist (when the page is cached).

> If one of the form can change the user session via AJAX (e.g. a login form), then we should probably write a custom event handler to refresh the CSRF token upon successful login and replace the existing token(s) page-wide?

That is beyond the scope of what we want to do with this update. In general I would say that if you have a form that can change the user session then you'll need to take care of updating the other forms yourself.

**Comment by benface** [comment]
> Hmm, guys, correct me if I'm wrong. If CSRF tokens remain valid for the user session duration, how would having a single XHR resolve the problem? Theoretically, no matter how many XHRs on the same page, they should all return valid CSRF tokens.

Yeah but no – like Ben says, when it's the user's first visit, there is no session cookie sent with these requests so the session is fully initialized at every request, which renders the previously generated tokens invalid.

**Comment by bencroker** [comment]
@benface as of https://github.com/putyourlightson/craft-blitz/commit/7c7499a979e3ba8ac2c34689ed5368b6e526dfee, the dynamic content inject script now only makes a single AJAX request per unique URL, including CSRF inputs and tokens. If you could help test this on your end then that would be much appreciated.

**Comment by bencroker** [comment]
Released in version 3.11.1.
