### ISSUE TITLE
Feature Request: Handling content scheduled for publish or expiration

### ISSUE THREAD

**Issue by wbrowar** [putyourlightson/craft-blitz#33]
Is there a way to check for content that has recently been published via scheduling a post to go live at a later date, or recently scheduled to expire, via command line so I could set up a cron job to check for it every night?

I know I could just clear the entire cache and warm it again via the command line, but it would be great to be able to run a task that checks to see if content has been updated and then use the smart caching setup to clear and warm only the related pages.

With something like this in place, it might also be nice to have a controller action set up so that I could use AJAX from the front end to run the methods behind this command, too. It could be used to when certain actions are performed on the front-end (like updating product inventory after a sale has gone through).

**Comment by putyourlightson** [comment]
You'd need to write a simple plugin or module to check for recently published or expired entries. Once you have them, you can call the Blitz cache service to recache the appropriate pages only:

    foreach ($updatedEntries as $entry) {
        Blitz::$plugin->cache->cacheByElement($entry)   
    }

Let me know if you need any other pointers.

**Comment by putyourlightson** [comment]
FYI I may consider adding this to the plugin in the future.

**Comment by wbrowar** [comment]
Thanks. My client asked about being able to expire and schedule entries, so I think I'll tinker with my site module to get something working. I can see this being a tricky problem to solve, especially when you do the server rewrite that bypasses php altogether.

**Comment by putyourlightson** [comment]
Yeah, the code sample above should handle clearing the cached file too, so it should just a matter of catching the expired or posted entries really.

**Comment by putyourlightson** [comment]
After consideration, this functionality will _not_ be added to the plugin. I'd still be interested to see if you come up with a module/plugin to handle this!

**Comment by michaelroper** [comment]
Related, I saw this plugin released the other day. I haven't tried it yet, but going on their description, would it possibly help in these cases, where the _save_ event is needed to trigger the cache invalidation?

https://github.com/Goldinteractive/craft3-publisher

**Comment by putyourlightson** [comment]
Yeah possibly, I'm reopening this issue and will reconsider it a feature request.

**Comment by sjelfull** [comment]
I think this is pretty essential to the plugin. Clients won't get why something isn't showing up, and relying on some other plugin seems pointless. (I wrote one that fires an event for this).

**Comment by putyourlightson** [comment]
Regardless, It will require a cron job to be set up. @sjelfull is your code on github?

**Comment by sjelfull** [comment]
Yep, it's here: https://github.com/sjelfull/craft3-publishedevent

**Comment by putyourlightson** [comment]
Does Published Event expect a cron job to trigger it? I didn't see any mention of it in the readme file.

**Comment by sjelfull** [comment]
Yeah, you have to run the console command from a cron job.

**Comment by wbrowar** [comment]
What do you think about keeping track of cache expirations in the DB table that keeps track of element cache groups? When EVENT_AFTER_SAVE_ELEMENT is fired, you could see if a cache expiration is needed if either the post date or expiation date is set to a future date. Then a new controller action and console command could be used to check the DB to see if any cache expirations have past and then clear and warm that group.

This would allow us developers to create a cron job or to use AJAX to ping the controller to see if the cache needs to be refreshed.

**Comment by putyourlightson** [comment]
I like it @wbrowar!! Any thoughts @sjelfull?

**Comment by sjelfull** [comment]
That basically sound like a more generic solution than a entry expiration-specific one, so 👍👍👍

**Comment by putyourlightson** [comment]
Thumbs up all round, consider it added (to the list!).

**Comment by putyourlightson** [comment]
FYI this is planned for the next release.

**Comment by brettburwell** [comment]
Very excited to read this thread. I was playing around with Blitz this morning and quickly fell in love, but this was one feature I can see most clients/sites needing.

**Comment by putyourlightson** [comment]
Added this in version 1.11. A cron job that runs the following console command should work nicely:

    ./craft blitz/cache/refresh-expired

**Comment by brettburwell** [comment]
@bencroker Quick question. I noticed your [example in the docs](https://putyourlightson.com/plugins/blitz#cron-jobs) has the `blitz/cache/refresh-expired` command running once an hour. 

I realize this is highly dependent on the site and server, but is there anything in particular about how this command works that would make it problematic to speed up the checks to once every 10 minutes? 

I realize we want to avoid putting unnecessary strain on the server, but I'm thinking if there's very rarely scheduled / expired content to deal with it shouldn't burden the server in any notable way to check more frequently. Let me know if that's flawed logic.

**Comment by bencroker** [comment]
@brettburwell If you anticipate having entries with post and expiry dates that need to be refreshed more frequently than every hour then setting the command to run every 10 minutes is totally fine. There isn't much of a strain on refreshing expired cache anyway, so all good.

**Comment by brettburwell** [comment]
@bencroker Awesome. I was hoping that would be the case, but thanks for confirming!
