### ISSUE TITLE
Purge not executed to cloudflare after entry update

### ISSUE THREAD

**Issue by ghost** [putyourlightson/craft-blitz#331]
### Describe the bug
We've been using the plugin for a while now but since june 24th the Reverse Proxy Purger doesn't purge items in cloudflare whenever a entry is edited, it only works whenever I press the "purge cache" button in /utilities/blitz-cache. So from what i understand is that my API key and zone ID are fine because the last action wouldn't succeed if they were broken. 

### To reproduce
Steps to reproduce the behaviour:
1. Edit an item (The index file in the cache folder is removed so it seems it does clear the cache)
2. Cloudflare doesn't purge the cache.

### Expected behaviour
Cloudflare releases its cache and servers the new version either via bypass or miss.

### Versions
SYSTEM
PHP version	7.4.20
OS version	Linux 3.10.0-1160.11.1.el7.x86_64
Database driver & version	MySQL 5.5.5
Image driver & version	Imagick 3.4.4 (ImageMagick 6.9.10-68)
Craft edition & version	Craft Pro 3.6.17
Yii version	2.0.42.1
Twig version	v2.14.6
Guzzle version	7.3.0

PLUGINS
Blitz	3.9.0
Feed Me	4.3.6
Freeform	3.11.8
Instagram Feed	1.1.5
Navigation	1.4.18
Redactor	2.8.7
SEO	3.3.43
Site Switcher	2.2.0
Super Table	2.6.8
Typed link field	1.0.25

**Comment by bencroker** [comment]
What value do you have in the "Warm Cache Delay" setting under "Reverse Proxy Purging"? A delay between purging the cache and warming it helps prevent stale versions of pages from being warmed, which may be happening in your case.

**Comment by ghost** [comment]
Cache warming delay is set to 30 seconds but in my website the cache warming has been turned off because large amount of entries (3000+ items). The issue you are describing occurred a few weeks ago during setup, took me a day to figure that one out but after that it worked great for a while.

**Comment by bencroker** [comment]
Ok great!

**Comment by ghost** [comment]
I think you've misread my answer, the issue you described does not relate to my issue as I figured that one out a few weeks ago and this one it still persists.

**Comment by bencroker** [comment]
Ah I see. Are you modifying the entry before saving? And how are you testing whether the Cloudflare is really purged?

**Comment by ghost** [comment]
I was checking the response headers for a hit in cf-cache-status and an updated age in multiple browsers. 

The weird thing is that it seems to work fine now that I check it again. It is a website for an event https://chio.nl/ that was hosted last weekend, it had around 13.000 to 15.000 visitors per day so maybe cloudflare wasn't happy to clear the cache of the most visited pages.

It seems to work fine right now.

**Comment by bencroker** [comment]
Good to hear!
