### ISSUE TITLE
Cannot overwrite cacheStorageType to YiiCacheStorage when FileStorage settings exist in project config

### ISSUE THREAD

**Issue by mattsbanner** [putyourlightson/craft-blitz#333]
### Describe the bug
We currently have a few sites live using Blitz with the FileStorage driver. I'm in the process of setting up another environment to migrate them to a load balanced setup, meaning I need to use the YiiCacheStorage driver in order to share a Redis cluster across each of the web servers.

I'm unable to override `cacheStorageType` setting to `putyourlightson\blitz\drivers\storage\YiiCacheStorage` in `blitz.php` as I receive this error: `Setting unknown property: putyourlightson\blitz\drivers\storage\YiiCacheStorage::folderPath`.

This appears to be due to the fact we have the FileStorage driver in use currently, with the folderPath variable saved in project config. If I change the driver within the CP, I do not encounter this error as the `cacheStorageSettings` array is cleared.

Currently, I have the two environments running from different codebases, but they still use the same database and so I cannot commit my changes into project config.

### To reproduce
Steps to reproduce the behaviour:
1. Save Blitz config using the FileStorage driver to project config.
2. Override `cacheStorageType` to `putyourlightson\blitz\drivers\storage\YiiCacheStorage` in `blitz.php`.
3. See error message`Setting unknown property: putyourlightson\blitz\drivers\storage\YiiCacheStorage::folderPath..`

### Expected behaviour
The `cacheStorageSettings` array should be ignored when `cacheStorageType` is being overridden to a driver that does not require settings.

### Versions
- Plugin version: 3.9.0
- Craft version: 3.6.12

**Comment by bencroker** [comment]
Each cache storage type can have settings. Setting `cacheStorageSettings` to an empty array will override the already saved values.

```php
'cacheStorageSettings' => [],
```
