### ISSUE TITLE
Pages not cached on production server when specifying siteIds

### ISSUE THREAD

**Issue by simonda86** [putyourlightson/craft-blitz#334]
### Question
I've set my Blitz config in the config/blitz.php and added the siteId's this works fine when I test locally (changing the environment to production). But on the production server, I see 0 cached pages for these sites in the Blitz admin. If I change the siteId to a blank string then all of the pages are successfully cached, the siteIds are the same in both databases.

I need to specify only these two sites as one handles a GEO redirect and I need this to not be cached, I'm not sure what I'm doing wrong. Can I use the site UUIDs instead?

I've included the config file below.

```
<?php

/**
 * @copyright Copyright (c) PutYourLightsOn
 */

/**
 * Blitz config.php
 *
 * This file exists only as a template for the Blitz settings.
 * It does nothing on its own.
 *
 * Don't edit this file, instead copy it to 'craft/config' as 'blitz.php'
 * and make your changes there to override default settings.
 *
 * Once copied to 'craft/config', this file will be multi-environment aware as
 * well, so you can have different settings groups for each environment, just as
 * you do for 'general.php'
 */

return [
	'*' => [
		// With this setting enabled, Blitz will log detailed messages to `storage/logs/blitz.log`.
		'debug' => true,

		// With this setting enabled, Blitz will begin caching pages according to the included/excluded URI patterns. Disable this setting to prevent Blitz from caching any new pages.
		'cachingEnabled' => true,

		// The URI patterns to include in caching. Set `siteId` to a blank string to indicate all sites.
		'includedUriPatterns' => [
		    [
		        'siteId' => 1,
		        'uriPattern' => '.*',
		    ],
			[
		        'siteId' => 2,
		        'uriPattern' => '.*',
		    ],
		],

		// Whether the cache should automatically be cleared when elements are updated.
		'clearCacheAutomatically' => true,

		// Whether the cache should automatically be warmed after clearing.
		'warmCacheAutomatically' => true,

		// Whether an `X-Powered-By: Blitz` header should be sent.
		'sendPoweredByHeader' => false,
	],
	'dev' => [
		// With this setting enabled, Blitz will log detailed messages to `storage/logs/blitz.log`.
		'debug' => true,

		// With this setting enabled, Blitz will begin caching pages according to the included/excluded URI patterns. Disable this setting to prevent Blitz from caching any new pages.
		'cachingEnabled' => false,
	],
];

```

**Comment by bencroker** [comment]
Can you double check the site IDs on the production server? It is possible that they differ in different environments. Using a site UUID is not supported.

**Comment by simonda86** [comment]
Hi @bencroker I have double checked this and there are both using the same IDs. I regularly copy the production DB to my local site as well.

This is one of the first things I checked as it sounded like a likely problem! The weird thing is I can see a number of pages being cached when I select the "Warm cache" option but then nothing is in the cache folders and there's no errors in the logs.

**Comment by bencroker** [comment]
Enabling the `debug` config setting will help you track down why pages are not being cached:
https://putyourlightson.com/plugins/blitz#debugging

Your issue might be due to the base site URLs containing a `@web` alias that is not explicity defined, see https://putyourlightson.com/plugins/blitz#the-site-is-not-being-cached-when-using-console-commands

**Comment by simonda86** [comment]
Thanks @bencroker I've enabled caching and in the logs I can see that all URLs don't match a include URI pattern when I specify siteIds but when its all sites they work. So your theory about not being able to determine base URL makes sense. I've tested this with specifying the full URL's in the site settings and it works.

I do use an alias to determine base site URLs and for the other two sites which is retrieved from the environment variable. I've been doing this with a @baseUrl alias and then appending the language version e.g. `/en-gb/` and `/en-us` but this wasn't working when I use an alias for each site URL and language it works. 

I'm really confused now, is there any reason why this would be the case?

**Comment by bencroker** [comment]
What are you setting `@baseurl` to and how are you setting the URLs for each site?

**Comment by simonda86** [comment]
`@baseUrl` is set from an environment variable in `config/general.php` e.g.

```
'aliases' => [
  '@baseUrl' => getenv('BASE_URL'),
  '@usUrl' => getenv('BASE_URL') . '/en-us/',
  '@ukUrl' => getenv('BASE_URL') . '/en-gb/',
],
```
and the `.env` file
```
BASE_URL="https://www.nurvv.com"
```
Then I was setting the siteUrl like this`@baseUrl/en-gb/` which isn't working when I test it. But for some reason `@ukUrl` is working.

**Comment by bencroker** [comment]
So what does the debug message tell you?

**Comment by simonda86** [comment]
This is an example from this morning
```
2021-07-27 08:47:12 [][][debug] Page not cached because it does not match an included URI pattern. [https://www.nurvv.com/en-gb/]
```

**Comment by bencroker** [comment]
Just tested this exact setup locally and caching works fine. When you go to the site settings page at `admin/settings/sites`, do you see the Base URL values parsed correctly?

**Comment by bencroker** [comment]
Also, are you running the latest versions of Craft and Blitz?

**Comment by simonda86** [comment]
Strange, this has just started working for me after removing the `config/blitz.php`, I was preparing some more debug information and the logs were clear. I'll mark this as closed for now and reopen if I have any other problems later on.

**Comment by bencroker** [comment]
Ok, well glad it is working for you at least!
