### ISSUE TITLE
Exclude Urls from Cache Warming

### ISSUE THREAD

**Issue by aloco** [putyourlightson/craft-blitz#335]
### Is your feature request related to a problem? Please describe.

We are dealing with a big site including around 30.000 news entries and almost 50.000 commerce products. running the cache warmer task takes like forever and blocks all further queue jobs. However I don´t really need all of those old news entries and commerce products warmed but still want to cache them when a visitor visits this specific page because why not. Something like the Exclude URI Patterns from the general settings would make it I think

**Comment by bencroker** [comment]
There are no plans to add inclusion/exclusion URI patterns to the warming driver.

One option is to disable automatic cache warming and allow the cache to be warmed organically. The other is to write a custom module/plugin that listens for the `EVENT_BEFORE_WARM_CACHE` event and removes any `siteUris` that should not be warmed.
https://github.com/putyourlightson/craft-blitz/blob/fac649e3857dcf74a73f803a148071fb643f78a2/src/drivers/warmers/BaseCacheWarmer.php#L148

**Comment by bencroker** [comment]
FYI I added a code sample to BaseCacheWarmer. 
https://github.com/putyourlightson/craft-blitz/blob/1f14c71892034375ee08fa32c03a3fdde194479f/src/drivers/warmers/BaseCacheWarmer.php#L28-L54

**Comment by aloco** [comment]
Thank you Ben! ✌️
