### ISSUE TITLE
Prevent Blitz from warming on cp login

### ISSUE THREAD

**Issue by ursbraem** [putyourlightson/craft-blitz#336]
### Question
Hi! When I log into the CP I get

<img width="248" alt="grafik" src="https://user-images.githubusercontent.com/1446443/126744081-848459e7-0bf2-49f4-bfe4-8a83b1bfdc8e.png">

Which slows down the cp handling. This is due to craft's poorman's cron at cp login I guess.

Now I set `'runQueueAutomatically' => false,` in config/general.php and added a cronjob to start ./craft queue/run at midnight, but it still heats up the warmers when I log in. 

What am I missing?

**Comment by bencroker** [comment]
If you set `runQueueAutomatically` to `false` then you should run the cron job much more frequently than once per day. The example in the docs shows the command set to run every minute:
https://craftcms.com/docs/3.x/config/config-settings.html#runqueueautomatically

**Comment by ursbraem** [comment]
Thanks Ben! I thought it hadn't stopped executing the queue on login yet. But it did now.

**Comment by ursbraem** [comment]
For others: Locally, I disabled blitz by setting in config/blitz.php

```
return [
	// Local environment settings
	'local' => [
             'cachingEnabled' => false,
	],
];
```
