### ISSUE TITLE
Blitz and Craft Commerce sales for user groups

### ISSUE THREAD

**Issue by rbrv** [putyourlightson/craft-blitz#338]
### Question
- Blitz is enabled
- Cache warming is enabled
- The Apache rules are set
- In Craft Commerce, there is a sale assigned to a specific User Group  

1. How to display these specific sale prices for the logged in user when Blitz has cached the page
2. Extra caveat: A user in this group visits the page before the cache for that page has been warmed. Now the page with the user-group specific sale prices is cached in Blitz and shown for all visitors

**Comment by bencroker** [comment]
You can either use the [dynamic content](https://putyourlightson.com/plugins/blitz#dynamic-content) feature of Blitz, or use [Sprig](https://putyourlightson.com/plugins/sprig) for loading dynamic content into cached pages.

**Comment by rbrv** [comment]
We've thought about this approach, bit it's far from ideal:

The target User Group is only +/- 2% of all website visitors.
Using Blitz dynamic content or sprig will generate extra requests for each product price displayed; and this for 100% of website visitors...

Is there a way to bypass Blitz if a user of a specific User Group is logged in?

**Comment by bencroker** [comment]
No there is not. If it is for only intended for a very small number of visitors then they could perhaps be redirected either to a special template or to an uncached version of the same template.
