### ISSUE TITLE
Environment-aware settings via config files?

### ISSUE THREAD

**Issue by michaelroper** [putyourlightson/craft-blitz#34]
Hey Ben!

Is it possible to expose/override the plugin settings via a `config/blitz.php` file, so we can enable/disable or change paths, depending on what the current environment is?

If not, can there maybe be a setting to disable caching if `'devMode' => true` is set, for local development?

Cheers,
Michael

**Comment by putyourlightson** [comment]
Hi Michael, yes that's possible with every plugin. I've create a sample `config.php` file so you can see what settings you can override and how. Hope this helps!
https://github.com/putyourlightson/craft-blitz/blob/v1/src/config.php
Ben

**Comment by michaelroper** [comment]
Hah, I didn't realise that was a default thing. Awesome, thanks for the example too!

**Comment by klick** [comment]
Hey Ben.

The config needs to be named `blitz.php`, right? Somehow, it doesn’t seem to work.

Cheers.

**Comment by putyourlightson** [comment]
Correct, see the comments at the top of the file:
https://github.com/putyourlightson/craft-blitz/blob/v2/src/config.php

**Comment by klick** [comment]
Thanks.

It is caching though, no matter what I put in the config file. Weird.

Correction:
It works now but ignores variables from the .env like: `BLITZ_CACHE=false` which I am then calling with `'cachingEnabled' => getenv('BLITZ_CACHE'),`. 

Do booleans not work this way?

**Comment by putyourlightson** [comment]
Are you using a multi-environment setup? If so then you'll need to adjust `blitz.php` accordingly.

**Comment by putyourlightson** [comment]
Ah I see, the value `false` will be converted to a string, thereby evaluating to `true`. Can you try `BLITZ_CACHE="0"` instead? Or you could try the method as explained here:
https://medium.com/@cobbers/easy-boolean-support-for-dotenv-env-variables-66ddf941bde9

**Comment by klick** [comment]
Ah ok that makes sense.

`BLITZ_CACHE="0"` works.

Thanks!

**Comment by putyourlightson** [comment]
Great!
