### ISSUE TITLE
Very Slow When saving/updating an entry with Blitz Enabled

### ISSUE THREAD

**Issue by ambidustrious** [putyourlightson/craft-blitz#340]
### Describe the bug
I launched a new site this evening and went from Dev to Production in the settings... Once I did this, entries took a very long time to save (sometimes 2-3 minutes).

This was not the case in dev mode on the same server.

All that changed was the mode of the site and the URL.

### Versions
- Plugin version: 3.10.2
- Craft version:3.7.8

**Comment by ambidustrious** [comment]
This went away when I turned off automatic cache warming... This is a very large site with a LOT of related entries/cross posting etc... So I'm just going to leave that off

**Comment by bencroker** [comment]
There are a few other suggestions you can consider for such a site as documented at https://putyourlightson.com/plugins/blitz#the-refresh-cache-queue-jobs-run-for-long-periods-of-time-and-sometimes-pile-up

**Comment by ambidustrious** [comment]
Thank you - I think this will work great... quick question. Can you put multiple tags on the same page? Instead of listing multiple tags in a single {% do craft.blitz.options.tags(['sectionId:3']) %}..

It would be great if I can put them in neo block templates.

```
<neo  blog>
{% do craft.blitz.options.tags(['blog') %}
Blog Posts
</neo blog>

<neo  news>
{% do craft.blitz.options.tags(['news') %}
News Posts
</neo blog>

<neo  resources>
{% do craft.blitz.options.tags(['resources') %}
Resource Posts
</neo resources>

```

**Comment by bencroker** [comment]
You can, but assuming you want to append tags, you'll need to merge/push the tags each time.

```twig
{% set tags = [] %}

<neo  blog>
{% set tags = tags|push('blog') %}
Blog Posts
</neo blog>

<neo  news>
{% set tags = tags|push('news') %}
News Posts
</neo blog>

<neo  resources>
{% set tags = tags|push('resources') %}
Resource Posts
</neo resources>

{% do craft.blitz.options.tags(tags) %}
```

**Comment by ambidustrious** [comment]
I should have thought of that :) Thanks!
