### ISSUE TITLE
Throttle not working as intended on Cloudflare purger

### ISSUE THREAD

**Issue by DavidStrada** [putyourlightson/craft-blitz#341]
This [value](https://github.com/putyourlightson/craft-blitz/blob/develop/src/drivers/purgers/CloudflarePurger.php#L238) is just being used to chunk the request, however on Pool reference you send all the values, without throttling them, Cloudflare starts throwing `/purge_cache` resulted in a `429 Too Many Requests` response`

### To reproduce
Save an Entry and when Blitz tries to purge_cache, you will see 429 Too many reques.

### Versions
- Plugin version: Blitz 3.9.0
Craft CMS 3.6.13

**Comment by bencroker** [comment]
Correct, requests are being chunked into groups of max 30 URLs, which is a limit set by the Cloudflare API: https://api.cloudflare.com/#zone-purge-files-by-url

According to the API docs at https://api.cloudflare.com/#getting-started-requests

> The Cloudflare API sets a maximum of 1,200 requests in a five minute period.

So throttling the chunks won't help. I suppose the only way of working around this is to detect if the API responds with a 429 error and then retry every X number of seconds until the rate limit is reset and the request is successful. It's far from an ideal way of handling it though, as the queue job would be stalled in the meantime. A more robust solution might be to queue up a new queue job each time we hit that rate limit.

**Comment by DavidStrada** [comment]
Thanks for your reply @bencroker, here's a possible solution that I've used in `Laravel`

- Have a table where you push the failed jobs eg. `failed_jobs` (so when error occurs) you put those items here.
- Have a command `./craft queue:retry all` (to rety all failed jobs). so this will fire a new job.

On your instructions have a note to say, configure a cron-job (decide what works best time eg. every 5 minutes) and run `./craft queue:retry all`

for reference : 

- [DB table](https://github.com/laravel/framework/blob/8.x/src/Illuminate/Queue/Console/stubs/failed_jobs.stub)
- [Retry as batch](https://github.com/laravel/framework/blob/8.x/src/Illuminate/Queue/Console/RetryBatchCommand.php)
- [Retry] (https://github.com/laravel/framework/blob/8.x/src/Illuminate/Queue/Console/RetryCommand.php)

**Comment by bencroker** [comment]
Thanks but Craft already handles failed queue jobs and provides the `queue/retry` console command:
https://craftcms.com/docs/3.x/console-commands.html#queue-retry

It also gets trickier when you consider that purging the cache blocks the cache warming process, which runs in a separate queue job.

**Comment by bencroker** [comment]
As of [5.12.8](https://github.com/putyourlightson/craft-blitz/releases/tag/5.12.8), the Cloudflare purger now sends requests sequentially rather than in parallel, and can make up to 3 attempts, to help prevent rate limiting when purging a large number of URLs.
