### ISSUE TITLE
"Cache" input token

### ISSUE THREAD

**Issue by lenvanessen** [putyourlightson/craft-blitz#342]
We have a webshop running Craft Commerce, with add-to-carts on the catalog pages. This means, Blitz will run many fetch-requests to get the input, whilst 1 would be suffient.

Perhaps we can improve the performance here a bit and just do 1 fetch request?

<img width="1788" alt="Schermafbeelding 2021-09-02 om 11 24 30" src="https://user-images.githubusercontent.com/23024452/131819020-ad5da02b-c96b-4764-97dc-0347b3cbbef4.png">

**Comment by bencroker** [comment]
Are these requests for CSRF input fields? If so then this is already underway and you can follow the conversation at https://github.com/putyourlightson/craft-blitz/issues/329.

**Comment by lenvanessen** [comment]
Duplicate of #329
