### ISSUE TITLE
getTemplate parsing Template path incorrectly in local environment

### ISSUE THREAD

**Issue by Kotstar1** [putyourlightson/craft-blitz#345]
So I tested the getTemplate Method in a Project that im working on. 
I discovered that when I include a template with getTemplate, the url to the action is not correct.

The Url I get is: 
http://localhost/actions/blitz/templates/get?template=82ce102aef7db1198900104fe3ad2bd2ceb00c773044fbb9a1110883ace97ae9_includes%2Fheader%2Findex.twig&siteId=1

The url should be: http://localhost/2020/project/actions/blitz/templates/get?template=82ce102aef7db1198900104fe3ad2bd2ceb00c773044fbb9a1110883ace97ae9_includes%2Fheader%2Findex.twig&siteId=1

I found out that when I change the action path in the Cached file to -> actions/.... rather than /actions... it worked.

But when I disable the Blitz caching, I can't modify the action path and the template is not found: 
![image](https://user-images.githubusercontent.com/45969589/133002751-70865a76-1785-4dfc-aadb-d491a45f628c.png)

BTW it works on my test server.

### To reproduce
Steps to reproduce the behaviour:
1. include a template in a local environment with the same folder structure I have (I use XAMPP)
2. Check the Network tab

### Versions
- Plugin version: 3.10.3
- Craft version: 3.7.11

**Comment by bencroker** [comment]
Thanks, changed this in https://github.com/putyourlightson/craft-blitz/commit/c6ac25c0b6a749260136f62cdae0029181ee0539 for the next release.

**Comment by bencroker** [comment]
Released in version 3.10.4.
