### ISSUE TITLE
Refresh jobs added to the queue even with Blitz disabled

### ISSUE THREAD

**Issue by seandelaney** [putyourlightson/craft-blitz#347]
Hey Ben!

### Question
We have Blitz installed on a very large site. Enabled on Production but disabled on Development and locally...However `'clearCacheAutomatically' => true,`.

A few days ago, we needed to update ~5k worth of entries programmatically and we did this via a console command on Development server.

However, we noticed that even with Blitz disabled on Development server, Blitz still added new Refresh jobs to the queue for each entry we updated (I'm assuming this is caused by `'clearCacheAutomatically' => true,`) and we ended up with a pretty large queue of jobs...Saying that, the jobs were getting processed but my question is why add said jobs to the queue if the plugin is disabled? Shouldn't `'cachingEnabled' => false,` overrule `'clearCacheAutomatically' => true,` ?

Please correct me if I'm wrong but I can't see anything in here that checks if the plugin is enabled or disabled when adding updated elements to the refresh queue: https://github.com/putyourlightson/craft-blitz/blob/develop/src/services/RefreshCacheService.php#L185

I've found https://github.com/putyourlightson/craft-blitz/issues/236 leading me to https://putyourlightson.com/plugins/blitz#the-refresh-cache-queue-jobs-run-for-long-periods-of-time-and-sometimes-pile-up and we have `cacheElementQueries` set to `false`.

**Comment by bencroker** [comment]
Setting `cachingEnabled` to `false` prevents any new pages from being cached. Pages already cached may continue to be cleared/warmed. To disable the plugin in your development environments, use the [disabledPlugins](https://craftcms.com/docs/3.x/config/config-settings.html#disabledplugins) general config setting.

**Comment by seandelaney** [comment]
Thanks Ben!
