### ISSUE TITLE
Blitz template not found on production

### ISSUE THREAD

**Issue by timprint** [putyourlightson/craft-blitz#349]
Craft CMS 3.7.16
Blitz 3.10.3 

I have a YouTube video embed on a page via an oEmbed field and Blitz. It is working fine on my local set up in MAMP and also on a staging server. On the live server I am getting a console error.

`{{ craft.blitz.getTemplate('components-blitz/video', { iframe: entry.homeVideo.media.code }) }}`

On the live server I am getting a 404 error for the template 

```
XHR GET https://www.odette.org/actions/blitz/templates/get?template=1115c2871e34bcf0f4b1ad5d15abb1802fbbb0dd13f1953825d66f389fd6d52ccomponents-blitz/video&params[iframe]=<iframe+width="200"+height="113"+src="https://www.youtube.com/embed/L43KWprd-b4?feature=oembed"+frameborder="0"+allow="accelerometer;+autoplay;+clipboard-write;+encrypted-media;+gyroscope;+picture-in-picture"+allowfullscreen=""></iframe>&siteId=1
[HTTP/1.1 404 Not Found 1613ms]
```

I'm struggling to diagnose what the issue is. Any ideas would be really helpful.

**Comment by bencroker** [comment]
Have you tried clearing the Blitz cache for that page to ensure it is not serving stale HTML?

**Comment by bencroker** [comment]
Have you tried clearing the Blitz cache for that page to ensure it is not serving stale HTML?

**Comment by timprint** [comment]
Yes, I've cleared the cache several times. I've just tested adding video to another page and that is doing the same.

**Comment by bencroker** [comment]
It looks like the content of the iFrame is being added to the URL. Can you show me what your component looks like?

**Comment by timprint** [comment]
This is the page template code
```
<div class="video" style="background-image: url('{{ entry.homeVideo.media.image }}');" data-video-url="{{ entry.homeVideo.url }}">
	{{ craft.blitz.getTemplate('components-blitz/video', 
		{ iframe: entry.homeVideo.media.code })
	}}
</div>
```

This is 'components-blitz/video'

```
{% if craft.cookieConsent.getConsent('default-third-party-cookies') %}
	{{ iframe|raw }}
{% else %}
	<div class="video-warning">
		<div class="alert m_info">
			<svg><use xlink:href="{{ siteUrl }}assets/svgs/svg-master.svg#icon-info"></use></svg>
			<div class="copy">
				<p>You must <a href="#" class="show-cookie-consent">accept third party cookies</a> to enable this video content.</p>
			</div>
		</div>
	</div>
{% endif %}
```

I'm going to do some htaccess testing today, as I say it is working on local and staging.

**Comment by bencroker** [comment]
You probably shouldn't be passing the entire iframe source code as a parameter. Instead, just pass in the entry ID and then fetch the code using an `entries` query.

```twig
{{ craft.blitz.getTemplate('components-blitz/video', { entryId: entry.id }) }}
```

```twig
{% set entry = craft.entries.id(entryId).one() %}
{% if entry %}
    {{ entry.homeVideo.media.code|raw }}
{% endif %}
```

**Comment by timprint** [comment]
Thank you. Fixed
