### ISSUE TITLE
No Blitz Cache on latest update 1.6.5 - not working

### ISSUE THREAD

**Issue by Osze** [putyourlightson/craft-blitz#35]
I had an issue with Warm Blitz Cache so I updated the plugin to 1.6.5. 

but now nothing works. :(

in my settings I have included:
/.*

I want to cache all my pages. 

I've tried with / and * but nothing works now after the update.

**Comment by putyourlightson** [comment]
Fixed in 1.6.6 https://github.com/putyourlightson/craft-blitz/commit/7966c9f37e22867fcd7bec84e00cf200c4a45f47
