### ISSUE TITLE
3.10.4 breaks Craft pagination 

### ISSUE THREAD

**Issue by paulboger** [putyourlightson/craft-blitz#350]
### Describe the bug
Since installing the latest update, it appears the [changes here](https://github.com/putyourlightson/craft-blitz/commit/bfe317a59bd59209f65547fd86bd05050288609b#diff-e74129f9c490eae2fdd5[…]7c46999b05606fdf5ee6b9eee) have broken pagination. 'pathInfo' simply returns the primary entry url, missing the pagination path. The docs indicate this as well "Returns the requested path, sans control panel trigger and pagination info". 

We're using standard craft pagination in this case, nothing out of the ordinary. Cache rules are set to cache everything, including query strings. We are also utilizing gzip and server rewrites on blitz storage. It may be worth mentioning that our environment is using a Cloudfront reverse proxy purger which has added additional considerations for dynamic requests. 

### To reproduce
1. Upgrade to 3.10.4
2. Confirm pagination is now failing - given any number of paginated views — /blog-posts/, /blog-posts/p1/, /blog-posts/p2/, etc. — they all return the same content, which is the view that was cached first. 
3. Downgrade to 3.10.3
4. Confirm pagination is working as expected
You can also remain on 3.10.4 and simply disable caching which also restores functionality.

### Expected behaviour
Pagination should not be impacted

### Versions
- Plugin version: 3.10.4
- Craft version: 3.7.17

**Comment by bencroker** [comment]
Thanks, fixed in https://github.com/putyourlightson/craft-blitz/commit/2fd6f152957b0651dfa493dafdeaf38dc8615150 and released in version 3.10.5.
