### ISSUE TITLE
[3.10.5] Server rewrite fails for for multi site setups with subdirectories

### ISSUE THREAD

**Issue by wsydney76** [putyourlightson/craft-blitz#351]
### Describe the bug

Having a site setup with a base url including a subdirectory, like `baseUrl: '@baseurl/de'`, the cached pages where stored as `...\domain.local\de\studios\index.html` , after upgrading to 3.10.5 it's now `...\domain.local\de\de\studios`, causing the server rewrite to fail.

Looks like a cached page is still served, but it hits php.

### To reproduce
Steps to reproduce the behaviour:
1. Setup sites using base urls with a subdirectory like https://domain.local/de and https://domain.local/en
2. Visit a page 
3. Inspect cache folder structure, the subdirectory appears twice.
3. Revisit the page
![image](https://user-images.githubusercontent.com/60010597/138412878-98e25762-b368-4b86-b6b0-9672122836e3.png)

### Expected behaviour
Well, like before....

### Versions
- Plugin version: 3.10.5
- Craft version: 3.7.17.2

**Comment by bencroker** [comment]
Thanks for reporting this. Can you please check whether this is working correctly for you using Blitz version 3.10.4? I think I see the issue but want to be sure before releasing.

**Comment by wsydney76** [comment]
@bencroker Thanks, yes it is working correctly with 3.10.4

**Comment by bencroker** [comment]
Ok thanks for checking, we'll release a fix for this soon.

**Comment by bencroker** [comment]
Fixed in https://github.com/putyourlightson/craft-blitz/commit/30af577ce9fc3b267bf35e16cc74d54a3ed92dd4 and released in version 3.10.6.

**Comment by wsydney76** [comment]
@bencroker Thanks for the quick fix!

Works well in general, one thing i noticed: Looks like the subdirectory string (en/de in our case) is not only removed from the beginning of the URI, but any subsequent occurrences are also replaced.

`https://domain.local/en/photo-events/budapest-2022` is cached in a folder `...\domain.local\en\photo-evts\budapest-2022`

`https://domain.local/de/videos` in `...\domain.local\de\vios`

**Comment by bencroker** [comment]
Thanks for catching that! Fixed in https://github.com/putyourlightson/craft-blitz/commit/503a6b8db921ef02cb896eb0ce8d0b48d7b28286 and released in 3.10.7. Hopefully this will be the last required tweak regarding request URIs!
