### ISSUE TITLE
A lot of 404s since the action url changed to relative urls

### ISSUE THREAD

**Issue by lenvanessen** [putyourlightson/craft-blitz#352]
### Describe the bug
We have a lot of problems with the recent version of blitz, relating to this commit
c6ac25c0b6a749260136f62cdae0029181ee0539

Because the url is not this:
` {{ craft.blitz.getTemplate('/components/header-user') }}`

Now renders:
`  <span class="blitz-inject" id="blitz-inject-2" data-blitz-id="2" data-blitz-uri="actions/blitz/templates/get" data-blitz-params="template=f8e25231778d934edc938d015864b9be87184f26b17e8f847672b76c8c1a534a%2Fcomponents%2Fheader-user&siteId=1"></span>`

Which works fine, but only on the homepage...

If you visit for instance: yoursite.nl/contact
The action url that's fetched will become: yoursite.nl/contact/actions/blitz/templates

Perhaps it's an idea to prepend the site baseurl here, for the multisite approach to work without breaking on all pages except the homepage

**Comment by bencroker** [comment]
Fixed in https://github.com/putyourlightson/craft-blitz/commit/aca78e7497679bd543bf103ca752001753a08e02 for the next release, thanks!

**Comment by bencroker** [comment]
Released in version 3.10.8.

**Comment by aaronlax** [comment]
I am having this same issue with the latest version

**Comment by bencroker** [comment]
Please ensure you refresh the Blitz cache and if the issue persists then create a new issue providing details to help us troubleshoot.
