### ISSUE TITLE
Pass `cacheDuration` config setting to `YiiCacheStorage` driver

### ISSUE THREAD

**Issue by mattsbanner** [putyourlightson/craft-blitz#353]
### Is your feature request related to a problem? Please describe.
We have a site where we like pages in the Blitz cache to expire after six hours. We're using the `YiiStorageDriver` which has support for a cache duration where the TTL can be set in Redis. 

### Describe the solution you would like
We would love for the `cacheDuration` config setting to be passed through in the `set()` method so that we do need to schedule any commands to clear expired cache items as the items would expire natively within Redis.

### Describe alternatives you have considered
Setting `defaultDuration` in the cache component. It would just be nice if we could control Blitz separately to this.

**Comment by bencroker** [comment]
Thanks for the suggestion! Added in https://github.com/putyourlightson/craft-blitz/commit/a5b45e6aedb0d7238e70da43a1decf7bdbea0740 for the next release, feel free to test in the meantime.

**Comment by mattsbanner** [comment]
Awesome, thanks Ben!

**Comment by bencroker** [comment]
Released in version 3.11.0.
