### ISSUE TITLE
Home page cache not being cleared

### ISSUE THREAD

**Issue by tyssen** [putyourlightson/craft-blitz#354]
I'm working on a site that has a number of pages being cached and cleared properly by Blitz except for the home page whose cache doesn't get cleared unless you do it manually.

    {% do craft.blitz.options.tags(['sectionId:4']) %}

That's an example from a template that does get cleared successfully.

    {% do craft.blitz.options.tags(['sectionId:2','sectionId:3','sectionId:4','sectionId:5','sectionId:7','groupId:122557-comparisons','groupId:122558-best_cameras']) %}

And that's from the home page. Any ideas why all the other templates should be working OK but not the home page?

**Comment by bencroker** [comment]
Which section ID does the homepage entry belong to, assuming that is how it is set up?

**Comment by tyssen** [comment]
The home page doesn't have an entry. It's made up of listings from other channels.

**Comment by bencroker** [comment]
Ok, so in what specific circumstance is the cached homepage _not_ being cleared, and why do you believe it should be? Please provide specifics.

**Comment by tyssen** [comment]
It should be cleared whenever an entry is published in one of the sections or categories listed. For example, an entry gets published into a section with ID = 4 and the page that displays entries from that channel gets refreshed. 

The home page also has a section that displays entries from that channel (amongst others) but it doesn't show the new entry that is already showing on the other listing page.

**Comment by bencroker** [comment]
So are you saying that it doesn't get refreshed only when a new entry is created in one of the sections listed? Or also when an existing entry is modified?

**Comment by tyssen** [comment]
Not sure about edits as well. The client only lets me know about when new entries have been published.

**Comment by bencroker** [comment]
Just tested locally with the latest version 3.10.8 and it is working as expected.

**Comment by bencroker** [comment]
I'm looking into another issue which may be related, will post an update here as soon as I have one.

**Comment by bencroker** [comment]
Released version 3.11.0 which should hopefully help with this.

**Comment by tyssen** [comment]
Yes, this seems to have fixed the issue, thanks. 👍

**Comment by tyssen** [comment]
I'm not sure whether this is related or not, but this behaviour was present before upgrading to the latest version, and initially, we thought the upgrade had sorted it out, but it still seems to be occurring.

We end up with a large number of pending jobs in the queue manager, all with the same contents:

    {
        "cacheIds": [],
        "elements": {
            "craft\\elements\\Entry": {
                "elementIds": [
                    124566,
                    124559,
                    124554,
                    124546,
                    124541,
                    124539,
                    124529,
                    124519,
                    124511,
                    124475,
                    124500,
                    124492,
                    124460,
                    124446,
                    124431,
                    124440,
                    122779,
                    124426,
                    124410,
                    124262
                ],
                "sourceIds": [
                    "5",
                    "4",
                    "2",
                    "3"
                ]
            }
        },
        "clearCache": true,
        "description": null
    }

Every now and then there will be one that pops up that says reserved with progress 100% but it stays there for a long time so I'm not sure if it's ever completing.

**Comment by bencroker** [comment]
It sounds unrelated, a new issue with more details would be helpful.
