### ISSUE TITLE
Issue with Simple Map plugin and cache not clearing

### ISSUE THREAD

**Issue by samstevens** [putyourlightson/craft-blitz#355]
### Describe the bug

When Blitz automatically clears the cache, the queue task can fail for certain queries when using the Simple Map plugin. This will result in the site being partially cleared.

![image](https://user-images.githubusercontent.com/4434133/141868018-b877ea97-f2e8-4f15-a24e-e9edce79ffc0.png)

### To reproduce

When using the Simple Map plugin and the ORDER BY distance feature, Blitz will store the original SQL query it saw, however, the plugin is doing some extra work under the hood:

https://github.com/ethercreative/simplemap/blob/v3/src/services/MapService.php#L392

This results in an error in the SQL query blitz stores.

### Expected behaviour / potential fix

These queries could be ignored.

### Versions
- Plugin version: Latest
- Craft version: Latest

Thanks,
Sam

**Comment by bencroker** [comment]
Thanks for reporting this. I made the refresh cache job ignore exceptions when executing element queries in https://github.com/putyourlightson/craft-blitz/commit/867bcb8f876dba9c7c9dfd265f95c4cfbc3c634a, which should prevent the queue job from failing in the next release.

**Comment by samstevens** [comment]
Thanks Ben – that makes sense.

Cheers,
Sam

**Comment by bencroker** [comment]
Released in version 3.11.1.
