### ISSUE TITLE
Blitz serves cached pages when site is in maintenance mode

### ISSUE THREAD

**Issue by nickdunn** [putyourlightson/craft-blitz#356]
### Describe the bug
When making a site deployment, we use an environment variable to push the Craft site into maintenance mode (`'isSystemLive' => (getenv('SITE_LIVE') === '1')` in our general.php config). This allows editors to make content changes before opening the site back up to the public, and they can browse the site freely.

We're finding that as the editors browse the "offline" site checking content changes, this is caching responses and they're being served to the public instead of the maintenance page.

### To reproduce
1. Enable Blitz
2. Enable maintenance mode on the site, use a private browser to see the homepage serving the custom 503.twig template
3. In another browser, log into Craft and then hit the homepage to see the true homepage (rather than the maintenance page)
4. Refresh the first browser and you'll see that Blitz serves the homepage rather than the 503 template

### Expected behaviour
My expectation was that public users would still see the 503.twig template, while CMS users could still browse the site freely (presumably warming caches too) whole the site is in maintenance mode. Perhaps Blitz needs to understand the the `Craft::$app->getConfig()->getGeneral()->isSystemLive` setting to not cache anything when offline?

### Versions
- Plugin version: 3.11.0
- Craft version: 3.7.19

**Comment by nickdunn** [comment]
Similar to #83

**Comment by nickdunn** [comment]
FYI we're _not_ using server-rewrites here, just a Redis cache.

One option is to disable Blitz cache entirely at the same time as putting the site into maintenance mode I guess (which we also have as an env var `'cachingEnabled' => (getenv('ENABLE_BLITZ_CACHE') === '1')`), but it'd be nice for Blitz to handle this gracefully itself somehow.

**Comment by bencroker** [comment]
As explained in https://github.com/putyourlightson/craft-blitz/issues/83, it is often beneficial to have the site cache pages while in maintenance mode. This only happens when a user that has permission to access a non-live site is logged in. 
https://github.com/putyourlightson/craft-blitz/blob/867bcb8f876dba9c7c9dfd265f95c4cfbc3c634a/src/services/CacheRequestService.php#L86-L91

So I don't consider this a bug, perhaps a feature request. However, you can solve this quite easily using config settings and environment variables.

```
'cachingEnabled' => getenv('ENABLE_BLITZ_CACHE') && getenv('SITE_LIVE'),
```

**Comment by nickdunn** [comment]
That's a good workaround that my tired brain hadn't considered! Thanks.
