### ISSUE TITLE
Refreshing Blitz cache jobs rack up in the queue

### ISSUE THREAD

**Issue by tyssen** [putyourlightson/craft-blitz#357]
A site with Blitz installed keeps having *Refreshing Blitz cache* jobs stack up in the queue saying *Pending* and never completing.

The job data is always the same:

    {
        "cacheIds": [],
        "elements": {
            "craft\\elements\\Entry": {
                "elementIds": [
                    124566,
                    124559,
                    124554,
                    124546,
                    124541,
                    124539,
                    124529,
                    124519,
                    124511,
                    124475,
                    124500,
                    124492,
                    124460,
                    124446,
                    124431,
                    124440,
                    122779,
                    124426,
                    124410,
                    124262
                ],
                "sourceIds": [
                    "5",
                    "4",
                    "2",
                    "3"
                ]
            }
        },
        "clearCache": true,
        "description": null
    }

We have git hooks triggering the clearing and flushing of Blitz cache whenever I push changes to the server, and the log files for those actions say they're completing successfully. 

We also have a cron job set up to run `blitz/cache/refresh-expired` every five minutes and I assume it's this that's causing all the pending jobs. So we're wondering what's stopping all these jobs from completing.

**Comment by bencroker** [comment]
Please provide the versions of Blitz and Craft the site is running on, as well as anything out of the ordinary about your Blitz setup. Are queue jobs run via web requests in Craft or are you using another technique (cron job or a plugin)?

**Comment by tyssen** [comment]
Craft 3.7.21
Blitz 3.11.0

The only thing triggering Blitz cache refreshes are the git hook and cron job mentioned above.

Cache storage is set to Blitz File Storage with create gzip files.
Cache warmer is guzzle with 3 concurrent requests.
No reverse proxy purger or remote deployer.
Cache is set to clear automatically when elements are updated and query strings are cached as unique pages.

**Comment by bencroker** [comment]
Thanks. Are queue jobs run via web requests in Craft or are you using another technique (cron job or a plugin)?

**Comment by tyssen** [comment]
Sorry, I thought I already answered that. I assume the queue jobs are created by the cron job which runs every 5 minutes.

**Comment by bencroker** [comment]
What I mean is, do queue jobs run each time the CP is visited, or have you disabled [runQueueAutomatically](https://craftcms.com/docs/3.x/config/config-settings.html#runqueueautomatically) in favour of a cron job, or are you using a plugin like [Async Queue](https://github.com/ostark/craft-async-queue) to manage queue jobs?

**Comment by tyssen** [comment]
` runQueueAutomatically` isn't disabled but Async Queue is installed and enabled.

**Comment by bencroker** [comment]
I would suggest disabling Async Queue to see if that makes any difference.

**Comment by tyssen** [comment]
I've disabled it and the jobs are still mounting up.

**Comment by bencroker** [comment]
Have you tried restarting them from the queue manager?

**Comment by tyssen** [comment]
At the moment, there are two jobs, one with a reserved status which has a restart button, the one after that says pending. I've tried restarting the reserved job but it doesn't appear to have done anything. The client is saying he's clearing the queue manager manually daily.

**Comment by bencroker** [comment]
Hmm, I'm not sure why that is. Looking at the job data, it looks like you may be using [source tags](https://putyourlightson.com/plugins/blitz#source-tags) to clear multiple sections in one go, is that the case and is it intentional?

**Comment by tyssen** [comment]
Yes and yes. The site is a reviews site with lots of different sections and categories. Each one has its own listing page with a single source tag for section or group. 

The home page is a conglomeration of all those listing pages but only shows a small number of the most recent entries from each.

**Comment by bencroker** [comment]
Are the memory limit and max execution time sufficiently large? See https://putyourlightson.com/plugins/blitz#the-refresh-cache-queue-job-is-stalling

**Comment by tyssen** [comment]
`max_execution_time` was already at 300 but `memory_limit` was 256 so I've increased it now. Will see how that goes.

**Comment by tyssen** [comment]
I increased the `memory_limit` to 1024 but the jobs are still mounting up. Do I need to increase it any further or should 1024 be sufficient in most cases?

**Comment by bencroker** [comment]
1024 should be sufficient. Have you tried disabling Async Queue as per my previous suggestion? I'm pretty sure this is some sort of configuration issue, as I'm not getting other reports of such behaviour.

**Comment by tyssen** [comment]
Yes, it's already disabled.

**Comment by bencroker** [comment]
Ok, in that case I'm running out of suggestions. Are you able to identify what action might be triggering the queue job that is stuck, based on the source IDs?

Can you try running the `Refresh Expired Cache` utility under _Utilities_ → _Blitz Cache_?

And finally, check the `blitz_elementexpirydates` database table, as well as the `blitz_caches` table for rows where the `expiryDate` is not null.

**Comment by tyssen** [comment]
Looking at the cron jobs that have been set up, there's also `resave/entries --limit=20` which is set to run every 15 minutes which matches up with the timestamps on the pending jobs, and each job also has 20 elements it's trying to refresh.

That cron job was set up because we were finding that future-dated entries weren't forcing a cache refresh on the home page when they were eventually published unless the entry was resaved again after its publishing date had passed.

**Comment by bencroker** [comment]
Ok, well there's the culprit, although I'm not sure as to why it is causing those pending jobs. I'd suggest removing the `resave/entries` cron job and let Blitz do its thing. If some page is not refreshing as expected then please create a new issue, providing details.

**Comment by tyssen** [comment]
I removed the cron job and it did indeed solve the problem with the pending jobs building up. But eventually, the original problem returned which related to future-dated entries. 

They weren't being displayed on the home page when their publish date arrived until they were resaved, which is why the cron job was set up in the first place.

Is there a better way to have future-dated entries clear the cache for listing pages when their final publish date arrives?

**Comment by bencroker** [comment]
That is what the `blitz/cache/refresh-expired` command is for. A cron job to execute it every 10 minutes should do the trick!

**Comment by tyssen** [comment]
We've already got one of those in place although it was set to run at 5 minutes past the hour, so I've updated it to run every 10 minutes now instead.

**Comment by bencroker** [comment]
Sounds good.

**Comment by tyssen** [comment]
After a bit of time to see how this was working, the `refresh-expired` cron job is clearing a listing page that has a source tag for a single category for future-dated entries, but not for the site's home page which has source tags for a number of sections and categories (including the same source tag for the listing page that does clear successfully).

**Comment by bencroker** [comment]
The home page will only be refreshed if an entry/category in one of its tagged sources is modified. It will _not_ be refreshed just because another page that has a tagged source in common is modified. Make sense?

**Comment by tyssen** [comment]
Yes, that's what I mean, but maybe didn't explain it very well. 

The site has a series of category listing pages that list say 20 articles each, paginated. And then the home page has a smaller section for each of those categories with only the first five from each category.

So if an article in a particular category that is future-dated goes live, the category listing page is updated, but the section corresponding to that category on the home page doesn't.

This only happens for future-dated entries though. If you create a new entry and publish it immediately or make edits to it, the changes show up on both the category listing and home pages.

**Comment by bencroker** [comment]
So it's acting like a bug for one page, but not for another? I'd suggest you look at the `blitz_cachetags` table (linked to the `blitz_caches` table) and double check that the source tags are present for the home page.

**Comment by tyssen** [comment]
If you mean that every value that appears in the `tag` column is included in the home page template, then yes, they are.

**Comment by bencroker** [comment]
In that case I don't see any reason for this not to work...
