### ISSUE TITLE
Defining @webroot changes cache path

### ISSUE THREAD

**Issue by emmaswann** [putyourlightson/craft-blitz#359]
When I attempt to define @webroot in config/general.php, the path to the cached files breaks, e.g. setting it as
`/www/public_html/public`
makes what would be 
`/storage/[username]/www/public_html/public/cache/blitz/[domain]`
become
`/storage/[username]/www/public_html/public/www/public_html/public/cache/blitz/[domain]`
Any ideas how I can have @webroot defined to avoid other issues, and still avoid this? Or have I got some settings elsewhere I can check in case they're what are doubling up?

**Comment by bencroker** [comment]
What is `Folder Path` set to under `Cache Storage` in the plugin settings?

<img width="421" alt="Screenshot 2021-12-03 at 12 58 13" src="https://user-images.githubusercontent.com/57572400/144614531-7dfc0320-43bb-4581-bd5b-1f710f31bdae.png">

**Comment by emmaswann** [comment]
It's exactly as you've put there.

**Comment by bencroker** [comment]
In that case you can either set the value to the full folder path, `/storage/[username]/www/public_html/public/cache/blitz`, or set `@webroot` to `/storage/[username]/www/public_html/public`, which is more correct than `/www/public_html/public`.

**Comment by emmaswann** [comment]
I tried this, and it went and created a whole load more folders to bury the cache deep. The plugin knows @webroot is defined (and the path @webroot/blitz/cache finds exactly where that folder should sit), bit it's not in config.php, which tells me it's defined **somewhere** and the issue must not be with the plugin! 

Thank you for your help, though, much appreciated!

**Comment by bencroker** [comment]
Sure thing! 

For reference, here is how aliases work in Craft: https://craftcms.com/docs/3.x/config/#aliases
