### ISSUE TITLE
Query strings are no longer getting cached

### ISSUE THREAD

**Issue by wbrowar** [putyourlightson/craft-blitz#36]
It looks like 1.6.5 might not have fixed the query string issues. It looks like a URL with a query string is saving and retrieving the cache as if the URL didn't have the query string.

For example, if I got to `http://something.com/search?search=hello` it seems to be saving the cache as `http://something.com/search`. Then if I go to `http://something.com/search?search=hi+ben` it will retrieve the cache saved from `http://something.com/search?search=hello`. Going to `http://something.com/search` does the same.

**Comment by putyourlightson** [comment]
Can you please first clear the cache and then retest with 1.6.6?

**Comment by wbrowar** [comment]
Hey @putyourlightson sorry for not mentioning this, but I am on 1.6.6. I just cleared the cache and wiped Craft‘s cache and I‘m setting the same result.

**Comment by putyourlightson** [comment]
Hmm I'm not seeing this behaviour. Do you have the "Query String Caching" setting disabled?

**Comment by wbrowar** [comment]
Nope, I have that enabled.

I *am* using the apache snippet in an `.htaccess` file and my cache path is `cache/blitz`:

```
# Blitz cache rewrite
RewriteCond %{DOCUMENT_ROOT}/cache/blitz/%{HTTP_HOST}/%{REQUEST_URI}/%{QUERY_STRING}/index.html -s
RewriteCond %{REQUEST_METHOD} GET
RewriteRule .* /cache/blitz/%{HTTP_HOST}/%{REQUEST_URI}/%{QUERY_STRING}/index.html [L]
```

**Comment by putyourlightson** [comment]
Ok, so from the [docs](https://github.com/putyourlightson/craft-blitz#considerations):

> URIs with query strings will only be cached if the "Query String Caching Enabled" setting is enabled. If it is disabled then no caching of URIs with query strings (anything following a ? in a URI) will take place. If it is enabled then all URIs with query strings will be cached.

Is that clear? You'll need to disable the setting for it to work as expected...

**Comment by wbrowar** [comment]
Hmm okay, so that would mean that each of those search results pages would be ignored by Blitz if that's disabled, right? I think that's what I was misunderstanding. It seemed like they all got their own entry into the cache table before and it seemed like the update broke that, but maybe it was never working correctly for us (I didn't check those pages for the HTML comment to verify).

To cache my search results pages, I'm guessing I'll need to remove the query string altogether and find a way to get what would be the query string into the URI?

**Comment by putyourlightson** [comment]
Let me review this and get back to you.

**Comment by putyourlightson** [comment]
Ok, you were right, a change in 1.6.0 changed the behaviour of URIs with query strings. Can you try again with 1.6.7 https://github.com/putyourlightson/craft-blitz/commit/f93306cc065cd68db19a4ef44fb393ef20cb4cb3?

**Comment by wbrowar** [comment]
Yes! That seems to have done it. I've also cleared the cache and refreshed and it's working as expected.

Thanks for fixing it 😃

**Comment by putyourlightson** [comment]
Excellent, thanks for reporting it. Now you can supercharge your search results!!
