### ISSUE TITLE
CSRF issue with the CacheController

### ISSUE THREAD

**Issue by teekay** [putyourlightson/craft-blitz#360]
### Describe the bug
The CacheController has `$enableCsrfValidation = false`, yet when I invoke the URL `/actions/blitz/cache/clear?key=...`, I receive status `400` with message `Unable to verify your data submission.`

I was able to step-through the `actionClear()` to confirm that it actually executes successfully. The problem is likely here:

```php
    public function afterAction($action, $result)
    {
        // If front-end request, run the queue to ensure action is completed in full
        if (Craft::$app->getView()->templateMode == View::TEMPLATE_MODE_SITE) {
            Craft::$app->runAction('queue/run'); // <--- Exception thrown
        }

        return parent::afterAction($action, $result);
    }
```

I am a relative newbie when it comes to Craft. Is there a way to construct the `curl` call such that `afterAction` does not execute?

Thanks!

### Versions
- Plugin version: 3.11.0
- Craft version: 3.6.17

**Comment by bencroker** [comment]
Where exactly are you calling the action URL from? If you use a `GET` request then there shouldn't be any issue with CSRF.

**Comment by teekay** [comment]
We're calling it from a script that makes a `POST` request. We can get away with using `GET` for `cache/clear` but for `cache/refresh-uris`, I think we need `POST` since the list of URIs to clear might potentially get too long for a `GET` request.

**Comment by bencroker** [comment]
In that case you'd be better off running a console command, which does not require a CSRF token, see https://putyourlightson.com/plugins/blitz#console-commands

To clarify, the issue you're running into is with Craft, not Blitz.

**Comment by teekay** [comment]
@bencroker thank you. Yes, I figured this behavior was coming out of Craft. In your estimation, should we be concerned that the action `queue/run` fails to run in this scenario? What's supposed to happen there?

**Comment by bencroker** [comment]
There's nothing to be concerned about, it is expected behaviour since you are using a POST request, which requires a CSRF token. If you must use a web request the I would suggest splitting your large payload into smaller GET requests to avoid the issue.
