### ISSUE TITLE
craft.blitz.getUri returning action in absolute url

### ISSUE THREAD

**Issue by aaronlax** [putyourlightson/craft-blitz#361]
using the following 
`{{ craft.blitz.getUri('/store/headerCart', { showCart: true, cartItemCount: cartItemCount }) }}`

returns 

`<span class="blitz-inject" id="blitz-inject-3" data-blitz-id="3" data-blitz-uri="http://mylocalsite.com/actions/store/headerCart" data-blitz-params="showCart=1&amp;cartItemCount=1&amp;no-cache=1"></span>`

How can i return the url without action prepended?

**Comment by bencroker** [comment]
The URL requires the [actionTrigger](https://craftcms.com/docs/3.x/config/config-settings.html#actiontrigger) to be able to fetch the URI. Is there any particular reason for thinking that this is a bug?

**Comment by bencroker** [comment]
Thanks, fixed in https://github.com/putyourlightson/craft-blitz/commit/51fdb03b53f8a53353206a1740f04b0f6988e79e for the next release.

**Comment by bencroker** [comment]
Released in version 3.11.1.
