### ISSUE TITLE
Is Cloudflare cache purges when item is disabled or deleted

### ISSUE THREAD

**Issue by jripmeester** [putyourlightson/craft-blitz#363]
### Question
My client use Cloudflare reverse proxy caching and we got the purger installed. But they experience large delays on purges of pages when the entry is disabled. Is Blitz handling purging in that scenario?

### Additional context
We're using Blitz 3.10.7 on Craft CMS 3.6.17

**Comment by bencroker** [comment]
Yes, it should be. Please update to the latest version of Blitz, as version 3.11.0 added some improvements in this regard.
