### ISSUE TITLE
Geomate

### ISSUE THREAD

**Issue by xsinisa** [putyourlightson/craft-blitz#364]
Hi,

I am trying to use geomate to geolocate the city and use that info in template.

{% set city = craft.geomate.city() %}

As it is cached it is always the same city.
I tried to use Sprig:
{% set city =  sprig('_globals/geomateLocation') %}

Template content
{% set city = craft.geomate.city() %}

{% if craft.app.language == 'de' and city.raw.subdivisions is defined %}
    {{ city.raw.subdivisions[0].names.de }}
{% elseif craft.app.language[:2] == 'en' and city.raw.subdivisions is defined %}
   {{ city.raw.subdivisions[0].names.en }}
{% elseif city.raw.subdivisions is defined %}
    {{ city.raw.subdivisions[0].names.en }}
{% endif %}

Even with Sprig it is always "the same city" no matter the real location, so basically it is cached.

What I am doing wrong? Please  help.
How to exclude that variable from caching?

**Comment by bencroker** [comment]
The first thing to verify is whether the Sprig component is rendered dynamically. Can you test if the time is refreshed each time you load this component?

```twig
{{ now|datetime }}
```

**Comment by xsinisa** [comment]
@bencroker it is not rendered dynamicly

**Comment by bencroker** [comment]
So that's where you should start troubleshooting. Try clearing the cache and seeing if that helps?

**Comment by bencroker** [comment]
Did you make any progress on this @xsinisa?

**Comment by xsinisa** [comment]
Hi @bencroker sorry for not letting you know earlier. 
I managed to solve the problem, it was not refreshing so at the end I added:
{{ sprig.script }}
and trigger this when needed to refresh 
    htmx.trigger('#search-component', 'refresh'));

Maybe Its only me, but on the first look at the docs I didnt realise that it is required to use in order to work properly.

**Comment by bencroker** [comment]
Ok, FYI adding `{{ sprig.script }}` is one of the first steps mentioned in https://putyourlightson.com/plugins/sprig#how-it-works
