### ISSUE TITLE
Lagging/Stalling when using YiiCacheStorage Driver

### ISSUE THREAD

**Issue by bymayo** [putyourlightson/craft-blitz#366]
When an entry is saved the Blitz Refresh Cache task is created but as soon as it starts running it's extremely slow to the point that it lags the server and the site is unresponsive on the front and back end.

I'm using the YiiCacheStorage Driver as i'm hosting on Servd.

I've noticed in the past that this can happen if images are being transformed whilst warming, but this isn't the case.

My `blitz.php` config file is:

```
return [
    '*' => [
        'cachingEnabled' => false,
        'includedUriPatterns' => [
            [
                'uriPattern' => '.*',
            ]
        ],
        'excludedUriPatterns' => [
            ['uriPattern' => 'dynamic/form']
        ],
        'cacheStorageType' => 'putyourlightson\blitz\drivers\storage\YiiCacheStorage',
        'clearCacheAutomatically' => true,
        'warmCacheAutomatically' => true,
        'refreshCacheAutomaticallyForGlobals' => true,
        'queryStringCaching' => 1
    ],
    'production' => [
        'cachingEnabled' => true
    ]
];
```

### Versions
- Plugin version: 3.11.1
- Craft version: 3.7.27.2

**Comment by bencroker** [comment]
Have you identified whether it is the cache clearing or cache warming process that is slow? If it is the latter, then how many pages are warmed and approximately how long is each page taking to be warmed? You can open the queue job details page in the CP to try and get an idea of where the bottleneck is.

**Comment by bymayo** [comment]
It's when the `Warming Blitz Cache` runs and currently, it's only warming 45 pages. 

I can't get to the task to view it because the site just endlessly spins until this task has finished.

I'm wondering now if it's a bit of logic I've got in there that's taking Blitz a while to warm each page. But surely this shouldn't lag the CP and the whole site until this task is complete?

**Comment by bencroker** [comment]
No, it shouldn't. Is this happening on a production server or only in a local testing environment?

**Comment by bymayo** [comment]
Production, using Servd.

I contacted them about it and they said to log an issue with you as it looks like an issue with the YiiCache driver.

(I could put this on staging if you want to look btw)

**Comment by bencroker** [comment]
If you warm a single page using the Blitz cache utility, how long does the queue job take?

**Comment by bencroker** [comment]
Closing due to no response.
