### ISSUE TITLE
Do tagged pages have to be refreshed by a cronjob?

### ISSUE THREAD

**Issue by andreasbecker** [putyourlightson/craft-blitz#367]
We have a multi-site where the homepage shows the newest articles. That page has the source tag `{% do craft.blitz.options.tags('sectionId:11') %}`

We also have a cronjob for refreshing the tagged pages every minute. 
`* * * * * blitz/cache/refresh-tagged sectionId:11`

Is this cronjob needed at all or are pages automatically refreshed if they have that source tag?

`cacheElementQueries` is set to `false`

**Comment by bencroker** [comment]
That cron job wouldn't normally be required, as Blitz can detect changes to entries listed in other pages. However, since you have `cacheElementQueries` set to `false`, that won't happen. Is there any specific reason you've disabled this feature?

**Comment by andreasbecker** [comment]
We have a very large multi-site (12 sites) with over 200,000 entries in total and had the issue that you described [here](https://putyourlightson.com/plugins/blitz#the-refresh-cache-queue-jobs-run-for-long-periods-of-time-and-sometimes-pile-up). From that text it wasn't clear to me, if we have to refresh the tagged pages manually/by cronjob.

**Comment by bencroker** [comment]
Oh I see what you mean now. The cached homepage should be refreshed automatically any time an entry in the section with ID `11` is modified, as explained at https://putyourlightson.com/plugins/blitz#source-tags

**Comment by andreasbecker** [comment]
Ok, so I can delete that cronjob although `cacheElementQueries` is set to `false`?

**Comment by bencroker** [comment]
That's correct.

**Comment by andreasbecker** [comment]
Last question: would that still be true if `clearCacheAutomatically` was set to `false`?

**Comment by bencroker** [comment]
No, if `clearCacheAutomatically` is set to `false` then cached pages are not immediately cleared. Instead, they are marked as expired and cleared the next time the expired cache is refreshed using the `blitz/cache/refresh-expired` command.
