### ISSUE TITLE
Lazy load dynamic content

### ISSUE THREAD

**Issue by pgrzyb** [putyourlightson/craft-blitz#368]
Hi guys, 

On one of our sites, we use AdWizard for ad handling, and since those ads can't be cached, we load them using getTemplate() (https://putyourlightson.com/plugins/blitz#craft.blitz.gettemplatetemplate-name-params).

One thing that we are missing to make this work perfectly is the ability to lazy load those ads so that advertisers wouldn't be charged for views of ads that are below the fold and are never actually viewed. I was thinking I could hook into the JS events triggered by blitz, but I couldn't come up with a way to prevent the load until the ad gets into the viewport.

Would you be able to suggest a solution for this or at least point me in the right direction? I would very much appreciate it!

Thanks!

**Comment by bencroker** [comment]
Sprig (a free plugin) can handle this use-case, which is demonstrated in this livestream: 
https://craftquest.io/livestreams/dynamic-content-on-statically-cached-pages
