### ISSUE TITLE
Problems using Blitz when the site url contains invalid characters for a folder

### ISSUE THREAD

**Issue by goraxan** [putyourlightson/craft-blitz#369]
### Describe the bug
If the site base URL contains invalid characters for a folder, Blitz doesn't work, causing the following error on page refresh.

### To reproduce
Configure a site with invalid characters for a folder, like ':' (in Windows) using a non-standard port. In my case the base URL es http://localhost:8080, therefore the folder that Blitz tries to create to store the cached pages is "localhost:8080".

Enable blitz (using defaults), and refresh any cached page. You'll get this error:
Next yii\base\Exception: Failed to create directory "xxxxxxx\public\cache\blitz\localhost:8080": mkdir(): Not a directory in xxxxxxx\vendor\yiisoft\yii2\helpers\BaseFileHelper.php:642
Stack trace:
#0 xxxxxxx\vendor\craftcms\cms\src\helpers\FileHelper.php(84): yii\helpers\BaseFileHelper::createDirectory('xxxxxxx', 509, true)
#1 xxxxxxx\vendor\craftcms\cms\src\helpers\FileHelper.php(350): craft\helpers\FileHelper::createDirectory('xxxxxxx')
#2 xxxxxxx\vendor\putyourlightson\craft-blitz\src\drivers\storage\FileStorage.php(121): craft\helpers\FileHelper::writeToFile('xxxxxxx', '<!DOCTYPE html>...')
#3 xxxxxxx\vendor\putyourlightson\craft-blitz\src\services\GenerateCacheService.php(366): putyourlightson\blitz\drivers\storage\FileStorage->save('<!DOCTYPE html>...', Object(putyourlightson\blitz\models\SiteUriModel), NULL)
#4 xxxxxxx\vendor\putyourlightson\craft-blitz\src\services\GenerateCacheService.php(337): putyourlightson\blitz\services\GenerateCacheService->saveOutput('<!DOCTYPE html>...', Object(putyourlightson\blitz\models\SiteUriModel), NULL)
#5 xxxxxxx\vendor\putyourlightson\craft-blitz\src\Blitz.php(261): putyourlightson\blitz\services\GenerateCacheService->save('<!DOCTYPE html>...', Object(putyourlightson\blitz\models\SiteUriModel))
#6 [internal function]: putyourlightson\blitz\Blitz->putyourlightson\blitz\{closure}(Object(craft\events\TemplateEvent))
#7 xxxxxxx\vendor\yiisoft\yii2\base\Event.php(312): call_user_func(Object(Closure), Object(craft\events\TemplateEvent))
#8 xxxxxxx\vendor\yiisoft\yii2\base\Component.php(637): yii\base\Event::trigger('craft\\web\\View', 'afterRenderPage...', Object(craft\events\TemplateEvent))
#9 xxxxxxx\vendor\craftcms\cms\src\web\View.php(1810): yii\base\Component->trigger('afterRenderPage...', Object(craft\events\TemplateEvent))
#10 xxxxxxx\vendor\craftcms\cms\src\web\View.php(469): craft\web\View->afterRenderPageTemplate('_pages\\home', Array, 'site', '<span class="st...')
#11 xxxxxxx\vendor\craftcms\cms\src\web\Controller.php(201): craft\web\View->renderPageTemplate('_pages\\home', '[<span class="s...', '<span class="st...')
#12 xxxxxxx\vendor\craftcms\cms\src\controllers\TemplatesController.php(102): craft\web\Controller->renderTemplate('_pages\\home', Array)
#13 [internal function]: craft\controllers\TemplatesController->actionRender('_pages\\home', Array)
#14 xxxxxxx\vendor\yiisoft\yii2\base\InlineAction.php(57): call_user_func_array(Array, Array)
#15 xxxxxxx\vendor\yiisoft\yii2\base\Controller.php(181): yii\base\InlineAction->runWithParams(Array)
#16 xxxxxxx\vendor\yiisoft\yii2\base\Module.php(534): yii\base\Controller->runAction('render', Array)
#17 xxxxxxx\vendor\craftcms\cms\src\web\Application.php(287): yii\base\Module->runAction('templates/rende...', Array)
#18 xxxxxxx\vendor\yiisoft\yii2\web\Application.php(104): craft\web\Application->runAction('templates/rende...', Array)
#19 xxxxxxx\vendor\craftcms\cms\src\web\Application.php(272): yii\web\Application->handleRequest(Object(craft\web\Request))
#20 xxxxxxx\vendor\yiisoft\yii2\base\Application.php(392): craft\web\Application->handleRequest(Object(craft\web\Request))
#21 xxxxxxx\public\index.php(21): yii\base\Application->run()
#22 {main}

### Expected behaviour
Invalid characters should be removed from the folder name, which happens partially when you remove the protocol https://github.com/putyourlightson/craft-blitz/blob/develop/src/drivers/storage/FileStorage.php#L318

### Screenshots
![image](https://user-images.githubusercontent.com/8337784/151351108-508e2493-0877-4269-89f0-0a677da6efb3.png)

![error](https://user-images.githubusercontent.com/8337784/151351631-5bcc0622-93dd-4f9f-8653-038f9586a2cb.png)

### Versions
- Plugin version: 3.11.1
- Craft version: 3.7.21

**Comment by bencroker** [comment]
Thanks, fixed in https://github.com/putyourlightson/craft-blitz/commit/5d6fdc762431e3dec186a090d0b3e0cfd42a8a47 for the next release.

**Comment by bencroker** [comment]
Released in version 3.11.2.
