### ISSUE TITLE
Does Blitz work with multiple deamons handling the Craft queue?

### ISSUE THREAD

**Issue by naboo** [putyourlightson/craft-blitz#371]
### Question
We are seeing some issues on a couple of Craft sites when running the queue through multiple deamons on the server instead of the default execution through the CP. 

For example: 
We have a site with 2 deamons handling the queue. When we setup a `blitz/warm` CLI command through cron to warm the cache every fourth (4) hour for 1 concurrent URL the `craft` PHP processes keep adding up on the server until the CPU reaches 100%. 

It's like the queue doesn't understand to warm the cache 1 URL at a time and keep starting new processes which never stops.

Could this be the case?

**Comment by bencroker** [comment]
The `blitz/cache/warm` command adds a queue job _and_ runs it, which is likely causing a race condition with your daemons. You can prevent the job from being run using the `--queue` flag.

```shell
./craft blitz/cache/warm --queue=1
```

**Comment by naboo** [comment]
Will try this and see what type of result we get!

**Comment by bencroker** [comment]
Any update on this @naboo?

**Comment by bencroker** [comment]
Closing due to lack of a response.
