### ISSUE TITLE
Exclude page from cache from any element

### ISSUE THREAD

**Issue by bymayo** [putyourlightson/craft-blitz#372]
It would be nice to be able to exclude an entry/category etc from cache, via a field or option in that particular element.

A use case for this is that Settings aren't accessible by CMS admins, and we can't trust them using the `excludedUriPatterns` correctly.

We had a weird situation recently where Freeform multipage forms (Without Ajax) won't work with Blitz, even with the hack around for CSRF tokens. So optionally being able to exclude these multipage form entries from the cache would be great.

**Comment by bencroker** [comment]
You can already do this in your templates.

```twig
{% if entry.excludeFromCache %}
    {% do craft.blitz.options.cachingEnabled(false) %}
{% endif %}
```

See https://putyourlightson.com/plugins/blitz#page-specific-options
