### ISSUE TITLE
Bypass GET action

### ISSUE THREAD

**Issue by SamLNL** [putyourlightson/craft-blitz#374]
### Question
How can I bypass GET actions?

### Additional context
I'm using Blitz with Cloudflare for caching pages. 
Caching level in Cloudfare is set to: `Cache Everything, Origin Cache Control: On`.
At some pages I use Sproutforms with the Blitz csrf input (https://sprout.barrelstrengthdesign.com/docs/forms/caching-and-csrf-tokens.html).

It seems that the action for retrieving this csrf token (https://website.com/actions/blitz/csrf/json) is cached by Cloudflare. This results to Sproutforms giving me 400-error after the second time I fill in the form.
`cf-cache-status` in the network tab is showing 'HIT'.

![Screenshot at Feb 15 13-48-40](https://user-images.githubusercontent.com/21331474/154065260-dd532578-e925-4eb2-9f64-c200174bfe87.png)

I tried adding the following in my blitz.php config file, so Cloudflare will BYPASS the action `actions/blitz/csrf/json`.

```
'excludedUriPatterns' => [
           [
               'siteId' => '',
               'uriPattern' => '^actions\/.*$',
           ]
        ],
```

But with no luck.
How can I make Cloudflare to BYPASS the request instead of caching it?

**Comment by bencroker** [comment]
Action requests are never cached by Blitz, as per this line: https://github.com/putyourlightson/craft-blitz/blob/5d6fdc762431e3dec186a090d0b3e0cfd42a8a47/src/services/CacheRequestService.php#L71

Something else must be going on here.

**Comment by SamLNL** [comment]
Hmm I think I fixed my problem.
I enabled `Server Side Excludes: On` in Cloudflare.
It seems like a odd fix to me. But yeah... it fixes my problem.

**Comment by bencroker** [comment]
I've never had to do that, but good to know that it solved your issue!
