### ISSUE TITLE
Shell deployment when entries are created / updated

### ISSUE THREAD

**Issue by wuhhh** [putyourlightson/craft-blitz#375]
### Question
Hi, I'm looking for some clarity on remote deployment of new/updated entries using the shell deployer. Is there a way to deploy only those files which have changed? I guess it would be necessary to write this into the shell script, checking against date modified or something along those lines? If that's the only way with the shell deployer, is it recommended to use another deployer if it's necessary to avoid deploying the whole site any time one entry changes? I feel like I'm missing something here.

**Comment by bencroker** [comment]
Since you can add any commands you want, it would be possible to only copy modified files. Copying files is generally a fast operation, so I probably wouldn't bother with it, but if you want to deploy as little as possible then I'd recommend using the built-in Git deployer.
