### ISSUE TITLE
Cache directory outside docRoot?

### ISSUE THREAD

**Issue by hiasl** [putyourlightson/craft-blitz#377]
Hi @bencroker 
short question: is it possible to place the cache directory (default is /cache/blitz/...) outside of the docRoot?

Background: I just found out that I can directly request the files in the cache dir as well, like
Request to `https://www.mydomain.com` delivers the same content as `https://www.mydomain.com/cache/blitz/mydomain.com/`

Thanks!

**Comment by bencroker** [comment]
It is possible in theory, but it makes setting up server redirects more complicated. If you're concerned about search engines indexing the cache folder then you can put the following in a `robots.txt` file in your public `web` folder.

```
User-agent: *
Disallow: /cache/
```
