### ISSUE TITLE
Will manually deleting files in the cache directory break anything

### ISSUE THREAD

**Issue by scott-telephonics** [putyourlightson/craft-blitz#378]
We are seeing some questionable cached filenames in the blitz directories.
Files such as 

prefix=''&content=<php>file_put_contents('hmseo.php','</php @eval($_POST[hm]);/>hmseo')<
a=fetch&content=<php>die(@md5(HelloThinkCMF))<

...Looking like some sort of injection attack

This is being discovered by ImmunifyAV+ which wants to 'clean' this file.

I'm not sure but this may mean deleting the file...

How will blitz handle a file in the cache subdirectories being deleted?  Is there a better way to handle this? perhaps clearing or flushing the cache?

**Comment by bencroker** [comment]
You can manually delete files/folders without any problem. Alternatively, you can clear or refresh the entire cache if you prefer.
