### ISSUE TITLE
cache not getting cleared when an entry is updated

### ISSUE THREAD

**Issue by revanthchallagundla** [putyourlightson/craft-blitz#379]
### Describe the bug
Cache is not getting cleared when an entry is updated in craft version 3.7.34 and blitz version 311.1.

### To reproduce
Steps to reproduce the behaviour:

### Expected behaviour
As per https://putyourlightson.com support the cache should be updated when entry is updated.

The cached page should be cleared when the entry is modified and published live, is that not the case? You can take a look at common issues at https://putyourlightson.com/plugins/blitz#common-issues and https://github.com/putyourlightson/craft-blitz/issues, and if you can provide more details (ideally via GitHub issues) then I'll try to help troubleshoot.

### Versions
- Plugin version: 3.11.1
- Craft version: 3.7.34

**Comment by bencroker** [comment]
Can you describe how the template is set up or, better yet, test with the simplest use-case, for example:

```twig
{{ craft.entries.one.title }}
```
