### ISSUE TITLE
Make mapping the smart cache table more efficient

### ISSUE THREAD

**Issue by wbrowar** [putyourlightson/craft-blitz#38]
Hi Ben, I have a store location page that loads 250+ locations and through my best efforts—when Blitz is disabled—I've got it down to 57 DB queries (most of which are unrelated to the location entries).

I want Blitz to associate these entries with this page so that when one entry is updated this page will be re-cached upon cache warming, so I am not using any `{% cache %}` tags. Unfortunately what I'm seeing is that as Blitz does all of its magic to check and associate the entries in the cache tables, it winds up adding about 1,000+ queries upon first load and the process stalls the site for about 2 minutes. Also, it seems that when I try to manually warm the cache and then visit that URI, the page doesn't seemed to be cached (is there a way to specify that a page is warmed? I've tried adding it to the URI patterns, and that didn't seem to affect this situation).

I'm hoping to find my own solution to this problem of stalling the site, but I wonder if there are other ways to solve this. Here's what I'm thinking:

- Tweak server settings to make this page load faster that doesn't mess with the performance of the rest of the site
  - The downside here is that this situation only occurs when this page's Blitz cache has been invalidated, so I wonder if it's a good idea to make a lot of server adjustments for a situation that doesn't happen more than once a week or so
- Maybe see if Craft or Yii has a way to help solve this
  - From what I can tell the extra load time is due to all of the DB queries, so maybe starting there might help?

If I can't figure it out, here is a feature request to solve this within the plugin:
- Add a way to Blitz to manually populate the smart cache table
  - Maybe we could find a way to disable Blitz's method of associating entries with a URI then provide a Twig (or PHP) way to submit a list of all of the IDs associated with the content that Blitz would have figured out on its own
- Could Blitz offload the check and insert of the ID into a background task?
  - I haven't dug into if it's even possible to run a background task from the front-end, but I assume it's possible
  - This might cause its own issues, but it could at least let the user access the page even if Blitz isn't done doing its thing

Once the page is cached by Blitz it works perfectly, but I can see similar situations like this popping up in other projects that we'd like to use Blitz for.

Thanks,
Will

**Comment by putyourlightson** [comment]
Hey Will, I haven't come across a situation where a page that requires 57 queries would result in such a slow page load just because of Blitz. It also doesn't make sense to me why once cached, warming the cache would not result in the page being recached. I'd like to take a look at the site if that's possible, so perhaps you can chat me on slack or send me an email?

**Comment by putyourlightson** [comment]
This was solved by making optimisations to the template, feel free to comment if there's something helpful to note.
