### ISSUE TITLE
Home page and listing pages not caching

### ISSUE THREAD

**Issue by russback** [putyourlightson/craft-blitz#382]
### Question
I am getting Blitz working fine with individual entry pages, but not with the home page or listing pages. Can you see any issue with this set up?

Config when testing the homepage:

```
return [
	// All environments
	'*' => [
		'cachingEnabled' => getenv('BLITZ_CACHE'), // this is set to 1 in the env file, devMode is off and I am not logged in
		'cacheFolderPath' => '@webroot/cache/blitz',
		'refreshCacheAutomaticallyForGlobals' => true,
		'clearCacheAutomatically' => true,
		'warmCacheAutomatically' => true,
		'includedUriPatterns' => [[
			'uriPattern' => ''
		]]
	]
];
```

Console output:

```
./craft blitz/cache/warm
Warming Blitz cache...
[================================================================================] 100% (0/0) ETA: n/a
Blitz cache warming complete.
```

Config when testing a section (the listing page is at `/opinion` and is paginated, entries are at `/opinion/article/{slug}`. Only the entries are being cached:

```
return [
	// All environments
	'*' => [
		'cachingEnabled' => getenv('BLITZ_CACHE'),
		'cacheFolderPath' => '@webroot/cache/blitz',
		'refreshCacheAutomaticallyForGlobals' => true,
		'clearCacheAutomatically' => true,
		'warmCacheAutomatically' => true,
		'includedUriPatterns' => [[
			'uriPattern' => 'opinion'
		]]
	]
];
```

Console output:

```
./craft blitz/cache/warm
Warming Blitz cache...
[=========================================================================] 100% (517/517) ETA: 2 sec.
Blitz cache warming complete.
```

For the listing pages where there is pagination, the following is in place:

```
{% paginate query.limit(10) as pageInfo, entries %}
{% do craft.blitz.options.paginate(pageInfo.totalPages) %}
```

For the home page, there is no pagination.

### Additional context
This is on Blitz version 3.11.1

**Comment by bencroker** [comment]
Have you tried enabling the [debug](https://putyourlightson.com/plugins/blitz#debugging) config setting?

Also be sure to read the common issues at https://putyourlightson.com/plugins/blitz#common-issues
