### ISSUE TITLE
Section Source Tags not clearing on Entry Creation

### ISSUE THREAD

**Issue by TraffordFewster** [putyourlightson/craft-blitz#383]
### Describe the bug
When creating an entry in a section its not clearing the cache on templates tagged with sectionId [source tags](https://putyourlightson.com/plugins/blitz#source-tags), it works fine with updates and deletes but wont clear on creation.

### To reproduce
Steps to reproduce the behaviour:
1. Add a source tag to a template like `{% do craft.blitz.options.tags('sectionId:1') %}`
2. Create an entry in the relevant section.
3. Notice it didn't clear the cache

### Expected behaviour
It to clear the cache for pages that are tagged with the relevant sectionId when an entry is created.

### Versions
- Plugin version: 3.11.1
- Craft version: 3.7.35

**Comment by bencroker** [comment]
I just tested locally and this is working as expected. Can you please double check this with a template that contains only this line, using a section ID that exists?

```twig
{% do craft.blitz.options.tags('sectionId:1') %}
```

**Comment by TraffordFewster** [comment]
Ah yes testing it with just the tagging alone does seem to work as intended so I dug a bit deeper into our templates and found the issue seems to be when you are tagging something and then including a different template file that tags something somewhere else so new steps to reproduce would be:

1. Add a source tag to a template like {% do craft.blitz.options.tags('sectionId:1') %}
2. Create another template and tag a different section in that.
3. Include that other template in the first template.
4. Create an entry in the first templates relevant section.
5. Notice it didn't clear the cache

**Comment by bencroker** [comment]
Yeah, so the second time you set the tags will override the first time. You should be able to get around this by merging new tags with existing tags.

```twig
{% do craft.blitz.options.tags(craft.blitz.options.tags|merge(['sectionId:1'])) %}
```
