### ISSUE TITLE
Cached pages cannot be password-protected via Knock-Knock et al

### ISSUE THREAD

**Issue by jannisborgers** [putyourlightson/craft-blitz#385]
I think this isn't technically a bug, but the way this plugin works, sparing visitors the server and database requests… still I wonder if this can be achieved in some way that doesn’t include manually setting password protection on the server.

### Describe the bug
As soon as Blitz does its magic, pages are saved as static index.html pages in a folder structure based on the sections and entries in the project. As soon as an entry has been cached, it isn't protected by Knock-Knock anymore. We noticed this when our site’s staging server, which uses both Blitz for testing and Knock-Knock for obvious reasons, was public-facing, but only for entries that had been cached by Blitz.

### To reproduce
Steps to reproduce the behaviour:
1. Enable Blitz
2. Enable Knock-Knock and set a password
3. Visit cached pages
4. Pages are accessible publicly

### Expected behaviour
Cached pages should still be password-protected

### Versions
- Blitz version: 3.11.1 (with Server rewrites)
- Knock-Knock version: 1.2.16
- Craft version: 3.6.17

**Comment by bencroker** [comment]
Since the Knock Knock plugin requires Craft to be bootstrapped on every request, it will not work with server rewrites, which prevent requests from ever reaching Craft. To get around this, you can either disable server rewrites or exclude URIs that should be password protected from being cached.

**Comment by jannisborgers** [comment]
Thanks Ben, I thought as much. I’ll disable server rewrites or leave the additional server password in place for our staging server.

**Comment by jannisborgers** [comment]
@bencroker As a follow-up on this topic, I noticed that the `X-Robots-Tag: none` Header that is sent by Craft when you set the `disallowRobots` config setting to `true` is not sent by entries served by Blitz. At first I thought it was the server rewrites again, but the header is also missing from requests that are served by the Blitz plugin (as indicated by the `Served by` HTML-comment at the bottom of the source). 

Is this by design? I saw [this issue](https://github.com/putyourlightson/craft-blitz/issues/239) describing something similar, but adding a robots.txt is something I would like to avoid due to our dev/staging/production setup and deployment process.

**Comment by bencroker** [comment]
Sounds like an unrelated issue that I'll address separately.

**Comment by bencroker** [comment]
Fixed the missing headers added by Craft in https://github.com/putyourlightson/craft-blitz/commit/67c712aeb58209b26650cf6bcc775d36b4a4e92b for the next release.

**Comment by jannisborgers** [comment]
Thanks, Ben!
