### ISSUE TITLE
Event for refreshing by tags?

### ISSUE THREAD

**Issue by yiska** [putyourlightson/craft-blitz#386]
Hey Blitz team,

I was hoping to find an event I could hook into for refreshing the Blitz cache by tag. Mind if I make a PR following the pattern used for the refreshCacheUris to pass along specific tags in the event? I'm going to start adding this code because I think it's pretty straightforward. ;)

Thanks!
Jessica

**Comment by bencroker** [comment]
Thanks for the PR! I tweaked it in https://github.com/putyourlightson/craft-blitz/commit/b742e25df403a4c8932751035e910c16a0f1839e so that tags can be modified by the event and have merged for the next release.
