### ISSUE TITLE
Query String Caching: Please document "includedQueryStringParams".

### ISSUE THREAD

**Issue by outline4** [putyourlightson/craft-blitz#389]
Hi

Please update the docs of [Query String Caching](https://putyourlightson.com/plugins/blitz#query-string-caching) to reflect what you can do within the config file!

It's a huge plus to be able to specify which query strings should be cached.

        'queryStringCaching' => 1,

        // The query string parameters to include when determining if and how a page should be cached (regular expressions may be used).
        'includedQueryStringParams' => ['category', 'return', 'month', 'year', 'day', 'country', 'code'],
 
This changes all and it's not even in the docs （◎ ｡ ◎）

Cheers  
Stefan

**Comment by bencroker** [comment]
Added under https://putyourlightson.com/plugins/blitz#query-string-cachings, thanks!
