### ISSUE TITLE
Adding needless jobs to the queue

### ISSUE THREAD

**Issue by gixxy22** [putyourlightson/craft-blitz#390]
When updating or deleting entries, blitz fires a job in the queue even though the entries have not been marked to cache.

I can mark 1 entry to cache in "included URL patterns", update 50k entries and Blitz will fire 50k jobs in the queue even though only 1 need to be sent.

This causes issues when waiting for all the jobs to complete, delaying other jobs.

**Comment by bencroker** [comment]
There is an important distinction to make between entries and pages (URL patterns). An entry can, in theory, be populated on _any_ page with _any_ URL. Say you had a single page on a site that happened to list the title of every single entry in the site. Then any time any entry is updated, that page's cache would need to be cleared. 

So the behaviour you are describing, of updating 50k entries, should indeed result in 50k refresh jobs being queued up. If you are updating all of the entries in a single request via a module/plugin (in batch), then you can enable `batchMode`, which forces Blitz to wait until the refresh method is manually called until it refreshes the cache (https://putyourlightson.com/plugins/blitz#integrations).
