### ISSUE TITLE
How do we handle future entries or expired ones?

### ISSUE THREAD

**Issue by outline4** [putyourlightson/craft-blitz#391]
### Asking for a client ;)

A client of mine has a news section that he has to coordonate with other social media entries.  
A lot of news are time critical. They have to appear at the same minute on multiple platforms.  
Now a lot of these News are set to future dates and he somehow complains that these news only appear about 10 minutes later. 

So my question is:   
How exactly do we handle future dates or expired dates with blitz?  

I haven't found anything in the docs.  
Thanks in advance!  
Stefan

**Comment by bencroker** [comment]
Do you have a cron job set up to refresh expired cache? You can send this to run every minute, to ensure that content is live to-the minute. See https://putyourlightson.com/plugins/blitz#cron-jobs
