### ISSUE TITLE
Allow caching of non-GET requests

### ISSUE THREAD

**Issue by nickdunn** [putyourlightson/craft-blitz#392]
I recently had a site suffer from a malicious attack whereby a bot was sending a large number of POST requests to the site. Blitz ignores these as un-cacheable, which meant the server was brought to its knees pretty quickly. Is there any trick to allowing Blitz to cache non-GET requests too?

Edit: should be a question or feature request, not a bug.

**Comment by bencroker** [comment]
A POST request is generally a request to the server to take some action, so it makes no sense to cache it. POST requests are also protected from CSRF in Craft, so there is extra security attached to them. It sounds like you are asking about DDoS protection, which Blitz does _not_ provide. For that I'd recommend looking into [Cloudflare](https://www.cloudflare.com/en-gb/ddos/) or the numerous other solutions out there.
