### ISSUE TITLE
How can I debug a huge craft_blitz_elementcaches table?

### ISSUE THREAD

**Issue by mdunbavan** [putyourlightson/craft-blitz#393]
### Question
I would like to know the best way to debug what is making the `craft_blitz_elementcaches` table to be so huge?

### Additional context

I have looked at the ids for the elements and they all match to actual elements but I wanted to dig further. Would there be a better approach to looking into this?

Currently settings for what should be cached are global in the plugin settings and some in templates but I wondered if it so go even granular to help debug it better?

**Comment by bencroker** [comment]
I'd start by refreshing the entire cache, to ensure that old references are either regenerated or dropped. Then, running the following SQL query on your database should help you identify the pages containing the most references to elements.

```sql
SELECT cacheId, uri, count(*) as count FROM blitz_elementcaches JOIN blitz_caches ON cacheId = id GROUP BY cacheId ORDER BY count DESC
```

You can then investigate the top results and look into why those pages reference so many elements.

**Comment by mdunbavan** [comment]
I think I may have got to the bottom of it.

In the returned results from the above, it looks like it is also adding the paginated results in it too.

```
224887	products/storage/small-storage-furniture/p4	950
224925	products/storage/small-storage-furniture/p5	950
224987	products/lounge-seating/chaises-benches-daybeds/p20	950
215552	products/storage/small-storage-furniture/p13	949
215559	products/storage/small-storage-furniture/p16	949
177588	products/tables-desks/coffee-side-tables	949
192909	products/storage/small-storage-furniture/p32	949
176147	brands/andtradition	947
186345	products/lighting/pendant-suspension-lighting/p2	947
215572	products/storage/small-storage-furniture/p26	946
224999	products/lounge-seating/chaises-benches-daybeds/p26	944
225021	products/lounge-seating/chaises-benches-daybeds/p32	943
190186	products/lounge-seating/p3	943
215573	products/storage/small-storage-furniture/p25	942
```

Is there anyway that I can mitigate this happening or do you think it should be happening?

**Comment by bencroker** [comment]
That shouldn't be happening. How many entries do you fetch per page and can you show me the pagination code you are using?

**Comment by mdunbavan** [comment]
```
{% set products = craft.products.relatedTo(category)
		.with([
		'mainImage',
		'variants',
		'productImages'
		])
		.id(['not']|merge(excludedIds))
		.limit('40') %}

	{% paginate products as pageInfo, productEntries %}
	{% include "_partials/templates/products-block-grid-four" with { 'template': 'product', 'products': productEntries } %}
	 <div class="pagination_blocks">
		{% if pageInfo.prevUrl %}<a class="previous-blocks" href="{{ pageInfo.prevUrl }}">Previous Page</a>{% endif %}
		{% if pageInfo.nextUrl %}<a class="next-blocks" href="{{ pageInfo.nextUrl }}">Next Page</a>{% endif %}
	</div>

	{% if pageInfo.total > 0 %}
		<div class="block-load-status">
			<p class="infinite-scroll-request">Loading more products...</p>
		</div>
	{% endif %} 
```

This is the code that paginates the entries.

I lazyload them in with infinite scroll here.

**Comment by bencroker** [comment]
Thanks, I'll look into it.

**Comment by mdunbavan** [comment]
Thanks a lot @bencroker much appreciated. If I can help on any way please tell me

**Comment by bencroker** [comment]
So I was able to replicate your issue, which has to do with the eager-loading of elements. For each product, you are eager-loading its related elements as per the `mainImage`, `variants`, and `productImages` fields. Since you load 40 products on each page, if each product had 24 related elements, then you would see 960 rows in the database for each cached page. Make sense now?

**Comment by mdunbavan** [comment]
Ah yeah okay totally clear now. So should I get rid of eager loading on these then to trim down the size?

**Comment by bencroker** [comment]
Well it depends on your end goal, if you're outputting them all on each page, then probably not, as I'm not sure it will even reduce the number of rows in the end. If you'd like to use lazy-loading on the front-end then check out this livestream, in which I explain how to load dynamic content into statically cached pages.
https://craftquest.io/livestreams/dynamic-content-on-statically-cached-pages
