### ISSUE TITLE
Unable to resolve the request blitz/cache/refresh-expired

### ISSUE THREAD

**Issue by johnwbaxter** [putyourlightson/craft-blitz#394]
We're seeing a lot of this in our log files at the moment and not sure what the cause is!

2022-04-06 13:15:02 [-][-][-][error][yii\console\UnknownCommandException] yii\base\InvalidRouteException: Unable to resolve the request "blitz/cache/refresh-expired". in /home/devwoc/vendor/yiisoft/yii2/base/Module.php:561

Craft CMS 3.7.37
Blitz 3.11.1

Thanks!

**Comment by bencroker** [comment]
Do you have a cron job set up to run the `blitz/cache/refresh-expired` command or are you running it manually? Can you run it manually to ensure that Blitz is correctly installed?

```shell
php craft blitz/cache/refresh-expired
```

And is there any more to that error message?

**Comment by johnwbaxter** [comment]
We have a cron job running every 5 mins

/usr/bin/php /home/xxxxxx/craft blitz/cache/refresh-expired > /dev/null 2>&1

Further output

```
Next yii\console\UnknownCommandException: Unknown command "blitz/cache/refresh-expired". in /home/xxxxxx/vendor/yiisoft/yii2/console/Application.php:184
Stack trace:
#0 /home/livewoc/vendor/craftcms/cms/src/console/Application.php(89): yii\console\Application->runAction('blitz/cache/ref...', Array)
#1 /home/livewoc/vendor/yiisoft/yii2/console/Application.php(148): craft\console\Application->runAction('blitz/cache/ref...', Array)
#2 /home/livewoc/vendor/yiisoft/yii2/base/Application.php(392): yii\console\Application->handleRequest(Object(craft\console\Request))
#3 /home/livewoc/craft(23): yii\base\Application->run()
#4 {main}
```

**Comment by bencroker** [comment]
Can you run the command manually to ensure that Blitz is correctly installed?

**Comment by johnwbaxter** [comment]
Yeah it runs fine from the terminal!

**Comment by bencroker** [comment]
In that case I'm not sure what would cause those errors, it seems to be on a Craft level though, since the controller action cannot be found. How many of these errors are you seeing on a daily basis approximately?

**Comment by johnwbaxter** [comment]
Well, we were seeing it a good few times an hour. As you say, it must be something craft related, I'll go look into seeing if there is a hosting issue here.

**Comment by bencroker** [comment]
Let me know what you find out. It looks like Craft is not recognising the Blitz controller actions, which is unusual.

**Comment by johnwbaxter** [comment]
Will do!

**Comment by johnwbaxter** [comment]
Well, it looks like the wider server issues we were having meant we were dropping the DB connection often and that would be causing the routing issue here one assumes. Sorry about this, there was a lot going on and we were trying to work out what was causing the issues. It wasn't blitz :)

**Comment by bencroker** [comment]
Ok, glad to hear you got to the bottom of it!
