### ISSUE TITLE
Ngnix config

### ISSUE THREAD

**Issue by wmdhosting** [putyourlightson/craft-blitz#395]
I have added this. 
https://putyourlightson.com/plugins/blitz#nginx   have ngnix  > Engitron  on server
For site i now testing with Blitz .. all work ok. without this rule, but this can speedup things right...

**There is another Craft 2 site and one Craft 3 site without Blitz** on that server
When i add rule they start throwing errors. 

Craft 2
2022/04/08 04:45:25 [error] 6107#6107: *47 rewrite or internal redirection cycle while internally redirecting to "/index.php", client: ::ffff:103.214.235.222, server: xxxxxx, request: "GET / HTTP/2.0", host: "xxxxxx"

Craft 3
2022/04/08 04:45:29 [error] 6108#6108: *52 rewrite or internal redirection cycle while internally redirecting to "/index.php", client: ::[ffff:190.2.132.127](), server: xxxxx, request: "GET / HTTP/1.0", host: "xxxxx", referrer: "xxxxx"

Does that rule need any change in this case or any other advice..

**Comment by bencroker** [comment]
If this is a shared hosting setup then it may need tweaking, but I can't tell how from the error messages above.

**Comment by wmdhosting** [comment]
ok thx
