### ISSUE TITLE
Blitz caches JSON responses from controllers (and element-api)

### ISSUE THREAD

**Issue by aloco** [putyourlightson/craft-blitz#397]
### Describe the bug
Hi Ben!

It seems like the latest release of Blitz started to cache JSON responses. We have a Website with a lot of custom controllers delivering JSON to clients - since the latest update, we can find `<!-- cached via blitz ... -->` comments at the end of those JSON responses. We rolled back to the previous version (3.11.2) and the issue was gone. I guess the Mimetype check from [this](https://github.com/putyourlightson/craft-blitz/commit/67c712aeb58209b26650cf6bcc775d36b4a4e92b) is somehow related.

a typical controller action ends with something like this

```
$response = Craft::$app->getResponse();
$response->format = Response::FORMAT_JSON;
$response->data = $data;
return $response;
```

Please note that those JSON endpoint URL´s are RESTful and don´t end with `.json` ... e.g. `api/v1/user` 

We also noticed this behaviour on element-api routes

We are using 
```
        'includedUriPatterns' => [
            [
                'siteId' => '',
                'uriPattern' => '.*',
            ],
        ],
```

### To reproduce
Steps to reproduce the behaviour:
1. Install Blitz 3.12.0
2. Create a controller returning JSON
3. Instruct Blitz to cache all sites with includedUriPatterns 
4. Call the JSON endpoint twice 
5. JSON Response gets `<!-- cached by .. -->` at the end    

### Expected behaviour
Only HTML responses / "web pages" should be cached by default

### Versions
- Plugin version: 3.12.0
- Craft version: 3.7.38

**Comment by karensg** [comment]
Experienced the same thing yesterday. It also started to cache the seomatic sitemap.

**Comment by bencroker** [comment]
Blitz 3.12.0 became more eager in what caches, due to switching the event that it listens to:
https://github.com/putyourlightson/craft-blitz/compare/3.11.2...3.12.0#diff-d84ebe8fb81ca8bac77db5f72409e075c583ad551b9c701c4a59918247643235L256-R264

This has the benefit of being able to cache more responses, however I see how it also changes the behaviour of the plugin drastically in some cases, especially yours. I'm going to revert the changes for Blitz 3 and will consider adding it back in for Blitz 4, with an additional setting to ease the upgrade.

**Comment by karensg** [comment]
Maybe we could use a "Cached by Blitz" header instead of comment to make sure the content does not break
Should also be ok for HTML.

**Comment by bencroker** [comment]
Yeah I'll need to make extra considerations for Blitz 4, in which it will be easier to justify changing behaviour.

Just pushed https://github.com/putyourlightson/craft-blitz/commit/6fcc967c03f0b4d7ed48ec13ed68371ead3f21a3 which should resolve the eager caching issue, for the next release. In case you'd like to test it on your end too, that would be much appreciated.

**Comment by bencroker** [comment]
Released in version 3.12.1, thanks for reporting this!

**Comment by aloco** [comment]
It is working again at our end. Thank you

> Yeah I'll need to make extra considerations for Blitz 4, in which it will be easier to justify changing behaviour.
> 
> Just pushed [6fcc967](https://github.com/putyourlightson/craft-blitz/commit/6fcc967c03f0b4d7ed48ec13ed68371ead3f21a3) which should resolve the eager caching issue, for the next release. In case you'd like to test it on your end too, that would be much appreciated.

**Comment by thomasdefilippis** [comment]
@bencroker Just wondering if you ever re-added ability to cache actions in controllers? and if so, whether this cache also refreshes on changes in the dashboard? We are currently considering moving our laravel api to controller actions in a module to serve our mobile app, and I am trying to determine whether this will have performance issues for users accessing our website. The ability to cache will obviously help with that.

Also, if you have any documentation or tips that would be greatly appreciated.

Thanks

**Comment by bencroker** [comment]
@thomasdefilippis No, and it isn’t planned. Blitz tracks pages based on their URIs, making it impractical to cache controller actions. I recommend you use Craft’s native caching mechanism for that.
