### ISSUE TITLE
$generalConfig->permissionsPolicyHeader is not a setting until Craft 3.6.14

### ISSUE THREAD

**Issue by bgrrtt** [putyourlightson/craft-blitz#398]
### Describe the bug

$generalConfig->permissionsPolicyHeader is not a setting until Craft 3.6.14

https://github.com/craftcms/cms/blob/3.6.14/CHANGELOG.md#added

Blitz commit: https://github.com/putyourlightson/craft-blitz/commit/67c712aeb58209b26650cf6bcc775d36b4a4e92b#diff-e74129f9c490eae2fdd5f4f84743badcb13b1d97c46999b05606fdf5ee6b9eeeR443-R445

### To reproduce
Steps to reproduce the behaviour:
1. Refresh Blitz Cache
2. Visit cached page
3. See error message "Getting unknown property: craft\config\GeneralConfig::permissionsPolicyHeader"

### Expected behaviour

To see the cached page, not the error message.

### Versions
- Plugin version: ^3.12.0
- Craft version: Craft CMS 3.6.13 and below

**Comment by bencroker** [comment]
Thanks for reporting this, fixed in https://github.com/putyourlightson/craft-blitz/commit/589a6b3b73b73c8ba9d413c233a9b407d31060df and released in 3.12.2.

**Comment by bgrrtt** [comment]
Thank you!
