### ISSUE TITLE
Country detection query and implementation of correct exclusion URI matches

### ISSUE THREAD

**Issue by AlexShearcroft** [putyourlightson/craft-blitz#399]
### Question
Wonder if you could assist... Couldn't see anywhere other than here to request support.

We currently have a number of translated sites that all serve their own URLs e.g. /en-gb, /de-de etc. However, when utilising Cloudflare's IP Geolocation users then get served the correct site based on their location. This all works perfectly fine, until Blitz is initiated. We're simply hitting the route domain, making a check on their location and then sending them to the Craft site best for them. By default this is set to EN-GB. When hitting the route domain it redirects correctly to the homepage for EN-GB, however, when I next hit the route domain it no longer redirects and then caches the EN-GB homepage. When checking the headers it's no longer a 301 but instead a 200 status and says powered by Blitz... meaning this has now been cached. However... we've set up an exclude for a direct URI match `^/$` and this appears to not be working.

I've also read through the docs and can see you can exclude the homepage too for all sites. When implementing this, it worked correctly and would then redirect from the route to the correct site. The issue we're now having is the homepages no longer get cached by Blitz and impacts on performance and load speeds.

Am I missing or implementing something wrong? Any help and guidance would be fully appreciated.

### Additional context
**Plugins**
Blitz | 3.11.0
Craft CMS | Craft Pro 3.7.30.1
SEOmatic | 3.4.23
PHP 7.4

Many thanks,
Alex

**Comment by bencroker** [comment]
This is indeed the best place to submit support requests, the other is by email.

Is the redirect based on the IP address being done by Cloudflare or by Craft? If the former, then I'd expect that everything should work, since the redirect would happen before Blitz gets involved. If the latter, then how and where exactly has the redirect been implemented? If I could see your implementation then perhaps I could try help you resolve this.

**Comment by AlexShearcroft** [comment]
Thanks for the response Ben. We're using Cloudflare IP Geolocation to detect user location and then redirect accordingly based on their country code and that matching a field setup within our Craft CMS.

Please see below code for reference:

Middleware class
```php
class TidyUrlsMiddleware
{
    public static $exclusions = [
        '*api*',
        '*ads.txt',
        '*robots.txt',
        '*humans.txt',
        '*index.php?p=*',
        '*actions/*',
        '*blitz*',
    ];

    public static function handle()
    {
        $request = Craft::$app->request;

        $hostname = $request->getHostInfo();

        $slug = $request->getUrl();
        $slug = rtrim($slug, '/'); // remove trailing slash
        $slug = ltrim($slug, '/'); // remove starting slash
        $slug = preg_replace('#/+#', '/', $slug); // remove double slashes
        $slug = '/' . $slug;

        if (
            !Str::is(static::$exclusions, $slug) &&
            !$request->getIsCpRequest() &&
            !preg_match('#/[a-z]{2}-[a-z]{2}#i', $slug)
        ) {
            $slug = rtrim(static::getCountrySlugForUser() . $slug, '/');
        }

        $newLocation = $hostname . $slug;

        if ($slug !== $request->getUrl()) {
            http_response_code(301);
            header('X-Redirect-Reason: No language selected.');
            header("Location: $newLocation");
            exit;
        }
    }

    public static function getCountrySlugForUser()
    {
        $request = Craft::$app->request;

        $ipCountry = strtolower($request->headers->get('HTTP_CF_IPCOUNTRY', $request->headers->get('cf-ipcountry', null)));

        if (empty($ipCountry)) {
            return '/en-gb';
        }

        $sites = Craft::$app->getSites()->getAllSites(false);

        $languages = collect($sites ?? [])->mapWithKeys(function ($site) {
            return [strtolower(substr($site->language, -2)) => $site->id];
        });

        // Get country list
        $countryRedirects = Craft::$app->globals->getSetByHandle('countryRedirects', $languages->get($ipCountry))->countryRedirects;

        $redirects = collect($countryRedirects ?? [])->map(function ($group) {
            $site = '/' . strtolower($group->redirectTo->value);
            $codes = explode("\n", trim($group->countryCodes));
            return collect($codes)->mapWithKeys(function ($code) use ($site) {
                return [strtolower($code) => $site];
            });
        })->mapWithKeys(fn($a) => $a);

        return $redirects->get($ipCountry) ?? '/en-gb';
    }
}
```

Request Event

```php
private function requestEvents()
{
    Event::on(Application::class, Application::EVENT_BEFORE_REQUEST, function () {
        TidyUrlsMiddleware::handle();
    });
}
```

Blitz config
![Screenshot 2022-04-27 at 09 08 07](https://user-images.githubusercontent.com/2182037/165471875-21bb33e8-a23e-4939-a6fa-44ae55cc3ed3.png)

When Blitz cache is cleared the first hit of the route domain e.g. https://www.domain.com redirects to /en-gb with 301 response. Accessing the route domain again returns a 200 status and shows the content for the /en-gb site. The cache file is not stored in the web cache folder and neither the database as this isn't an actual page.

Hope this helps.

**Comment by bencroker** [comment]
It looks like you're correctly handling the request before Blitz does. I tested locally and the redirect works _without_ creating a cached version of the page. However, if no redirect takes place then the page _will_ be cached, and if using server rewrites will be served on the next request.

So your options are to disable server rewrites (assuming you're using them), which I don't recommend as it will not perform as well. Otherwise you can exclude the home page from caching by replacing `^/$` with a blank string, which will match the home page, but will also not perform as well. Or finally, use Sprig or vanilla JS to perform the redirect, or better yet to ask the user if they want to be redirected based on their locale, on page load.

I'd also recommend you update the plugin so you're on the latest version.

**Comment by AlexShearcroft** [comment]
Thanks for taking the time to review and test Ben. I will take on board your advice and see where this leads me.

**Comment by bencroker** [comment]
Great, I'd be interested to hear what solution you land on.
