### ISSUE TITLE
Plugin doesn't seem to respect the Included/Excluded URI Pattern lists.

### ISSUE THREAD

**Issue by tyler-shaw** [putyourlightson/craft-blitz#4]
I notice when the plugin runs, the `Blitz::init()` method checks `$this->cache->getIsCacheableRequest()`, and if it's true, it registers the code to cache the page after rendering finishes. However, it doesn't seem to consider the fact that `$this->cache->getIsCacheableUri()` is returning false. I would think that both methods would need to be true prior to registering the event code that caches the page.

Just to test my thought process, I moved this line: https://github.com/putyourlightson/craft-blitz/blob/v1/src/Blitz.php#L70 inside this block: https://github.com/putyourlightson/craft-blitz/blob/v1/src/Blitz.php#L62-L68 - and the plugin seems to be working as I would expect. With this change, the only pages that are being cached are ones that I explicitly add to the Included list.

Perhaps I'm missing something - any insight would be great.

Thanks!

**Comment by putyourlightson** [comment]
You're absolutely right, thanks for reporting this.
Fixed in https://github.com/putyourlightson/craft-blitz/commit/4b8fe05eee355b97bfa30f13df069bee2be8617c

**Comment by tyler-shaw** [comment]
Great! Thanks for getting that fixed so quickly.
