### ISSUE TITLE
Ignore Query Strings

### ISSUE THREAD

**Issue by michaelroper** [putyourlightson/craft-blitz#40]
Hey Ben! Regarding caching pages with query strings, would you consider giving an option to _ignore/strip query strings_ when saving the cache?

I understand the need for the option to _not_ cache pages with query strings, when they are being used to affect what the page content is. But my use-case here is where my page content is the same regardless of the query string, but I'm using UTM parameters in the URL for campaign tracking with Google Analytics. In this case, I _do_ want to cache pages with these query strings, but I _don't_ need it to create a separate cached version of each unique URL. 

For example, all of these URLs should only create the one cached version of the `/sale` page, instead of 3 different versions:

```
foo.com/sale?utm_campaign=xmas-sale&utm_medium=social&utm_source=twitter
foo.com/sale?utm_campaign=xmas-sale&utm_medium=social&utm_source=facebook
foo.com/sale?utm_campaign=xmas-sale&utm_medium=social&utm_source=twitter
```

Hope that makes sense!

**Comment by putyourlightson** [comment]
Hi Michael! Yes that does make sense, however the setting would have to be applied across the entire site and would also require having to change the server rewrite code. I think that the way it is now, you are getting the benefits of caching without the fuss of extra setup. The only drawback could be that you have more files on the server, but I don't see that being such a bad trade-off. If you have other pages on the site whose content does depend on the query string, then everything will still work as expected, for example:

    foo.com/search?q=xmas
    foo.com/search?q=sale

Any thoughts?

**Comment by michaelroper** [comment]
Yeah, I guess it's one of those things where you would have your site set up one way or the other... 
I know for my site, where the only place I use query strings is for search, I'd rather exclude the `/search` page from being cached, ignore the query string and cache everything that way.

Another view from the flip side, is that if any sites (thinking ad publishers, etc) link to my pages with any kind of dynamic value in them, like a timestamp or id [ie Adwords `?gclid=xxxxx` value], every single one of those urls will generate its own cache, and nobody coming from those type of links will hit a cached version... which would make the caching a lot less useful for me.

I get where you're coming from with ease of setup for the majority though... could it possibly be documented config file option instead?

**Comment by putyourlightson** [comment]
I'm considering how the `Query String Caching` setting could be changed to a select field with the following options:

- Do not cache URLs with query strings
- Cache URLs with unique query strings as unique pages
- Cache URLs with unique query strings as the same pages

What do you think of the wording? And I'm wondering if it would make sense to bring this setting into the `Included URI Patterns` table, that way it could vary per URI pattern.

**Comment by michaelroper** [comment]
Yeah, that sounds like a better plan. If you were to make it a select in the table, maybe it could be simplified to something like...

|For URLs with query strings|
|-----|
| Do not cache them |
| Cache them with the query string |
| Cache them without the query string |

I think as long as you keep it reasonably clear, and then clarify the difference in the behaviours in the documentation, that would be fine.

And also - it shouldn't necessarily change the server rewrite code, because wouldn't it just try 
`${request_uri}/index.html` if it didn't find `${request_uri}/${args}/index.html`?

**Comment by putyourlightson** [comment]
Regarding the rewrite, a request to `foo.com/sale?source=twitter` will not automatically rewrite to `foo.com/sale`. Setting it to do so will break the functionality in the first two options of the select field, so I'm kind of on the fence about it.

**Comment by michaelroper** [comment]
Ahh, were you referring to the rewrite done by Blitz, as opposed to the Apache/nginx config?

**Comment by putyourlightson** [comment]
No, the plugin has control over its own rewrite. I was refering to the server rewrite.

**Comment by michaelroper** [comment]
I'm not sure if Apache has the same concept, but with nginx you could theoretically make the default rewrite something like this?
```
# Blitz cache rewrite
location / {
  try_files 
    /cache/blitz/$http_host${request_uri}/${args}/index.html 
    /cache/blitz/$http_host${request_uri}/index.html
}
```

**Comment by putyourlightson** [comment]
Yes, but that would not work in the case where URL query strings should be cached as unique pages, as if `foo.com/search?q=xmas` was requested, the server would show the output of `foo.com/search`, which is incorrect behaviour. Make sense?

**Comment by michaelroper** [comment]
Okay, I get you - if you were to provide the option to treat different patterns separately, you'd have to have separate rewrites to match each of those patterns. It's no longer a simple cover-all solution. Tricky...

**Comment by putyourlightson** [comment]
Added in 1.8.0.
https://github.com/putyourlightson/craft-blitz/blob/v1/CHANGELOG.md#180---2018-11-28

**Comment by michaelroper** [comment]
Awesome, thanks Ben! Seems to be working great so far..

**Comment by putyourlightson** [comment]
Excellent!!
