### ISSUE TITLE
Latest update throws error when saving entry or clearing cache

### ISSUE THREAD

**Issue by ZapaNOR** [putyourlightson/craft-blitz#401]
After the latest update I get this error whenever i change a field on an entry or try to clear cache from the CP.
Clearing cache with console command works, but right now i can not edit or save entries.

`2022-05-03 11:53:54 [-][3][aa7i8rgdbsl369h96s8sg976e0][error][ParseError] ParseError: syntax error, unexpected ')', expecting '|' or variable (T_VARIABLE) in /xxx/vendor/putyourlightson/craft-blitz/src/services/RefreshCacheService.php:436`

**Comment by bencroker** [comment]
Thanks for reporting, just released a fix with https://github.com/putyourlightson/craft-blitz/commit/42e16bd873e2e2be5fdb98c05a84d1911a50d042 in 3.12.4.
