### ISSUE TITLE
Cache warming as background task?

### ISSUE THREAD

**Issue by iamtompickering** [putyourlightson/craft-blitz#403]
Is it possible to change the cache warming to a background task instead of running in the foreground?

A project I am running on Servd is struggling to sync because the cache warming task is taking forever, and timing out the sync. 

They are going to look into if they can run it as an async task, but also were wondering if it's possible within the blitz config to warm the cache as background task. I've had a look in your docs and couldn't see anything, but just wanted to check in case I missed it!

**Comment by bencroker** [comment]
Cache warming happens via a queue job and you have plenty of options to run queue jobs in background processes, see https://nystudio107.com/blog/robust-queue-job-handling-in-craft-cms

Alternatively, you can disable automatic cache warming and set up a cron job to warm on a schedule using the `blitz/cache/warm` command (in Blitz 3), see https://putyourlightson.com/plugins/blitz#console-commands
