### ISSUE TITLE
Remote Deployment Error connecting to repository

### ISSUE THREAD

**Issue by Medsaad** [putyourlightson/craft-blitz#405]
I have craft cms installed into a k8s pod. I am using the remote deployer. I've added the path of the repository `/static/website-static`, The branch `main` and the remote `origin`. I've also sshed into the pod and checked that a git repo there (git commands are working). However, I see the following error in the settings:

```
Error connecting to repository: fatal: not in a git directory
```

*Note*: I cloned the repo into `/static/website-static` using the format: `https://oauth2:<PERSONAL_TOKEN>@gitlab.com/workstreams.ai/workstreams-website-static.git` and the remote is currently shown in this format.

**Comment by bencroker** [comment]
Please provide details such as plugin and Craft versions, which remote deployer you are using and how, etc.

**Comment by Medsaad** [comment]
**Details**:
craftcms/cms: 3.7.42
putyourlightson/craft-blitz: 3.12.4
Using "Git Deployer", added Git Repositories (path, branch and remote), username, personal access token etc ..

Under the "Git Repositories" table I got the error mentioned above.

**Comment by bencroker** [comment]
The error above is coming directly from Git. Can you please double check that your repository path is correct, and that it contains a `.git` folder?

**Comment by Medsaad** [comment]
Hey @bencroker, Thank you for your quick support. Yes, the error was from git itself but it was a bit misleading from them. It was actually a permission issue. the git project directory was owned by `root` while a non-root user was trying to access it. Once I added the project in a directory owned by this user, it worked.

**Comment by bencroker** [comment]
Glad to hear you figure it out!
