### ISSUE TITLE
Blitz 4.1.2: Internal server error when query string added to URL

### ISSUE THREAD

**Issue by jl-digital** [putyourlightson/craft-blitz#408]
I upgraded Blitz to 4.1.2, and now URL's with any query string added will throw an internal server error.

PHP version | 8.0.16
Database driver & version | MySQL 10.4.24
Craft edition & version | Craft Pro 4.0.2

This is only since Blitz 4.1.2. Before that, everything was working fine on Craft 4.

Problem now temporarily solved by disabling the cache.

Log error:
[web.ERROR] [TypeError] Cannot access offset of type string on string {"memory":5795296,"exception":"[object] (TypeError(code: 0): Cannot access offset of type string on string at /home/***/***/***/vendor/putyourlightson/craft-blitz/src/services/CacheRequestService.php:403)"}

**Comment by bencroker** [comment]
Did you see the required changes as per the release notes?

> Changed the included/excluded query string parameters config setting format.

The new format is as follows.

https://github.com/putyourlightson/craft-blitz/blob/a3571ae82254fd48fce7f6ecca9b24ff0adbc6f2/src/config.php#L139-L157

https://github.com/putyourlightson/craft-blitz/blob/develop/CHANGELOG.md#400---2022-05-04

**Comment by jl-digital** [comment]
Excuse me, I didn't see that. I changed my config and now the problem has been solved.

**Comment by bencroker** [comment]
Great!
