### ISSUE TITLE
getTemplate injecting randomly with no errors

### ISSUE THREAD

**Issue by louderthan10** [putyourlightson/craft-blitz#409]
I've been experiencing a strange behaviour where Blitz isn't injecting templates consistently. In fact it's failing more often than it's succeeding. An example is this sign in link in my nav:

**Cached template**
```
{{ craft.blitz.getTemplate('_modules/nav--sign-in') }}
```

**Injected template**
```
{% import '_components/nav/default' as page %}

{% if currentUser and currentUser.admin %}
  {{ page.NavItem({ slug: 'backstage', url: '/backstage', title: 'Backstage' }) }}
{% else %}
  {% set text = currentUser ? 'Class dashboard' : 'Sign-in' %}
  {{ page.NavItem({ slug: 'sign-in', url: craft.app.sites.getSiteByHandle('app').baseUrl , title: text }) }}
{% endif %}
```

This worked perfectly for a long time, then just recently it acting up in either of the following ways:

1. Works as expected (about 20% of the time… randomly across pages and after refreshing the same page)
2. Nothing appears (60% of the time: no errors given in console or Craft debug bar (all templates requested and have 200 status)
3. The template appears, but the wrong state is shown (20% of the time: e.g., I see "Sign in" when I'm signed in as an admin user)

Update: This is the rendered injection code after a Nothing appears result:
```
<span id="blitz-inject-1" data-blitz-id="1" data-blitz-uri="https://louderthanten.ltt/actions/blitz/templates/get" data-blitz-params="template=68edcee1727ff13cf0a0880fa268ea56cdc9f17ed5a0573c699d3270740ace7e_modules%2Fnav--sign-in&amp;siteId=2" data-blitz-property="" class="blitz-inject"></span>
```
Happens both locally and on production.

Craft 3.7.42
Blitz 3.12.4

**Comment by bencroker** [comment]
It looks like your action response is being cache by Cloudflare. Are you overriding the `Cache-Control` headers? You might want to review your site's headers in general, it looks like there's a lot of duplication happening.

<img width="358" alt="Screenshot 2022-05-19 at 12 22 16" src="https://user-images.githubusercontent.com/57572400/169271924-26986866-8826-4ae3-8317-f9c2b5b26a0a.png">
...
<img width="275" alt="Screenshot 2022-05-19 at 12 20 41" src="https://user-images.githubusercontent.com/57572400/169271741-5fe02443-f4e2-4a38-a881-2515848b7b4f.png">

**Comment by louderthan10** [comment]
Ahhh! Thanks @bencroker! For the time being I added a Cloudflare rule to bypass caching on all /actions requests and my templates immediately started working as expected again.

I'll go through the rest of my cache headers, but thanks for helping me zero in on this!

**Comment by bencroker** [comment]
Blitz intentionally does _not_ add cache headers on action requests, so this shouldn't be necessary. My guess is that your server is setting cache headers when it shouldn't be. Let me know how you go about solving this, for future reference!
