### ISSUE TITLE
Database filling up

### ISSUE THREAD

**Issue by thaoms** [putyourlightson/craft-blitz#41]
My database is still filling up with queries until it's full.

Is there no way to disable caching in the DB?
What is the use of caching element queries if you are using static files (htaccess redirect)?

**Comment by putyourlightson** [comment]
Elements and element queries are stored in order to make cache invalidation possible. What exactly do you mean by "full"?

**Comment by thaoms** [comment]
It's making thousands of records and the tables get over 300MB in size.
My database has a limit of 500mb and when that fills up everything goes down.

Im using a cronjob to clear the cache every night but that only clears the files on the server, wouldn't be an option to also clear the tables with that command? A clean start every night is okay by me.

And in my case it keeps the DB from overflowing

**Comment by putyourlightson** [comment]
Would a config setting to disable element query caching be useful to you? That will mean that related element updates will not invalidate the cache however.

**Comment by thaoms** [comment]
That would be fine!

**Comment by putyourlightson** [comment]
Ok will add to the next release.

**Comment by sjelfull** [comment]
I'm experiencing the same. Is there any way to make this more efficient, or is it simple the name of the game with big sites?

An idea: Could the cache warming take a time parameter, and only cache entries that was last updated and/or created within x days/months

AND

Could there be a setting then that older entries will be cached on the fly?

The thinking is that the most "important" entries (as in new? maintained?) will already be warmed, while the long tail stuff isn't.

**Comment by putyourlightson** [comment]
Intelligent cache invalidation needs a lot of logic unfortunately. I don't see the time parameter being a viable solution, as who's to say that older elements are not as important if not more than recently updated ones. The next release will include a config setting to disable element query caching, similar to the native Craft [config setting](https://docs.craftcms.com/v3/config/config-settings.html#cacheelementqueries), which will prevent the table size getting out of hand. The caching of element queries is similar to how it is done in Craft.

**Comment by putyourlightson** [comment]
Out of curiosity, can you run the following SQL command and compare the number of unique queries with the total number of rows in the table? I want to get an idea of whether the are a significant number of repeating queries as those could reduced using a relating table.

```SELECT COUNT(DISTINCT query), COUNT(*) FROM blitz_elementquerycaches```

**Comment by riasvdv** [comment]
On a site with 6.000 elements I have this:
```
COUNT(DISTINCT query)	COUNT(*)
3368	                13349
```

**Comment by putyourlightson** [comment]
Thanks @Rias500, so bringing unique element queries into their own table would reduce the database size significantly!

@thaoms and @sjelfull, could you also check? If you get the same results then I'll proceed with this approach for the next release.

**Comment by thaoms** [comment]
```
COUNT(DISTINCT query)	COUNT(*)
6942	                84806
```

**Comment by sjelfull** [comment]
```
COUNT(DISTINCT query)	COUNT(*)
478	1068
```

**Comment by putyourlightson** [comment]
Thank you, adding this to the list :)

**Comment by putyourlightson** [comment]
Added in 1.8.0, would be interested to hear what difference it makes.
https://github.com/putyourlightson/craft-blitz/blob/v1/CHANGELOG.md#180---2018-11-28

**Comment by putyourlightson** [comment]
And if it's not enough then it is now possible to disable element query caching altogether in the Blitz config file:
```
'cacheElementQueries' => false,
```

**Comment by smockensturm** [comment]
hahahahaahaa ha

```
COUNT(DISTINCT queryID)	COUNT(*)
2736	1241248
```
ok wow blitz. this seems like we have a mis-configuration here.

**Comment by bencroker** [comment]
Yup, your site's templates very likely need optimising. See the common issue at https://putyourlightson.com/plugins/blitz#the-refresh-cache-queue-jobs-run-for-long-periods-of-time-and-sometimes-pile-up.
