### ISSUE TITLE
preventing cache refreshing

### ISSUE THREAD

**Issue by moldedjelly** [putyourlightson/craft-blitz#410]
I've got a site where we have some caching setup on some product feeds. When we do some mass updates on products from some syncing with a third party inventory system, we seem to get thousands of Blitz Cache Refreshing tasks added to the queue and it quickly overwhelms the system. 

I assuming that when the product updates occur, Blitz is pushing a cache refresh task into the queue even though technically it only needs the one refresh after all the product edits.

I thought that we could update our mass updates function so that before the product updates occur, we could temporarily disable the caching so we have tried this bit of code:

        $settings = Blitz::$plugin->settings;
        $settings->setAttributes([
            'clearCacheAutomatically'=>0,
            'warmCacheAutomatically'=>0,
            'refreshCacheAutomaticallyForGlobals'=>0,
        ], false);
        Craft::$app->getPlugins()->savePluginSettings(Blitz::$plugin, $settings->getAttributes());
        Blitz::$plugin->clearCache->clearAll();
        Blitz::$plugin->flushCache->flushAll();

It seems to succesfully disable the settings in Blitz, but when performing the product updates, we still end up with many Blitz refreshing tasks. We'd expect there to be no refreshing tasks added since the automatic clear and warm are not enabled. Any ideas why this wouldn't be working as expected?

**Comment by bencroker** [comment]
Sounds like you should be setting `batchMode` to `true` before performing the sync, as documented at https://putyourlightson.com/plugins/blitz#integrations

**Comment by moldedjelly** [comment]
@bencroker thanks so much, that was the trick!
