### ISSUE TITLE
Blitz removes caches without refresh

### ISSUE THREAD

**Issue by martinhellwagner** [putyourlightson/craft-blitz#412]
We have a special use case for Blitz, wherein pages like https://www.karriere.at/brutto/300 up to https://www.karriere.at/brutto/8000 (counting upwards one by one, resulting in a total of 7701 pages) should be cached, but those caches never removed. Pages "outside" of this rage (like https://www.karriere.at/brutto/299 or https://www.karriere.at/brutto/8001) should also be cached, but those caches don't necessarily need to be persisted. Only when a special pipeline is triggered, all of the caches in the range of 300 to 8000 should be refreshed – but only then.

However, after checking that those 7701 folders are present on the server, I've re-checked a couple of days later – and found only around 2600 folders on the server. So, somehow, around 5000 cache folders were removed – even though nobody triggered a refresh. We have automatic refresh turned on, but these pages only have external links (to non-Blitz sites) or links to other pages of the same type (e.g. https://www.karriere.at/brutto/3000 has a link to https://www.karriere.at/brutto/3200). Nothing has changed on these pages, so in my understanding an automatic refresh should not be triggered.

How can we make sure that these folders are always persisted when nothing has changed on these pages, and nobody has triggered a manual refresh?

**Comment by bencroker** [comment]
To ensure that cached pages are _never_ deleted, you'll likely need to hook into the `ClearCacheService::EVENT_BEFORE_CLEAR_CACHE` and `ClearCacheService::EVENT_BEFORE_CLEAR_ALL_CACHE` events using a custom module/plugin. Here's some (untested) code to get you started.

```php
Event::on(ClearCacheService::class, ClearCacheService::EVENT_BEFORE_CLEAR_CACHE,
    function (RefreshCacheEvent $event) {
        foreach ($event->siteUris as $key => $siteUri) {
            $segments = explode('/', $siteUri->uri);
            if (!empty($segments[0]) && $segments[0] == 'brutto'
                && !empty($segments[1]) && $segments[1] >= 300 && $segments[1] >= 8000
            ) {
                unset($event->siteUris[$key]);
            }
        }
    }
);
```

**Comment by martinhellwagner** [comment]
@bencroker 

Thanks! I've just tested the code – however, `$event->siteUris` seems to be `null`. 🤔 
Just out of curiosity: what might be the reason for the `/brutto/*` pages to be cleared?

**Comment by bencroker** [comment]
> Thanks! I've just tested the code – however, $event->siteUris seems to be null. 🤔

It shouldn't ever be `null`, it can be an empty array though, assuming you're on the latest version 4.1.2 of the plugin.

> Just out of curiosity: what might be the reason for the /brutto/* pages to be cleared?

My guess is that the cache was cleared or refreshed by someone or for some reason, but you haven't provided enough details for me to give an accurate answer.

**Comment by martinhellwagner** [comment]
I've had another look at the `siteUris`, but it doesn't seem to me that an empty array is present here? However, cache clear works as expected locally, that's why I'm confused.

![Screenshot 2022-05-20 at 13 58 44](https://user-images.githubusercontent.com/19146752/169523748-3b028c67-0ebe-4b93-8c20-18b8f7439662.png)

I'm still gathering information how the clearing took place. If I have more insight, I can share it here. 🙂

**Comment by bencroker** [comment]
That seems to be coming from the `EVENT_BEFORE_CLEAR_ALL_CACHE`, in which case `siteUris` is empty, since _all_ site URIs are about to be cleared. You can prevent this by event from continuing by setting `$event->isValid = false`.

**Comment by martinhellwagner** [comment]
Do you mean like this?
I've tried that, but unfortunately `siteUrls` is still empty.

```
Event::on(ClearCacheService::class, ClearCacheService::EVENT_BEFORE_CLEAR_ALL_CACHE,
    function (RefreshCacheEvent $event) {
        $event->isValid = false;
        foreach ($event->siteUris as $key => $siteUri) {
            $segments = explode('/', $siteUri->uri);
            if (!empty($segments[0]) && $segments[0] == 'brutto'
                && !empty($segments[1]) && $segments[1] >= 300 && $segments[1] <= 8000
            ) {
                unset($event->siteUris[$key]);
            }
        }
    }
);
```

**Comment by bencroker** [comment]
As expected with this event. Just setting the value to `false` is sufficient.

**Comment by martinhellwagner** [comment]
But if that doesn‘t work even though the parameter is set to `false`, is it at all possible that the site URI array is not empty with this event?

**Comment by bencroker** [comment]
It will always be empty for the `EVENT_BEFORE_CLEAR_ALL_CACHE` event.

**Comment by martinhellwagner** [comment]
So I need to use the `ClearCacheService::EVENT_BEFORE_CLEAR_CACHE` events to query the `siteUris`?

**Comment by bencroker** [comment]
Correct, as per my example in https://github.com/putyourlightson/craft-blitz/issues/412#issuecomment-1132659854

**Comment by martinhellwagner** [comment]
Just tried that, but it seems the event is never called – neither on the Backend nor on the CLI.

**Comment by martinhellwagner** [comment]
Just tried that, but it seems the event is never triggered – neither on the Backend, nor on the CLI.

```
Event::on(ClearCacheService::class, ClearCacheService::EVENT_BEFORE_CLEAR_CACHE, function (RefreshCacheEvent $event) {
    $event->isValid = false;
    print_r($event);
    die();
});
```

**Comment by bencroker** [comment]
The event is triggered here in the latest version: https://github.com/putyourlightson/craft-blitz/blob/a3571ae82254fd48fce7f6ecca9b24ff0adbc6f2/src/services/ClearCacheService.php#L44

**Comment by martinhellwagner** [comment]
Ah, I found the problem: it seems that the `ClearCacheService::EVENT_BEFORE_CLEAR_CACHE` event is only triggered with the "Refresh Caches URLs" or "Refresh Site Cache" commands, not the "Refresh Cache" command?

**Comment by bencroker** [comment]
Correct, the `Refresh Cache` command triggers the `EVENT_BEFORE_CLEAR_ALL_CACHE` event.

**Comment by martinhellwagner** [comment]
Got it. Thanks for the help! 👍🏼
