### ISSUE TITLE
Additional default `excludedQueryStringParams`

### ISSUE THREAD

**Issue by mattsbanner** [putyourlightson/craft-blitz#414]
On all of our sites we have had to add the following to the `excludedQueryStringParams`.
- `utm_source`
- `utm_medium`
- `utm_campaign`
- `utm_content`
- `utm_term`
- `mc_cid`
- `mc_eid`

It might be helpful for others if these were default in the config as I believe they come from Google and Mailchimp. Causing our sites to return a lot of non-Blitz responses.

**Comment by bencroker** [comment]
Thanks for the suggestion, but I prefer not to make assumptions about what query string parameters people want to include/exclude, hence the setting. Note this you can reuse it across all your sites by putting it the config setting.
https://github.com/putyourlightson/craft-blitz/blob/a3571ae82254fd48fce7f6ecca9b24ff0adbc6f2/src/config.php#L147-L157
