### ISSUE TITLE
Issue with query params in URL

### ISSUE THREAD

**Issue by zizther** [putyourlightson/craft-blitz#415]
With caching disabled via the config file and query string caching set to 0 (`'queryStringCaching' => 0,`) I am finding it impossible to access any URL with a query string.
The CMS is setup as a multi site. I am using Geomate to handle the redirects, if I try to access any URL with a query string, either Geomate's or any query param it shows an error `Cannot access offset of type string on string`

`vendor/putyourlightson/craft-blitz/src/services/CacheRequestService.php at line 403`

I don't think this has anything to do with Geomate as any query causes this error for me.
Don't know if this is somewhat related to #411 or not.

- The plugin and Craft version numbers.
Blitz 4.1.3
Craft 4.0.3
PHP 8.1.6

**Comment by bencroker** [comment]
This sounds more like a duplicate of https://github.com/putyourlightson/craft-blitz/issues/408

**Comment by zizther** [comment]
That would do it :)
Thanks
