### ISSUE TITLE
Manual remote deployment in Blitz 4

### ISSUE THREAD

**Issue by Gnative** [putyourlightson/craft-blitz#416]
I'm a little confused with the Refresh Modes and how they relate to Remote Deployment. 

I'm looking to have the cache refreshed on entry updates but want to manually chose when to deploy to a remote location. This enable us to review the current state before deployment.  

Thanks

**Comment by bencroker** [comment]
Deployment automatically follows cache generation, so if you want to manually choose when to deploy then select either of the two refresh modes that `regenerate manually`. I'd suggest you use `Clear the cache, regenerate manually or organically`.

**Comment by Gnative** [comment]
Ok thanks. 

Sorry but I think I keep falling outside of how this plugin works as I am working with a multi language site
I have currently 2 sites, one for english and one for german `de` under sub pages `/de/` as outlined in the Craft Docs - https://craftcms.com/docs/4.x/sites.html#site-url

E.G

```
/contact.html
/de/kontact.html

```

The remote deployment only pushes the english, base, version, where I need both to be pushed to the same repo. I understand that these are separate sites so Blitz is probibly looking to push these separately so I've looked at setting Git Repositories in to the same repo but unable to get this to deploy into the specific language subfolder.

**Comment by bencroker** [comment]
What exactly is not working and what do your Remote Deployment settings look like?

**Comment by Gnative** [comment]
I'm trying to deploy a multi language site, as one site, as the file structure below.
Just cant figure out how this can be accomplished with this plugin.  

The deploy setting below pushes the `de` site files into the root of the repository instead of under `/de/`

Thanks Ben

<img width="1310" alt="Screenshot 2022-06-02 at 16 07 26" src="https://user-images.githubusercontent.com/1758875/171648384-2b98ff62-394c-4a95-a1b4-122bfd7b0b4b.png">

<img width="358" alt="Screenshot 2022-06-02 at 16 12 35" src="https://user-images.githubusercontent.com/1758875/171649307-6963c7aa-5e15-49a2-8f06-bb26fd41149a.png">

<img width="1158" alt="Screenshot 2022-06-02 at 16 10 55" src="https://user-images.githubusercontent.com/1758875/171649292-239b54db-6b13-490c-906f-e946bd891ab1.png">

**Comment by bencroker** [comment]
Have you tried setting the repository path for the `de` site to `/Users/.../website-static/de/`?

**Comment by Gnative** [comment]
Hi Ben.. damn it that works. "Damn it" meant in a good way and why didn't I just try it. 
I assumed that it wouldn't as I seen this error and thought the settings weren't working 

<img width="1542" alt="Screenshot 2022-06-08 at 10 40 01" src="https://user-images.githubusercontent.com/1758875/172573422-9e443c57-f1fa-48d1-af35-1a9eab08eb2c.png">

Thank you for your patience, this plugin is great for what we need.

**Comment by Gnative** [comment]
Hi Ben.. damn it that works. "Damn it" meant in a good way and why didn't I just try it.
I assumed that it wouldn't as I seen this error and thought the settings weren't working

<img width="1542" alt="Screenshot 2022-06-08 at 10 40 01" src="https://user-images.githubusercontent.com/1758875/172574236-37236466-74ce-4553-8c25-39b7ce1949f5.png">


Thank you for your patience, this plugin is great for what we need.

**Comment by bencroker** [comment]
Glad to hear it!!
