### ISSUE TITLE
Blitz visually outputs an object with cache info into a web page

### ISSUE THREAD

**Issue by juangong** [putyourlightson/craft-blitz#417]
Please provide a clear and concise description of what the bug is, including:
- Steps to reproduce the issue.

Update entry content in a Craft 3 web page.

- A clear and concise description of what you expected to happen.

Cache gets updated for Blitz on that page. And no additional markup appears at the bottom of that page explaining what has been cached (as an outputted object with keys/values of cache information).

- If applicable, add screenshots to help explain your problem.

N/A unfortunately

- The plugin and Craft version numbers.

Craft CMS Pro 3.7.42
Blitz 3.12.4

**Comment by bencroker** [comment]
I've no idea what you're referring to, can you show me an example of what is being output that shouldn't be?

**Comment by juangong** [comment]
Hi @bencroker 

Sorry I didn't get pinged for some reason. Here's some screenshots of it:

![Screen Shot 2022-07-28 at 10 30 20 AM](https://user-images.githubusercontent.com/104027602/181550863-afa87393-452c-49ed-ae62-217ac77b2cb6.png)

![Screen Shot 2022-07-28 at 10 31 19 AM](https://user-images.githubusercontent.com/104027602/181550996-aa4f8ac3-eba3-4750-a3c5-24a7919a90bc.png)

```
<!-- Cached by Blitz on 2022-07-28T10:06:12-04:00 -->
https:\/\/www.breezeline.com\/fcc-info","description":null,"audience":null,"icon":null,"items":null},{"text":"Privacy","url":"https:\/\/www.breezeline.com\/privacy","description":null,"audience":null,"icon":null,"items":null},{"text":"e911","url":"https:\/\/www.breezeline.com\/e911","description":null,"audience":null,"icon":null,"items":null},{"text":"Legal","url":"https:\/\/www.breezeline.com\/policies-agreements","description":null,"audience":null,"icon":null,"items":null},{"text":"FCC Public Files","url":"https:\/\/www.breezeline.com\/internet-voice\/fcc-public-files","description":null,"audience":null,"icon":null,"items":null}]"
        :social-links="[{"text":"","url":"https:\/\/twitter.com\/breezeline","description":null,"audience":null,"icon":"\/assets\/icons\/twitter-icon.png","items":null},{"text":"","url":"https:\/\/www.facebook.com\/breezeline","description":null,"audience":null,"icon":"\/assets\/icons\/facebook-icon.png","items":null},{"text":"","url":"https:\/\/www.instagram.com\/breezeline","description":null,"audience":null,"icon":"\/assets\/icons\/instagram-icon.png","items":null},{"text":"","url":"https:\/\/www.linkedin.com\/company\/breezeline","description":null,"audience":null,"icon":"\/assets\/icons\/linkedin-icon.png","items":null},{"text":"","url":"https:\/\/www.youtube.com\/channel\/UCdBhD60FCK49Gu4Fz7rgUUA","description":null,"audience":null,"icon":"\/assets\/icons\/youtube-icon.png","items":null}]">
```

For the following website: https://www.breezeline.com/

**Comment by bencroker** [comment]
Hmm I'm not seeing that, but I would guess it is being added by a custom plugin/module.

![Screenshot 2022-07-29 at 12 04 13](https://user-images.githubusercontent.com/57572400/181736228-37825111-4c7b-4f81-8f1d-0ed7744b57df.png)

**Comment by juangong** [comment]
We had to clear the blitz cache again to remove that markup (since it's a prod site). But it usually appears (at very random times) when we update content on an entry page, or deploy new yaml configurations for craft, and then clear the cache.

**Comment by bencroker** [comment]
Do you have any custom modules/plugins installed? If not, can you send a list of installed plugins for me to look over?

**Comment by juangong** [comment]
We have no custom modules/plugins that I'm aware of. Here's a list of what we have installed:

Typed link field
1.0.25
Table Maker
3.0.1
Sprout Fields
3.8.5
SEOmatic
3.4.37
Retour
3.1.73
Redactor
2.10.10
Neo
2.13.15
MobileDetect
1.0.2
Mix
1.5.2
Maps
3.9.4
Freeform
3.13.15
Field Manager
2.2.5
Feed Me
4.5.3
Element API
2.8.6.1
Cookie Consent Banner
1.2.9
CodeMirror
1.0.2
Blitz
3.12.5

**Comment by bencroker** [comment]
Nothing stands out at me, except that the URLs being output in that JSON code appear to be social links. Perhaps you can track down which collection of links that is and then pinpoint the issue from there.
