### ISSUE TITLE
Inactivity timeout exceeded

### ISSUE THREAD

**Issue by wsydney76** [putyourlightson/craft-blitz#418]
Since updating to Craft 4/Blitz 4 we randomly see that cache generation stops with this error:

`[2022-06-07 11:12:59] Inactivity timeout exceeded, more than 10000 ms elapsed from last data received. Operation timed out`.

There may be pages that take that long (generating a lot of image transforms), but not sure that is always the case.

Could not find a setting to increase this timeout, but I guess there is one?

Craft 4.0.4
Blitz 4.1.3
Windows 10 Pro

/Mel

**Comment by bencroker** [comment]
The timeout for HTTP requests is fixed at 10 seconds, however this should not affect cache generation. The HTTP request will timeout, so it will log the issue, but the cached page should still be generated in the background.

**Comment by wsydney76** [comment]
OK, thanks.

However, the problem is that the cache generation is immediately aborted after the timeout and no more pages are generated.

```
[2022-06-07 11:12:59] Inactivity timeout exceeded, more than 10000 ms elapsed from last data received. Operation timed out
[2022-06-07 11:12:59] Blitz cache generation complete.
```

**Comment by bencroker** [comment]
I don't think that is the case, but I'll need to investigate further.

**Comment by wsydney76** [comment]
Thanks.

Quite sure, this is how it looks for me:

![image](https://user-images.githubusercontent.com/60010597/172367370-927e4885-0f1f-41af-9d2e-ba4aa79dd146.png)

Log output like above.

/Mel

**Comment by bencroker** [comment]
I've addressed this in https://github.com/putyourlightson/craft-blitz/commit/375d2c081950330df3f350bf12c3106f7bbf69ca for the next release, feel free to test in the meantime.

**Comment by wsydney76** [comment]
Great, thanks, the job finishes now correctly!
