### ISSUE TITLE
excludedQueryStringParams Array to string error with new config settings for V4

### ISSUE THREAD

**Issue by zizther** [putyourlightson/craft-blitz#419]
I have set `excludedUriPatterns` in the blitz config file, this follows the new setting as demonstrated here https://github.com/putyourlightson/craft-blitz/blob/v4/src/config.php

I am getting this error message `Array to string conversion`  in `.../vendor/putyourlightson/craft-blitz/src/services/CacheRequestService.php at line 398`.

This is what in the config file.

```
'excludedQueryStringParams' => [
    [
        'siteId' => '',
        'queryStringParam' => 'gclid'
    ],
    [
        'siteId' => '',
        'queryStringParam' => 'fbclid'
    ],
],
```

Commenting this out also causes the issue to show.
The only thing which fixes this is using `'excludedQueryStringParams' => [],`

**Comment by bencroker** [comment]
Please provide a plugin version.

**Comment by zizther** [comment]
The moment I read that i realised this is a Craft 3 and Blitz 3 setup. Sorry!
