### ISSUE TITLE
Blitz 3.12.4 - Local Warmer renders all pages with the same HTML content

### ISSUE THREAD

**Issue by NickHolder** [putyourlightson/craft-blitz#421]
Warming content using the Local Warmer displays the same HTML content on all cached pages. 
I've been able to replicate this on an fresh Craft project.

### Steps to reproduce the issue.
1. Install craft 3.x
2. Install Blitz trial
3. Set **Included URI Patterns** to `.*`
4. Set **Cache Warmer** to `Local Warmer`
5. Create a twig file for the home page
6. Create homepage single in the CMS with the above template
7. Create a twig file for second page
8. Create a second single in the CMS with the above template
9. Create a twig file for third page
7. Create a third single in the CMS with the above template
10. Clear the blitz cache from the Utils panel
11. Warm the blitz cache from the Utils panel

### A clear and concise description of what you expected to happen.
Each page should show the the HTML content from the correct twig file.

### The plugin and Craft version numbers.
Craft 3.7.44
Blitz 3.12.4

Laravel Valet
MacOS 11.6.5
PHP version 8.0.19
MySQL 5.7.23

![Screenshot 2022-06-13 at 15 07 23](https://user-images.githubusercontent.com/1211987/173372582-175f4e3d-90fa-4d91-aa2d-2b809549a4df.png)
![Screenshot 2022-06-13 at 15 07 09](https://user-images.githubusercontent.com/1211987/173372603-ce4b9707-465e-434a-83af-d1e28c86b2d9.png)
![Screenshot 2022-06-13 at 15 06 56](https://user-images.githubusercontent.com/1211987/173372616-63d289d0-0381-4001-90ec-56bc24dfb10d.png)

**Comment by NickHolder** [comment]
I ran the same test on Craft 4 with Blitz 4 and all content was rendered correctly by the Local Warmer

**Comment by bencroker** [comment]
The Local Warmer in Blitz 3 is, as stated, experimental, and should only be used in rare cases. Specifically, using the Async Plugin or other local queue job runners can cause issues, as you've encountered. As of Blitz 4, the Local Generator is considered stable and safe to use.

**Comment by NickHolder** [comment]
Hi, thanks for the reply. We were intending to us the Local Warmer as the site sits behind an .htpasswd and publishes via the git deployer to Cloudflare pages. Is there another method I should be using to warm the cache for git deployment with Blitz 3 in this case?

**Comment by bencroker** [comment]
Are you using the Async Plugin or a local queue job runner?

**Comment by NickHolder** [comment]
No, just using the Warm Cache button on the Utils -> Blitz Cache page.

**Comment by NickHolder** [comment]
Just to clarify we are using the Warm Cache button to test the output, our intention is to use the Refresh Cache button when deploying the site.

**Comment by bencroker** [comment]
It's tricky to give you suggestions since I cannot replicate the issue on my end. Are you testing only locally or in a staging/production environment too? The ideal solution would be to upgrade to Blitz 4, in which the Local Generator is stable.

**Comment by NickHolder** [comment]
I've been testing locally, so it might be related to my environment (Valet or Mac OS). We're going to look at upgrading the project to Craft and Blitz 4, thanks for looking into it for me.

**Comment by bencroker** [comment]
Sounds good!
