### ISSUE TITLE
Entries with future Post Dates not included in cache clearing

### ISSUE THREAD

**Issue by iainsaxon** [putyourlightson/craft-blitz#422]
I'm having issues getting pages with a future Post Date to be included in cache clearing processes and I wanted to check if I'm missing something :) .

I can see that Blitz uses a `blitz_elementexpirydates` record to tag elements that need to be cleared after a certain date. This table is populated on some entry edits (not consistently) and via the `craft blitz/cache/generate-expiry-dates` command.

Should saving (ie creating or editing) an entry also maintain a relevant `blitz_elementexpirydates` record to ensure the related cache is cleared after that date?

**DEV NOTES**

Craft CMS: 3.7.44
Blitz: 3.12.4
Timezone: +10hr (explains why dates in database are 10hrs off ;) )

I started with an empty `blitz_elementexpirydates` table:
![Screen Shot 2022-06-17 at 9 42 35 am](https://user-images.githubusercontent.com/546517/174197081-a38b73ac-474e-4686-bb04-bb3e145915e0.png)

If I update an existing entry that was active to use a future Post Date and save Blitz adds an element expiry date:
![Screen Shot 2022-06-17 at 9 43 39 am](https://user-images.githubusercontent.com/546517/174197170-54a1ae9c-b065-4117-98ff-fcc968b5a1e4.png)

If I change the Post Date to another future date the record is not updated (I was expecting the DB row would reflect the new date):
![Screen Shot 2022-06-17 at 9 44 04 am](https://user-images.githubusercontent.com/546517/174197381-35080850-c4fc-481f-8d3e-2555f788f320.png)

If I change the date again and then run the `blitz/cache/generate-expiry-dates` command the date does appear in the DB:
![Screen Shot 2022-06-17 at 9 46 45 am](https://user-images.githubusercontent.com/546517/174197439-1682628e-4b82-4aac-ac2a-3b73d0dc1dc7.png)

Here is a new entry to be saved with the truncated `blitz_elementexpirydates` table for demonstration:
![Screen Shot 2022-06-17 at 9 48 17 am](https://user-images.githubusercontent.com/546517/174197535-5cf8c623-9ec9-4dcd-b3be-0d4f8f05870a.png)

Saving the entry did not create its `blitz_elementexpirydates` record:
![Screen Shot 2022-06-17 at 9 49 13 am](https://user-images.githubusercontent.com/546517/174197559-f4da9d4d-8aa5-4e6a-93f8-a300a8fc2032.png)

**Comment by bencroker** [comment]
Thanks for reporting this, I'll take a closer look and see if I can find and fix the issue.

**Comment by bencroker** [comment]
Fixed in https://github.com/putyourlightson/craft-blitz/commit/49aa7252fe7eab36923d9f22caf9bfdbdddf4cd0 and released in version 4.1.4.

**Comment by iainsaxon** [comment]
Thanks :) . Will this fix be merged back into the v3 branch?

**Comment by bencroker** [comment]
Just released in version 3.12.5.

**Comment by iainsaxon** [comment]
Fantastic, thanks for that :) !
