### ISSUE TITLE
Blitz Hints - option to disable?

### ISSUE THREAD

**Issue by cloudgrayau** [putyourlightson/craft-blitz#424]
Are we able to have a Blitz config setting that hides Blitz Hints? The hint plugin is great for development, but ideally would be fantastic to be able to hide it once we go to production.

Thanks,
Aaron.

**Comment by bencroker** [comment]
There is one already. 
https://github.com/putyourlightson/craft-blitz/blob/8c739d0691647751b894c9431fbbe811633e5dab/src/config.php#L25-L26
