### ISSUE TITLE
Refresh options not showing

### ISSUE THREAD

**Issue by Harrisonbro** [putyourlightson/craft-blitz#426]
The config page in the admin area is shown in the screenshot below. It's missing the options for refresh mode as described in https://putyourlightson.com/plugins/blitz#refresh-mode

<img width="1018" alt="Screenshot 2022-06-23 at 17 13 20" src="https://user-images.githubusercontent.com/377366/175346320-8876cb35-d2cb-4cb9-ad7b-c43a681490f5.png">

**Comment by bencroker** [comment]
You're probably running Blitz 3, whereas the Refresh Mode was added in Blitz 4.

**Comment by Harrisonbro** [comment]
Right you are! 

Do you have a documentation page available for v3 anywhere so we can see how cache refreshing/invalidation works?

**Comment by bencroker** [comment]
We don't, but the only real difference is that the cache strategy is controlled by the two lightswitch fields in the Advanced Settings tab, both of which are documented inline.

![Screenshot 2022-06-24 at 09 38 20](https://user-images.githubusercontent.com/57572400/175487525-1879ef9f-6517-4c45-bf84-871da414f1c2.png)

**Comment by Harrisonbro** [comment]
OK, thanks. While I've got you, could you confirm how the cache is automatically purged? Does it create a queue job? We're not seeing that happening so I want to debug and see it working before we buy the plugin.

**Comment by bencroker** [comment]
Yes, via a queue job, provided a reverse proxy is configured.
