### ISSUE TITLE
Remote deployment - fatal: not in a git directory

### ISSUE THREAD

**Issue by david-richards-specsavers** [putyourlightson/craft-blitz#427]
Craft 3.7.45.1
Blitz 3.12.5

When setting up remote deployment we are getting the following error for the repo path: Error connecting to repository: fatal: not in a git directory

The directory is has git initiated with the remote origin set 

![Screenshot-2022-06-24-at-15 09 29](https://user-images.githubusercontent.com/103633638/175556429-fd38caa4-7e1b-4fad-95a7-e2b14d852ea3.jpg)

**Comment by bencroker** [comment]
If that's the case then the path must not be correct. Can you test by running this command inside of that directory?
```shell
git status
```

**Comment by david-richards-specsavers** [comment]
Hi @bencroker 

It is a git directory, I can access it via commandline and it is giving me the untracked files with `git status`

**Comment by bencroker** [comment]
Is this in a local or staging/production environment? If local and using docker, perhaps the file path is not correct? It might also perhaps be worth testing an alias such as `@root` or `@webroot` in the path.

**Comment by david-richards-specsavers** [comment]
On a staging server, not using docker and it knows that the path is correct as before that error it advised me that it needs to be able to write to that folder, after changing the permissions we now have this error.

**Comment by bencroker** [comment]
Can you ensure that the web user owns the path directory, as per https://github.com/putyourlightson/craft-blitz/issues/405#issuecomment-1132815570?

**Comment by david-richards-specsavers** [comment]
That's sorted it

Thanks
