### ISSUE TITLE
Delay Cache Warming by a few seconds

### ISSUE THREAD

**Issue by theurbanu** [putyourlightson/craft-blitz#429]
Is there a way to delay cache warming by a few seconds? The problem I'm having is when an entry is saved, the cache warms the page before ImageOptimize can finish processing the image sizes. This then causes blank image blocks on the frontend with an (unknown) url. Once I refresh the cache on the page then everything shows correctly. This wouldn't be feasible as these entries are updated through frontend forms by various users. Is there any way I can fix this?

For clarification, I noticed this happening with entries that are being edited on the frontend where new images are being uploaded

**Comment by theurbanu** [comment]
Sorry I omitted some details. I'm using Craft 3.7.45.2 and Blitz 3.12.5

**Comment by bencroker** [comment]
You can use the [EVENT_BEFORE_WARM_CACHE](https://github.com/putyourlightson/craft-blitz/blob/v3/src/drivers/warmers/BaseCacheWarmer.php#L54) event to add a delay to the cache warming process via a custom module/plugin.

```php
use putyourlightson\blitz\drivers\warmers\BaseCacheWarmer;
use yii\base\Event;

Event::on(BaseCacheWarmer::class, BaseCacheWarmer::EVENT_BEFORE_WARM_CACHE, 
    function() {     
        sleep(10);
    }
);
```

Here's the Blitz v4 equivalent.

```php
use putyourlightson\blitz\drivers\generators\BaseCacheGenerator;
use yii\base\Event;

Event::on(BaseCacheGenerator::class, BaseCacheGenerator::EVENT_BEFORE_GENERATE_CACHE,
    function() {
        sleep(10);
    }
);
```

**Comment by theurbanu** [comment]
So this works in theory however what I'm seeing is that Blitz is set to process before ImageOptimize. I'm assuming the Priority in the Queue Manager has something to do with it? "Warming Blitz Cache" shows a Priority of 100 and ImageOptimze shows a priority of 1024. Could that be the issue? If so, is there a way I can change that?

No matter what, Blitz processes first and just delays everything by the amount of time I set in the sleep function

**Comment by bencroker** [comment]
There's a `driverJobPriority` config setting you can use to control that. 
https://github.com/putyourlightson/craft-blitz/blob/fe9da1b97363c1d713da2a347bbe70529feddcad/src/config.php#L202

**Comment by theurbanu** [comment]
Perfect! Everything is working now. Thank you SO MUCH for your help and great plugin!

**Comment by bencroker** [comment]
Great!
