### ISSUE TITLE
Timeout when saving globals

### ISSUE THREAD

**Issue by Djive** [putyourlightson/craft-blitz#43]
We have 130 sites in a multi-site setup.
Installed your addon, added htaccess rule and did a full setup of all the URI patterns.
Tested the front-end of the site, and its super fast now.
Then had to change a value of a global variable on one of the sites, but couldn't do it, was just getting a time-out.
Turned off the addon and then I managed to save it.
Turned out it was 'Warm Cache Automatically' setting that was causing this.
When I turned that off, then everything started working normally.

Does the addon try to clear and warm up all the sites caches when global variable for 1 site is saved?

Would definetly like to have 'Warm Cache Automatically' option turned on, since we do a lot of stuff via global variables.

Thanks!

Our server settings are way higher than any standard settings.
PHP version - 7.2.10
Craft Pro 3.0.33
Blitz 1.5.5

**Comment by putyourlightson** [comment]
Yes, saving a global will clear the entire cache as a global can potentially be used on every single template (a phone number in the footer for example). Can you please test with Blitz 1.8.0? Try it with a concurrency setting of between 10 and 20.

**Comment by Djive** [comment]
Tried Blitz 1.8.0 with concurrency setting on 10.
Still getting a time-out.

Also started seeing this in logs:

PDOException: SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction in /home/sitename/vendor/yiisoft/yii2/db/Command.php:1258

Next yii\db\Exception: SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction
The SQL being executed was: DELETE FROM `craft_blitz_caches` WHERE (`siteId`=123) AND (`uri`='') in /home/sitename/vendor/yiisoft/yii2/db/Schema.php:664

**Comment by putyourlightson** [comment]
Just re-read your initial message and saw that you have _130 sites_, is that correct?! I'm guessing that must result in a huge number of URLs for the cache to warm when a global is saved. Does the global affect more than one site? If not then perhaps it can be reworked into an entry? Globals should really only be things that need to be accessible by every site. We could in theory add a config setting to prevent warming the cache after a global is saved, but then the cached pages could remain stale.

Another thing you can perhaps try is warming the cache in the background using the [Async Queue plugin](https://github.com/ostark/craft-async-queue).

**Comment by Djive** [comment]
Cannot have 'Warm Cache Automatically' turned on when we want to save anything in globals.
This has always resulted in a time-out.

Now I tested saving an entry.
'Warm Cache Automatically' is still turned off.
'Concurrency' is set to 5.
Saved the entry that exists only on this one site.
This site has a total of 128 entries.
'Refreshing Blitz cache' task immediately started after saving the entry and took 24 minutes to complete.

2018-11-30 10:40:06 [-][1][-][info][craft\queue\QueueLogBehavior::beforeExec]  [79368] Refreshing Blitz cache (attempt: 1) - Started
2018-11-30 11:04:50 [-][1][-][info][craft\queue\QueueLogBehavior::afterExec]  [79368] Refreshing Blitz cache (attempt: 1) - Done (time: 1484.208s)

One of the sites has 10000+ entries and that one literally stops working when we turn the caching ON.
Just returns error 500.
Not sure if the problem is only caching or combination with something else.

**Comment by putyourlightson** [comment]
The 24 minutes to complete was most likely due to the job sitting in the queue for 23 minutes and 55 seconds. Refreshing the cache without warming will only delete a few cached pages. My guess is that your queue jobs are timing out often. Have you tried the Async Queue plugin as mentioned above?

**Comment by Djive** [comment]
Using 'Queue Manager' plugin since the begining of this project.
How can I check if the job is just sitting in the queue and not working all the time?
Both lines I pasted above were the only thing in the queue at that moment.
There was no message in the Admin area or in the Logs about it waiting or failing.

I will install the Async Queue plugin and test everything again.

**Comment by putyourlightson** [comment]
Another great plugin that helps with troubleshooting the queue is [Queue Manager](https://github.com/lukeyouell/craft-queue-manager).

**Comment by Djive** [comment]
Yes, as I mentioned in my post above, using that one since the begining of this project :)

**Comment by putyourlightson** [comment]
Ah sorry, missed that. 

To be honest, with 130 sites in a single Craft install, it may just not be feasible for Blitz to warm the cache without continually timing out. I'm curious as to the use case for so many sites, but regardless it seems that it is too many for a single server to handle.

**Comment by Djive** [comment]
We built city portals in Croatia.
Those sites are 130 Croatian towns.

For now, only 1 site has a large amount of entries in it (10000+).
This is the one that is causing a deadlock mentioned above (siteId=123).

I excluded only this 1 site from caching (with `/`), and everything is working ok now.
All other sites are caching normally.

Then I wanted to only partially exclude this big site, so I excluded only URI Patterns where those large amount of entries are located. Then, those pages with large amount of entries were opening normally but all others pages on that big site were returning 404 (actually they are returning error 500, its just that there is no template for that error). Nothing was being cached for that site at all. Checking all the logs but not seeing any deadlocks or any fresh errors or notices about this site.

Before I started any testing mentioned above, I installed "AsyncQueue" plugin aswell.

Will do imports to few other sites now, so will have more testing material.

Btw, would you recommend to disable the addon while doing lots of imports? Or maybe disable it for only site to which we are importing into?

Thanks!

**Comment by putyourlightson** [comment]
I suggest you use `.*` to exclude everything from a site.

Yes, you should probably disable the plugin before importing large amounts of data. Then warm the cache when your import is complete.

**Comment by Djive** [comment]
Used `.*` now, thanks!

You were right, it seems that Blitz tasks in queue are timing-out.
Seeing 7 attempts and 0 fails for one "Refreshing Blitz cache" task.
After a while, task seems to get removed from the queue and next task starts.

We increased "max_execution_time" even more, but it didn't help.
Maybe increasing the job timeout would be of more help? 
(as per your answer here: https://craftcms.stackexchange.com/questions/25437/queue-exec-time)

Would you be interested in looking deeper into our setup and everything.
Maybe we can improve something on our side which would resolve this.
We are willing to compensate you for your time.

Thanks.

**Comment by putyourlightson** [comment]
What are `max_execution_time` and `memory_limit` set to? 

Sure, you can email details to info@putyourlightson.net.

**Comment by Djive** [comment]
max_execution_time = 4200
memory_limit = 512M

**Comment by putyourlightson** [comment]
We just released 1.10.0 with lots of performance optimisations. Please update and let me know if you have any further issues.

**Comment by putyourlightson** [comment]
Added a `warmCacheAutomaticallyForGlobals` config setting in version 1.10.2. Setting it to `false` might help your situation.
