### ISSUE TITLE
.env based cache disabling

### ISSUE THREAD

**Issue by mattcdavis1** [putyourlightson/craft-blitz#430]
I don't see a way to disable the cache for local development except through the database. Would like to be able to disable blitz caching the same way I disable template caching (via .env + general config).

Not sure if this exists and I'm just missing it but it'd be a pain to have to update the database every time i sync it down to local.

**Comment by bencroker** [comment]
There's the `cachingEnabled` config setting that you can use in addition to environment variables.
https://github.com/putyourlightson/craft-blitz/blob/develop/src/config.php
