### ISSUE TITLE
Using `'queryStringCaching' => 2` in conjunction with `excludedQueryStringParams`

### ISSUE THREAD

**Issue by twosixcode** [putyourlightson/craft-blitz#435]
Using Blitz 3.12.0 with Craft 3.7.22

What is the expected behavior when using `'queryStringCaching' => 2` in conjunction with `excludedQueryStringParams`?

In `config/blitz.php` we have set   `'queryStringCaching' => 2` "Cache URLs with query strings as the same page"

Along with this we'd like to exclude a few query strings that, when present in the URL, would cause the URL to _NOT_ be cached as the same page. We had assumed that the `excludedQueryStringParams` setting would accomplish this when used in conjunction with  `'queryStringCaching' => 2`. 

Example configuration:

```
'queryStringCaching' => 2,
'excludedQueryStringParams' => ['sort', 'show-modal', 'product', 'solution', 'industry', 'region', 'filter', 'term', 'offset'],
```
Taking the `product` query string parameter as an example, we have found that all variations are cached as the same page. For example there would be no difference between the pages cached for the URLs `https://example.com/page?product=one` and `https://example.com/page?product=two`.  Whichever variation is loaded first is the version cached for that URL and all query string permutations of that URL.

Is that expected? Or is there something incorrect about our approach?

**Comment by bencroker** [comment]
That is the expected behaviour, the URL is seen as `https://example.com/page` in both cases.

**Comment by twosixcode** [comment]
So in other words, if we set `'queryStringCaching' => 2` there is not a way to exclude some types of URLs from this rule. With this setting it is "Cache URLs with query strings as the same page. Period, no exceptions." Is that correct?

And the `excludedQueryStringParams` setting would only be relevant if you set `'queryStringCaching' => 1`?

Is that correct?

To clarify our goal (in case there is some other way to achieve this):

We are not looking to exempt pages from caching. Merely looking to have _some_ types of query string URLs be cached as separate pages. With all other types query string URLs being treated as the same.

**Comment by bencroker** [comment]
Yes, that is correct.

> We are not looking to exempt pages from caching. Merely looking to have some types of query string URLs be cached as separate pages. With all other types query string URLs being treated as the same.

In that case, I'd probably recommend changing the setting to `Cache URLs with unique query strings as unique pages` and using `excludedQueryStringParams` to avoid some query string parameters being cached as separate pages.

**Comment by twosixcode** [comment]
> In that case, I'd probably recommend changing the setting to Cache URLs with unique query strings as unique pages and using excludedQueryStringParams to avoid some query string parameters being cached as separate pages.

Thanks, the issue with that approach is that this list of query strings we want to exempt might be a bit long and potentially unknowable. The list that we _know_ we want to treat as unique is much shorter and a known quantity.

Is there a way to achieve what we want using `queryStringCaching` rule in conjunction with `includedQueryStringParams` ?

That is, again, to mostly ignore query strings and treat as the same URL, with just a few exceptions.

**Comment by bencroker** [comment]
Yes, that is exactly what `includedQueryStringParams` is intended for.

**Comment by twosixcode** [comment]
For our goal to mostly ignore query strings and treat as the same URL, with just a few exceptions (eg `products` query string). What combination of `queryStringCaching` and `includedQueryStringParams` would you expect to work? 

Does this look correct?
```
'queryStringCaching' => 2,
'includedQueryStringParams' => [
   [
       'siteId' => '',
       'queryStringParam' => 'product',
   ],
],
```

With this configuration I still see `https://example.com/page?product=one` and `https://example.com/page?product=two` cached as the same page.

**Comment by bencroker** [comment]
As mentioned above, that setting should be set to `Cache URLs with unique query strings as unique pages`, in other words `'queryStringCaching' => 1`.

**Comment by twosixcode** [comment]
Perfect, thanks. 

With the version of Blitz we are using here this gives us the results we're looking for, to treat only a few query string parameters as relevant for caching unique URLS and treat the rest as the same URL.

```
'queryStringCaching' => 1,
'includedQueryStringParams' => ['product', 'solution', 'show-modal', 'etc'],
```

**Comment by bencroker** [comment]
Glad to hear you got it working the way you were looking for!

**Comment by KevinSleegers** [comment]
@bencroker I'm currently trying to achieve the same thing and stumbled across this issue. My config looks like this:

```
'queryStringCaching' => 1,
'includedQueryStringParams' => [
    [
        'siteId' => '',
        'queryStringParam' => 'search',
    ],
],
```

If I'm understanding this issue correctly the config should result in URL's containing '?search' not being cached. However, the pages are being cached and show the same content as the original URL (without any query string). 

Am I overlooking something, or has this functionality changed in newer versions of Blitz? I'm currently using Blitz 4.9.3.

**Comment by bencroker** [comment]
@KevinSleegers When a query string is _excluded_, it is ignored, meaning that a request to `my/page?search=abc` is treated as if it is a request to `my/page`.

**Comment by KevinSleegers** [comment]
@bencroker Thanks for your fast reply. I would like to cache URLs with query strings as the same page except for some query strings (such as ?search, ?filter, ?sort). Can you tell me or point me in the direction of what config should be used to achieve that?

**Comment by bencroker** [comment]
Set `queryStringCaching` to `1` and add query strings to ignore to the `excludedQueryStringParams` setting,.

**Comment by KevinSleegers** [comment]
Thanks, I've just tried that (after clearing the cache), but it doesn't seem to make any difference. Is there anything in particular that should be configured in the `includedQueryStringsParams` setting in order for this to work?

My config now looks like this:
![Screenshot 2023-12-18 at 15 24 10](https://github.com/putyourlightson/craft-blitz/assets/4705176/f8f2e4fd-0ec7-4af0-8e03-d63c1fa783e0)

**Comment by bencroker** [comment]
No, that should do it, but I just realised that you want to “include” `search`, rather than “exclude” it (my mistake). Does that make a difference?

**Comment by KevinSleegers** [comment]
Ah yes, that works! Pretty sure I had tried that config, but apparently not. Thanks Ben!

**Comment by bencroker** [comment]
Great!

**Comment by KevinSleegers** [comment]
I have one more question regarding server rewrites. I'm using the `Cache URLs with query strings as unique pages` server rewrite config as mentioned on https://putyourlightson.com/plugins/blitz#apache. 

The Blitz config change causes URL's with query strings that aren't defined in the `includedQueryStringParams` option to being served by Blitz instead of being served directly based on the index.html file on the server (all other URL's are being served directly). Is there a way to make this work?

**Comment by bencroker** [comment]
Please clear the cache and retest, creating a new issue for this if it is still a problem, as we’re getting off-topic now.

**Comment by KevinSleegers** [comment]
Clearing the cache resolved that issue, thanks!

I have another question about including query strings though. Is there a way to only allow included query strings for specific URL's? For example, the `search` query param is only relevant on our `/search` page, while other URL's (e.g. `/contact` or `/about-us`) don't do anything with the `search` query param and should therefore be ignored. I'm asking this because we see in our statistics that bots are targeting nearly every URL of the website with query strings which causes all those URL's to be cached by Blitz.

**Comment by bencroker** [comment]
It’s not possible to be that granular with included query string params, no. You could probably achieve this with a custom module/plugin. Here, for example, we include the `search` query string param only if the URI equals `search`.

```php

use craft\services\Plugins;
use putyourlightson\blitz\Blitz;
use yii\base\Event;

Event::on(Plugins::class, Plugins::EVENT_AFTER_LOAD_PLUGINS, function() {
    $uri = Craft::$app->getRequest()->getFullUri();
    if ($uri === 'search') {
        Blitz::$plugin->settings->includedQueryStringParams[] = [
            'siteId' => '',
            'queryStringParam' => 'search',
        ];
    }
});
```

**Comment by KevinSleegers** [comment]
Thanks, will definitely try that. If I'm not using a custom plugin, should the `Plugins::EVENT_AFTER_LOAD_PLUGINS` event still work in a custom module or will I have to use another event?

**Comment by bencroker** [comment]
Yes, it should still work. It is triggered after all plugins, including Blitz, are loaded.
