### ISSUE TITLE
Repository path ~/deploy is not a directory.

### ISSUE THREAD

**Issue by shifuma** [putyourlightson/craft-blitz#438]
I'm trying to setup Blitz to deploy to Netlify and I'm getting the errror `Repository path ~/deploy is not a directory.`

I've followed the article on setting up, and my structure is:

- Users
- - Me
- - - Sites
- - - - MySite
- - - - - cms
- - - - - deploy

I've tried adding the full path to the directory `Users/myuser/Sites/MySite/deploy` but I'm getting the same error every time. What is that expecting / what I'm I doing wrong?

![Remote Deployment Repo settings](https://user-images.githubusercontent.com/86767543/182755334-106957d6-bf15-42a1-969b-1b1e40c9d933.jpg)

![Finder Folders](https://user-images.githubusercontent.com/86767543/182755414-4e81b4ad-1acd-4ec5-b7a0-b1702bb1d031.jpg)

**Comment by bencroker** [comment]
`~` is shorthand for your home directory, so I would expect `~/Sites/MySite/deploy` and `/Users/myuser/Sites/MySite/deploy` to both work.

**Comment by shifuma** [comment]
Thanks for the reply. I get the 'is not a directory' error with both of those. There's no `blitz.log` written when saving these, and the only thing in the `web.log` is `Plugin settings saved. One or more deployer connections failed.'`

I'm running this locally with ddev. Do I need to account for the container?

**Comment by bencroker** [comment]
> I'm running this locally with ddev. Do I need to account for the container?

Probably. The best way to set the path might be via an alias, so set it to `@deploy` and then in your general config file:

```php
return [
    'aliases' => [
        '@deploy' => dirname(__DIR__, 2) . '/deploy',
    ],
];
```

**Comment by shifuma** [comment]
I forgot to comment but I got this working like this: `'@deploy' => dirname(__DIR__) . '/web/deploy',`

Not sure if that's correct but it did what I needed it today. Thanks!
