### ISSUE TITLE
Clear page and subpages in PHP

### ISSUE THREAD

**Issue by espensgr** [putyourlightson/craft-blitz#439]
We are using blitz on a page where some of the pages are not inside Craft elements, just parsed from an api.
And some of these pages have subpages, like that on the main page it is a project and the subpages are units of that.
So when the project is fetched from the api we run clearCache to remove the cache:
`Blitz::$plugin->clearCache->clearUris( [new SiteUriModel( ["siteId" => 1, "uri" => "/$o"] )] );`

But this only removes the files inside the folder and not the subpages.
Is that possible to do that with the php functions?
Like a `"uri" => "/$o/*"` wildcard type og a setting in the `clearUris`?

Using Craft 3

**Comment by espensgr** [comment]
Dont know if a solution could be to add a `->clearCacheTags(["o:$o"])`function to the `clearCache` service?

**Comment by bencroker** [comment]
There is the `SiteUriHelper::getSiteUrisFromUrls()` method that should help you do this.

```php
use putyourlightson\blitz\Blitz;
use putyourlightson\blitz\helpers\SiteUriHelper;

$siteUris = SiteUriHelper::getSiteUrisFromUrls('https://domain.com/folder/*');
Blitz::$plugin->clearCache->clearUris($siteUris);
```

**Comment by espensgr** [comment]
Got it working with this to get the page, and subpages
```
$home = Craft::getAlias( '@web' );
$siteUris = SiteUriHelper::getSiteUrisFromUrls( ["$home/$this->o", "$home/$this->o/*"] );
```
The function needed an array, not a string to.

**Comment by bencroker** [comment]
Ah yes, glad to hear you got it working!
