### ISSUE TITLE
[FR] temporarily turning off the caching

### ISSUE THREAD

**Issue by Djive** [putyourlightson/craft-blitz#44]
Ran into another situation, which could maybe be a Feature Request.

Had to turn of Blitz addon so I can do some changes on the sites.
Did that by turning of 'Caching Enabled' option in the Blitz Settings.
Also went to Utilities >> Blitz Cache and cleared all caches.
Then I changed the name of 1 category for only 1 site. 
After saving that change, I got 130 rows (for all 130 sites) in Queue Manager which all said "Refreshing Blitz cache".
Now its slowly going trough them.

Is there a way to really turn of the caching or I need to deinstall / deactivate the plugin?
Don't want to lose the settings.

Thanks!

**Comment by putyourlightson** [comment]
Disabling the "Caching Enabled" setting will prevent pages form being newly cached. The plugin will still clear stale cache as queue jobs, which is what you are seeing. Disabling the plugin should avoid the jobs from being generated without losing any settings (just don't uninstall it).

**Comment by Djive** [comment]
Ok, great!
Just one more question, for clarification.
Clearing the caches in Utilities >> Blitz Cache doesn't clear them all or?

Thanks again for your fast support!

**Comment by putyourlightson** [comment]
It clears all cached files, but not the cache invalidation logic which is stored in the database so that the plugin can continue invalidating the cache when elements are modified.
