### ISSUE TITLE
Why is Blitz still generating Blitz cache when Caching Enabled is off in Craft 4?

### ISSUE THREAD

**Issue by pixeldeluxe** [putyourlightson/craft-blitz#440]
Hi, 

Thanks for the very nice plugin. The websites we build with Blitz are lighting fast. 
When we are filling the website, Blitz is taking too much tasks so we shut it off for a while until we are ready with filling new entries.

Why is Blitz still generating Blitz cache when Caching Enabled is off in Craft 4?

Thanks in advance.

Best regards,
Martijn La Feber
Owner PixelDeluxe

**Comment by bencroker** [comment]
It shouldn't be, what exactly are you seeing that makes you think it is generating cache? Perhaps you are seeing the cache being refreshed, which is expected behaviour as long as Blitz is enabled.
