### ISSUE TITLE
Php error on QueryStringParams arrays

### ISSUE THREAD

**Issue by espensgr** [putyourlightson/craft-blitz#441]
When i activate the `includedQueryStringParams` or `excludedQueryStringParams` in the blitz.php config i get an `Array to string conversion` error.
Just commented this in from the default config.
```
'includedQueryStringParams' => [
    [
        'siteId' => '',
        'queryStringParam' => '.*',
    ],
],
```
![image](https://user-images.githubusercontent.com/3862891/187638428-61852392-201e-4b21-a02a-3dc89132ba68.png)

Using Craft 3.7.50
Blitz 3.12.6
PHP 7.4.21

**Comment by espensgr** [comment]
My bad, i had copied the v4 config example, not the v3

**Comment by bencroker** [comment]
Glad to see you figured it out!
