### ISSUE TITLE
Page is cached although the 'excludedQueryStringParams' is set

### ISSUE THREAD

**Issue by outline4** [putyourlightson/craft-blitz#442]
Hello, 

I've enabled "^newscenter" on "Included URI Patterns" and I've specified 'excludedQueryStringParams' => ['q'] in the blitz config file. 

<img width="1205" alt="Bildschirmfoto 2022-09-07 um 13 00 52" src="https://user-images.githubusercontent.com/145828/188863550-f431fe25-84ee-463b-b39f-54cc624bee13.png">

When I search for something on newscenter it caches the search query. It will stay like this until I clear the cache. 

E.g. https://motorsport.ch/de/newscenter?q=Lukas+Arnold

This will work once, and then, when searching for something else it will display the same results. 

I've cleared caches but it won't work as I expected it to work. 

Any help highly appreciated!  
Stefan

--

Craft CMS 3.7.36
Blitz 3.11.2
PHP version 7.4.3

**Comment by bencroker** [comment]
Excluding a query string parameter doesn't prevent a URI containing it from being cached. Instead, it simply behaves as if that query string was not there, which explains why the same results are being shown regardless of the query. Have you tried excluding the URI pattern `^newscenter\?q=`?

**Comment by outline4** [comment]
> Excluding a query string parameter doesn't prevent a URI containing it from being cached. Instead, it simply behaves as if that query string was not there, which explains why the same results are being shown regardless of the query. 

Wow, so I've totally misunderstand how this works. I've thought that if one of these parameters is excluded it won't cache that page. Is something like this possible: like "don't cache pages if x parameter is present"?

> Have you tried excluding the URI pattern `^newscenter\?q=`?

I've tried, but it didn't work. 

So for instance: how can I cache the "newscenter" index page but don't cache it as soon as a parameter is present?

**Comment by bencroker** [comment]
> how can I cache the "newscenter" index page but don't cache it as soon as a parameter is present?

To do that, you'd need to set the `Query String Caching` to `Do not cache URLs with query strings`.

**Comment by outline4** [comment]
Can't I have a mix?  
Like cache some parameters and others not?

**Comment by bencroker** [comment]
As previously mentioned, this should be possible by excluding the URI pattern `^newscenter\?q=`.
