### ISSUE TITLE
sitexml.xml is being served as text/html

### ISSUE THREAD

**Issue by Gnative** [putyourlightson/craft-blitz#443]
Hi Ben,

Trying to figure out this problem. I have this template sitemap.xml that is generating well the sitemap output. 
When generating the cache and deploying remotely it is showing as a folder structure `/sitemap.xml/index.html` which isn't ideal.
I have a similar issue with needing to output a json file as well.   

Have I missed a setting that might enabled this ?

Thanks

**Comment by bencroker** [comment]
What version of Blitz and Craft are you running?

**Comment by Gnative** [comment]
Craft CMS 4.2.4
Blitz 4.2.1

I tried to set this as a single page in Settings -> Sections and as a template that is included in Blitz Settings -> Cache Generation -> Custom Site URIs

**Comment by bencroker** [comment]
Thanks, this looks like a bug with how deploying pages is currently set up. I'll look into releasing a fix in the coming days.

**Comment by Gnative** [comment]
Thanks @bencroker

**Comment by bencroker** [comment]
Fixed in https://github.com/putyourlightson/craft-blitz/commit/f8d5c17a91976eb9bdb9bd3c50c82fefc3bcd94a and released in version 4.2.2.
