### ISSUE TITLE
Local Generator fails while HTTP Generator doesn't

### ISSUE THREAD

**Issue by naboo** [putyourlightson/craft-blitz#444]
We are having an issue with the Local Generator when warming the site cache. The Local Generator failes after X pages (almost always on the same page) but if we switch to the HTTP Generator it works everytime.

Attached are the console, queue and blitz log files (env. information removed).

Craft version: 4.2.3
Blitz version: 4.2.1

[queue-2022-09-16.log](https://github.com/putyourlightson/craft-blitz/files/9582927/queue-2022-09-16.log)
[console-2022-09-16.log](https://github.com/putyourlightson/craft-blitz/files/9582928/console-2022-09-16.log)
[blitz-2022-09-16.log](https://github.com/putyourlightson/craft-blitz/files/9582929/blitz-2022-09-16.log)

**Comment by bencroker** [comment]
I'm not seeing anything in the Blitz log file, which is where I would expect to see errors. Can you provide any more details about how exactly it fails?

**Comment by naboo** [comment]
So what I did now was I cleared all the logs. Then I cleared the entire cache in Blitz and ran "Generate all pages" and after page ~62 of 437 pages I just stops. Then those three log files are the ones getting created. No visitors or anything during the process. It's just me.

If I do exactly the same with the HTTP Generator all pages gets generated as they should.

Can there be something in the template(s) that the Local Generator gets stuck on which the HTTP Generator doesn't since Craft mutes the frontend error for the site? But internally twig catches it? I'm thinking about that URLHelper error.

**Comment by bencroker** [comment]
Yes, it does look like it's related.

> craft\helpers\UrlHelper::url(): Argument #1 ($path) must be of type string, null given, called in /home/craft/********.com/storage/runtime/compiled_templates/10/10e34c248e5a7b4ac207f68c4732f6ab.php on line 48

Can you check around line 48 in `/storage/runtime/compiled_templates/10/10e34c248e5a7b4ac207f68c4732f6ab.php`?

**Comment by naboo** [comment]
So here's the line @bencroker:
`\Craft::$app->getResponse()->redirect(craft\helpers\UrlHelper::url(($context["companyEntryUrl"] ?? null)), 302);`
I'm guessing there's an entry which can't be find. I'll look into this today and see if this is it.

**Comment by bencroker** [comment]
Ok, so it in indeed looks like there's a case where the value passed into `UrlHelper::url` is `null`. Perhaps you could rewrite it to be more robust by checking that `companyEntryUrl` is not null beforehand?

**Comment by naboo** [comment]
Small update. We are working through the template errors and so far whenever we fix something the Local Generator goes a little bit further. So this might be 100% twig errors. I'll report back once we are done. But maybe something to figure out anyways? Right now if there's a twig error the warming just halts.

**Comment by bencroker** [comment]
It does sound like Twig errors. Keep checking the logs until you fix them all up. I'll look into allowing the Local Generator to carry on even when it encounters errors.

**Comment by bencroker** [comment]
This should resolve the Local Generator failing, feel free to test:
https://github.com/putyourlightson/craft-blitz/commit/9b15890ec962e33ea5dec16bcdaad8e788f153da#diff-72fab4ca2c17457a2fd0ef39eeb4480369756d782bc260c7b31c65c63b7b173a

**Comment by naboo** [comment]
The Local Generator now runs as it should @bencroker. Great update! Thanks

**Comment by bencroker** [comment]
Glad to hear it, be sure to fix up those errors though, they should be logged to `blitz.log` as well now.
