### ISSUE TITLE
When updating an entrie, cache does not purge

### ISSUE THREAD

**Issue by dedoface** [putyourlightson/craft-blitz#445]
Hello,

Thank you for your plugin ! You did an amazing job ! 

But I have encountered an issue, when I want to update an entrie with Craft, to add content for example, the first time, the cache will be purged and a process of warming the cache will be added into the queue.

If between the process, I update the entrie, the cache will not be purged, so I have to wait the entire process of warming up, it takes 5 minutes for over 200 pages, to get the updated page.

Is there any solution, for example, every time I update an entrie, I want the cache purged even if we are in a process of warming up.

Kind regards.

**Comment by bencroker** [comment]
I think you are referring to the cache refresh process. 5 minutes for 200 pages sounds very slow, I suggest you ensure you are eager-loading elements in the templates for good performance practices: https://craftcms.com/docs/4.x/dev/eager-loading-elements.html

There is no way to interrupt a queue job in Craft, as far as I'm aware. Setting concurrency to 5 might help speed up the cache generation process.

<img width="667" alt="Screenshot 2022-10-06 at 12 36 31" src="https://user-images.githubusercontent.com/57572400/194292639-b0feb538-2ad6-4ba7-add4-a421f1a70444.png">

**Comment by dedoface** [comment]
I have the version 3.11.2 of your plugin. So I have another option of "Cache Warming" like in the screenshot :

<img width="992" alt="Capture d’écran 2022-10-06 à 12 50 47" src="https://user-images.githubusercontent.com/92579007/194295181-809048d9-617d-4a74-b73a-4617863d5105.png">

Even if I change the concurrency request to 5, it stills low. Did you have any suggestions ?

Kind regards !

**Comment by bencroker** [comment]
My suggestion, as above, is to focus on making your templates performant via eager-loading elements.

**Comment by bencroker** [comment]
Also, update to the latest version of the plugin!
