### ISSUE TITLE
Nginx + PHP-FPM | Defining $cache_path Using $uri Doesn't Produce File Structure Created by Blitz

### ISSUE THREAD

**Issue by curtismorte** [putyourlightson/craft-blitz#447]
Hey Ben,
I'm opening this issue as a support request, because this isn't technically an issue with the plugin code base.

**Description of the problem:**
I noticed that the timestamps at the bottom of generated files from Blitz didn't match the timestamps for generated files on the filesystem for an environment I was working on. I found this issue to be the same across all environment instances for a specific site (local dev, test, stage, production)

So at first I thought that we must have configured something wrong, but after some digging I found that the `$cache_path` variable for the [suggested nginx configuration](https://putyourlightson.com/plugins/blitz#nginx) was to blame. What I found is below:
```
# $cache_path would be set to (notice the //):
/some/path/to/public/cache/blitz/domain.com//index.php/index.html

# $cache_path should be set to:
/some/path/to/public/cache/blitz/domain.com/some-entry-slug/index.html
```

So the location directive would always fail to find local cache on the system and direct the request to PHP-FPM. The first request would generate the cache through Craft, and every successive request would be a cache hit served by Craft.
```
#- Blitz cache rewrite
set $cache_path false;
if ($request_method = GET) {
    set $cache_path /some/path/to/public/cache/blitz/$host/$uri/index.html;
}
if ($args ~ "token=") {
    set $cache_path false;
}

#- Send would-be 404 requests to the cache path or Craft
location / {
    try_files $cache_path $uri $uri/ /index.php?$query_string;
}
```
From NGINX's site, I found the following statement in the description for `$uri`, since this is an [NGINX defined variable](https://nginx.org/en/docs/http/ngx_http_core_module.html#var_uri):
>$uri
>current URI in request, [normalized](https://nginx.org/en/docs/http/ngx_http_core_module.html#location)
>The value of $uri may change during request processing, e.g. when doing internal redirects, or when using index files.

This makes sense since Craft uses an index file to serve all of its requests. It's my understanding that this is why NGINX determines the value of $uri to be `/index.php` since that's the file which is processed relative to the file root for the server directive in NGNIX:
```
http{
  server{
    root /some/path/to/files/public;
  }
}
```
> $uri is appended to the root to get the absolute path, and that's the file that Craft relies on to serve all requests (/some/path/to/files/public/index.php)

**If this is true for any standard NGINX environment using PHP-FPM, then we can't use $uri.** You can verify this with any environments you have by adding a header in your NGINX configuration file to output the value of $cache_path like so:
```
http{
  server{
    # Place outside of a location directive so you always get the header output
    add_header X-debug-message "At time of evaluation we have $uri, $host, $request_uri, and $cache_path" always;
  }
}
```

**If this is indeed an issue for standard environments, I think I found a potential solution:**
```
# Map $request_uri to $blitz_uri to create the $uri portion of the equation below:
# $request_uri = $uri$is_args$args
# The map below captures what would be the $uri that Blitz normally expects before it gets converted to index.php due to the nature of Craft CMS rewrites
map $request_uri $initial_uri {
    "~^(?<u>[^\?]+)\?(?:.*)?"  $u; # Capture the URI, excluding any query parameters
    default                    $request_uri;
}

server {
    ...
    
    # Change // -> / for all URLs, so it works for our php location block, too
    # This should be at the top of your server block before other directives to redirect
    # URLs that contain double slashes to contain single slashes
    merge_slashes off;
    rewrite (.*)//+(.*) $1/$2 permanent;
    
    set $cache_path false;
    if ($request_method = GET) {
        set $cache_path /some/path/to/public/cache/blitz/$host/$initial_uri/index.html;
    }
    if ($args ~ "token=") {
        set $cache_path false;
    }
   
    location / {
        try_files $cache_path $uri $uri/ /index.php?$query_string;
    }

}
```
> This only works if you have access add something inside the `http` directive, but before any `server` directive in the NGINX configuration file traditionally found at `/etc/nginx/nginx.conf`. So those with shared hosting might be out of luck.

**Environments I was able to replicate this in:**
1. Generic DDEV Craft CMS Setup
2. Nitro Setup
3. Generic AWS Elastic Beanstalk Managed PHP Environment
4. Generic NGINX + PHP-FPM container setup.

**Comment by bencroker** [comment]
Thank you for the detailed report and for taking the time to describe your findings. Do you have [omitScriptNameInUrls](https://craftcms.com/docs/4.x/config/general.html#omitscriptnameinurls) set to `true` in your general config settings, and if not then does changing that value make a difference?

**Comment by curtismorte** [comment]
@bencroker,
Pulled this straight from `/config/general.php`:
```
// Global settings
    '*' => [
         // Whether generated URLs should omit "index.php"
        'omitScriptNameInUrls' => true,
    ]
```
> I made sure to check it wasn't being overwritten on a per environment basis. The value is set to true for all environments.

It's worth mentioning that every entry has a `$cache_path` set to the same value:
|entry|$cache_path|
|-----|-----|
|/some-page/ | /some/path/to/public/cache/blitz/domain.com//index.php/index.html|
|/some-page/with-nesting/ | /some/path/to/public/cache/blitz/domain.com//index.php/index.html|

**Comment by curtismorte** [comment]
It's worth noting here that this issue is really independent of Craft, and is an NGINX issue specifically.

NGINX -> PHP-FPM -> Craft

The issue is at the NGINX layer/level which comes before PHP-FPM and Craft.

With that being said, I'd be curious to know if you're able to produce the same results using the `add_header` method I described.

**Comment by bencroker** [comment]
I'll test the header, but for now let's take a step back – what versions of Blitz, Craft and PHP are you running?

**Comment by curtismorte** [comment]
Versions:
```json
{
        "craftcms/cms": "4.2.5.1",
        "putyourlightson/craft-blitz": "4.2.2"
    },

```

Running PHP 8.0

**Comment by bencroker** [comment]
I did some testing and I think I see what's going on here. Adding your header does indeed output a path to `index.php`, provided the `index.html` file does not exist. As soon as a page is cached and an `index.html` file is created for it, the header outputs the correct path. In other words, the result of `$cache_path` depends on whether the page has already been cached or not.

**Comment by curtismorte** [comment]
@bencroker,
The fact that you were able to get the proper cache file to show told me that I missed something. So I went back through all of the configurations and found the smallest of typos in the following place:
```php
# /config/blitz.php
        'cacheStorageSettings' => [
            'folderPath' => '/path/here/did/not/match',  # Typo was here
            'createGzipFiles' => true,
            'countCachedFiles' => true,
        ],
```
> The `folderPath` above didn't match the $cache_path variable declaration in Nginx. Once I fixed this, I was able to get the proper cache timestamp that matched the files on the server.

Looking back on this now, I should have used a `grep` command earlier to search files for part of the timestamp string which is what made me find the path issue.

----

All things aside, when I output the value of $cache_path in a header, I get that the $cache_path value is set to `/some/path/to/public/cache/blitz/domain.com//index.php/index.html`, which serves the proper cached index.html file from the server, but it doesn't live at the path above, it lives in a place like `/some/path/to/public/cache/blitz/domain.com/entry-slug/index.html`.

**Comment by bencroker** [comment]
As mentioned above, if an `index.html` file exists for your URI, the header will output the correct path. Please test with a cached page.

**Comment by curtismorte** [comment]
@bencroker you said:
> Adding your header does indeed output a path to index.php, provided the index.html file does not exist. As soon as a page is cached and an index.html file is created for it, the header outputs the correct path. In other words, the result of $cache_path depends on whether the page has already been cached or not.

With a [new project for Craft CMS from DDEV](https://ddev.readthedocs.io/en/latest/users/quickstart/#craft-cms), I'm not able to replicate this. The header contains the same value before the cached html file is created, and after the cached html file is created.

I can verify using DDEV that PHP is always responsible for serving cache files, and not Nginx. For example, if you generate the cache file, view the cache file using the browser, and then place `echo "hi"; die();` at the top of your `index.php` file in the web folder, can you still get the cache file or does the page say "hi"?

**I was able to replicate the problem by doing the following:**
1. Create a [new project for Craft CMS from DDEV](https://ddev.readthedocs.io/en/latest/users/quickstart/#craft-cms)
2. Install Blitz Cache: `ddev composer require putyourlightson/craft-blitz -w && ddev exec php craft plugin/install blitz`
3. Enable Caching, Cache all files using `.*`
4. Create an entry type, and associated twig file
5. Create the actual entry in Craft CMS
6. Go to the URL for the entry from step 5
7. Verify that you have a cache file at /web/cache/blitz/domain/slug/index.html
8. Modify your nginx configuration file at `.ddev/nginx_full/nginx-site.conf`. Remove the line "#ddev-generated" and add your settings for [nginx found here](https://putyourlightson.com/plugins/blitz#nginx) (note that `location ~ \.php$` is the location that always gets executed, so I added $cache_path here), and run `ddev restart`
9. Load the URL from step 6. Notice the timestamp signatures from Blitz (Generated and Served).
10. Open `web/index.php` and add `echo "hi"; die();` at the very top.
11. Reload the URL from step 9. Notice how the page says "hi' and does not contain the twig template contents from step 5

What I have been trying to say this whole time is that when using Nginx with the configuration provided in the documentation, that using server rewrites doesn't actually work because PHP is still processing and returning the files on the server. This was essentially my point around `$uri` always being `/index.php`.

What setup are you using to test? Are you able to post your full nginx.conf file? If you can truly get server rewrites to work with nginx, then I'd like to figure out what the pitfalls so others could make sure to avoid them as well.

**Comment by bencroker** [comment]
I tested using DDEV and the default nginx code provided in the Blitz docs. Can you show me only the relevant part of your nginx file?

**Comment by curtismorte** [comment]
At first, I found the issue with a site we were working on. After your comment earlier today, I created a new project using DDEV, and was able to verify the issue exists.

The steps I took to setup the environment are the listed in my previous comment.

My nginx configuration file for the new DDEV environment is:
```
# ddev craftcms config

# If you want to take over this file and customize it, remove the line above
# and ddev will respect it and won't overwrite the file.
# See https://ddev.readthedocs.io/en/stable/users/extend/customization-extendibility/#providing-custom-nginx-configuration

server {
    listen 80 default_server;
    listen 443 ssl default_server;

    root /var/www/html/web;

    ssl_certificate /etc/ssl/certs/master.crt;
    ssl_certificate_key /etc/ssl/certs/master.key;

    # Cribbed from https://github.com/nystudio107/nginx-craft
    # Enable serving of static gzip files as per: http://nginx.org/en/docs/http/ngx_http_gzip_static_module.html
    gzip_static  on;
    # Enable server-side includes as per: http://nginx.org/en/docs/http/ngx_http_ssi_module.html
    ssi on;
    # Disable limits on the maximum allowed size of the client request body
    client_max_body_size 0;
    # 404 error handler
    error_page 404 /index.php?$query_string;

    include /etc/nginx/monitoring.conf;

    index index.php index.htm index.html;

    # Disable sendfile as per https://docs.vagrantup.com/v2/synced-folders/virtualbox.html
    sendfile off;
    error_log /dev/stdout info;
    access_log /var/log/nginx/access.log;

    # Change // -> / for all URLs, so it works for our php location block, too
    # This should be at the top of your server block before other directives to redirect
    # URLs that contain double slashes to contain single slashes
    merge_slashes off;
    rewrite (.*)//+(.*) $1/$2 permanent;

    set $cache_path false;
    if ($request_method = GET) {
        set $cache_path cache/blitz/$host/$uri/index.html;
    }
    if ($args ~ "token=") {
        set $cache_path false;
    }

    #- Send would-be 404 requests to the cache path or Craft
    location / {
        add_header X-debug-location "Generic location directive matched. The value for cache_path is: $cache_path";
        absolute_redirect off;
        try_files $cache_path $uri $uri/ /index.php?$query_string;
    }

    location @rewrite {
        # For D7 and above:
        # Clean URLs are handled in drupal_environment_initialize().
        rewrite ^ /index.php;
    }

    # pass the PHP scripts to FastCGI server listening on socket
    location ~ \.php$ {
        add_header X-debug-location "Header only gets processed for PHP files. The value for cache_path is: $cache_path";
        try_files $cache_path $uri $uri/ /index.php?$query_string =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass unix:/run/php-fpm.sock;
        fastcgi_buffers 16 16k;
        fastcgi_buffer_size 32k;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param SCRIPT_NAME $fastcgi_script_name;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_intercept_errors off;
        # fastcgi_read_timeout should match max_execution_time in php.ini
        fastcgi_read_timeout 10m;
        fastcgi_param SERVER_NAME $host;
        fastcgi_param HTTPS $fcgi_https;
    }

    # Prevent clients from accessing hidden files (starting with a dot)
    # This is particularly important if you store .htpasswd files in the site hierarchy
    # Access to `/.well-known/` is allowed.
    # https://www.mnot.net/blog/2010/04/07/well-known
    # https://tools.ietf.org/html/rfc5785
    location ~* /\.(?!well-known\/) {
        deny all;
    }

    # Prevent clients from accessing to backup/config/source files
    location ~* (?:\.(?:bak|conf|dist|fla|in[ci]|log|psd|sh|sql|sw[op])|~)$ {
        deny all;
    }

    include /etc/nginx/common.d/*.conf;
    include /mnt/ddev_config/nginx/*.conf;
}

```

**Comment by bencroker** [comment]
Can you try it with a leading slash, as per the docs?

```
set $cache_path /cache/blitz/$host/$uri/index.html;
```

**Comment by curtismorte** [comment]
@bencroker doh. 

Yeah, that was the source of the problem with DDEV. Mea culpa here.

**I am now seeing `$uri` being set to a proper value for DDEV.**

As for the actual environment where this issue originated from, I've traced down the problem to a location directive that was taking precedence over another location directive. Since that location directive didn't include the `$cache_path` variable in the `try_files` statement, the value for `$uri` would always be set to the index.php file for Craft. 

To anyone else that might be having issues, double check ALL location directives.

Thank you @bencroker

**Comment by bencroker** [comment]
Sure thing, glad you figured it out!

**Comment by curtismorte** [comment]
The issue is fixed in DDEV, but we're cross referencing the DDEV configuration to our production nginx configurations because the `$uri` issue is present in our production environments. This is from some setting with a location directive and the way PHP-FPM is configured along with FastCGI. When we discover the issue, I will post it here.
