### ISSUE TITLE
Blitz consumes tokens when checking if a page can be cached, which breaks user impersonation URLs

### ISSUE THREAD

**Issue by VitaliiTsilnyk** [putyourlightson/craft-blitz#448]
When there is a token included in the request (for example, a preview or an impersonation URL), Blitz tries to get the route associated with the token in the [getIsGeneratorRequest](https://github.com/putyourlightson/craft-blitz/blob/f8d5c17a91976eb9bdb9bd3c50c82fefc3bcd94a/src/services/CacheRequestService.php#L228), which in turn [consumes the token](https://github.com/craftcms/cms/blob/3c16404560f03b7c63f31cb6e368fb4787e86dd4/src/services/Tokens.php#L138-L151), and if the use count of the token is limited (for example, impersonation tokens are one-time use only), the token can be deleted by Craft.
And so in this case, when after that Craft continues to process the request, the token is not valid any more.

Steps to reproduce:

1. Set up Craft with Blitz.
2. Create a user that doesn't have access to the control panel (at least in our case, Blitz doesn't cache control panel requests and when you generate an impersonation URL for the user that has access to CP, craft uses the CP URL instead of site URL).
3. Open the user edit page, click the cog wheel on the right sidebar, and select "Copy impersonation URL...", copy the URL to the clipboard.
4. Open a private browser window and open the copied URL. It wouldn't work (you won't be logged in as the user).

When doing the same with Blitz disabled, impersonation works fine.

Craft version: Craft Pro 4.2.7
Blitz version: 4.2.2

**Comment by bencroker** [comment]
Thanks for reporting this, will release a fix soon.

**Comment by bencroker** [comment]
Fixed in https://github.com/putyourlightson/craft-blitz/commit/7dc9b98929f920e10ce428dab3ec80eb254497d7 and released in 4.2.3.
