### ISSUE TITLE
Character encoding changes and breaks page when cache query turned on

### ISSUE THREAD

**Issue by danmansfield** [putyourlightson/craft-blitz#449]
I have a page that loads some photo gallery content via json file query. e.g. url/json/entry/?id=69669
If I turn on query string caching the results get broken.
Looking at the cached results there is a character encoding issue with an apostrophe.
Instead of "title": "blah blah’s blah",
Instead of the apostrophe it produces â€™
 "title": "blah blahâ€™s blah",
Just wondered if there is some character encoding setting I'm missing?
Thanks
PHP version | 8.1.11
Craft Pro 3.7.57
Blitz | 3.12.6

**Comment by bencroker** [comment]
Where, if anywhere, are you specifying the character encoding? If the page returns JSON, using a `.json` suffix, for example `url/json/entry.json?id=69669`, might solve the encoding issue, as the MIME type will be auto-detected.

**Comment by danmansfield** [comment]
Thanks Ben - I will dig around further - perhaps it is because I also have apache rewrites to the cache and need to set apache to the correct encoding.
