### ISSUE TITLE
Handle ResaveElements job

### ISSUE THREAD

**Issue by sjelfull** [putyourlightson/craft-blitz#45]
When ResaveElements is firing, Blitz is going to listen to that and potentially add lots of jobs for every single elements. If a big section is being resaved, that will be a lot of jobs.

Instead, Blitz should patiently wait until the resave is done, tally up all the elements to work with, _then_ fire off job(s).

In Audit, I listen for a few events to control when a resave start and ends.
- https://github.com/sjelfull/craft-audit/blob/v1/src/Audit.php#L283-L311
- https://github.com/sjelfull/craft-audit/blob/v1/src/services/AuditService.php#L436

In other plugins I have taken this further, and uses the cache to save element references while the resave is going on, then process the elements at the end.

**Comment by putyourlightson** [comment]
Thanks for the suggestion. In Audit, I see that you're listening for the `Elements::EVENT_AFTER_SAVE_ELEMENT` event as well. Are you differentiating between a regular element save and a resave element done in a queue job?

**Comment by sjelfull** [comment]
Yes, I create a log record when the queue job starts, saves the id of that entry to the cache, and while the resave is going on, any records created will be grouped by that parent entry.

Once the job ends/fails, it removes that parent id and saves a final record.

**Comment by putyourlightson** [comment]
Thanks, I'll add this to the list.

**Comment by putyourlightson** [comment]
This has been addressed in 1.10.0.
