### ISSUE TITLE
Storage settings on SERVD

### ISSUE THREAD

**Issue by timprint** [putyourlightson/craft-blitz#450]
I have Blitz working locally OK and previously had it working on Production. I have just moved to Servd hosting and have some set up issues. I have followed the instructions at [https://servd.host/docs/caching-with-blitz](https://servd.host/docs/caching-with-blitz) and am not using Servd's static cache. I have that turned off.
This is my blitz config
```
return [
    // Global settings
    '*' => [
      'cachingEnabled' => true,
            'debug' => true,
            'queryStringCaching' => 1,
            'cacheStorageType' => 'putyourlightson\blitz\drivers\storage\FileStorage',
            'cacheStorageSettings' => [
                  'folderPath' => '@webroot/cache/blitz',
                  'createGzipFiles' => false,
                  'countCachedFiles' => true,
    	],
    ],

    // Dev environment settings
    'dev' => [
           'cachingEnabled' => true,
           'debug' => true,
    ],

    // Staging environment settings
    'staging' => [
            'cachingEnabled' => true,
            'debug' => true,
            'cacheStorageType' => 'putyourlightson\blitz\drivers\storage\YiiCacheStorage',
            'cacheStorageSettings' => new yii\helpers\ReplaceArrayValue([]),
    ],

      // Production environment settings
      'production' => [
            'cachingEnabled' => false,
            'cacheStorageType' => 'putyourlightson\blitz\drivers\storage\YiiCacheStorage',
            'cacheStorageSettings' => new yii\helpers\ReplaceArrayValue([]),
    ],
];
```
Local is working OK and pages are being cached.

On Staging and production on Servd the cached pages section is completely missing in the control panel
![Screenshot 2022-10-26 at 00 57 03](https://user-images.githubusercontent.com/365760/197903529-bb0883d8-165d-466b-af00-9e21e6a976b3.png)

Running `blitz/cache/refresh` in the Servd control panel on staging I get
![Screenshot 2022-10-26 at 00 58 37](https://user-images.githubusercontent.com/365760/197903759-357c15d3-8c2c-47b8-8fc8-d2c76c7bcff4.png)

Running `blitz/cache/refresh` in the Servd control panel on production I get
![Screenshot 2022-10-26 at 01 04 57](https://user-images.githubusercontent.com/365760/197904238-16dac6dc-883b-4465-b0c0-3207082fa90f.png)
I get

I am all up to date on Craft 3
```
Craft 3.7.58
Beam 2.1.5
Blitz 3.12.6
Craft Commerce 3.4.17.2
Feed Me 4.5.3
Freeform 3.13.21
Imager X v3.6.5
Mailgun 2.0.1
oEmbed 1.3.18
Preparse Field 1.4.0
Redactor 2.10.10
Retour 3.2.3
SEOmatic 3.4.40
Servd Assets and Helpers 2.7.6
Sprout Notes 2.2.3
Stripe for Craft Commerce 2.4.3
```

I'm not sure where to look to try and fix this, Servd's workflow is new to me at the moment and I'm not sure if the issue is there or if I need to change something in my blitz config. Any ideas would me much appreciated.

**Comment by bencroker** [comment]
It looks like you have `cachingEnabled` set to `false` in production.

Also, according to the instructions, Static Caching should be set to Enabled.

<img width="623" alt="Screenshot 2022-10-25 at 19 42 55" src="https://user-images.githubusercontent.com/57572400/197908084-679822a1-aa02-474b-a64c-b7013ceadbf7.png">

**Comment by timprint** [comment]
I've made those changes but still no joy.

What could cause the "Cached pages" section on the /admin/utilities/blitz-cache page in the control panel to be missing completely?

**Comment by bencroker** [comment]
Well that will only appear when using the File Storage driver. There's no reliable way to fetch the number of cached pages per site using the Yii Cache Storage driver, unfortunately.

Have you looked to see why pages are not being cached in the `blitz.log` file?

**Comment by timprint** [comment]
Ah, the cached pages panel, that makes sense. Thanks.

I think I am getting a bit closer, when I run blitz/cache/refresh the blitz.log has a lot of this.
```
2022-10-26 21:23:14 [][][debug] An exception has been thrown during the rendering of a template ("Session does not exist in a console request.").
2022-10-26 21:23:14 [][][debug] An exception has been thrown during the rendering of a template ("Session does not exist in a console request.").
2022-10-26 21:23:14 [][][debug] An exception has been thrown during the rendering of a template ("Session does not exist in a console request.").
2022-10-26 21:23:15 [][][debug] An exception has been thrown during the rendering of a template ("Session does not exist in a console request.").
```
This is a commerce site and I am showing cart info on every page like this.

`{{ craft.blitz.getTemplate('/_includes/_cart_link') }}`

I'm not sure what else in my templates is calling session info

**Comment by bencroker** [comment]
You should be seeing a full stack trace for that error in one of the Craft log files, perhaps the `console` one?

**Comment by timprint** [comment]
Hi Ben
Just to update this for reference. It was my error, I had
```
{% if cart is not defined %}
{% set cart = craft.commerce.carts.cart %}
{% endif %}
```
in my main layout template. This was causing a session error when refresh was called via console command. Moving it into a blitz dynamic content block has fixed it.

I did have another issue. Servd instructions for Blitz specify to use **Local Warmer**. I was getting multiple pages across the site cached as the same page (multiple urls all showing the same template and content). Switching to **Guzzle Warmer** has fixed this and is working on Servd at the moment. I am waiting to hear back from Servd support about whether this is likely to cause any issues going forward (Servd support have been really helpful).

**Comment by bencroker** [comment]
I believe the Servd instructions specify using the "Local Generator". The Local Warmer is a Blitz 3 concept, which was marked experimental, you can now see why. If the Guzzle Warmer works then great, but the best long-term option is to upgrade to Blitz 4 and use the Local Generator.
