### ISSUE TITLE
Unable to access Blitz settings

### ISSUE THREAD

**Issue by TGriffiths88** [putyourlightson/craft-blitz#451]
## Steps to reproduce the issue:
- Attempt to open the plugin settings panel.
- The following exception is thrown:
<img width="911" alt="image" src="https://user-images.githubusercontent.com/85160908/200547574-73f55f57-f0e0-49ea-9924-620fc3c31f3d.png">

## What I expected to happen:
The settings for Blitz should open. 

## Other notes
- I have tried removing the `blitz.php` and it still causes the same issue. 
- Also tried uninstalling and reinstalling blitz and the same problem occurs.

## The plugin and Craft version numbers.
Craft 4.3.1
Blitz 4.2.3

Update: Uninstalling and re-installing via the CMS UI seems to resolve the issue.

**Comment by bencroker** [comment]
I cannot replicate this locally. My guess is that some of the plugin files were not correctly downloaded into the project, that's the best I can do without taking a closer look. Glad to hear it's working now for you!

**Comment by TGriffiths88** [comment]
That sounds plausible. Thanks @bencroker
