### ISSUE TITLE
Question about Cache-Tags

### ISSUE THREAD

**Issue by Thijmen** [putyourlightson/craft-blitz#452]
Hi there!

I am tweaking a bit with Blitz and I'd like Blitz to automatically see which entries are being rendered on a page and create the Cache-Tags on it's own. Is this possible?

**Comment by bencroker** [comment]
Which cache tags do you mean, specifically? Blitz will automatically keep track of which elements are used on which page URIs and invalidate pages as needed.

**Comment by Thijmen** [comment]
Say our homepage. On the homepage there are several parts of entries being rendered. I would like Blitz to automatically add those rendered entries to have their internal id's added as `Cache-Tags` header, so I can uncache by tag in Cloudflare. If I need to add them by code it's no problem too (in the Twig templates), however I need some guidance on this in that case. 

I would like to express my gratitude for this plugin too, works awesome so far! Keep up the good work.

**Comment by bencroker** [comment]
Well Blitz will take care of purging the Cloudflare cache for you too, provided you set up the Cloudflare purger. There's really no need to do any of this manually. If you must set  `Cache-Tags` headers then you'll need to hook into one of the events that Blitz triggers via a module or plugin. I can send you a code sample if you'd like.

**Comment by Thijmen** [comment]
I gladly receive a sample (sharing here would be fine too). How would Blitz know when it should uncache the homepage?

**Comment by bencroker** [comment]
Part of what Blitz does is it keeps track of which elements are used on each page URI, so it can refresh the cache appropriately, see https://putyourlightson.com/plugins/blitz#how-it-works

**Comment by bencroker** [comment]
This code should get you started.

```php
use putyourlightson\blitz\events\SaveCacheEvent;
use putyourlightson\blitz\services\GenerateCacheService;

Event::on(GenerateCacheService::class, GenerateCacheService::EVENT_AFTER_SAVE_CACHE,
    function (SaveCacheEvent $event) {
        $elementIds = $event->sender->elementCaches;
        // Do something with the element IDs.
    }
);
```
