### ISSUE TITLE
SEOmatic integration causes in timeout, some sections missing on Craft 3.x ?

### ISSUE THREAD

**Issue by Romanavr** [putyourlightson/craft-blitz#455]
**Question 1**:
I have a problem with SEOmatic
We have a fairly large site with a lot of subdomains and therefore a pages(the warm up job has at least 40k pages)
The problem is that after saving the any value(e.g. in "Global SEO"), SEOmatic fires the `EVENT_INVALIDATE_CONTAINER_CACHES `event.
[As part of the integration with Blitz](https://github.com/putyourlightson/craft-blitz/blob/v3/src/drivers/integrations/SeomaticIntegration.php#L38), this starts updating the cache for the entire site.
[Blitz starts looking up URLs for all URLs](https://github.com/putyourlightson/craft-blitz/blob/v3/src/helpers/SiteUriHelper.php#L91) from all sites, resulting in a timeout.
I figured it out "empirically" by disabling/enabling parts of the code.
Is there any way to solve this problem other than increasing the PHP execution time?

**Question 2**:
I also noticed that in the blitz for version 3 of the craft, some tabs are missing.
For example, "cache generator" or "include/exclude query parameters".
Is it only available for blitz in the craft 4.x?

**Environment:**
PHP 8.1
CraftCMS 3.7.56 PRO
Blitz 3.12.6
SEOmatic 3.4.41

**Comment by bencroker** [comment]
1. Please refer to this common issue in the docs at https://putyourlightson.com/plugins/blitz#the-refresh-cache-queue-jobs-run-for-long-periods-of-time-and-sometimes-pile-up. If the Global SEO settings updated, Blitz must refresh the entire cache to ensure that the new "global" settings get applied to all pages.
2. The current version of Blitz which all the latest features is 4.2.3, so staying on Craft 3 will keep your version behind. I'd suggest updating.

**Comment by Romanavr** [comment]
> 1. Please refer to this common issue in the docs at https://putyourlightson.com/plugins/blitz#the-refresh-cache-queue-jobs-run-for-long-periods-of-time-and-sometimes-pile-up. If the Global SEO settings updated, Blitz must refresh the entire cache to ensure that the new "global" settings get applied to all pages.
> 
>     2. The current version of Blitz which all the latest features is 4.2.3, so staying on Craft 3 will keep your version behind. I'd suggest updating.

Hey @bencroker , thanks for the reply!
Just one more question. What default refresh mode in the terms of 3rd version of Blitz(Craft 3.x)?
As far as I understand it's "Clear the cache and regenerate in a queue job" ?
And I don't understand this "Clear the cache, regenerate manually or organically":
In the case of this mode, for example, if I update a global variable, will it not automatically trigger the job to warm up the cache (even if `warmCacheAutomatically` is true)? What is the difference if I just set the "Clear the cache and regenerate in a queue job" mode and turn off `warmCacheAutomatically` ? In theory, the cache should also be generated simply when visiting the page, isn't it?

**Comment by bencroker** [comment]
Those options won't be available to you in version 3, but you can recreate them with the `clearCacheAutomatically` and `warmCacheAutomatically` config settings.
https://github.com/putyourlightson/craft-blitz/blob/74e08d31f77a42ef0065aab07fcfe9a5c477f92b/src/config.php#L124-L128

For example, setting `warmCacheAutomatically` to `false` is the equivalent of the `Clear the cache, regenerate manually or organically` refresh mode.

However, if the core problem is timeouts, then perhaps you should consider using a more robust method of queue job handling, see https://nystudio107.com/blog/robust-queue-job-handling-in-craft-cms

**Comment by Romanavr** [comment]
> Those options won't be available to you in version 3, but you can recreate them with the `clearCacheAutomatically` and `warmCacheAutomatically` config settings.
> 
> https://github.com/putyourlightson/craft-blitz/blob/74e08d31f77a42ef0065aab07fcfe9a5c477f92b/src/config.php#L124-L128
> 
> For example, setting `warmCacheAutomatically` to `false` is the equivalent of the `Clear the cache, regenerate manually or organically` refresh mode.
> 
> However, if the core problem is timeouts, then perhaps you should consider using a more robust method of queue job handling, see https://nystudio107.com/blog/robust-queue-job-handling-in-craft-cms

Thank you very much for the replies, got answers to my questions.
