### ISSUE TITLE
Zone IDs

### ISSUE THREAD

**Issue by S-n-d** [putyourlightson/craft-blitz#457]
Hi,

We're using Blitz on a clients site and it has greatly improved the ttfb. Great work on the plugin! 

We're now trying to set up the Cloudflare Purger but are running in to a problem with the Zone IDs. It's a multisite setup and in the Blitz settings each site requires a Zone ID. The client tells me there is only **one** zone ID in their cloudflare control panel, because all the sites in the multisite setup are just different language versions of the main site account. And to be more specific: we're testing this on a staging version. So on domain _staging.domain.com_.  How does the matching of the Zone IDs work? 

Is there a way to test this with more debug information? I'm only getting a _One or more purger connections failed._ message in the Craft CP.

Thanks in advance for the help!

**Comment by bencroker** [comment]
Glad to hear you're enjoying Blitz!

Each domain name gets its own Zone ID in Cloudflare, so you should be able to use the same Zone ID for both sites in the production environment, and a different Zone ID for both sites in the staging environment. Let me know if that works.

**Comment by S-n-d** [comment]
Thanks for the reply Ben,

I forwarded your info and the client's response is: _staging is a subdomain, so it will be under the same main account and use the same Zone ID(s) as the production url._

But I guess this is wrong, because obviously it currently doesn't work. Am I correct in understanding there is a need for a **separate** account for the staging subdomain, hence generating different Zone IDs?

**Comment by bencroker** [comment]
Ah right, if it is a subdomain then it will likely be using the same Zone ID. Can you double check that the API Token used by Blitz has the `Cache Purge` permission enabled for the entire zone at https://dash.cloudflare.com/profile/api-tokens?

**Comment by S-n-d** [comment]
Thanks for the reply Ben, that was indeed the solution! 🙌
