### ISSUE TITLE
LocalGenerator only working in dev mode

### ISSUE THREAD

**Issue by pixelmachine** [putyourlightson/craft-blitz#458]
I've just added Blitz to a private site (requires login) so am using the LocalGenerator to generate cached pages.

On my development server this seems to generally work fine. On my production server I cannot get Blitz to generate any pages unless I switch the production environment to dev mode.

This is the error I get after running `craft blitz/cache/generate` in production (with debug enabled):
```
[2022-12-14 05:46:22] The process stopped responding, potentially due to a fatal error or calling exit. The channel closed unexpectedly. Did the context die?
[2022-12-14 05:46:22] Blitz cache generation complete.
```

The cache is generated correctly when visiting pages manually.

Here's my config:
```php
<?php

use craft\helpers\App;

$isDev = App::env('ENVIRONMENT') === 'dev';
$isProd = App::env('ENVIRONMENT') === 'production';

return [
    '*' => [
        'debug' => $isDev,
        'hintsEnabled' => $isDev,
        'cachingEnabled' => $isProd,
        'refreshMode' => 3,
        'includedUriPatterns' => [
           [
               'siteId' => '',
               'uriPattern' => '.*',
           ],
        ],
        'excludedUriPatterns' => [
           [
               'siteId' => '',
               'uriPattern' => 'search',
           ],
           [
               'siteId' => '',
               'uriPattern' => 'logout',
           ],
        ],
        'cacheStorageType' => 'putyourlightson\blitz\drivers\storage\FileStorage',
        'cacheStorageSettings' => [
           'folderPath' => App::env('DEFAULT_CACHE_ROOT'),
           'createGzipFiles' => true,
           'countCachedFiles' => true,
        ],
        'cacheGeneratorType' => 'putyourlightson\blitz\drivers\generators\LocalGenerator',
        'cacheGeneratorSettings' => ['concurrency' => 3],
    ],
];
```

**Comment by bencroker** [comment]
Can you try setting `debug` to `true`, which should give you more details in the logs?

**Comment by pixelmachine** [comment]
Hi Ben, the error I added was with debug set to true. It's the only error I can find.

**Comment by bencroker** [comment]
I'm not sure what exactly is causing the issue, it could be to do with how you've restricted access to the site. Will the site eventually be made public or is this the intended long-term behaviour?

**Comment by pixelmachine** [comment]
It's a private catalogue, so will always be restricted. However I just checked how I'm restricting access and this snippet from the `_layout` template probably answers a big part of the puzzle:

```php
{% if craft.app.config.general.devMode != true  %}
  {% requireLogin %}
{% endif %}
```

So it's not devMode that's the issue, it's that the site requires the user to be logged in. Is there any way to generate cache pages if the whole site is restricted?

**Comment by bencroker** [comment]
No there isn't, by design, otherwise unauthenticated users could be able to view cached pages. What you could do is use [Dynamic Content](https://putyourlightson.com/plugins/blitz#dynamic-content) to get around this, if it makes sense to.

**Comment by pixelmachine** [comment]
Ok, thanks I'll take a look, feel free to close this since it's not a bug.

**Comment by pixelmachine** [comment]
Actually, just to confirm: 

A page which is manually cached i.e. the user logs in and visits that page, is essentially no longer restricted – because it's now static and therefore publicly accessible. Is that correct?

**Comment by bencroker** [comment]
If the logic for ensuring that a user is logged in happens via Twig, then it will only run on uncached pages. As soon as a pages is cached, the login requirement will no longer kick in. So you're right in thinking that restriction is essentially disabled when pages are cached. This is one scenario in which static page caching is probably not a viable solution.

**Comment by pixelmachine** [comment]
Yep ok thanks Ben, that seems completely obvious now!

Perhaps there's a case to be made that Blitz shouldn't manually cache pages with `{% requireLogin %}` either, by default? I was slowly exposing my site without realizing as I clicked around!

**Comment by bencroker** [comment]
> Perhaps there's a case to be made that Blitz shouldn't manually cache pages with {% requireLogin %} either, by default?

Perhaps, but you must have told Blitz to cache those pages, either with the catch-all include pattern of `.*` or more specific. Your options to exclude login-protected pages from being cached are to ensure they not included via an included URI pattern, to specify an excluded URI pattern, or to disable via a page specific option, for example `{% do craft.blitz.options.cachingEnabled(false) %}`.
