### ISSUE TITLE
Cache warming console command not working

### ISSUE THREAD

**Issue by michaelroper** [putyourlightson/craft-blitz#46]
Hey Ben,

I havent been able to work out if this issue is specific to my install or not, but the `./craft blitz/cache/warm` command doesn't seem to work for me from the console, either when used in my deploy script, or from the console directly. It doesn't show an error, and it seems to know how many files it needs to warm, but it just doesn't warm any.

```
./craft blitz/cache/warm
Warming Blitz cache.
0% (0/19) ETA: n/a   
5% (1/19) ETA: n/a   
10% (2/19) ETA: n/a   
15% (3/19) ETA: n/a   
21% (4/19) ETA: n/a   
26% (5/19) ETA: n/a   
31% (6/19) ETA: n/a   
36% (7/19) ETA: n/a   
42% (8/19) ETA: n/a   
47% (9/19) ETA: n/a   
52% (10/19) ETA: n/a   
57% (11/19) ETA: n/a   
63% (12/19) ETA: n/a   
68% (13/19) ETA: n/a   
73% (14/19) ETA: n/a   
78% (15/19) ETA: n/a   
84% (16/19) ETA: n/a   
89% (17/19) ETA: n/a   
94% (18/19) ETA: n/a   
100% (19/19) ETA: n/a   
100% (19/19) ETA: n/a   
Blitz cache successfully warmed 0 files.
```
The odd part is, if I trigger the warming from within the CP, that _does work_. Any ideas why it would behave differently? The only thing I thought it might be, is that my site doesn't yet have a public DNS entry (i'm just using a hosts entry) - but then I'd have thought it wouldn't work form the CP either if that was the issue.

**Comment by putyourlightson** [comment]
Does your site use the `@web` alias in the base URL? Does pinging the site work from the terminal? For example:
```
ping craftcms.com
```

**Comment by michaelroper** [comment]
No, I'm not using `@web` in the base url, but I am using Andrew's Multi-environment setup, like below... would that make a difference? 

```
// snip from .env.php

$httpHost = $_SERVER['HTTP_HOST'] ?? '';
$craftEnvVars = [
  'SITE_URL' => $protocol . $httpHost . '/',
  'BASE_URL' => $protocol . $httpHost . '/',
  'BASE_PATH' => realpath(dirname(__FILE__)) . '/web/',
];
```
```
// snip from config/general.php

'siteUrl' => getenv('CRAFTENV_SITE_URL'),
'aliases' => [
  '@baseUrl' => getenv('CRAFTENV_BASE_URL'),
  '@basePath' => getenv('CRAFTENV_BASE_PATH'),
 ],
```

Also, the ping does work, because I specifically added an entry to the hosts file on the server as well:
```
ping v3-test-www.vocus.com.au
PING vocus-live (127.0.0.1) 56(84) bytes of data.
64 bytes from vocus-live (127.0.0.1): icmp_seq=1 ttl=64 time=0.024 ms
```

**Comment by putyourlightson** [comment]
It looks like you're detecting the URLs from a web request. A console request doesn't come in through a URL so there'll be nothing to detect. Best to provide an absolute URL where possible.

**Comment by michaelroper** [comment]
Bingo, that was it. Makes sense. Thanks!

**Comment by putyourlightson** [comment]
Great, have clarified this in the docs for the next release.
