### ISSUE TITLE
Blitz appears to make Generating Blitz Cache jobs when it should not

### ISSUE THREAD

**Issue by joepagan** [putyourlightson/craft-blitz#460]
Hey,

An app we manage is using:

```
"craftcms/cms": "4.3.3",
"putyourlightson/craft-blitz": "4.2.3",
```

Quite frequently we see `Generating Blitz cache` in the queue.
We had turned this off when using craft v3 so it was only generated manually on a cron 3 times a day due to cache warming overwhelming the server.

I just witnessed a job get to the last page and it restarted back to page 0/~300.
Sometimes I login to the site and see several stacked up.

There are several content editors on the site throughout the day, but seemingly when I save an entry, the cache does NOT generate.

My config/blitz.php with comments/prod things redacted:

```php
<?php
use craft\helpers\App;
return [
    '*' => [
        'cachingEnabled' => true,
        'refreshMode' => 3,
        'includedUriPatterns' => [
            [
                'siteId' => 1,
                'uriPattern' => '.*',
            ],
        ],
        'cacheStorageType' => 'putyourlightson\blitz\drivers\storage\YiiCacheStorage',
        'queryStringCaching' => 1,
        'excludedQueryStringParams' => [
            [
                'siteId' => '1',
                'queryStringParam' => 'success',
            ],
        ],
        'generatePagesWithQueryStringParams' => true,
        'refreshCacheAutomaticallyForGlobals' => false,
        'refreshCacheWhenElementMovedInStructure' => false,
        'refreshCacheWhenElementSavedUnchanged' => false,
        'refreshCacheWhenElementSavedNotLive' => false,
        'sendPoweredByHeader' => false,
    ],
    'production' => [
        'cacheGeneratorType' => 'putyourlightson\blitz\drivers\generators\HttpGenerator',
        'cacheGeneratorSettings' => ['concurrency' => 3],
        'cachePurgerSettings' => [
          'zoneIds' => [
            'REDACTED' => [
              'zoneId' => App::parseEnv('$CLOUDFLARE_ZONE_ID'),
            ],
          ],
          'email' => App::parseEnv('$CLOUDFLARE_EMAIL'),
          'apiKey' => App::parseEnv('$CLOUDFLARE_API_KEY'),
        ],
        'cachePurgerType' => 'putyourlightson\blitz\drivers\purgers\CloudflarePurger',
    ],
...
```

My only thought is. that maybe I should use `'refreshMode' => 2,` instead of `3`, but reading the docs it suggests this will make no difference here.

Do you have any suggestions to prevent the non-stop generate jobs?

Thanks!

**Comment by bencroker** [comment]
Having `'refreshMode' => 3` is equivalent to `Clear the cache and regenerate in a queue job`, which does of course regenerate the cache. If you don't want regeneration to happen automatically, then you should set `'refreshMode' => 1` which is equivalent to `Clear the cache, regenerate manually or organically`. 

See `config.php` for reference.
https://github.com/putyourlightson/craft-blitz/blob/dafa085fb6877bbcd611baa6644f9da48058ec8a/src/config.php#L37-L42

**Comment by joepagan** [comment]
Sigh, thanks for pointing that out, I was sure I read these in a different order! 

Maybe it was [the order on your docs](https://putyourlightson.com/plugins/blitz#refresh-mode) being different.
