### ISSUE TITLE
Updated asset fields not reflected on page update/Blitz refresh (in specific SEOMatic context)

### ISSUE THREAD

**Issue by sonoflee** [putyourlightson/craft-blitz#461]
Hello! I'm submitting this as a support request because I'm not 100% sure of whether this is a Blitz issue or an SEOMatic issue, or whether there's a quick Blitz method I can use to fix.  Happy to file as a bug report if needed. 

On a Craft site using Blitz and SEOMatic, with an image gallery system that uses assets with custom fields like "artist," "medium," "description," etc. 

- Custom templates are used to create work "entry" pages with a URL structure of site-url/work/assetId; the asset(image) and custom asset fields are displayed on that template. 
- On these "entry" pages, I'm also using these custom asset fields to create meta titles, descriptions, and other values, via  SEOMatic's "[do seomatic.meta](https://nystudio107.com/docs/seomatic/using.html#seomatic-variables)" method - `{% do seomatic.meta.seoTitle( asset.workCaption ??? asset.workTitle ??? asset.title )%}`

I recently ran into an issue when updating the artist name, title, and description for a work. 

On **production**, where Blitz is enabled, the updated asset field values are displayed correctly on the page when saved, but the SEOmatic-generated meta tags do not update - they still display the old information for page title, meta description, etc. Refreshing the Blitz cache for that page does not have any effect.

On the **development** version of the same site, where Blitz is disabled, the updated asset field values are displayed correctly on the page _and_ in the SEOmatic-generated meta tags when saved.  The page and meta tags are also both correct if I disable the Blitz cache on production with `do craft.blitz.options({ cachingEnabled: false }) %}`.

It seems like the SEOMatic values are being cached here in a way that doesn't want to refresh, so wondering if there's a simple way to address - possibly adding a new asset Source ID attribute?  Any assistance is appreciated!

**Comment by bencroker** [comment]
> It seems like the SEOMatic values are being cached here in a way that doesn't want to refresh, so wondering if there's a simple way to address - possibly adding a new asset Source ID attribute?

Have you posted the same issue in the SEOmatic repo? From your statement above, it sounds like the issue may be more related to SEOmatic than to Blitz. Paging @khalwat in case he has any ideas.

**Comment by sonoflee** [comment]
Thanks for the response! I started here as things seem to work as expected when Blitz is disabled, but will definitely post an issue for SEOMatic as well.

**Comment by sonoflee** [comment]
Looks like it is indeed an issue with the way SEOMatic caches data and my nonstandard use of an asset rather than an entry here - [SEOmatic issue for reference](https://github.com/nystudio107/craft-seomatic/issues/1270).

**Comment by bencroker** [comment]
Glad to hear you figured out the source of the issue!
