### ISSUE TITLE
no caching for part of page

### ISSUE THREAD

**Issue by thomasbendl** [putyourlightson/craft-blitz#463]
we added accessibility options to our website https://szenario.design. I set them with JS/cookies and retrieve them with Andrews Cookie Plugin- after i write it in template to the html class attribute. How can I prevent caching for html Tag?

 html Block shouldn't be cached
```
{% block html %}
	<htm></html>
{% endblock %}
```

**Comment by thomasbendl** [comment]
made a solution with JS. Still interesting if partial template block caching is possible with blitz.

**Comment by bencroker** [comment]
Blitz allows full static page caching only, so things like this are best handled with JavaScript. If you need partial template caching then Craft's native cache tags allow that.
