### ISSUE TITLE
Refreshing Blitz Cache Queue Stuck 

### ISSUE THREAD

**Issue by petenice** [putyourlightson/craft-blitz#464]
Greetings and thanks in advance for your help.

I've just launched a new site on Craft 4 and noting that "Refreshing Blitz cache" is getting stuck in the queue. It's a robust site, with 1000+ pages, however, the error appears with a very low number of cached pages (over 100). I can replicate the error on Prod / Stage and Dev environments. 

Relevant details on DEV:
Craft 4.3.6.1 
Blitz 4.2.3
Memory Limit 512M
Max Execution Time 300

Config settings on DEV:
'refreshMode' => 3,
'queueJobTtr' => 300,

Here's a screenshot of the queue manager job ID details DEV
https://www.screencast.com/t/ISgWPotzdyJ

Details from STAGE
max_execution_time | 600
memory_limit | 1024M

I'm inclined to follow Andrew's "Robust Queue Jobs" direction (https://nystudio107.com/blog/robust-queue-job-handling-in-craft-cms) however, I think it's useful for my client to become familiar with Queue Manager, it's great to have a visual tool that shows what's happening when Blitz refreshes the cache. 

Also, curiously, the job always gets stuck during the progress at the same number, on DEV it's 70 of 163, on STAGE it's 56 of 163.

Finally, the job queue doesn't get stuck when there's a very small number of cached pages (less than 100).

**Comment by bencroker** [comment]
It looks like something is triggering a PHP error:
```
2023-01-30 23:22:33 [queue.ERROR] [craft\queue\QueueLogBehavior::afterError]  [31400] Refreshing Blitz cache (attempt: 4, pid: 63936) - Error (time: 1.149s): Array to string conversion {"memory":15044624} 
```

Can you please send a dump of the `blitz_elementqueries` database table to info@putyourlightson.com and I'll take a closer look.

**Comment by petenice** [comment]
Sent :-)

**Comment by bencroker** [comment]
Thanks! 

It looks like some of your element queries are incorrectly configured, which is throwing an exception during the cache refresh process. They all have the `limit` value set to an array of values instead of a single value:
`{"label":"4","value":"4","selected":true,"valid":true}`

If you can track this down in your templates then you should be able to resolve the issue. I've also addressed this in https://github.com/putyourlightson/craft-blitz/commit/57c54a549fb45edd154dd0a87cfae0a02c4eddaa by catching and logging the exception instead of throwing it, for the next release.

**Comment by petenice** [comment]
I found the offending element query, it's the "numberOf" variable in the limit. I'll need to refactor this, thanks for helping me track it down.

```
{% set catwraps = entry.categoryOptions.all() %}
{% for catwrap in catwraps %}
    {% set numberOf = catwrap.numberOf %}
    {% set relCatEntries = craft.entries().relatedTo(catz).id('not ' ~ currentPage).limit(numberOf).all() %} 
    {% for relCatEntry in relCatEntries %}
     // do stuff 
     {% endfor %}      
{% endfor %} 
```

**Comment by bencroker** [comment]
This should do it.

```twig
{% set numberOf = catwrap.numberOf.value %}
```
