### ISSUE TITLE
Is example in docs for source tags wrong?

### ISSUE THREAD

**Issue by curtishenson** [putyourlightson/craft-blitz#470]
On https://putyourlightson.com/plugins/blitz#source-tags it says to use `groupId` in blitz tags for categories but that doesn't seem to work for me, however `categoryGroupId` does seem to work.

This works for me: `{% do craft.blitz.options.tags(['categoryGroupId:2']) %}`
This doesn't seem to work: `{% do craft.blitz.options.tags(['groupId:2']) %}`

Are the docs wrong or maybe I'm seeing a different behavior that just looks like it is working?

**Comment by bencroker** [comment]
How are you testing whether it works or not? It looks like `groupId` is correct.
https://github.com/putyourlightson/craft-blitz/blob/0822df41c803122f1c6ba233e8cff1e414f42c64/src/helpers/ElementTypeHelper.php#L53

**Comment by curtishenson** [comment]
I generate the cached page, edit one of the categories and see if the blitz refresh cache task runs. 

Never runs with just `groupId` but does with `categoryGroupId`. Also `sectionId` works just fine. Really strange, I don't see how the way I have it works at all.

Blitz 4.2.3 and Craft 4.3.6.1 incase it matters.

**Comment by bencroker** [comment]
Have you perhaps added your own `sourceIdAttributes` via the config setting?
https://github.com/putyourlightson/craft-blitz/blob/0822df41c803122f1c6ba233e8cff1e414f42c64/src/config.php#L201-L204

**Comment by curtishenson** [comment]
No, only thing in config file is enable/disable caching.

Maybe it is actually `groupId` preventing the refresh in my case? And categoryGroupID is just allowing something else to trigger it?  I think I could test that

**Comment by bencroker** [comment]
Possibly. I just tested locally and it is working for me as expected.

**Comment by curtishenson** [comment]
I'll close this, probably something specific to my project. If testing reveals anything I'll let you know.
