### ISSUE TITLE
Issue upgrading to 4.3.0

### ISSUE THREAD

**Issue by kmmartinez** [putyourlightson/craft-blitz#473]
Hi. I've had this happen to me on the last two sites I've done Blitz Updates on.

When I run updates locally they all work fine, but once I push the changes and apply the project.yaml file on production and/or staging I receive the following error.

Your project config YAML files are expecting different versions to be installed for the following: Blitz

Exception 'yii\base\NotSupportedException' with message 'Changes to the project config are not possible while in read-only mode.'
in /app/vendor/craftcms/cms/src/services/ProjectConfig.php:503
Stack trace:
#0 /app/vendor/craftcms/cms/src/services/ProjectConfig.php(475): craft\services\ProjectConfig->_setInternal('plugins.blitz.s...', '4.3.0', 'Update plugin s...', true, false)
#1 /app/vendor/craftcms/cms/src/services/Plugins.php(866): craft\services\ProjectConfig->set('plugins.blitz.s...', '4.3.0', 'Update plugin s...')
#2 /app/vendor/craftcms/cms/src/console/controllers/MigrateController.php(373): craft\services\Plugins->updatePluginVersionInfo(Object(putyourlightson\blitz\Blitz))
#3 [internal function]: craft\console\controllers\MigrateController->actionAll()
#4 /app/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#5 /app/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#6 /app/vendor/yiisoft/yii2/console/Controller.php(180): yii\base\Controller->runAction('all', Array)
#7 /app/vendor/yiisoft/yii2/base/Module.php(552): yii\console\Controller->runAction('all', Array)
#8 /app/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('migrate/all', Array)
#9 /app/vendor/craftcms/cms/src/console/Application.php(90): yii\console\Application->runAction('migrate/all', Array)
#10 /app/vendor/yiisoft/yii2/base/Controller.php(212): craft\console\Application->runAction('migrate/all', Array)
#11 /app/vendor/craftcms/cms/src/console/Controller.php(218): yii\base\Controller->run('migrate/all', Array)
#12 /app/vendor/craftcms/cms/src/console/controllers/UpController.php(61): craft\console\Controller->run('migrate/all', Array)
#13 [internal function]: craft\console\controllers\UpController->actionIndex()
#14 /app/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#15 /app/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#16 /app/vendor/yiisoft/yii2/console/Controller.php(180): yii\base\Controller->runAction('', Array)
#17 /app/vendor/craftcms/cms/src/console/Controller.php(227): yii\console\Controller->runAction('', Array)
#18 /app/vendor/yiisoft/yii2/base/Module.php(552): craft\console\Controller->runAction('', Array)
#19 /app/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('up', Array)
#20 /app/vendor/craftcms/cms/src/console/Application.php(90): yii\console\Application->runAction('up', Array)
#21 /app/vendor/yiisoft/yii2/console/Application.php(147): craft\console\Application->runAction('up', Array)
#22 /app/vendor/craftcms/cms/src/console/Application.php(121): yii\console\Application->handleRequest(Object(craft\console\Request))
#23 /app/vendor/yiisoft/yii2/base/Application.php(384): craft\console\Application->handleRequest(Object(craft\console\Request))
#24 /app/craft(13): yii\base\Application->run()
#25 {main}

Craft version: Craft Pro 4.3.8.1

**Comment by bencroker** [comment]
Plugin updates via `composer install` (or `composer update`) need to happen _before_ project config changes can be applied. Is this part of your deployment process?

See https://craftcms.com/docs/4.x/deployment.html#simple-git for more details.

**Comment by kmmartinez** [comment]
Hi.

This is our process and what we’ve done for many Blitz updates in the past.

In the local development environment we:
1). Run craft update blitz. This updates the Blitz plugin, using composer in the background.
2). Commit any changes. During a plugin update, this would consist of changes to the Project Config, the vendor folder, and the composer.* files.
3). Push commit to Bitbucket.The Bitbucket pipeline runs. This performs the following actions on the staging environment:
4). Pulls the latest changes from the repository on Bitbucket.
5). Runs craft up --interactive=0, which applies all pending Project Config changes.What appears to have happened on the last few Blitz upgrade attempts is that when craft up runs on the staging environment, Craft is still attempting to make new Project Config changes. It fails to do this because we have allowAdminChanges disabled.

**Comment by bencroker** [comment]
The error message states:

> Your project config YAML files are expecting different versions to be installed for the following: Blitz

So it looks like running `composer install` is missing before step 5. 

This is not a Blitz issue but a general workflow issue, please read https://craftcms.com/docs/4.x/deployment.html#simple-git carefully.
