### ISSUE TITLE
Pages get pragma: no-cache header when logged in the backend

### ISSUE THREAD

**Issue by Thijmen** [putyourlightson/craft-blitz#477]
Situation:

When logged in in the backend and visiting the frontend, Craft sends a `pragma: no-cache` header. When I am not logged in (incognito window), this header is not being send (and thus being cached by Cloudflare).

How can I debug this/fix this?

Many, many thanks in advance!

**Comment by bencroker** [comment]
I need more details to help troubleshoot this.

**Comment by bencroker** [comment]
Any update on this? Is it still an issue and if so, can you provide some more details such as your Blitz settings, Craft and plugin version numbers, a URL that I can see, etc.?

**Comment by Thijmen** [comment]
Blitz: 4.3.3
Craft: 4.3.10

Blitz config:
```
return [
  '*' => [
      // With this setting enabled, Blitz will log detailed messages to `storage/logs/blitz.log`.
      'debug' => true,

      // With this setting enabled, Blitz will provide template performance hints in a utility.
      'hintsEnabled' => true,

      // With this setting enabled, Blitz will begin caching pages according to the included/excluded URI patterns. Disable this setting to prevent Blitz from caching any new pages.
      'cachingEnabled' => true,

      'queryStringCaching' => 0,

    
      // Whether elements should be cached in the database.
      'cacheElements' => true,

      // Whether element queries should be cached in the database.
      'cacheElementQueries' => true,

  

      // The value to send in the cache control header.
      'cacheControlHeader' => 'public, s-maxage=300, max-age=0', // 300s = 5 minuten

      // Whether an `X-Powered-By: Blitz` header should be sent.
      'sendPoweredByHeader' => false,

    
  ],
];

```

I am still debugging stuff deep inside vendor directory, possibly this is caused by a plugin but I am having a hard time debugging this. Any suggestions? URL is https://www.1twente.nl/nieuws

**Comment by Thijmen** [comment]
When I uncomment the `session_start()` in `yiisoft/yii2/web/Session.php` (`unfreeze` and `open` method), it does not send the `pragma: no-cache` header.

**Comment by Thijmen** [comment]
Put some debugging code, it seems to come from CacheRequestService.php; https://github.com/putyourlightson/craft-blitz/blob/develop/src/services/CacheRequestService.php#L94

<img width="691" alt="image" src="https://user-images.githubusercontent.com/383903/221645751-b4ace406-42b5-4048-8cc2-30d834ee70b7.png">

**Comment by bencroker** [comment]
The `pragma: no-cache` header tells the client (web browser in this case) not to cache the request, which is fine. I’m seeing Cloudflare caching the page on the front-end, so not sure what exactly the issue is?

<img width="726" alt="Screenshot 2023-02-27 at 12 01 23" src="https://user-images.githubusercontent.com/57572400/221646959-475e2a66-f720-44dd-a6c0-ee7f051e254d.png">

**Comment by Thijmen** [comment]
I am getting a BYPASS;
<img width="576" alt="image" src="https://user-images.githubusercontent.com/383903/221649692-c50d74b5-30aa-4d10-a96d-b594ef3909ed.png">

Sorry, I thought Pragma: no-cache was that CF does not cache it. My mistake, but can you tell me why I am getting BYPASS?

**Comment by bencroker** [comment]
According to https://developers.cloudflare.com/cache/about/default-cache-behavior, Cloudflare does not cache resources when the origin web server sends cookies in the response header, which is possibly what you're seeing happen.

> Cloudflare does not cache the resource when:
> - The Cache-Control header is set to private, no-store, no-cache, or max-age=0.
> - The Set-Cookie header exists.

**Comment by Thijmen** [comment]
That must be it then, sorry for the fuzz!

**Comment by Thijmen** [comment]
Is there a way to prevent that Craft returns a identityCookie for a user though?

**Comment by bencroker** [comment]
Yes, this has been on mind for a while and I finally removed cookies from cached responses in https://github.com/putyourlightson/craft-blitz/commit/c657ebc0ac2020e2700c51b0c1d6f056ff9920cb, for the next release.

**Comment by Thijmen** [comment]
Awesome, any ETA on this? No hurry, this would help us alot!

**Comment by bencroker** [comment]
This is part of 4.4.0 which is a relatively large release. We're hoping for this week or next week at the latest. If you'd like to help out with testing then would be great.

```
composer require putyourlightson/craft-blitz:^4.4.0-alpha.1
```

**Comment by Thijmen** [comment]
Sure, I'll take a look at it and will see if we can deploy this to our production, thanks!

**Comment by Thijmen** [comment]
Just a small question, I cannot run the alpha locally and on production 4.3.3 due to the database migrations, right?

**Comment by bencroker** [comment]
That shouldn't be an issue.
