### ISSUE TITLE
&token in Cachefiles

### ISSUE THREAD

**Issue by alexanderloewe** [putyourlightson/craft-blitz#478]
When Blitz builds the cache, it is not uncommon for the Craft CMS Preview token to be cached as well when I use {{ craft.app.request.absoluteUrl }} in the template. 

Can the plugin witness this or use the option to not include queries?

<img width="818" alt="Bildschirm­foto 2023-02-23 um 23 31 12" src="https://user-images.githubusercontent.com/69263307/221047837-24b2deab-8ec9-4645-85ea-adeb85c4378f.png">

**Comment by bencroker** [comment]
Pages with `token` parameters should not be cached by Blitz. Please provide more details about your setup so I can help you troubleshoot.

**Comment by alexanderloewe** [comment]
Hello Ben,

this is the code I use in my template, besides from that I don't do something special. The Blitz settings are the default once.

```<a class="title area_link_copy" title="{{ block.mainTitle }}" href="{{ craft.app.request.absoluteUrl }}#{{ block.mainTitle | ascii | kebab | lower }}">{{ block.mainTitle }}</a>```

I'm not sure if the probles arises when I open the page over the preview button, in that case the entry will open with the token to be views but then blitz kicks in and caches it?

That other information can i provide you?

**Comment by bencroker** [comment]
The plugin and Craft version numbers would be a good start.

**Comment by alexanderloewe** [comment]
These would be the specifications for the versions. But I think the problem exists already a little bit longer, because I found some URLs from before with the tokens in the Google Search Console.

Craft | 4.3.10
PHP version | 8.1.13
Blitz | 4.3.3

**Comment by bencroker** [comment]
Thanks, I think I see what is happening now. The cache generator adds a token parameter to URLs when generating the cache, and since you are outputting `absoluteUrl`, the token is being included. Can you find an alternative to `absoluteUrl`, as it is not recommended to use in pages that are cached.

> WARNING
> Don’t include the results of this method in places that will be cached, to avoid a cache poisoning attack.

Source: https://docs.craftcms.com/api/v4/craft-web-request.html#method-getabsoluteurl
