### ISSUE TITLE
Depends on abandoned league/uri-parser

### ISSUE THREAD

**Issue by marten-wirelab** [putyourlightson/craft-blitz#479]
When installing this plugin through composer, the following warning pops up:
`Package league/uri-parser is abandoned, you should avoid using it. No replacement was suggested.`

Reverse dependency tree is as follows:
```
league/uri-parser 1.4.1 userland URI parser RFC 3986 compliant
└──amphp/socket v1.2.0 (requires league/uri-parser ^1.4)
   └──amphp/http-client v4.6.2 (requires amphp/socket ^1)
      └──putyourlightson/craft-blitz 4.4.0 (requires amphp/http-client ^4.0)
```

I'd suggest updating dependencies of Blitz to `amphp/http-client ^5.0`, which doesn't depend on `league/uri-parser` anymore.

**Comment by bencroker** [comment]
Version 5 of `amphp/http-client` is currently in beta and requires PHP 8.1, which is greater than the Craft 4 requirement of PHP 8.0. Once it becomes stable I'll take a closer look. 

This is in no way a bug though.

**Comment by bencroker** [comment]
While I'd love to upgrade AMPHP to version 3 (which includes `amphp/http-client` v5), it contains breaking changes and depends on fibers, introduced in PHP 8.1 (see https://amphp.org/upgrade). There's no practical way of doing this while maintaining backwards compatibility with PHP 8.0, so this is going to have to wait for the Craft v5 compatible version of Blitz, which I believe will require PHP 8.1.

**Comment by kylecotter** [comment]
@bencroker is this back on your radar given Craft 5 is on the horizon? Thanks!
