### ISSUE TITLE
Caching not working

### ISSUE THREAD

**Issue by jayhlee** [putyourlightson/craft-blitz#48]
I can't seem to get Blitz to work for me. I installed the plugin, used the same settings as the Usage guide, used `^$` URI pattern to cache the homepage, created a cache/blitz directory relative to my public webroot, but nothing seems to cache. Is there something I'm missing or need to do? Apologies in advance—I'm probably missing something very basic.

**Comment by putyourlightson** [comment]
That sounds about right. Are you testing locally and does the cache folder have write permissions set?And can you test with a another specific include pattern, perhaps a single page and see if that gets cached?

**Comment by jayhlee** [comment]
I tested both locally and on a staging server using the `.*` pattern. On the local setup, the cache folder has write permissions, but nothing caches. Strangely, when I click on Warm Blitz Cache, the blitz directory within the cache directory gets deleted. My local setup is on Valet.

On my staging server, nothing gets cached when a web page is visited. But when I click on Warm Blitz Cache, caches are generated. When doing this, another directory automatically seems to get created within the cache/blitz and the cache files are saved there. 

On both local and staging environments, enableTemplateCaching is enabled and devMode is false, in case that matters.

**Comment by putyourlightson** [comment]
That's very strange. Can you send login credentials to info@putyourlightson.net and I'll take a look?

**Comment by jayhlee** [comment]
Sure. Just sent you an email.

**Comment by putyourlightson** [comment]
The issue was that pages were not being cached when visited by a logged in user, likely because the debug toolbar was enabled.
