### ISSUE TITLE
Html::svg() only available starting from craftcms/cms:4.3

### ISSUE THREAD

**Issue by WHITE-developer** [putyourlightson/craft-blitz#480]
The widget's that are added in blitz 4.3 are using the `Html::svg()` function, but this function is only added since craftcms/cms 4.3.0 (https://github.com/craftcms/cms/blob/develop/CHANGELOG.md#430---2022-10-25), this is now giving a server error when viewing the control panel

**Comment by bencroker** [comment]
Thanks and good catch! Fixed in https://github.com/putyourlightson/craft-blitz/commit/1ad523f8779265969ae13ca81c2b20e884e0699e and released in version 4.4.1.
