### ISSUE TITLE
Class "putyourlightson\campaign\helpers\StringHelper" not found

### ISSUE THREAD

**Issue by ZapaNOR** [putyourlightson/craft-blitz#481]
When using cache tags, this error appears in the logs.
It seems blitz tries to use a string helper from the campaign plugin.

**Error:**
`Class "putyourlightson\campaign\helpers\StringHelper" not found {"trace":["#0 /webapps/craftcms/vendor/putyourlightson/craft-blitz/src/services/GenerateCacheService.php(466): putyourlightson\\blitz\\services\\CacheTagsService->saveTags()","#1 /webapps/craftcms/vendor/putyourlightson/craft-blitz/src/services/CacheRequestService.php(413): putyourlightson\\blitz\\services\\GenerateCacheService->save()","#2 /webapps/craftcms/vendor/putyourlightson/craft-blitz/src/Blitz.php(307): putyourlightson\\blitz\\services\\CacheRequestService->saveAndPrepareResponse()","#3 [internal function]: putyourlightson\\blitz\\Blitz->putyourlightson\\blitz\\{closure}()","#4`

Blitz: 4.4.1
Craft CMS: 4.4

**Comment by bencroker** [comment]
Thanks for reporting that! Fixed in https://github.com/putyourlightson/craft-blitz/commit/37342ebf468e851903e9d12e0347c760267f4b3f and released in version 4.4.2.
