### ISSUE TITLE
Nginx not serving GZIP for html files

### ISSUE THREAD

**Issue by dillonbailey** [putyourlightson/craft-blitz#482]
Hey Team, we've configured our NGINX in-line with the documentation but are not quite able to get GZIP compression working for text files, namely text/html. Our CSS encoding is returning Gzip so we know it's possible with the configuration.

Our infrastructure is a LEMP stack with CloudFront as the CDN. 

GZIP is enabled on CloudFront.

We can see the GZIP files are created on the source server:
<img width="468" alt="Screenshot 2023-03-10 at 8 55 37 am" src="https://user-images.githubusercontent.com/1067872/224169468-4790772b-6b5c-46a0-a481-65b1d187b2c6.png">

This is our nginx config:

```
#Elastic Beanstalk Nginx Configuration File

user                    nginx;
error_log               /var/log/nginx/error.log warn;
pid                     /var/run/nginx.pid;
worker_processes        auto;
worker_rlimit_nofile    32136;

events {
    worker_connections  1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    include       conf.d/*.conf;

    map $http_upgrade $connection_upgrade {
        default     "upgrade";
    }

    # Bots to ban via user agent
    map $http_user_agent $limit_bots {
        default 0;
        ~*(AhrefsBot|Baiduspider|PaperLiBot) 1;
    }

    server {
        listen        80 default_server;
        access_log    /var/log/nginx/access.log main;

        client_header_timeout 240;
        client_body_timeout   240;
        keepalive_timeout     240;
        proxy_connect_timeout 240;
        proxy_send_timeout    240;
        proxy_read_timeout    240;
        send_timeout          240;
        gzip                  on;
        gzip_comp_level       5;
        # Compress all output labeled with one of the following MIME-types.
        gzip_types
            application/atom+xml
            application/javascript
            application/json
            application/ld+json
            application/manifest+json
            application/rss+xml
            application/vnd.geo+json
            application/vnd.ms-fontobject
            application/x-font-ttf
            application/x-web-app-manifest+json
            application/xhtml+xml
            application/xml
            font/opentype
            image/bmp
            image/svg+xml
            image/x-icon
            text/cache-manifest
            text/css
            text/plain
            text/vcard
            text/vnd.rim.location.xloc
            text/vtt
            text/x-component
            text/x-cross-domain-policy;
            # text/html is always compressed by HttpGzipModule

        # Include the Elastic Beanstalk generated locations
        include conf.d/elasticbeanstalk/*.conf;

        index index.html index.htm index.php;
        charset utf-8;

        # Enable serving of static gzip files as per: http://nginx.org/en/docs/http/ngx_http_gzip_static_module.html
        gzip_static  on;

        #- Blitz cache rewrite
        set $cache_path false;
        if ($request_method = GET) {
            set $cache_path /cache/blitz/$host/$uri/$args/index.html;
        }
        if ($args ~ "token=") {
            set $cache_path false;
        }

        location ~* .(?:css|js|woff|woff2)$ {
          expires 1y;
          add_header Cache-Control "public";
        }

        # Enable server-side includes as per: http://nginx.org/en/docs/http/ngx_http_ssi_module.html
        ssi on;

        # Disable limits on the maximum allowed size of the client request body
        client_max_body_size 0;

        # Ban certain bots from crawling the site
        if ($limit_bots = 1) {
            return 403;
        }

        # 404 error handler
        # error_page 404 /index.php?$query_string;

        # 301 Redirect URLs with trailing /'s as per https://webmasters.googleblog.com/2010/04/to-slash-or-not-to-slash.html
        rewrite ^/(.*)/$ /$1 permanent;

        # Change // -> / for all URLs, so it works for our php location block, too
        merge_slashes off;
        rewrite (.*)//+(.*) $1/$2 permanent;

        # Handle Do Not Track as per https://www.eff.org/dnt-policy
        location /.well-known/dnt-policy.txt {
            try_files /dnt-policy.txt /index.php?p=/dnt-policy.txt;
        }

        # Don't send the nginx version number in error pages and Server header
        server_tokens off;

        # Load configuration files from nginx-partials
        include /etc/nginx/nginx-partials/*.conf;

        # Root directory location handler
        location / {
            try_files $cache_path $uri/index.html $uri $uri/ /index.php?$query_string;
        }

        # Craft-specific location handlers to ensure AdminCP requests route through index.php
        # If you change your `cpTrigger`, change it here as well
        location ^~ /admin {
            try_files $uri $uri/ /index.php?$query_string;
        }
        location ^~ /cpresources {
            try_files $uri $uri/ /index.php?$query_string;
        }

        # Disable reading of Apache .htaccess files
        location ~ /\.ht {
            deny all;
        }

        # Misc settings
        sendfile off;
    }
}
```

**Comment by bencroker** [comment]
> Hey Team, we've configured our NGINX in-line with the documentation but are not quite able to get GZIP compression working for text files, namely text/html.

When you say “text files”, do you mean cached `index.html.gz` files? 

Can you also remove the double space in `gzip_static  on;`, just in case?

**Comment by dillonbailey** [comment]
Hey @bencroker - yup `index.html.gz`

No worries will remove that and come back.

**Comment by bencroker** [comment]
Do you have a public link you can share? If sensitive then please email to info@putyourlightson.com so I can take a look.

**Comment by dillonbailey** [comment]
@bencroker links sent via email - also space has been removed from nginx config.

**Comment by bencroker** [comment]
Thanks @dillonbailey! In the network tab of the non-CDN site, you can see that the response is indeed GZIP encoded in the `content-encoding` header and due to the transfer size being smaller than the file size. So it seems that the issue is on the CloudFront side of things.

<img width="864" alt="Screenshot 2023-03-09 at 17 02 19" src="https://user-images.githubusercontent.com/57572400/224180682-65dcfff6-6ff2-4f02-b57d-75e4ad0402bf.png">

**Comment by dillonbailey** [comment]
Thanks legend - when is the issue not CloudFront 😆 , I'll go digging and feedback what I find in case it helps anyone else!

**Comment by bencroker** [comment]
FWIW, compressing cached files in Blitz is kind of redundant when using a CDN since it will (generally) serve compressed responses by default, or at least Cloudflare does. Perhaps CloudFront has to be configured to do so?

**Comment by dillonbailey** [comment]
@bencroker after doing a little more digging, turns out that CloudFront is not compressing or serving a compressed response because there is no `Content-Length` header, makes sense in a way as it doesn't compress things that aren't worth it, and if it can't measure, then it plays it safe.

I've been digging around (literally inspecting text/html responses on known Craft sites) and even jumped over to putyourlightson.com just to see, but I can't seem to find anyone that's setting the Content-Length header for `text/html`.

I know it's probably a bit beyond your scope, but didn't know in your explorations of the nginx config updates needed to use Blitz's statically generated HTML files if you've come across this or anything similar.

Next question back to AWS is how I can get it to serve text/html as gzip compressed if the origin does the compression, which I know it does per your example above.

Thanks again

**Comment by bencroker** [comment]
Have you tried setting the `sendContentLengthHeader` config setting to `true`?
https://craftcms.com/docs/4.x/config/general.html#sendcontentlengthheader

**Comment by bencroker** [comment]
Alternatively, you could manually add this using a module/plugin, for example: (untested)

```php
Event::on(
    CacheRequestService::class,
    CacheRequestService::EVENT_AFTER_GET_RESPONSE,
    function (ResponseEvent $event) {
        $content = $event->response->content;
        $length = mb_strlen($content);
        $event->response->getHeaders()->set('Content-Length', $length);
    }
);
```
