### ISSUE TITLE
Disabled entry persists in cache

### ISSUE THREAD

**Issue by ccchapman** [putyourlightson/craft-blitz#483]
**Steps to reproduce:**

1. Set refresh mode to `Expire the cache and regenerate in a queue job`
1. Create an entry
2. Save the entry
3. Load the entry URI
4. Disable the entry
5. Wait for queue job to finish

**Expected behaviour:**

Entry URI returns 404

**Actual behaviour:**

Entry cache persists and page is returned

---

<details>
<summary>
Composer info
</summary>

<pre>
craftcms/aws-s3                            2.0.1            Amazon S3 integration for Craft CMS
craftcms/cms                               4.4.1            Craft CMS
craftcms/feed-me                           5.0.5            Import content from XML, RSS, CSV or JSON feeds into entri...
craftcms/redactor                          3.0.3            Edit rich text content in Craft CMS using Redactor by Impe...
hybridinteractive/craft-position-fieldtype v4.x-dev e0c05bb Brings back the Position fieldtype from Craft 2
korcontrol/craft-classy                    2.0.0            Twig helpers inspired by https://github.com/JedWatson/clas...
mutation/translate                         3.0.1            Translate messages in the control panel
nystudio107/craft-closure                  1.0.0            Allows you to use arrow function closures in Twig
nystudio107/craft-retour                   4.1.11           Retour allows you to intelligently redirect legacy URLs, s...
nystudio107/craft-seomatic                 4.0.20           SEOmatic facilitates modern SEO best practices & implement...
nystudio107/craft-vite                     4.0.5            Allows the use of the Vite.js next generation frontend too...
putyourlightson/craft-blitz                4.4.2            Intelligent static page caching for creating lightning-fas...
sebastianlenz/linkfield                    2.1.5            A Craft field type for selecting links
spacecatninja/imager-x                     4.1.11           Ninja powered image transforms.
spicyweb/craft-embedded-assets             3.1.1            Manage YouTube videos, Instagram photos, Twitter posts and...
spicyweb/craft-neo                         3.7.0            A Matrix-like field type that uses existing fields
topshelfcraft/environment-label            4.0.2            ...so you don't forget where you are.
topshelfcraft/wordsmith                    4.2.0            ...because you have the best words.
verbb/navigation                           2.0.16           Create navigation menus for your site.
vlucas/phpdotenv                           v5.5.0           Loads environment variables from `.env` to `getenv()`, `$_...
yiisoft/yii2-redis                         2.0.18           Redis Cache, Session and ActiveRecord for the Yii framework
yiisoft/yii2-shell                         2.0.5            The interactive shell extension for Yii framework
</pre>
</details>

**Comment by bencroker** [comment]
Thanks for reporting this, I can confirm that it is indeed an issue, will work on getting this fixed. Can you please provide the Blitz version number and Cache Storage type you are running?

**Comment by ccchapman** [comment]
We are using `FileStorage` (mounted EFS volume) and Blitz version 4.4.2.

**Comment by bencroker** [comment]
Oh and the Cache Generator type too, please?

**Comment by ccchapman** [comment]
> Oh and the Cache Generator type too, please?

HTTP Generator. 😀

**Comment by bencroker** [comment]
Thanks, I’ve addressed this in https://github.com/putyourlightson/craft-blitz/commit/f3779094d9a94d7184295e3547273a79df84e300 for the next release (scheduled for next week). 

If you’d like to test now then you can by running `composer require putyourlightson/craft-blitz:dev-develop as 4.4.3`.

**Comment by bencroker** [comment]
Released in version 4.4.3.

**Comment by ccchapman** [comment]
Confirmed working.  Thanks!
