### ISSUE TITLE
The server goes down when Blitz creates cache files

### ISSUE THREAD

**Issue by alexanderloewe** [putyourlightson/craft-blitz#484]
On a new installation of a customer I have the problem that the server goes down when Blitz starts to create the cache files.

I am not sure how the problem arises, because Craft CMS itself runes normal

**Comment by bencroker** [comment]
Can you please provide some details so I can help troubleshoot this? 
- What happens when the server goes down? 
- What do the log files say and are there any errors that might offer clues?
- What versions of Blitz and Craft is the site running?
- ...

**Comment by ambidustrious** [comment]
I've actually been experiencing this as well over the last few days... although the entire server crashes - and it seems to be related to a memory demand on my particular server. The RAM usage spikes when a cache is building.  My server only has 4GB of ram, but we are upgrading it today so see if it resolved...

**Comment by bencroker** [comment]
@ambidustrious can you please provide more details? Specifically, and at the very least, Blitz and Craft versions as well as the Blitz settings in your `project.config` file (redacting out the license number).

**Comment by alexanderloewe** [comment]
**What happens when the server goes down?**
First everything works fine then the Server starts to getting busy, and after 2 to 3 Minutes we get a 504 Error. When we restart the Server, everything works fine again. Until Blitz starts to create new files.

Craft CMS 4.3 but I will test everything on a dev site

**Comment by Romanavr** [comment]
I want to clarify that I had the same problem earlier, the server went down because it couldn't handle so many requests and so there was a request to add a timeout for the HTTP/Local generator. (Blitz 4.x)
(Reference https://github.com/putyourlightson/craft-blitz/issues/467#issuecomment-1414491399)
Is it still working, I mean timeout for amphp?
Yesterday I tried to warm up the cache on a small site (server) with 2 concurent requests.
The server has: 1 CPU core, 2 GB of RAM (DigitalOcean droplet).
And on a blitz warm-up(generate), `htop` shows me 100% CPU load. + PHP starts to work super-slowly, and the MySQL periodically crashes. Once cache generation is complete, everything returns to normal.
I understand that I can remove the cache warm-up(generate) and generate it "organically" or put 1 concurent request at all, but it seems that blitz is not very suitable for warming up small sites?

**Comment by bencroker** [comment]
The cache generation process (warming the cache) consists of sending requests to the web server. The HTTP Generator does this over HTTP requests, much like a regular site visitor, whereas the Local Generator does this via PHP processes. Regardless of which generator you use, if your site is not optimised for performance then it will struggle with lots of concurrent requests. So my recommendation, when experiencing the issue described above, is to first optimise the site using the Blitz Hints utility. Reducing the generator concurrency to `1`, which means that at most 1 request at a time will be made to the server, will also help reduce the load on the server but will also result in slower cache generation. If that still doesn’t help, then you can disable cache generation by selecting a refresh mode that refreshes the cache manually (`Clear the cache, regenerate manually or organically`, for example).

**Comment by Romanavr** [comment]
> The cache generation process (warming the cache) consists of sending requests to the web server. The HTTP Generator does this over HTTP requests, much like a regular site visitor, whereas the Local Generator does this via PHP processes. Regardless of which generator you use, if your site is not optimised for performance then it will struggle with lots of concurrent requests. So my recommendation, when experiencing the issue described above, is to first optimise the site using the Blitz Hints utility. Reducing the generator concurrency to `1`, which means that at most 1 request at a time will be made to the server, will also help reduce the load on the server but will also result in slower cache generation. If that still doesn’t help, then you can disable cache generation by selecting a refresh mode that refreshes the cache manually (`Clear the cache, regenerate manually or organically`, for example).

Yes, indeed sounds like a great recommendation. Probably worth adding to the "common issues" section.

**Comment by bencroker** [comment]
Good idea, done at https://putyourlightson.com/plugins/blitz#the-cache-generation-process-causes-the-server-to-crash
