### ISSUE TITLE
GeneratorController::_generateResponse: Return value must be of type yii\web\Response, null returned

### ISSUE THREAD

**Issue by Romanavr** [putyourlightson/craft-blitz#486]
- **Steps to reproduce the issue.**
Try to warmup/generate cache via HTTP Generator
- **A clear and concise description of what you expected to happen.**
The error should not occur.
- **If applicable, add screenshots to help explain your problem.**
- **The plugin and Craft version numbers.**
Craft Pro 4.4.2
Blitz 4.4.3
PHP 8.2

After update to 4.4.3 from 4.4.2 we're noticed error in the sentry.
`putyourlightson\blitz\controllers\GeneratorController::_generateResponse(): Return value must be of type yii\web\Response, null returned`
I checked and there is type error, should be easy to fix.
Check my PR please #485 .
Also the question is, shouldn't this error be logged in the `blitz.log`?
I see the response becomes `null `in the catch section, so it happens that something went wrong, like what?

**Comment by bencroker** [comment]
Thanks for reporting this, fixed in https://github.com/putyourlightson/craft-blitz/commit/36ba0b26c37a057c577d92d6fbddafdd1803cdec for the next release.
