### ISSUE TITLE
Tons of "Generatng image transform" on cache generate

### ISSUE THREAD

**Issue by Romanavr** [putyourlightson/craft-blitz#487]
Just ran into a weird issue, not sure if the problem is with Blitz:
I recently upgraded a project from craft 3.x to the latest craft, blitz and ImageOptimize.
When I warm up the bltz cache, it starts generating TONS(10.000 jobs+) of "Generating image transform" jobs. I checked one of the jobs and tried to find the transformId in `craft_imagetransformindex` but there was no such transform id. Any ideas what it could be?
If I restart the cache warmup, it'll start pushing jobs with the same transform ids.
We use S3 as VolumeStorage and Sharp as image converter via ImageOptimize.
Asking here only because it happens when I warm up the cache.
I will be glad for any idea.

Craft Pro 4.4.2
Blitz 4.4.2
ImageOptimize 4.0.4
HTTP generator, 3 concurrent requests, nothing changed.
![изображение](https://user-images.githubusercontent.com/3519951/225739556-ad1010a0-ae61-4789-8622-7d5485ede438.png)

**Comment by bencroker** [comment]
It sounds like as pages are being generated (warmed), missing image transforms are being queued up for generation. I imagine that once all image transforms are generated, this shouldn’t happen any more.

**Comment by Romanavr** [comment]
Okay, that makes sense the first time I do it.
We have a staging environment, so I waited for over 10,000+ jobs to complete before going live.
And then I get the same count of jobs on the live site(we're using the same storage). So it looks like for some reason the transform isn't created or the transformations are regenerated each time.

**Comment by Romanavr** [comment]
Solved this via:
`generateTransformsBeforePageLoad => true`
https://github.com/craftcms/cms/issues/12750#issuecomment-1447436787

**Comment by bencroker** [comment]
Glad to hear it, that is mentioned here too: https://putyourlightson.com/plugins/blitz#the-site-is-not-being-cached-when-i-visit-it
