### ISSUE TITLE
Auto-Refresh seems to kill all other queue jobs

### ISSUE THREAD

**Issue by Mixxey** [putyourlightson/craft-blitz#489]
After updating to the latest version (Blitz 4.4.3, Craft 4.4.5, multisite setup with subfolders on the same domain) I experience the following issue:

Whenever I change anything (be it uploading an asset or saving a changed entry), Blitz tries to refresh automatically and gets stuck at "Reserving" (much longer than the assigned 300 seconds), mo matter how long I wait, while all other queue jobs fail instantly, throwing the following error:

> The command "'/usr/local/bin/php' './craft' 'queue/exec' '40982' '3600' '1' '83' '--verbose=1' '--color='" failed. Exit Code: 1(General error) Working directory: /var/www/html Output: ================ Error Output: ================ Error: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'licenseKeyStatus' in 'field list' The SQL being executed was: SELECT `id`, `handle`, `version`, `schemaVersion`, `licenseKeyStatus`, `licensedEdition`, `installDate` FROM `plugins` ORDER BY `handle`

![image](https://user-images.githubusercontent.com/71216279/227462971-446faa9c-7eea-41f7-afbf-e35c1419ca29.png)

![image](https://user-images.githubusercontent.com/71216279/227463523-837fa8a4-82f1-4e65-842b-8d22e5ad9418.png)

![image](https://user-images.githubusercontent.com/71216279/227463088-f1677f7b-057f-4e7f-8f8d-bd22bed950dd.png)

Additional info that might be related: Also, after manually clearing and flushing the cache, it gets stuck at "Reserving" Generate Cache most of the time. Cancelling the job, refreshing and hitting "Generate Cache" again occasionally triggered the process to run successfully, but the problem described above remains.

Is there anything I can do to fix this or have I run into some bug?

Thanks a lot in advance for your help :)

**Comment by bencroker** [comment]
The error log you shared above says:
> Column not found: 1054 Unknown column 'licenseKeyStatus' in 'field list' The SQL being executed was: SELECT id, handle, version, schemaVersion, licenseKeyStatus, licensedEdition, installDate FROM plugins ORDER BY handle

Can you please share the entire stack trace so we can see where the error originates?

**Comment by bencroker** [comment]
Any update on this, @Mixxey?

**Comment by Mixxey** [comment]
@bencroker oooh sorry, I totally forgot to give you an update :see_no_evil: it appears it was just a very very strange bug with our database :sweat_smile: thanks for getting back to me!

**Comment by bencroker** [comment]
The best kind of issue is the one that resolves itself!
