### ISSUE TITLE
Cache files are not generated over queue job

### ISSUE THREAD

**Issue by alexanderloewe** [putyourlightson/craft-blitz#491]
Hello Ben,

I often use Blitz for caching all types of pages, but this time I have an issue: The cache files can't be generated over queue jobs. The job stays for days in the waiting-line and nothing happens. The problem only occurs with queue jobs from the blitz plugin

I use the option:
Clear the cache and regenerate in a queue job

PHP version	8.2.4
OS version	Linux 4.15.0-204-generic
Database driver & version	MySQL 5.7.41
Image driver & version	Imagick 3.7.0 (ImageMagick 6.9.7-4)
Craft edition & version	Craft Pro 4.4.5
Yii version	2.0.47
Twig version	v3.4.3
Guzzle version	7.5.0

Plug-ins
Blitz	4.4.4
HOMM XML Sitemap	1.0.3
Minify	4.0.0-beta.2
Neo	3.7.5
Postmark	3.0.0
Redactor	3.0.4
Retour	4.1.11
Simple Language Redirector	1.0.3
Typed link field	2.1.5

**Comment by alexanderloewe** [comment]
<img width="1183" alt="Bildschirm­foto 2023-03-28 um 09 34 42" src="https://user-images.githubusercontent.com/69263307/228162523-af87fa60-4d33-4273-93a9-30aed7dee296.png">

**Comment by bencroker** [comment]
Note that the URL patterns use regular expressions, not wild cards, so you'll likely want to use `.*` and  `/team/.*` respectively. Does that resolve the issue for you?

**Comment by alexanderloewe** [comment]
Ben, thanks for the hint.

Unfortunately this does not fix the problem, so far I had `*` and not `.*` for all pages and it always worked

With this specific page Blitz can not seem to build the cache via queue job, which was desired.

Originally the page always crashed when the queue job was supposed to generate the cache files, now no cache pages are generated at all.

**Comment by bencroker** [comment]
The `queue.log` files should be logging any exceptions that might be preventing the queue job from completing. Also enabling the `debug` Blitz config setting might result in an exception being reported in the `blitz.log` files.  See https://putyourlightson.com/plugins/blitz#debugging

**Comment by alexanderloewe** [comment]
I added the `debug` config to see that I get.

The problem is, the site has gone down again, by creating the cache files over the `queue job`.  In the `queue.log` I couldn't find any issues, but what I can say is without an active blitz plugin the site does not run into that issue.

When craft is creating the files organically, everything works fine. The server has 4gb of RAM and 2 CPUs. I run other sites with less resources, and they have 1000+ pages and I never run into issues with blitz.

Dose Blitz use the package `amphp/dns`?

**Comment by bencroker** [comment]
If you send a dump of the database along with the `composer.json` and `blitz.php` files to info@putyourlightson.com then I’ll take a closer look.

**Comment by bencroker** [comment]
I have yet to receive anything from you, are you able to share the above?

**Comment by alexanderloewe** [comment]
Hello Ben,

Currently we have made an update from Ubuntu 18 to 22. Now we are testing Craft CMS on the system.

Blitz runs normally on the shared hosting, but on the said machine Blitz did not quite want to run as we should. The queue jobs work for all operations except those from Blitz caching.

If I send you the DB and the files, you probably won't be able to recreate the problem 1 to 1.

I hope to gain some new knowledge that I can share with you, so hopefully we can fix the problem.

**Comment by bencroker** [comment]
Ok, sounds good. One other thing to perhaps consider is that if the issue is with the filesystem specifically, then it may be worth trying the Yii Cache Storage driver instead.

**Comment by bencroker** [comment]
Any update on this, @alexanderloewe?

**Comment by DavidKabelitz** [comment]
We have the same issues and it feels it started with the latest Craft Updates. Before Craft 4 ist was never a problem. We also recognized that on reload different cache versions are provided. So we always need to delete full cache on top of saving an entry. Related to this main issue, we set runQueueAutomatically to false and use craft-async-queue to trigger the waitlist. So whenever the blitz job does not start on it's own we just start a test with async and this helps to start also the blitz job.

**Comment by bencroker** [comment]
Does the Blitz refresh queue job get stuck at 0%, or what exactly happens to it, @DavidKabelitz? Please provide the versions of Craft, Blitz and PHP that the site is running.

**Comment by DavidKabelitz** [comment]
Yes stuck at 0%, sometimes it also helps to save an entry 3 times in the row. But does not feel good to overwrite the versions just for blitz ;)

Craft: 4.4.8
Blitz: 4.4.4
Php: 8.0.28

It's at a couple of Craft 4 projects, craft 3 are fine.

**Comment by bencroker** [comment]
Are you seeing any errors in the `queue.log` files?

**Comment by bencroker** [comment]
Any update on this?

**Comment by DavidKabelitz** [comment]
It feels it's connected to Auto Save, we usually had Auto Save off at config, but to be honest craft 4 does not work very well with auto save off. So we turned it on and with that also Blitz works fine again. No more problems from my side.

**Comment by bencroker** [comment]
Hmm, that is interesting, I’ll investigate further and let you know if I come up with anything.

**Comment by bencroker** [comment]
I looked into this but can’t replicate the issue in my local development environment. Updating to the latest version of Blitz and Craft, followed by clearing or refreshing the Blitz cache, might help to eliminate it. Note also that the `autosaveDrafts` config setting is deprecated and will likely be removed in Craft 5, therefore it’s probably advisable to leave it on.
