### ISSUE TITLE
Behaviour of Refresh and Refresh Expired Cache

### ISSUE THREAD

**Issue by MalcolmJohnston** [putyourlightson/craft-blitz#493]
I have a query on the behaviour of the Refresh and Refresh Expired Cache commands.  

According to the docs the Refresh command, clears, flushes, generates and deploys all the pages.  But the behaviour that I see is that Refresh and Refresh Expired only clears and flushes the cache?

Is this because I am using the refresh mode "Clear the cache, and regenerate manually or organically"?

Currently I am using the CLI command blitz/cache/generate in a CRON, but that generates all of the pages on the site, what I was hoping for was just to re-generate the expired pages.  This is where I was hoping Refresh Expired would come in but it doesn't seem to work that way. 

NOTE: I am running all of these commands from the CLI and not from the utility, in case that has any bearing.

Look forward to your thoughts.

**Comment by bencroker** [comment]
> Is this because I am using the refresh mode "Clear the cache, and regenerate manually or organically"?

Yes, this is exactly why refreshing the cache is only clearing and flushing the cache. If you also want the cache to be generated and deployed on refresh then you’ll have to select the “Clear the cache and regenerate in a queue job” refresh mode.

**Comment by MalcolmJohnston** [comment]
Thanks for getting back to me so quickly Ben.

Ok that makes total sense.  Would there be any chance of a "generate-expired" command in a future release?  That just generates the pages that have been cleared?

**Comment by bencroker** [comment]
Not without a very compelling use-case, no.

**Comment by MalcolmJohnston** [comment]
Well the use case is that when you are running under "Clear the cache, and regenerate manually or organically" mode, that ideally I would like to regenerate the expired pages frequently, to avoid them being re-generated organically.

Generating the entire site (few thousand pages) takes a while and means that this isn't really feasible.

I expect the answer will be, then you should switch refresh mode to generate in a queue job.  Which is fair enough, although I have other issues there (site does need some love to play nicely with Blitz).

**Comment by bencroker** [comment]
I get that, but your use-case is specific to your site (and its issues). Probably best to figure out the underlying issues and then change the refresh mode to regenerate automatically, if that’s more important to you.
