### ISSUE TITLE
All cache is refreshed on reorder of items in a structure

### ISSUE THREAD

**Issue by remcoov** [putyourlightson/craft-blitz#494]
Hi,

Awesome plugin! Very happy with it. I have a little issue I'd like some help with: I have a structure with 50+ entries. When I change/update something in one of these entries, the blitz cache is updated beautifully for that page and all pages it has been referenced in. But, when I reorder one of these, let's say I drag the 2nd one to the 3rd place.. all cache is being updated. Which is very heavy on my server, so you can imagine I'd like to fix this.. ;-)

FYI, my refresh mode is set to **Clear the cache and regenerate in a queue job**

Thanks in advance!!

**Comment by bencroker** [comment]
> But, when I reorder one of these, let's say I drag the 2nd one to the 3rd place.. all cache is being updated. 

This is intentional, as changing the order of entries in a structure generally requires refreshing the cache. If you prefer to disable this functionality, however, then you can do so by setting the `refreshCacheWhenElementMovedInStructure` config setting to `false`.
https://github.com/putyourlightson/craft-blitz/blob/fe3f97ae67fa982b8b65f486ee6c4d1f79b1d81d/src/config.php#L178-L179

**Comment by remcoov** [comment]
Hi ben, thanks! Am using this setting now to save my server from dying. ;-) But.. I keep thinking: why refresh every page on the whole site on a reorder? f.e. in my case I have:

- Projects index page (with 50+ project tiles)
- Project page (_mind you, I don't have any references to other projects on this page_)
- A section on the homepage which has a query to the 6 latest projects

Whenever I edit a project page (or add a new one), the cache for the above pages is being refreshed. So 3 pages. Which is the exact behaviour I'm expecting.

But whenever I reorder projects in it's structure, **all** 60+ pages on the whole website are being generated again. I'm not sure why that should be the case, when it's just supposed to update the above 3 pages?

**Comment by bencroker** [comment]
If the order of a structure changes then _every_ entry in that structure can potentially have its order changed. Blitz is being cautious and refreshing every page that the reorder could possibly affect. But if that’s an issue for your site (refreshing 60 pages shouldn’t kill your server), you have the config setting available to disable the behaviour.

**Comment by remcoov** [comment]
Hmm, ok. For me that doesn't work, but that's fine. My question would still be, how would I only refresh the 3 aforementioned pages on reorder and not all pages? Because isn't setting `refreshCacheWhenElementMovedInStructure ` to FALSE just saying: ignore the order until something else triggers the refresh of the aforementioned pages?

Regarding: "refreshing 60 pages shouldn’t kill your server". I absolutely agree.. but that's a separate issue.

**Comment by bencroker** [comment]
You’d first need to track down why changing one entry is causing so many pages to refresh. If you look in the `blitz_elementcaches` table then you’ll see the relationship between all entries and pages (`blitz_caches`), which may help you figure out whether your site has more relationships than you expect.

**Comment by remcoov** [comment]
Hi Ben, so I dove into this and bugtested a lot of scenarios. So, I actually found that the problem is that all image transformations (on a very image-heavy site..) are being done again. So that'd be about 750-1000 images being transformed and converted to webp. Once this has been done and I generate the cache again, it's a breeze and the cache generation of all pages is being done amazingly fast. So I guess the question would be: why or when does Blitz decide to transform all images again? Or does Blitz nog have anything to do with this?

FYI, I'm using [Imager-X](https://plugins.craftcms.com/imager-x?craft4), which I found has a `cacheDuration` setting. Will that have any effect bumping up from the default two weeks to a year?

Thanks

**Comment by bencroker** [comment]
Great to hear that you figured it out! Blitz has nothing to do with image transforms, so it sounds like something on the side of Imager X.

> FYI, I'm using [Imager-X](https://plugins.craftcms.com/imager-x?craft4), which I found has a cacheDuration setting. Will that have any effect bumping up from the default two weeks to a year?

The cache duration is presumably of images, so that should be fine, although I’m not 100% sure about the implications.
