### ISSUE TITLE
How to debug: File does not get deleted in /cache/blitz when page gets expired

### ISSUE THREAD

**Issue by hiasl** [putyourlightson/craft-blitz#495]
Hi,
we are experiencing the problem, that files do not get deleted from the blitz cache folder when the expiry date of an entry gets passed. It does get deleted when I actively set it to a date/time in the past and save it however.

We have both a Cronjob and I also manually called  `craft blitz/cache/refresh-expired`.
I do not get any error but I get the message "Expired Blitz cache successfully refreshed."

My guess: the Craft console command has a problem with the path to the cache directory, but we have a console command that outputs all active aliases and both @root and @webroot are correct. 

What's the best way to debug this?
Thanks

PHP version	7.4.30
OS version	Linux 4.18.0-425.13.1.el8_7.x86_64
Database driver & version	PostgreSQL 12.10
Image driver & version	GD 7.4.30
Craft edition & version	Craft Pro 3.7.56
Yii version	2.0.45
Twig version	v2.15.3
Guzzle version	7.5.0
Blitz	3.12.6

**Comment by bencroker** [comment]
Can you first check in the `blitz_elementexpirydates` database table that the element ID is listed along with its expiry date? This table is populated on element save, so if the element is missing then perhaps something got out of sync?

If that’s not the issue then, assuming you are using the Blitz File Storage driver, what is the folder path set to under Cache Storage? It also wouldn’t hurt to update to the latest version 3 of Blitz.

**Comment by hiasl** [comment]
I updated Blitz to 3.12.9

- I monitored the table `blitz_elementexpirydates` as well as the Cache directory where I would expect the cache directory/files to appear and disappear.
- I added an expiry date to the monitored entry
- A row pointing to that entry was added to `blitz_elementexpirydates`
- I loaded the entry on the frontend and a cache file was created
- I waited until the expiry date was passed
- I manually started `craft blitz/cache/refresh-expired`
- The row got in the db table got deleted but the file/directory stayed where it was

I'm using the Blitz File Storage driver and the configuration looks like that:

```
        // The storage type to use.
        'cacheStorageType' => 'putyourlightson\blitz\drivers\storage\FileStorage',

        // The storage settings.
        'cacheStorageSettings' => [
            'folderPath' => '@webroot/cache/blitz',
            'createGzipFiles' => true,
            'countCachedFiles' => false,
        ],
```

My aliases being output by a console command (CLI context):
```
@root => /srv/vhosts/craft01
@webroot => /srv/vhosts/craft01/web

```

I even tried to recursively give the cache directory full permissions (777) to make sure that file permissions are not the problem.
Again, the table row got deleted, the files/dirs stayed.

One sidenote: The cache dir is a mount of an NFS share, but creation and deletion works from the CP, so I guess this is not the reason for the behavior.

**Comment by bencroker** [comment]
To eliminate whether or not this is an issue with the console command, can you try running the command by first setting an API key under _Advanced Settings_ and then visiting the URL `/actions/blitz/cache/refresh-expired?key=1234567890`?

**Comment by bencroker** [comment]
Any update on this @hiasl?

**Comment by hiasl** [comment]
Not yet, I am waiting for feedback from a colleague who believes the problem is related to another plugin. Please keep this open. I will either close it or do the test you suggested.

**Comment by hiasl** [comment]
Took some time (as always), but 
- it is not caused by another plugin and can also not be resolved by removing it and
- I'm 99% sure that the issue is not blitz cache, but rather SITE_URL related, so Blitz can not correctly create the path to delete the cache for

Thanks for helping and sorry for taking your time with problems of our own... Closing this now.

**Comment by bencroker** [comment]
That could be, thanks for following up on it.
