### ISSUE TITLE
Blitz timing out frequently...

### ISSUE THREAD

**Issue by MattAppleton** [putyourlightson/craft-blitz#497]
Hi there...

Fairly new to Blitz so apologies if this is an obvious question...

We have a fairly large site (tavinstitute.org) — 1064 pages

The Blitz process is working, but seems to fail frequently at the moment. Typical error message:

`The process "'/opt/sp/php8.1/bin/php' 'apps/tavistock-production/craft' 'queue/exec' '149626' '300' '10' '2777916' '--color='" exceeded the timeout of 300 seconds.`

PHP max_execution_time is currently  120 — should I simply bump this up? Or is this timeout for a different process?

We also see a lot (100+) of 'Eager-load' Blitz hints — could this be something to do with the failed caching?

Many thanks for your time — and a fantastic plugin.

**Comment by bencroker** [comment]
100 eager-loading hints indicates that the templates could be _much_ more performant and is likely compounding the issue of queue jobs timing out. Ideally you would use one of the suggested [robust queue job handling](https://nystudio107.com/blog/robust-queue-job-handling-in-craft-cms) methods to prevent timeouts, but, failing that, increasing the `max_execution_time` to `300` should help.

**Comment by MattAppleton** [comment]
Hi @bencroker  — thanks for the note, checking this out...

**Comment by MattAppleton** [comment]
So far that seems to work @bencroker 


one thing — took a bit of digging to find out which config needed editing to bump up the Time To Reserve, might be worth updating the docs...

If anyone is interested we did that in config/blitz.php

```
return [
    '*' => [
        'cachingEnabled' => false,
        'queueJobTtr' => 600,
    ],
    'staging' => [
        'cachingEnabled' => true,
```
<img width="371" alt="Halite-screenshot 2023-04-20 at 16 43 48-2023-04-20" src="https://user-images.githubusercontent.com/6295710/233418440-c0f310ca-c6b6-4e01-82a8-2ee814896872.png">
