### ISSUE TITLE
Setting unknown property: `CloudflarePurger::warmCacheDelay`

### ISSUE THREAD

**Issue by kaspar-allenbach** [putyourlightson/craft-blitz#498]
I can't purge the cache anymore because this erorr message appears

It also appears when I want to access blitz settings. What is this?

```
yii\base\UnknownPropertyException: Setting unknown property: putyourlightson\blitz\drivers\purgers\CloudflarePurger::warmCacheDelay in /Users/atelierworkstation/Documents/git-local/atelier7/vendor/yiisoft/yii2/base/Component.php:209
Stack trace:
#0 /Users/atelierworkstation/Documents/git-local/atelier7/vendor/yiisoft/yii2/BaseYii.php(558): yii\base\Component->__set('warmCacheDelay', '0')
#1 /Users/atelierworkstation/Documents/git-local/atelier7/vendor/yiisoft/yii2/base/BaseObject.php(107): yii\BaseYii::configure(Object(putyourlightson\blitz\drivers\purgers\CloudflarePurger), Array)
#2 /Users/atelierworkstation/Documents/git-local/atelier7/vendor/craftcms/cms/src/base/Model.php(78): yii\base\BaseObject->__construct(Array)
#3 [internal function]: craft\base\Model->__construct(Array)
#4 /Users/atelierworkstation/Documents/git-local/atelier7/vendor/yiisoft/yii2/di/Container.php(419): ReflectionClass->newInstanceArgs(Array)
#5 /Users/atelierworkstation/Documents/git-local/atelier7/vendor/yiisoft/yii2/di/Container.php(170): yii\di\Container->build('putyourlightson...', Array, Array)
#6 /Users/atelierworkstation/Documents/git-local/atelier7/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get('putyourlightson...', Array, Array)
#7 /Users/atelierworkstation/Documents/git-local/atelier7/vendor/craftcms/cms/src/Craft.php(54): yii\BaseYii::createObject(Array, Array)
#8 /Users/atelierworkstation/Documents/git-local/atelier7/vendor/craftcms/cms/src/helpers/Component.php(122): Craft::createObject(Array)
#9 /Users/atelierworkstation/Documents/git-local/atelier7/vendor/putyourlightson/craft-blitz/src/helpers/BaseDriverHelper.php(46): craft\helpers\Component::createComponent(Array, 'craft\\base\\Sava...')
#10 /Users/atelierworkstation/Documents/git-local/atelier7/vendor/putyourlightson/craft-blitz/src/controllers/SettingsController.php(78): putyourlightson\blitz\helpers\BaseDriverHelper::createDriver('putyourlightson...', Array)
#11 [internal function]: putyourlightson\blitz\controllers\SettingsController->actionEdit()
#12 /Users/atelierworkstation/Documents/git-local/atelier7/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#13 /Users/atelierworkstation/Documents/git-local/atelier7/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#14 /Users/atelierworkstation/Documents/git-local/atelier7/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('edit', Array)
#15 /Users/atelierworkstation/Documents/git-local/atelier7/vendor/craftcms/cms/src/web/Application.php(302): yii\base\Module->runAction('blitz/settings/...', Array)
#16 /Users/atelierworkstation/Documents/git-local/atelier7/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('blitz/settings/...', Array)
#17 /Users/atelierworkstation/Documents/git-local/atelier7/vendor/craftcms/cms/src/web/Application.php(287): yii\web\Application->handleRequest(Object(craft\web\Request))
#18 /Users/atelierworkstation/Documents/git-local/atelier7/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest(Object(craft\web\Request))
#19 /Users/atelierworkstation/Documents/git-local/atelier7/www/index.php(32): yii\base\Application->run()
#20 {main}
```

**Comment by bencroker** [comment]
What version of Blitz are you running? If 4.x, you’ll need to remove the `warmCacheDelay` setting as it was removed from the plugin in 4.0.0, see https://github.com/putyourlightson/craft-blitz/blob/develop/CHANGELOG.md#400---2022-05-04

**Comment by Romanavr** [comment]
@bencroker 
**CraftCMS** 4.4.8
**Blitz** 4.4.4
**PHP** 8.1
I'm getting the same error after upgrade from craft 3.x. on `php craft up`, after applying migrations when craft applying project-config changes.
Any ideas how to fix this?

![изображение](https://user-images.githubusercontent.com/3519951/235154668-dc00dbed-668b-45bd-b01a-3ec65edbf982.png)

**Comment by bencroker** [comment]
Same as above, @Romanavr. You’ll need to remove the `warmCacheDelay` config setting in `/config/blitz.php`.

**Comment by Romanavr** [comment]
> Same as above, @Romanavr. You’ll need to remove the `warmCacheDelay` config setting in `/config/blitz.php`.

@bencroker 
I don't have it in blitz config:

```
<?php

return [
  '*' => [
    'debug' => false,
    'cachingEnabled' => false,
  ],
  'dev' => [
    'debug' => true,
  ],

  // Staging environment settings
  'staging' => [
    'debug' => false,
    'cachingEnabled' => true,
  ],

  // Production environment settings
  'production' => [
    'debug' => false,
    'cachingEnabled' => true,
    'cacheControlHeader' => 'public, s-maxage=14400, max-age=0',
  ],
];
```

**Comment by Romanavr** [comment]
![изображение](https://user-images.githubusercontent.com/3519951/235163828-024c83cf-6e62-44e6-acb4-67b3d2d956ee.png)
After deleting the last 2 values and clearing the cache, I can apply the changes from the project file

**Comment by bencroker** [comment]
I’m not sure why applying project config changes would not have removed the `warmCacheDelay` setting, but glad to hear you resolved it!

**Comment by kaspar-allenbach** [comment]
I haven't defined `warmCacheDelay ` in `/config/blitz.php` either. How exactely did you resolve this? @Romanavr 

I found an entry in the project.yaml:

![image](https://github.com/putyourlightson/craft-blitz/assets/762213/a76a9dc8-7d47-4c2b-9592-a99a7a00f4c9)

Is this the culprit? I'm afraid changing anything manually here.

**Comment by bencroker** [comment]
@kaspar-allenbach Removing the setting from project config, as described above, should work, let me know if you have any further issues.

**Comment by kaspar-allenbach** [comment]
Ah. this is indeed the project config. Okay now I get it. Thank you

**Comment by Romanavr** [comment]
> I haven't defined `warmCacheDelay ` in `/config/blitz.php` either. How exactely did you resolve this? @Romanavr
> 
> I found an entry in the project.yaml:
> 
> ![image](https://user-images.githubusercontent.com/762213/252636198-a76a9dc8-7d47-4c2b-9592-a99a7a00f4c9.png)
> 
> Is this the culprit? I'm afraid changing anything manually here.

I've removed it manually from the DB, `projectconfig` table, example on the screenshot.
Ben's method didn't work for me.

**Comment by kaspar-allenbach** [comment]
Have the plugin setting tables moved in craft `4.4.15 `? `plugins.blitz.settings` don't exist in my db also nothing exists in table`projectconfig`.

I've removed it from everywhere but the error still occurs:

```
name@domain [path]# ./craft project-config/apply
Applying changes from your project config files ...
- updating globalSets.1c6ad9c1-3d9d-49ef-9c8a-0cd5255c0032.fieldLayouts.3f1049cf-9faa-4f12-9afc-5298bf69987e.tabs.0.elements.0 ... 
![Bildschirmfoto 2023-07-11 um 14 10 58](https://github.com/putyourlightson/craft-blitz/assets/762213/79c5e732-7e6e-4086-a4c4-b5927cb5c927)

  - updating globalSets.1c6ad9c1-3d9d-49ef-9c8a-0cd5255c0032 ... 
error: Setting unknown property: putyourlightson\blitz\drivers\purgers\CloudflarePurger::warmCacheDelay
```

Where else could it be?
![Bildschirmfoto 2023-07-11 um 14 10 58](https://github.com/putyourlightson/craft-blitz/assets/762213/e41cc1c5-81b8-445f-93cd-4ee408946f73)

**Comment by kaspar-allenbach** [comment]
I can't find anything in `projectconfig` table. Has it moved? I'm on Craft CMS 4.4.1.5

**Comment by kaspar-allenbach** [comment]
I think I found the solution:

1. `./craft project-config rebuild`
2. `./craft project-config/apply`
3. `./craft blitz/cache/clear`

via the terminal. The Blitz CP Panel is inacessible with this issue ¯\_(ツ)_/¯

**Comment by johnwbaxter** [comment]
@bencroker I've got this exact same issue too! Nothing in my project config mentions the `warmCacheDelay` setting anywhere.

`[error] yii\base\UnknownPropertyException: Setting unknown property: putyourlightson\blitz\drivers\purgers\CloudflarePurger::warmCacheDelay at /var/www/html/vendor/yiisoft/yii2/base/Component.php:209 `

This is coming from a Craft 3.8 -> Craft 4.4 upgrade!

I can't apply my updated project config from the upgrade with this issue!

**Comment by bencroker** [comment]
@johnwbaxter Is the config setting found in the `config/blitz.php` file, perhaps?

**Comment by johnwbaxter** [comment]
@bencroker Nope!! I searched the whole project and it's nowhere in any config or PC.

I have resolved i?t by doing what @kaspar-allenbach suggested. rebuild/apply/clear and then redeploy the branch with the migrated PC from the repo and then run "reapply everything" and now I'm back in business.

Very weird though.

**Comment by bencroker** [comment]
My guess it that it was either cached or stored in the database. Glad to hear you got it resolved.
