### ISSUE TITLE
callback function after craft.blitz.includeCached

### ISSUE THREAD

**Issue by mach1media** [putyourlightson/craft-blitz#499]
Hi Ben, I'm using `craft.blitz.includeCached` to fetch cached versions of the nav menus and footer templates in my project.

```
{{ craft.blitz.includeCached('_layout/_navigation') }}
...
{{ craft.blitz.includeCached('_layout/_footer') }}
```

Works great, but I'm running into problems attaching JS event listeners to some of the elements within those cached templates.

For example, I need to toggle some CSS class names on the `body` when the twitter bootstrap `offcanvas` element within cached navigation template is opened/closed.

My original code for attaching these event listeners works great without using `craft.blitz.includeCached` but I'm finding that they aren't being attached since blitz loads these partials via Ajax.

QUESTION: Is there a way to tell `craft.blitz.includeCached` to execute a _callback function after Ajax is complete_?

I found a temporary workaround by wrapping my original code for attaching these event listeners within a `setTimeout` of 1.5 secs, but that seems a little janky.

Any suggestions or feedback is appreciated!

**Comment by bencroker** [comment]
Have you seen the JavaScript events that Blitz fires after injecting elements into the DOM?
https://putyourlightson.com/plugins/blitz#javascript-events

**Comment by mach1media** [comment]
Thanks Ben, I hadn't seen that part of the docs, so thanks for pointing me to this!

**Comment by bencroker** [comment]
Sure thing, hope that helps you solve it!
