### ISSUE TITLE
Cache warming does nothing

### ISSUE THREAD

**Issue by riasvdv** [putyourlightson/craft-blitz#5]
Seems to clear the cache, but the queued job doesn't add anything.

Might be because it's a site with multiple locales?

**Comment by putyourlightson** [comment]
Are you on version 1.2.3.1? Does your site have elements with URIs?

**Comment by riasvdv** [comment]
Yes latest version, and yeah almost all elements have URIs

**Comment by putyourlightson** [comment]
Hmm ok I'll look into it. In the meantime, is there anything unusual about your site setup?

**Comment by putyourlightson** [comment]
And is caching working when you visit the site pages?

**Comment by riasvdv** [comment]
What might be unusual is that we have `addTrailingSlashesToUrls` set to true in `config/general.php`

If I visit the site pages, they're cached perfectly.

**Comment by putyourlightson** [comment]
Ok I see what's going on now, it is indeed an issue with the multi site setup. I'll try to get a fix out tomorrow for you.

**Comment by riasvdv** [comment]
Great, thanks!

**Comment by putyourlightson** [comment]
Fixed in https://github.com/putyourlightson/craft-blitz/commit/ceb2480226d9fe274c3c1501080ce86787bed3eb, please let me know if it works as expected now.

**Comment by riasvdv** [comment]
Works great now, thanks for the quick fix!

**Comment by putyourlightson** [comment]
Great, glad to hear it and please let me know if any other multi-site related issues come up.
