### ISSUE TITLE
Can't clear individual 

### ISSUE THREAD

**Issue by wihodges** [putyourlightson/craft-blitz#50]
When I try to toggle the check mark on "Clear the Blitz cache selectively" - page becomes blank and can't clear individually. 

<img width="1263" alt="screenshot 2018-12-10 14 08 29" src="https://user-images.githubusercontent.com/286956/49758890-b312be00-fc85-11e8-8ba1-56b847650458.png">

**Comment by putyourlightson** [comment]
Huh that's strange. Are you on version 1.9.2? Does the same happen when you toggle it in the Clear Caches utility?

**Comment by wihodges** [comment]
Strange, so what was really happening, is was scrolling down and whole bunch of space is created at bottom of settings page. I finally noticed the scrollbar and scrolled back up and could clear individual files.

<img width="1255" alt="screenshot 2018-12-11 14 44 41" src="https://user-images.githubusercontent.com/286956/49829239-8a58fa00-fd53-11e8-86a1-925880b0be88.png">

**Comment by putyourlightson** [comment]
Strange but seems that it is a control panel issue.

**Comment by wihodges** [comment]
Yea it's super weird - so basically once you deselect all and check a box, page is instantly exapanded a full browser height and you see none of the existing CP. Hopefully this helps anyone who runs into it.
