### ISSUE TITLE
Only homepage is cached

### ISSUE THREAD

**Issue by CMeldgaard** [putyourlightson/craft-blitz#501]
When testing this plugin, we can only get the homepage to cache. All other pages are not cached. We have tried with both file and redis cache storage.

We are running latest version of Blitz and Craft CMS 4.4.8

Config file:
`<?php

return [
    '*' => [
        'cachingEnabled' => true,
        'refreshMode' => 1,
        'includedUriPatterns' => [
            [
                'siteId' => '',
                'uriPattern' => '.*',
            ],
        ],
        'excludedUriPatterns' => [
            [
                'siteId' => '',
                'uriPattern' => 'flush-op.php',
            ],
            [
                'siteId' => '',
                'uriPattern' => '^shop',
            ],
            [
                'siteId' => '',
                'uriPattern' => '^admin',
            ],
            [
                'siteId' => '',
                'uriPattern' => '^actions',
            ],
            [
                'siteId' => '',
                'uriPattern' => '^services/aws',
            ],
            [
                'siteId' => '',
                'uriPattern' => '^api/qd-app/app/get-sitedata',
            ],
            [
                'siteId' => '',
                'uriPattern' => '^api/qd-cache/update-prices',
            ],
            [
                'siteId' => '',
                'uriPattern' => '^api/get-block-recommendations',
            ],
            [
                'siteId' => '',
                'uriPattern' => '^quantity',
            ],
            [
                'siteId' => '',
                'uriPattern' => '^craftapi',
            ],
            [
                'siteId' => '',
                'uriPattern' => '^quickpay',
            ],
            [
                'siteId' => '',
                'uriPattern' => '^shipmondo',
            ],
        ],
        'cacheStorageType' => 'putyourlightson\blitz\drivers\storage\YiiCacheStorage',
        'queryStringCaching' => 1,
        'includedQueryStringParams' => [
            [
                'siteId' => '',
                'queryStringParam' => '.*',
            ],
        ],
        'excludedQueryStringParams' => [
            [
                'siteId' => '',
                'queryStringParam' => 'gclid',
            ],
            [
                'siteId' => '',
                'queryStringParam' => 'fbclid',
            ],
        ],

        // The integrations to initialise.
        'integrations' => [
            'putyourlightson\blitz\drivers\integrations\CommerceIntegration',
        ],
        'refreshCacheAutomaticallyForGlobals' => false,
    ],
];
`

**Comment by bencroker** [comment]
Please read through the [The site is not being cached when I visit it](https://putyourlightson.com/plugins/blitz#the-site-is-not-being-cached-when-i-visit-it) common issue to see if that helps. Also note that the URI pattern you should be using to include all pages is `.*`. Let me know whether that helps you resolve it or if you need any further assistance.

**Comment by CMeldgaard** [comment]
thank you @bencroker - it was the image transforms that was preventing the cache :D
