### ISSUE TITLE
Possibility to run blitz/cache/refresh-expired via supervisor

### ISSUE THREAD

**Issue by KevinSleegers** [putyourlightson/craft-blitz#505]
Hi,

I was wondering if it is possible to run the blitz/cache/refresh-expired command via a tool like supervisor instead of a cron job so it keeps running, similar to Craft queue/listen command.

Kind regards,
Kevin

**Comment by bencroker** [comment]
It’s not. The `refresh-expired` command has to go check the database so it must be run at intervals, there’s no way to handle it via listening alone.

**Comment by KevinSleegers** [comment]
@bencroker I was wondering if your response is still valid or if there is now a way to achieve this with a tool like supervisor. Thanks!

**Comment by bencroker** [comment]
It might be, but Supervisor is the wrong tool for the job here. What you want is to run a command on a schedule, which is what cron jobs are generally used for.
