### ISSUE TITLE
Temporarily disabling cache invalidations for an element from PHP

### ISSUE THREAD

**Issue by tomdavies** [putyourlightson/craft-blitz#509]
Is it possible to save an element programmatically without triggering Blitz to refresh the caches that track that element's ID?

My use case is that we have a large amount of content that is stored in Entries and gets regularly updated from an API trigger via Cron every 30m. 

Right now, when we run the sync from the API, we end up with refresh events for each saved entry, which massively spams the queue. Ideally I'd like to be able to temporarily disable the invalidation before saving each element, and then re-enable it immediately after that. Then at the end of the API import we would then do a manual single cache clear / refresh for all the affected content.

Alternatively, if there's a better way to handle this, I'm very open to other options too

Am running Blitz 4.4.4 / Craft  4.4.12

**Comment by bencroker** [comment]
Yes it is possible, by setting `batchMode` to `true` before updating the content, as documented at https://putyourlightson.com/plugins/blitz#integrations
