### ISSUE TITLE
Conditional URI Pattern

### ISSUE THREAD

**Issue by wihodges** [putyourlightson/craft-blitz#51]
Not sure if this has been mentioned before or if it's already possible, but is there a way to have a conditional update rule.

If page(s) is updated (e.g. /blog/.*) then update some other page that references  /some-blog-index 
and really it could be multiple places that also need updating. For instance in my scenario I have a channel type of blog, I reference the three latest blog post on the homepage [single], and the full-list on the blog-index page [part of different section structure of pages]. So in my configuration of caching all pages, which I really want to do, but when a new blog post is created I need the homepage, blog-index page and the new blog post to update in cache.

**Comment by putyourlightson** [comment]
Modifying an element will refresh every URI that references it that Blitz knows of. So in your example the blog article itself, the homepage and the listing page should all be recached by Blitz. Are you seeing different behaviour?

**Comment by wihodges** [comment]
So I went back and did a few tests. What I experience is that when I as an admin create a blog post and save, I see que run with blog index refresh and blitz cache warm. Blog index page did update like it should. But then when I go to delete a post, I see que process run and finish in the sidebar, but the blog index page did not update. When I run the warm blitz cache from Utilities, the page then updated and deleted the blog post.

The other test was conducted with an Editor user. And when that user creates a blog post. The que appears to process in the sidebar, but the blog index page never updates. Did this multiple times. Waited for que's to finish and also refreshed with browser with Empty cache & Hard reload.
The blog index page only updates when manually triggering the Warm Blitz Cache in utilities section.

I double checked Blitz settings and warm cache automatically is turned on: 
<img width="1035" alt="screenshot 2018-12-11 16 59 12" src="https://user-images.githubusercontent.com/286956/49835857-2be94700-fd66-11e8-88d3-0bae3e005744.png">
 
I thought something was off when I created the issue because I really hadn't noticed this issue until other editors began accessing the backend and complaining that their content isn't showing up.

**Comment by wihodges** [comment]
Ok tested a bit more, once post has been saved twice, it seems to work pretty consistently, but if a new post is created and saved, usually does not updated corresponding pages. Once it's saved twice, it appears that additional changes are processed as expected.

**Comment by putyourlightson** [comment]
Ok, so I can confirm that deleting an entry may not result in a listing page being recached, but I cannot replicate it for a new entry. Can you show me the element query you are using in the listing page that is not being refreshed the first time a new entry is created?

**Comment by wihodges** [comment]
Here is the query:
{% paginate craft.entries.section('blog').limit(10) as pageInfo, pageEntries %}
{% for entries in pageEntries %}
 ...
{% endfor %}

And sidenote, the blog index exists as an entry under a structure channel of pages. Whereas the blog is a channel of its own posts. Not sure if that matters. I'm continuing to test on another server, with and without the blitz htaccess redirect, which doesn't seem to affect the issue. Also confirmed that the hardcoded .html page in the cache folder is not updated. The only thing that seems to really trigger the update is saving the blog post a second time. Then everything updates. In another test for instance, I created 5 new blog posts, checking the blog index to update each time, but nothing happens until I re-edit one of the unseen posts and then it seems to run update.  

Hopefully that description is helpful - really love the plugin otherwise. Thanks!

**Comment by putyourlightson** [comment]
Thanks, very helpful! We'll address this in the next release.

**Comment by putyourlightson** [comment]
We just released 1.10.0 with lots of performance optimisations. Can you update and test with it?

**Comment by wihodges** [comment]
Seems to be working now! Thanks.

**Comment by putyourlightson** [comment]
Excellent!
