### ISSUE TITLE
CloudFlare purge_cache returns "403 Forbidden"

### ISSUE THREAD

**Issue by jskrivanek** [putyourlightson/craft-blitz#510]
Our settings:

```
// The purger type to use.
'cachePurgerType' => 'putyourlightson\blitz\drivers\purgers\CloudflarePurger',

// The purger settings (zone ID keys are site UIDs).
'cachePurgerSettings' => [
    'zoneIds' => [
        // Global (English)
        'aaaaaaa-bbbbbbb-ccccccc' => [
            'zoneId' => '██████████',
        ],
        // Global (Deutsch)
        'dddddd-eeeeee-ffffff' => [
            'zoneId' => '██████████',
        ],
        // Global (Italiano)
        'gggggg-hhhhhh-iiiiii' => [
            'zoneId' => '██████████',
        ],
        // Global (Français)
        'jjjjjj-kkkkkk-llllll' => [
            'zoneId' => '██████████',
        ],
    ],
    'authenticationMethod' => 'apiKey',
    'apiKey' => '█████████████████████',
    'email' => '████████████',
],
```

Error on the console:

```
[2023-05-30 12:00:10] Client error: `DELETE https://api.cloudflare.com/client/v4/zones/██████████'/purge_cache` resulted in a `403 Forbidden` response
```

CloudFlare API Permission:

```
Zone > Cache Purge > Purge
```

Any idea how to debug?

**Comment by bencroker** [comment]
When viewing the Reverse Proxy Purger settings in the CP, do the settings appear as normal and do any error messages appear after saving? For example: `Error connecting to Cloudflare using zone ID`

**Comment by jskrivanek** [comment]
@bencroker Same error messages in the CP.

```
Error: Error connecting to Cloudflare using zone ID for “Global (English)”.
Error: Error connecting to Cloudflare using zone ID for “Global (Deutsch)”.
Error: Error connecting to Cloudflare using zone ID for “Global (Italiano)”.
Error: Error connecting to Cloudflare using zone ID for “Global (Français)”.
```

**Comment by bencroker** [comment]
I believe only API Tokens have zone specific permissions, can you double check that you’re using an API Token (rather than an API Key) in your Blitz settings?

**Comment by jskrivanek** [comment]
Changed the token (not the key) to one zone only, same error.

**Comment by bencroker** [comment]
Hmm, I'm really not sure what the issue might be. Do you have IP restrictions in place, or any other security measures that might prevent API requests from working? As a last resort, perhaps you could contact Cloudflare support as only they can help troubleshooting API token permissions.

**Comment by jskrivanek** [comment]
@bencroker I changed from API token to API key and the error is gone.

**Comment by bencroker** [comment]
That’s good to hear, but still unusual. Here is what my API Token settings page looks like in Cloudflare.

![Screen Shot 2023-06-01 at 09 20 10-fullpage](https://github.com/putyourlightson/craft-blitz/assets/57572400/1cf31fa7-31b6-40f0-879a-373a98b4b2d6)

Does saving the Blitz settings work after entering the API Token? I noticed a validation issue if the API Key email address is invalid that I’ll fix up for the next release.

**Comment by jskrivanek** [comment]
@bencroker And are you sure that you have used this token in your config as well? In the config, it says

`'apiKey' => '',`

and not

`apiToken' => '',`

**Comment by bencroker** [comment]
I am. Did you save the plugin settings in the CP?

**Comment by jskrivanek** [comment]
Just saw that in the CP I have the option to switch between API token and API key. The token key is not listed in the default config. This caused the issue for sure. Is it `apiToken`?

**Comment by bencroker** [comment]
Yes, set `'authenticationMethod' => 'apiToken',`.
https://github.com/putyourlightson/craft-blitz/blob/35a0b0dce64104c6570653f0cd07f8c83493955e/src/config.php#LL98C16-L98C36
