### ISSUE TITLE
Commerce products triggering a refresh job on save even when not included in Including URI Patterns

### ISSUE THREAD

**Issue by bleepsandblops** [putyourlightson/craft-blitz#512]
Hello,

I have a Commerce install where I'm trying to cache a handful of static pages, but every time a product is saved, it triggers a 'Refreshing Blitz cache' job for that product. I've checked the db and the logs and those product pages are definitely not being cached. 

This is an example of the job details for one of those refreshes:
```
{
    "description": null,
    "data": {
        "cacheIds": [],
        "elements": {
            "craft\\commerce\\elements\\Product": {
                "elementIds": {
                    "148378": true
                },
                "sourceIds": {
                    "1": true
                },
                "changedFields": {
                    "148378": {
                        "editHistory": true
                    }
                },
                "isChangedByAttributes": {
                    "148378": false
                },
                "isChangedByFields": {
                    "148378": false
                }
            }
        }
    },
    "forceClear": false,
    "forceGenerate": false
}
```

Refresh mode is 'expire the cache, regenerate manually'.
Included URI patterns has around ten lines like:
`contact-us$`
`refunds$`

No custom config.

If I save an entry that's not part of the included URI patterns and that's not a Commerce product, no cache refresh job is triggered.

Craft 4.4.13
Commerce 4.2.10
Blitz 4.4.5

Thank you!

**Comment by bencroker** [comment]
Is `editHistory`, seen in the queue job data above, a custom field belonging to the product? And if so, what kind of field is it and how is it defined? According to the queue job, it appears to have been changed, triggering the cache refresh.

**Comment by bleepsandblops** [comment]
@bencroker yes it is a custom Table field that is modified on save, good point. Correcting what I said about regular entires, they do also trigger a cache refresh job if I modify one of their fields.

I think then my questions is, why do those need to happen if the product is never cached anywhere? I have a daily job modifying thousands of products and the queue gets filled up by cache refresh jobs which sometimes end up with the daily job being killed signal 9. Reading other issues + doc it looks like I need to activate batchMode, but would love to understand why those jobs are kicked off in the first place? Am I basically asking the question as here? https://github.com/putyourlightson/craft-blitz/issues/390

**Comment by bencroker** [comment]
Because that product _might_ be listed somewhere after the changes are applied, Blitz has to check whether it is each time modifications are made. It sounds like enabling `batchMode`, which forces Blitz to wait until the refresh method is manually called until it refreshes the cache (https://putyourlightson.com/plugins/blitz#integrations), is what you should be using.

**Comment by bleepsandblops** [comment]
@bencroker ok great understood thank you!
