### ISSUE TITLE
Request: cacheControlHeader per page

### ISSUE THREAD

**Issue by Thijmen** [putyourlightson/craft-blitz#513]
Dear maintainers,

Is there any way to set the `cacheControlHeader` setting per page in my twig files? Doing so would give us some control how long Cloudflare or any other CDN caches our pages.

Best regards,

**Comment by bencroker** [comment]
There’s the [`cacheControlHeader`](https://github.com/putyourlightson/craft-blitz/blob/35a0b0dce64104c6570653f0cd07f8c83493955e/src/config.php#L217) which is applied to all cached responses. If you’d like it to be different per page then you’d have to that via a custom module/plugin. I can share some sample code if you’d like?

**Comment by Thijmen** [comment]
Yes please, just some bits would be fine! Appreciated @bencroker

**Comment by bencroker** [comment]
Here you are.

```php
use putyourlightson\blitz\events\ResponseEvent;
use putyourlightson\blitz\services\CacheRequestService;
use yii\base\Event;

Event::on(CacheRequestService::class, CacheRequestService::EVENT_AFTER_GET_RESPONSE,
    function (ResponseEvent $event) {
        if ($event->siteUri->uri === 'my-page') {
            $event->response->getHeaders()->set('Cache-Control', 'public, s-maxage=31536000, max-age=0');
        }
    }
);
```

**Comment by Thijmen** [comment]
Thanks Ben, appreciated!
