### ISSUE TITLE
Request: Option to sort / prioritise sections / entry types

### ISSUE THREAD

**Issue by pom-pom** [putyourlightson/craft-blitz#515]
It would be nice if there was a way to define the order in which elements and categories are cached when warming / generating the cache, in order to be able to prioritise key sites and entries for larger sites with many entries.

Here's an example screenshot from a Magento Cache Warming extension to illustrate what I mean:
<img width="1091" alt="CleanShot 2023-06-15 at 10 49 35@2x" src="https://github.com/putyourlightson/craft-blitz/assets/4548353/e23f9057-2983-422e-b609-02518e95f093">

**Comment by bencroker** [comment]
Thanks for the suggestion. This feels like a feature that would be useful for a minority of very large sites. I’m not sure that we’d want to make it part of the default Generators as it adds complexity and setup regardless of whether the user needs it or not. It also really only makes sense in situations where the entire site is refreshed/generated, which Blitz tries to avoid whenever possible.

The good news is that Blitz allows you to [build your own cache generator](https://putyourlightson.com/plugins/blitz#cache-generators) with whatever functionality you need!
