### ISSUE TITLE
SSI detector only started working after adding PHP extension to output filter

### ISSUE THREAD

**Issue by wblommaert** [putyourlightson/craft-blitz#517]
We wanted to set up our project using Blitz, and opted for the server-side incudes (SSI) since using the regular approach seemed to give us a flashing effect due to the AJAX request waiting for the page load. We followed the instructions in the documentation and a few StackOverflow/StackExchange threads to try and get SSI working on Apache. What we did was add the following in our .htaccess file, as per the documentation:

```
Options +Includes
AddType text/html .html
AddOutputFilter INCLUDES .html
```

We also enabled the `include` mod in Apache, using `apachectl -M` to verify the module has been enabled. The Blitz settings page however kept indicating that SSI was not detected on the webserver. This sent us down a trail to find why Apache was not picking up the configuration and kept rendering the include tag as plain text on the settings page. We tried many variations of the directives that we found on StackOverflow and StackExchange, usually the same as listed on the documentation page, but the settings page kept indicating SSI was not detected.

It wasn't until we dug into the CMS template cache and noticed that they are PHP files that we discovered that adding the PHP extension to the output filter directive was the solution to make the SSI detector work. In the end our directives look like this:

```
Options +Includes
AddType text/html .html
AddOutputFilter INCLUDES .html .php
```

Is this expected behaviour or did we do something wrong? If expected behaviour, I think the documentation should include the PHP extension so that people don't get a false negative on the SSI detector like we did. We suspect SSI could have been working for us this whole time but we were likely misled by the indicator on the settings page to not further attempt it in our front-end templating.

Versions:
* Apache 2.4 (via DDEV)
* Craft CMS 4.4.14
* Blitz 4.4.5

**Comment by bencroker** [comment]
I’m not sure which docs you were following, but the sample Apache config in the official plugin docs at https://putyourlightson.com/plugins/blitz#ssi-enabled contains a `.php` extension.

```apacheconf
#- Enable Server-Side Includes
#- https://httpd.apache.org/docs/current/howto/ssi.html
Options +Includes
AddOutputFilter INCLUDES .html .php
```

**Comment by wblommaert** [comment]
@bencroker Terribly sorry, must've been a very bad case of Monday morning head because I could have sworn that it wasn't there. This can obviously be closed as all seems to be in order and working as intended. Thanks for this amazing plugin!

**Comment by wblommaert** [comment]
@bencroker Sorry to comment on a closed issue, but I found where I copied the wrong directives from. It was listed in the article announcing SSI found [here](https://putyourlightson.com/articles/blitz-4-3-feature-release). Still my fault for not checking the documentation directly, but maybe worth mentioning? Thanks again!

**Comment by bencroker** [comment]
Thanks for the heads up, we must have caught that after the article was published. I just updated the code in the article to avoid others having the same issue.
