### ISSUE TITLE
Clearing cache by tags

### ISSUE THREAD

**Issue by Thijmen** [putyourlightson/craft-blitz#518]
Hi,

Is there a reason why there is no possibility to flush/purge pages by tag, via URL as described https://putyourlightson.com/plugins/blitz#refreshing-cache-via-url?

If not, would you be open for a PR supporting this?

Best regards,

**Comment by bencroker** [comment]
The last item in the list is to “Refresh Tagged Cache”, which includes clearing and purging tagged pages. This is also provided via a utility and console command. Does that help clarify what you’re looking for?

**Comment by Thijmen** [comment]
Yes and no, we don't want to refresh, just clear the cache of those tags. From my understanding from the docs, refreshing includes regeneration of the cache as well - which is something we don't want at this stage.

**Comment by bencroker** [comment]
> From my understanding from the docs, refreshing includes regeneration of the cache as well - which is something we don't want at this stage.

What happens during the cache refresh process always respects the selected [Refresh Mode](https://putyourlightson.com/plugins/blitz#refresh-mode). So provided you’ve selected the right option, all should work well. If, on the off chance, you want the “Refresh Tagged Cache” to deviate from the Refresh Mode then you’d have to do that via a custom module or plugin.

**Comment by Thijmen** [comment]
Clear, thanks for clarifying! I want to deviate in this case from the selected refresh mode, so I'll create some module of my own. Thanks for the very fast response!

**Comment by bencroker** [comment]
Sure, let me know if I can help.

**Comment by Thijmen** [comment]
All I need is some sort of page which can be called to purge those keys, any quick tips? I'm not too familiair with Craft and plugins, but can code myself if I got some direction.

**Comment by Thijmen** [comment]
@bencroker Not sure if you've seen my comment, any guidelines to purge cache by keys only would be helpfull! Thanks in advance.

**Comment by bencroker** [comment]
The following code, added to an action controller, will clear (`deleteUris`) and purge (`purgeUris`) cached pages for the provided tags.

```php
use putyourlightson\blitz\Blitz;
use putyourlightson\blitz\helpers\SiteUriHelper;

$tags = ['tag1', 'tag2'];
$cacheIds = Blitz::$plugin->cacheTags->getCacheIds($tags);
$siteUris = SiteUriHelper::getCachedSiteUris($cacheIds);
Blitz::$plugin->cacheStorage->deleteUris($siteUris);
Blitz::$plugin->cachePurger->purgeUris($siteUris);
```

**Comment by Thijmen** [comment]
Cheers Ben, appreciated as always!

**Comment by Thijmen** [comment]
Upon coding, I found out that while the mechanism works fine (so far), it seems that the `craft_blitz_cachetags` does not gets deleted when delete/purge it. Is this intended? Do we need to clean this up? Thanks in advance @bencroker

**Comment by bencroker** [comment]
That is intentional, similar to how rows in the `blitz_caches` table are not cleared out on delete. The rows, however are regenerated whenever a page is cached again, to ensure that they are kept up-to-date.

**Comment by Thijmen** [comment]
Wouldn't it speed up the purge/deletion of the cache if those tables would have less rows? Now it still needs to fetch the cache ids, even if the page is uncached. Not doubting your choices - not at all, but I am trying to get my head around the concept :)

**Comment by bencroker** [comment]
Keeping cache IDs around is intentional as it makes it possible to regenerate the cache, rather than depending on users revisiting pages. The cache ID request process is well optimised and shouldn’t have any negative effect on the cache refresh process.
