### ISSUE TITLE
Error "Integrity constraint violation"

### ISSUE THREAD

**Issue by Odusanya** [putyourlightson/craft-blitz#52]
Craft throws this error when I try to load a cached page, both locally, and on a staging environment. 

<img width="1655" alt="screenshot 2018-12-12 at 1 38 21 pm" src="https://user-images.githubusercontent.com/22182946/49879827-1a1da780-fe2b-11e8-897c-011ebabece03.png">

After debugging, I learned that setting `cacheElementQueries` ==> `false` in config, removed this error. So whatever is wrong, it has something to do with `cacheElementQueries`

<img width="564" alt="screenshot 2018-12-12 at 2 46 09 pm" src="https://user-images.githubusercontent.com/22182946/49880280-19394580-fe2c-11e8-8df3-352ef2c15892.png">

**Comment by putyourlightson** [comment]
Hmm is this a fresh install or an updated version of Blitz? Either way it seems that one of the migrations may not have worked. Can you test if uninstalling and then installing the plugin locally solves the issue? And what version is this happening on?

**Comment by Odusanya** [comment]
Hey Ben, 
- This is a fresh install.
- I can confirm that reinstalling the plugin locally didn't fix the issue.
- Current running version: 1.9 of the plugin.

**Comment by putyourlightson** [comment]
Can you try updating to the latest version, currently 1.9.2.

**Comment by Odusanya** [comment]
Hey @putyourlightson problem still persists in version 1.9.2

**Comment by putyourlightson** [comment]
This can't be an issue with 1.9.2, there must be something strange going on with your database. Did you uninstall and reinstall with version 1.9.2?

**Comment by Odusanya** [comment]
Yes, I did. I literally removed with composer, `composer remove putyourlightson/craft-blitz`, cleared my composer cache and then ran `composer require putyourlightson/craft-blitz`, which should be the latest version. The vendor's composer.json confirms the version number as well, and the problem still persists.

If it would help, my site is heavily powered by Supertables - but I don't think this should be the cause, but whatever is happening, caching element queries is still a problem.

**Comment by putyourlightson** [comment]
Ok, but removing the package is not the same as uninstalling the plugin. Let me explain what I believe the issue to be. The error message is indicating that there is column called `type` in both the `blitz_elementquerycaches` and the `blitz_elementqueries` tables. This is not the case in version 1.9.2. Therefore you need to delete those tables from your database and the easiest way to do this is to uninstall the plugin (not remove it), as the uninstall will delete all of Blitz's tables. Then when you install again, a fresh set of tables will be created. If you are able to then have a look at the `blitz_elementquerycaches` table – it should _not_ contain a column called `type`.

**Comment by Odusanya** [comment]
Hmm... I see. Uninstalling from the CP now, I'll provide an update in a bit.

**Comment by Odusanya** [comment]
Cleaning up the table, actually did solve the problem. Thank you @putyourlightson

**Comment by putyourlightson** [comment]
Great, glad to hear it!
