### ISSUE TITLE
Queue jobs are holding up the queue for order emails

### ISSUE THREAD

**Issue by WHITE-developer** [putyourlightson/craft-blitz#520]
hey @bencroker,
We are using blitz on a pretty big webshop (~80k products), and the queue jobs are holding up the sending of Order emails, because the jobs of Blitz have a prio of 10 while the commerce emails have a prio of 100.
Would it maybe be possible to put the prio right after the emails?

**Comment by bencroker** [comment]
You can change the `refreshCacheJobPriority` config setting value (the lower the number, the higher the priority).
https://github.com/putyourlightson/craft-blitz/blob/35a0b0dce64104c6570653f0cd07f8c83493955e/src/config.php#L230

**Comment by WHITE-developer** [comment]
oeps, sorry overlooked that one thanks!
