### ISSUE TITLE
Cache different between nodes

### ISSUE THREAD

**Issue by Thijmen** [putyourlightson/craft-blitz#523]
Hi Ben,

I've got a somewhat strange situation at hands.
Some background information, we're using Cloudflare with Azure Redis cluster on a VPS and we're moving our sites to a Kubernetes cluster. We have a multi-site setup. An article is visible on two sites.

The deployment on the kubernetes cluster uses the same docker image as our VPS, and uses the same environment values. It connects to the same Redis cluster for cache.

Now, I edited an article and I can see the change propagating to our VPS, but not on our Kubernetes cluster. When I perform a cache-busting attack (url appened with `?test-query`), it fetches the correct article with the changes I made. 

It seems, that for some reason, the cache on the kubernetes cluster is stale or does not get updated. I fail to understand as of why this is happening. 

I've made sure that no CDN cache is part of this problem, as I change my hostfile directly (and I set the hostname in the headers, so I verified that it's coming from the kubernetes cluster.

Even when I refresh the page via the Blitz Cache utility, I see that the VPS takes some time to load on one site, but it's near instant on Kubernetes. 

Could there be different cache-keys (as in the Redis cluster) for the kubernetes cluster? Is there anything I can do to debug this issue?

Best regards and thanks in advance,

Thijmen

**Comment by Thijmen** [comment]
My cache component:
```php
 'cache' => function () {
            $config = [
                'class' => yii\redis\Cache::class,
                'keyPrefix' => Craft::$app->id,
                'defaultDuration' => Craft::$app->config->general->cacheDuration,

                // Full Redis connection details:
                'redis' => [
                    'hostname' => App::env('REDIS_HOST') ?: 'localhost',
                    'port' => App::env('REDIS_PORT') ?: 6379,
                    'password' => App::env('REDIS_PASSWORD') ?: null,
                    'database' => App::env('REDIS_CACHE_INDEX') ?: 5
                ],
            ];
       return Craft::createObject($config);
}
```

The APP_ID env var is the same on both environments.

**Comment by bencroker** [comment]
> Could there be different cache-keys (as in the Redis cluster) for the kubernetes cluster? Is there anything I can do to debug this issue?

Assuming there really only is a single Redis cluster, and reverse proxy caching is not playing into this, I don’t see what might be causing it. 

Did I understand that updating an entry results in a cached page being refreshed on the VPS but not on the Kubernetes cluster, but that clearing a cached page results in an immediate update to the Kubernetes cluster and a delayed update to the VPS? That would be very strange.

I’d suggest first disabling caching on the Cloudflare side, to eliminate the possibility of that being the cause. Then purge the cache. Use the timestamped comments at the end of the page to determine whether the VPS and Kubernetes cluster are serving the same cached version (https://putyourlightson.com/plugins/blitz#debugging). And finally, if you can, look at the contents of the Redis cluster to see what is being stored and served.

**Comment by Thijmen** [comment]
> Assuming there really only is a single Redis cluster, and reverse proxy caching is not playing into this, I don’t see what might be causing it.

There is no reverse proxy caching, and it's the same Redis cluster.

> Did I understand that updating an entry results in a cached page being refreshed on the VPS but not on the Kubernetes cluster, but that clearing a cached page results in an immediate update to the Kubernetes cluster and a delayed update to the VPS? That would be very strange.

Yes, correct. I update an entry in the control panel, it updates on the VPS but not on the Kubernetes cluster. 

> I’d suggest first disabling caching on the Cloudflare side, to eliminate the possibility of that being the cause. Then purge the cache. Use the timestamped comments at the end of the page to determine whether the VPS and Kubernetes cluster are serving the same cached version (https://putyourlightson.com/plugins/blitz#debugging). And finally, if you can, look at the contents of the Redis cluster to see what is being stored and served.

I request the pages at the origin, so without Cloudflare. I've verified that the call to Kubernetes actually went to the pods. I even ran the curl request in one of the pods, same timestamp.

Request to Kubernetes:
`<!-- Cached by Blitz on 2023-06-25T21:50:06+02:00 --><!-- Served by Blitz on 2023-06-26T09:43:56+02:00 -->`

Request to VPS 1:
`<!-- Cached by Blitz on 2023-06-26T09:38:09+02:00 --><!-- Served by Blitz on 2023-06-26T09:46:03+02:00 -->`

Request to VPS 2:
`<!-- Cached by Blitz on 2023-06-26T09:38:09+02:00 --><!-- Served by Blitz on 2023-06-26T09:46:19+02:00 -->`


>  And finally, if you can, look at the contents of the Redis cluster to see what is being stored and served.
I can, but I need to know the redis key first. Is there any way to output this too? I can make some changes in the vendor code on the kubernetes cluster to display this (it is not getting any traffic atm, so we should be fine).

Blitz version: 4.4.5
Craft version: 4.4.14

**Comment by Thijmen** [comment]
After searching with a python script through all my keys and values in my redis cluster, I discovered that the value was not in there. That lead me to re-evaluating my environment variables. It was the database index of redis that was wrongly configured (doh), because of a typo in the environment variable 🤦 

Works like a charm - this was a bug on my end. Hopefully it may help someone in the future :)

**Comment by bencroker** [comment]
Glad to hear you figured it out!
