### ISSUE TITLE
How to include Commerce products via Sprig and Blitz

### ISSUE THREAD

**Issue by hhentschel** [putyourlightson/craft-blitz#525]
I have an overview page for products.
each product is included via sprig: 
`{{ sprig('sprig/components/cart/_components/product', {variantId : variant.id, productId : product.id},
{'s-trigger': 'refresh'}) }}`

each product has a form for adding it to the cart.
the add-to-cart button is sprigified, so i can add a hint, when the product is added to the cart,
and in the meantime show a spinner.
```
{% set purchasableId = purchasableId ?? 0 %}
{% set addedToCart = success is defined %}

<a  href="{{ product.url }}">
Image, Title and price info
</a>
<form>

<button sprig

s-action="commerce/cart/update-cart"
s-method="post"
s-val:purchasable-id="{{ variant.id }}"
s-replace="#addtocart-{{ variant.id }}">

{% if addedToCart and purchasableId == variant.id %}
Added to cart
{% else %}
Buy            
{% endif %}
</button>

</form>
```

This product overview page is being cached via blitz. 
When i test it with two different users in seperate browsers i can only add products in the first browser
(the browser which is used the first time, after clearing the cache). 
If i go then to the second user, i get an 400 error code, if i want to add a product.

i watched the [this episode about blitz & sprig.](https://www.youtube.com/watch?v=DJqdF7kYgjE)
When i switch the _s-tigger_ to load, all spinners are loading and products disappear one after the other.

1. What i am doing wrong with this setup?
2. Should'nt be the input field the only field being excluded from cache ?
    So i would inlcude the single products not via {{ sprig..}} but with {{ include }} 
and then inside the procut include the input field with {{ sprig }} and s-trigger="load"?

craft cms: 3.8.13
commerce: 3.4.21
sprig: 1.13.0
blitz: 3.12.9.

**Comment by bencroker** [comment]
It sounds like you want both a `load` and `refresh` trigger, however if you do that then every single product will refresh on load. Instead, I’d suggest you wrap all of the product Sprig components in one Sprig components that is triggered on `load`.

In the main template:
```twig
{{ sprig('_components/products', {}, { 's-trigger': 'load' }) }}
```

In the `_components/products` template:
```twig
{% for product in products %}
    {{ sprig('_components/product', { productId: product.id }) }}
{% endfor %}
```

**Comment by hhentschel** [comment]
Thanks, It kind of works (as i can add products for different users on different browsers), but not really ideal and ready for production, because the shop index page loads really slow and all the products are reloaded on every load of the page. 

My Set-up is more complex as initially posted, because i have an additional filter within the product-overview page.
I try my best to show my current set-up:

main template (shop index page, show category filter and all products)

```
{{ sprig('_components/products', {}, { id: 'products-filters', 's-trigger': 'load' }) }}

{% js %}
  htmx.on('#products-filters', 'htmx:afterSwap', function(event) {
  htmx.trigger('#cartsize', 'refresh');
  });
{% endjs %}
  ```

In the _components/products template:
```
<div s-replace="#productsboard">
   
   {% include '/_components/filters' %}   // in here are sprigified inputs for filtering
   
   also some sprigified buttons to change the view of the products
   
   <div id="productsboard">
     {% for product in products %}
        {% for variant in product.getVariants() %}
          {{ sprig('sprig/components/cart/_components/product', {variantId : variant.id, productId : product.id}, {}) }}
        {% endfor %}
      {% endfor %}
   </div>
</div>

```
In the _components/product template:

```
Productinfo

<form>
   <button sprig
        s-action="commerce/cart/update-cart"
        s-method="post"
        s-val:purchasable-id="{{ variant.id }}"
        s-replace="#addtocart-{{ variant.id }}">
   Add to cart
   </button>
</form>
        
 ```

**Comment by bencroker** [comment]
> Thanks, It kind of works (as i can add products for different users on different browsers), but not really ideal and ready for production, because the shop index page loads really slow and all the products are reloaded on every load of the page.

All the products are loaded in a single AJAX request though, right? I’d probably go for a placeholder pattern approach, as explained in the livestream at https://craftquest.io/livestreams/dynamic-content-on-statically-cached-pages

```twig
{% if sprig.isInclude %}
    {# Placeholder image #}
{% else %}
    {# Load products #}
{% endif %}
```

**Comment by hhentschel** [comment]
Ah, that's a good hint. With that i show some loading 3 dots, while the products are loading.

One last thing i have though: 
now my loading spinner is not working properly anymore.
all the items get the `htmx-request` class, when adding a item to the cart.

**Comment by bencroker** [comment]
> all the items get the `htmx-request class`, when adding a item to the cart.

That’s not what I’d expect. Which DOM element(s) is the class being added to?

**Comment by hhentschel** [comment]
It was added to my loading-spinner element, which was inside my button element.

i had an `s-indicator` also applied to the button element, which is not needed.

its working now. thanks!
