### ISSUE TITLE
Tracked elements are not refreshing when updating Entries with a Preparse Field

### ISSUE THREAD

**Issue by jodeba** [putyourlightson/craft-blitz#526]
# 1. Steps to reproduce the issue.
- configure a [preparse field](https://plugins.craftcms.com/preparse-field?craft4) on an entry type, with a value set by twig template.
- normal query on template, for example: 
```
{% for job in craft.entries.section('jobs').all() %}
    <h2>{{ job.title }}</h2>
{% endfor %}
```
- Disable one Entry: this will trigger an update of the element (changes: status attribute and preparse field)
- This should trigger a refresh for the pages where you query the jobs, but it won't
- In the `helpers\RefreshCacheHelper::getElementCacheIds` `$isChangedByFields` will be true, it will add query conditions that will never match because the preparse field is not displayed in the twig.
- Page is not refreshed

# The plugin and Craft version numbers.
Craft 4.4.15 with Blitz 4.4.6

**Comment by bencroker** [comment]
If the entry status is changed then the value of `$isChangedByFields` will be `false`. Can you please double check your test case?

**Comment by jodeba** [comment]
I might have been confused in combination with #527 , but that one is still an issue with the Preparse Fields

**Comment by bencroker** [comment]
Ok, let’s continue the conversation there, in that case.
