### ISSUE TITLE
ImageOptimize does not return an absolute URL of image transforms

### ISSUE THREAD

**Issue by stefanprosch** [putyourlightson/craft-blitz#528]
Hi,
for a few weeks I ran into following issue and I'm not able to resolve it.

Uploading images with enabled Blitz cache will not return absolute URLs of image transforms. As soon as I disable Blitz and regenerate the image transforms of an asset by enabling focus and saving, the absolute URLs will be returned - as it should.

For example:
enabled Blitz cache returns 'uploads/images/_800x1203_crop_center-center_line/assetname.jpg?mtime=1688584317'
disabled Blitz cache returns 'https://SITE.COM/uploads/images/_800x1203_crop_center-center_line/assetname.jpg?mtime=1688584317'

I am using 
Craft Solo 3.8.14
Blitz 3.12.9
ImageOptimize 1.6.50

**Comment by bencroker** [comment]
I tested locally and cannot replicate this. 

What is the asset volume’s `File System Path` value set to under _Settings → Assets → Volumes_? If it contains a `@webroot` alias then please ensure this is defined, as per https://craftcms.com/docs/3.x/config/#aliases

**Comment by stefanprosch** [comment]
Locally it works fine also on my end, but the issue only appears live.
Volume alias are set up correctly, also the image transformations work and are saved into the correct folder.

In the meantime I updated to Craft Solo 3.8.15 and ImageOptimize 1.6.51. 

Same error appears when I upload an asset initially. 
<img width="635" alt="image" src="https://github.com/putyourlightson/craft-blitz/assets/26538087/acfae78c-638a-45e7-84eb-aa4c94b76017">

When I open the image again and hit save, the urls are correct.
<img width="634" alt="image" src="https://github.com/putyourlightson/craft-blitz/assets/26538087/819ac585-1ff3-4af7-b2af-22cede249b3c">

But I noticed that the error seems to be to occur if the task "Warming Blitz Cache" is still running?!

**Comment by bencroker** [comment]
> Same error appears when I upload an asset initially.

If that’s the case then it sounds like the page is being accessed _before_ the images have been processed, and likely to be an issue with the ImageOptimize plugin rather than Blitz. 

Paging @khalwat to take a look at this.

**Comment by stefanprosch** [comment]
> > Same error appears when I upload an asset initially.
> 
> If that’s the case then it sounds like the page is being accessed _before_ the images have been processed, and likely to be an issue with the ImageOptimize plugin rather than Blitz.
> 
> Paging @khalwat to take a look at this.

Maybe, but if I disable Blitz, ImageOptimize works how it should.

**Comment by bencroker** [comment]
My thinking is that it is happening with Blitz enabled only because cached pages are being generated _before_ ImageOptimize has finished optimising the asset images. This would make sense considering that you reported how images appear broken when you initially upload an asset in https://github.com/putyourlightson/craft-blitz/issues/528#issuecomment-1623447214.

**Comment by stefanprosch** [comment]
Same appears when I upload via asset manager

https://github.com/putyourlightson/craft-blitz/assets/26538087/118bbc5b-0c0a-49e8-80d2-c87bee4bad6d

**Comment by bencroker** [comment]
What you show in that video has nothing to do with Blitz, is that correct?

**Comment by stefanprosch** [comment]
I cannot clearly confirm. In the meantime I reported the issue also here https://github.com/nystudio107/craft-imageoptimize/issues/387
