### ISSUE TITLE
"Integrity constraint violation" causing front-end template to Error 500 immediately after saving entry

### ISSUE THREAD

**Issue by roberttolton** [putyourlightson/craft-blitz#53]
I'm seeing errors on the front-end when viewing a page immediately after it's saved, and being logged as:

```
An exception has been thrown during the rendering of a template ("SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`database_live`.`craft_blitz_elementcaches`, CONSTRAINT `craft_blitz_elementcaches_cacheId_fk` FOREIGN KEY (`cacheId`) REFERENCES `craft_blitz_caches` (`id`) ON DELETE CASCADE) The SQL being executed was: INSERT INTO `craft_blitz_elementcaches` (`cacheId`, `elementId`, `dateCreated`, `uid`, `dateUpdated`) VALUES (2238, 5532, '2018-12-17 00:12:53', '8ad75581-4283-4e79-abea-5061f257d76d', '2018-12-17 00:12:53')").
```

After refreshing the page, everything is fine (although the cached page title is wrong, but I think that's a separate issue).

**Comment by roberttolton** [comment]
I thought it might be related to https://github.com/putyourlightson/craft-blitz/issues/52 but I have no `type` column in that table.

**Comment by roberttolton** [comment]
Can confirm this issue is reproducible locally:
http://cloud.roberttolton.com/14cf25a9b23a

Can also confirm this still happens on the latest `1.9.2` release and after uninstalling and reinstalling the plugin (had to force-delete the tables using SequelPro as Uninstall process failed, I'm guessing on similar key constraints).

Looking at the error, and the state of the tables after a clear and save of just that one entry, it's trying to insert a row:

```
INSERT INTO `craft_blitz_elementcaches` (`cacheId`, `elementId`, `dateCreated`, `uid`, `dateUpdated`) VALUES (2238, 5532, '2018-12-17 00:12:53', '8ad75581-4283-4e79-abea-5061f257d76d', '2018-12-17 00:12:53')")
```

`cacheId` of `2238` doesn't exist. After saving, I have only one row in the `blitz_caches` table, which `cacheId` references - and that row's `id` is `10`. Not anywhere near `2238`..!

**Comment by putyourlightson** [comment]
We just released 1.10.0 with lots of performance optimisations. Can you update and test with it?

**Comment by roberttolton** [comment]
Have just updated, and initial local testing all seems to be good - can't reproduce the error anymore.
Thanks for the update Ben!

**Comment by putyourlightson** [comment]
Excellent!
