### ISSUE TITLE
Migration Failure

### ISSUE THREAD

**Issue by brianrivet-tilt** [putyourlightson/craft-blitz#530]
Hi,

I'm getting a migration error on one of my sites when trying to upgrade Neo from 3.7.9 to 3.7.12. Here's the error message:

```
Applying changes from your project config files ...

removing matrixBlockTypes.7a8209a6-1eda-4933-a928-e7bbfb9ad98f.fieldLayouts.667e515a-d531-4130-9272-617b98cbcc3b.tabs.0.elements.0 ...
removing matrixBlockTypes.7a8209a6-1eda-4933-a928-e7bbfb9ad98f ... done
done
removing matrixBlockTypes.53e04b39-f0c0-4047-a3ad-b77fe60d31f0.fieldLayouts.5012d86f-71cd-4517-adca-7d4e64e69b6b.tabs.0.elements.0 ...
removing matrixBlockTypes.53e04b39-f0c0-4047-a3ad-b77fe60d31f0 ...
error: Getting unknown property: benf\neo\Field::contentTable
updating dateModified ... done
removing meta.names.7a8209a6-1eda-4933-a928-e7bbfb9ad98f ... done
removing meta.names.53e04b39-f0c0-4047-a3ad-b77fe60d31f0 ... done
```

I put this in as a support ticket with the developer of Neo, and he looked into it and he thinks it may be an issue with Blitz. Here's the support thread from Neo:
https://github.com/spicywebau/craft-neo/issues/760

The site is running Blitz version 4.4.5 on Craft 4.4.13.

Can you please look into this to see if there is an issue with Blitz? I can send you a Dropbox link with a database backup, project config and composer files as well. Just let me know where to send the link.

Thanks!

**Comment by bencroker** [comment]
Sure, please send to support@putyourlightson.com.

**Comment by brianrivet-tilt** [comment]
Thanks! I've sent the link. Let me know if you need anything else.

**Comment by bencroker** [comment]
This appears to be an edge-case. Disabling Blitz using the [`disabledPlugins`](https://craftcms.com/docs/4.x/config/general.html#disabledplugins) general config setting, runing the update and then re-enabling Blitz solves the issue.
