### ISSUE TITLE
URLs that contain `admin` are not cached

### ISSUE THREAD

**Issue by therealpecus** [putyourlightson/craft-blitz#532]
Pages that include `admin` in the URL are not cached. 

Examples:
- /category/public-administration/
- /page-with-admin-in-the-slug/

To reproduce, create a page containing `admin` in the slug. Blitz logs don't list any debugging info.

Craft CMS PRO 3.8.15 +  Blitz 3.12.9

**Comment by bencroker** [comment]
Do you perhaps have an excluded URI pattern set with the value `admin` or similar in the plugin settings?

**Comment by therealpecus** [comment]
No, neither in the plugin config file (`/config/blitz.php`) nor in the settings stored in `/config/project.yaml` via the GUI.
Included pattern is set to `.*`
Excluded patterns is set to:
- `^/?robots.txt`
- `^/?dynamic/`
- `^/?gated/`
- `^/?styles/`
- `^/?favicon`

**Comment by bencroker** [comment]
Confirmed that this was indeed a bug. Fixed in https://github.com/putyourlightson/craft-blitz/commit/2a0408df9cd07fbd214bf54604a5df8286ecdc29, released in version 3.12.10 and version 4.4.7.
