### ISSUE TITLE
Splitting up the Generating Blitz caches job

### ISSUE THREAD

**Issue by Wiejeben** [putyourlightson/craft-blitz#535]
As of right now whenever changing globals or generating cache for all pages it would create a job that would re-crawl all the pages on the website. Currently I am rolling out Blitz to a website of over 30 thousand webpages and I would like to see the possibility for these jobs to be split up.

One way I could think of splitting up the jobs would be by each defined "Included URI Patterns". Another even simpler way would be by splitting up the job into 1000 page pieces.

As of right now regenerating the cache on the entirety of the site would take up to 4 hours for just a single job. Instead I'd rather see sub-1 hour jobs. Reducing the consequences if the job fails or times out.

It would also allow a situation for pages to be indexed more spread out. Instead of starting at `/blog` and stopping at `/products`, it would do both URI patterns separately, creating a more evenly applied cache as people visit the site while its still in progress.

**Comment by bencroker** [comment]
> As of right now whenever changing globals or generating cache for all pages it would create a job that would re-crawl all the pages on the website.

Ideally, you would remove the use of globals, which are anyway being [entrified](https://craftcms.com/blog/entrification) in Craft 5). See the [best practices](https://putyourlightson.com/plugins/blitz#best-practices) when using Blitz.

> One way I could think of splitting up the jobs would be by each defined "Included URI Patterns". Another even simpler way would be by splitting up the job into 1000 page pieces.

I think splitting generate cache jobs into batches makes absolute sense. Batchable jobs were introduced in Craft 4.4, but Blitz supports Craft 4.0 and above, so this will have to wait until the next major version of Blitz. I’ve added an issue for this in https://github.com/putyourlightson/craft-blitz/issues/537.

> As of right now regenerating the cache on the entirety of the site would take up to 4 hours for just a single job.

That’s a pretty huge job, have you considered using a refresh mode that refreshes the cache manually? `Clear the cache, regenerate manually or organically`, for example.

If you want to generate the entire cache in a specific order then I suggest you do this using a custom module/plugin. Here’s some code to get you started.

```php
use putyourlightson\blitz\drivers\generators\BaseCacheGenerator;
use putyourlightson\blitz\events\RefreshCacheEvent;
use yii\base\Event;

Event::on(BaseCacheGenerator::class, BaseCacheGenerator::EVENT_BEFORE_GENERATE_ALL_CACHE,
    function (RefreshCacheEvent $event) {
        $event->isValid = false;
        
        $siteUriGroup1 = [];
        $this->generateUris($siteUriGroup1);

        $siteUriGroup2 = [];
        $this->generateUris($siteUriGroup2);
    }
);
```
