### ISSUE TITLE
Batch queue jobs

### ISSUE THREAD

**Issue by bencroker** [putyourlightson/craft-blitz#537]
Large queue jobs should be batched using a new config setting. Batchable jobs were only introduced in Craft 4.4, so this will have to happen in Blitz 5.

Related: https://github.com/putyourlightson/craft-blitz/issues/535

**Comment by bencroker** [comment]
Bumped the required version of Craft to 4.4 and added a new batchable generate cache job in Blitz 4.14.0.

**Comment by jrrdnx** [comment]
Any timeline for when 4.14.0 will be released? Anxiously awaiting this update. Thanks!

**Comment by bencroker** [comment]
@jrrdnx I’m hoping for tomorrow. If you could help test this and report any issues by running `ddev composer require "putyourlightson/craft-blitz:dev-develop as 4.14.0"` then that would be great.

**Comment by jrrdnx** [comment]
So far so good.

<img width="1272" alt="Screenshot 2024-03-19 at 19 01 19" src="https://github.com/putyourlightson/craft-blitz/assets/4584671/9287c286-7306-4688-b26d-786b3336b6c8">
<img width="1271" alt="Screenshot 2024-03-19 at 19 03 37" src="https://github.com/putyourlightson/craft-blitz/assets/4584671/b0a73563-eeb2-48f6-931b-8696500201df">

Is there a new setting (or will there be) to customize the batch size, or is this hard-coded to 100?

**Comment by bencroker** [comment]
I considered adding one but couldn’t come up with a good use-case for why you might want to change it. Can you?

**Comment by jrrdnx** [comment]
Depending on site size and server specs, it'd be nice to have the ability to increase/decrease it on a case-by-case basis. 100 definitely feels like a good default, but I'm working on a lot of tweaks for the site I'm currently testing on so don't know if there would be a benefit to lowering this. I'm no expert on the Queue Manager so I'll defer to your expertise.

One thing I am noticing during my testing (currently debugging an access issue preventing the cache from generating in these queue jobs) is that subsequent jobs aren't added to the queue until the current batch has completed. So trying to cancel everything is pretty tedious: cancel the current batch, hit OK, refresh, repeat. Is it possible to have them all added at once so they could be released at the same time?

**Comment by bencroker** [comment]
Yeah I agree it could be a nice to have. I added a new `driverJobBatchSize` config setting in https://github.com/putyourlightson/craft-blitz/commit/03bd8216818d6e6d175d9b87ba0b1281e5bfc043.

The job batching system is part of Craft core, so how it behaves is out of my control. But it does sound like a potential UX issue. Could you please report it in a discussion at https://github.com/craftcms/cms/discussions?

**Comment by jrrdnx** [comment]
Fixed my access issue, and it is taking a decent amount of time to run each batch so I'll be experimenting with lowering that batch size. Thank you for adding that.

I think what I'm looking for in regards to the UX is less batching and more having them all added at once but as separate jobs. Using those screenshots as examples, it would add 24 separate jobs all at once while still only running one at a time (assuming I only have one process running). But I'd also be able to release them all at once instead of individually. Not sure if it's worth the effort to allow for both options, just throwing it out there.

**Comment by bencroker** [comment]
Feel free to open an issue or discussion at https://github.com/craftcms/cms/ about how job batching works. I doubt they’ll transition to the approach you debscribed, but being able to cancel a job, along with all subsequent batches, could be a useful feature to have.

**Comment by bencroker** [comment]
Released in [4.14.0](https://github.com/putyourlightson/craft-blitz/releases/tag/4.14.0).

**Comment by bencroker** [comment]
@jrrdnx FYI I created a discussion addressing batched queue jobs being spawned at https://github.com/craftcms/cms/discussions/14986
