### ISSUE TITLE
`__home__` returns 200 instead of 404

### ISSUE THREAD

**Issue by ccchapman** [putyourlightson/craft-blitz#538]
**Steps to reproduce:**

1. Disable Blitz
1. Have section with `uriFormat: '{slug}'`
1. Create entry in section with slug of `__home__`
1. Expect `curl -I https://mysite.com` to show 200 status code
1. Expect `curl -I https://mysite.com/__home__` to show 404 status code
1. Enable Blitz
1. Load `https://mysite.com` (to warm cache)

**Actual behaviour:**

`curl -I https://mysite.com/__home__` shows 200 status code (returning `web/cache/blitz/mysite.com/index.html`)

**Expected behaviour:**

`curl -I https://mysite.com/__home__` shows 404 status code

See also https://github.com/craftcms/cms/issues/7585.

**Comment by bencroker** [comment]
Thanks for reporting this! Fixed in https://github.com/putyourlightson/craft-blitz/commit/d616f974653cf9176254f6d304f5a6ec6999e836 for the next release.

**Comment by bencroker** [comment]
Released in version [4.5.0](https://github.com/putyourlightson/craft-blitz/releases/tag/4.5.0).
