### ISSUE TITLE
FR: Support for URIs larger than 255 chars

### ISSUE THREAD

**Issue by joepagan** [putyourlightson/craft-blitz#539]
Was debugging why some search results uris on a site we manage were bypassing cache, and unfortunately got the log: 

>`Page not cached because it exceeds the max URI length of 255 characters. [https:/...`

[It looks like this is by design on an older github issue because craft3 supposed mysql5.5+](https://github.com/putyourlightson/craft-blitz/issues/113#issuecomment-510814384)

However [craft4 supports mysql5.7.8+](https://craftcms.com/docs/4.x/requirements.html)

Can we please get support for this for blitz v4 and onwards?

**Comment by bencroker** [comment]
Yes, I’ll look into making this happen. What version of Blitz is the site currently running?

**Comment by joepagan** [comment]
Amazing thanks Ben! Currently running `4.2.3`

**Comment by bencroker** [comment]
Added this as a config setting in https://github.com/putyourlightson/craft-blitz/commit/4fb3ec21c96cc6e31698ef097d82400d8f96404e for the upcoming 4.5.0 release. Be sure to read the caveats before changing.

**Comment by bencroker** [comment]
Released in version [4.5.0](https://github.com/putyourlightson/craft-blitz/releases/tag/4.5.0).
