### ISSUE TITLE
Plugin Migration issue 1.8 -> 1.10.1

### ISSUE THREAD

**Issue by proposifymax** [putyourlightson/craft-blitz#54]
I just updated blitz from 1.8 to 1.10.1 (changed composer.json, ran `composer update`) which went fine, when I went to the admin panel, the DB migration message comes up but the blitz migration fails with the following message:

> One of Blitz’s migrations failed.
> 
> Database Exception: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'ps_staging.craft_blitz_elementcaches' doesn't exist
The SQL being executed was: ALTER TABLE craft_blitz_elementcaches ADD UNIQUE INDEX craft_blitz_elementcaches_cacheId_elementId_unq_idx (cacheId, elementId)
> 
> Migration: putyourlightson\blitz\migrations\m181214_120000_add_indexes_hash_column
> 
> Output:
> 
> create unique index craft_blitz_elementcaches_cacheId_elementId_unq_idx on {{%blitz_elementcaches}} (cacheId,elementId) ...Exception: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'ps_staging.craft_blitz_elementcaches' doesn't exist
The SQL being executed was: ALTER TABLE craft_blitz_elementcaches ADD UNIQUE INDEX craft_blitz_elementcaches_cacheId_elementId_unq_idx (cacheId, elementId) (/path/to/app/vendor/yiisoft/yii2/db/Schema.php:664)
#0 /path/to/app/vendor/yiisoft/yii2/db/Command.php(1263): yii\db\Schema->convertException(Object(PDOException), 'ALTER TABLE cr...')
#1 /path/to/app/vendor/yiisoft/yii2/db/Command.php(1075): yii\db\Command->internalExecute('ALTER TABLE cr...')
#2 /path/to/app/vendor/yiisoft/yii2/db/Migration.php(495): yii\db\Command->execute()
#3 /path/to/app/vendor/craftcms/cms/src/db/Migration.php(400): yii\db\Migration->createIndex('craft_blitz_ele...', '{{%blitz_elemen...', Array, true)
#4 /path/to/app/vendor/putyourlightson/craft-blitz/src/migrations/m181214_120000_add_indexes_hash_column.php(20): craft\db\Migration->createIndex('craft_blitz_ele...', '{{%blitz_elemen...', Array, true)
#5 /path/to/app/vendor/craftcms/cms/src/db/Migration.php(56): putyourlightson\blitz\migrations\m181214_120000_add_indexes_hash_column->safeUp()
#6 /path/to/app/vendor/craftcms/cms/src/db/MigrationManager.php(243): craft\db\Migration->up(true)
#7 /path/to/app/vendor/craftcms/cms/src/db/MigrationManager.php(163): craft\db\MigrationManager->migrateUp(Object(putyourlightson\blitz\migrations\m181214_120000_add_indexes_hash_column))
#8 /path/to/app/vendor/craftcms/cms/src/services/Updates.php(215): craft\db\MigrationManager->up()
#9 /path/to/app/vendor/craftcms/cms/src/controllers/BaseUpdaterController.php(443): craft\services\Updates->runMigrations(Array)
#10 /path/to/app/vendor/craftcms/cms/src/controllers/UpdaterController.php(207): craft\controllers\BaseUpdaterController->runMigrations(Array, 'restore-db')
#11 [internal function]: craft\controllers\UpdaterController->actionMigrate()
#12 /path/to/app/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#13 /path/to/app/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#14 /path/to/app/vendor/craftcms/cms/src/web/Controller.php(104): yii\base\Controller->runAction('migrate', Array)
#15 /path/to/app/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('migrate', Array)
#16 /path/to/app/vendor/craftcms/cms/src/web/Application.php(282): yii\base\Module->runAction('updater/migrate', Array)
#17 /path/to/app/vendor/craftcms/cms/src/web/Application.php(664): craft\web\Application->runAction('updater/migrate')
#18 /path/to/app/vendor/craftcms/cms/src/web/Application.php(236): craft\web\Application->_processUpdateLogic(Object(craft\web\Request))
#19 /path/to/app/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
> #20 /path/to/app/web/index.php(23): yii\base\Application->run()
> #21 {main}

**Comment by putyourlightson** [comment]
That's strange, the `blitz_elementcaches` table has existed since a very early version. Can you try reinstalling the plugin? Note your settings first or add them to the config file.

**Comment by proposifymax** [comment]
I did but it didn't work. Here are the steps taken:

- reverted database to pre-update state
- ran `composer remove putyourlightson/craft-blitz`
- refreshed `/admin/settings/plugins` to verify cpanel loading
  - it did
  - listed blitz as "missing"
- ran `composer require putyourlightson/craft-blitz`
- refreshed `/admin/settings/plugins` to verify cpanel loading
  - presented with DB migration message
  - same error

EDIT: I also do not have a config file, the settings in the cpanel were:
- do not cache query strings
- warm concurrency 3
- include pattern: .+

**Comment by proposifymax** [comment]
Sorry it wasn't the same error. Now there is this error:


> One of Blitz’s migrations failed.
> 
> Integrity constraint violation: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '13090-2' for key 'craft_blitz_elementcaches_cacheId_elementId_unq_idx'
The SQL being executed was: ALTER TABLE craft_blitz_elementcaches ADD UNIQUE INDEX craft_blitz_elementcaches_cacheId_elementId_unq_idx (cacheId, elementId)
> 
> Migration: putyourlightson\blitz\migrations\m181214_120000_add_indexes_hash_column
> 
> Output:
> 
> create unique index craft_blitz_elementcaches_cacheId_elementId_unq_idx on {{%blitz_elementcaches}} (cacheId,elementId) ...Exception: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '13090-2' for key 'craft_blitz_elementcaches_cacheId_elementId_unq_idx'
The SQL being executed was: ALTER TABLE craft_blitz_elementcaches ADD UNIQUE INDEX craft_blitz_elementcaches_cacheId_elementId_unq_idx (cacheId, elementId) (/path/to/app/vendor/yiisoft/yii2/db/Schema.php:664)
#0 /path/to/app/vendor/yiisoft/yii2/db/Command.php(1263): yii\db\Schema->convertException(Object(PDOException), 'ALTER TABLE cr...')
#1 /path/to/app/vendor/yiisoft/yii2/db/Command.php(1075): yii\db\Command->internalExecute('ALTER TABLE cr...')
#2 /path/to/app/vendor/yiisoft/yii2/db/Migration.php(495): yii\db\Command->execute()
#3 /path/to/app/vendor/craftcms/cms/src/db/Migration.php(400): yii\db\Migration->createIndex('craft_blitz_ele...', '{{%blitz_elemen...', Array, true)
#4 /path/to/app/vendor/putyourlightson/craft-blitz/src/migrations/m181214_120000_add_indexes_hash_column.php(20): craft\db\Migration->createIndex('craft_blitz_ele...', '{{%blitz_elemen...', Array, true)
#5 /path/to/app/vendor/craftcms/cms/src/db/Migration.php(56): putyourlightson\blitz\migrations\m181214_120000_add_indexes_hash_column->safeUp()
#6 /path/to/app/vendor/craftcms/cms/src/db/MigrationManager.php(243): craft\db\Migration->up(true)
#7 /path/to/app/vendor/craftcms/cms/src/db/MigrationManager.php(163): craft\db\MigrationManager->migrateUp(Object(putyourlightson\blitz\migrations\m181214_120000_add_indexes_hash_column))
#8 /path/to/app/vendor/craftcms/cms/src/services/Updates.php(215): craft\db\MigrationManager->up()
#9 /path/to/app/vendor/craftcms/cms/src/controllers/BaseUpdaterController.php(443): craft\services\Updates->runMigrations(Array)
#10 /path/to/app/vendor/craftcms/cms/src/controllers/UpdaterController.php(207): craft\controllers\BaseUpdaterController->runMigrations(Array, 'restore-db')
#11 [internal function]: craft\controllers\UpdaterController->actionMigrate()
#12 /path/to/app/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#13 /path/to/app/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#14 /path/to/app/vendor/craftcms/cms/src/web/Controller.php(104): yii\base\Controller->runAction('migrate', Array)
#15 /path/to/app/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('migrate', Array)
#16 /path/to/app/vendor/craftcms/cms/src/web/Application.php(282): yii\base\Module->runAction('updater/migrate', Array)
#17 /path/to/app/vendor/craftcms/cms/src/web/Application.php(664): craft\web\Application->runAction('updater/migrate')
#18 /path/to/app/vendor/craftcms/cms/src/web/Application.php(236): craft\web\Application->_processUpdateLogic(Object(craft\web\Request))
#19 /path/to/app/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#20 /path/to/app/web/index.php(23): yii\base\Application->run()
#21 {main}

**Comment by proposifymax** [comment]
working fix: 

- from approot run `./craft blitz/cache/clear`
- from approot run `./craft blitz/cache/warm`
- from approot run `./craft migrate/all`

This let the blitz migrations pass (for me) and the cpanel is accessible and lists blitz as enabled at version 1.10.1

**Comment by putyourlightson** [comment]
Ok great! `./craft migrate/all` must have applied some missing migrations, I'm not sure why that would have happened though :)

**Comment by proposifymax** [comment]
just a quick recap when I deployed it into production I needed to run `./craft migrate/all` first (which would fail but make the blitz commands available, then the blitz clear and warm, then again `./craft migrate/all` to finish the migration (this time successfully).
