### ISSUE TITLE
Choose optional requestType voor includeCached() template function

### ISSUE THREAD

**Issue by Tim-Wils** [putyourlightson/craft-blitz#540]
Hi Ben!

In our project we've come to the point where we want to include a lot of things with SSI now that our project becomes very large with 100.000+ pages, which is an awesome new feature!
Besides this, there's a sidebar and a custom include in the articles where we want to load it with a ajax-include. It seems this is not possible right now, is it?

If it isn't to much to ask, I wanted to ask for a feature to manually set which requestType the include is, by passing it to the options:

At line 45 and 60: https://github.com/putyourlightson/craft-blitz/blob/3d12c1ada7412a63606c3277d4b822a8cdb50362/src/variables/BlitzVariable.php#L45

Add: 
`'requestType' => $options[''requestType] ?? VariableConfigModel::INCLUDE_REQUEST_TYPE,`

Then if the default INCLUDE_REQUEST_TYPE is set to SSI, you can always add some ajax includes like this:
includeCached('template.twig', {}, {'requestType': 'ajax'})

Tim

**Comment by bencroker** [comment]
Hi Tim,

There are currently two supported ways of including content: 
- Static includes, loaded over SSI/ESI (falling back to AJAX if neither are enabled), using the `includeCached`.
- Dynamic includes, loaded over AJAX, using the `includeDynamic`.

These tags should make it possible to mix and match SSI and AJAX requests. Does that work for your use-case? And if not then please help me understand why you’d like to be able to select SSI vs. AJAX requests per include.

**Comment by Tim-Wils** [comment]
Thanks for your answer.
Can includeDynamic also load cached includes? 

The reason for this feature request is that we generally want to use SSI includes, which are awesome. But for specific articles, we additionally want to load for example cached interactive content blocks like _temporary_ quizes, polls, manually highlighted comments etc. that could be switched om or off , but aren’t directly in the sourcecode or part of the article itself. 

Does that make sense?

**Comment by bencroker** [comment]
> Can includeDynamic also load cached includes?

No, dynamic includes cannot load statically cached content.

> But for specific articles, we additionally want to load for example cached interactive content blocks like temporary quizes, polls, manually highlighted comments etc. that could be switched om or off , but aren’t directly in the sourcecode or part of the article itself.

That sounds like the perfect use-case for dynamic includes!

**Comment by Tim-Wils** [comment]
Alright, thank you!
Do you have any tips on making that dynamicInclude load less resource intensive (thousands of users per second)? I’d like to statically cache that dynamic include and bypass the php to be as light as possible :)

**Comment by Tim-Wils** [comment]
We can always create our own Ajax calls and templates to bypass this off course 👍🏻 no worries :)

**Comment by bencroker** [comment]
> Do you have any tips on making that dynamicInclude load less resource intensive (thousands of users per second)?

You can use Craft’s native cache tags within an included template.

> I’d like to statically cache that dynamic include and bypass the php to be as light as possible :)

Then use a static include...? I’m still confused as to why you are trying to avoid this.

**Comment by bencroker** [comment]
FYI you can already override the request type using the config options, thanks to this line:
https://github.com/putyourlightson/craft-blitz/blob/develop/src/variables/BlitzVariable.php#L47

**Comment by Tim-Wils** [comment]
Thanks for the help! I was under the impression line 45 was overriding the options. 

I totally get your confusion and maybe we were overthinking this ;). You’re probably right to just use static includes. 
I think I was afraid of polluting the html-source of the page a lot by adding seemingly random html+assets (large quizes) right under the article keeping in mind that Lighthouse will penalty a page with lots of nodes.

Thanks for shining your light on this, appreciate it! Cheers! We will play around with it and go for the most performant solution.

**Comment by bencroker** [comment]
I think you have lots of options of how to implement this, it mainly depends on what you’re trying to achieve. And if you ever find yourself needing even more options, there’s [Sprig](https://putyourlightson.com/sprig).
