### ISSUE TITLE
Disable serving cached pages

### ISSUE THREAD

**Issue by jorisnoo** [putyourlightson/craft-blitz#541]
Dear Ben, thank you so much for all your continued work on this plugin!

I've followed your guide to export the cached pages to a git repo, which is then deployed to netlify, which seems to work very well so far. In this case, however, i'd like to redirect from the `cms.website.com` site, where craft is hosted and the cache is being generated, to the netlify domain. One way for this to work could be by disabling serving the cache entirely — eg. only generating and deploying it, but not serving it for visitors to the craft hosted site. I may have missed the relevant info in the docs or some obvious way to do this; is this currently possible?

Thank you very much in advance!

Craft Pro 4.4.16.1
Blitz 4.5.0

**Comment by bencroker** [comment]
There’s no obvious way to do this, as the cache must be generated before it can be deployed, but it should be possible to set up a redirect rule in a custom module/plugin. I’d recommend doing this in such a way that it only redirects users that are not logged in and requests that are not live preview requests. Let me know if you’d like help with this. Note also that, provided indexing is disabled on the `cms` subdomain, there’s no need for a redirect and I tend to avoid doing so on the sites I have that use this technique.

**Comment by jorisnoo** [comment]
Thanks a lot for the answer and the tip; using a module does the trick.

I was just a bit bothered by the fact that clicking on the logo or an entry link within the control panel links to the `cms` subdomain (setting the base URL of a site to the netlify domain breaks caching, right?), and a bit worried that editors then would browse the `cms` — which is supposed to be identical with the public url, but if something with the latter was off, the editors then may not notice, and may even share a link to the `cms` url by accident.

For what reason would you avoid setting a redirect; did you run into any issues?

**Comment by bencroker** [comment]
Yeah I get that it’s not ideal but haven’t yet found a way that I feel comfortable recommending officially. I generally don’t set up redirects because it makes it easier for content editors to check their edits without having to wait for the cache to be deployed to Netlify.
