### ISSUE TITLE
Git Deployer: Single git Repository for multiple Sites

### ISSUE THREAD

**Issue by jorisnoo** [putyourlightson/craft-blitz#542]
Sorry for bothering you again 🙇

I'm planning on using the Git Deployer with a multi-lang craft installation, where each locale corresponds to one site. Looking at the `GitDeployer`class, it seems like it won't be possible to use a single git repository for multiple sites (in subfolders) — or am i missing a way to achieve this?

If not, would this be something you'd consider supporting? Otherwise i assume that creating my own deployer would be the way to achieve this. (Extending the current `GitDeployer` doesn't seem like an option, as most functions are set to private.)

Thanks a lot!

**Comment by bencroker** [comment]
This should be possible by using the same Repository Path for each site. Just make sure that you’re using unique subfolders for each site. Let me know if you have any issues getting it to work.

**Comment by jorisnoo** [comment]
Ah, i now got it to work, thanks! It may be deploing the repo multiple times, but then all renders fine.

**Comment by bencroker** [comment]
That’s right, it deploys one site at a time.
