### ISSUE TITLE
Ability to determine if request is cacheable

### ISSUE THREAD

**Issue by Thijmen** [putyourlightson/craft-blitz#543]
Hi,

We're using Azure Redis and we stumbled upon some diagnostics. Apparently, there was a key being set with too much data. This is the report;

``
Responses from this cache exceeded recommended size limits between 2023-08-01 10:45:34Z and 2023-08-02 10:45:34Z. The maximum response size detected 1926328 is greater than 204800. Redis server is designed as a highly performant store for lightweight pieces of data, generally smaller than 200KB. Requests that produce larger responses often cause problems because the Redis server and client libraries are optimized for rapidly processing and transmitting many small requests. Attempting to move large payloads through this system can severely impact Redis server load and performance, leading to command timeouts and failures in the client application.
``

Is there any way to configure a callback to determine if something is 'cacheable'? I think this would be a neat addition! Let me know what your thoughts are.

Best regards,

**Comment by bencroker** [comment]
There is, but this message is specific to your Redis instance. What are you imagining, exactly? My recommendation would be to increase the size limits of your Redis instance if you intend to use it for caching large pages.

**Comment by Thijmen** [comment]
Yeah we're experiencing command timeouts every now and then (when running on memory pressure). This is a tip I got from the Azure portal. I thought maybe there was a very, very big page (several MB's) being cached, but I assume `1926328 bytes` should be peanuts for Redis. 

If there was a very very big page being cached, maybe I could exclude cache keys with a value over 10MB, or something. Hence I was thinking about a callback or so. 

What are your experiences / do you have tips?

**Comment by bencroker** [comment]
You can prevent cached values from being saved when the output is over a certain number of bytes via a custom module/plugin. Here’s some code to get you started.

```php
use putyourlightson\blitz\events\SaveCacheEvent;
use putyourlightson\blitz\services\GenerateCacheService;
use yii\base\Event;

Event::on(GenerateCacheService::class, GenerateCacheService::EVENT_BEFORE_SAVE_CACHE,
    function (SaveCacheEvent $event) {
        if (strlen($event->output) > 204800) {
            $event->isValid = false;
        }
    }
);
```
