### ISSUE TITLE
Homepage does not get refreshed (due to token in query string?)

### ISSUE THREAD

**Issue by luke-nehemedia** [putyourlightson/craft-blitz#544]
I run Blitz on a client's site for many years. It is a multisite setup with 5 pages. 
So far, everything runs smoothly. However, for some time the homepage does not refresh after an edit and I have no idea why. 

On the template itself, the following is written:
```
{% do craft.blitz.options({
	cachingEnabled: true,
	trackElements: true,
	trackElementQueries: true,
	cacheDuration: 'P10D',
	tags: ['home', 'news']
}) %}
```

The homepage does not match an exclude pattern. Inclusion patterns for all sites are `.*`. 
I do not get any logs after making changes to the homepage, or when editing associated pages (like elements that are listed on the homepage), I get the following message (having `devmode` on):

> [2023-08-02 13:45:05] Page not cached because a query string was provided with the query string caching setting disabled. `[https://www.example.org/__home__?token=Vti2-rKtOZoOGai_Dqvj7BSumo1d2BAo]`
> [2023-08-02 13:45:07] 404 error: Not Found `[https:/www.example.org/__home__?token=Vti2-rKtOZoOGai_Dqvj7BSumo1d2BAo]`

Manually refreshing the cache does not work either, as far as I understand. However, on the next page visit, the cache is created without any problems. 

> [2023-08-02 13:48:38] Cached URLs successfully refreshed.
> [2023-08-02 13:48:42] Page not cached because a query string was provided with the query string caching setting disabled. `[https://www.example.org/?token=7PHT-czMT6vUaBc7ZFvCjlCXX2qQhAOL]`
> 

As far as I understand this token is added by Blitz itself? 
What can I do to solve this issue? Have I configured something wrong?

**Comment by bencroker** [comment]
Please provide the plugin and Craft version numbers that your site is running.

**Comment by luke-nehemedia** [comment]
Of course. Sorry I forgot:
Craft Pro 4.4.16.1
Blitz 4.5.0
PHP 8.1.21

**Comment by bencroker** [comment]
The token you see may have been added by Blitz during the cache generation process, but it should detect that and not log it. Have you done a full cache refresh since the issue arose? And is the homepage being cached? And can you please share the Blitz settings found in `config/project/project.yaml` (removing any license keys first)?

**Comment by bencroker** [comment]
Any update on this @luke-nehemedia?

**Comment by luke-nehemedia** [comment]
Sorry for the late reply.

Yes, I have cleared the cache (both Blitz and all Craft-Caches). I have also run the updates of Craft (now version 4.4.17) and  Blitz (now version 4.5.1).

Settings in  `config/project.yaml` are as follows:
```
blitz:
    edition: standard
    enabled: true
    licenseKey: *********************
    schemaVersion: 4.5.0
    settings:
      apiKey: ''
      cacheControlHeader: 'public, s-maxage=31536000, max-age=0'
      cacheDuration: null
      cacheElementQueries: true
      cacheElements: true
      cacheGeneratorSettings:
        __assoc__:
          -
            - concurrency
            - '5'
      cacheGeneratorType: putyourlightson\blitz\drivers\generators\HttpGenerator
      cacheNonHtmlResponses: false
      cachePurgerType: putyourlightson\blitz\drivers\purgers\DummyPurger
      cacheStorageSettings:
        __assoc__:
          -
            - folderPath
            - '@webroot/cache/blitz'
          -
            - compressCachedValues
            - '1'
      cacheStorageType: putyourlightson\blitz\drivers\storage\FileStorage
      cachingEnabled: true
      debug: true
      deployerType: putyourlightson\blitz\drivers\deployers\DummyDeployer
      driverJobPriority: 100
      esiEnabled: false
      excludedQueryStringParams:
        -
          __assoc__:
            -
              - siteId
              - ''
            -
              - queryStringParam
              - gclid
        -
          __assoc__:
            -
              - siteId
              - ''
            -
              - queryStringParam
              - fbclid
      excludedUriPatterns:
        -
          __assoc__:
            -
              - siteId
              - '2'
            -
              - uriPattern
              - '/kontakt/kontaktformular.*'
        -
          __assoc__:
            -
              - siteId
              - '2'
            -
              - uriPattern
              - '/service/anfrage-stellen.*'
        -
          __assoc__:
            -
              - siteId
              - '1'
            -
              - uriPattern
              - '/contact/contact-form.*'
        -
          __assoc__:
            -
              - siteId
              - '1'
            -
              - uriPattern
              - '/service/repair-inquiry.*'
        -
          __assoc__:
            -
              - siteId
              - '4'
            -
              - uriPattern
              - '.*'
        -
          __assoc__:
            -
              - siteId
              - ''
            -
              - uriPattern
              - '/ajax/*'
        -
          __assoc__:
            -
              - siteId
              - '2'
            -
              - uriPattern
              - '/kontakt/kontakt.*'
        -
          __assoc__:
            -
              - siteId
              - '1'
            -
              - uriPattern
              - '/contact/contact.*'
      generatePagesWithQueryStringParams: true
      hintsEnabled: true
      includedQueryStringParams:
        -
          __assoc__:
            -
              - siteId
              - ''
            -
              - queryStringParam
              - '.*'
      includedUriPatterns:
        -
          __assoc__:
            -
              - siteId
              - '2'
            -
              - uriPattern
              - '.*'
        -
          __assoc__:
            -
              - siteId
              - '1'
            -
              - uriPattern
              - '.*'
        -
          __assoc__:
            -
              - siteId
              - '5'
            -
              - uriPattern
              - '.*'
        -
          __assoc__:
            -
              - siteId
              - '6'
            -
              - uriPattern
              - '.*'
      injectScriptEvent: DOMContentLoaded
      integrations:
        - putyourlightson\blitz\drivers\integrations\CommerceIntegration
        - putyourlightson\blitz\drivers\integrations\FeedMeIntegration
        - putyourlightson\blitz\drivers\integrations\SeomaticIntegration
      maxRetryAttempts: 10
      maxUriLength: 255
      mutexTimeout: 1
      outputComments: true
      purgeAssetImagesWhenChanged: true
      queryStringCaching: 0
      queueJobTtr: 300
      refreshCacheAutomaticallyForGlobals: true
      refreshCacheJobPriority: 10
      refreshCacheWhenElementMovedInStructure: true
      refreshCacheWhenElementSavedNotLive: false
      refreshCacheWhenElementSavedUnchanged: false
      refreshMode: 3
      sendPoweredByHeader: true
      ssiEnabled: false
      trackElementQueries: true
      trackElements: true
```

The options in the template of the homepage are:
```
{% do craft.blitz.options({
	cachingEnabled: true,
	trackElements: true,
	trackElementQueries: true,
	cacheDuration: 'P10D',
	tags: ['home', 'news']
}) %}
```

**Comment by bencroker** [comment]
That all looks good. Can you show me the template code that outputs the homepage and its entry index?

**Comment by luke-nehemedia** [comment]
Sure:

`startseite.twig` basically has the same template as all other pages. The only exceptions are `_highlightCards` and the listing of the news articles and expo dates.

```
{% do craft.blitz.options({
	cachingEnabled: true,
	trackElements: true,
	trackElementQueries: true,
	cacheDuration: 'P10D',
	tags: ['home', 'news']
}) %}

{% set title = entry.title %}
{% extends "clientname/_layouts/site" %}

{% block main %}
			
		{# Show titleimage #}
		{% include "clientname/_includes/_titleImage"  %}

		{# Show factrow if enabled on site #}
		{% if entry.showFactsRow == 1 %}
			{% include "clientname/_includes/_factRow" %}
		{% endif %}
		
		{# Show notifications #}
		{% include "clientname/_includes/_notifierRow" %}
		
		{% include "clientname/_includes/_highlightCards" %}
		
		{# Content-Builder #}
		{% include "clientname/_includes/content-builder" %}
		
		{# News articles #}
		<section id="news" class="container">
			<h2>{{ 'Aktuelles'|t }}</h2>
			{% paginate craft.entries().section('aktuelles').limit(12) as pageInfo, pageEntries %}
			{% include "clientname/aktuelles/_cards" with {pageEntries: pageEntries}%}
			
		</section>
		
		{# Expo events #}
		<section id="messe" class="container">
			<h2>{{ 'Messetermine'|t }}</h2>
			{% include 'clientname/messetermine/_list' %}
		</section>
{% endblock %}
```

This is the content of `_highlightCards`:

```
{% if entry.highlightCards is defined and entry.highlightCards|length %}
	{% set cards = entry.highlightCards %}
{% endif %}

{% if cards is defined %}
<section class="container-fluid highlightcards highlightcards-grey">
	<div class="row">
		{% for highlight in cards.all() %}
		<div class="col-xs-12 col-sm-6 col-md-6 col-lg-3 highlightcard">
			<div class="animated" data-av-animation="slideInUp">
				<div class="image" style="position: relative;">
					{% include "clientname/_includes/_img" with {image: highlight.titleimage.one()} %}
					{% if highlight.overlayTextTitelbild|length %}
					<div class="image-overlay title">
						<h2>{{highlight.overlayTextTitelbild}}</h2>
					</div>
					{% endif %}
				</div>
				<div class="text">
					<h3>{{highlight.titel|raw}}</h3>
					<p>{{highlight.teaser}}</p>
					<p>{{highlight.linkto.getLink({class: 'btn btn-primary'})}}
						{% if highlight.linkto %}
							{{highlight.linkto2.getLink({class: 'btn btn-primary'})}}
						{% endif %}
					</p>
				</div>
			</div>
		</div>
		{% endfor %}
	</div>
</section>
{% endif %}
```

And this is the content of `messetermine/_list`:

```
<table class="table">
    <thead>
    <tr>
        <th scope="col">Titel</th>
        <th scope="col">Zeitraum</th>
        <th scope="col">Ort</th>
    </tr>
    </thead>
    <tbody>
    {% for messe in craft.entries().section('messetermine').all() %}
    <tr>
        <th scope="row">{{messe.title}}</th>
        <td>{{messe.termin}}</td>
        <td>{{messe.messeort}}</td>
    </tr>
    {% endfor %}
    </tbody>
</table>
```

And finally, this is `aktuelles/_cards`

```
{% if pageEntries|length == 0 %}
	<div class="alert alert-dark" role="alert">{{'nicht verfügbar'|t}}</div>
{% endif %}

	<div class="row row-cols-2 row-cols-sm-3 row-cols-md-3 row-cols-lg-4">
	{% for artikel in pageEntries %}
		<div class="col artikel-card">
			<div class="titleimage">
				{% include "_globalcomponents/responsiveImage" with {image: artikel.titleimage.one(), class: 'img-responsive', sizes: '(max-width: 640px) 50vw, (max-width: 900px) 30vw, (max-width: 1200px) 296px, (max-width: 1600px): 216px, 261px', transform: 'thumbnail'} %}
				<div class="overlay">
					<div class="text">
						<h3>{{artikel.title}}</h3>
						<span class="badge bg-info rounded">{{artikel.aktuellesCategory.one()}}</span>
						<p class="small">{{artikel.richText|striptags|truncate(70)}}</p>
						<a href="{{ artikel.url }}" alt="Link zum Artikel" title="Artikel lesen" class="btn btn-primary btn-sm">Artikel lesen</a>
					</div>
				</div>
			</div>
			
		</div>
	
	{% endfor %}
	</div>
	
	
	{% if pagination %}
		{% include "_globalcomponents/pagination" %}
	{% endif %}
```

I cannot spot any code that would interfere with Blitz. 

I also realised today that it does also affect other entries than just the homepage.

**Comment by bencroker** [comment]
So I see that `entry.title`, `entry.showFactsRow` and `entry.highlightCards` are all output. Can you test whether changing those specific field values in the homepage entry results in the page being refreshed?

As an aside, I’d suggest refactoring some of your code in `_highlightCards`.

```twig
{% set cards = entry.highlightCards.all() %}
{% if cards is not empty %}
	...
{% endif %}
```

**Comment by luke-nehemedia** [comment]
Oh yes, indeed! I will do the refactoring. 

With regard to your question: Even when I delete the whole template and only render a `<h1>Hello World</h1>` the problem persists.

**Comment by bencroker** [comment]
Can you please follow the steps below and let me know if and where it goes astray?

1. In the `blitz_caches` database table you should find a row for the homepage, indicated by an empty value for `uri`. Note the `cacheId`. If it does not exists then the page must not be cached.
2. In the `blitz_cacheelements` database table you should find a row with the `cacheId` linked to the `elementId` of the homepage entry. If it does not exists then the cached homepage must not be linked to the homepage entry.
3. Open the homepage entry, modify the title and save the entry.
4. A `Refreshing Blitz Cache` queue job should be added to the queue and executed.
5. When the queue job is complete, the cached homepage should have a new timestamp in the bottom of the HTML source code when you visit it, and the row in the `blitz_caches` database table should be regenerated, meaning that it will have a new `cacheId`.

**Comment by luke-nehemedia** [comment]
1. I have found the table `blitz_caches`. For each `siteId` there is an entry (id = 1) with an empty value for `uri`. Interestingly, those "homepages" are the only entries, where an `expiryDate` is given (which is in the past). For all other sites, the `expiryDate` is set to `NULL`. There is no column `cacheId`, but I guess that `id` is the equivalent. 
2. The table `blitz_cacheelements` is called `blitz_elementcaches` in my system and lists 75 element-ids associated with the `cacheId` 1.
3. Done that.
5. The queue job updates 287 pages, but in the logs I also see about 287 times the message of the attached query string.
6. The time stamp is still from this morning, where I manually refreshed the cache. The table `blitz_caches` is unchanged. The homepage is still the item with `id` 1 and the same `expiryDate`.

**Comment by bencroker** [comment]
Can you please send a dump of the database, along with both composer files, to support@putyourlightson.com and I’ll test it locally?

**Comment by luke-nehemedia** [comment]
Just sent you a copy of the files.

**Comment by bencroker** [comment]
This issue turned out to be caused by the Async Queue plugin. After deactivate the plugin, everything worked as expected.
