### ISSUE TITLE
Response headers are not appearing consistently

### ISSUE THREAD

**Issue by chrishouse** [putyourlightson/craft-blitz#546]
We are trying to set the x-frame-options header using this Twig code:
{% header('X-Frame-Options: SAMEORIGIN') %}

It works fine on staging (where caching is disabled), but where we have Blitz caching enabled it only works briefly after clearing cache, then it doesn't work on subsequent reloads.

**Comment by bencroker** [comment]
Blitz statically caches the rendered output of pages, meaning that the once cached, the template that includes setting the header will no longer be executed. To set headers across the site, I suggest using Apache or Nginx configurations, or the appropriate configuration settings for your hosting setup. 

Here’s an example of doing it with Nginx:

```
server {
   add_header X-Frame-Options "SAMEORIGIN";
}
```
