### ISSUE TITLE
Cache empty after refresh

### ISSUE THREAD

**Issue by seanconn** [putyourlightson/craft-blitz#547]
The cache has 0 pages after running "refresh cache" in blitz utilities. The messages appears saying that cache is queued for warming but the list of cached pages never becomes populated. There are no error messages. The blitz log simply says "Blitz cache successfully refreshed and queued for warming." Only way to add pages to the cache seems to be loading them in the browser.

Craft
3.8.17

Blitz
3.12.10

**Comment by bencroker** [comment]
The debug [config setting](https://putyourlightson.com/plugins/blitz#config-settings) can help troubleshoot why pages are not being cached. Can you enable it and check for clues in the logs?

**Comment by eddiedale** [comment]
I made the mistake of trying to warm cache while "isSystemLive" was false. Then this happens. 

With debug on it will tell you that you get 503's, but without debug on it seems to just do its thing, but still not populate the cache.

**Comment by bencroker** [comment]
Yup, that is the expected behaviour, glad you got to the bottom of it!

**Comment by eddiedale** [comment]
@bencroker Ui, sorry if unclear, I don't have anything to do with this GitHub issue.
I just wanted to give a personal experience that might be relevant. I don't know if it is relevant or not to @seanconn 😅

**Comment by bencroker** [comment]
Ah I see, well either way enabling debug mode should help.
