### ISSUE TITLE
Include Dynamic Template Question

### ISSUE THREAD

**Issue by thomasdefilippis** [putyourlightson/craft-blitz#548]
In the documentation, it reads, 

"This function is useful for including a dynamic template – one whose content is never cached but is dynamically rendered by Twig each time it’s called. It returns a script that injects the contents of the template via an AJAX request."

The only template content that I could return was a single string or number like the cart total:

`{{ craft.commerce.carts.cart.totalQty() }}`

My code to call this template was:
                 
` {% set options = { placeholder: '...',} %}`
  `{{ craft.blitz.includeDynamic('partials/commerce/_cartTotal', { }, options) }}`

Is there a way to return more complex craft template types and if so how? Do I need to use javascript each time to call a custom controller?

**Comment by bencroker** [comment]
You can put any code you want into the dynamically included template. The rendered output is what is then injected into the cached page in place of the Twig tag. Does that make sense?

**Comment by thomasdefilippis** [comment]
Okay for example.

If I put the following into my craft template partial:

```
{% from 'macros' import fa_icon %}

{% set creditCards = craft.entries.title('Globals').one().acceptedCreditCards %}

{% for card in creditCards %}
	<div class="svg-md svg-primary">{{fa_icon (card.svg.label, 'brands')}}</div>
{% endfor %}
```

I just get 1 back, but not the actual divs. I cleared all blitz cache and also cleared default craft cms.

So, I am wondering whether I am missing something here or doing something incorrectly?

**Comment by thomasdefilippis** [comment]
Here is the html that I get in the browser:

```<span id="blitz-inject-1" class="blitz-inject blitz-inject--injected" data-blitz-id="1" data-blitz-uri="/" data-blitz-params="action=blitz%2Finclude%2Fdynamic&amp;index=1190525167" data-blitz-property="">1</span>```

**Comment by bencroker** [comment]
I’m not sure this has anything to do with Blitz. If you access the template partial directly, does it work? You can do this by renaming the template to `partials/commerce/cartTotal` and visiting the URL in the browser.

Also, can you check what the raw response is in the browser’s network tab for the request to the controller action?

**Comment by thomasdefilippis** [comment]
Yep, so when I access directly:

```
<div class="svg-smmd">
    {{ fa_icon ('basket', 'regular') }}
</div>
{% set options = {
         placeholder: '...',
 } %}
{{ craft.blitz.includeDynamic('partials/commerce/_cartTotal', { }, options) }}
{% include 'partials/commerce/_cartTotal' %}
```

I get the div back but not when I use the craft include Dynamic I just get '1'


So, the raw response shows the following, so it appears to be returning the correct information.

```
<div class="svg-md svg-primary">
    <svg xmlns="http://www.w3.org/2000/svg" height="1em" viewBox="0 0 576 512">
        <!--! Font Awesome Free 6.4.0 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2023 Fonticons, Inc. -->
        <path d="M48 480C21.49 480 0 458.5 0 432V80C0 53.49 21.49 32 48 32H528C554.5 32 576 53.49 576 80V82.43H500.5L483.5 130L466.6 82.43H369.4V145.6L341.3 82.43H262.7L181 267.1H246.8V430.9H450.5L482.4 395.8L514.3 430.9H576V432C576 458.5 554.5 480 528 480H48zM482.6 364L440.4 410.3H390.5L458 338.6L390.5 266.1H441.9L483.4 312.8L525.4 266.1H576L508 338.2L576 410.3H524.6L482.6 364zM576 296.9V380.2L536.7 338.3L576 296.9zM307.6 377.1H390.6V410.3H268.6V267.1H390.6V300.2H307.6V322.6H388.5V354.9H307.6V377.2V377.1zM537.3 145.7L500.4 246.3H466L429.2 146V246.3H390.5V103H451.7L483.6 192.3L515.8 103H576V246.3H537.3V145.7zM334.5 217.6H268.6L256.7 246.3H213.7L276.1 103H327.3L390.6 246.3H346.5L334.5 217.6zM301.5 138.5L282 185.4H320.9L301.5 138.5z"/>
    </svg>
</div>
```


However, it doesn't display in the dom. Not sure why. Possibly something to do with how I am writing the include template tag?

**Comment by bencroker** [comment]
Hmm, I can’t replicate this locally. Are you running the latest version 4.5.2 of Blitz? And can you test with a simplified template partial that returns a string?

**Comment by thomasdefilippis** [comment]
Okay, so I was using 4.50 and then updated to 4.5.2 and it suddenly started working for me. I reinstalled to 4.5.0, and it looks like it still worked. So, it must have been incomplete package build or something. Thanks for your help.

**Comment by bencroker** [comment]
Glad to hear that solved it!

**Comment by thomasdefilippis** [comment]
Ben,

So, I was messing around with the plugin and ran into the same issue where the include stopped working, but I think I found a good theory of what was happening. Creating or maybe altering include with blitz turned on creates a weird issue where it doesn't load even after clearing and flushing all blitz cache and default craft cache. However, when I turned off blitz and made edits it worked (if I started editing before doing so, I had to restart my ddev env), then it would start working. Recreated this on v4.5.2 as well. Not a big deal for me, as I can turn off blitz while making include, and restart my environment if that doesn't work. Of course, this could all just be a ddev thing and not related to the plugin, but I just wanted to follow up

Do you see any problems with this statement or theory? Didn't look at all at the code for this. So just relaying my experiences with getting includes to load into the dom.

**Comment by bencroker** [comment]
If you could describe the exact steps you took so I can recreate this locally and troubleshoot then I’d be happy to do so. In these cases it’s always good to start with the simplest possible example code.

**Comment by thomasdefilippis** [comment]
Okay, I am coming back to this so that anyone else with a similar issue has an answer. Ultimately, I think that this was my own user error. By checking the network request, I found that there was an error being thrown. I was not importing a necessary macro. So, I think important thing here is if the include dynamic is not coming back, then just check the network request with the corresponding index id, and you can preview what is being returned. and see if an error is being returned. Obviously, parent imports do not get to these as in craft include statements because they are being loaded separately, so any necessary imports need to be included in the dynamic include.

Thanks again ben for your time. Love the plugin.

**Comment by bencroker** [comment]
Glad to hear you managed to troubleshoot this, @thomasdefilippis!
