### ISSUE TITLE
How do I disable caching only in development mode?

### ISSUE THREAD

**Issue by airidasbrikas23** [putyourlightson/craft-blitz#549]
Can I for example set the caching switch from an environment value?

**Comment by bencroker** [comment]
The [config settings](https://putyourlightson.com/plugins/blitz#config-settings) provide a multi-environment way to set specific plugin settings, so you can enable/disable caching per environment using the [config file](https://github.com/putyourlightson/craft-blitz/blob/develop/src/config.php).
