### ISSUE TITLE
Call to a member function getBaseUrl() on null

### ISSUE THREAD

**Issue by jskrivanek** [putyourlightson/craft-blitz#551]
Hi,

I run blitz cache via cronjob:

`*/30 * * * * craft/craft blitz/cache/refresh-expired --queue=1 &> /dev/null`

... and I run the queue every minte:

`* * * * * nice -n 15 craft/craft queue/run -v > /dev/null 2>&1 &`

Setup:

```
Craft Pro 4.4.16.1
Blitz 4.5.0
```

Error is `Call to a member function getBaseUrl() on null`. Any idea what could cause that?
![Screenshot 2023-08-27 at 9 21 37 pm](https://github.com/putyourlightson/craft-blitz/assets/12047827/aa316311-4fc9-40c3-9f0e-41d376afd73b)

**Comment by bencroker** [comment]
This could be caused by any number of things. Have you checked the `storage/logs/queue.log` file (maybe `console.log` too) for specific error messages?

**Comment by jskrivanek** [comment]
Fixed. There were `feed-me` cronjobs running for sites that have been deleted before. This might have caused the error.

**Comment by bencroker** [comment]
Glad to hear you figured it out!
