### ISSUE TITLE
Disabled Blitz Cache is still generating queue jobs

### ISSUE THREAD

**Issue by sander-lameco** [putyourlightson/craft-blitz#554]
Found this related issue https://github.com/putyourlightson/craft-blitz/issues/47 which I would like to extend on.

The situation arises in our particular case because we have a multi-site (language) setup with a lot of entries (1000+ per site), and we just added a new language to the setup at which Craft wil resave all the entries to make sure any relations are present when an Entry should exist for that language (depending on propagation method). This took almost a full day to process because every section resave it will create new Blitz Cache queue jobs for that entry and anything related. As the title mentions the Blitz Cache is disabled with the .env `BLITZ_ENABLED=0`.

Is there another way next to disabling the plugin entirely to bypass the queue jobs?
As you said it is to clear stale cache, but in this instance it doesn't really generate cache because it is disabled.

**Comment by bencroker** [comment]
What versions of Blitz and Craft are you running? The latest version 4 should be able to detect and adjust to bulk resave entry events. My recommendation in future would be to temporarily disable Blitz if this takes so long, but it’s surprising that it would.

**Comment by sander-lameco** [comment]
We're running Craft Pro `4.5.3` and Blitz `4.5.2`. I didn't see any Blitz Cache jobs mentioning a Bulk X of Y.

**Comment by bencroker** [comment]
What I meant is that when elements are resaved in bulk, Blitz should only create a single refresh cache job after all elements have been resaved.

**Comment by sander-lameco** [comment]
Ah sorry, the elements resaved in Bulk are all entries, mainly structures configured with the propagation method "Let each entry choose which site it should be saved to" and about 2 sections have propagation set to "Save to each site this section is enabled for".

When these bulk jobs are processed multiple Blitz Cache jobs are created right after the running Bulk job.

**Comment by bencroker** [comment]
> When these bulk jobs are processed multiple Blitz Cache jobs are created right after the running Bulk job.

That sounds about right, one refresh cache job per element resave batch.

So has this answered your original question above?

**Comment by sander-lameco** [comment]
Sorry my formulation of the sentence is of:
When a single Entry bulk job is processed, multiple Blitz Cache jobs are created right after the running Bulk job.

Is that still how it should work? So 1 Bulk job generates multiple Blitz Cache jobs?

**Comment by bencroker** [comment]
That’s correct – each bulk element resave event and each bulk propagate elements event will result in a refresh cache job. 
https://github.com/putyourlightson/craft-blitz/blob/e3e6ef6f18802583503136cd666db0540c3db72e/src/Blitz.php#L370-L404

**Comment by sander-lameco** [comment]
Sorry, one last question if I may:
Is it needed to rebuild the cache for all entries if Craft is resaving all existing entries just because we added a new site? Because nothing really changes for the existing entries since the propagation mode is set to `Let each entry choose which site it should be saved to`.

**Comment by sander-lameco** [comment]
Just a small update, we've pushed the update to live and not encountering any issues as of yet.

It also says `Checking X of Y node queries.` instead of generating new cache (as we've experienced on staging). The obvious difference is that on staging there was no cache, and Blitz might have been trying to regenerate it. 🤞

**Comment by bencroker** [comment]
Glad to hear it! FYI the message `Checking X of Y node queries.` is not generated by Blitz but likely by the Navigation plugin.

**Comment by sander-lameco** [comment]
Ah ok I see, but it is still a `Refreshing Blitz cache` queue job (just trying to understand whats happening).
So Blitz is then checking if any node is changed and if the caches including the navigation need updating?

The other ones say `Checking X of Y entry queries.`.

**Comment by bencroker** [comment]
Yes, any time you see a `Refreshing Blitz cache` queue job, it means that some piece of content was changed in the CMS and that triggered Blitz to check whether this affects any of the cached pages, in case it needs to refresh them.
