### ISSUE TITLE
Question: Event after clearing cache

### ISSUE THREAD

**Issue by Thijmen** [putyourlightson/craft-blitz#556]
Hi there,

I am looking for ways to hook onto Blitz events. Especially, after cache has been cleared. 
Ideally we want to do something additionally, for instance - uncache some keys at Cloudflare (to support our API).

What would be the best way to get started?

**Comment by bencroker** [comment]
The [`BaseCacheStorage`](https://github.com/putyourlightson/craft-blitz/blob/develop/src/drivers/storage/BaseCacheStorage.php) class has two events, `EVENT_AFTER_DELETE_URIS` and `EVENT_AFTER_DELETE_ALL`, that you can listen for in a custom module/plugin. Below is some code to get you started.

```php
use putyourlightson\blitz\drivers\storage\BaseCacheStorage;
use putyourlightson\blitz\events\RefreshCacheEvent;
use yii\base\Event;

Event::on(BaseCacheStorage::class, BaseCacheStorage::EVENT_AFTER_DELETE_ALL,
    function(RefreshCacheEvent $event) {
        // Do something
    }
);
```

The [`BaseCachePurger`](https://github.com/putyourlightson/craft-blitz/blob/develop/src/drivers/purgers/BaseCachePurger.php) class also has similar events that you could listen for too.

**Comment by Thijmen** [comment]
Cool Ben, thanks! And is there any event available on cache save which also has all element ids on that page? If not, would you be open for that?

**Comment by bencroker** [comment]
The [`GenerateCacheService`](https://github.com/putyourlightson/craft-blitz/blob/develop/src/services/GenerateCacheService.php) has an `EVENT_AFTER_SAVE_CACHE` event, but I’m not sure that’s what you want. If you can explain what you’re trying to achieve then perhaps I can suggest a solution.

**Comment by Thijmen** [comment]
What I am trying to achieve is the following.

I am looking for ways to add all Entry IDs which are visible on a page as a cache tag header for Cloudflare. That way, when an entry gets updated, I can uncache by tag too. This is something we want, as we are exposing an API too (non Craft, uses GraphQL). That API sends also those Entry IDs with the same header. So, if we can uncache at Cloudflare by Entry ID, that would be great for us.

So I figured that if these element Ids were available in the EVENT_AFTER_SAVE_CACHE event, I could add those IDs to the Header. In a custom module, I would uncache the tags at Cloudflare when an entry gets changed.

**Comment by bencroker** [comment]
Some like this should work.

```php
use putyourlightson\blitz\Blitz;
use putyourlightson\blitz\events\SaveCacheEvent;
use putyourlightson\blitz\services\GenerateCacheService;
use yii\base\Event;

Event::on(GenerateCacheService::class, GenerateCacheService::EVENT_AFTER_SAVE_CACHE,
    function(SaveCacheEvent $event) {
        $url = $event->siteUri->getUrl();
        $elementIds = Blitz::$plugin->generateCache->generateData->getElementIds();
    }
);
```

**Comment by Thijmen** [comment]
Cheers @bencroker, appreciated! Now what would be a good way to only find Entry ids, and not just all element ids?

**Comment by bencroker** [comment]
Something like this should work to filter down to entry IDs only.

```php
use craft\records\Entry;
use putyourlightson\blitz\Blitz;
use putyourlightson\blitz\events\SaveCacheEvent;
use putyourlightson\blitz\services\GenerateCacheService;
use yii\base\Event;

Event::on(GenerateCacheService::class, GenerateCacheService::EVENT_AFTER_SAVE_CACHE,
    function(SaveCacheEvent $event) {
        $url = $event->siteUri->getUrl();
        $elementIds = Blitz::$plugin->generateCache->generateData->getElementIds();
        $entryIds = Entry::find()
            ->select('id')
            ->where(['id' => $elementIds])
            ->column();
    }
);
```

**Comment by Thijmen** [comment]
Doh, I feel a bit stupid now 🤦  Thanks!! Appreciated.
