### ISSUE TITLE
Blitz can't save deprecation warning, 'fingerprint' column is NULL

### ISSUE THREAD

**Issue by Romanavr** [putyourlightson/craft-blitz#557]
After updating Blitz from 4.2.3 to 4.5.4, we noticed a strange issue in our monitoring tool.

```
Couldn't save deprecation warning: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'fingerprint' cannot be null
The SQL being executed was: INSERT INTO `deprecationerrors` (`key`, `fingerprint`, `lastOccurrence`, `file`, `line`, `message`, `traces`, `dateCreated`, `dateUpdated`, `uid`) VALUES ('putyourlightson\\blitz\\controllers\\TemplatesController::actionGet', NULL, '*Redacted time*', NULL, NULL, '`blitz/templates/get` has been deprecated.', '[{\"objectClass\":\"craft\\\\services\\\\Deprecator\",\"file\":\"\\/project\\/craft\\/vendor\\/putyourlightson\\/craft-blitz\\/src\\/controllers\\/TemplatesController.php\",\"line\":27,\"class\":\"craft\\\\services\\\\Deprecator\",\"method\":\"log\",\"args\":\"\\\"putyourlightson\\\\blitz\\\\controllers\\\\TemplatesController::actionGet\\\", \\\"`blitz\\/templates\\/get` has been deprecated.\\\"\"}, _**more stack trace**_
```

We have 1 template that is dynamically included via `craft.blitz.includeDynamic(...)`. Here is an example of its contents:
```
{% if craft.app.session.allFlashes|length %}
        {% if craft.app.session.hasFlash('notice') %}
                {{ craft.app.session.getFlash('notice') }}
        {% elseif craft.app.session.hasFlash('error') %}
                {{ craft.app.session.getFlash('error') }}
        {% endif %}
{% endif %}
```
Every time the page is opened we get this error in our monitoring tool.
Could you please check this issue on the plugin side or do we need to change something?
I tried include the template via the native "include" twig tag and it works fine for me, no deprecation errors/warnings or something like that.

**PHP 8.1.22**

**Craft 4.5.5**

**Blitz 4.5.4**

**Comment by bencroker** [comment]
This appears to be a bug in Craft rather than Blitz. Did you happen to update Craft along with Blitz? Also, can you search for `craft.blitz.getTemplate` in your templates? That has been deprecated and `craft.blitz.includeDynamic` should be used instead. If it is not found, then perhaps it has been cached in one of the pages. To make sure that’s not the issue, refresh the entire Blitz cache.

**Comment by Romanavr** [comment]
> This appears to be a bug in Craft rather than Blitz. Did you happen to update Craft along with Blitz? Also, can you search for `craft.blitz.getTemplate` in your templates? That has been deprecated and `craft.blitz.includeDynamic` should be used instead. If it is not found, then perhaps it has been cached in one of the pages. To make sure that’s not the issue, refresh the entire Blitz cache.

Yea, you are right, craft was also updated. About getTemplate. I fixed the deprecation and we now we use includeDynamic, however  the error still appears, but less often.

**Comment by bencroker** [comment]
Did you refresh the entire Blitz cache? It may be necessary to clear compiled templates too. If the issue continues then there must be a leftover tag somewhere in the templates.

**Comment by Romanavr** [comment]
> Did you refresh the entire Blitz cache? It may be necessary to clear compiled templates too. If the issue continues then there must be a leftover tag somewhere in the templates.

Cache was cleared a few times. After some research, I noticed that visiting this URL
site.com/actions/blitz/templates/get?template=03f2b052ad7ffc746143be5ee417f612db513b52102cb761d464bfc9bc140213_templateName.twig&siteId=1
Triggers a deprecation warning. Do you have any ideas?

**Comment by Romanavr** [comment]
I did refresh, a few times.
It appears that some users simply have a cached version of the page open in their browsers.
Thanks for the help anyway.
