### ISSUE TITLE
Cache files not generated

### ISSUE THREAD

**Issue by wei2go** [putyourlightson/craft-blitz#559]
Some of my sites don't generate Blitz cache files:
- The queued job "Generating Blitz Cache" finishes almost instantly.
- The cache folder (`@webroot/cache/blitz`) on the server is empty, after generate cache / refresh cache queue jobs are completed.
- Under "Utilities -> Blitz Cache" page in CP, the "Cached Files" section on the top of the page shows 0 Pages are cached.
- Enabled 'debug' setting in `blitz.php`, but it doesn't report any issues - "Blitz cache successfully queued for generation."
- Also no log in `queue.log`

Blitz settings are pretty much the default settings:
- Caching Enabled - On
- Refresh Mode - Clear the cache and regenerate in a queue job
- Cache Storage - Blitz File Storage
- Folder Path - @webroot/cache/blitz
- Cache Generator - HTTP Generator
- No reverse proxy / remote deployment / advance settings

System report:
```
Server: Apache
PHP version | 8.1.22
Linux 3.10.0-962.3.2.lve1.5.81.el7.x86_64
Craft Pro 4.5.5
Blitz: 4.5.4
MariaDB 10.6.15
Imagick 3.7.0 (ImageMagick 7.1.0-62)
Yii: 2.0.48.1
Guzzle: 7.8.0
```

Also it doesn't happen to all my sites with the same settings, which confuses me. Any clue?

**Comment by bencroker** [comment]
It sounds like it may be an environment-specific issue. Are pages being cached when you visit them on the front-end site?

**Comment by wei2go** [comment]
@bencroker No, they are not cached. Basically Blitz doesn't work for those sites. I didn't notice earlier as I usually use Cloudflare cache, and Blitz works like a auto cache purger, so it appears to be working.

What kind of environment specific settings will cause such an issue? Any suggestion for where should I look into?

**Comment by bencroker** [comment]
> No, they are not cached. Basically Blitz doesn't work for those sites.

Can you show me the values you are using for Included and Excluded URI Patterns in the plugin settings? Enabling the [`debug`](https://putyourlightson.com/plugins/blitz#debugging) config setting should log the reason that pages are not cached when visited to the `blitz-*.log` file.

**Comment by wei2go** [comment]
I see. Some of my sites have `.*` removed from "Included URI pattern" for some reasons, so none of the pages are being cached. Leaving "Included URI pattern" empty somehow gave me an impression that it means including all URIs by default.

All good now!

**Comment by bencroker** [comment]
Great!
