### ISSUE TITLE
Feature request: also cache custom headers

### ISSUE THREAD

**Issue by Thijmen** [putyourlightson/craft-blitz#560]
Hi,

Would it be nice to have a list of headers configured which also are being cached? Now the response is being cached, but what if I also want a custom header being cached, which is being returned as well when cache is being hit?

Would you be open for something like this?

About how it could work:

I was thinking about adding an event, BEFORE_CACHE_SAVE, which allows the developer to set the Headers. These headers would be saved as a separate array in the cache store, under the same key.

When retrieving the cache from the store, check for headers. If there are headers -> emit.

Thanks for your time.

**Comment by bencroker** [comment]
Blitz caches pages statically, so just the rendered HTML code. There is no way to reliably cache headers since cached responses can be delivered by Blitz, the web server or a reverse proxy.

**Comment by Thijmen** [comment]
I understand. I have some ideas that may add compatibility to also the file driver. Would you be open for a PR, just to see what my idea is and maybe work together if you like it? 😄

**Comment by bencroker** [comment]
Sure, with the understanding that there's a very low probability of it being accepted, given the limitations mentioned in my last comment.

**Comment by Thijmen** [comment]
@bencroker Hi there, coming back to this with an out-of-the-box idea. What if I can create a PR that adds two events;
1. An event to edit the payload that is going to the cache backend. This event would have the full HTML body + all headers of the response.
2. An event that is being called to fetch the cached contents and return them. This allows me to set headers, that are being retrieved from the changed format that I have set up in event 1.

Would you be open to allow such PR? We really would like to set certain `X-Robot-Tag` headers - amongst other headers when returning cached content.

**Comment by bencroker** [comment]
There’s nothing stopping you from setting a header in a custom plugin/module by hooking into the `CacheRequestService::EVENT_AFTER_GET_RESPONSE`. This feels like a very niche request that can already be solved for your specific use-case. Would you agree?

**Comment by Thijmen** [comment]
> There’s nothing stopping you from setting a header in a custom plugin/module by hooking into the `CacheRequestService::EVENT_AFTER_GET_RESPONSE`. This feels like a very niche request that can already be solved for your specific use-case. Would you agree?

Yes, but I believe this flow does not allow me to store the Response headers into the cache. Ofcourse I could use `CacheRequestService::EVENT_AFTER_GET_RESPONSE` to set headers, but I am looking for a solution to store them into the cache as well, albeit via an event or such.

EDIT: Hmm maybe with `EVENT_BEFORE_SAVE_AND_PREPARE_RESPONSE`?

**Comment by bencroker** [comment]
You can use the `GenerateCacheService::EVENT_AFTER_SAVE_CACHE` to store the header info in a custom table, which can be referenced later.
