### ISSUE TITLE
Field or entry panel that controls if an entry cache file is generated or not

### ISSUE THREAD

**Issue by Gnative** [putyourlightson/craft-blitz#568]
I have a set of pages in a structure that is use as the site main navigation. 

In some cases I just want to link the navigation item to a single page, via an entry field, and as this page has no content it doesn't require caching.

My current solution to prevent the cache generation is to prefix the page url with no-cache and then filter this out with in the Blitz settings "Exclude URI Patterns". As we have a lot of users with in our team, and quite a few pages in multiple languages with in the site, it's not easy to teach everyone this process.

<img width="779" alt="Screenshot 2023-10-11 at 12 10 25" src="https://github.com/putyourlightson/craft-blitz/assets/1758875/ae6184ca-03b5-47aa-a06d-4216c6364102">

It would be helpful to have a field or an entry 'panel' where we can control the caching of the page instead of relaying on users to add no-cache as a url prefix. Whether the page is cached or not can then also be displayed on the entry dashboard. 

Maybe if there was an entry panel it might also display the last time the entries cache was updated

**Comment by bencroker** [comment]
There’s nothing stopping you from excluding pages from caching using a custom field. Here’s an example using a lightswitch field with the handle `cachingDisabled`.

```twig
{% if entry.cachingDisabled %}
    {% do craft.blitz.options.cachingEnabled(false) %}
{% endif %}
```

See https://putyourlightson.com/plugins/blitz#page-specific-options
