### ISSUE TITLE
Can craft.blitz.includeCached "param" include an array?

### ISSUE THREAD

**Issue by adrianjean** [putyourlightson/craft-blitz#569]
I'm trying to include a cached file with an array of entires as dynamic content:

```
{% set articleSection = entry.slug %}

{% set entriesAll = craft.entries({ 
        section:            "article",
        orderBy:            "postDate DESC",
        articleSection:     articleSection,
        publishStatus:      "published",
        relatedTo:          ['or', {targetElement:filterEntriesByTopics}],
        with:               ['articlePhoto', 'articleAuthor', 'articlePublication','articleTopic'],
        limit:              30,
}).all() %}

{% set assetType = "article" %}
  
{{ craft.blitz.includeCached('_contentBuilder/_partials/filterPage-desktop.twig',{entriesAll,assetType}) }}
```

When I have the `entriesAll` array as a parameter, the include doesn't seem to work. However when I have the `assetType` as a parameter, the include works. 

Is it possible to set a array as a parameter element, using `includeCached` ?

**Comment by bencroker** [comment]
It should be possible to pass in the entry IDs, but not the entries themselves, as those are elements (PHP objects).

**Comment by adrianjean** [comment]
Ok — I just tried changing my element query to return only IDs:

```
{% set entriesAll = craft.entries({ 
        section: "article",
...
        limit: 4,
}).ids() %}
```

and can confirm with `{{dump(entriesAll)}}` I see an array of IDs:
```
array:4 [▼
  0 => 3609
  1 => 3346
  2 => 3133
  3 => 2572
]
```

but when I include it as a parameter it still doesn't load the page (after all Blitz caches cleared etc.)

```
{{ craft.blitz.includeCached('_contentBuilder/_partials/filterPage-desktop.twig',{'entriesAll':entriesAll,'assetType':assetType}) }}
```

**Comment by bencroker** [comment]
What exactly happens when you load the page?

**Comment by adrianjean** [comment]
Aha — it works to send an array of ID's!

The loaded page was erroring because I was feeding it ID's now instead of elements. 

Thank you!!
