### ISSUE TITLE
Commerce support

### ISSUE THREAD

**Issue by samuelbirch** [putyourlightson/craft-blitz#57]
It would be great to have blitz working with post/expire dates on products, and also promotions - sales/discounts.

**Comment by putyourlightson** [comment]
Thanks for the suggestion, we'll look into adding this in the next release.

**Comment by putyourlightson** [comment]
Version 1.11.2 added future post/expiry dates to all elements, so refreshing products should now work (they'll need to be resaved for this to take effect). 

Sales and discounts in commerce are not elements, so we'll need to consider if and how to add this functionality. I'll keep this issue open for the meantime and post an update when I can tell you more.

**Comment by putyourlightson** [comment]
After some consideration, we've decided to only support elements in cache invalidation. In saying that, Blitz v2 is currently in beta and adds flags, which should make invalidating pages that use sales/discounts posiible.
https://github.com/putyourlightson/craft-blitz/tree/v2/#flag
