### ISSUE TITLE
If I disable caching, will Blitz still send a purge request to Fastly CDN?

### ISSUE THREAD

**Issue by airidasbrikas23** [putyourlightson/craft-blitz#570]
I would like to stop local caching with Blitz, but I would like Blitz to still purge cache on the CDN on every edit.

**Comment by bencroker** [comment]
Blitz only knows what it should purge based on what it has cached. By disabling caching, you lose this functionality. A possible workaround, however, is to use a dummy cache storage driver, as discussed in https://github.com/putyourlightson/craft-blitz/issues/502.
