### ISSUE TITLE
Refresh expired as soon as possible without queue

### ISSUE THREAD

**Issue by jodeba** [putyourlightson/craft-blitz#571]
Hi, 

I'm in search for the best way to refresh cache as soon as possible, for a website with high traffic.

So it brings me to these two refresh methods:
- 2: Expire the cache and regenerate in a queue job
- 0: Expire the cache, regenerate manually

We are now using method "2: Expire the cache and regenerate in a queue job", but the queue jobs keep stacking up. For example when saving the globals two times, two very long jobs are generating all pages. They are actually refreshing the same pages twice, at the same time, because we have multiple queue/listeners

So I was thinking of changing to method "0: Expire the cache, regenerate manually", but in the docs I can't find which cron job is supposed to run, I'm guessing `blitz/cache/refresh-expired`. But how can we make sure it is always running, without running twice or more at the same time.

I was hoping a 'listen' task could be started, so you could make a systemd service for it. An alternative is to start it every minute in a cron using flock, but in case of a crash, the lock will stay, and we want to be sure it is always running.

Thank you for your time!

Best regards,
Jonathan

**Comment by jodeba** [comment]
Additionally:

When I run blitz/cache/refresh-expired, only the cached files are deleted, but not generated.
Because on [RefreshCacheService.php#L536](https://github.com/putyourlightson/craft-blitz/blob/a23bf6b7b077d5c3ea08153d2af1552de86e883a/src/services/RefreshCacheService.php#L536) there is no parameter $forceGenerate. In my case, I would want to create a cronjob that generates all the expired caches immediately, but there is no command to do this? 

I can ofcourse create my own command, but I would think that $forceGenerate should be true for method "0: Expire the cache, regenerate manually"?

**Comment by bencroker** [comment]
Hi Jonathan. It sounds like `Expire the cache and regenerate in a queue job` is what you want. Globals should generally be avoided wherever possible as per https://putyourlightson.com/plugins/blitz#2-avoid-using-globals. You use [cached includes](https://putyourlightson.com/plugins/blitz#cached-includes) for template partials that include elements and that are used in multiple pages, which should make a significant difference to the refresh cache process.

> I can ofcourse create my own command, but I would think that $forceGenerate should be true for method "0: Expire the cache, regenerate manually"?

Maybe, I’ll have to look into that a bit closer.

**Comment by jodeba** [comment]
Thank you for your feedback!
You're right about the globals and cached includes, we are working towards it, but I was thinking about using the other method in the meantime.

**Comment by bencroker** [comment]
I’ve changed the behaviour in https://github.com/putyourlightson/craft-blitz/commit/7ef3507f724a5ca6e17f174f85d9893e0381cd8e to forcibly generate new cached pages if they are not cleared.

You can test this by running `composer require "putyourlightson/craft-blitz:dev-develop as 4.6.1"`.

**Comment by bencroker** [comment]
Released in [4.7.0](https://github.com/putyourlightson/craft-blitz/releases/tag/4.7.0).
