### ISSUE TITLE
Cached includes don't regenerate when using the includedQueryStringParams setting

### ISSUE THREAD

**Issue by jodeba** [putyourlightson/craft-blitz#573]
## Steps to reproduce the issue.

1. Set some allowed query parameters in includedQueryStringParams
2. Refresh expired cached includes

## A clear and concise description of what you expected to happen.
The updated file is found in `_includes/index.html` instead of `_includes/action=blitz%2Finclude%2Fcached&index=123`

I had to include `action` and `index` to includedQueryStringParams to fix it.

## The plugin and Craft version numbers.
Craft CMS 4.5.7 with Blitz 4.6.0

**Comment by bencroker** [comment]
Can you please explain the second step, specifically how you refresh expired cached includes?

**Comment by jodeba** [comment]
Hi Ben, I'm using the method `Expire the cache and regenerate in a queue job` and run the command `php craft blitz/cache/refresh-expired`

**Comment by bencroker** [comment]
I’ve fixed this issue in https://github.com/putyourlightson/craft-blitz/commit/eb47a0c9d4517d6588445c604a7823eb7ceae79e for the next release.

You can test this by running `composer require "putyourlightson/craft-blitz:dev-develop as 4.6.1"`.

**Comment by jodeba** [comment]
Thanks a lot!

**Comment by bencroker** [comment]
Released in [4.7.0](https://github.com/putyourlightson/craft-blitz/releases/tag/4.7.0).
