### ISSUE TITLE
Blitz hints: Formie form groups generate a lot of hints

### ISSUE THREAD

**Issue by mandrasch** [putyourlightson/craft-blitz#574]
Hi,

thanks for providing the plugin!

I have many upload fields in multiple form groups in a formie form.

This causes a lot of hints :-D

![image](https://github.com/putyourlightson/craft-blitz/assets/777278/d8315839-dd2c-482c-8a0e-6eb21c8a0685)

![image](https://github.com/putyourlightson/craft-blitz/assets/777278/d882a7b2-2fdc-4cde-8136-55b7b14a132d)

`/var/www/html/vendor/verbb/formie/src/templates/_special/form-template/fields/file-upload.html:5`

Can I somehow disable checking this path?

thanks very much in advance! cheers, Matthias

**Comment by bencroker** [comment]
Thanks for the suggestion. Since this tool is intended for front-end templates, it might be wise to exclude the `vendor` folder path completely. I’ll mark this as a feature request and look into it in the coming days.

**Comment by mandrasch** [comment]
> Thanks for the suggestion. Since this tool is intended for front-end templates, it might be wise to exclude the `vendor` folder path completely. I’ll mark this as a feature request and look into it in the coming days.

Thanks!

(What I forgot to mention: I use these fields in a `templates/formie/my-email-template.twig` and a pdf template. I access row of form groups with `{% set row = submission.myFormGroup.one() %}`. Haven't had time to investigate properly if this triggers the hints - but I don't use .all() or else in my email template. Formie automatically provides the `submission` object in these templates https://verbb.io/craft-plugins/formie/user-guides/the-complete-guide-to-rendering-submission-content)

**Comment by bencroker** [comment]
Released in Blitz Hints [1.1.0](https://github.com/putyourlightson/craft-blitz-hints/releases/tag/1.1.0). Running `composer update` should get you to the latest version.

**Comment by mandrasch** [comment]
Nice, thanks very much! 👍
