### ISSUE TITLE
Mixed Caching for logged in/logged out users

### ISSUE THREAD

**Issue by shifuma** [putyourlightson/craft-blitz#576]
I've looked through the docs and a few issues (for example [this](https://github.com/putyourlightson/craft-blitz/issues/552), [this](https://github.com/putyourlightson/craft-blitz/issues/270) and [this](https://github.com/putyourlightson/craft-blitz/issues/169)) but I'm not sure if my scenario quite matches.

I have a template that checks `if currentUser` and if they're logged out, it shows the first 5 blocks in a Matrix field. If they're logged in, it shows them all (20 or so blocks). These 20 blocks are quite heavy, with relation fields, so I want to cache the content if possible.

I understand I could do something like:

```
## Main Entry template
{{ craft.blitz.includeDynamic('matrixField.twig') }}

## matrixField.twig
{% if currentUser %}
  {# Show all blocks #}
{% else %}
  {# Show first 5 blocks #}
{% endif %}
```

And that would handle the `if currentUser` part of it. But is there any way to then also cache the output based on whether `currentUser` is true or not?

As I type this, I feel like the answer is going to be 'no, it isn't possible' but I just wanted to ask. Thanks for your time.

**Comment by bencroker** [comment]
You should be able to use a cached include for this, which would work well if you have SSI enabled. 

``` twig
{% if currentUser %}
    {{ craft.blitz.includeCached('_allBlocks') }}
{% else %}
    {{ craft.blitz.includeCached('_someBlocks') }}
{% endif %}
```

Or, if you want to reuse the template:

``` twig
{% if currentUser %}
    {{ craft.blitz.includeCached('_blocks', { limit: null }) }}
{% else %}
    {{ craft.blitz.includeCached('_blocks', { limit: 5 }) }}
{% endif %}
```

If SSI is not an option then you can also just use Craft’s native `cache` Tag.

**Comment by shifuma** [comment]
Ah that's great! I completely missed it. Will give it a shot, thanks!
