### ISSUE TITLE
PHP error when generating cache

### ISSUE THREAD

**Issue by GaelPQCQ** [putyourlightson/craft-blitz#578]
![Screenshot 2023-11-02 at 11 18 19](https://github.com/putyourlightson/craft-blitz/assets/141964242/a7ec0049-7d7c-42b3-b897-9bccf66b50c2)

- Steps to reproduce the issue
I have two sites in my Craft instance.
I click on Generate cache and I get the error, same with the console command.

- A clear and concise description of what you expected to happen.
The cache is generated without any error

- The plugin and Craft version numbers.
Craft 4.5.9
Blitz 4.7.0

**Comment by bencroker** [comment]
Do you have custom site URIs defined in config settings (via a `blitz.php` file) and, if so, is the setting correctly formatted?

**Comment by GaelPQCQ** [comment]
No I don't have a `blitz.php` file.
I tried setting up the cache only on one site (instead of all sites) but it does the same error still.

**Comment by kerrig** [comment]
I'm also running into this same error (same versions as well). We do have a blitz.php file but no custom site URIs are defined. Seems like this happened with the most recent update as I just updated today and this was working fine before the update.

**Comment by bencroker** [comment]
Thanks for reporting and confirm this! Fixed in https://github.com/putyourlightson/craft-blitz/commit/2feda81e4069d831b4f8bb7189f86e66008d9d28 for the next release.

You can test this by running `composer require "putyourlightson/craft-blitz:dev-develop as 4.7.1"`.

**Comment by bencroker** [comment]
Released in [4.7.1](https://github.com/putyourlightson/craft-blitz/releases/tag/4.7.1).

**Comment by GaelPQCQ** [comment]
Thank you very much for this fast correction!
