### ISSUE TITLE
Manual warming

### ISSUE THREAD

**Issue by samuelbirch** [putyourlightson/craft-blitz#58]
Is there an option to be able to call a function and pass in an array or urls to flush and warm?

As part of this is it possible to disable then re-enable the cache so that when updating a load of elements from an api request we don't add a load of jobs to the queue when some of those maybe be flushing and warming the same page.

**Comment by putyourlightson** [comment]
> Is there an option to be able to call a function and pass in an array or urls to flush and warm?

Right now it's an all or nothing scenario. What might the use-case be for selectively clearing/warming URLs?

> As part of this is it possible to disable then re-enable the cache so that when updating a load of elements from an api request we don't add a load of jobs to the queue when some of those maybe be flushing and warming the same page.

The easiest way to acheive this is to disable (not uninstall) the plugin from the plugins page in the control panel.

**Comment by samuelbirch** [comment]
The user case for selectively clearing/warming URLs, is that i have a custom route that renders out some categories, which has a different url format than the category so therefore is not trigger by the element update. I would like to be able to check for this particular category update in a custom site module and flush and warm the cache for it, without doing the whole site.

The disable/enable user case is that I'm integrating with a 3rd party API to receive stock and price updates for products. I can obviously get quick a few product/variants within this update, and the variants would cause the same cache urls to be cleared and warmed multiple times - is that correct?
So i was thinking it would be good to be able to temporary disable the cache which i process these updates and keep a track of the element id's myself. Then when completed, enable the caching again and fire off the call to flush and warming the cache by the element ids.

**Comment by putyourlightson** [comment]
When any URL is cached by Blitz, the URI is saved in the `blitz_caches` table and any elements (including categories) will be saved in the `blitz_elementcaches` table. When those elements are updated, the cached URIs are refreshed, so even with a custom route, the cache should remain warm. Can you please test that this is working in your case?

If the updates come in a single API call (a single request to Craft), then Blitz is smart enough to collect all the updates and put them into a single refresh job, so I don't foresee this being an issue.

**Comment by samuelbirch** [comment]
i'll test it out and let you know.

**Comment by putyourlightson** [comment]
Any update on whether this is still an issue for you?

**Comment by putyourlightson** [comment]
Assuming this is resolved as no update in a month, let me know if otherwise.

FYI Blitz v2 is in beta and adds more fine-grained control over how cached pages are refereshed.
https://github.com/putyourlightson/craft-blitz/tree/v2
