### ISSUE TITLE
Media embeds/iframes not showing up when caching is enabled

### ISSUE THREAD

**Issue by ejaedesign** [putyourlightson/craft-blitz#582]
Hi there,

Running Craft 3.9.1, media embeds (such as YouTube, Vimeo, SoundCloud) suddenly stopped displaying when caching is enabled. 

When caching is disabled, the embeds show:

https://www.theologyofwork.org/resources/could-family-be-part-of-a-calling

The odd thing is this just started to happen a couple of days ago. I thought it was the plugin I was using (oEmbed) but it still happens when straight iframe (raw) is used as well. 

There were no updates done before or after the embeds stopped displaying (when caching is enabled). The site currently has the caching off. 

Thanks in advance!

**Comment by bencroker** [comment]
Can you perhaps create and cache a test page with embeds, so I can take a closer look and we can compare the difference?

**Comment by ejaedesign** [comment]
Hi Ben,

Oddly, the videos and audio are now appearing WITH caching enabled. If it
happens again, I'll touch base with you again.

Thanks for reaching out right away!

Jae

**Comment by bencroker** [comment]
Ok, great!
