### ISSUE TITLE
Issue with `preloadSingles` and eager loading

### ISSUE THREAD

**Issue by vandres** [putyourlightson/craft-blitz#583]
We entrified our installation and use Singles for all "global" tasks. With `preloadSingles()` in the general.php, the use is very painless.

Now I ran into an issue, that templates don't get invalidated, when e.g. the navigation changes.

To reproduce:

- enable `preloadSingles()`
- create a Single "header"
- create a Structure "page"
- create a field "navigation", which is an entry field for "page"
- add that field to "header"
- create some pages and put some of them in the header.navigation field
- create the navigation template (see below)
- you will get Blitz hint for eager loading navigation
- add eager loading for "globals" (see below)
- now the hint is gone, but the cache no longer refreshes

When I use this syntax `{% set header = craft.entries.section('header').with(['navigation']).one() %}`, everythings works as expected. But I would prefer to preload the Singles.

```
{# Navigation template #}
{% if header.navigation.all() | length %}
      <ul>
        {% for link in header.navigation.all() %}
          <li><a href="{{ link.url }}">{{ link.title }}</a></li>
        {% endfor %}
      </ul>
{% endif %}
```

```
{# Eager load navigation in header #}
{% do craft.app.elements.eagerLoadElements(
  className(header),
  [header],
  ['navigation']
) %}
```

**Comment by bencroker** [comment]
Just tested this locally and it is working as expected. Are you running the latest versions of both Blitz and Craft?

**Comment by vandres** [comment]
Yes

**Comment by bencroker** [comment]
If you can share a ddev test repo then I can take a closer look.

**Comment by bencroker** [comment]
Also, how exactly are you triggering the cache to refresh?

**Comment by vandres** [comment]
> Also, how exactly are you triggering the cache to refresh?

I don't do anything separate to refresh the cache. `refreshMode` is set to 3

```
  'cacheStorageSettings' => [
    'folderPath' => '@webroot/cache/blitz',
    'compressCachedValues' => true,
    'countCachedFiles' => true,
  ],
```

**Comment by bencroker** [comment]
> I don't do anything separate to refresh the cache.

You’ll need to do _something_ to trigger the page to refresh. Can you test by changing and saving the title of one of the entries that appears in the header navigation?

If that doesn’t work then the next step would be to set up and send me a test repo.

**Comment by vandres** [comment]
You are right, the cronjob takes care of it

![Bildschirmfoto 2023-11-17 um 12 37 38](https://github.com/putyourlightson/craft-blitz/assets/1436383/c4e7a9ff-d886-454c-8d6e-9b972e1a6775)

When I change the title of the page, everything is refreshing. But if I only add one entry to the navigation field, then nothing.


![grafik](https://github.com/putyourlightson/craft-blitz/assets/1436383/f109df15-eb37-4cb8-9063-b53c2d97352d)

I cannot share this repo. I will try to rebuild the behaviour on the weekend on a naked repository

**Comment by bencroker** [comment]
Ok, in that case it sounds like this may be a different issue. Please open a new GitHub issue once you’ve confirmed whether you can reproduce it on a fresh test site.

**Comment by vandres** [comment]
Don't know what you mean. It is exactly the behaviour I described in the initial description. When changing an eager loaded field, the cache is not refreshing. 

I will reopen with a fresh repository

**Comment by bencroker** [comment]
Ok, I must have misunderstood. Can you please explain the exact steps you are taking when testing this? It is hard to reproduce locally when I don’t have your setup and the steps are unclear.

**Comment by vandres** [comment]
I will create that repo for you this weekend, with an initial db. Is DDEV okay for you?

**Comment by bencroker** [comment]
DDEV is perfect. Let’s do that in a new GitHub issue, please.
