### ISSUE TITLE
Refresh cache not behaving as expected

### ISSUE THREAD

**Issue by rellafella** [putyourlightson/craft-blitz#586]
Craft Pro 4.5.11
Blitz 4.9.0

This could very well be me not understanding quite how this works but i'll try and explain as best as I can.

I am using the "Expire the cache, regenerate manually or organically" mode. I am also using server rewrites with Apache so I have to manually regenerate.

I am trying to understand this by cause and effect:
- user hits the page => index.html and index.html.gz files get created in my cache directory
- content author updates page => blitz to expire the cache ?
- manually run "refresh cache" either from utilities, command line or action url => blitz creates new index.html and index.html.gz files

What I am experiencing is that once the page is cached, the only way I can get the latest updates is to clear the cache (either the entire cache or a specific page), then revisit the page. 

I am not sure what I am missing.

**Comment by bencroker** [comment]
This should work, assuming what is updated is an attribute (such as the title) or a custom field that is output on the page. Running "refresh expired" via the Blitz cache utility or via the console command should regenerate the cached files. Running "refresh" should also work, but is more heavy handed.

**Comment by rellafella** [comment]
Ok that's good to know that we're on the same page then. Also good to know that "refresh expired" should work, that was what I initially wanted to use. 

> @kayqq The Guzzle warmer needs your site to be publicly accessible. If it is not (although I don't see why you'd need to cache a non-public site) then you can try using the Local warmer. #208

Turns out this was our issue, our staging environment isn't publicly accessible so needed to use the local generator. Now it seems to work perfectly.

**Comment by bencroker** [comment]
Right, also documented at https://putyourlightson.com/plugins/blitz#cache-generation

**Comment by jon-collette** [comment]
Ah, ran into this issue while working with restricted IP access dev server
