### ISSUE TITLE
Focal point change inside entry

### ISSUE THREAD

**Issue by luizboaretto** [putyourlightson/craft-blitz#587]
We have a similar issue #431

If I change the focal point inside "Assets" page, it works. 
If I change focal point inside entry: clicking once on the image and opening a popup, after dragging the focal point the image is removed and the cache is not cleared

- Craft 4.5.11.1
- Blitz 4.9.1

**Comment by bencroker** [comment]
I cannot reproduce this locally, following your steps seems to work fine for me. Can you please double check and see if you can provide any further details?

**Comment by luizboaretto** [comment]
@bencroker I noticed it's something intermittent so I'm trying to figure out how to reproduce

**Comment by bencroker** [comment]
Any update on this, @luizboaretto?

**Comment by luizboaretto** [comment]
@bencroker For some reason I couldn't reproduce any more after an DDEV update, let's close it and if it happens again I'll try to get more information
