### ISSUE TITLE
Dont collect site URLs unless "generateOnRefresh" is selected.

### ISSUE THREAD

**Issue by Romanavr** [putyourlightson/craft-blitz#590]
Hi,
I have a large site with over 50 subsites, and after a recent Blitz update, I ran into an SEOmatic issue where the "Content SEO" update results in a very looooooong save and sometimes causes a **PHP timeout**.
In fact, **we have this case before** a year ago(almost on the same date, lol). https://github.com/putyourlightson/craft-blitz/issues/455

So I went to check what could be wrong here and, surprise, found that it was the same problem as last time.
**Getting website URLs takes a lot of time** when saving anything in SEOmatic as it triggers blitz cache refresh.

My mode is set to `clearOnRefresh` so I don't see any good reason to collect site URLs in this case.
I understand that it is being used right now in the `EVENT_BEFORE_REFRESH_ALL_CACHE`, but from my point of view **it make no sense  to have `$siteUris` here,** before the 
`if (Blitz::$plugin->settings->generateOnRefresh()) {`
line

. It **doesn't change site URLs after the event fires**, so we can remove it and if the some developer wants to use it, they can just look at the source code and use them at the same way.

**I suggest [589](https://github.com/putyourlightson/craft-blitz/pull/589) as a solution**, but if you disagree, please let's find something else where we don't need to collect site URLs unless "generateOnRefresh" is selected. (for the 3.x it was fixed in https://github.com/putyourlightson/craft-blitz/pull/456)
With this solution, saving in SEOmatic takes only a few seconds instead of 1+ minute.

Craft pro 4.5.11.1
Blitz 4.9.1

**Comment by bencroker** [comment]
Thanks for the explanation. I’ve reverted this in https://github.com/putyourlightson/craft-blitz/commit/4fb6f0a2df398a4c52cd076ca481d85fa987a7fa and released in [4.9.2](https://github.com/putyourlightson/craft-blitz/releases/tag/4.9.2).

**Comment by Romanavr** [comment]
> Thanks for the explanation. I’ve reverted this in [4fb6f0a](https://github.com/putyourlightson/craft-blitz/commit/4fb6f0a2df398a4c52cd076ca481d85fa987a7fa) and released in [4.9.2](https://github.com/putyourlightson/craft-blitz/releases/tag/4.9.2).

Thanks for the quick response!
