### ISSUE TITLE
Refresh cached URLs section in blitz utility

### ISSUE THREAD

**Issue by rellafella** [putyourlightson/craft-blitz#592]
Craft Pro    4.5.11.1
Blitz            4.9.3
--

We have a relatively large content heavy website (3000+ pages).

Our caching strategy is "Expire the cache, regenerate manually or organically", we are manually refreshing via a Cron job that utilizes the CLI refresh-expired-cache command.

Since this is a large site, we can only run this every 3 hours at this time, we are in the process of optimizing templates with various recommended strategies (SSI, eager loading, page specific rules etc.) with the aim of increasing the regularity of the Cron job.

If we need to manually regenerate a page, I am hoping that we can use the Refresh cached urls utility in the control panel, however this doesn't seem to work as I would expect.

When I put a single url into the table and hit the button, I would expect to see that index.html file for that given path be deleted then the next visit to that URL would trigger a regeneration. 

That doesn't seem to be the case, the file remains there and the only way I seem to be able to refresh the page outside of triggering a large amount of pages to be refreshed is to manually remove that index.html file from the server's filesystem.

Should this technique work? I am struggling to find ways to debug/understand what is supposed to be happening under the hood.

**Comment by bencroker** [comment]
The refresh cached URLs utility will respect the refresh mode, so if it is set to `Expire the cache, regenerate manually or organically` then the cached page will be marked as expired. Optimising the templates should significantly help in reducing the work require to generate expired cache, which should ultimately allow you to run the cron job more frequently.

**Comment by rellafella** [comment]
That does bring me to another problem we seem to be having. Which is when the refresh expired cache job runs, the amount of pages that need refreshing is constantly very high, even in times where there haven't been any changes made to content. From my understanding there are a few different things that will influence the amount of pages that need refreshing:
1. As more pages are cached, the potential that some of those pages are related to others increases
2. We cache pages with query strings as separate pages for now, so as more pages are visited with query strings this would contribute to the first point.
3. Some pages that are updated would have more related pages than others.
4. Simply the amount of pages updated within the 3 hour window.

We're logging the time taken for the cron job to complete so we can get an idea of how often we can run it, we're even logging this out of office hours (which is a relatively low traffic time for our site too). I would expect that when it goes to run during this time that the amount of pages that needs refreshing is significantly decreased compared to the rest of the day. But that doesn't seem to be the case.

Do you have any suggestions on trying to get to the bottom of what could possibly be triggering so many pages to require regeneration?

**Comment by bencroker** [comment]
One of the suggestions given in the [common issues](https://putyourlightson.com/plugins/blitz#common-issues) section of the docs is to run the following SQL queries to track down pages that are referenced by elements and element queries more than `n` number of times. That might give you some ideas for potential optimisations.

```
SET @n := 1000;

#- Returns pages that are referenced by elements more than `n` times.
SELECT uri, count FROM blitz_caches INNER JOIN (
	SELECT cacheId, count(*) as count FROM blitz_elementcaches GROUP BY cacheId HAVING count(*) > @n
) AS t ON blitz_caches.id = t.cacheId;

#- Returns pages that are referenced by element queries more than `n` times.
SELECT uri, count FROM blitz_caches INNER JOIN (
	SELECT cacheId, count(*) as count FROM blitz_elementquerycaches GROUP BY cacheId HAVING count(*) > @n
) AS t ON blitz_caches.id = t.cacheId;
```

**Comment by rellafella** [comment]
Thanks Ben I'll give that a shot!
