### ISSUE TITLE
Why are there so many "Checking asset queries" jobs?

### ISSUE THREAD

**Issue by twosixcode** [putyourlightson/craft-blitz#596]
Craft Pro 4.5.6.1
Blitz 4.5.5

For more than three weeks now, since updating to Craft 4, our site has had large amounts of Asset related Blitz jobs in the queue. No one is making changes to any Assets, content edits in the CMS are generally fairly light (a few Entries per day, here or there).

At times the jobs build up to over 100K jobs, with each job having 3K asset queries to check. This was not previously an issue on the Craft 3 site.
<img width="512" alt="Screenshot 2023-12-19 at 12 38 14" src="https://github.com/putyourlightson/craft-blitz/assets/498260/b9f937eb-0125-418c-a042-79d5efa17d25">

Did something change related to Asset queries? Any idea what might be causing this? Is there something we can do to prevent the queue being filled with so many Asset related Blitz jobs?

**Comment by bencroker** [comment]
As of Blitz 4.5.0, the cache refresh process is triggered when an asset’s file is replaced or its filename is changed. Could that be related to what you’re seeing? Are any long-running asset import jobs or asset transform jobs being executed, perhaps?

**Comment by twosixcode** [comment]
The only thing I can think of is that we cleared Asset caches after updating to Craft 4. That's all. No one is working on Assets or running any processes related to asset transforms, file names, or imports.

**Comment by bencroker** [comment]
Something appears to be wrong with your queue runner. Only one queue job should be run at a time. I suggest you cancel all jobs and implement a queue runner allowing at most one concurrent process, see https://putyourlightson.com/articles/queue-runners-and-custom-queues-in-craft-cms for details.

**Comment by twosixcode** [comment]
Thanks, would that really have any effect on the large number of queued jobs, though?

**Comment by bencroker** [comment]
You appear to have upwards of 20 jobs running concurrently, which could suggest that it the same job is being run by multiple processes.

**Comment by twosixcode** [comment]
Thanks, we will certainly look into that. But it sounds like that would be a separate issue from the fact that day after day, loads of new Asset related Blitz jobs are being pushed into the queue. These all look like unique jobs, regardless of how they are processed.

> the cache refresh process is triggered when an asset’s file is replaced or its filename is changed

We're doing neither of these. Do you have any other thoughts on why so many different jobs like this could be pushed into the queue?

<img width="750" alt="Screenshot 2023-12-20 at 11 56 32" src="https://github.com/putyourlightson/craft-blitz/assets/498260/91e9f863-8534-404a-b673-2ede80baf151">

**Comment by twosixcode** [comment]
OK I just found an angle I did not consider that may be re-saving existing Assets (PDF creation triggered via some template code). That looks like it may be the cause and I will confirm here once I sort it out.

**Comment by twosixcode** [comment]
The issue here was caused by unnecessary Asset saves triggered at the template level by a PDF plugin. Thanks for the replies.

**Comment by bencroker** [comment]
Glad to hear you figured it out!
