### ISSUE TITLE
Twig template error on settings page

### ISSUE THREAD

**Issue by davecoggins** [putyourlightson/craft-blitz#60]
Hi,

Installing the plugin I get the following error when visiting the settings page:

Calling unknown method: putyourlightson\blitz\models\SettingsModel::queryStringCachingEnabled()

Cheers
Dave

**Comment by putyourlightson** [comment]
Hi Dave, is this happening with a fresh install or an update? I can't replicate this locally so perhaps uninstalling and reinstalling the plugin in the contol panel will solve it (note that you will lose your saved settings by doing this).

**Comment by davecoggins** [comment]
Thanks for the quick response :)

Was getting the error after doing a fresh reinstall (I had reinstalled because an update migration was erroring out).

I have figured the problem though, it was being caused by craft template cache in admin area.

**Comment by putyourlightson** [comment]
Ah I see, glad to hear you figure it out!
