### ISSUE TITLE
Blitz stuck in a generate/purge loop

### ISSUE THREAD

**Issue by raptureaid** [putyourlightson/craft-blitz#600]
We've been experiencing an issue with Blitz recently where the cache generation/purge tasks become stuck in a loop over an entry (seems to be a different entry each time). The only way we're able to stop this is to "release all jobs" in the queue manager, sometimes this must be done multiple times, but this could also kill other Craft tasks that are queued.

This appears to happen most often when doing a "Refresh Cache" of the entire cache either via the control panel or CLI.

Craft 4.5.14
Blitz 4.9.4

**Comment by bencroker** [comment]
Are multiple queue jobs running (reserved) at the same time, by any chance?

**Comment by raptureaid** [comment]
Tried to grab a screenshot of the queue:
![Screen Shot 2024-01-04 at 1 16 23 PM](https://github.com/putyourlightson/craft-blitz/assets/5720326/20a0f908-45bb-49dd-8541-b69c9783536e)

**Comment by bencroker** [comment]
My first suggestion would be to ensure that only one queue job is running at a time, the reasoning for which I explain in at https://putyourlightson.com/articles/queue-runners-and-custom-queues-in-craft-cms#queue-runners

If that doesn’t solve the issue then let me know and I can help troubleshoot further.

**Comment by bhashkar007** [comment]
I am facing the same issue after updating Craft 3 to Craft 4. The process of "Generating Blitz cache" is stopping after some generating some pages.
Craft CMS v4.6.0
PHP v8.1.26
Blitz plugin v4.10.1

Even, I tried by increasing `memory_limit` to 512M and `max_execution_time` to 240.

![image](https://github.com/putyourlightson/craft-blitz/assets/1473647/c34b1af2-028f-4a1d-bd72-fddf19bdae79)

**Comment by bencroker** [comment]
What queue runner are you using? It could be a memory or timeout issues. Please refer to this article for best practices to use for long-running queue jobs:
https://putyourlightson.com/articles/queue-runners-and-custom-queues-in-craft-cms

**Comment by bhashkar007** [comment]
Thank you @bencroker 

I wouldn't prefer to have any further setup for queue runner. Few more notes please:
- It was working fine with Craft 3. I am facing this problem after Craft 4 upgrade.
- I am facing the same problem if I keep active login in Craft dashboard for hours. The process of "Generating Blitz cache" runs for some pages and then stops and restarts again after few seconds.
- I have already increased PHP `memory_limit` to 512M and `max_execution_time` to 240. 

Please share your further thoughts. Thank you,

**Comment by bencroker** [comment]
It honestly sounds like a queue runner issue to me. You could try increasing `max_execution_time` and the [queueJobTtr](https://github.com/putyourlightson/craft-blitz/blob/8d4e6384fa8cc489cfb4af22a6bd8d12f0b53ca8/src/config.php#L249) config setting to 3000.

What cache generator are you using? You could try the Local Generator if you haven’t already.

**Comment by bhashkar007** [comment]
Thank you @bencroker I tried with Local Generator setting and it worked. Later, I 'll setup for queue runner also. Thank you for your help.

**Comment by bencroker** [comment]
Glad to hear it!
