### ISSUE TITLE
Cache not cleared on zero-downtime setup

### ISSUE THREAD

**Issue by shoored** [putyourlightson/craft-blitz#601]
Hey there,

I'm trying to track down what looks to be an issue due to zero-downtime deployment setup. 
I was wondering if you've come across a setup like this before and might have some pointers?

**Setup**
I've recently moved a site to a new server setup with zero-downtime / atomic deployments.
The caching does work and cached output files are created in the correct cache-folder. 
Also nginx can find those cached HTML files and use them.

But the cached output files don't seem to get removed anymore when changes happen in the CP and Blitz is clearing caches. I can see the queue jobs being fired but the files remain.

The files do get cleared on my local DDEV setup, which is just a regular setup.

The output files get created in the right cache directory, which is something like `/home/ploi/www.domainname.xyz/current/public/cache`

Any idea what I might be missing here?
Could it perhaps be that the old symlink is still "cached" somewhere even though PHP-FPM gets reloaded after a deploy? Just random thoughts ...

**Comment by bencroker** [comment]
It could be a symlink issue. If you’re using the Blitz File Storage driver, which it appears you are, then the cache folder is determined by the value set in the `folder path` field. Can you double check that it is set correctly?

**Comment by shoored** [comment]
Thanks for the quick response Ben. 

`folder path` is set to `@webroot/cache/blitz`.
the `webroot` alias points to `/home/ploi/www.domain.xyz/current/public/`
There are several sites & cache folders in there.

Perhaps I just need to create this cache folder outside of the deployment folders so it's path never changes.

I should mention this site still runs on Craft CMS 3 and Blitz `3.13.0`

**Comment by shoored** [comment]
Hm some additional things.

There's an overview page on the site that lists entries from a section. When I change an image from one of those entries, the overview page cache isn't cleared - the cached file remains. 
When I change the overview page in the CP, same thing.

However, when I clear the overview page cache by going to Blitz Utilities and use the Refresh Caches URL's feature, that cached file is removed correctly.

So Blitz seems to be able find that cached file and remove it. 
It's probably something silly on my end but I'm stuck trying to debug this.

**Comment by shoored** [comment]
Sorry for this live report. Just created a staging environment for this site on a different server with the same type of setup, cache clearing when updating entries in the CP seems to work correct here. Makes it even weirder.

**Comment by shoored** [comment]
Ben, I hope you haven't read all these comments. If so, I'm gonna beer you some beers at the next Craft event. 
Turns out I had issues with a daemon so the cache clearing queue tasks weren't following through. 
Talking about feeling embarrassed ..

**Comment by bencroker** [comment]
I’m just glad you got it resolved!
