### ISSUE TITLE
REGEXP_SUBSTR does not exist; Does 4.10.0 require MySQL 8.0?

### ISSUE THREAD

**Issue by bgrrtt** [putyourlightson/craft-blitz#602]
https://putyourlightson.com/articles/introducing-blitz-diagnostics

We are really excited to use this new utility! But, I am running into this issue on sites still running MySQL 5.7. 

https://dev.mysql.com/blog-archive/new-regular-expression-functions-in-mysql-8-0/

https://putyourlightson.com/plugins/blitz#requirements doesn't include anything regarding MySQL versions.

**Comment by bencroker** [comment]
Hmm, I think you’re right that `REGEXP_SUBSTR` was added in MySQL 8. I’ll look into whether there is an equivalent for 5.7 and let you know what I find.

**Comment by bencroker** [comment]
Fixed in https://github.com/putyourlightson/craft-blitz/commit/c84d677df417b21c896a5d650ce3584961cd5ef7 for the next release, thanks for reporting!

**Comment by bencroker** [comment]
Released in [4.10.1](https://github.com/putyourlightson/craft-blitz/releases/tag/4.10.1).
