### ISSUE TITLE
Pagination goes further than allowed

### ISSUE THREAD

**Issue by ishetnogferre** [putyourlightson/craft-blitz#603]
Please provide a clear and concise description of what the bug is, including:
- Steps to reproduce the issue.
- A clear and concise description of what you expected to happen.
- If applicable, add screenshots to help explain your problem.
- The plugin and Craft version numbers.

Using the new Blitz Diagnostics, I navigated to "xx Tracked Pages", when using the search, I could navigate beyond the allowed pagination, see screenshot below.

<img width="471" alt="Screenshot 2024-01-10 at 15 51 58" src="https://github.com/putyourlightson/craft-blitz/assets/6649706/0b1de646-c26c-472d-8950-8a3e8c021668">

- Craft 4.6.0
- Blitz 4.10.0

**Comment by bencroker** [comment]
Fixed in https://github.com/putyourlightson/craft-blitz/commit/804aba2a4fd048f64cfeb1b33397bf29b3533c86 for the next release, thanks for reporting!

**Comment by bencroker** [comment]
Released in [4.10.1](https://github.com/putyourlightson/craft-blitz/releases/tag/4.10.1).
