### ISSUE TITLE
blitz_includes not cleared when Refresh expired is run

### ISSUE THREAD

**Issue by wolispace** [putyourlightson/craft-blitz#604]
I notice `blitz_includes` table is not being cleared like `blitz_caches` when we run 'Flush Cache' from Utilities / Blitz Cache.

Is this intended behaviour or have we maybe miss-configured our Blitz setup?

Craft 4.6.0
Blitz 4.10.1

The reason I ask is:
With both tables empty and we visit one page, we get 5 records in `blitz_includes`. Visit more pages, make some edits, run 'Refresh Expired Cache' and the number of records in `blitz_includes` keeps increasing (Im guessing this is due to unique params but its hard to tell). At no point have we seen the records in `blitz_includes` reduce.

**Comment by bencroker** [comment]
This is indeed the intended behaviour. The cached includes table will only be emptied after a cache clear. This is to ensure that no cached pages exist that reference deleted cached includes. It should therefore be possible to empty the table by refreshing the entire cache when the refresh mode is set to `REFRESH_MODE_CLEAR_AND_GENERATE` or `REFRESH_MODE_CLEAR`.

https://github.com/putyourlightson/craft-blitz/blob/8d4e6384fa8cc489cfb4af22a6bd8d12f0b53ca8/src/services/FlushCacheService.php#L132-L135

**Comment by wolispace** [comment]
Thanks for that, I didn't expect the 'Refresh mode' would have an impact on the 'Clear cache' or 'Flush cache' commands.

However I must be missing something as I am still seeing the `blitz_includes` table full of data after doing some experiments:

Steps:

- I set the 'Refresh mode' to the first of the 4 available options
- Save 
- I click the Utilities / Blitz Cache / 'Clear cache' button
- See popup confirmation (bottom left) showing success.
- I query the database:

`select 
(select count(*) from blitz_includes) as blitz_includes_count,
(select count(*) from blitz_caches) as blitz_caches_count;`

- I see both tables have > 0 records.

Repeat for the remaining three 'Refresh mode's. 

At no stage does `blitz_includes` get cleared when running 'Clear cache'.

Next I  repeat the process, testing each `Refresh mode' to each of the 4 options
I click the 'Flush cache' button
I run the same query: 

I see `blitz_caches` = 0 records but `blitz_includes` is still > 0 records. 

I then re-ran the 'Clear caches' after 'Flush caches' has cleared `blitz_caches` table, but that still didnt delete anything from `blitz_includes`.

This is our settings file incase it helps. (note we are explicitly setting cacheDuration = 0)

```
use craft\helpers\App;

return [
  '*' => [
    // The time to reserve for queue jobs in seconds.
    'queueJobTtr' => 3600,
    // With this setting enabled, Blitz will log detailed messages to `storage/logs/blitz.log`.
    'debug' => (bool)App::env('DEV_MODE'),
    // With this setting enabled, Blitz will begin caching pages according to the included/excluded URI patterns. Disable this setting to prevent Blitz from caching any new pages.
    'cachingEnabled' => (bool)App::env('BLITZ_ENABLED'),
    // We want this to be 0 for our stale-while-revalidate pattern
    'cacheDuration' => 0,
    // An API key that can be used via a URL (min. 16 characters).
    'apiKey' => App::env('BLITZ_API_KEY'),
    // Whether SSI detection via the control panel should be enabled.
    'detectSsiEnabled' => false,
  ],
  'staging' => [
    // The generator type to use. (staging is not a publicly accessible server so we can't use HTTP generation)
    'cacheGeneratorType' => 'putyourlightson\blitz\drivers\generators\LocalGenerator',
  ],
];
```

I noticed in your code flushAll receives the $afterClear flag, but have not chased through the code to see if its passed through when clicking the 'Flush caches' button.  

```
    /**
     * Flushes the entire cache.
     */
    public function flushAll(bool $afterClear = false): void
```

**Comment by bencroker** [comment]
Sorry if I wasn’t specific enough. You’ll need to refresh the cache using the `Refresh Cache` action in the Blitz Cache utility, or by running the `craft blitz/cache/refresh` console command, which both clears and flushes the cache in one go.

**Comment by wolispace** [comment]
Ah.. Excellent, this works.

This is our data before I switch Refresh mode from: 
'Expire the cache, regenerate manually or organically'
to:
'Clear the cache and regenerate in a queue job'

```MariaDB [db]> select   (select count(*) from blitz_includes) as blitz_includes_count,  (select count(*) from blitz_caches) as blitz_caches_count;
+----------------------+--------------------+
| blitz_includes_count | blitz_caches_count |
+----------------------+--------------------+
|                  684 |               3338 |
+----------------------+--------------------+
1 row in set (0.013 sec)```

And this is after running 'Refresh cache' in Blitz Utility:

```MariaDB [db]> select   (select count(*) from blitz_includes) as blitz_includes_count,  (select count(*) from blitz_caches) as blitz_caches_count;
+----------------------+--------------------+
| blitz_includes_count | blitz_caches_count |
+----------------------+--------------------+
|                   26 |               3307 |
+----------------------+--------------------+
1 row in set (0.004 sec)
```

So does this means we need to switch this setting, run the Refresh cache, then switch back again .. every once in a while.. to keep our tables clean?

Or is there a way of doing this when the Refresh mode is 'Expire the cache, regenerate manually or organically'?

**Comment by bencroker** [comment]
It’s ok if that table grows a bit, as each row represents a cached include that Blitz needs to keep track of. If it increases significantly in size then I’d see if you can track down why. Query params, as you mentioned, might be the issue.
