### ISSUE TITLE
Migration fails when updating from 4.9.4 => 4.10.1

### ISSUE THREAD

**Issue by philipboomy** [putyourlightson/craft-blitz#605]
**For extra info I updated Craft at the same time. 4.5.13 => 4.6.0
Using Postgres**

Database Exception: SQLSTATE[42703]: Undefined column: 7 ERROR: column "elementid" does not exist
LINE 3: INNER JOIN "wd_elements" ON "wd_elements".id = elementId
^
HINT: Perhaps you meant to reference the column "wd_blitz_elementcaches.elementId".
The SQL being executed was: SELECT "type"
FROM "wd_blitz_elementcaches"
INNER JOIN "wd_elements" ON "wd_elements".id = elementId
GROUP BY "type"

Migration: putyourlightson\blitz\migrations\m240110_120000_clear_out_legacy_cached_element_types

Output:

Exception: SQLSTATE[42703]: Undefined column: 7 ERROR: column "elementid" does not exist
LINE 3: INNER JOIN "wd_elements" ON "wd_elements".id = elementId
^
HINT: Perhaps you meant to reference the column "wd_blitz_elementcaches.elementId".
The SQL being executed was: SELECT "type"
FROM "wd_blitz_elementcaches"
INNER JOIN "wd_elements" ON "wd_elements".id = elementId
GROUP BY "type" (/Users/name/Sites/website/vendor/yiisoft/yii2/db/Schema.php:676)
#0 /Users/name/Sites/website/vendor/yiisoft/yii2/db/Command.php(1307): yii\db\Schema->convertException(Object(PDOException), 'SELECT "type"\nF...')
#1 /Users/name/Sites/website/vendor/yiisoft/yii2/db/Command.php(1168): yii\db\Command->internalExecute('SELECT "type"\nF...')
#2 /Users/name/Sites/website/vendor/yiisoft/yii2/db/Command.php(453): yii\db\Command->queryInternal('fetchAll', 7)
#3 /Users/name/Sites/website/vendor/yiisoft/yii2/db/Query.php(320): yii\db\Command->queryColumn()
#4 /Users/name/Sites/website/vendor/putyourlightson/craft-blitz/src/migrations/m240110_120000_clear_out_legacy_cached_element_types.php(23): yii\db\Query->column()
#5 /Users/name/Sites/website/vendor/craftcms/cms/src/db/Migration.php(49): putyourlightson\blitz\migrations\m240110_120000_clear_out_legacy_cached_element_types->safeUp()
#6 /Users/name/Sites/website/vendor/craftcms/cms/src/db/MigrationManager.php(233): craft\db\Migration->up(true)
#7 /Users/name/Sites/website/vendor/craftcms/cms/src/db/MigrationManager.php(149): craft\db\MigrationManager->migrateUp(Object(putyourlightson\blitz\migrations\m240110_120000_clear_out_legacy_cached_element_types))
#8 /Users/name/Sites/website/vendor/craftcms/cms/src/services/Updates.php(252): craft\db\MigrationManager->up()
#9 /Users/name/Sites/website/vendor/craftcms/cms/src/controllers/BaseUpdaterController.php(493): craft\services\Updates->runMigrations(Array)
#10 /Users/name/Sites/website/vendor/craftcms/cms/src/controllers/UpdaterController.php(203): craft\controllers\BaseUpdaterController->runMigrations(Array, 'restore-db')
#11 [internal function]: craft\controllers\UpdaterController->actionMigrate()
#12 /Users/name/Sites/website/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#13 /Users/name/Sites/website/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#14 /Users/name/Sites/website/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('migrate', Array)
#15 /Users/name/Sites/website/vendor/craftcms/cms/src/web/Application.php(305): yii\base\Module->runAction('updater/migrate', Array)
#16 /Users/name/Sites/website/vendor/craftcms/cms/src/web/Application.php(693): craft\web\Application->runAction('updater/migrate')
#17 /Users/name/Sites/website/vendor/craftcms/cms/src/web/Application.php(262): craft\web\Application->_processUpdateLogic(Object(craft\web\Request))
#18 /Users/name/Sites/website/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest(Object(craft\web\Request))
#19 /Users/name/Sites/website/web/index.php(22): yii\base\Application->run()
#20 /Users/name/.composer/vendor/laravel/valet/server.php(110): require('/Users/name/Site...')
#21 {main}

**Comment by bencroker** [comment]
That looks like a Postgres specific error. Thanks for reporting, I'll work on a fix for it.

**Comment by bencroker** [comment]
Fixed in https://github.com/putyourlightson/craft-blitz/commit/8d4e6384fa8cc489cfb4af22a6bd8d12f0b53ca8 for the next release.

**Comment by bencroker** [comment]
Released in [4.10.2](https://github.com/putyourlightson/craft-blitz/releases/tag/4.10.2).
