### ISSUE TITLE
SQL error when accessing diagnostics (tracking element)

### ISSUE THREAD

**Issue by Thijmen** [putyourlightson/craft-blitz#606]
Hi there,

While visiting the following page: `utilities/blitz-diagnostics/elements/element-type?elementType=craft%5Celements%5CAsset&site=default`, I get the following exception:

```
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'craft_content.siteId' in 'where clause'
The SQL being executed was: SELECT COUNT(*)
FROM (SELECT `elementcaches`.`elementId`, count(*) AS `count`, `title`
FROM `craft_blitz_elementcaches` `elementcaches`
INNER JOIN `craft_blitz_caches` ON `elementcaches`.`cacheId` = `craft_blitz_caches`.`id`
INNER JOIN `craft_elements` `elements` ON `elements`.`id` = `elementcaches`.`elementId`
INNER JOIN `craft_content` `content` ON `content`.`elementId` = `elementcaches`.`elementId`
WHERE (`craft_blitz_caches`.`siteId`=1) AND (`craft_content`.`siteId`=1) AND (`type`='craft\\elements\\Asset')
GROUP BY `elementcaches`.`elementId`, `title`
ORDER BY `count` DESC) `c`
```

Craft version: 4.5.13
Blitz version: 4.10.3

I ran the migrations though. 

Is there anything I can do to help? Or is there something wrong on my end?

Best regards,

Thijmen

**Comment by bencroker** [comment]
Apologies, there were hiccups in the 4.10.3 release so it was delayed. Running `composer update` will get you updated to the correct version of 4.10.3 in which this is resolved.

**Comment by Thijmen** [comment]
Awesome, thanks for your efforts Ben! I love the diagnostics utility! Love it! ❤️
