### ISSUE TITLE
Error generating cache via queue

### ISSUE THREAD

**Issue by samuelbirch** [putyourlightson/craft-blitz#608]
I'm getting a "Unable to verify your data submission" (from blitz logs) issue when trying to generate the cache via a queue job. It works if i do it via a console command.

Any ideas why or where to start looking?

**Comment by samuelbirch** [comment]
it appears async queue plugin was the issue here

**Comment by bencroker** [comment]
The Async Queue plugin has caused more than a few issues in the past, which is why I've started recommending against using it. For my recommendations on running queue jobs, see https://putyourlightson.com/articles/queue-runners-and-custom-queues-in-craft-cms
