### ISSUE TITLE
invalid argument error

### ISSUE THREAD

**Issue by umanglemonade** [putyourlightson/craft-blitz#61]
I am trying out plugin in my local WAMP Environment and I am getting below error when I add `*.` as row calue in Included URI Patterns:

`Exception – yii\base\Exception
Failed to create directory "C:\Development\craftsite\public_html\cache\blitz\craftsite.localhost\http:": mkdir(): Invalid argument
↵
Caused by: yii\base\ErrorException 
mkdir(): Invalid argument
in C:\Development\craftsite\vendor\yiisoft\yii2\helpers\BaseFileHelper.php at line 624`

I think it's because it's crying to create folder with "http:" which does not look correct.

Please let me know if I am missing anything.

**Comment by putyourlightson** [comment]
The pattern you should be using is `.*` (rather than `*.`). 

Is your site’s base URL an absolute URL starting with `http://`?

**Comment by umanglemonade** [comment]
I have changed pattern to `.*` but still getting same error.
URL is `http://craftsite.localhost/`

Still getting same error.

**Comment by putyourlightson** [comment]
Ok, we'll look into it and let you know what we find.

**Comment by putyourlightson** [comment]
I'm not able to replicate this. What versions of Blitz and Craft are you using?

**Comment by umanglemonade** [comment]
I am using Craft CMS 3.0.37 with Blitz version 1.11.3.

**Comment by putyourlightson** [comment]
So just to confirm, under "Settings → Sites → Base URL" you have `http://craftsite.localhost/`?

And what is the value in "Settings → Plugins → Blitz → Cache Folder"?

Since I don't have a local WAMP environment to test on, troubleshooting this is proving quite challenging.

**Comment by putyourlightson** [comment]
Any update on whether this is still an issue for you?

**Comment by umanglemonade** [comment]
Hi Ben,

 

Thanks for the follow up. I added http:// in the site URL and it has fixed the issue. Thanks for your help.

 

Thanks

**Comment by putyourlightson** [comment]
Glad to hear it!
