### ISSUE TITLE
Entry query "DESCLIMIT" invalid SQL

### ISSUE THREAD

**Issue by wolispace** [putyourlightson/craft-blitz#611]
On the 'Entry Queries' ie this page:
https://putyourlightson.com/articles/introducing-blitz-diagnostics#tracked-element-queries

When we copy the SQL and paste it, we see a sort order has been added to the query without wrapping it with spaces.. so we end up with in invalid SQL: "DESCLIMIT"

`SELECT `elements`.`id` AS `elementId`FROM (SELECT `elements`.`id` AS `elementsId`, `elements_sites`.`id` AS `elementsSitesId`, `content`.`id` AS `contentId`FROM `elements` `elements`INNER JOIN `entries` `entries` ON `entries`.`id` = `elements`.`id`INNER JOIN `elements_sites` `elements_sites` ON `elements_sites`.`elementId` = `elements`.`id`INNER JOIN `content` `content` ON (`content`.`elementId` = `elements`.`id`) AND (`content`.`siteId` = `elements_sites`.`siteId`)LEFT JOIN `structureelements` `structureelements` ON (`structureelements`.`elementId` = `elements`.`id`) AND (`structureelements`.`structureId`=13)WHERE (`entries`.`sectionId`=4) AND (`elements_sites`.`siteId`=1) AND (`elements`.`archived`=FALSE) AND (`elements`.`dateDeleted` IS NULL) AND (`elements`.`draftId` IS NULL) AND (`elements`.`revisionId` IS NULL)ORDER BY `elements`.`dateUpdated` DESCLIMIT 1) `subquery`INNER JOIN `elements` `elements` ON `elements`.`id` = `subquery`.`elementsId`INNER JOIN `elements_sites` `elements_sites` ON `elements_sites`.`id` = `subquery`.`elementsSitesId`INNER JOIN `entries` `entries` ON `entries`.`id` = `subquery`.`elementsId`INNER JOIN `content` `content` ON `content`.`id` = `subquery`.`contentId`LEFT JOIN `structureelements` `structureelements` ON (`structureelements`.`elementId` = `subquery`.`elementsId`) AND (`structureelements`.`structureId`=13)ORDER BY `elements`.`dateUpdated` DESC;`

Notice there is no space before 'ORDER BY' so its possibly this being added without wrapping in spaces:

"ORDER BY `elements`.`dateUpdated` DESC"

**Comment by bencroker** [comment]
It sounds like perhaps line breaks need to be replaced with spaces before the SQL string is output. Thanks for reporting this, I'll work on a fix for the next release.

**Comment by bencroker** [comment]
Fixed in https://github.com/putyourlightson/craft-blitz/commit/2d8214ca1061b6e11dded483f0bc44c87d044f17 for the next release.

**Comment by bencroker** [comment]
Released in [4.11.0](https://github.com/putyourlightson/craft-blitz/releases/tag/4.11.0).
