### ISSUE TITLE
Generating cache through cmd adds port :80 to all assets

### ISSUE THREAD

**Issue by svondervoort** [putyourlightson/craft-blitz#612]
**Steps to reproduce the issue.**
Unsure since this might be a configuration issue?
- Refresh mode is set to `Expire cache, regenerate manually or organically`.
- Cache Generator set to `Local Generator`.

**A clear and concise description of what you expected to happen.**
- Whenever the cache is generated by visiting the page the asset paths are cached without the `:80` between the domain and slug.
- Whenever the cache is generated by cmd (`craft blitz/cache/refresh-expired`) asset paths are cached with `:80`.

**The plugin and Craft version numbers.**
- Craft 4.6.1
- Blitz 4.10.3

**Comment by bencroker** [comment]
Have you explicitly defined the site URL and the filesystem path? Can you show me what values you have given them?

**Comment by svondervoort** [comment]
With `filesystem path` do you mean the Cache Storage? The `Folder path` is set to `@webroot/cache/blitz` with `Cache Storage` set to `Blitz File Storage`.

In the Cache Generation tab we don't have any `Custom Site URIs` set.

**Comment by bencroker** [comment]
I actually meant the site URL in Craft's site settings, and the URL and path in the filesystem that your asset volume uses, see https://craftcms.com/docs/4.x/assets.html#volumes

**Comment by svondervoort** [comment]
We set the **site_url** with an .env variable called `$PRIMARY_SITE_URL`. It is set to `https://man-nederland.nl/`.
The Filesystem **base url** is set to `@web/uploads` and the **base path** is set to `@webroot/uploads`.

**Comment by bencroker** [comment]
My guess is that the `@web` alias needs to be explicitly defined. See the note in the docs at https://craftcms.com/docs/4.x/sites.html#site-url

**Comment by svondervoort** [comment]
Thanks for pointing that out. We'll give it a go and see if it helps.

**Comment by bencroker** [comment]
Had a chance to test this?

**Comment by svondervoort** [comment]
Sorry, yeah it turned out to be the @web allias that was missing from the general config. Thanks.

**Comment by justenh** [comment]
I believe I'm hitting this same issue. @svondervoort did you solve it be setting the @web alias in `general.php` config to something like this to avoid the issue? 

```php
->aliases([
        '@webroot' => /path/on/server/web,
])
```

**Comment by svondervoort** [comment]
@justenh We use this in the general.php config:
```'@web' => App::env('PRIMARY_SITE_URL'),``` since its already a thing in the .env file anyway.
