### ISSUE TITLE
Major Database Usage

### ISSUE THREAD

**Issue by MacroFabMktg** [putyourlightson/craft-blitz#613]
Shortly after installing the plugin, Blitz seems to be pushing a lot of data in the database.  It's getting to the point where the site will cease.  Here is my system report and a screenshot of the database usage over the last 30 days.   You can see how it grows once I deploy Craft Copy from development to production.

System Report
Application Info
PHP version	8.1.21
OS version	Linux 6.2.0-1012-aws
Database driver & version	MySQL 8.0.33
Image driver & version	Imagick 3.7.0 (ImageMagick 7.1.1-15)
Craft edition & version	Craft Pro 4.7.0
Yii version	2.0.48.1
Twig version	v3.4.3
Guzzle version	7.8.1
Plugins
Blitz	4.10.3
Copy	2.4.4
Feed Me	5.3.0
Field Manager	3.0.8
HOMM XML Sitemap	1.0.3
Mix	1.6.0
PDFThumb	2.0.0
Redirect Manager	2.0.1
Tags	2.0.0

![image](https://github.com/putyourlightson/craft-blitz/assets/118196177/1cb529e7-1676-4a37-aba9-2d553811d6b7)

**Comment by bencroker** [comment]
It sounds like your templates and content may be structured in a way that Blitz needs to track a very large number of elements and element queries. The new Blitz Diagnostics utility should help you identify which pages are tracking the most elements and element queries, and to optimise from there. See https://putyourlightson.com/articles/introducing-blitz-diagnostics 

The Blitz Hints utility will help you identify opportunities for eager-loading, which will also help reduce the number of tracked queries.

**Comment by bencroker** [comment]
Did you discover anything useful, @MacroFabMktg?

**Comment by MacroFabMktg** [comment]
Ben, I decided to NOT cache query strings (we use them for tags on our blogs, podcasts and downloadables).  That seems to have reduced the issue for now.  I'm also going through and ensuring that we lazy load our queries.  In addition, I'll use the diagnostics to further troubleshoot.  I'll let you know how it goes.

**Comment by bencroker** [comment]
Sounds good, closing this issue for now.
