### ISSUE TITLE
Refreshing Blitz Cache Runs and Locks Up Site

### ISSUE THREAD

**Issue by adrianjean** [putyourlightson/craft-blitz#614]
I have noticed lately on my Blitz sites that when I log into them it triggers a Blitz cache refresh, which locks up the site until the task is either completed (which takes a while, even on simple sites), or I nuke the task in the queue.

Is there a way to control when the caches are refreshed? Right now I have a cron job that runs the CraftCMS queue at night and I have disabled automatic queue running in general.php `->runQueueAutomatically(false)` — but seems to have no effect.

Craft Pro: 4.6.1
Blitz: 4.10.3
PHP: 8.3.1
MySQL: 8.0.30

**Comment by bencroker** [comment]
Ideally you'd have a daemonised queue runner than runs queue jobs on demand, as explained in https://putyourlightson.com/articles/queue-runners-and-custom-queues-in-craft-cms

Running the queue once per day means that there could be hundreds of jobs queued up by the time the cron job runs, which sounds like it might be the cause of the issue you're seeing.

**Comment by adrianjean** [comment]
My bad, I meant to say the cron job runs every 5 minutes even through the night — but I think it might actually be a CraftCMS queue issue as there are several other tasks running as well, so it's as if the queue resets or something on log in. 

So I submitted a ticket there:  https://github.com/craftcms/cms/issues/14208

**Comment by bencroker** [comment]
Ah, I see. Well, let me know what you end up discovering and I'll keep an eye on that Craft bug report you opened too.

**Comment by adrianjean** [comment]
Seems it was related to me having the Async Queue plugin installed/enabled. Disabling/removing it allowed my cron task to work as intended.  False alarm!

**Comment by adrianjean** [comment]
So It seems that this issue isn't resolved.

**Here's my setup:**

I have one cron job running every 2 minutes.  
`*/2 * * * * /usr/bin/nice -n 10 /usr/bin/php /srv/www/website.com/craft http://website.com/craft queue/run`

I have another cron job to rebuild the Blitz Cache every 2 minutes. Blitz set to expire and rebuild manually (via cron)
`#*/2 * * * * php /srv/www/website.com/craft http://website.com/craft blitz/cache/refresh-expired`

I have this in my `/config/general.php` — `->runQueueAutomatically(false)`

I have the Blitz `Refresh Mode` setting to:
`Expire the cache, regenerate manually or organically`

**What happens**

- Throughout the day, when content is posted to the website, there is no issue. Jobs run and content is posted.

- However over night, when no content is posted on the site, it seems as tho Blitz refresh tasks build up all night — one for every 2 minutes that pass.

- In the morning, when users start posting on the site, this somehow triggers the queue to run (even though it should have been triggered every 2 minutes), and 10,000 - 30,000 queued Blitz tasks begin processing all of a sudden. This causes the DB server lock up with 100% CPU and stop responding.

Not sure if this is a Blitz thing, or a queue issue. I have an email in with Brad @ P&T — but in case it's something you have insight into as well I'm updating this here.

**Comment by bencroker** [comment]
I would not recommend running queue jobs nor the refresh expired command in such short succession, for the reasons I give in in https://putyourlightson.com/articles/queue-runners-and-custom-queues-in-craft-cms

This honestly sounds like a configuration issue with Craft, so let me know what P&T comes back to you with.
