### ISSUE TITLE
Version 3.14.0 still has 3.13.0 in composer.json

### ISSUE THREAD

**Issue by hiasl** [putyourlightson/craft-blitz#618]
### Bug Report

Blitz v3 does not update to 3.14.0 with composer, I guess because version 3.14.0. still has 3.13.0 as version number in composer.json.
 see here: https://github.com/putyourlightson/craft-blitz/blob/3.14.0/composer.json

### Plugin Version

3.14.0

### Craft CMS Version

3

### PHP Version

8

**Comment by hiasl** [comment]
or maybe it updates but it shows 3.13.0 to be installed ... don't know :-)

**Comment by bencroker** [comment]
You’re right, fixed and released in [3.14.0](https://github.com/putyourlightson/craft-blitz/releases/tag/3.14.0).
