### ISSUE TITLE
Allow plugins to add integrations that invalidate cache

### ISSUE THREAD

**Issue by BenParizek** [putyourlightson/craft-blitz#62]
It looks like this topic has been touched on in a couple places: 
- https://github.com/putyourlightson/craft-blitz/issues/8
- https://github.com/putyourlightson/craft-blitz/issues/57

I have a plugin where custom plugin settings may be output in the templates. It appears Blitz attempts to invalidate cache for Elements and Globals but I didn't see a way that we could add support for one of our plugins to also let Blitz know if some other settings have changed.

It would be nice if plugins could add some sort of integration that helped invalidate cache in scenarios where the default cache may not clear.

**Comment by putyourlightson** [comment]
Things have changed a bit in Blitz v2 (currently at version 2.0.0-beta.2), so I'll refer to the new setup here. Blitz generally uses elements to detect changes in site content and therefore which pages to invalidate. If you want to clear the cache based on custom plugin settings, then you'll need to build in the logic yourself to figure out which URIs need to be cleared. You can then pass those directly to the cache driver as follows.
```
Blitz::$plugin->driver->clearCachedUri($siteId, $uri);
```

If you want to clear the entire cache then that would be better done using the invalidate service as follows.
```
Blitz::$plugin->invalidate->clearCache();
```

Does that help you achieve what you need to?

**Comment by BenParizek** [comment]
I think this helps me understand the direction I need. I'm not just thinking about a custom plugin but a commercial plugin that others will install perhaps alongside Blitz.

I don't like the idea of hard coding third-party plugin specific actions in a commercial plugin and appreciate keeping those things in a dedicated integration or class. So, I'm thinking I'll just add an Event wherever I need one and create a related Blitz helper class or separate plugin that can be configured to trigger the above on those events.

We can call this resolved.

**Comment by putyourlightson** [comment]
Ok, feel free to let me know if there's any way I can make this process easier for you.
