### ISSUE TITLE
Cache for all pages not generated in queue job but when visiting page

### ISSUE THREAD

**Issue by yannkost** [putyourlightson/craft-blitz#622]
### Bug Report

I realized that on a plesk environment I have one website where the cache will be generated for all pages when using the cache utility, for another, only when visiting the site. Are there any hints why I get following message when enabling debug=true in the blitz cache config? 

```
[2024-02-19 12:50:05] The request was not processed and can be safely retried  (followed by the url, matching a pattern, generated when visited)
```

To mention, a nginx reverse-proxy is in front of the apache behind it.

### Plugin Version

4.11.1

### Craft CMS Version

4.7.1

### PHP Version

8.1.27

**Comment by yannkost** [comment]
As a side note, I see that the website not caching all pages on demand does not display the numbers of the pages under the queue job, but still list all entries to cache once clicking on the job.

**Comment by bencroker** [comment]
I’m not quite following your issue, but can you check which cache generator type you’re using? If it is the Local Generator then you may want to try using the HTTP Generator.

**Comment by yannkost** [comment]
I'm already using the HTTP Generator.

![image](https://github.com/putyourlightson/craft-blitz/assets/25202769/ef380943-82b6-41bd-857d-5c1ac967c060)

Strangely only pages of other sites do not seem to get generated. 
Here is the part where the "number" is missing on one of the sites, if ever that helps. 

![image](https://github.com/putyourlightson/craft-blitz/assets/25202769/e0725525-bb05-4867-86de-6441ed5c8531)

I will try digging in some logs, is there any special option I can activate in the bliz config to get more precise logs?

**Comment by bencroker** [comment]
Does the generating page count show in the Queue Manage utility at `/admin/utilities/queue-manager`?

Enabling the `debug` config setting may log helpful messages about why some pages are not being cached, see https://putyourlightson.com/plugins/blitz#debugging

**Comment by yannkost** [comment]
There have been some entries, yes. I looked in the debug log and I saw following: 
```
[2024-02-21 13:15:11] The request was not processed and can be safely retried [(myURL)/es-mx/aplicaciones/bombas-de-calor?token=aOxv69ovK62KEosei34wZ-lj4NMjXELN]
[2024-02-21 13:15:11] The request was not processed and can be safely retried [(myURL)/es-mx/aplicaciones/hvac?token=aOxv69ovK62KEosei34wZ-lj4NMjXELN]
[2024-02-21 13:15:11] The request was not processed and can be safely retried [(myURL)/es-mx/aplicaciones/industrial-food?token=aOxv69ovK62KEosei34wZ-lj4NMjXELN]
[2024-02-21 13:15:11] The request was not processed and can be safely retried [(myURL)/es-mx/aplicaciones/refrigeracion-comercial?token=aOxv69ovK62KEosei34wZ-lj4NMjXELN]
[2024-02-21 13:15:11] The request was not processed and can be safely retried [(myURL)/es-mx/aplicaciones/refrigeracion-de-ti?token=aOxv69ovK62KEosei34wZ-lj4NMjXELN]
```

Do you know where there "token" query parameters come from? It does show a blank page with this token.

**Comment by bencroker** [comment]
The token is likely being used for cache generation. You can confirm this by checking the `route` value for the associated `token` column in the `tokens` database table.

I’m not sure what the problem is, though. Can you please explain it to me in clearer terms?

**Comment by yannkost** [comment]
To resume: 

The cache generation works when: 
- visiting the page (second visit is instant, we love it!)
- saving the entry (when already generated)

The cache generation works NOT when: 
- Using the cach utils "generate all pages"

I saw that craft returns a "blank page" as soon as the url with the token in the blitz log is called. When I remove the ?token from the url, the page is returned normally.

So something with this url and the token makes craft-cms return absolutly nothing.

The setup: 
The craft-cms is running on apache, behind a nginx reverse-proxy.

**Comment by bencroker** [comment]
> Strangely only pages of other sites do not seem to get generated.

Can you explain what you mean by “only pages of other sites”? When is it working and when is it not?

**Comment by yannkost** [comment]
This was only in reference to the image just above. 

![image](https://github.com/putyourlightson/craft-blitz/assets/25202769/4e365f69-fe3f-4c2e-971b-57e93173b272)

In this image, the other site aside Global had almost no pages cached.

The cache generation works when:

- visiting the page (second visit is instant, we love it!)
- saving the entry (when already generated)
- 
The cache generation works NOT when:
- Using the cach utils "generate all pages"

**Comment by bencroker** [comment]
I’m not sure, but Blitz [4.12.0](https://github.com/putyourlightson/craft-blitz/releases/tag/4.12.0) might fix this issue for you, if it is related to https://github.com/putyourlightson/craft-blitz/issues/624. Can you try updating to 4.12.1 and test, after clearing _and_ flushing cache?

**Comment by bencroker** [comment]
Also, note that Blitz can only generate pages that it knows about. If you look in the Blitz Diagnostics tool then you’ll see what pages Blitz is tracking per site, at any point in time.

**Comment by HBunnick** [comment]
Having the same Problem with Blitz Version 4.12.2

I'm using this Settings:
```
'debug' => true,
'refreshMode' => 3,
'cacheStorageType' => 'putyourlightson\blitz\drivers\storage\FileStorage',
'cacheGeneratorType' => 'putyourlightson\blitz\drivers\generators\HttpGenerator',
```

Craft 4 is setup in a docker containerized environment.
The filesystem cache folder is writable and gets populated when visiting the sites organically.

When running
```
craft blitz/cache/generate
```
every found site yields the following error:
```
[console.ERROR] [blitz] The request was not processed and can be safely retried ...
```

**Comment by bencroker** [comment]
@HBunnick have you tested it using the Local Generator?

**Comment by HBunnick** [comment]
Yes LocalGenerator works, but generates Urls pointing to the internal docker domains like cms:80,
which make the output html kinda useless.

Another noteworthy info is,
that the plugin works as expected when the complete docker compose stack is deployed, which leads me to believe that this may be related to the local dev environment.

If i get more insights, i will keep you updated.

**Comment by bencroker** [comment]
The URLs should be generated using the site’s base URL, so make sure that the `@web` alias is explicitly defined if used in the base URL.

I’m marking this issue closed, as it appears to be a configuration/devops issue.
