### ISSUE TITLE
Archiving a multi-site completely with Blitz, including uninstalling Craft

### ISSUE THREAD

**Issue by jannisborgers** [putyourlightson/craft-blitz#626]
### Support Request

For an old multi-site installation, I’m looking for a way to archive the whole installation’s frontend as static HTML, after which I’d like to uninstall Craft completely. 

The client won’t make any content changes anymore, but the sites need to stay online. This is Craft 3 and hosting restrictions prevent us from installing PHP 8. Because Craft 3 reaches end-of-life in April, we need to find a way to publish the content without a CMS in the background going forward.

We already use Blitz with server rewrites and warm the cache manually. My idea is to copy the content of the `cache/blitz` folder and make it the web root(s), then move the asset volume folders to that new web root.

Would that make it a static archive of the sites that does not rely on CraftCMS anymore?

There are some dependencies on Craft’s GraphQL API, as well as an AJAX search form, which I would have to remove or make static separately for them to work without requesting from the backend. Other than that, it’s simply a couple of hundred pages of content.

### Plugin Version

3.11.1

**Comment by bencroker** [comment]
In theory, that should work. You’ll need to ensure that Blitz has cached _every_ page of the site, and making a full backup of the Craft site before making the switch would be a good precautionary step. 

Good luck!
