### ISSUE TITLE
Template with (seemingly) untracked element query

### ISSUE THREAD

**Issue by deeekay** [putyourlightson/craft-blitz#627]
### Support Request

Hey there

I have a website with a blog overview that is grouped by year.

```twig
[...]

{% paginate craft.entries({
            section: 'blogs',
            postDate: ['and', '>=' ~ yearSelectorStart, '<=' ~ yearSelectorEnd],
            limit: 10
        }).with(['blogCategories', 'articleImage', 'genericContentPage', 'teaserImage']).relatedTo(selectedCat).orderBy('postDate desc') as pageInfo, pageEntries %}

[...]
```

Now, if I adjust (for example) the title of a specific blog article, I would expect blitz to refresh the cache of two pages (the detail page of the article and the overview as stated above). In reality, however, only the blog detail page is refreshed, the overview page will stay as it was.

I was checking the documentation and was also trying with the following line:

```twig
{% do craft.blitz.options.paginate(pageInfo.totalPages) %}
```

which did not work.

Do you see any reason why the blog overview page is not tracked?

Thanks in advance for your help and best regards,
Daniel

### Plugin Version

4.11.2

**Comment by bencroker** [comment]
It should work. If you open _Blitz Diagnostics Utility → Tracked Pages → The page in question’s elements_, you should be able to see all of the elements that are tracked by the page. Can you identify whether the blog overview page tracks the blog entry you modified?

**Comment by deeekay** [comment]
Thanks for the prompt response @bencroker 

As a matter of fact, it seems that no elements are tracked on this page (neither are any element queries).

**Comment by bencroker** [comment]
In that case, the `trackElements` (or the deprecated `cacheElements`) config setting must be set to `false`. If you want Blitz to track keep track of which elements are used on each page, you’ll need to ensure it is set to `true`.
https://github.com/putyourlightson/craft-blitz/blob/9fd700154ac6ffb95fa77671e8ac646b3fa95966/src/config.php#L197-L198

**Comment by deeekay** [comment]
I double-checked that, and even explicitly setting it to true in the template did not help🤔

**Comment by bencroker** [comment]
Can you show me your Blitz config settings and the Blitz settings in `config/project/project.yaml‘, excluding the license key and any other sensitive data?

**Comment by deeekay** [comment]
Sure thing

Blitz config (_blitz.php_):
`
return [
    '*' => [
        'debug' => false,
        'hintsEnabled' => true,
    ],
];
`

_project.yaml_:
blitz:
    edition: standard
    enabled: true
    licenseKey: ****
    schemaVersion: 4.11.1
    settings:
      apiKey: ''
      cacheControlHeader: 'public, s-maxage=31536000, max-age=0'
      cacheControlHeaderExpired: 'public, s-maxage=5, max-age=0'
      cacheDuration: null
      cacheElementQueries: true
      cacheElements: true
      cacheGeneratorSettings:
        __assoc__:
          -
            - concurrency
            - '3'
      cacheGeneratorType: putyourlightson\blitz\drivers\generators\HttpGenerator
      cacheNonHtmlResponses: false
      cachePurgerType: putyourlightson\blitz\drivers\purgers\DummyPurger
      cacheStorageSettings:
        __assoc__:
          -
            - folderPath
            - '@webroot/cache/blitz'
          -
            - compressCachedValues
            - ''
      cacheStorageType: putyourlightson\blitz\drivers\storage\FileStorage
      cachingEnabled: true
      debug: false
      defaultCacheControlHeader: 'no-cache, no-store, must-revalidate'
      deployerType: putyourlightson\blitz\drivers\deployers\DummyDeployer
      detectSsiEnabled: true
      driverJobPriority: 100
      esiEnabled: false
      excludedQueryStringParams:
        -
          __assoc__:
            -
              - queryStringParam
              - gclid
        -
          __assoc__:
            -
              - queryStringParam
              - fbclid
      excludedUriPatterns:
        -
          __assoc__:
            -
              - uriPattern
              - organizationcard
        -
          __assoc__:
            -
              - uriPattern
              - search
      generatePagesWithQueryStringParams: true
      hintsEnabled: true
      includedQueryStringParams:
        -
          __assoc__:
            -
              - queryStringParam
              - '.*'
      includedUriPatterns:
        6:
          __assoc__:
            -
              - uriPattern
              - '/insights/editorial/blog.*'
      injectScriptEvent: DOMContentLoaded
      integrations:
        - putyourlightson\blitz\drivers\integrations\SeomaticIntegration
      maxRetryAttempts: 10
      maxUriLength: 255
      mutexTimeout: 1
      outputComments: true
      purgeAssetImagesWhenChanged: true
      queryStringCaching: 0
      queueJobTtr: 300
      refreshCacheAutomaticallyForGlobals: true
      refreshCacheJobPriority: 10
      refreshCacheWhenElementMovedInStructure: true
      refreshCacheWhenElementSavedNotLive: false
      refreshCacheWhenElementSavedUnchanged: false
      refreshMode: 3
      sendPoweredByHeader: false
      ssiEnabled: false
      ssiTagFormat: ''
      trackElementQueries: false
      trackElements: false



Hmm...while checking on the project.yaml I see that trackElementQueries and trackElements are set to false (I haven't seen - or found a way to update this - in the project.yaml. Can you see how this could have been missed? According to my knowledge, there is no explicit toggle (or similar) in the settings page of the Blitz plugin - or maybe I missed it?

Best regards,
Daniel

**Comment by bencroker** [comment]
They are indeed set to `false`. Someone must have set them to `false` via the config settings and never set them back to `true`, and some time in between the settings were saved to project config.

**Comment by deeekay** [comment]
Thanks for the analysis on this 👍🏼 I realized that a change in the config setting will update the project config at some point. Since this is not inherently transparent behaviour I was wondering whether it is on purpose and/or if it is going to change in the future - so that, for example, there may be a dedicated toggle to set these settings in the CP itself?

**Comment by bencroker** [comment]
This is Craft behaviour. You can replicate it by changing a config setting and then saving the plugin settings in the CP. When you do that, Craft will save it to project config. 

There are no plans to make the config settings appear in the CP, but a future version of Blitz is planned in which these settings can be configured differently, at which point I'll be revisiting the plugin settings page in the CP.
