### ISSUE TITLE
Check if a dispatcher actually exists before setting its targets

### ISSUE THREAD

**Issue by boboldehampsink** [putyourlightson/craft-blitz#628]
### Bug Report

See https://github.com/verbb/verbb-base/pull/1 and https://github.com/digitalpulsebe/craft-multi-translator/issues/3, same issue. Also applies to Snaptcha btw.

### Plugin Version

4.12

### Craft CMS Version

4.8.0

### PHP Version

8.3.0

**Comment by bencroker** [comment]
Thanks. Fixed in https://github.com/putyourlightson/craft-blitz/commit/c14c519370544859608df7dd8ba46b5c86fc3145 and https://github.com/putyourlightson/craft-snaptcha/commit/7c5beb56221c11e2154ef5b9b70e6d301dcabe3d.

**Comment by bencroker** [comment]
Released in [4.12.2](https://github.com/putyourlightson/craft-blitz/releases/tag/4.12.2).
