### ISSUE TITLE
Add support for refreshing cache with a post-deploy hook

### ISSUE THREAD

**Issue by BenParizek** [putyourlightson/craft-blitz#63]
We use file revving to cache bust front-end resources. As I currently understand it, this requires that we also need to manually clear or re-warm the cache when we deploy updates to front-end resources.

This can be done with console commands however some servers don't allow those commands to be run. It would be nice to be able to ping a URL to trigger this behavior as well. We implemented this with a custom module on an existing project as it doesn't appear the current controllers allowAnonymous for the cache clearing methods.

In doing so, we also discovered that some services, like Beanstalk, send POST requests to the server for their post-deploy hooks. Craft expects all POST requests to provide CSRF tokens so an exclusion may be necessary to ping the site for a cache refresh.

Or, am I complicating this?  Is there some other way to do what I'm after?

**Comment by putyourlightson** [comment]
I've added controllers that bypass the CSRF token using an API key in other plugins, however I was hoping to avoid it here in place of the console commands which are more reliable (no memory limits or timeouts). Ideally, you would achieve this by using [command events](https://getcomposer.org/doc/articles/scripts.md#command-events) in composer.

Adding this to your `composer.json` will clear the Blitz cache on `composer update` or `composer install`.
```
"scripts": {
    "post-update-cmd": [
        "./craft blitz/cache/clear"
    ],
    "post-install-cmd": [
        "./craft blitz/cache/clear"
    ]
}
```

To re-warm the entire cache use:
```
./craft blitz/cache/warm
```

Or to to clear all Craft caches (requires Craft CMS 3.0.37 or later):
```
./craft clear-caches/all
```

<img width="857" alt="screenshot 2019-01-20 at 10 49 22" src="https://user-images.githubusercontent.com/2318222/51437625-12121c80-1ca1-11e9-93d6-47db97d19204.png">

Source: https://twitter.com/nystudio107/status/1085911878298148866

Would this work in your case?

**Comment by BenParizek** [comment]
In my situation, I simply can't run composer or console commands on the server due to the security model.

I can see where memory limits and timeouts could make this other direction a bit trickier. You do allow us to set concurrency when warming the cache. I'd understand if certain settings had to be low to avoid memory limits. Maybe there are other steps that are harder to have limits for. Or maybe make it a setting that needs to be enabled so people are more likely to see the disclaimers.

We can work around this with our own custom controller in a module, it just seemed that if this was a scenario that others ran into as well it'd be nice to just have it included. I'll understand if you think it'll bring on more support trouble than it's worth.

**Comment by putyourlightson** [comment]
Ok I see. I'm prepared to add access to the controller with an API key and will add this to the list for the next beta release.

**Comment by putyourlightson** [comment]
Added in 2.0.0-beta.3 https://github.com/putyourlightson/craft-blitz/commit/6e73d552ad964423c31571b8cc7b325605dcd2d1.

<img width="792" alt="screenshot 2019-01-20 at 15 55 57" src="https://user-images.githubusercontent.com/2318222/51440883-e6585c00-1ccb-11e9-91b4-07e7971aaa97.png">

**Comment by putyourlightson** [comment]
Note that the requests should be `GET` requests, is this possible in Beanstalk?

**Comment by putyourlightson** [comment]
Just read up on the Beanstalk docs and seems it must be a `POST` request, so I made this possible in 2.0.0-beta.3.1 https://github.com/putyourlightson/craft-blitz/commit/ae2d9bdc57c3d43e0c198b1dd13b59fee2b8ae08.
