### ISSUE TITLE
Too many duplicate entries in "blitz_elementfieldcaches" table.

### ISSUE THREAD

**Issue by simajkeee** [putyourlightson/craft-blitz#630]
### Bug Report

Hey craft-blitz team!

In "blitz_elementfieldcaches" table, multiple cacheId's are stored for the same elementId and fieldId. The main issue is that the table is growing very fast (currently, it contains 30+ million rows.) Please take a look at the screenshot.
![Screenshot (55)](https://github.com/putyourlightson/craft-blitz/assets/37087698/2d5784cf-7df3-44be-9b74-236f6a23279a)
Is it a normal behaviour or a bug? 
Today we've updated from 4.10.3 to 4.12.2 version. Would the update to 4.12.2 address this issue?
Is there any way to elimenate duplicates? If not, can these entries be removed without causing any issues with the plugin's functionality?

### Plugin Version

4.10.3

### Craft CMS Version

4.7.1

### PHP Version

8.2.13

**Comment by bencroker** [comment]
This is not normal behaviour. Duplicates shouldn’t be allowed, since the primary key is the unique combination of `cacheId, elementId, fieldId`. Can you check whether this primary key is in place? If not, then perhaps the plugin installation migration was not successfully completed and it may be worth reinstalling the plugin.

```sql
SHOW INDEXES FROM blitz_elementfieldcaches WHERE key_name = "PRIMARY";
```

![CleanShot 2024-03-07 at 07 22 18@2x](https://github.com/putyourlightson/craft-blitz/assets/57572400/30016574-115a-48e9-b0c9-f09f7a6e66a8)

**Comment by simajkeee** [comment]
i can see the same query output.
Could you please answer these: "Is there any way to elimenate duplicates? If not, can these entries be removed without causing any issues with the plugin's functionality?"

**Comment by bencroker** [comment]
Are you sure you have duplicates? I have a feeling your query needs to include `cacheId` in the `GROUP BY` clause to catch duplicate combinations.

```sql
SELECT
	elementId,
	fieldId,
	count(cacheId) AS count
FROM
	blitz_elementfieldcaches
WHERE
	elementId = 12345
GROUP BY
	elementId,
	fieldId,
	cacheId
HAVING
	count > 1
```

**Comment by simajkeee** [comment]
One row can look like this: cacheId = 1, fieldId = 1, elementId = 1.
The second can look like: cacheId = 2, fieldId = 1, elementId = 1.
In the screenshot I've sent you, you can see that there are many rows with different cacheIds but identical elementIds and fieldIds, which seems like excessive duplication, although I am not familiar with all the specifics.

**Comment by bencroker** [comment]
Those are two distinct rows, there’s no duplication here. 30 million rows does sound rather excessive, though. What does the main Blitz diagnostics utility show in terms of tracked items?

**Comment by simajkeee** [comment]
Hey @bencroker, 
![⚙-Blitz-Diagnostics-Armada-Music](https://github.com/putyourlightson/craft-blitz/assets/37087698/96ce3f0d-090a-4b27-b44e-37d2e1b68ea8)

**Comment by bencroker** [comment]
Ok, so you seem to have a large site with a lot of content! There’s not much you can do besides address the recommendations you see in the screenshot above. Is the large number of rows impacting the site, besides growing the database?

**Comment by simajkeee** [comment]
A large database is the main issue. Can we clean the table? Won't it cause any issues with the plugin's operation?

**Comment by bencroker** [comment]
Yes, you can clear, then flush the cache, which will remove all data from the database tables. My advice would be to begin by auditing the tracked pages and query string params, to ensure that there isn’t too much noise in there. Query string params, especially, can sometimes get out of hand, and setting more explicit include patterns can help a lot. Also, getting eager loading in place and following the other other recommendations can all help.
