### ISSUE TITLE
BaseCacheWarmer no longer available, which events can we use ?

### ISSUE THREAD

**Issue by DavidStrada** [putyourlightson/craft-blitz#633]
### Support Request

Hey there, here are our current versions of the system. (thanks in advance).

Craft v. 4.8.0
Blitz 4.12.1

---

Since [cache warmers have been replaced by generators](https://github.com/putyourlightson/craft-blitz/blob/develop/CHANGELOG.md#400---2022-05-04). 

What would be the events we can listen to?  in order to achieve our custom functionality we had in place.  What we were doing before this got removed from plugin: (`BaseCacheWarmer::EVENT_BEFORE_WARM_CACHE` and `BaseCacheWarmer::EVENT_BEFORE_WARM_ALL_CACHE,`).

``` php
Event::on(
	GuzzleWarmer::class,
	BaseCacheWarmer::EVENT_BEFORE_WARM_CACHE,
	function (RefreshCacheEvent $event) {
		$this->handleWarmCache($event);
	}
);
Event::on(
	GuzzleWarmer::class,
	BaseCacheWarmer::EVENT_BEFORE_WARM_ALL_CACHE,
	function (RefreshCacheEvent $event) {
		$this->handleWarmAllCache($event);
	}
);
```

### Plugin Version

Blitz 4.12.1

**Comment by bencroker** [comment]
`BaseCacheWarmer::EVENT_BEFORE_WARM_CACHE` and `BaseCacheWarmer::EVENT_BEFORE_WARM_ALL_CACHE` have been replaced by [`BaseCacheGenerator::EVENT_BEFORE_GENERATE_CACHE`](https://github.com/putyourlightson/craft-blitz/blob/23ab0b92fe510abc87233d8a001b6cc7d2627456/src/drivers/generators/BaseCacheGenerator.php#L52) and [`BaseCacheGenerator::EVENT_BEFORE_GENERATE_ALL_CACHE`](https://github.com/putyourlightson/craft-blitz/blob/23ab0b92fe510abc87233d8a001b6cc7d2627456/src/drivers/generators/BaseCacheGenerator.php#L62) respectively.
