### ISSUE TITLE
"Refreshing Blitz Cache" jobs hang a lot

### ISSUE THREAD

**Issue by boboldehampsink** [putyourlightson/craft-blitz#635]
### Bug Report

There's a lot of "Refreshing Blitz Cache" jobs either not starting at all, and saying "Reserved" @ 0% - or never finishing after reaching 100%. 

I'm using a queue worker to process them async via the CLI.

### Plugin Version

4.13

### Craft CMS Version

4.8

### PHP Version

8.3

**Comment by bencroker** [comment]
Is this something that started happening recently? Can you provide any more details to help me start troubleshooting?

**Comment by boboldehampsink** [comment]
I feel like it started happening after the last updates. I was on 4.12 before and didn't notice it. Here is a screenshot of my current queue:

<img width="791" alt="Screenshot 2024-03-15 at 19 58 35" src="https://github.com/putyourlightson/craft-blitz/assets/378974/b2176494-3029-4eb5-af99-7e11ca7907db">

**Comment by bencroker** [comment]
Why are there so many processes running at once? One refresh cache job should be handled by a single PHP process. I suggest you read the article on queue runners and compare this to your current queue runner setup. One possibility is that these queue jobs are all waiting on a mutex to free up, causing a race condition.
https://putyourlightson.com/articles/queue-runners-and-custom-queues-in-craft-cms

**Comment by boboldehampsink** [comment]
I'm not sure. I do use multiple workers (I'm on Heroku) temporarily, so that if one stalls, others will continue. But I only use 3 workers - and there's more open processes. The workers only run `craft queue/listen`. They move on to the next job tho, at 100%, which is also weird? I think its because they crash, and the worker gets restarted and that moves it to the next job. I do have error reporting via Sentry also, which notifies me in case of a Mutex exception. But I didn't get any.

**Comment by boboldehampsink** [comment]
FWIW, just got this error from Sentry:

```
yii\base\ErrorException: Could not send result to parent; be sure to shutdown the child before ending the parent
  File "/vendor/amphp/parallel/lib/Context/Internal/process-runner.php", line 120, in yii\base\ErrorHandler::handleError
    \trigger_error("Could not send result to parent; be sure to shutdown the child before ending the parent", E_USER_ERROR);
  File "/vendor/craftcms/cms/src/web/ErrorHandler.php", line 79, in craft\web\ErrorHandler::handleError
    return parent::handleError($code, $message, $file, $line);
  File "[internal]", line 0, in trigger_error
  File "/vendor/amphp/parallel/lib/Context/Internal/process-runner.php", line 120, in Amp\Parallel\Context\Internal\{closure}
    \trigger_error("Could not send result to parent; be sure to shutdown the child before ending the parent", E_USER_ERROR);
  File "/vendor/amphp/parallel/lib/Context/Internal/process-runner.php", line 123
    })();
```

`amphp/parallel` is required and used by Blitz, right?

The latest 2.x releases of that package have descriptions like "Fixed hang during shutdown"(https://github.com/amphp/parallel/releases). Maybe its in this package?

Is there a reason not to update to 2.x btw? You're on 1.4. I'm assuming it is because of the PHP 8.1 requirement. But since last november, 8.0 is fully end-of-life, so that could be dropped.

**Comment by bencroker** [comment]
Your screenshot shows 8 reserved queue jobs, which would concern me. Keep in mind, too, that both the HTTP and local generators create their own child processes with a default concurrency of `3`.

Yes, `amphp/parallel` 1.x is required. Blitz 4 works with Craft 4.0 and above, which requires PHP 8.0.2 and above, meaning that it’s not trivial to update AMPHP due to breaking changes. Blitz 5.0 requires PHP 8.2 and `amphp/parallel` 2.x.

With the `debug` setting enabled, these errors should be logged to `blitz-****.log`. 

While AMPHP is a great library, I will concede that it has been challenging to work with due to the foreign concepts and light documentation.

**Comment by boboldehampsink** [comment]
I would like to try Blitz 5, is it compatible with Craft 4?

**Comment by bencroker** [comment]
No, Blitz 5 requires Craft 5. Also, the AMPHP error you‘re seeing is a cache generation error, nothing to do with refresh cache jobs. I’m working on batched driver jobs, which will include generate cache jobs, in https://github.com/putyourlightson/craft-blitz/tree/feature/batch-driver-jobs, which you‘re welcome to test by running `ddev composer require "putyourlightson/craft-blitz:dev-feature/batch-driver-jobs as 4.14.0"`.

**Comment by boboldehampsink** [comment]
Will try that, thanks. Was wondering about Blitz 5 being compatible for Craft 4, as P&T have lots of their plugins updated to support both versions simultaneously - but hey, if there's anything Craft 5 specific I get it ;-)

**Comment by bencroker** [comment]
It’s mainly got to do with the PHP requirement version bump from 8.0.2 to 8.2, and the dependencies that come along with that. Craft 5 also has some new concepts such as matrix-in-matrix, that are not backwards compatible with Craft 4. 

Like I said above though, this issue has nothing to do with AMPHP. It would be worth looking into why Blitz is tracking _so many_ unique product variant queries (you can find them in the Blitz Diagnostics utility). If you could bring that number from over two thousand down to double digits, than that would likely make a big difference.

**Comment by bencroker** [comment]
FYI I’ve pulled all changes in to the `develop` branch, so you can test by running `ddev composer require "putyourlightson/craft-blitz:dev-develop as 4.14.0"`.

**Comment by boboldehampsink** [comment]
@bencroker when running your latest develop, weird thing are happening to my site. After generating cache, my assets get served with a port number on the host (which is wrong as well, as Heroku uses SSL):

<img width="400" alt="Screenshot 2024-03-17 at 19 23 09" src="https://github.com/putyourlightson/craft-blitz/assets/378974/43184369-e8a8-4533-9055-cf77d1dfdad9">
<img width="975" alt="Screenshot 2024-03-17 at 19 23 14" src="https://github.com/putyourlightson/craft-blitz/assets/378974/33175117-41eb-4b92-8e87-7f1cac2ef69b">

Is there anything that can cause this?

**Comment by boboldehampsink** [comment]
fwiw, im using the craft vite plugin, but that hasn't been updated this weekend

**Comment by boboldehampsink** [comment]
I'm also using the local generator - guess it has something to do with that? Only happens after generating cache so

**Comment by boboldehampsink** [comment]
#640 might fix that, didn't test it yet tho - but found that making sense

**Comment by boboldehampsink** [comment]
Tested it and that fixed it. It's a different issue tho. Regarding the original issue - I flushed the blitz database, maybe it got clogged by testing. So far so good

**Comment by bencroker** [comment]
Thanks, I'll take a look and merge later today.

**Comment by bencroker** [comment]
Merged, thank you! 

Regarding the original issue, try to ensure at most one queue job is executed at a time, and hopefully the next release will address any remaining issues for you. Thanks again for the contributions!

**Comment by boboldehampsink** [comment]
Hi @bencroker - this is still happening a lot. I have to frequently clear the database for it to work:

<img width="778" alt="Screenshot 2024-07-15 at 13 45 28" src="https://github.com/user-attachments/assets/3021c519-a9ce-4702-ad1d-2f5a36c3bd50">

**Comment by bencroker** [comment]
Are you running the latest version 4.19.0? It looks like, as before, multiple queue jobs are being simultaneously reserved, which can cause issues. You should be able to prevent that using a daemon with at most 1 concurrent process to run the queue.

**Comment by boboldehampsink** [comment]
This is on 4.19.0 - yes. The way my site is set up is that it sometimes uses multiple workers to run the queue. Just running 1 is not an option. Is there something that can be done on your side? I.e. use a mutex or something?

**Comment by bencroker** [comment]
This appears to be an issue with Craft so I’m not sure if and how it could be addressed by Blitz. Here’s one possible explanation with a solution that could be informative for your specific setup: 
https://craftcms.stackexchange.com/questions/41252/craft-loses-contact-with-database-and-stops-daemon/41261

**Comment by boboldehampsink** [comment]
@bencroker that is specifically for supervisord/deamon implementations. We don't use that - we just fire up workers (nodes) that run `queue/listen`.

The use case for this is, when you have a webshop for example and it needs to mail/send order mails/calls to the client/api it now has to wait until a cache job is done, which could take some time. That's why we have multiple workers, so on one hand we are updating the cache and on the other we continue with that kind of stuff.

**Comment by bencroker** [comment]
If that’s your use-case then I suggest you use a custom queue for Blitz (and possibly one for your API calls). See https://putyourlightson.com/articles/queue-runners-and-custom-queues-in-craft-cms#configuring-custom-queues for more details.

**Comment by boboldehampsink** [comment]
@bencroker thanks, will look into that
