### ISSUE TITLE
Make position of inject script configurable

### ISSUE THREAD

**Issue by boboldehampsink** [putyourlightson/craft-blitz#636]
### Feature Request

The inject script is now always injected at the end of the body. But when using Turbo Drive for example, and listening to the `turbo:load` event, this scripts gets added multiple times because the body is re-evaluated - and thus multiple requests are made when browsing around (and keeps getting worse). I'd rather see this script in the `head` section. Would be nice if it could be configured.

### Plugin Version

4.13

**Comment by bencroker** [comment]
Thanks! Added in https://github.com/putyourlightson/craft-blitz/pull/637 and https://github.com/putyourlightson/craft-blitz/commit/03ae6e52f132e10ab35bc51ed64c2939edfc81df, for the next release.

**Comment by bencroker** [comment]
Released in [4.14.0](https://github.com/putyourlightson/craft-blitz/releases/tag/4.14.0).
