### ISSUE TITLE
Twig Runtime error when viewing Tracked Pages > Element Type instance.

### ISSUE THREAD

**Issue by MattWilcox** [putyourlightson/craft-blitz#645]
### Bug Report

Going to Blitz Diagnostics > Tracked Pages > Page and then clicking on the top link breaks.

<img width="926" alt="Screenshot 2024-03-22 at 17 14 39" src="https://github.com/putyourlightson/craft-blitz/assets/814039/f31cff55-ebbd-4f02-bc24-1e5ab3d17b1b">

leads to

<img width="1280" alt="Screenshot 2024-03-22 at 17 14 23" src="https://github.com/putyourlightson/craft-blitz/assets/814039/399eb3b2-9939-45a2-88fe-cc04cc3c851d">

### Plugin Version

5.0.0.beta3

### Craft CMS Version

5.0.beta-10

### PHP Version

8.2

**Comment by bencroker** [comment]
Thanks! Fixed in https://github.com/putyourlightson/craft-blitz/commit/3fed3d2d7007f102b9bb5d73a6f3e79e10ae0bce for the next release.

**Comment by bencroker** [comment]
Released in [4.14.1](https://github.com/putyourlightson/craft-blitz/releases/tag/4.14.1) and [5.0.0-beta.4](https://github.com/putyourlightson/craft-blitz/releases/tag/5.0.0-beta.4).
