### ISSUE TITLE
x-craft-preview prevents 'afterBlitzInjectAll' event completion

### ISSUE THREAD

**Issue by jon-collette** [putyourlightson/craft-blitz#655]
### Bug Report

Noticed this bug recently. When previewing a page from the editor either using:

- The "Preview" button from the Entry editor that slides out a live preview
- The "View" button from the Entry editor that opens a new window that results in a URL like https://example.com/test-page?x-craft-preview=SOnlWnmOyY&token=8F1Ni7MR52AhCYJN0G1iPfNUa5-CIRMy

The `{{ craft.blitz.includeDynamic('[templateUrl]') }}` call will still inject the dynamic content without the usual blitz wrapper `<span id="blitz-inject-4" class="blitz-inject blitz-inject--injected" data-blitz-id="4" data-blitz-uri="/_dynamic" data-blitz-params="action=blitz%2Finclude%2Fdynamic&amp;index=3233167847" data-blitz-property="">[inject results]</span>` but the JS event won't fire.

We have this JS event listener that waits for the injects to be complete that doesn't fire as a result:

`document.addEventListener('afterBlitzInjectAll', function (event) {
  initialize();
});`

I can manually fire the event using `document.dispatchEvent(new CustomEvent('afterBlitzInjectAll'));`. No errors report in live or previews.

This bug looks like it's a result from including `?x-craft-preview` in the URL — you can reproduce this bug by just adding the param to any page to stop the `afterBlitzInjectAll` event from firing there. For example: https://example.com/live-page?x-craft-preview the event doesn't fire.

Bug only reproduces when `x-craft-preview` is the exact param: https://example.com/live-page?x-craftt-preview works as intended.

Will update the plugin version to verify.

### Plugin Version

4.14.1

### Craft CMS Version

4.8.7

### PHP Version

8.0.24

**Comment by bencroker** [comment]
I’ve made it so that dynamic includes in preview requests are now also sent via AJAX (passing through the token param) in https://github.com/putyourlightson/craft-blitz/commit/aaa8a8850dd8ba3e5d8c459b349fee8cc6526558. Released in [4.16.2](https://github.com/putyourlightson/craft-blitz/releases/tag/4.16.2). Thanks for the report!
