### ISSUE TITLE
Query string caching per URI pattern

### ISSUE THREAD

**Issue by raptureaid** [putyourlightson/craft-blitz#66]
First, this plugin has been wonderful in improving site speed and performance.

It would be helpful to control the query string caching on specific URI patterns. For instance, ad campaign landing pages that use query strings for tracking purposes would use `Cache URLs with query strings as the same page`, whereas a directory listing that uses pagination would use `Cache URLs with query strings as unique pages`

**Comment by putyourlightson** [comment]
Thanks for the suggestion. I feel like this might overcomplicate the settings UI, which we really want to keep as simple to use as possible. I wonder though, if you avoid using query string parameters in your paginated pages by using Craft's [`{% paginate %}`](https://docs.craftcms.com/v3/dev/tags/paginate.html) tag then won't the listing pages have the form `http://my-project.test/news/p2` and therefore be cached?

**Comment by raptureaid** [comment]
I was thinking an additional column similar to the site selector, but your suggestion to rework the pagination is also valid.

We're also using query strings to dynamically update the results of the paginated list (ex: https://www.lynn.edu/events?category%5B%5D=free#upcoming-events). Would we need to transition this portion of the template to use `{{ craft.blitz.getUri('/template/name') }}`?

**Comment by putyourlightson** [comment]
If you select `Cache URLs with query strings as unique pages` then it should still work. If you select `Cache URLs with query strings as the same page` however then it likely won't. 

We'll look into how involved coupling it to URI patterns is.

**Comment by putyourlightson** [comment]
After some consideration, we've decided that matching the query string setting with URI patterns is not currently feasible. The reason for this is that the server rewrite that is used depends on the value of the setting and would require custom rewrites to make them work together. Thanks again for the suggestion!
