### ISSUE TITLE
Not able to try Blitz in Craft 5

### ISSUE THREAD

**Issue by espensgr** [putyourlightson/craft-blitz#660]
### Bug Report

When i run try install from plugin store i get:
`You need to be on at least Blitz 4.11.1 before you can update to Blitz 5.2.0.`
Screenshot of the error:
![image](https://github.com/putyourlightson/craft-blitz/assets/3862891/9d6d98ee-8b11-4186-b3eb-869612132d35)
Not able to install the 4.11.1 version either, a lot of dependency errors that i cant resolve.

### Diagnostics Report

Craft 5.1.1
Blitz  5.2.0
Php 8.3 from DDEV

**Comment by bencroker** [comment]
Part of the [Craft 5 upgrade process](https://craftcms.com/docs/5.x/upgrade.html) is that:

> The most recent Craft 4-compatible versions of all plugins are installed

See https://craftcms.com/docs/5.x/upgrade.html

Blitz 5 requires that at least 4.11.1 was installed, due to database migrations.

**Comment by espensgr** [comment]
This isn't an upgrade, it's a fresh Craft 5 install.
I have tried to uninstall and reinstall the Blitz plugin too, but to no other outcome.
Could this be a bug in the Craft 5 install prosess then?

We are running the Solo edition, may that have any affect on the plugin?

**Comment by espensgr** [comment]
I tried to uninstall the plugin, den remove from composer, then add to composer, then install again, then it worked.
Maybe som tables in the db wasn't added properly in the install prosess, dont know but fixed now.

**Comment by bencroker** [comment]
Great! It was possibly an issue in the first install attempt.
