### ISSUE TITLE
Possible to have Blitz ignore certain entry sections from "Refreshing Blitz cache"

### ISSUE THREAD

**Issue by adrianjean** [putyourlightson/craft-blitz#662]
### Support Request

I have a content type that is updated quite a bit because I use the [View Count](https://plugins.craftcms.com/view-count) plugin to increment how many times the entry was viewed on the page, which can happen +10 times per user visit.

Every time the View Count field is updated, it triggers a queue job to "Refreshing Blitz cache", inside I can see that the task is related to the View Count field being updated on the entry. For example:

```
{
    "description": null,
    "data": {
        "cacheIds": [],
        "elements": {
            "craft\\elements\\Entry": {
                "elementIds": {
                    "4718": true
                },
                "sourceIds": {
                    "30": true
                },
                "changedFields": {
                    "4718": {
                        "embededItemImpressionCounter": true
                    }
                },
                "isChangedByAttributes": {
                    "4718": false
                },
                "isChangedByFields": {
                    "4718": true
                }
            }
        }
    },
    "forceClear": false,
    "forceGenerate": false
}

```

The section related to this content (which is an embedded item on another page) does not have a public URL, so adding something to the exclude section of Blitz config doesn't seem to have an effect.

Is there a setting to tell Blitz to just completely ignore a list of entry sections all together?

```
My Setup:
- CraftCMS Pro 4.9.1
- Blitz: 4.17.0
- PHP: 8.3.6
- MySQL: 8.0.30
- Apache: 2.4.59 (Ubuntu)
```

### Plugin Version

4.17.0

**Comment by bencroker** [comment]
There isn’t, but you can prevent the cache from being refreshed on save of entries in that section using a custom plugin/module. Here’s some sample code to get you started (replace `1` with the section ID in question).

```php
use craft\elements\Entry;
use putyourlightson\blitz\events\RefreshElementEvent;
use putyourlightson\blitz\services\RefreshCacheService;
use yii\base\Event;

Event::on(RefreshCacheService::class, RefreshCacheService::EVENT_BEFORE_ADD_ELEMENT,
    function(RefreshElementEvent $event) {
        $element = $event->element;
        if ($element instanceof Entry && $element->sectionId === 1) {
            $event->isValid = false;
        }
    }
);
```
