### ISSUE TITLE
Query not tracked when it includes variables

### ISSUE THREAD

**Issue by andrewfairlie** [putyourlightson/craft-blitz#666]
### Bug Report

On Craft 5 I've got this query

```
{# Get the related cards dynamically if taxonomies have been chosen #}
{% set relatedArticleTypes = block.relatedArticleTypes|length ? block.relatedArticleTypes : null %}
{% set relatedTopics = block.relatedTopics|length ? block.relatedTopics : null %}
{% set relatedSubTopics = block.relatedSubTopics|length ? block.relatedSubTopics : null %}

{% set limit = block.showPopular ? (block.highlightFirstCard ? 3 : 2) : block.highlightFirstCard ? 5 : 3 %}
{% set cards = craft.entries()
    .section('article')
    .relatedTo(relatedArticleTypes)
    .andRelatedTo(relatedTopics)
    .andRelatedTo(relatedSubTopics)
    .orderBy('postDate desc')
    .limit(limit) %}
```

Which is pretty dynamic with a bunch of variables.

It appears like the moment there's a variable in the query (eg: this still happens if I remove the relatedTo logic but keep limit, or vice-versa), element query tracking is disabled. Is there a way around this?

### Diagnostics Report

- Craft  5.1.4
- Blitz  5.1.4
- PHP 8.3

**Comment by bencroker** [comment]
What exactly do you mean by “element query tracking is disabled”, that the query is not tracked? Have you tested with passing IDs into `relatedTo` instead of elements?

**Comment by andrewfairlie** [comment]
Thanks for the response.

I will do some more work on this next week and will be sure to report back.

**Comment by bencroker** [comment]
Sounds good. If you can reduce this to the simplest reproducable query in which the issue can be observed then I’ll be able to test and troubleshoot locally.

**Comment by bencroker** [comment]
Any update on this, @andrewfairlie?

**Comment by andrewfairlie** [comment]
Hi @bencroker 

Sorry for the delay. This problem doesn't seem to be happening now. So I think either I was mis-testing it, or something else on the site has changed and fixed it. Sorry for the inconvinience, but thanks for the help.
