### ISSUE TITLE
Cache Sprig components

### ISSUE THREAD

**Issue by andrewfairlie** [putyourlightson/craft-blitz#667]
### Support Request

Is it possible to cache Sprig components to improve their performance?

I mean the ones loaded like

```
index.php?p=actions/sprig-core/components/render&query=&page=2&sprig%3Aconfig=eb9ce109222fb72cf718be545a0dcc92049549ac06a216b29e2aac26c9552505{"siteId"%3A1%2C"template"%3A"_\%2Fcomponents\%2Fsprig-content\%2Farticles"}
```

I have the following included URI patterns enabled
![CleanShot 2024-05-22 at 14 05 16@2x](https://github.com/putyourlightson/craft-blitz/assets/1772888/5393f030-3637-4976-9268-b2f3d7543741)

And the following query string setting

![CleanShot 2024-05-22 at 14 05 42@2x](https://github.com/putyourlightson/craft-blitz/assets/1772888/d77a9973-e31c-4971-85e4-345971c9135e)

And the following nginx config

```
    gzip_static on;
set $cache_path false;
if ($request_method = GET) {
    set $cache_path /cache/blitz/$host/$uri/$args/index.html;
}
if ($args ~ "token=") {
    set $cache_path false;
}

#- Send would-be 404 requests to the cache path or Craft
location / {
    try_files $cache_path $uri $uri/ /index.php?$query_string;
}

```

Ideally these partials would be cachable in the same way other pages are for peak performance.

### Plugin Version

5.3.1

**Comment by bencroker** [comment]
No, Sprig requests are never cached, since they are action requests, but you can cache database queries in the Sprig component using Craft’s native cache tags to help reduce their load time.
