### ISSUE TITLE
Error with properties after updating to v5 createGzipFiles/createBrotliFile

### ISSUE THREAD

**Issue by loqus** [putyourlightson/craft-blitz#668]
### Bug Report

After updating to Craft 5 Pro and updating Blitz to ^5.3 I got a non-functioning dashboard and non functioning blitz plugin page.
It seems to be related to the 2 properties that got removed in v5.0.0 

Setting unknown property: putyourlightson\blitz\drivers\storage\FileStorage::createGzipFiles
Setting unknown property: putyourlightson\blitz\drivers\storage\FileStorage::createBrotliFile

After manually adding the properties from v4 back into the FileStorage everything was functioning again. I don't have these values active in the blitz.php config and I am unsure where they are called from.

### Diagnostics Report

PHP version | 8.2.19
Craft edition & version | Craft Pro 5.1.5
Blitz | 5.3.1

**Comment by bencroker** [comment]
Can you share the “Blitz Plugin Settings” part of the diagnostics report, so I can see what settings you have?

**Comment by loqus** [comment]
Well good news, after uninstalling and re-installing the plugin, the errors above are gone. But now a new one pops up:

I cannot load the generate report page. I cleared the runtime directory. But clicking on the generate diagnostics report gives me a (TypeError(code: 0): get_class(): Argument #1 ($object) must be of type object, string given at /var/www/vhosts/xxx/xxx/storage/runtime/compiled_templates/cd/cdbcdf1d50c468a38bece6c6b7579c04.php:88 (which is the blitz/_utilities/diagnostics/_includes/report template)

Row 88: echo twig_escape_filter($this->env, get_class($context["module"]), "html", null, true);

PS i have the same error on another Craft CMS (different site) running on Craft Pro 4.9.2, Blitz 4.18.0, PHP 8.1.28

**Comment by bencroker** [comment]
That’s good to hear!

Can you please share the entire stack trace of the error so I can track it down? The error appears to be referencing a custom module.

**Comment by bencroker** [comment]
Any update on this, @loqus?

**Comment by loqus** [comment]
This is what I got now

Twig\Error\RuntimeError: Impossible to access an attribute ("id") on a string variable ("modules\Module"). in /var/www/vhosts/example.com/httpdocs/vendor/putyourlightson/craft-blitz/src/templates/_utilities/diagnostics/_includes/report.twig:19
Stack trace:
#0 /var/www/vhosts/example.com/httpdocs/vendor/craftcms/cms/src/helpers/Template.php(141): twig_get_attribute()
#1 /var/www/vhosts/example.com/httpdocs/storage/runtime/compiled_templates/93/9398d210647b70fc0167005b4d55291e.php(86): craft\helpers\Template::attribute()
#2 /var/www/vhosts/example.com/httpdocs/vendor/twig/twig/src/Template.php(394): __TwigTemplate_ace9722dce9fa9f6353fa7ca127362d3->doDisplay()
#3 /var/www/vhosts/example.com/httpdocs/vendor/twig/twig/src/Template.php(367): Twig\Template->displayWithErrorHandling()
#4 /var/www/vhosts/example.com/httpdocs/vendor/twig/twig/src/Template.php(379): Twig\Template->display()
#5 /var/www/vhosts/example.com/httpdocs/vendor/twig/twig/src/TemplateWrapper.php(38): Twig\Template->render()
#6 /var/www/vhosts/example.com/httpdocs/vendor/twig/twig/src/Environment.php(280): Twig\TemplateWrapper->render()
#7 /var/www/vhosts/example.com/httpdocs/vendor/craftcms/cms/src/web/View.php(482): Twig\Environment->render()
#8 /var/www/vhosts/example.com/httpdocs/vendor/putyourlightson/craft-blitz/src/controllers/DiagnosticsController.php(144): craft\web\View->renderTemplate()
#9 /var/www/vhosts/example.com/httpdocs/vendor/putyourlightson/craft-blitz/src/controllers/DiagnosticsController.php(50): putyourlightson\blitz\controllers\DiagnosticsController->getReport()
#10 [internal function]: putyourlightson\blitz\controllers\DiagnosticsController->actionReport()
#11 /var/www/vhosts/example.com/httpdocs/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#12 /var/www/vhosts/example.com/httpdocs/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams()
#13 /var/www/vhosts/example.com/httpdocs/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction()
#14 /var/www/vhosts/example.com/httpdocs/vendor/craftcms/cms/src/web/Application.php(340): yii\base\Module->runAction()
#15 /var/www/vhosts/example.com/httpdocs/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction()
#16 /var/www/vhosts/example.com/httpdocs/vendor/craftcms/cms/src/web/Application.php(308): yii\web\Application->handleRequest()
#17 /var/www/vhosts/example.com/httpdocs/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest()
#18 /var/www/vhosts/example.com/httpdocs/web/index.php(228): yii\base\Application->run()
#19 {main}

**Comment by loqus** [comment]
I'm also getting some blank pages in my cache, is this due to a Craft Pro update?

**Comment by bencroker** [comment]
It’s unclear why `modules\Module` is a string and not a module. Can you please show me the `modules` section in your `config/app.php` file?

**Comment by loqus** [comment]
return [
    'modules' => [
        'my-module' => \modules\Module::class,
    ],
    //'bootstrap' => ['my-module'],
];

**Comment by loqus** [comment]
Might it be the 'my-module' => \modules\Module::class, default module in there? It's never changed since using Craft since v2
OMG, yes it is.

**Comment by bencroker** [comment]
It looks like the module not being bootstrapped was causing the issue. Fixed in https://github.com/putyourlightson/craft-blitz/commit/64af11ee7701bab3d2435323f4577bb91d53737d to only show bootstrapped modules, for the next release. Thanks for helping me figure this out!

**Comment by bencroker** [comment]
Released in [4.18.2](https://github.com/putyourlightson/craft-blitz/releases/tag/4.18.2) and [5.3.2](https://github.com/putyourlightson/craft-blitz/releases/tag/5.3.2).

**Comment by sarahschuetz** [comment]
@bencroker running in the same initial error when updating to Craft 5 and Blitz 5.4 ⚡️
Uninstalling and re-installing fixed the error for me, too.

**Comment by bencroker** [comment]
Thanks @sarahschuetz, https://github.com/putyourlightson/craft-blitz/commit/b2b21384f01eb98c6cd79129a749de06c67d880d should fix that in future.

**Comment by bencroker** [comment]
Released in [5.5.0](https://github.com/putyourlightson/craft-blitz/releases/tag/5.5.0).

**Comment by CentroNia1420** [comment]
Hello, I'm getting this error with an upgrade from Craft 4 to 5. Everything worked fine. When I remove the Blitz plugin, the site works as expected, but as soon as I install Blitz, the front and backend shows this error.

Craft = 5.4.7.1
Blitz = 5.9

-------------
Unknown Property – [yii\base\UnknownPropertyException](https://www.yiiframework.com/doc-2.0/yii-base-unknownpropertyexception.html)
Setting unknown property: putyourlightson\blitz\drivers\storage\FileStorage::createGzipFiles
1. in /var/www/html/vendor/yiisoft/yii2/base/Component.php at line 217
2. in /var/www/html/vendor/craftcms/cms/src/helpers/App.php at line 1479– [yii\base\Component::__set](https://www.yiiframework.com/doc-2.0/yii-base-component.html#__set()-detail)('createGzipFiles', '')
3. in /var/www/html/vendor/craftcms/cms/src/base/Model.php at line 84– craft\helpers\App::configure(putyourlightson\blitz\drivers\storage\FileStorage, ['folderPath' => '@webroot/cache/blitz', 'createGzipFiles' => '', 'createBrotliFiles' => ''])
4. craft\base\Model::__construct(['folderPath' => '@webroot/cache/blitz', 'createGzipFiles' => '', 'createBrotliFiles' => ''])
5. in /var/www/html/vendor/yiisoft/yii2/di/Container.php at line 419– ReflectionClass::newInstanceArgs([['folderPath' => '@webroot/cache/blitz', 'createGzipFiles' => '', 'createBrotliFiles' => '']])
6. in /var/www/html/vendor/yiisoft/yii2/di/Container.php at line 170– [yii\di\Container::build](https://www.yiiframework.com/doc-2.0/yii-di-container.html#build()-detail)('putyourlightson\blitz\drivers\st...', [], ['folderPath' => '@webroot/cache/blitz', 'createGzipFiles' => '', 'createBrotliFiles' => ''])
7. in /var/www/html/vendor/yiisoft/yii2/BaseYii.php at line 365– [yii\di\Container::get](https://www.yiiframework.com/doc-2.0/yii-di-container.html#get()-detail)('putyourlightson\blitz\drivers\st...', [], ['folderPath' => '@webroot/cache/blitz', 'createGzipFiles' => '', 'createBrotliFiles' => ''])
8. in /var/www/html/vendor/yiisoft/yii2/di/ServiceLocator.php at line 137– [yii\BaseYii::createObject](https://www.yiiframework.com/doc-2.0/yii-baseyii.html#createObject()-detail)(['folderPath' => '@webroot/cache/blitz', 'createGzipFiles' => '', 'createBrotliFiles' => ''])
9. in /var/www/html/vendor/yiisoft/yii2/base/Module.php at line 769– [yii\di\ServiceLocator::get](https://www.yiiframework.com/doc-2.0/yii-di-servicelocator.html#get()-detail)('cacheStorage', false)
10. in /var/www/html/vendor/yiisoft/yii2/di/ServiceLocator.php at line 74– [yii\base\Module::get](https://www.yiiframework.com/doc-2.0/yii-base-module.html#get()-detail)('cacheStorage')
11. in /var/www/html/vendor/putyourlightson/craft-blitz/src/services/CacheRequestService.php at line 461– [yii\di\ServiceLocator::__get](https://www.yiiframework.com/doc-2.0/yii-di-servicelocator.html#__get()-detail)('cacheStorage')
12. in /var/www/html/vendor/putyourlightson/craft-blitz/src/Blitz.php at line 328– putyourlightson\blitz\services\CacheRequestService::getCachedResponse(putyourlightson\blitz\models\SiteUriModel)
13. putyourlightson\blitz\Blitz::putyourlightson\blitz\{closure}(yii\base\Event)
14. in /var/www/html/vendor/yiisoft/yii2/base/Event.php at line 312– call_user_func(Closure, yii\base\Event)
15. in /var/www/html/vendor/yiisoft/yii2/base/Component.php at line 650– [yii\base\Event::trigger](https://www.yiiframework.com/doc-2.0/yii-base-event.html#trigger()-detail)('craft\web\Application', 'init', yii\base\Event)
16. in /var/www/html/vendor/craftcms/cms/src/base/ApplicationTrait.php at line 546– [yii\base\Component::trigger](https://www.yiiframework.com/doc-2.0/yii-base-component.html#trigger()-detail)('init', yii\base\Event)
17. in /var/www/html/vendor/craftcms/cms/src/base/ApplicationTrait.php at line 1637– craft\web\Application::trigger('init')
18. in /var/www/html/vendor/craftcms/cms/src/web/Application.php at line 110– craft\web\Application::_postInit()
19. in /var/www/html/vendor/yiisoft/yii2/base/BaseObject.php at line 109– craft\web\Application::init()
20. in /var/www/html/vendor/yiisoft/yii2/base/Application.php at line 204– [yii\base\BaseObject::__construct](https://www.yiiframework.com/doc-2.0/yii-base-baseobject.html#__construct()-detail)(['env' => 'local', 'components' => ['config' => craft\services\Config, 'addresses' => ['class' => 'craft\services\Addresses'], 'announcements' => ['class' => 'craft\services\Announcements'], 'api' => ['class' => 'craft\services\Api'], ...], 'id' => 'CraftCMS--713fe2f0-ec4d-411e-ab4...', 'name' => 'Craft CMS', ...])
21. [yii\base\Application::__construct](https://www.yiiframework.com/doc-2.0/yii-base-application.html#__construct()-detail)(['env' => 'local', 'components' => ['config' => craft\services\Config, 'addresses' => ['class' => 'craft\services\Addresses'], 'announcements' => ['class' => 'craft\services\Announcements'], 'api' => ['class' => 'craft\services\Api'], ...], 'id' => 'CraftCMS--713fe2f0-ec4d-411e-ab4...', 'name' => 'Craft CMS', ...])
22. in /var/www/html/vendor/yiisoft/yii2/di/Container.php at line 419– ReflectionClass::newInstanceArgs([['vendorPath' => '/var/www/html/vendor', 'env' => 'local', 'components' => ['config' => craft\services\Config, 'addresses' => ['class' => 'craft\services\Addresses'], 'announcements' => ['class' => 'craft\services\Announcements'], 'api' => ['class' => 'craft\services\Api'], ...], 'id' => 'CraftCMS--713fe2f0-ec4d-411e-ab4...', ...]])
23. in /var/www/html/vendor/yiisoft/yii2/di/Container.php at line 170– [yii\di\Container::build](https://www.yiiframework.com/doc-2.0/yii-di-container.html#build()-detail)('craft\web\Application', [], ['vendorPath' => '/var/www/html/vendor', 'env' => 'local', 'components' => ['config' => craft\services\Config, 'addresses' => ['class' => 'craft\services\Addresses'], 'announcements' => ['class' => 'craft\services\Announcements'], 'api' => ['class' => 'craft\services\Api'], ...], 'id' => 'CraftCMS--713fe2f0-ec4d-411e-ab4...', ...])
24. in /var/www/html/vendor/yiisoft/yii2/BaseYii.php at line 365– [yii\di\Container::get](https://www.yiiframework.com/doc-2.0/yii-di-container.html#get()-detail)('craft\web\Application', [], ['vendorPath' => '/var/www/html/vendor', 'env' => 'local', 'components' => ['config' => craft\services\Config, 'addresses' => ['class' => 'craft\services\Addresses'], 'announcements' => ['class' => 'craft\services\Announcements'], 'api' => ['class' => 'craft\services\Api'], ...], 'id' => 'CraftCMS--713fe2f0-ec4d-411e-ab4...', ...])
25. in /var/www/html/vendor/craftcms/cms/src/Craft.php at line 70– [yii\BaseYii::createObject](https://www.yiiframework.com/doc-2.0/yii-baseyii.html#createObject()-detail)(['vendorPath' => '/var/www/html/vendor', 'env' => 'local', 'components' => ['config' => craft\services\Config, 'addresses' => ['class' => 'craft\services\Addresses'], 'announcements' => ['class' => 'craft\services\Announcements'], 'api' => ['class' => 'craft\services\Api'], ...], 'id' => 'CraftCMS--713fe2f0-ec4d-411e-ab4...', ...], [])
26. in /var/www/html/vendor/craftcms/cms/bootstrap/bootstrap.php at line 312– Craft::createObject(['vendorPath' => '/var/www/html/vendor', 'env' => 'local', 'components' => ['config' => craft\services\Config, 'addresses' => ['class' => 'craft\services\Addresses'], 'announcements' => ['class' => 'craft\services\Announcements'], 'api' => ['class' => 'craft\services\Api'], ...], 'id' => 'CraftCMS--713fe2f0-ec4d-411e-ab4...', ...])
27. in /var/www/html/vendor/craftcms/cms/bootstrap/web.php at line 40– require('/var/www/html/vendor/craftcms/cm...')
28. in /var/www/html/public/index.php at line 11

**Comment by bencroker** [comment]
The `FileStorage::createGzipFiles` property was removed in Blitz [5.0.0](https://github.com/putyourlightson/craft-blitz/releases/tag/5.0.0). Can you please ensure it no longer exists in the `config/blitz.php` config file?

**Comment by CentroNia1420** [comment]
I don't have a "config/blitz.php" file, as I always used the backend UI for my settings. The documentation read as if it was optional, do I need to add this?

**Comment by CentroNia1420** [comment]
I just tried deleting all table references to Blitz, including the rows in the "projectconfig" table. I then tried installing the plugin and still got the same above error so I have no clue what else I can try as I'm not too skilled with php

**Comment by bencroker** [comment]
> I don't have a "config/blitz.php" file, as I always used the backend UI for my settings. The documentation read as if it was optional, do I need to add this?

No, you shouldn’t have to add this. In your `config/project.yaml` file, can you try _removing_ any lines that look like this under `cacheStorageSettings` and then running `php craft project-config/apply`? That should clear it out and then be deployed to production when project config is applied there.
```
          -
            - createGzipFiles
            - '1' 
```

**Comment by CentroNia1420** [comment]
That fixed it! My yaml file didn't have a number at all within the quotes, but I deleted the entire 3 lines and now it's working. Thanks so much for the quick help! :)

**Comment by bencroker** [comment]
Glad to hear that helped!

**Comment by estebancastro** [comment]
> No, you shouldn’t have to add this. In your `config/project.yaml` file, can you try _removing_ any lines that look like this under `cacheStorageSettings` and then running `php craft project-config/apply`? That should clear it out and then be deployed to production when project config is applied there.
> 
> ```
>           -
>             - createGzipFiles
>             - '1' 
> ```

Just for the record, after upgrading from Craft 4 to 5, to fix this I changed:
```
      cacheStorageSettings:
        __assoc__:
          -
            - folderPath
            - '@webroot/cache/blitz'
          -
            - createGzipFiles
            - '1'
          -
            - createBrotliFiles
            - ''
```
to:
```
      cacheStorageSettings:
        __assoc__:
          -
            - folderPath
            - '@webroot/cache/blitz'
```

then `php craft project-config/apply`

and it works!
