### ISSUE TITLE
Blitz Generates Nothing

### ISSUE THREAD

**Issue by kaspar-allenbach** [putyourlightson/craft-blitz#669]
### Support Request

I run several sites with Blitz and never seen this behavior before:

I've Updated a running craft site to all the latest version (craft `4.9.5`)

- When I'm logged in and bypass Blitz, the site renders fine.
- When I'm not logged in and don't bypass Blitz, nothing is generated except this markup:

`<!-- Served by Blitz on 2024-05-29T18:02:29+02:00 -->`
There is no other content

The timestamp is updated on each page load

- No .logfile is generated

- I hit `Generate Cache` in the CP and the task runner starts its job and runs successfully, but on the Server there is no cache folder being generated.

I have no angle since there is no log and the blitz was running fine before the update. Maybe it's a pathing issue, do you have any ideas?

### Plugin Version

4.18.1

**Comment by kaspar-allenbach** [comment]
I don't know what that behavior was, but I found the solution:

`rm -rf vendor` & `composer install` on the live server

**Comment by bencroker** [comment]
Sounds like perhaps an old file was not replaced, glad to hear you got it working!

**Comment by kaspar-allenbach** [comment]
looks like it.

I deploy to LIVE via github action + rsync + several commands afterwards like `project-config/apply`.
It seems much less reliable then what I was hoping for.
