### ISSUE TITLE
[FR] Treating Craft as an SSG

### ISSUE THREAD

**Issue by MattWilcox** [putyourlightson/craft-blitz#67]
I'm long into Craft but I'm new to the JAMstack stuff - and I'd like the benefits of both: I think you're mostly there with Blitz? It is making a _huge_ amount of sense to me to have pre-generated static files for all URIs pushed out to CDNs, and then pull dynamic content via client-side JS which polls some form of API endpoint on a central server.

A huge problem with all SSGs i've seen is they assume whoever is doing content for the site is a developer and require a developer to trigger the build. I'd like to have Craft as the Content Management and 'build' part of the JAMstack, and Blitz already seems to be doing almost all of the work that might require. I'd love it to be able to offer integration to JAMstack deployment methods: For example, to push those generated flat files to a CDN or S3 bucket so the majority of the site is served from the network edge, or to write them to a GitHub repo so that something like Netlify could take over deployment.

Is this something you're likely to offer?

**Comment by croxton** [comment]
Matt - it's not JAMstack,but have you considered a proxy cache? The static html rendered by Craft can be cached and distributed via a CDN, but you retain the Craft goodness of live previews, granular cache-breaking etc. You can still use JS to poll for content that has to remain dynamic, via CraftQL/GraphQL or just the Element API. I *think* I read that Blitz is will soon support cache-breaking of proxy caches, but there's also this: https://github.com/ostark/upper

**Comment by putyourlightson** [comment]
Thanks for the question @MattWilcox, and for the long discussion that took place over Slack regarding this topic.

The main vision for Blitz was to fill exactly the gap you are asking about. How can we get the best of both worlds: a blazingly fast static site, with a fully dynamic CMS and a great authoring experience. 

Blitz v2 is currently at beta 5.1 and one of it's goals is to make it possible to have the statically cached files that Blitz generates be served by a CDN. Blitz v2 will come with reverse proxy purgers (currently Cloudflare with others planned) and the ability to load purgers dynamically, similarly to how you can load mailer adapters in Craft. This means that you can have your CDN store and serve the statically cached HTML files automatically (by just turning on the setting in Cloudflare) and Blitz will purge the Cloudflare cache whenever it detects changes to your site’s pages. The advantage of a reverse proxy purger is that it generally pulls statically cached files directly from your server. Pushing files to an S3 bucket or Github adds an extra step which seems unnecessary, but I'm open to arguments for it if you have some.

**Comment by MattWilcox** [comment]
Cheers Ben! Nope, I have no particular thoughts about whether pushing to GIT or an S3 bucket or similar would be worth it - must admit that just getting my head straight with "web app" stuff over "web page" stuff is proving interesting. It's just that's a workflow I have seen and which services like Netlify provide. I suppose its possible that a particular project might want Craft to do it's thing, and then some form of build process to run on top of whatever Craft itself spits out, before those newly built files get pushed to a CDN - but I certainly have no knowledge about if that might be a liklihood, or desirable. Still learning the basics of the "app web" side of things at the moment. I can imagine someone somewhere might want to hook into a Netlify type deployment with the core files being ingested from whatever Blitz creates... but that's just guessing.

**Comment by putyourlightson** [comment]
For now, my recommendation would be to stick to a “pull service“ (reverse proxy purger) such as Cloudflare, KeyCDN or Fastly. That way the CDN is responsible for “pulling” the page from Blitz and Blitz is responsible for purging that cache any time updates are made to the content. The idea of “pushing” the cache to a third-party service such as GIT or S3 seems less efficient and more to have to manage.

I'll be releasing a video (and documentation) that explains the benefits and recommended way of using CDNs together with Blitz with the release of v2.

**Comment by putyourlightson** [comment]
In case you missed the announcement, Blitz 3 introduces "Remote Deployment" which sounds exactly like what you're after. Currently in beta but coming soon, see the announcement here: 
https://putyourlightson.com/articles/blitz-3-is-here-hello-jamstack
