### ISSUE TITLE
Creating and updating drafts or offline pages triggers Blitz cache purge

### ISSUE THREAD

**Issue by jan-dh** [putyourlightson/craft-blitz#670]
### Bug Report

When creating page as a draft the Blitz cache clear task gets triggered
When creating or updating an offline page the Blitz cache gets triggered

Since we're on cloudfront having some more granular control to minimise the amount of invalidation requests would be very nice.

### Diagnostics Report

Craft CMS: 4.8.9
Blitz 4.16.0
PHP 8.1.17

**Comment by bencroker** [comment]
Please explain what exactly you are seeing and how it is an issue, so I can reproduce and help you with this.

**Comment by jan-dh** [comment]
Hmm, saw Blitz cache clear appearing in the queue this morning when I was editing a Draft & offline page but can't recreate since. Will close for now.
