### ISSUE TITLE
Error connecting to the Git repository in the Remote Deployment settings

### ISSUE THREAD

**Issue by handplant** [putyourlightson/craft-blitz#671]
### Bug Report

The error `Error connecting to repository: Exit code: 127 while executing: 'LC_ALL=C '-c' user.name=handplant '-c' user.email=andi.grether@gmail.com remote '--verbose' with reason: sh: -c: command not found` occurs. Shouldn't -c be without quotation marks, or is there another issue?

![Bildschirmfoto 2024-06-06 um 08 52 49](https://github.com/putyourlightson/craft-blitz/assets/2598962/ed51bcc3-ca1f-44c2-9c0e-c8386aaed6f9)

The paths to the local repo are correct.

![Bildschirmfoto 2024-06-06 um 08 55 24](https://github.com/putyourlightson/craft-blitz/assets/2598962/a4e168ce-d1dc-4b2b-a5bd-12247e7bf58c)

Thanks in advance!

#### Application Info

- PHP version: 8.2.19
- Craft edition & version: Pro 5.1.8
- Database driver & version: MySQL 8.3.0

#### Installed Plugins

- Blitz: 5.3.1
- CKEditor: 4.0.6
- Elements Panel: 3.0.0
- Embedded Assets: 5.1.0
- Feed Me: 6.1.0
- Hyper: 2.0.1
- Image Resizer: 4.0.0
- SEOMate: 3.0.0-beta.6
- Sprig: 3.0.2
- Vite: 5.0.0

#### Loaded Modules

- codeeditor: nystudio107\codeeditor\CodeEditor
- sprig-core: putyourlightson\sprig\Sprig
- verbb-base: verbb\base\Base

#### Blitz Plugin Settings

```json
{
    "debug": false,
    "hintsEnabled": true,
    "cachingEnabled": true,
    "refreshCacheEnabled": true,
    "refreshMode": 3,
    "includedUriPatterns": [
        {
            "siteId": "1",
            "uriPattern": ".*"
        },
        {
            "siteId": "1",
            "uriPattern": ""
        }
    ],
    "excludedUriPatterns": [],
    "cacheStorageType": "putyourlightson\\blitz\\drivers\\storage\\FileStorage",
    "cacheStorageSettings": {
        "folderPath": "@webroot\/cache\/blitz",
        "compressCachedValues": ""
    },
    "cacheStorageTypes": [],
    "cacheGeneratorType": "putyourlightson\\blitz\\drivers\\generators\\LocalGenerator",
    "cacheGeneratorSettings": {
        "concurrency": "3"
    },
    "cacheGeneratorTypes": [],
    "customSiteUris": [],
    "cachePurgerType": "putyourlightson\\blitz\\drivers\\purgers\\DummyPurger",
    "cachePurgerSettings": [],
    "cachePurgerTypes": [],
    "deployerType": "putyourlightson\\blitz\\drivers\\deployers\\GitDeployer",
    "deployerSettings": {
        "gitRepositories": {
            "6eab4b84-63fb-4382-bdd7-d2bee959aafb": {
                "repositoryPath": "\/Users\/andee\/Sites\/craft\/playground5-static",
                "branch": "main",
                "remote": "origin"
            },
            "7d2f72c3-2676-4d61-9279-bf2e5b06d06d": {
                "repositoryPath": "\/Users\/andee\/Sites\/craft\/playground5-static",
                "branch": "main",
                "remote": "origin"
            }
        },
        "commitMessage": "Blitz auto commit",
        "username": "handplant",
        "personalAccessToken": "****************************************",
        "name": "handplant",
        "email": "andi.grether@gmail.com",
        "commandsBefore": "",
        "commandsAfter": ""
    },
    "deployerTypes": [],
    "ssiEnabled": false,
    "ssiTagFormat": "<!--#include virtual=\"{uri}\" -->",
    "detectSsiEnabled": true,
    "esiEnabled": false,
    "queryStringCaching": 0,
    "includedQueryStringParams": [
        {
            "siteId": "",
            "queryStringParam": ".*"
        }
    ],
    "excludedQueryStringParams": [
        {
            "siteId": "",
            "queryStringParam": "gclid"
        },
        {
            "siteId": "",
            "queryStringParam": "fbclid"
        }
    ],
    "apiKey": "",
    "generatePagesWithQueryStringParams": true,
    "purgeAssetImagesWhenChanged": true,
    "refreshCacheAutomaticallyForGlobals": true,
    "refreshCacheWhenElementMovedInStructure": true,
    "refreshCacheWhenElementSavedUnchanged": false,
    "refreshCacheWhenElementSavedNotLive": false,
    "cacheNonHtmlResponses": false,
    "trackElements": true,
    "trackElementQueries": true,
    "excludedTrackedElementQueryParams": [],
    "cacheDuration": null,
    "nonCacheableElementTypes": [],
    "sourceIdAttributes": [],
    "liveStatuses": [],
    "integrations": [
        "putyourlightson\\blitz\\drivers\\integrations\\CommerceIntegration",
        "putyourlightson\\blitz\\drivers\\integrations\\FeedMeIntegration",
        "putyourlightson\\blitz\\drivers\\integrations\\SeomaticIntegration"
    ],
    "defaultCacheControlHeader": "no-store",
    "cacheControlHeader": "public, max-age=31536000",
    "cacheControlHeaderExpired": "public, max-age=5",
    "sendPoweredByHeader": true,
    "outputComments": true,
    "refreshCacheJobPriority": 10,
    "driverJobBatchSize": 100,
    "driverJobPriority": 100,
    "queueJobTtr": 300,
    "maxRetryAttempts": 10,
    "maxUriLength": 255,
    "mutexTimeout": 1,
    "commands": [],
    "injectScriptEvent": "DOMContentLoaded",
    "injectScriptPosition": 3
}
```

#### Recommendations

- ❌ The Blitz Hints utility is reporting 1 eager-loading opportunity.
- ❌ The blitz/cache/refresh-expired console command has not been executed within the past 24 hours.
- ✅ Blitz is configured not to refresh cached pages when an element is saved but unchanged.
- ✅ Blitz is configured not to refresh cached pages when an element is saved but not live.
- ✅ Image transforms are configured to be generated before page load.
- ✅ No globals exist.
- ✅ The @web alias is not used in the base URL of any sites.
- ✅ Queue jobs are configured not to run automatically via web requests.
- ✅ The Async Queue plugin is not installed or enabled.

#### Site Tracking [#1]

- Tracked Pages: 6
- Tracked Includes: 0
- Tracked Query String Params: 0
- Tracked Elements: 10
    - craft\elements\Entry: 9
    - craft\elements\User: 1
- Tracked Element Queries: 2
    - craft\elements\Entry: 2
- Tracked Tags: 0

#### Site Tracking [#2]

- Tracked Pages: 0
- Tracked Includes: 0
- Tracked Query String Params: 0
- Tracked Elements: 0
- Tracked Element Queries: 0
- Tracked Tags: 0

**Comment by bencroker** [comment]
The repository path in your local development environment is likely not at `/Users/...`. When using DDEV, for example, the path will be `/var/www/html`, which you can verify by running `ddev ssh` and then `pwd`. It might be easier, however, to use the `@root` alias, which points to the route project inside the container. See https://craftcms.com/docs/5.x/configure.html#aliases

**Comment by handplant** [comment]
No, I don't use DDEV. I use Laravel Herd and I have two repositories and project paths: one for the Craft CMS (playground5) itself and one for the static site (playground5-static), as described in the screenshot.

![Bildschirmfoto 2024-06-07 um 07 39 05](https://github.com/putyourlightson/craft-blitz/assets/2598962/953a5911-c4f9-46fe-999f-55878228f54c)

**Comment by bencroker** [comment]
Can you please check the value of `PWD` under _Utilities → PHP Info_ in the CP?

**Comment by handplant** [comment]
Under "Utilities → PHP Info," there is no pwd entry. However, my path should be correct. See screenshot.

![Bildschirmfoto 2024-06-10 um 08 45 12](https://github.com/putyourlightson/craft-blitz/assets/2598962/85cb1b34-c42e-4dfc-ad2f-9695e42fe592)

**Comment by bencroker** [comment]
You’re right, the path does look correct, so it may be a problem with the path to the Git binary.

It looks like you’re on MacOS. Can you check whether running `which git` returns `/usr/bin/git` or something else? And please check whether `git status` runs successfully?

**Comment by handplant** [comment]
I installed git using Homebrew: `/opt/homebrew/bin/git`. `git status` is correct. See screenshot.

![Bildschirmfoto 2024-06-10 um 09 19 41](https://github.com/putyourlightson/craft-blitz/assets/2598962/ce9eef56-3213-4aad-8a62-269e154a6291)

**Comment by bencroker** [comment]
Can please manually add the following above line 195 and share the stack trace?
https://github.com/putyourlightson/craft-blitz/blob/87863bbcc32bc72da6fbf3599fea88cfd3a6f634/src/drivers/deployers/GitDeployer.php#L195

```php
throw $exception;
```

**Comment by handplant** [comment]
I added `throw $exception;` and then navigated to `http://playground5.test/admin/settings/plugins/blitz?site=de` in the control panel. This is where the error occurs.

![playground5 test_admin_settings_plugins_blitz_site=de](https://github.com/putyourlightson/craft-blitz/assets/2598962/44616168-d0be-4da9-a629-42ed308866f2)

**Comment by bencroker** [comment]
Thanks, that unfortunately doesn’t give any clues.

Can you please try defining the Git executable path using the [`commands`](https://github.com/putyourlightson/craft-blitz/blob/87863bbcc32bc72da6fbf3599fea88cfd3a6f634/src/config.php#L275-L278) config setting as follows? It should be auto-detected but perhaps this is not working.

```php
        // The paths to executable shell commands.
        'commands' => [
            'git' => '/opt/homebrew/bin/git',
        ],
```

**Comment by handplant** [comment]
Hey, that helps. I was able to successfully deploy the data to a GitHub repo. Thanks a lot for your effort!

**Comment by bencroker** [comment]
Great to hear! I’m not sure why it was not correctly auto-detected, possibly a permission issue.
