### ISSUE TITLE
Cache refresh not working for listings when new entries are added, even with cron `refresh-expired` running

### ISSUE THREAD

**Issue by brnquester** [putyourlightson/craft-blitz#675]
### Bug Report

We're having issues with pages listing the most recent entries from a section not refreshing cache when a new entry is added/published. It does refresh on updated of entries already listed. 

In a previous thread (https://github.com/putyourlightson/craft-blitz/issues/492 ), we switched the `cacheElementQueries` to `false` and started tagging those listing pages as follows:
```

{% if craft.blitz.options.tags %}
	{% do craft.blitz.options.tags(craft.blitz.options.tags|merge(['sectionId:16'])) %}
{% else %}
	{% do craft.blitz.options.tags(['sectionId:16']) %}
{% endif %}
```

We have a cron running `./craft blitz/cache/refresh-expired` every 5 min. We have tested this locally as well, it doesn't flag the listing page to refresh cache for the given section even with the tagging.

This is causing a lot of problems with our content authors. Just to bring again our context, we have a very large website content with over 10k live entries.

### Diagnostics Report

- Craft CMS v3.9.10
- Blitz plugin v3.12.9
- PHP v8.0.30
- DB MySQL v8.0.23
- PHP Memory Limit 1024M
- Max execution time 300s
- Robust queue job handling on via systemd worker

## Blitz config options:
```
[

        'debug' => false,

        'warmCacheAutomatically' => true,

        "cachingEnabled" => true,

        'cacheControlHeader' => 'max-age=0, s-maxage=60, stale-while-revalidate=300, stale-if-error=86400',

        'cacheDuration' => 0,

        'cacheElementQueries' => false,

        'cacheElements' => true,

        "queueJobTtr" => 3600,

        'cacheWarmerType' => 'putyourlightson\blitz\drivers\warmers\GuzzleWarmer',

        "cacheWarmerSettings" => ["concurrency" => 2],

        "sendPoweredByHeader" => false,

        'outputComments' => 2,

        'cacheStorageType' => 'putyourlightson\blitz\drivers\storage\FileStorage',

        'cacheStorageSettings' => [
           'folderPath' => '@webroot/cache/blitz',
           'createGzipFiles' => false,
           'countCachedFiles' => false,
        ],

        'clearCacheAutomatically' => true,

        'deployerType' => 'putyourlightson\blitz\drivers\deployers\DummyDeployer',

        'driverJobPriority' => 100,

        'queryStringCaching' => 1,

        'warmPagesWithQueryStringParams' => false,

        'injectScriptEvent' => 'DOMContentLoaded',

        'integrations' => [
           'putyourlightson\blitz\drivers\integrations\FeedMeIntegration',
           'putyourlightson\blitz\drivers\integrations\SeomaticIntegration',
        ],

        'maxRetryAttempts' => 10,

        'mutexTimeout' => 1,

        'refreshCacheAutomaticallyForGlobals' => true,

        'refreshCacheJobPriority' => 10,

        'refreshCacheWhenElementSavedUnchanged' => false,

        'refreshCacheWhenElementSavedNotLive' => false,
    ]
```

**Comment by bencroker** [comment]
Before I jump into the code, are you able to update to the latest version Blitz 3.14.0 to eliminate any possible issues that were previously addressed?

**Comment by brnquester** [comment]
> Before I jump into the code, are you able to update to the latest version Blitz 3.14.0 to eliminate any possible issues that were previously addressed?

@bencroker - thanks for the quick response. I can confirm that even updating to v3.14, new entries added to the tagged section in a listing page doesn't flag that page for refresh.

**Comment by bencroker** [comment]
Thanks, I’ll take a closer look and let you know what I find.

**Comment by brnquester** [comment]
> Thanks, I’ll take a closer look and let you know what I find.

@bencroker - sorry for the "pressure". As you can imagine, we're having to manually clear cache and for a large website like ours, not everyone has access to utilities. Any news here would be appreciated.

**Comment by bencroker** [comment]
I understand and will prioritise this.

**Comment by bencroker** [comment]
I did some testing locally and source tags are working as expected for me using 3.14.0. Can you please open the `blitz_cachetags` database table and ensure that the `section:16` tag is associated with the cached pages that you expect it to be?

**Comment by brnquester** [comment]
> I did some testing locally and source tags are working as expected for me using 3.14.0. Can you please open the `blitz_cachetags` database table and ensure that the `section:16` tag is associated with the cached pages that you expect it to be?

@bencroker - thanks again for the dedication and effort on this. My testing steps:
1. Cleared all cached pages and flushed all database cached records;
2. Confirmed the `blitz_cachetags` was empty;
3. Reloaded the page;
4. Checked again the `blitz_cachetags` table, it had 1 record where the cacheId was correct pointing to the page, but showing `sectionId:42` for the tag. The code I have on the page:
```
{% if craft.blitz.options.tags %}
	{% do craft.blitz.options.tags(craft.blitz.options.tags|merge(['sectionId:16'])) %}
{% else %}
	{% do craft.blitz.options.tags(['sectionId:16']) %}
{% endif %}
```
Just to reinforce, I'm working on the correct template. I can make other changes and see it right away. The `sectionId:42` is coming from an include I have on this template. It seems that it is not merging the tags on my condition.

**Comment by brnquester** [comment]
> > I did some testing locally and source tags are working as expected for me using 3.14.0. Can you please open the `blitz_cachetags` database table and ensure that the `section:16` tag is associated with the cached pages that you expect it to be?
> 
> @bencroker - thanks again for the dedication and effort on this. My testing steps:
> 
> 1. Cleared all cached pages and flushed all database cached records;
> 2. Confirmed the `blitz_cachetags` was empty;
> 3. Reloaded the page;
> 4. Checked again the `blitz_cachetags` table, it had 1 record where the cacheId was correct pointing to the page, but showing `sectionId:42` for the tag. The code I have on the page:
> 
> ```
> {% if craft.blitz.options.tags %}
> 	{% do craft.blitz.options.tags(craft.blitz.options.tags|merge(['sectionId:16'])) %}
> {% else %}
> 	{% do craft.blitz.options.tags(['sectionId:16']) %}
> {% endif %}
> ```
> 
> Just to reinforce, I'm working on the correct template. I can make other changes and see it right away. The `sectionId:42` is coming from an include I have on this template. It seems that it is not merging the tags on my condition.

@bencroker - figured it out. The tag including `sectionId:42` wasn't merging tags and for some reason, it was happening after my tag merge in the template I was extending. Really appreciate you anyway.

**Comment by bencroker** [comment]
Sure thing, glad to hear you figured it out!
