### ISSUE TITLE
SEOmatic possibly triggering an infinite loop on Cloudfront invalidation requests

### ISSUE THREAD

**Issue by jan-dh** [putyourlightson/craft-blitz#676]
### Bug Report

Yesterday we had a situation where the following happend:
1. We notice an event from SEOmatic that caused an error
2. Next thing we see is an infinite loop starting from Blitz to invalidate caches which ramped up to 170.000k Blitz tasks in queue
3. When further inspecting, it seems all the blitz cache entries in the DB gotten an expiry date (of the exact moment the SEOmatic error happend)
4. Flushing the DB & clearing the queue managed to solve this

The SEOmatic event which was flagged already with Andrew
```
[web.ERROR] [nystudio107\\seomatic\\services\\MetaBundles::updateMetaBundle] Meta bundle failed validation: Array (     [typeId] => Array         (             [0] => Type Id must be no less than 1.         )  )  type: channel id: 12 from siteId: 8 
```

The report shows not a lot of items being tracked since the DB was flushed

#### Application Info

- PHP version: 8.1.17
- Craft edition & version: Pro 4.9.7
- Database driver & version: MySQL 8.0.26

#### Installed Plugins

- Blitz: 4.18.1
- Blitz CloudFront Purger: 4.0.0
- CKEditor: 3.8.3
- Cloner: 2.0.4
- Control Panel CSS: 2.6.0
- Dashboard Begone: 2.0.0
- Feed Me: 5.5.0
- Field Manager: 3.0.8
- Google Cloud Storage: 2.2.0
- Hyper: 1.1.31
- Imager X: 4.4.0
- Inventory: 3.2.0
- Jason: 3.0.1
- Knock Knock: 2.0.11
- MatrixMate: 2.2.1
- Navigation: 2.0.27
- Retour: 4.1.16
- SendGrid: 2.0.1
- SEOmatic: 4.0.49
- Sprig: 2.8.1
- Super Table: 3.0.14
- Template Selector: 5.0.1
- Translations: 4.0.2
- Vite: 4.0.9
- Vizy: 2.1.19

#### Loaded Modules

- twig-extension: modules\sitemodule\Module
- blitz-refresh-cache-logger: modules\BlitzRefreshCacheLogger
- codeeditor: nystudio107\codeeditor\CodeEditor
- sprig-core: putyourlightson\sprig\Sprig
- blitz-hints: putyourlightson\blitzhints\BlitzHints
- verbb-base: verbb\base\Base
- debug: craft\debug\Module

#### Blitz Plugin Settings

```json
{
    "debug": true,
    "hintsEnabled": true,
    "cachingEnabled": true,
    "refreshCacheEnabled": true,
    "refreshMode": 2,
    "includedUriPatterns": [
        {
            "siteId": "",
            "uriPattern": ".*"
        }
    ],
    "cacheStorageType": "putyourlightson\\blitz\\drivers\\storage\\YiiCacheStorage",
    "cacheStorageSettings": [],
    "cacheStorageTypes": [],
    "cacheGeneratorType": "putyourlightson\\blitz\\drivers\\generators\\HttpGenerator",
    "cacheGeneratorSettings": {
        "concurrency": "3"
    },
    "cacheGeneratorTypes": [],
    "customSiteUris": [],
    "cachePurgerType": "putyourlightson\\blitzcloudfront\\CloudFrontPurger",
    "cachePurgerSettings": {
        "condenseUrls": false
    },
    "cachePurgerTypes": [],
    "deployerType": "putyourlightson\\blitz\\drivers\\deployers\\DummyDeployer",
    "deployerSettings": [],
    "deployerTypes": [],
    "ssiEnabled": true,
    "ssiTagFormat": "[an error occurred while processing the directive]",
    "detectSsiEnabled": true,
    "esiEnabled": false,
    "queryStringCaching": 2,
    "includedQueryStringParams": [
        {
            "siteId": "",
            "queryStringParam": ".*"
        }
    ],
    "excludedQueryStringParams": [
        {
            "siteId": "",
            "queryStringParam": "gclid"
        },
        {
            "siteId": "",
            "queryStringParam": "fbclid"
        }
    ],
    "apiKey": "",
    "generatePagesWithQueryStringParams": true,
    "purgeAssetImagesWhenChanged": true,
    "refreshCacheAutomaticallyForGlobals": false,
    "refreshCacheWhenElementMovedInStructure": true,
    "refreshCacheWhenElementSavedUnchanged": false,
    "refreshCacheWhenElementSavedNotLive": false,
    "cacheNonHtmlResponses": false,
    "trackElements": true,
    "trackElementQueries": true,
    "excludedTrackedElementQueryParams": [],
    "cacheElements": true,
    "cacheElementQueries": true,
    "cacheDuration": null,
    "nonCacheableElementTypes": [],
    "sourceIdAttributes": [],
    "liveStatuses": [],
    "integrations": [
        "putyourlightson\\blitz\\drivers\\integrations\\FeedMeIntegration",
        "putyourlightson\\blitz\\drivers\\integrations\\SeomaticIntegration"
    ],
    "defaultCacheControlHeader": "no-cache, no-store, must-revalidate",
    "cacheControlHeader": "public, s-maxage=2592000, max-age=2592000",
    "cacheControlHeaderExpired": "public, s-maxage=5, max-age=0",
    "sendPoweredByHeader": true,
    "outputComments": true,
    "refreshCacheJobPriority": 10,
    "driverJobBatchSize": 100,
    "driverJobPriority": 100,
    "queueJobTtr": 3600,
    "maxRetryAttempts": 2,
    "maxUriLength": 255,
    "mutexTimeout": 30,
    "commands": [],
    "injectScriptEvent": "DOMContentLoaded",
    "injectScriptPosition": 3
}
```

#### Recommendations

- ❌ The Blitz Hints utility is reporting 22 eager-loading opportunities.
- ❌ The blitz/cache/refresh-expired console command has not been executed within the past 24 hours.
- ✅ Blitz is configured not to refresh cached pages when an element is saved but unchanged.
- ✅ Blitz is configured not to refresh cached pages when an element is saved but not live.
- ✅ Image transforms are configured to be generated before page load.
- ✅ No globals exist.
- ✅ The @web alias is explicitly defined.
- ✅ Queue jobs are configured not to run automatically via web requests.
- ✅ The Async Queue plugin is not installed or enabled.

#### Site Tracking [#1]

- Tracked Pages: 2
- Tracked Includes: 0
- Tracked Query String Params: 0
- Tracked Elements: 24
    - craft\elements\Entry: 21
    - craft\elements\Asset: 3
- Tracked Element Queries: 3
    - craft\elements\Entry: 3
- Tracked Tags: 0

#### Site Tracking [#2]

- Tracked Pages: 4
- Tracked Includes: 0
- Tracked Query String Params: 0
- Tracked Elements: 38
    - craft\elements\Entry: 29
    - craft\elements\Asset: 9
- Tracked Element Queries: 6
    - craft\elements\Entry: 6
- Tracked Tags: 0

#### Site Tracking [#3]

- Tracked Pages: 9
- Tracked Includes: 0
- Tracked Query String Params: 0
- Tracked Elements: 84
    - craft\elements\Entry: 55
    - craft\elements\Asset: 29
- Tracked Element Queries: 9
    - craft\elements\Entry: 9
- Tracked Tags: 0

#### Site Tracking [#4]

- Tracked Pages: 3
- Tracked Includes: 0
- Tracked Query String Params: 0
- Tracked Elements: 39
    - craft\elements\Entry: 29
    - craft\elements\Asset: 10
- Tracked Element Queries: 3
    - craft\elements\Entry: 3
- Tracked Tags: 0

#### Site Tracking [#5]

- Tracked Pages: 2
- Tracked Includes: 0
- Tracked Query String Params: 0
- Tracked Elements: 27
    - craft\elements\Entry: 21
    - craft\elements\Asset: 6
- Tracked Element Queries: 3
    - craft\elements\Entry: 3
- Tracked Tags: 0

#### Site Tracking [#6]

- Tracked Pages: 3
- Tracked Includes: 0
- Tracked Query String Params: 0
- Tracked Elements: 20
    - craft\elements\Entry: 17
    - craft\elements\Asset: 3
- Tracked Element Queries: 3
    - craft\elements\Entry: 3
- Tracked Tags: 0

#### Site Tracking [#7]

- Tracked Pages: 4
- Tracked Includes: 0
- Tracked Query String Params: 0
- Tracked Elements: 83
    - craft\elements\Entry: 53
    - craft\elements\Asset: 30
- Tracked Element Queries: 8
    - craft\elements\Entry: 8
- Tracked Tags: 0

#### Site Tracking [#8]

- Tracked Pages: 5
- Tracked Includes: 0
- Tracked Query String Params: 0
- Tracked Elements: 91
    - craft\elements\Entry: 62
    - craft\elements\Asset: 29
- Tracked Element Queries: 7
    - craft\elements\Entry: 7
- Tracked Tags: 0

**Comment by bencroker** [comment]
Do you have a link to where this has been reported to SEOmatic so I can follow along and see if any improvements can be made in the Blitz integration?

**Comment by jan-dh** [comment]
This is the commit (for V5 but it's being implemented for all versions); not released atm:
https://github.com/nystudio107/craft-seomatic/commit/67e77db2ca45ced28800b3f3165c656ee00854ec

the report was done through Discord, the `seomatic_metabundles` table had non-integer `typeId` column (NULL) which failed validation

**Comment by bencroker** [comment]
Ok, it doesn't tell me much but safe to assume this will resolve the issue in the next release of SEOmatic.
