### ISSUE TITLE
Twig native {% redirect %}

### ISSUE THREAD

**Issue by DenyEs** [putyourlightson/craft-blitz#679]
### Support Request

Hi guys,

Some of the pages on my project are set up the way that they can only be access by a certain user group. When the page is loading, it checks for logged in user's group and if it matched one of the allowed user groups, they can view the page.

If they are logged in but don't match any allowed user groups, I exit with a response code 403 and if they're not logged in at all, I want to redirect them to a login page.

How do I make this happen when I have Blitz caching enabled? I tried to use dynamicIncludes but then the redirected page is injected into the page I don't want certain users to see. I tried multiple things but I can't figure it out.

Any help would be appreciated.

```
{% set hasAccess = false %}

{% if currentUser is not null %}
    {% if currentUser.isInGroup(allowedUsergroup) %}
        {% set hasAccess = true %}
    {% else %}
        {% exit 403 %}
    {% endif %}
{% else %}
    {% redirect '/user/login' %}
{% endif %}
```

### Plugin Version

4.18.3

**Comment by bencroker** [comment]
You cannot statically cache such pages without using a dynamic include (or Sprig) to conditionally load the content. Sprig facilitates client-side redirects using the [`sprig.location(url)`](https://putyourlightson.com/plugins/sprig#sprig-locationurl) method, in case you need to redirect.
