### ISSUE TITLE
Missing stackTrace Column After Updating to CraftCMS 5

### ISSUE THREAD

**Issue by viesrood** [putyourlightson/craft-blitz#681]
### Bug Report

Hi,

After updating CraftCMS from version 4 to 5, I encountered the following error related to the Blitz plugin:

sql

`SQLSTATE[42S22]: Column not found: 1054 Unknown column 'stackTrace' in 'field list'`

It appears that the stackTrace column is missing from the blitz_hints table after the update. I tried running the migrations again using:

bash

```
php craft migrate/all
php craft blitz/migrate
```

However, the issue persists. Could you please provide guidance on properly resolving this issue, or update the plugin to ensure compatibility with CraftCMS 5?

Thank you for your assistance.

#### Application Info

- PHP version: 8.2.20
- Craft edition & version: Pro 5.2.5
- Database driver & version: MySQL 8.0.36

#### Installed Plugins

- Blitz: 5.3.4
- CKEditor: 4.1.0
- Imager X: 5.0.1
- Minify: 5.0.0
- oEmbed: 3.0.8
- SEO: 5.0.4
- Super Table: 4.0.1
- Typogrify: 5.0.1

#### Loaded Modules

- my-module: modules\Module
- tegeltjeswand: modules\TegeltjeswandModule
- codeeditor: nystudio107\codeeditor\CodeEditor
- sprig-core: putyourlightson\sprig\Sprig
- verbb-base: verbb\base\Base

#### Blitz Plugin Settings

```json
{
    "debug": false,
    "hintsEnabled": true,
    "cachingEnabled": true,
    "refreshCacheEnabled": true,
    "refreshMode": 3,
    "includedUriPatterns": [
        {
            "uriPattern": ".*"
        }
    ],
    "excludedUriPatterns": [
        {
            "uriPattern": "https:\/\/viesrood.nl\/tegeltjeswand\/form"
        },
        {
            "uriPattern": "https:\/\/viesrood.nl\/tegeltjeswand\/"
        }
    ],
    "cacheStorageType": "putyourlightson\\blitz\\drivers\\storage\\FileStorage",
    "cacheStorageSettings": {
        "folderPath": "@webroot\/cache\/blitz",
        "compressCachedValues": ""
    },
    "cacheStorageTypes": [],
    "cacheGeneratorType": "putyourlightson\\blitz\\drivers\\generators\\HttpGenerator",
    "cacheGeneratorSettings": {
        "concurrency": "3"
    },
    "cacheGeneratorTypes": [],
    "customSiteUris": [],
    "cachePurgerType": "putyourlightson\\blitz\\drivers\\purgers\\DummyPurger",
    "cachePurgerSettings": [],
    "cachePurgerTypes": [],
    "deployerType": "putyourlightson\\blitz\\drivers\\deployers\\DummyDeployer",
    "deployerSettings": [],
    "deployerTypes": [],
    "ssiEnabled": false,
    "ssiTagFormat": "<!--#include virtual=\"{uri}\" -->",
    "detectSsiEnabled": true,
    "esiEnabled": false,
    "queryStringCaching": 0,
    "includedQueryStringParams": [
        {
            "queryStringParam": ".*"
        }
    ],
    "excludedQueryStringParams": [
        {
            "queryStringParam": "gclid"
        },
        {
            "queryStringParam": "fbclid"
        }
    ],
    "apiKey": "",
    "generatePagesWithQueryStringParams": true,
    "purgeAssetImagesWhenChanged": true,
    "refreshCacheAutomaticallyForGlobals": true,
    "refreshCacheWhenElementMovedInStructure": true,
    "refreshCacheWhenElementSavedUnchanged": false,
    "refreshCacheWhenElementSavedNotLive": false,
    "cacheNonHtmlResponses": false,
    "trackElements": true,
    "trackElementQueries": true,
    "excludedTrackedElementQueryParams": [],
    "cacheDuration": null,
    "nonCacheableElementTypes": [],
    "sourceIdAttributes": [],
    "liveStatuses": [],
    "integrations": [
        "putyourlightson\\blitz\\drivers\\integrations\\CommerceIntegration",
        "putyourlightson\\blitz\\drivers\\integrations\\FeedMeIntegration",
        "putyourlightson\\blitz\\drivers\\integrations\\SeomaticIntegration"
    ],
    "defaultCacheControlHeader": "no-store",
    "cacheControlHeader": "public, max-age=31536000",
    "cacheControlHeaderExpired": "public, max-age=5",
    "sendPoweredByHeader": true,
    "outputComments": true,
    "refreshCacheJobPriority": 10,
    "driverJobBatchSize": 100,
    "driverJobPriority": 100,
    "queueJobTtr": 300,
    "maxRetryAttempts": 10,
    "maxUriLength": 255,
    "mutexTimeout": 1,
    "commands": [],
    "injectScriptEvent": "DOMContentLoaded",
    "injectScriptPosition": 3
}
```

#### Recommendations

- ❌ Image transforms are configured not to be generated before page load.
- ❌ Queue jobs are configured to run automatically via web requests.
- ❌ The Blitz Hints utility is reporting 6 eager-loading opportunities.
- ❌ The blitz/cache/refresh-expired console command has not been executed within the past 24 hours.
- ✅ Blitz is configured not to refresh cached pages when an element is saved but unchanged.
- ✅ Blitz is configured not to refresh cached pages when an element is saved but not live.
- ✅ No globals exist.
- ✅ The @web alias is not used in the base URL of any sites.
- ✅ The Async Queue plugin is not installed or enabled.

#### Site Tracking 

- Tracked Pages: 35
- Tracked Includes: 0
- Tracked Query String Params: 0
- Tracked Elements: 424
	- craft\elements\Asset: 288
	- craft\elements\Entry: 126
	- craft\elements\User: 10
- Tracked Element Queries: 2
	- craft\elements\Entry: 1
	- craft\elements\User: 1
- Tracked Tags: 0

**Comment by bencroker** [comment]
It looks like the [`m240310_120000_add_stack_trace`](https://github.com/putyourlightson/craft-blitz/blob/develop/src/migrations/m240310_120000_add_stack_trace.php) failed to run during your upgrade. Can you try removing it from the `migrations` database table, setting the value of `schemaVersion` to `5.0.0.0` in the `plugins` database table, and finally running `php craft migrate/all`?

**Comment by viesrood** [comment]
That solved the problem! Thanks a lot!

**Comment by bencroker** [comment]
Glad to hear it!
