### ISSUE TITLE
Excluding Specific Sections from Automatic Cache Clearing

### ISSUE THREAD

**Issue by green17** [putyourlightson/craft-blitz#683]
### Support Request

I am using the Blitz plugin version 3.15.0 with Craft CMS 3.8.16 and I am looking to exclude specific sections from being cleared automatically by the Blitz cache.

Exclude specific sections (e.g., sections with handles excludedSectionHandle1 and excludedSectionHandle2) from being automatically cleared from the Blitz cache, but still clear all the rest as content is edited. Is there any way to do this via hooks, configuration, or any other method? We have 'Clear Cache Automatically' ON and 'Warm Cache Automatically' OFF.

Could you please provide guidance on how to properly exclude specific sections from automatic cache clearing using Blitz? If there is a recommended way to achieve this, or if I am missing something in my current approach, any assistance would be greatly appreciated.

Thank you for your help!

### Plugin Version

3.15.0

**Comment by bencroker** [comment]
What exactly do you mean when you say “sections being cleared”? Sections are not cashed per se, pages (with individual URLs) are, which may contain one or more entries from various sections. If you can explain your specific use-case in a bit more detail then perhaps I can provide a solution.

**Comment by green17** [comment]
Thansk Ben, we have 3 sections that don't have URLs that users add content to, e.g. when they advance search, it stores the search they do and a few other bits. This gets shown to them in a sprig component, which is excluded from blitz, but any time users add to these sections it fires off a blitz cue, which we can see the section ID matches up to the ID of the 3 sections. Let me know if you need more info.

**Comment by bencroker** [comment]
This shouldn’t be an issue, as Blitz will presumably not find any cached pages to clear. What is the concern?

Here’s some code to help get you started with preventing the cache refresh process from happening using a custom module/plugin.

```php
use craft\elements\Entry;
use putyourlightson\blitz\events\RefreshElementEvent;
use putyourlightson\blitz\services\RefreshCacheService;
use yii\base\Event;

$excludedSectionIds = [1, 2, 3];

Event::on(RefreshCacheService::class, RefreshCacheService::EVENT_BEFORE_ADD_ELEMENT,
    function(RefreshElementEvent $event) {
        if ($event->element instanceof Entry) {
            $entry = $event->element;
            if (in_array($entry->sectionId, $excludedSectionIds)) {
                $event->isValid = false;
            }
        }
    }
);
```

**Comment by green17** [comment]
Thanks so much, Ben. This sorted the problem perfectly. :-)

**Comment by bencroker** [comment]
Glad to hear it!
