### ISSUE TITLE
Generating blitz cache for unwanted pages 

### ISSUE THREAD

**Issue by Brijeshgrg1999** [putyourlightson/craft-blitz#684]
### Bug Report

Hi I am new to this plugin and I really appreciates its features but after playing around i have a few questions and concerns.

but the weird part is why am i getting this many queue here : 
<img width="1193" alt="Screenshot 2024-07-10 at 1 59 50 PM" src="https://github.com/putyourlightson/craft-blitz/assets/118506279/5603a3db-217a-4439-b6c2-c48b308ce612">

am i doing some thing wrong in the blitz.php file ? I just wanna refresh the cache those are updated not the whole site or entries . please help 

### Diagnostics Report

<img width="707" alt="Screenshot 2024-07-10 at 2 01 16 PM" src="https://github.com/putyourlightson/craft-blitz/assets/118506279/badac2ca-61ca-4777-bca1-15f7c39b7edc">

**Comment by bencroker** [comment]
It looks like your site is not well optimised in terms of element queries, as Blitz is having to keep track of 7,733 entry queries. Please read through the [common issues](https://putyourlightson.com/plugins/blitz#common-issues) section of the docs, in particular [“The refresh cache queue jobs run for long periods of time and sometimes pile up”.](https://putyourlightson.com/plugins/blitz#the-refresh-cache-queue-jobs-run-for-long-periods-of-time-and-sometimes-pile-up)

Are you running a recent version of Blitz? I see that the refresh modes you showed above are not aligned. Can you please submit a diagnostics report in markdown that you can generate from the Blitz Diagnostics utility?

**Comment by Brijeshgrg1999** [comment]
Thank you for your response. so I actually deleted all the previous cached and  currently there is no tracked elements excepts pages. 
here : 
<img width="910" alt="Screenshot 2024-07-11 at 8 57 38 AM" src="https://github.com/putyourlightson/craft-blitz/assets/118506279/16bad614-ff8c-41a9-9276-4fea530cfd2d">

so my concerns is when I update any element its starts to generate the blitz cache in batch like this : 
<img width="1221" alt="Screenshot 2024-07-11 at 8 58 16 AM" src="https://github.com/putyourlightson/craft-blitz/assets/118506279/35806395-9ad1-4444-87d8-20bf24c1363c">

I don't want to generate the blitz cache of all the pages when there is an update or modification and I removed all the config in the blitz.php and i am just referring to cms dashboard here : 
<img width="1407" alt="Screenshot 2024-07-11 at 9 06 09 AM" src="https://github.com/putyourlightson/craft-blitz/assets/118506279/43a82145-18eb-4621-88fe-7fd018df5719">

can u help me to recommend can setting or config so that I can cache the whole site but when there is an any update in entries or element it will only refresh that specific page but  not the whole site .

much appreciate for your help .

**Comment by bencroker** [comment]
I can, but I first need you to submit a diagnostics report in **markdown** that you can generate from the Blitz Diagnostics utility.

![screenshot-00j9Kojv@2x](https://github.com/putyourlightson/craft-blitz/assets/57572400/15adbc77-4bcb-40cb-abff-dc320b8d95d8)

**Comment by bencroker** [comment]
Any update on this, @Brijeshgrg1999 ?

**Comment by Brijeshgrg1999** [comment]
Hi @bencroker  ,  currently its generating cache normally , where previously I had quite a lot of unnecessary tracked elements and queries it was creating cache all the time.  right now everything is working fine 
Thank you

**Comment by bencroker** [comment]
Glad to hear it!
