### ISSUE TITLE
Does Blitz Caching offer support for Graph QL queries?

### ISSUE THREAD

**Issue by boldpaul** [putyourlightson/craft-blitz#685]
### Support Request

Currently using Graph QL on Craft CMS 4.5x to query Nav menu items. Is it possbile for Blitz to cache these items?

Thanks.

### Plugin Version

4.10.0

**Comment by bencroker** [comment]
No, Blitz works with Twig templates only and does not support GraphQL. The GraphQL API has its own mechanism, which might be helpful, see https://craftcms.com/docs/4.x/graphql.html#caching
