### ISSUE TITLE
Entry without URL & template and custom fields doesn't updated until `refreshCacheWhenElementSavedUnchanged` set to true

### ISSUE THREAD

**Issue by Romanavr** [putyourlightson/craft-blitz#686]
### Bug Report

Basically, I have an entry without any custom fields, just the title and that's it.  This entry is referenced in the template via `craft.entries.section()...` and as you can assume, only the title is used from this entry.
![image](https://github.com/user-attachments/assets/84be0c76-352b-4508-a2d4-3a9d34e432d4)

At some point, we noticed that when we updated the title of this entry, the cache was not being updated (queue jobs were spawned and went through without errors). We even tried using blitz source tags, but that didn't help either.
Then I decided to try setting `refreshCacheWhenElementSavedUnchanged` to `true`, and that helped. It looks like you are only checking the changes for customFields/custom attributes but not for the title?

Could you please double-check this? I think `title` should be considered as “element saved with changes”.

#### Application Info

- PHP version: 8.2.19
- Craft edition & version: Pro 4.8.4
- Database driver & version: MySQL 8.0.30

#### Installed Plugins

- Amazon S3: 2.2.1
- Blitz: 4.19.0
- CP Field Inspect: 1.4.4
- Dumper: 5.0.1
- Embedded Assets: 4.1.0
- Hyper: 1.1.32
- ImageOptimize: 4.0.9
- Incognito Field: 1.3.0
- Instagram Feed: 2.2.1
- Mailgun: 3.1.0
- Navigation: 2.0.28
- Neo: 4.2.8
- Prefetch: 2.0.3
- Publisher X: 3.0.1
- Redactor: 3.1.0
- Retour: 4.1.18
- Sentry Logger: 4.1.6
- SEOmatic: 4.1.0
- Super Table: 3.0.14
- Translations: 4.0.2
- Typed link field: 2.1.5
- Vite: 4.0.9

**Comment by Romanavr** [comment]
Looks similar to https://github.com/putyourlightson/craft-blitz/issues/682#issuecomment-2231307625

**Comment by bencroker** [comment]
If an entry’s title is modified then the element is considered changed, so the cached page should be refreshed when you update the title. Can you please check that the page in question is tracking the entry in question using the Blitz Diagnostics tool?

**Comment by Romanavr** [comment]
> If an entry’s title is modified then the element is considered changed, so the cached page should be refreshed when you update the title. Can you please check that the page in question is tracking the entry in question using the Blitz Diagnostics tool?

Thanks for reply.
To add context, I have a `FAQ page` that uses a different section `FAQ categories` section via `craft.entires()...`, as I described earlier.
If I go to Blitz Diagnostics > Tracked Pages -> FAQ **page**, inside it I don't see my FAQ **categories** in the tracked elements, but I do see them in the element queries (FAQ category `sectionId` is listed in the param column).

**Comment by bencroker** [comment]
Can you show me the Twig template code used to fetch and output the FAQ categories on the page?

**Comment by Romanavr** [comment]
> Can you show me the Twig template code used to fetch and output the FAQ categories on the page?

Oh, indeed. 
`{%- set FAQCategories = craft.entries.section('faqCategories').select(['id', 'title']).pairs() -%}
`
I tested regular .one() or .all() and everything works fine. So maybe not a bug at all?

**Comment by bencroker** [comment]
I would expect that to work just fine. Are you saying that it works with `.all()` but not with `.pairs()`?

**Comment by bencroker** [comment]
Yeah I think you’ll need to use `.all()` instead of `.pairs()`, as the latter does not actually populate elements, meaning that Blitz does not know that it should track the elements in question.

**Comment by Romanavr** [comment]
Yea, make senee . thanks for checking it.

**Comment by bencroker** [comment]
Sure thing!
