### ISSUE TITLE
Flushing cache time out on large sites

### ISSUE THREAD

**Issue by bymayo** [putyourlightson/craft-blitz#687]
### Bug Report

When running a flush on the cached pages, the server always seems to timeout, and nothing is actually removed from the `blitz_caches` table

This is a bit more of an issue on large sites, specifically Commerce ones where there are 1,000's of products, but also we have filter menus that are also being cached with query strings.

The table currently has around 30,000 rows, and it just kills the server trying to clear it.

Is there any way around this other than us manually running `DELETE FROM blitz_caches LIMIT 2000` in batches in SQL. It would be good if Blitz could handle the flush as a task or in batches so it does it better, and no timeout happens.

### Diagnostics Report

"craftcms/cms": "4.5.9",
"putyourlightson/craft-blitz": "4.7.1"

PHP 8.1

**Comment by bencroker** [comment]
Blitz [4.16.4](https://github.com/putyourlightson/craft-blitz/blob/4.x/CHANGELOG.md#4164---2024-04-26) improved the deletion of cache records in batches, to avoid database memory issues. I suggest you update to the latest version to get this (and other) improvements. Let me know if that doesn’t solve it for you, but I imagine it will.

**Comment by bymayo** [comment]
@bencroker Ahh okay, gotcha. I already updated so hope that sorts it. I thought the new batch feature was mainly for warming cache, not clearing. So good to hear!

**Comment by bencroker** [comment]
There were a couple of improvements that involved batching, this was one of them.
