### ISSUE TITLE
Deleting entries not clearing cached URIs

### ISSUE THREAD

**Issue by raptureaid** [putyourlightson/craft-blitz#69]
We've been having an issue where deleting an entry is not removing the cached version of the page. The page(s) remain accessible via direct URL. In some cases top level pages using Craft queries to list results are updated to remove the deleted entry and sometimes they are not.

We've tried deleting the browser cache, using incognito mode and separate machines but the page(s) remain. To avoid rebuilding the entire cache, we keep needing to SSH to the server and manually deleting the directories for the _stuck_ pages.

Running version 1.11.4, warm cache automatically is enabled, cache URLs with unique query strings as unique pages with apache server rewrite as outlined in the documentation.

Site | Cache Folder Path | Cached URIs
-- | -- | --
Site A| cache/blitz/sitea | 2558
Site B | cache/blitz/siteb | 100

URI Pattern | Site
-- | --
^about/ | Site A
^directory/.* | Site A
^events/ | Site A
^news/ | Site A
.* | Site B

**Comment by putyourlightson** [comment]
Thanks for reporting this Matthew.

> The page(s) remain accessible via direct URL.

Is this the URL of the entry that appears when you click on the globe icon next to it (and on the share button), or do you generate links to pages using routes?

Can you please create a new entry and test whether it is the same case with it?

**Comment by raptureaid** [comment]
Yes, the URLs of entries are what appear with the globe/share button.

Event entries do use the following route `events/*` to load `events/_entry` template with the following check to redirect expired events:

```
{% set segment2 = 'events/' ~ craft.app.request.getSegment(2) %}
{% set uri = entry.uri ?? '' %}
{% set entry = craft.entries.section('events').uri(uri).status(null).one() %}

{# If event is over redirect to Events page #}
{% if not craft.app.request.isLivePreview and (not entry or entry.status == "expired" or segment2 != uri) %}
  {% redirect 'events' %}
{% endif %}
```

This isn't isolated to the events sections, though, as entries in other sections aren't always removed/refreshed from cache when deleted/modified.

I've tried adding five different new entries across the site and all were correctly updated when content changed and the URLs removed from the cache if the entry expired or was deleted.

In regard to older content, I have tried to re-save by both going into individual entries and saving and going into `Settings >Sections` and re-saving the section to update all entries.

**Comment by putyourlightson** [comment]
So what is the difference between the 5 new entries you created that were successfully updated when content changed, and the older content that is not being updated? If there isn't any discernable difference then it may be worthwhile to clear the entire cache and warm it or let it regenerate itself to ensure that all entries are being correctly tracked in the database.

Regarding your template conditional logic, keep in mind that Blitz will cache the entire page, including any redirecting you might want to happen in other scenarios.

**Comment by raptureaid** [comment]
There's no difference between the entries. I've spent the morning pulling a fresh copy down to a local development machine and am not seeing the same issues. Entries that won't delete from production cache are being removed just fine locally.

I'll try to clear and warm the cache again on production, but do you have any other thoughts/recommendations to continue troubleshooting?

**Comment by putyourlightson** [comment]
If clearing the cache doesn't solve it then perhaps you have a caching layer such as a reverse proxy in front of the site?

**Comment by raptureaid** [comment]
Clearing and rewarming the cache did not solve the issue. It works as intended for a number of entries and then suddenly an entry will not get updated/cleared - limited my focus to events for the moment, so the entries should all be handled the same way.

I'll look into the possibility of an additional caching layer and continue to closely monitor the site. 

Thanks for the support.

**Comment by putyourlightson** [comment]
Sure thing. Keep an eye on the refresh cache jobs to ensure they are being completed successfully. Otherwise, keep me posted on what you find and if there's anything I can do to help.

**Comment by raptureaid** [comment]
Confirmed with the hosting provider that Redis is being used. I'm having another developer who's more adept with Craft look into the possibility there's a conflict somewhere within our site's code/configuration as we're still seeing sporadic occurrences where cached entries are not correctly updated/removed.

**Comment by putyourlightson** [comment]
Ok, let me know how it goes. These things can be quite tricky to track down to a reproduceable set of steps, but if you can find a concrete situation in which it is not working then we can look into it in more detail.

**Comment by raptureaid** [comment]
I've taken some time to examine a number of entries in the database before and after their expiration date has passed. It does appear that the refresh expired cron job is working, but at some point new entries for the expired content are being inserted into the DB.

Here's an example of what I'm seeing occur:

**1. Before expiration**

`craft_blitz_caches`

| id | uri |
| --- | --- |
| 33375 | events/student-recital-20190212-730pm |

`craft_blitz_elementcaches`

| cacheId | elementId | uri |
| --- | --- | --- |
| 31350 | 57633 | events/concerts-and-performances/conservatory-of-music |
| 32471 | 57633 | academics/colleges/conservatory |
| 32657 | 57633 | directory/concert-hall |
| 33278 | 57633 | events/concerts-and-performances |
| 33287 | 57633 | events/concerts-and-performances/conservatory-of-music/student-recitals |
| 33375 | 57633 | events/student-recital-20190212-730pm |
| 33957 | 57633 | events |

`craft_blitz_elementexpirydates`

| elementId | expiryDate |
| --- | --- |
| 57633 | 2019-02-13 05:00:00 |

**2. After expiration**
There are new entries in the DB for the expired entry.

`craft_blitz_caches`

| id | uri |
| --- | --- |
| 35122 | events/student-recital-20190212-730pm |

`craft_blitz_elementcaches`

| cacheId | elementId | uri |
| --- | --- | --- |
| 34345 | 57633 | directory/concert-hall |
| 35007 | 57633 | events/concerts-and-performances |
| 35009 | 57633 | events/concerts-and-performances/conservatory-of-music |
| 35022 | 57633 | events/concerts-and-performances/conservatory-of-music/student-recitals |
| 35122 | 57633 | events/student-recital-20190212-730pm |

_The `events` page is no longer listed, but the entry is still appearing on the page._ 

`craft_blitz_elementexpirydates`
No entry for elementId 57633

**3. Manual resave of the entry**
The expired entry has now been correctly removed from the cache.

`craft_blitz_caches`
No entry for elementId 57633

`craft_blitz_elementcaches`
No entry for elementId 57633

`craft_blitz_elementexpirydates`
No entry for elementId 57633

_A resave of the `events` page will properly remove the expired listing. Rewarming the cache also works, but takes significantly longer to update the entire site as compared to a single entry._

**Comment by putyourlightson** [comment]
Thanks, I’ll look into this and let you know what I find.

**Comment by putyourlightson** [comment]
Just released version 1.11.5 which should address what you've been noticing above.

**Comment by raptureaid** [comment]
Thanks. I'll install the update and watch some entries that are set to expire in the coming days.

**Comment by putyourlightson** [comment]
Ok great.

**Comment by raptureaid** [comment]
It looks like the update is now successfully clearing the entries from the database as the entries I watched were removed from `craft_blitz_caches`, `craft_blitz_elementcaches` and `craft_blitz_elementexpirydates` upon expiration.

However, the actual page caches don't appear to have been properly updated. The page's cached file is still in the folder on the server and related entries (in `craft_blitz_elementcaches`) were not updated to remove the expired entry.

Here's one example of the ten I tracked:

---
events/divas-3-20190216-730pm
Expires: 2/16/2019 9:30 PM

**Pre-expiration**

`craft_blitz_caches`

| id | uri |
| --- | --- |
| 42970 | events/divas-3-20190216-730pm |

`craft_blitz_elementcaches`

| cacheId | elementId | uri |
| --- | --- | --- |
| 42677 | 41598 | events/concerts-and-performances/live-at-lynn |
| 42680 | 41598 | events/concerts-and-performances/live-at-lynn/theatre-series |
| 42970 | 41598 | events/divas-3-20190216-730pm |
| 43959 | 41598 | campus-directory/wold-performing-arts-center |
| 43967 | 41598 | giving/arts-culture/theatre-arts-guild |
| 44267 | 41598 | events |
| 44278 | 41598 | events/concerts-and-performances |

`craft_blitz_elementexpirydates`

| elementId | expiryDate |
| --- | --- |
| 41598 | 2019-02-17 02:30:00 |

**Post-expiration**

`craft_blitz_caches`

Empty

`craft_blitz_elementcaches`

Empty, but entry still appears on:

- events/concerts-and-performances/live-at-lynn
- events/concerts-and-performances/live-at-lynn/theatre-series
- campus-directory/wold-performing-arts-center
- giving/arts-culture/theatre-arts-guild
- events
- events/concerts-and-performances

`craft_blitz_elementexpirydates`

Empty

**Comment by putyourlightson** [comment]
Just ran some tests locally and am not able to replicate this issue. Are you saying then that the page caches are not correctly cleared when an entry expires, but they are when you then save the entry?

**Comment by raptureaid** [comment]
There were a number of events set to expire over the weekend. From what I can tell the cron job that runs hourly worked correctly in terms of removing the entries from the blitz tables in the database.

However they're still appearing on listing pages (those that would be in `craft_blitz_elementcaches`):

![screenshot_2019-02-19 events](https://user-images.githubusercontent.com/5720326/53022822-faf25600-3429-11e9-80cb-fab7d6610bbd.png)


The cached file is still in the directory on the server so it's still resolving the old page when going to the event URL - expired pages should redirect to the top level events page.

Resaving the entries did not correctly update the cache - assuming this is because there are no longer any entries for the pages in the blitz DB tables.

Going to Utilities > Blitz Cache > Warm Blitz Cache did properly flush the files and correctly update the cache. Downside being the entire cache must be purged/rebuilt manually.

**Comment by putyourlightson** [comment]
You said previously that this issue was not happening locally, only on production. I cannot replicate it either, so it would appear to be related to your production server setup. I'm happy to take a closer look if you can send login credentials to info@putyourlightson.net along with a description of steps to replicate the issue. I'd recommend using a test entry and template for this.

Alternatively, Blitz v2 is currently in beta and the release candidate is right around the corner, so you are welcome to try it in the meantime.
https://github.com/putyourlightson/craft-blitz/tree/v2

**Comment by raptureaid** [comment]
Based on what I'm seeing, it may be an order of operations issue when content expires - when the cron job runs to refresh expired cached, the cached files on the server aren't being updated/removed prior to the entries being updated/removed from the database. Once the expired entries have been removed from the blitz DB tables the only way to remove/update the associated cached files is manually delete them from the server or purge and rebuild the entire cache with warm cache.

I'll try to find time to thoroughly test on a local instance again to see if I can replicate the exact issue.

**Comment by putyourlightson** [comment]
Strange, it sounds like it could be a file permission issue, but then again you say that clearing/flushing/warming the cache is resulting in the files being deleted. 

Let me know what you find in your tests locally.

**Comment by putyourlightson** [comment]
Just released Blitz 2 which should resolve this issue. If not then please create a new issue with the steps to reproduce.
