### ISSUE TITLE
Old CSS File Loaded After Deploy

### ISSUE THREAD

**Issue by steve-p96** [putyourlightson/craft-blitz#691]
### Description:

We have encountered an issue for one of our clients where, after deploying css updates, sometimes an old CSS file is loaded. This results in the assets not being displayed correctly. When the same page is opened in Incognito mode, it appears as expected.

Upon inspecting the source code in both normal mode and Incognito mode, we found that different stylesheets are being served.

Here you can see the two diffferent css files

- **Icognito-Mode (working):**

```
<link rel=“stylesheet” href=“/dist/assets/app.9441d7df.css”>
…
<!-- Cached by Blitz on 2024-07-17T09:31:35+02:00 -->
<!-- Served by Blitz on 2024-07-17T15:59:04+02:00 -->
```

- **Normal Browser(not working):**

```
<link rel=“stylesheet” href=“/dist/assets/app.70f9c350.css”>
…
<!-- Cached by Blitz on 2024-07-17T09:31:35+02:00 -->
<!-- Served by Blitz on 2024-07-17T15:59:50+02:00 -->

```
### Questions:

1. How does this happen?
2. Is there any solution to ensure the correct CSS files are served consistently after a deploy?

### Steps to Reproduce:

1. Deploy updated CSS files.
2. Open the website in a normal browser window and note the incorrect CSS.
3. Open the same website in Incognito mode and note the correct CSS.

### Expected Behavior:
The correct CSS file should be loaded consistently across all browsing modes after a deploy.

### Diagnostics Report

Blitz | 3.15.0
PHP version | 8.3.7

**Comment by bencroker** [comment]
Is the `<link>` tag being cached as part of the page or is it being injected on the fly? You can verify this by opening the cache file (assuming you’re using the file cache) in the `cache/blitz` directory. Otherwise I’m not sure how that could happen, unless the browser is caching the response locally?

**Comment by white-lukas** [comment]
Got a likewise issue, I have removed all `includeDynamic` but I keep getting error's in the log
```{
    "dt": "2024-08-05T09:52:10+01:00",
    "level": "Error",
    "message": "Request contained an invalid param.",
    "monolog": {
        "channel": "web",
        "context": {
            "exception": {
                "class": "yii\\web\\BadRequestHttpException",
                "code": 0,
                "file": "/var/www/html/vendor/putyourlightson/craft-blitz/src/controllers/IncludeController.php:51",
                "message": "Request contained an invalid param."
            },
            "memory": 6194936,
            "trace": [
                "#0 /var/www/html/vendor/putyourlightson/craft-blitz/src/controllers/IncludeController.php(39): putyourlightson\\blitz\\controllers\\IncludeController->getRenderedTemplate()",
                "#1 [internal function]: putyourlightson\\blitz\\controllers\\IncludeController->actionDynamic()",
                "#2 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)",
                "#3 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(178): yii\\base\\InlineAction->runWithParams(Array)",
                "#4 /var/www/html/vendor/yiisoft/yii2/base/Module.php(552): yii\\base\\Controller->runAction('dynamic', Array)",
                "#5 /var/www/html/vendor/craftcms/cms/src/web/Application.php(349): yii\\base\\Module->runAction('blitz/include/d...', Array)",
                "#6 /var/www/html/vendor/craftcms/cms/src/web/Application.php(648): craft\\web\\Application->runAction('blitz/include/d...', Array)",
                "#7 /var/www/html/vendor/craftcms/cms/src/web/Application.php(311): craft\\web\\Application->_processActionRequest(Object(craft\\web\\Request))",
                "#8 /var/www/html/vendor/yiisoft/yii2/base/Application.php(384): craft\\web\\Application->handleRequest(Object(craft\\web\\Request))",
                "#9 /var/www/html/web/index.php(13): yii\\base\\Application->run()",
                "#10 {main}"
            ]
        },
        "extra": {
            "project": "scotlandshop",
            "yii_category": "yii\\web\\HttpException:400"
        }
    }
}```

Already cleared and flushes the cache multiple times, in the cached templates, it's not showing the includes anymore,
(Cloudflare cache is also disabled) so looks like it's still cached somewhere locally, I can't replicate it in my browser

**Comment by bencroker** [comment]
This looks like an unrelated issue, @white-lukas. What exactly are you experiencing?

Can you both please try refreshing the cache and seeing if that helps?

**Comment by steve-p96** [comment]
@bencroker thanks for your answer! (:
the link tag is being cached as part of the page and unfortunately refresh of the blitz cache does not help

**Comment by bencroker** [comment]
So are you saying that the "cached on" timestamp is being updated but the link to the CSS file is not? If so, is that link generated as part of the deploy process or somewhere else?

**Comment by steve-p96** [comment]
@bencroker Yes.
The link is generated by the craft vite plugin.

**Comment by steve-p96** [comment]
@bencroker 
We had the same page open in two different browser windows with the same timestamp but with two different versions — one with a link to the old/wrong CSS file and the other with a link to the recent one. And refreshing the page or refreshing the blitz cash had no impact

**Comment by bencroker** [comment]
Can you share a public link to the page in question so I can see the two different versions? If it's sensitive, or if it requires being logged in, please send to support@putyourlightson.com so I can take a closer look.

**Comment by steve-p96** [comment]
@bencroker I´ve sent an email. Thanks for your efforts.

**Comment by bencroker** [comment]
After discussing via email, this appears to have been caused by browser caching, rather than anything to do with Blitz. Will update here if we discover otherwise.
