### ISSUE TITLE
Blitz + Sprig stopped working after updating Blitz version to 5.6.0

### ISSUE THREAD

**Issue by jgpadua** [putyourlightson/craft-blitz#694]
### Bug Report

I'm using Blitz (v5.5.1) and Sprig (v3.1.0) in my project, but after upgrading Blitz to 5.6.0 (and also tested on 5.6.2), my sprig templates started receiving requests in a loop.

In my case, I have pages with multiple sprig components and they are being loaded in a loop, consuming all the memory. It worked okay when downgrading back to 5.5.1.

### Diagnostics Report

Blitz v5.6.0 or v5.6.2
Sprig v3.1.0
Craft v5.2.10

**Comment by bencroker** [comment]
Are you perhaps triggering refreshes of other components from within your components? It sounds like a cyclical request is resulting in an infinite loop. I’m not sure what changed in Blitz 5.6.0 that could possibly have caused this. Are you able to create one or more test components that demonstrate this so I can troubleshoot?

**Comment by jgpadua** [comment]
Forget about it. It was really a loop request. It's weird that this error only appeared now, but I managed to fix the code. Thanks and sorry for the false error.

**Comment by bencroker** [comment]
One of the things that changed in Sprig [3.2.0](https://github.com/putyourlightson/craft-sprig/blob/develop/CHANGELOG.md#320---2024-08-01) is that components now render markup added via `{% html %}`, `{% css %}` and `{% js %}` tags. If you updated to Sprig 3.2.0 or later then perhaps that caused the issue to arise in your codebase. Either way, glad to hear you figured it out!
