### ISSUE TITLE
Generating biltz cache in batch 

### ISSUE THREAD

**Issue by Brijeshgrg1999** [putyourlightson/craft-blitz#695]
### Bug Report

Hi Ben , we have a site with quite large number of webpages and we have been using blitz plugin for a while and also implemented the reverse proxy with cloudflare currently. we are relying on the blitz plugin interface in the cms dashboard to edit the settings of the plugin .

Also few weeks ago we already cached the whole site. 

Is there a reason why the blitz is creating or generating cache in batches most of the time , although we only upload and edit only few webpage  and 
this is what i see usually : 

<img width="2039" alt="Screenshot 2024-08-06 at 11 42 06 AM" src="https://github.com/user-attachments/assets/ce655440-0fea-4c1a-a828-f9d4b77c7735">

These are my current settings in the plugin : 

<img width="1989" alt="Screenshot 2024-08-06 at 11 52 54 AM" src="https://github.com/user-attachments/assets/787d681a-3e24-4c63-8b11-3a3445f79e61">

<img width="1520" alt="Screenshot 2024-08-06 at 11 53 07 AM" src="https://github.com/user-attachments/assets/9c5ca4da-0b85-4f4b-9dad-7d821ed2bec4">

here we reduce the number for concurrency cause the backend was used by few people to upload the articles and contents.

<img width="1817" alt="Screenshot 2024-08-06 at 11 53 25 AM" src="https://github.com/user-attachments/assets/72ff3760-e72b-426e-8992-87ccede381dc">

much appreciated ur support 

### Diagnostics Report

<img width="883" alt="Screenshot 2024-08-06 at 11 51 00 AM" src="https://github.com/user-attachments/assets/c76fe1af-a69d-4d42-85e2-0ff3c42e55c2">

**Comment by bencroker** [comment]
Batch generation was added to help ensure that generating large numbers of pages can be robustly handled by the server. 

The default batch size is `100`, but that doesn’t appear to be the case for you. Can you please check the value of `driverJobBatchSize` in the generated diagnostics report and adjust it if necessary via the [config setting](https://github.com/putyourlightson/craft-blitz/blob/3b5b233d5876a862a70f71f23aa3e8d79357895f/src/config.php#L255C12-L255C30)?

**Comment by bencroker** [comment]
If the batch size is set to `100` then you’re probably running an older version of Craft. Please update both Craft and Blitz and let me know if the issue persists.

**Comment by Brijeshgrg1999** [comment]
Hi thanks for replying , I am running running craft pro 4.8.9  currently not sure if that counts as an older version but i will try to modify the value of batch size in the config setting . 
closing this for now
