### ISSUE TITLE
CSRF input tag calls primary site

### ISSUE THREAD

**Issue by marten-wirelab** [putyourlightson/craft-blitz#697]
### Bug Report

When using `craft.blitz.csrfInput()`, the generated action url calls the primary site instead of the current site, causing CORS issues and inhibiting posting of the form.

I tested this with 4.17.0 and 4.21.0, with no difference.

### Application Info

- PHP version: 8.2.20
- Craft edition & version: Pro 4.10.6
- Database driver & version: MariaDB 10.11.8

### Installed Plugins

- Amazon S3: 2.2.1
- Blitz: 4.17.0
- Cookiebot: 2.1.2
- Embedded Assets: 4.1.0
- Field Manager: 3.0.9
- Freeform: 4.1.19
- Icon Picker: 2.0.18
- Navigation: 2.1.0
- Neo: 4.2.8
- Notifications: 4.1.2
- Redactor: 3.1.0
- Sentry Logger: 4.1.6
- SEO: 4.2.2
- Sherlock: 4.5.0
- Sidebar Entry Types: 2.0.1
- Super Table: 3.0.14
- Typed link field: 2.1.5
- Vite: 4.0.9
- Workflow: 2.0.11

### Loaded Modules

- site-module: modules\sitemodule\SiteModule
- sprig-core: putyourlightson\sprig\Sprig
- blitz-hints: putyourlightson\blitzhints\BlitzHints
- verbb-base: verbb\base\Base

### Blitz Plugin Settings

```json
{
    "debug": false,
    "hintsEnabled": true,
    "cachingEnabled": true,
    "refreshCacheEnabled": true,
    "refreshMode": 3,
    "includedUriPatterns": [
        {
            "uriPattern": ".*"
        }
    ],
    "excludedUriPatterns": [
        {
            "siteId": "",
            "uriPattern": "^\/dynamic\/.*"
        }
    ],
    "cacheStorageType": "putyourlightson\\blitz\\drivers\\storage\\FileStorage",
    "cacheStorageSettings": {
        "folderPath": "@webroot\/cache\/blitz",
        "createGzipFiles": "",
        "createBrotliFiles": ""
    },
    "cacheStorageTypes": [],
    "cacheGeneratorType": "putyourlightson\\blitz\\drivers\\generators\\HttpGenerator",
    "cacheGeneratorSettings": {
        "concurrency": "3"
    },
    "cacheGeneratorTypes": [],
    "customSiteUris": [],
    "cachePurgerType": "putyourlightson\\blitz\\drivers\\purgers\\DummyPurger",
    "cachePurgerSettings": [],
    "cachePurgerTypes": [],
    "deployerType": "putyourlightson\\blitz\\drivers\\deployers\\DummyDeployer",
    "deployerSettings": [],
    "deployerTypes": [],
    "ssiEnabled": false,
    "ssiTagFormat": "<!--#include virtual=\"{uri}\" -->",
    "detectSsiEnabled": true,
    "esiEnabled": false,
    "queryStringCaching": 0,
    "includedQueryStringParams": [
        {
            "queryStringParam": ".*",
            "siteId": ""
        }
    ],
    "excludedQueryStringParams": [
        {
            "queryStringParam": "gclid",
            "siteId": ""
        },
        {
            "queryStringParam": "fbclid",
            "siteId": ""
        }
    ],
    "apiKey": "",
    "generatePagesWithQueryStringParams": true,
    "purgeAssetImagesWhenChanged": true,
    "refreshCacheAutomaticallyForGlobals": true,
    "refreshCacheWhenElementMovedInStructure": true,
    "refreshCacheWhenElementSavedUnchanged": false,
    "refreshCacheWhenElementSavedNotLive": false,
    "cacheNonHtmlResponses": false,
    "trackElements": true,
    "trackElementQueries": true,
    "excludedTrackedElementQueryParams": [],
    "cacheElements": true,
    "cacheElementQueries": true,
    "cacheDuration": null,
    "nonCacheableElementTypes": [
        "craft\\elements\\GlobalSet",
        "craft\\elements\\MatrixBlock",
        "benf\\neo\\elements\\Block",
        "putyourlightson\\campaign\\elements\\ContactElement",
        "Solspace\\Freeform\\Elements\\Submission"
    ],
    "sourceIdAttributes": [],
    "liveStatuses": [],
    "integrations": [
        "putyourlightson\\blitz\\drivers\\integrations\\CommerceIntegration",
        "putyourlightson\\blitz\\drivers\\integrations\\FeedMeIntegration",
        "putyourlightson\\blitz\\drivers\\integrations\\SeomaticIntegration"
    ],
    "defaultCacheControlHeader": "no-store",
    "cacheControlHeader": "public, s-maxage=31536000, max-age=0",
    "cacheControlHeaderExpired": "public, max-age=5",
    "sendPoweredByHeader": true,
    "outputComments": true,
    "refreshCacheJobPriority": 10,
    "driverJobBatchSize": 100,
    "driverJobPriority": 100,
    "queueJobTtr": 300,
    "maxRetryAttempts": 10,
    "maxUriLength": 255,
    "mutexTimeout": 1,
    "commands": [],
    "injectScriptEvent": "DOMContentLoaded",
    "injectScriptPosition": 3
}
```

### Recommendations

- ❌ One or more globals exist and refreshCacheAutomaticallyForGlobals is enabled.
- ❌ Queue jobs are configured to run automatically via web requests.
- ❌ The Blitz Hints utility is reporting 76 eager-loading opportunities.
- ❌ The blitz/cache/refresh-expired console command has not been executed within the past 24 hours.
- ✅ Blitz is configured not to refresh cached pages when an element is saved but unchanged.
- ✅ Blitz is configured not to refresh cached pages when an element is saved but not live.
- ✅ Image transforms are configured to be generated before page load.
- ✅ The @web alias is explicitly defined.
- ✅ The Async Queue plugin is not installed or enabled.

### Site Tracking – REDACTED

- Tracked Pages: 257
- Tracked Includes: 0
- Tracked Query String Params: 0
- Tracked Elements: 1060
- Tracked Element Queries: 312
- Tracked Tags: 1

### Site Tracking – REDACTED

- Tracked Pages: 229
- Tracked Includes: 0
- Tracked Query String Params: 0
- Tracked Elements: 916
- Tracked Element Queries: 269
- Tracked Tags: 1

### Site Tracking – REDACTED

- Tracked Pages: 267
- Tracked Includes: 0
- Tracked Query String Params: 0
- Tracked Elements: 1049
- Tracked Element Queries: 304
- Tracked Tags: 1

### Site Tracking – REDACTED

- Tracked Pages: 220
- Tracked Includes: 0
- Tracked Query String Params: 0
- Tracked Elements: 905
- Tracked Element Queries: 259
- Tracked Tags: 1

### Site Tracking – REDACTED

- Tracked Pages: 311
- Tracked Includes: 0
- Tracked Query String Params: 0
- Tracked Elements: 1426
- Tracked Element Queries: 351
- Tracked Tags: 1

### Site Tracking – REDACTED

- Tracked Pages: 227
- Tracked Includes: 0
- Tracked Query String Params: 0
- Tracked Elements: 977
- Tracked Element Queries: 267
- Tracked Tags: 1

### Site Tracking – REDACTED

- Tracked Pages: 274
- Tracked Includes: 0
- Tracked Query String Params: 0
- Tracked Elements: 1174
- Tracked Element Queries: 312
- Tracked Tags: 1

### Site Tracking – REDACTED

- Tracked Pages: 234
- Tracked Includes: 0
- Tracked Query String Params: 0
- Tracked Elements: 921
- Tracked Element Queries: 274
- Tracked Tags: 1

**Comment by bencroker** [comment]
Are you perhaps using the `@web` alias? As of [Craft 4.11.0](https://github.com/craftcms/cms/releases/tag/4.11.0), Craft warns against using the `@web` alias for URL settings, regardless of whether it was explicitly defined. See https://github.com/craftcms/cms/pull/15347

**Comment by marten-wirelab** [comment]
The baseUrl for each site is set explicitly to an env var (screenshot from Sherlock):
![image](https://github.com/user-attachments/assets/285284cf-9381-4b81-9242-de57924de76b)

I dug into this a bit and what I noticed the correct url is returned when I change the argument for `$useRequestHostInfo` to false in `vendor/craftcms/cms/src/helpers/UrlHelper.php:396`:
```php
return self::_createUrl($path, $params, $scheme, $cpUrl, true, $showScriptName, false);
```

Digging further into the source code, passing true to that argument does seem to fall back on the `@web` alias. But this goes so deep into the internals of Craft that I'm not really sure how to fix this in our code.

**Comment by bencroker** [comment]
As mentioned above, Craft recommends _not_ using the `@web` alias at all (even if explicitly defined), so that the current site is used in action requests. Are you using it or hardcoded values in the environment variables?

See the warning at https://craftcms.com/docs/5.x/system/sites.html#step-1-create-the-site

![screenshot-eFAnSETr@2x](https://github.com/putyourlightson/craft-sprig/assets/57572400/c576c2b5-a842-4c81-9fa3-198e2c03174e)

Also, be sure to update to the latest versions of Craft and Blitz to ensure any related known issues have been addressed.

**Comment by marten-wirelab** [comment]
We've since found out that the problem is not with us using the `@web` variable, but just setting the variable explicitly is enough to cause this problem. It seems that explicitly setting `CRAFT_WEB_URL` will make Craft use that for action urls, even if the base URL for each site is set explicitly.

**Comment by bencroker** [comment]
Thanks for letting me know you figured it out! This recent change to Craft has caused a fair amount of issues, hoping it becomes easier/more intuitive in future.
