### ISSUE TITLE
Issue with expiration date and time zone

### ISSUE THREAD

**Issue by Megafry** [putyourlightson/craft-blitz#698]
### Bug Report

Hi
I've noticed an issue with the cache and its expiration date. It appears that the time zone isn't being respected. For example, the entry was created at 14:13, but the cache record time is 12:13. 
(GMT+2).

Additionally, the expiration date seems incorrect. The cache is not using the entry's specific expiry date but instead defaults to the setting in the configuration. (`'cacheDuration' => 'P1W'`)

Could you please look into this?

- Create a new page
- Add an expired date
- Open the page in the fronted
- Reload the backend 
- Check the status
![image](https://github.com/user-attachments/assets/c84b7e02-67ed-4aad-94ae-f26e5d2365f0)

### Diagnostics Report

Blitz: 4.22.0
CraftCMS: 4.11.0.2

**Comment by bencroker** [comment]
Thanks for reporting this! I fixed the date timezone issue in https://github.com/putyourlightson/craft-blitz/commit/a2cfc8b72990c4e90a612b6c7d4598829f55261a and added the expiry date behaviour you’re describing in https://github.com/putyourlightson/craft-blitz/commit/3a9946fd7f2e5c141b19cf8c17e53f76164dbb4b, both for the next release.

**Comment by bencroker** [comment]
Released in [4.23.0](https://github.com/putyourlightson/craft-blitz/releases/tag/4.23.0) and [5.7.0](https://github.com/putyourlightson/craft-blitz/releases/tag/5.7.0).
