### ISSUE TITLE
Saving an entry clears the entire cache

### ISSUE THREAD

**Issue by shoored** [putyourlightson/craft-blitz#70]
When I update the contents of a page, the entire Blitz cache is cleared. 
This goes for editing cached pages and not-yet cached pages.

On 1.9.0

- Cache a page front-end
- Update the page back-end
- Refreshing and warming cache tasks run
- No new cache files are being generated

So I updated to 1.11.4
- Cache a page front-end
- Update any page back-end
- Entire cache get's cleared
- Refreshing cache task runs
- No warming cache task
- No new cache files are being generated

I'm using the config file. In both CP and config file the `warmCacheAutomatically` is set to true.

**Setup**
- Craft CMS 3.0.37
- Homestead development environment
- PHP 7.2.14
- nginx

**Comment by putyourlightson** [comment]
The functionality has not changed, but the messaging has. You will see a “Refreshing Blitz cache” job after any element is updated in the CMS, which includes warming any pages in the cache that have been cleared. Only cached pages that are affected by an updated element should be cleared, so I’m not sure why or how you’re seeing that the entire cache is cleared. Could you test this out with a brand new entry that is not used in any listing pages and see if that yields the same results?

**Comment by shoored** [comment]
Ah okay, I did not know about the change in messaging. Great.

Hm I created a brand new entry and indeed it's not giving the same results. Some pages did stay cached. I saved another page that is in a structure a few levels deep and not in any main navigation. A few more pages got cleared than I suspected. Might be something else I'm missing. 

Thanks for all the work you put into this - it's a nifty little plugin. 
I'll try some more tests and will get back with a more solid result hopefully. Thanks!

**Comment by shoored** [comment]
Forgot to mention that the cache refresh task is being triggered, but no new cached files appear. Also the DB does not create those caches in `blitz_caches`

**Comment by putyourlightson** [comment]
Updating an entry in a structure can likely cause more than one page to be refreshed, as structured entries have children, parents, siblings, etc.

If you are seeing inconsistencies then I would begin by warming the cache to ensure that Blitz knows which pages are using which entries. If you then come across any concrete problems then please let us know the steps to reproduce and we'll take a closer look.

**Comment by shoored** [comment]
I'm having difficulties getting the site to refresh / warm the caches. 
The issue of clearing the entire cache is indeed probably due to the nature of the site. For instance, they have a giant mega-menu with lots of links. So even editing a simple "About us" page would cause a lot of caches to invalidate, me thinks. 

This might be a difficult site to tackle and maybe I'm not going about it the right way. 

With respect to the cache not warming / refreshing, it's probably better to create a new issue and keep things seperated? Maybe you have some things I can test first before creating another issue.

**Comment by putyourlightson** [comment]
It sounds likely that the mega-menu is causing the clearing of most if not all of the site's pages. If it really becomes an issue then perhaps consider a navigation system that is independent of the entries themselves. There are various ways of going about this, from a dedicated structure for the navigation only, to the navigation plugins that exist in the plugin store.

Yes, please create a new issue for the refresh/warm cache issue. You might consider first installing the [Async Queue](https://github.com/ostark/craft-async-queue) plugin to help prevent timeouts and memory issues and the [Queue Manager](https://github.com/lukeyouell/craft-queue-manager) plugin to see what jobs are in the queue and to manipulate them, if you aren't already.

**Comment by shoored** [comment]
I did a quick test with a navigation plugin and that seems to stop the massive cache clearing. Really great tip. 

The cleared cache items are still not being refreshed/warmed so will create another issue. Have both plugins in place but no clear issues arise.

**Comment by putyourlightson** [comment]
Ok great!

You may want to rewarm the cache after having implementing the navigation plugin to get everything updated. If refreshing the cache still doesn't work then please create a new issue for it.
