### ISSUE TITLE
Make "Exclude URI Patterns" Case Insensitive

### ISSUE THREAD

**Issue by philipboomy** [putyourlightson/craft-blitz#700]
### Bug Report

I think this is a bug. Adding "^my-voucher" in Exclude URI Patterns should prevent pages with "/My-Voucher" getting cached imo however "/My-Voucher" is getting cached. We never know when a website visitor uses uppercases and entering all the potential combinations is impossible. 

#### Application Info

- PHP version: 8.3.8
- Craft edition & version: Pro 4.11.2
- Database driver & version: PostgreSQL 13.15

#### Installed Plugins

- Amazon SES: 2.1.0
- Blitz: 4.22.0
- Campaign: 2.17.3
- Contact Form: 3.1.0
- Control Panel Nav: 4.0.12
- Craft Commerce: 4.6.2
- Google Maps: 4.5.2
- Guest Entries: 4.0.1
- Image Resizer: 3.0.12
- Imager X: 4.4.1
- Preparse: 2.1.2
- Ray: 2.1.1
- Redactor: 3.1.0
- Redirects: 4.1.18
- Scout: 4.1.1
- SEOmatic: 4.1.1
- Sprig: 2.8.1
- Stripe for Craft Commerce: 4.1.2.3
- Twigpack: 4.0.0
- WD: 1.1.2

#### Loaded Modules

- codeeditor: nystudio107\codeeditor\CodeEditor
- sprig-core: putyourlightson\sprig\Sprig
- blitz-hints: putyourlightson\blitzhints\BlitzHints
- verbb-base: verbb\base\Base
- debug: craft\debug\Module

#### Blitz Plugin Settings

```json
{
    "debug": false,
    "hintsEnabled": true,
    "cachingEnabled": false,
    "refreshCacheEnabled": true,
    "refreshMode": 1,
    "includedUriPatterns": [
        {
            "uriPattern": ".*"
        }
    ],
    "excludedUriPatterns": {

        "0": {
            "uriPattern": "^my-voucher"
        },
        "1": {
            "uriPattern": "^My-Voucher"
        }
    },
    "cacheStorageType": "putyourlightson\\blitz\\drivers\\storage\\FileStorage",
    "cacheStorageSettings": {
        "folderPath": "@webroot\/cache\/blitz",
        "compressCachedValues": ""
    },
    "cacheStorageTypes": [],
    "cacheGeneratorType": "putyourlightson\\blitz\\drivers\\generators\\HttpGenerator",
    "cacheGeneratorSettings": {
        "concurrency": "3"
    },
    "cacheGeneratorTypes": [],
    "customSiteUris": [],
    "cachePurgerType": "putyourlightson\\blitz\\drivers\\purgers\\DummyPurger",
    "cachePurgerSettings": [],
    "cachePurgerTypes": [],
    "deployerType": "putyourlightson\\blitz\\drivers\\deployers\\DummyDeployer",
    "deployerSettings": [],
    "deployerTypes": [],
    "ssiEnabled": false,
    "ssiTagFormat": "<!--#include virtual=\"{uri}\" -->",
    "detectSsiEnabled": true,
    "esiEnabled": false,
    "queryStringCaching": 2,
    "includedQueryStringParams": [
        {
            "queryStringParam": ".*"
        }
    ],
    "excludedQueryStringParams": {
        "0": {
            "queryStringParam": "gclid"
        },
        "2": {
            "queryStringParam": "page"
        }
    },
    "apiKey": "",
    "generatePagesWithQueryStringParams": true,
    "purgeAssetImagesWhenChanged": true,
    "refreshCacheAutomaticallyForGlobals": true,
    "refreshCacheWhenElementMovedInStructure": true,
    "refreshCacheWhenElementSavedUnchanged": false,
    "refreshCacheWhenElementSavedNotLive": false,
    "cacheNonHtmlResponses": false,
    "trackElements": true,
    "trackElementQueries": true,
    "excludedTrackedElementQueryParams": [],
    "cacheElements": true,
    "cacheElementQueries": true,
    "cacheDuration": null,
    "nonCacheableElementTypes": [],
    "sourceIdAttributes": [],
    "liveStatuses": [],
    "integrations": [
        "putyourlightson\\blitz\\drivers\\integrations\\SeomaticIntegration"
    ],
    "defaultCacheControlHeader": "no-store",
    "cacheControlHeader": "public, s-maxage=31536000, max-age=0",
    "cacheControlHeaderExpired": "public, max-age=5",
    "sendPoweredByHeader": true,
    "outputComments": true,
    "refreshCacheJobPriority": 10,
    "driverJobBatchSize": 100,
    "driverJobPriority": 100,
    "queueJobTtr": 300,
    "maxRetryAttempts": 10,
    "maxUriLength": 255,
    "mutexTimeout": 1,
    "commands": [],
    "injectScriptEvent": "DOMContentLoaded",
    "injectScriptPosition": 3
}
```

#### Recommendations

- ❌ One or more globals exist and refreshCacheAutomaticallyForGlobals is enabled.
- ❌ Queue jobs are configured to run automatically via web requests.
- ❌ The Blitz Hints utility is reporting 45 eager-loading opportunities.
- ❌ The blitz/cache/refresh-expired console command has not been executed within the past 24 hours.
- ✅ Blitz is configured not to refresh cached pages when an element is saved but unchanged.
- ✅ Blitz is configured not to refresh cached pages when an element is saved but not live.
- ✅ Image transforms are configured to be generated before page load.
- ✅ The @web alias is explicitly defined.
- ✅ The Async Queue plugin is not installed or enabled.

#### Site Tracking 

- Tracked Pages: 0
- Tracked Includes: 0
- Tracked Query String Params: 0
- Tracked Elements: 0
- Tracked Element Queries: 0
- Tracked Tags: 0

**Comment by bencroker** [comment]
Technically speaking, `/my-voucher` and `/My-Voucher` are different URIs. 

This question was answered and suggestions were provided in https://github.com/putyourlightson/craft-blitz/issues/623#issuecomment-1969071678. Let me know if any of them work for you.

**Comment by philipboomy** [comment]
Thanks. That all makes sense and your proposed solution will sort this. 

Tried searching for closed issues but missed this one.
