### ISSUE TITLE
Refresh Cached URLs not working.

### ISSUE THREAD

**Issue by wolispace** [putyourlightson/craft-blitz#701]
### Support Request

I tried to refresh a cached url using the "Refresh Cached URLs" via /utilities/blitz-cache

The url was https://www.environment.sa.gov.au/topics/coasts/adelaide-central-beaches-update

Looking in the blitz folder I see the index.html file has yesterdays date before I execute the command.

Running the command did not modify the file or change its date.

I manually renamed the file to OLD_index.html and revisited the page. Sure enough that did the trick:

```
-rw-r--r--  1 apache apache 43486 Aug 22 13:34 index.html
-rw-r--r--  1 apache apache 42587 Aug 21 16:02 OLD_index.html
```
File permissions look right to me.

Looking in the blitz log file I see my requests to rebuild had "completed successfully":

```
[2024-08-22 13:25:33] Cached URLs successfully refreshed. [via cache utility by "wallace.mcgee@sa.gov.au"]
[2024-08-22 13:31:00] Cached URLs successfully refreshed. [via cache utility by "wallace.mcgee@sa.gov.au"]
```

So my questions are:
1. Are there any more diagnostics I can do to find out why the index.html is not being deleted and re-created when run "Refresh Cached URLs"?
2. Why does the log show it succeeded when the file was not modified?

**Comment by wolispace** [comment]
Its all good.. I now see we refresh expired pages on a cron job so every half hour.

So clicking that button simply adds it to a queue - which I assume editing and Saving also did.

Would be wonderful if clicking that "Refresh Cached URLs" jumped the queue and worked straight away: deleting the inde.html

**Comment by bencroker** [comment]
Refreshing URLs (and all forms of refreshing) respects the Refresh Mode plugin setting. Clicking on Refresh Expired afterwards should have the desired effect.
