### ISSUE TITLE
Meaning of defaultCacheControlHeader

### ISSUE THREAD

**Issue by deeekay** [putyourlightson/craft-blitz#704]
### Support Request

Hi there

In the blitz config, there are several variables related to the cache control header. Namely, we know of the following variables:
- `defaultCacheControlHeader`
- `cacheControlHeader`
- `cacheControlHeaderExpired`

Now, my understanding is, that `defaultCacheControlHeader` will be used in case no other information is provided. However, when I check the cache control header of cached pages in our project, it seems the s-maxage is set to 365 days (which corresponds to `cacheControlHeader`). What is the usage of `defaultCacheControlHeader`.

In general, I think it would greatly help, if those variables and their usage were documented more extensively (optimally with concrete examples).

Thanks a lot and best regards,
Daniel

### Plugin Version

4.22.0

**Comment by bencroker** [comment]
Thanks for your suggestion! I’ve clarified the meanings of each of those settings. Generally speaking, they shouldn’t need to ever be updated, hence I don’t see a need to provide examples.

https://github.com/putyourlightson/craft-blitz/blob/60c36dd65f354829f56acad05e0d559841f902ab/src/config.php#L231-L238

The value of `defaultCacheControlHeader` is used for non-cached pages. I admit that the naming isn’t great, it was supposed to indicate the default behaviour, when Blitz is not involved in sending a cached response.

**Comment by deeekay** [comment]
Ok. I like that they should not be changed at all 😊 

However, wouldn't it make sense to return a maxage based on the information (if available) how long a page should be cached. If there is  a page has a cache time of one hour and the first response suggests to the browser, the maxage is 365 days, I could imagine that the page does not get refreshed in time since the browser has no indication to refresh the page accordingly. Or am I missing something?

**Comment by bencroker** [comment]
The max age directive (`s-maxage=31536000`) is for shared cache stores (reverse proxy CDNs) only. Blitz handles refreshing those cached stores during its cache refresh process.

Note that I did spot a potential issue while inspecting the default values and have addressed this for the next release.

**Comment by deeekay** [comment]
Does this also apply for max-age (without "s" 😊 )? I was under the impression that the "s" stands for shared. However, we observe a Cache-Control header that says `public, max-age=31536000`

**Comment by bencroker** [comment]
This was addressed in [4.23.0](https://github.com/putyourlightson/craft-blitz/releases/tag/4.23.0) and [5.7.0](https://github.com/putyourlightson/craft-blitz/releases/tag/5.7.0). After updating and refreshing the cache, you should see the more explicit `public, s-maxage=31536000, max-age=0`, which is what it originally was but was changed to the less verbose value a few versions ago.

**Comment by deeekay** [comment]
Ah, thanks for the hint. Just for clarification: Was that change just cosmetics or could it really impact how browsers handle caching on their end? (My expectation would be the latter 😊 )

**Comment by bencroker** [comment]
The intention of the change was to maintain the same functionality, i.e. that only shared stores would cache pages. On reading the `cache-control` specification, however, it appeared that `public` means any store (shared or private) rather than explicitly public, hence the decision to revert that change. Apologies if it caused confusion or negatively impacted your use of the plugin.

**Comment by bencroker** [comment]
@deeekay as a follow-up, please see this [article on the cache control header issue](https://putyourlightson.com/articles/critical-update-for-a-blitz-blunder).

**Comment by thijskaspers** [comment]
> @deeekay as a follow-up, please see this [article on the cache control header issue](https://putyourlightson.com/articles/critical-update-for-a-blitz-blunder).

Thanks for catching and fixing this @bencroker! We couldn't put our finger on all sorts of vague issues that popped up last week, why we were seeing things our client did not see and vice versa :sweat_smile:.. for example a searchbar that gave a result for us but 0 results for them with the exact same query (and cache cleared).
