### ISSUE TITLE
Error on install: Calling unknown method: yii\console\Response::redirect()

### ISSUE THREAD

**Issue by Jensderond** [putyourlightson/craft-blitz#705]
### Bug Report

Upon installing version 5.7.0 we got this error:

```Calling unknown method: yii\console\Response::redirect()```

<img width="1499" alt="image" src="https://github.com/user-attachments/assets/60de6305-bc46-44bc-aa07-843e085103d5">

### Diagnostics Report

This should probably already be enough

**Comment by bencroker** [comment]
Thanks for reporting that! Fixed in https://github.com/putyourlightson/craft-blitz/commit/4d2f4dba6b3d4e6cb4cf01e7cfa8c3ff54fefd37 and released in [5.7.1](https://github.com/putyourlightson/craft-blitz/releases/tag/5.7.0).
