### ISSUE TITLE
Show guest user a full cached page and logged-in user a page with sprig components

### ISSUE THREAD

**Issue by gddotorg** [putyourlightson/craft-blitz#707]
### Support Request

I currently have the following challenge: In principle, for example, the homepage is currently cached and dynamic content is loaded via Sprig. This applies to all visitors to the website.

Now my customer wants guest users to get a completely cached page and only logged-in users to load the dynamic content. However, if I check `{% if currentUser %}` inside a regular twig template, it's going to be cached by Blitz and everyone is shown what was cached on the first call. So I have to make the currentUser check in the Sprig component, right? Is there another solution here? I have also looked at Dynamic Content from Blitz. But I also have the same issue there.

Goal is to avoid dynamic calls, when user is not logged-in.

Thanks in advanced.

### Versions
- Blitz version: 4.23.0
- Sprig version: 2.13.0
- Craft version:  4.11.5

### Plugin Version

4.23.0

**Comment by bencroker** [comment]
To know whether the user is logged-in requires a dynamic request – there’s no way around it. 

It sounds like, in your current setup, the homepage is cached and the dynamic request happens in the background, which is ideal. Is there a specific issue you or your client are trying to address?

**Comment by gddotorg** [comment]
@bencroker Thanks for your fast response.

For example we have a personalised slider. Depending on user group and flags we set, they get a different slider with products fitting more to the user. This slider is currently a sprig component. Inside the sprig component we also a fallback for guest users and their are shown defined product. So every guest user sees the same result. Now the idea was to outsource the guest user code and make it part of the cached page version. 

In general the website has a lot of traffic and we have had performance issues in the past. It does not come directly from the templates themselves. We also have processes that run in the background and can overload the database at some point. 

Should the website ever be down, for example because the database is overloaded, the idea was to at least present a complete cached website to users who are not logged in (Majority of users).

However, Sprig or Dynamic Content generate queries to the database, which cannot be processed if the database is overloaded. If you don't see any other option to split this up by checking the currentUser inside the twig template, I would communicate this to my customer.

**Comment by bencroker** [comment]
It sounds like you have bigger issues if your database gets overloaded to the point that it can’t handle requests.

The approach I would take is to have Sprig output the guest version of the slider and refresh the component on page load. You can then run the check for `currentUser` and if one doesn’t exists, set the swap strategy to `none`. See [`sprig.reswap(value)`](https://putyourlightson.com/plugins/sprig#sprig-reswapvalue) and [`hx-swap`](https://htmx.org/attributes/hx-swap/) swap. So it could look something like the following.

```twig
{{ sprig('_components/slider.twig', {}, { 's-trigger': 'load' }) }}
```

```twig
{# _components/slider.twig #}

{% if sprig.isInclude %}
    {# Guest version #}
{% else %}
    {% if currentUser %}
        {# User version #}
    {% else %}
        {% do sprig.reswap('none') %}
    {% endif %}
{% endif %}
```
