### ISSUE TITLE
Warming job contains duplicates and empties?

### ISSUE THREAD

**Issue by michaelroper** [putyourlightson/craft-blitz#71]
Hey Ben, not sure if this is an actual plugin issue, setup issue, or just me not understanding how its working... but I have noticed that when I warm my site (about 288 entries), the url object in the job that it puts in the queue has those 288 entries listed twice, plus for every one of those 288 entries, there seems to also be 2 urls of just the root url. So that url object in the job has like 288*4 urls in it to warm.. does that seem odd?

**Comment by putyourlightson** [comment]
Thanks Michael, that does seem odd and I’ll look into it. Which branch and version are you seeing this behaviour on?

**Comment by michaelroper** [comment]
I've got `2.0.0-beta.6` running. Fwiw, after the job is finished, it still only says total cached pages is the 288..

**Comment by putyourlightson** [comment]
Ok thanks, I’ll let you know what I find.

**Comment by putyourlightson** [comment]
I wasn't able to reproduce this locally, but have added some code to ensure that the warmed URLs are unique in `2.0.0-beta.6.1`. Can you please check if that makes any difference?

**Comment by michaelroper** [comment]
Will give it a shot tomorrow and let you know, thanks.

Was also thinking - how does it handle entries in sections (or categories groups too?) that have no url pattern associated with them? I have a bunch of those...

**Comment by putyourlightson** [comment]
Great!

Provided they are being output on any page in the site, they will be associated with that page's URL. So it should invalidate them as needed.

**Comment by michaelroper** [comment]
Are those likely to be the phantom urls then? Though it did seem coincidental that the total number was 4x my entry count...

**Comment by putyourlightson** [comment]
Perhaps.

**Comment by michaelroper** [comment]
Hey Ben - that update didn't seem to make a difference to the number of urls in the job. Is there any better way that I could debug it to see what it is trying to warm?

**Comment by putyourlightson** [comment]
How exactly are you viewing the URLs in the warm job? And can you send an example?

**Comment by michaelroper** [comment]
From the job output in https://github.com/lukeyouell/craft-queue-manager - will drop you a screenshot on Discord

**Comment by putyourlightson** [comment]
Should be fixed in v2.0.0-beta.6.2, thanks again for reporting this!

**Comment by michaelroper** [comment]
Cheers mate, will give it a shot!

**Comment by michaelroper** [comment]
Yep, that is much better! CP queue job is no longer showing blank or duplicate urls, and the CLI output total number doesn't wildly jump around.
```
./craft blitz/cache/warm
Clearing Blitz cache.
Flushing Blitz cache.
Warming Blitz cache.
0% (0/291) ETA: n/a   
0% (1/291) ETA: 580 sec.   
0% (2/291) ETA: 580 sec.   
1% (3/291) ETA: 580 sec.   
1% (4/291) ETA: 580 sec.   
1% (5/291) ETA: 580 sec.   
2% (6/291) ETA: 114 sec.   
2% (7/291) ETA: 114 sec.   
...
99% (290/291) ETA: 2 sec.   
100% (291/291) ETA: 2 sec.   
Blitz cache successfully warmed 288 files.
Commands accomplished, great!
```

Side note though: when running `./craft clear-caches/all`, it's now showing the following error:
```
Clearing cache: Blitz cache
Error clearing cache Blitz cache: Calling unknown method: putyourlightson\blitz\services\ClearCacheService::clear()
```

**Comment by putyourlightson** [comment]
Great, thanks! I'll fix that last issue for the next release, which will likely be a release candidate.
