### ISSUE TITLE
Eagerly hint on user

### ISSUE THREAD

**Issue by rgauthier4c4** [putyourlightson/craft-blitz#710]
I have a blitz hint that is showing in my project and it seems like a false/positive when i'm querying the author of an entry.

Please provide a clear and concise description of what the bug is, including:
- Steps to reproduce the issue.

1. In an entry template, display the full name of the author : {{ entry.author.fullName }}
2. In the control panel, a blitz hint appear : Eager-load the relation field : {% set result = entry.fieldHandle.eagerly().all() %}
3. Add the eagerly function to the author in twig : Calling unknown method: craft\elements\User::eagerly()

- A clear and concise description of what you expected to happen.

CraftCms hasn't added the eagerly method to the users. Blitz should not raise a hint on this type of content.

- The plugin and Craft version numbers.

Craft cms : 5.4.1
Blitz : 5.7.1

**Comment by bencroker** [comment]
Thanks for reporting this! Fixed in https://github.com/putyourlightson/craft-blitz/commit/9794b6f29d574e6d8e3412361ee036f329d62651 for the next release.

**Comment by bencroker** [comment]
Released in [5.8.0](https://github.com/putyourlightson/craft-blitz/releases/tag/5.8.0).

**Comment by MattWilcox** [comment]
Ha! I hit this last week and hadn't been able to work out why what I was doing was wrong yet... that explains it :D Thanks both!
