### ISSUE TITLE
Redirecting to cache path that doesn't exist

### ISSUE THREAD

**Issue by rellafella** [putyourlightson/craft-blitz#711]
### Bug Report

I have query string caching enabled. It doesn't look like any query string directories are being created on the disc however we are getting blitz entries created in the database that contain query strings.

When a user visits a page with a query string `/foo?bar=1` they are redirected to `/cache/blitz/www.example.com/bar=1/index.html.gz?bar=1`

It seems to be unreliable as to whether I am served the page or a 404 as a result of the redirect.

#### Application Info

- PHP version: 8.0.30
- Craft edition & version: Pro 4.11.5
- Database driver & version: MariaDB 10.11.8

#### Installed Plugins

...
- Blitz: 4.23.0
...

#### Blitz Plugin Settings

```json
{
    "debug": false,
    "hintsEnabled": true,
    "cachingEnabled": true,
    "refreshCacheEnabled": true,
    "refreshMode": 1,
    "includedUriPatterns": [
        {
            "uriPattern": ".*"
        }
    ],
    "excludedUriPatterns": [
        {
            "uriPattern": "^feeds\/.*"
        },
        {
            "uriPattern": "^pdf\/.*"
        }
    ],
    "cacheStorageType": "putyourlightson\\blitz\\drivers\\storage\\FileStorage",
    "cacheStorageSettings": {
        "folderPath": "@webroot\/cache\/blitz",
        "compressCachedValues": "1"
    },
    "cacheStorageTypes": [],
    "cacheGeneratorType": "putyourlightson\\blitz\\drivers\\generators\\HttpGenerator",
    "cacheGeneratorSettings": {
        "concurrency": "3"
    },
    "cacheGeneratorTypes": [],
    "customSiteUris": [],
    "cachePurgerType": "putyourlightson\\blitz\\drivers\\purgers\\DummyPurger",
    "cachePurgerSettings": [],
    "cachePurgerTypes": [],
    "deployerType": "putyourlightson\\blitz\\drivers\\deployers\\DummyDeployer",
    "deployerSettings": [],
    "deployerTypes": [],
    "ssiEnabled": false,
    "ssiTagFormat": "<!--#include virtual=\"{uri}\" -->",
    "detectSsiEnabled": false,
    "esiEnabled": false,
    "queryStringCaching": 1,
    "includedQueryStringParams": [
        {
            "queryStringParam": ".*"
        }
    ],
    "excludedQueryStringParams": [
        {
            "queryStringParam": "gclid"
        },
        {
            "queryStringParam": "fbclid"
        }
    ],
    "generatePagesWithQueryStringParams": true,
    "purgeAssetImagesWhenChanged": true,
    "refreshCacheAutomaticallyForGlobals": true,
    "refreshCacheWhenElementMovedInStructure": true,
    "refreshCacheWhenElementSavedUnchanged": false,
    "refreshCacheWhenElementSavedNotLive": false,
    "cacheNonHtmlResponses": false,
    "trackElements": true,
    "trackElementQueries": true,
    "excludedTrackedElementQueryParams": [],
    "cacheElements": true,
    "cacheElementQueries": true,
    "cacheDuration": 0,
    "nonCacheableElementTypes": [],
    "sourceIdAttributes": [],
    "liveStatuses": [],
    "integrations": [
        "putyourlightson\\blitz\\drivers\\integrations\\CommerceIntegration",
        "putyourlightson\\blitz\\drivers\\integrations\\FeedMeIntegration",
        "putyourlightson\\blitz\\drivers\\integrations\\SeomaticIntegration"
    ],
    "defaultCacheControlHeader": "no-store",
    "cacheControlHeader": "public, s-maxage=31536000, max-age=0",
    "cacheControlHeaderExpired": "public, s-maxage=5, max-age=0",
    "sendPoweredByHeader": true,
    "outputComments": true,
    "refreshCacheJobPriority": 10,
    "driverJobBatchSize": 100,
    "driverJobPriority": 100,
    "queueJobTtr": 300,
    "maxRetryAttempts": 10,
    "maxUriLength": 255,
    "mutexTimeout": 1,
    "commands": [],
    "injectScriptEvent": "DOMContentLoaded",
    "injectScriptPosition": 3
}
```

#### Recommendations

- ❌ One or more globals exist and refreshCacheAutomaticallyForGlobals is enabled.
- ❌ The Blitz Hints utility is reporting 27 eager-loading opportunities.
- ❌ The Async Queue plugin is installed and enabled.
- ❌ The blitz/cache/refresh-expired console command has not been executed within the past 24 hours.
- ✅ Blitz is configured not to refresh cached pages when an element is saved but unchanged.
- ✅ Blitz is configured not to refresh cached pages when an element is saved but not live.
- ✅ Image transforms are configured to be generated before page load.
- ✅ The @web alias is explicitly defined.
- ✅ Queue jobs are configured not to run automatically via web requests.

#### Site Tracking 

- Tracked Pages: 1314
- Tracked Includes: 0
- Tracked Query String Params: 54
- Tracked Elements: 2963
	- craft\elements\Asset: 1,753
	- craft\elements\Entry: 1,110
	- craft\elements\Category: 98
	- craft\elements\Tag: 2
- Tracked Element Queries: 1492
	- craft\elements\Entry: 1,490
	- craft\elements\Category: 2
- Tracked Tags: 0

**Comment by bencroker** [comment]
Blitz doesn't ever redirect the browser to cached paths. Have you perhaps set up server redirects incorrectly? That might help explain those unexpected redirects.

**Comment by rellafella** [comment]
this might not be helpful without context of the rest of the config but these are the rewrite rules we have in place for Blitz
```apache
  #- Blitz cache rewrite for gzip files
  RewriteCond %{DOCUMENT_ROOT}/cache/blitz/%{HTTP_HOST}/%{REQUEST_URI}/%{QUERY_STRING}/index.html.gz -s
  RewriteCond %{HTTP:Accept-encoding} gzip
  RewriteCond %{REQUEST_METHOD} GET
  RewriteCond %{QUERY_STRING} !token= [NC]
  RewriteRule .* /cache/blitz/%{HTTP_HOST}/%{REQUEST_URI}/%{QUERY_STRING}/index.html.gz [L]

  #- AddEncoding allows you to have certain browsers uncompress information on the fly.
  AddEncoding gzip .gz

  #- Serve correct content types, and prevent mod_deflate double gzip.
  RewriteRule \.html\.gz$ - [T=text/html,E=no-gzip:1]

  #- Blitz cache rewrite
  RewriteCond %{DOCUMENT_ROOT}/cache/blitz/%{HTTP_HOST}/%{REQUEST_URI}/%{QUERY_STRING}/index.html -s
  RewriteCond %{REQUEST_METHOD} GET
  RewriteCond %{QUERY_STRING} !token= [NC]
  RewriteRule .* /cache/blitz/%{HTTP_HOST}/%{REQUEST_URI}/%{QUERY_STRING}/index.html [L]

  # Send would-be 404 requests to Craft
  RewriteCond %{REQUEST_FILENAME} !-f
  RewriteCond %{REQUEST_FILENAME} !-d
  RewriteCond %{REQUEST_URI} !^/(favicon\.ico|apple-touch-icon.*\.png)$ [NC]
  RewriteRule (.+) index.php?p=$1 [QSA,L]
```

**Comment by bencroker** [comment]
That all appears fine to me. Can you share a URL to a page on which this issue can be observed, or alternatively send to support@putyourlightson.com?

**Comment by rellafella** [comment]
After a bit more investigating we have a higher level rule in our apache config where we are converting urls to lowercase. We implemented this because Blitz treats urls as case sensitive and will create duplicate results with varying cases.
```apache
RewriteMap lowercase int: tolower
# Skip urls that have file extensions
RewriteCond %{REQUEST_URI} !\. (css|jpe?g|js|json|png|svg|woff2?|ttf|otf|ico)$ [NC]
# Skip urls that are in cpresources, dist or assets
RewriteCond %{REQUEST_URI} !\/(cpresources|dist|assets)\/ [NC]
# Target any urls with capitals
RewriteCond %{REQUEST_URI} [A-Z]
# Convert request URI to lowercase
RewriteRule (.*) ${lowercase:$1} [R=301, L]
```

**Comment by bencroker** [comment]
Based on this, as well as the URL you sent via email, it seems as though this rewrite rule is being problematic. My guess is that disabling resolves the issue.

As a side note, I believe your rewrite rule to convert to lowercase should use `tolower`:

```
RewriteRule (.*) ${tolower:$1} [R=301,L]
```

Interestingly, the next version of Blitz 5 will include a setting to only cache lowercase URIs.

![screenshot-upF9VHGJ@2x](https://github.com/user-attachments/assets/a5ca9622-dc04-4e31-b1e7-b2c51cc10aa5)
