### ISSUE TITLE
Caches page/entry not updating after content changes.

### ISSUE THREAD

**Issue by benjam-es** [putyourlightson/craft-blitz#712]
### Bug Report

When updating and saving entries, the cached page does not update. Blitz is setup to use file cache, and I have tried multiple settings within refresh mode all with the same result.

This image is the same before and after updated the page. I visit the page in a chrome incognito mode to ensure it is unrelated to being logged in as admin.

<img width="622" alt="Screenshot 2024-09-12 at 14 19 18" src="https://github.com/user-attachments/assets/67358f75-0a1e-4f90-9bb6-1f837b801ac9">

#### Application Info

- PHP version: 8.1.29
- Craft edition & version: Pro 4.12.2
- Database driver & version: MySQL 8.0.33

#### Installed Plugins

- Amazon S3: 2.2.1
- Asset Rev: 7.0.0
- Asset Usage: 3.3.0
- Blitz: 4.23.0
- Calendar: 5.0.8
- Control Panel CSS: 2.6.0
- Cookies: 4.0.1
- Field Manager: 3.0.9
- Formie: 2.1.29
- Imager X: 4.4.1
- Inventory: 3.2.0
- LJ Range Slider: 4.0.1
- Maps: 4.0.8
- Minify: 4.0.1
- Mix: v1.7.1
- Preparse: 2.1.2
- Redactor: 3.1.0
- Redactor Custom Styles: 4.0.3
- Redirects: 4.1.19
- SEO Settings: 4.1.3
- Sprig: 2.13.0
- Super Table: 3.0.14
- Typed link field: 2.1.5
- Wordsmith: 4.5.0

#### Loaded Modules

- codeeditor: nystudio107\codeeditor\CodeEditor
- sprig-core: putyourlightson\sprig\Sprig
- blitz-hints: putyourlightson\blitzhints\BlitzHints
- verbb-base: verbb\base\Base

#### Blitz Plugin Settings

```json
{
    "debug": false,
    "hintsEnabled": true,
    "cachingEnabled": true,
    "refreshCacheEnabled": true,
    "refreshMode": 2,
    "includedUriPatterns": [
        {
            "siteId": "",
            "uriPattern": ".*"
        }
    ],
    "excludedUriPatterns": [
        {
            "siteId": "",
            "uriPattern": "event\/ics\/.*"
        }
    ],
    "cacheStorageType": "putyourlightson\\blitz\\drivers\\storage\\FileStorage",
    "cacheStorageSettings": {
        "folderPath": "@webroot\/cache\/blitz",
        "compressCachedValues": "1"
    },
    "cacheStorageTypes": [],
    "cacheGeneratorType": "putyourlightson\\blitz\\drivers\\generators\\HttpGenerator",
    "cacheGeneratorSettings": {
        "concurrency": 1
    },
    "cacheGeneratorTypes": [],
    "customSiteUris": [],
    "cachePurgerType": "putyourlightson\\blitz\\drivers\\purgers\\DummyPurger",
    "cachePurgerSettings": [],
    "cachePurgerTypes": [],
    "deployerType": "putyourlightson\\blitz\\drivers\\deployers\\DummyDeployer",
    "deployerSettings": [],
    "deployerTypes": [],
    "ssiEnabled": false,
    "ssiTagFormat": "<!--#include virtual=\"{uri}\" -->",
    "detectSsiEnabled": true,
    "esiEnabled": false,
    "queryStringCaching": 0,
    "includedQueryStringParams": [
        {
            "siteId": "",
            "queryStringParam": ".*"
        }
    ],
    "excludedQueryStringParams": [
        {
            "siteId": "",
            "queryStringParam": "gclid"
        },
        {
            "siteId": "",
            "queryStringParam": "fbclid"
        }
    ],
    "apiKey": "",
    "generatePagesWithQueryStringParams": true,
    "purgeAssetImagesWhenChanged": true,
    "refreshCacheAutomaticallyForGlobals": true,
    "refreshCacheWhenElementMovedInStructure": true,
    "refreshCacheWhenElementSavedUnchanged": false,
    "refreshCacheWhenElementSavedNotLive": false,
    "cacheNonHtmlResponses": false,
    "trackElements": true,
    "trackElementQueries": true,
    "excludedTrackedElementQueryParams": [],
    "cacheElements": true,
    "cacheElementQueries": true,
    "cacheDuration": null,
    "nonCacheableElementTypes": [],
    "sourceIdAttributes": [],
    "liveStatuses": [],
    "integrations": [
        "putyourlightson\\blitz\\drivers\\integrations\\CommerceIntegration",
        "putyourlightson\\blitz\\drivers\\integrations\\FeedMeIntegration",
        "putyourlightson\\blitz\\drivers\\integrations\\SeomaticIntegration"
    ],
    "defaultCacheControlHeader": "no-store",
    "cacheControlHeader": "public, s-maxage=31536000, max-age=0",
    "cacheControlHeaderExpired": "public, s-maxage=5, max-age=0",
    "sendPoweredByHeader": true,
    "outputComments": true,
    "refreshCacheJobPriority": 10,
    "driverJobBatchSize": 100,
    "driverJobPriority": 100,
    "queueJobTtr": 300,
    "maxRetryAttempts": 10,
    "maxUriLength": 255,
    "mutexTimeout": 1,
    "commands": [],
    "injectScriptEvent": "DOMContentLoaded",
    "injectScriptPosition": 3
}
```

#### Recommendations

- ❌ Image transforms are configured not to be generated before page load.
- ❌ One or more globals exist and refreshCacheAutomaticallyForGlobals is enabled.
- ❌ The Blitz Hints utility is reporting 85 eager-loading opportunities.
- ✅ Blitz is configured not to refresh cached pages when an element is saved but unchanged.
- ✅ Blitz is configured not to refresh cached pages when an element is saved but not live.
- ✅ The @web alias is not used in the base URL of any sites.
- ✅ Queue jobs are configured not to run automatically via web requests.
- ✅ The Async Queue plugin is not installed or enabled.
- ✅ The blitz/cache/refresh-expired console command has been executed within the past 24 hours.

#### Site Tracking [1]

- Tracked Pages: 77
- Tracked Includes: 0
- Tracked Query String Params: 0
- Tracked Elements: 702
	- craft\elements\Asset: 381
	- craft\elements\Entry: 264
	- craft\elements\Category: 54
	- verbb\formie\elements\Form: 3
- Tracked Element Queries: 63
	- craft\elements\Entry: 56
	- craft\elements\Category: 5
	- Solspace\Calendar\Elements\Event: 1
	- verbb\formie\elements\Form: 1
- Tracked Tags: 0

#### Site Tracking [2]

- Tracked Pages: 8
- Tracked Includes: 0
- Tracked Query String Params: 0
- Tracked Elements: 71
	- craft\elements\Asset: 36
	- craft\elements\Entry: 33
	- craft\elements\Category: 2
- Tracked Element Queries: 2
	- craft\elements\Entry: 2
- Tracked Tags: 0

**Comment by benjam-es** [comment]
Using background queue and selecting the 'clear' option with queued jobs for refresh mode seems to work

**Comment by bencroker** [comment]
It looks like you had the refresh mode set to `Expire the cache and regenerate in a queue job`, which means that cached pages will be expired but not cleared until the regenerate cache job is completed.

**Comment by benjam-es** [comment]
With expire, and the refresh expires cron job running, this still doesn't update the content @bencroker

**Comment by bencroker** [comment]
In that case, it could be a bug. Let me know if you want to pursue using expiring of the cache instead of clearing, providing a demo site page so I can replicate this locally.
