### ISSUE TITLE
Blitz entry sidebar widget metadata when Blitz is used exclusively as a reverse proxy purger

### ISSUE THREAD

**Issue by kylecotter** [putyourlightson/craft-blitz#718]
### Feature Request

Our typical setup consists of using Blitz exclusively as a reverse proxy purger for Cloudflare (same approach as outlined in #502) using the DummyStorage driver.

The recent introduction of the element sidebar widget looks to be a useful tool for helping content editors understand cache status, but doesn’t provide any meaningful data when used with the DummyStorage driver (which makes sense).

Was wondering how feasible it would be to get some of that useful metadata stored without actually having a File or YiiCache driver in use.

Bonus if the Refresh button that shows in the sidebar widget could trigger a Cloudflare purge for that URL.

Thanks for any insight, Ben!

### Plugin Version

5.9.0

**Comment by bencroker** [comment]
Blitz cannot know whether a page is actually cached without having a cache storage driver to check. That means that I should probably remove the sidebar panel when the `DummyStorage` driver is being used. Sorry, but I don’t really see a way around this limitation.

**Comment by bencroker** [comment]
Added in https://github.com/putyourlightson/craft-blitz/commit/7d0b29dde3902ff8302eb274b7f119ef69ab914e for the next release.

**Comment by bencroker** [comment]
Released in [5.9.1](https://github.com/putyourlightson/craft-blitz/releases/tag/5.9.1). Thanks for reporting this!
