### ISSUE TITLE
Site root caching issue? 

### ISSUE THREAD

**Issue by rw-ninety** [putyourlightson/craft-blitz#719]
### Support Request

I've been trying to solve this issue in my multi-site setup (Craft CMS 4, latest version of all), but I must be missing something. Hopefully, you can help me figure this out.

The problem occurs when I use locales in the site URLs. For example:

- https://www.extralingo.com/en (default site)
- https://www.extralingo.com/nl

and so on...

The pages are cached correctly for all sites, and it works beautifully. However, there's a problem with the default site: cached pages are also being served for URLs without the locale, which shouldn't happen. For example:

- https://www.extralingo.com/en/language-schools/spanish/spain/barcelona (this URL is correct and gets cached, which is great)
- https://www.extralingo.com/language-schools/spanish/spain/barcelona (this URL should return a 404 or be handled by Craft, but instead, it serves the cached page)

When Blitz is disabled, the correct behavior happens—my Twig code properly redirects to the correct URL. But when Blitz is enabled, it serves the cached page for the URL without the locale, even though this variant doesn't exist in the file system on the server. Only the version under the /en folder is present.

Am I missing a configuration step?

Here's my standard Nginx config:

Normal nginx config: 
set $cache_path false;
if ($request_method = GET) {
    set $cache_path /cache/blitz/$host/$uri/index.html;
}
if ($args ~ "token=") {
    set $cache_path false;
}

# Modified root location block with Blitz cache
location / {
     try_files $cache_path $uri $uri/ /index.php?$query_string;
}

**Comment by bencroker** [comment]
Please show me how you perform the redirect and provide a plugin version number so I can test locally.

**Comment by rw-ninety** [comment]
Thanks for the prompt reply and sure, please find the redirect below. However, I don't think the redirect is that relevant because it does not get executed because of the cached page being served. Redirect: 

```twig
{% if craft.app.request.segments|length > 0 and siteUrl not in craft.app.request.absoluteUrl %}
    {% if entry is defined %}
        {% redirect entry.url 301 %}
    {% elseif category is defined %}
        {% redirect category.url 301 %}
    {% endif %}
{% endif %}
```

Craft CMS version: 4.12.6.1
Plugin version: 4.23.2
Probably not that relevant, but I also have Cache Igniter (1.2.0) installed. 

If there is anything else you need, please let me know.

**Comment by bencroker** [comment]
You should really avoid using `craft.app.request.absoluteUrl` on cacheable pages, since it can introduce a cache poisoning attack. See https://docs.craftcms.com/api/v5/craft-web-request.html#method-getabsoluteurl

I suggest you perform the redirect at the web server config level, rather than via Craft, since Craft anyway shouldn’t be handling requests that are for no particular site. Does that make sense?

**Comment by rw-ninety** [comment]
Thanks for the heads up, I was not aware of this one. I managed to fix it like you suggested, and after all it was maybe a more relevant question for Craft CMS itself. Thanks.

**Comment by bencroker** [comment]
Glad to hear it!
