### ISSUE TITLE
Updating global variable deleted all cached files

### ISSUE THREAD

**Issue by Djive** [putyourlightson/craft-blitz#72]
We have `Warm Cache Automatically` setting turned OFF.
We have /config/blitz.php with `'warmCacheAutomaticallyForGlobals' => false,` in it.

We thought that with those settings, Blitz would take no action when global is saved.
But instead, after saving global variable, all cached files were deleted.

Does it depend on some other factors?
Thanks!

Craft Pro 3.1.8
Blitz 1.11.4

**Comment by putyourlightson** [comment]
Warming the cache means that URLs are requested after being cleared so that the cache exists when the next user visits the site. 
The cache is still cleared when a global is saved, regardless of the warm cache setting values. Make sense?

**Comment by putyourlightson** [comment]
The reason for this is that globals are available and potentially used in every template. In order to be sure that the pages that use them are fresh, the plugin must clear the entire cache.

**Comment by Djive** [comment]
Yes, makes sense.
Thanks for clearing it up!
Great plugin and great support!

**Comment by putyourlightson** [comment]
Sure thing!

**Comment by Djive** [comment]
Just one more question :)

Would it be possible to only clear files from the site where the global was saved?

Since we have 130 sites in our multisite setup, and globals are only used on their sites (globals on site A are used only on site A) it would be a huge deal to not delete all files from all sites but just the one where global was saved.

Thanks again!

**Comment by putyourlightson** [comment]
Sure, will add this to the feature list for the next major release which is v2.0.0.

**Comment by Djive** [comment]
Thanks!
