### ISSUE TITLE
Neither the property "getTemplate" nor one of the methods exist and have public access

### ISSUE THREAD

**Issue by kaspar-allenbach** [putyourlightson/craft-blitz#720]
### Support Request

1. Migrated tfrom craft 4 to 5.4.8
2. I load some snippet: 

`{{ craft.blitz.getTemplate ("_atoms/shopCartTab") }}`

> Neither the property "getTemplate" nor one of the methods "getTemplate()", "getgetTemplate()"/"isgetTemplate()"/"hasgetTemplate()" or "__call()" exist and have public access in class "putyourlightson\blitz\variables\BlitzVariable".

In the doc's this still exists: https://putyourlightson.com/plugins/blitz#craft-blitz-gettemplate

What's the catch here?

Initially I ran into this issue: https://github.com/putyourlightson/craft-blitz/issues/668

Only a reinstallation of the Blitz Plugin helped. But I don't think that's related

Thank you

### Plugin Version

5.9.0

**Comment by bencroker** [comment]
As per the [docs](https://putyourlightson.com/plugins/blitz#craft-blitz-gettemplate):

> This function was deprecated in Blitz 4.3.0 and removed in 5.0.0. The [includeDynamic()](https://putyourlightson.com/plugins/blitz#craft-blitz-includedynamic) function should be used instead.
