### ISSUE TITLE
craft.blitz.csrfInput() never retrieves csrf token

### ISSUE THREAD

**Issue by dgrigg** [putyourlightson/craft-blitz#721]
### Bug Report

In our staging environment I can see the call to retrieve the token and the response. In our production environment the call never goes out to get the token. Everything between the two environments is identical, not idea why this is failing. 

### Diagnostics Report

php 8.3.6
craft 5.4.6 pro 
blitz 5.9.0

**Comment by bencroker** [comment]
Some sites that load JavaScript libraries that mess with the DOM have been experiencing this issue. I’m working on a fix but in the meantime can you please change [this config setting](https://github.com/putyourlightson/craft-blitz/blob/03f2fd7c1efcf51a0e8b8e2b3bd9f7e92baec3b3/src/config.php#L289) to `load`, then clear the cache and see if that helps?

```php
'injectScriptEvent' => 'load',
```

**Comment by dgrigg** [comment]
That worked. 

For your info this only happened when we upgraded from Craft 4 to Craft 5. The front end code never changed. Using AlpineJS.

**Comment by bencroker** [comment]
Improved in https://github.com/putyourlightson/craft-blitz/commit/ecbcff2ff968e58f04d9acf7c232cba0ad5273cf and and released in [5.9.1](https://github.com/putyourlightson/craft-blitz/releases/tag/5.9.1). You should be able to revert the config setting back to what it previously was, or leave it as is. Thanks again for reporting!
