### ISSUE TITLE
getSsi Tag error

### ISSUE THREAD

**Issue by jan-dh** [putyourlightson/craft-blitz#725]
### Bug Report

I get this error:
```
putyourlightson\blitz\variables\BlitzVariable::getSsiTag(): Argument #3 ($includeId) must be of type int, null given, called in /app/vendor/putyourlightson/craft-blitz/src/variables/BlitzVariable.php on line 227
```

On this bit
```
 {{craft.blitz.includeCached ('_blitz/main_nav', {menu:'main_nav'})}}
 ```
 
 Error appears after upgrading to last Blitz version.
 

### Diagnostics Report

PHP 8.2
Craft CMS: 4.12.8
Blitz 4.23.3

**Comment by bencroker** [comment]
Can you please check for an error in the `storage/logs/blitz-*` logs related to this?

**Comment by jan-dh** [comment]
Was a deploy error; fixed after redeploy
