### ISSUE TITLE
Setup Cloudflare Purger

### ISSUE THREAD

**Issue by kaspar-allenbach** [putyourlightson/craft-blitz#726]
### Support Request

I noticed that in the Cloudflare settings, the E-Mail is gone. Is it no longer necessary?

Also no value is accepted in ZONE ID. (also no direct string without the env variable)

![Bildschirmfoto 2024-10-31 um 10 11 40](https://github.com/user-attachments/assets/3bdf5f0e-d111-421c-9c75-8e079dc083e0)

Any Idea where to look?

### Plugin Version

5.9.1

**Comment by bencroker** [comment]
The email field is not shown when "API Token" is selected. Can you double check that the API token entered is correct?

**Comment by kaspar-allenbach** [comment]
jup it was the wrong authentication method. Selecting API Key solves the error
