### ISSUE TITLE
How to resolve stuck Refreshing Blitz cache task in queue

### ISSUE THREAD

**Issue by Djive** [putyourlightson/craft-blitz#73]
The `Refreshing Blitz cache` is just sitting in the queue and not progressing.
Attempt  = 1, Fail = 0, Progress = 0
When we delete this one, the next one also just sits and doesn't move from Progress = 0.
If the next task in queue is for example `Generating pending image transforms`, it finishes in seconds and then again all queue gets stuck on next `Refreshing Blitz cache` task.
It was working normally in the start, not sure what triggered this block.

Found some "deadlock" and "memory exhausted" errors in the phperrors.log

Next yii\db\Exception: SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction
The SQL being executed was: DELETE FROM `craft_blitz_caches` WHERE (`siteId`=119) AND (`uri`='site/entry-url') in /home/site/vendor/yiisoft/yii2/db/Schema.php:664

Is there something we can do to fix the stuck Blitz tasks in queue?

Thanks!

Craft Pro 3.1.8
Blitz 1.11.4

**Comment by putyourlightson** [comment]
I'm not sure why this might be happening. I would recommend using the [Async Queue](https://github.com/ostark/craft-async-queue) plugin to help prevent timeouts and memory issues and the [Queue Manager](https://github.com/lukeyouell/craft-queue-manager) plugin to see what jobs are in the queue and to manipulate them, if you aren't already.

If you cancel the refresh cache jobs and then resave an entry then does it just get stuck again?

What is your `concurrency` setting set to? Perhaps it is too high.

**Comment by Djive** [comment]
Already using both plugins.
Most of the times, if I press "Retry" in Queue Manager plugin, it doesn't help, just remains on 0% endlessly.
Sometimes it just randomly starts working again, if I remove all the tasks from queue and come back later, I see new `Refreshing Blitz cache` tasks running normally in queue.
`concurrency` setting is set to 10 at the moment. Will lover it to see if it helps.

**Comment by putyourlightson** [comment]
Yeah perhaps 5 is a safer value to use. It sounds like the the PHP process is getting stuck while executing the task. Unfortunately there's not much to do here besides ensure that the server has enough resources available (see this [guide](https://craftcms.com/guides/resolving-stalled-background-tasks)).

**Comment by Djive** [comment]
Lowered the setting to 5, but it didn't help. 
Lowered to 1 now and will test some more.

We are continuing to raise our server settings also.
max_execution_time = 4200
memory_limit = 3560M

Our `craft_blitz_elementcaches` table in database has ~225,158,229 rows and size of 18.5 GiB.
But when I check the Blitz Cache in Utilities, number of Cached URIs across all 130 sites is less than 200.
Is this as it should be?

Also continuing to get errors like these:

```
[22-Feb-2019 06:51:25 Europe/Zagreb] An Error occurred while handling another error:
PDOException: SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction in /home/site/vendor/yiisoft/yii2/db/Command.php:1290

Next yii\db\Exception: SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction
The SQL being executed was: DELETE FROM `craft_blitz_caches` WHERE (`siteId`=119) AND (`uri`='aaa/bbb') in /home/site/vendor/yiisoft/yii2/db/Schema.php:664

Previous exception:
PDOException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '90659-197260' for key 'craft_blitz_elementcaches_cacheId_elementId_unq_idx' in /home/site/vendor/yiisoft/yii2/db/Command.php:1290

Next yii\db\IntegrityException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '90659-197260' for key 'craft_blitz_elementcaches_cacheId_elementId_unq_idx'
The SQL being executed was: INSERT INTO `craft_blitz_elementcaches` (`cacheId`, `elementId`) VALUES (90659, 197260), ... 
```
(the amount of these numbers is 2 pages long so I had to shorten this last part for readability)

Thanks!

**Comment by putyourlightson** [comment]
That is a massive number of rows in the `craft_blitz_elementcaches` table! If those 200 entries exist for all 130 sites then we're talking about 26,000 elements. As this is a rather extreme case of multi site, my recommendation is to wait for the upcoming version 2, which is currently in beta and offers more fine-grained tuning for refreshing the cache. If you would like to contribute feature requests then now would be the time as the release candidate is right around the corner.
https://github.com/putyourlightson/craft-blitz/tree/v2

**Comment by Djive** [comment]
There is over 3000 cached pages now displayed in Utilities.
But the table now has little less rows (~223,948,422) and same size of 18.5 GiB.

Is this the total cache ever recorded for all sites? 
Does this table ever clears (for example if there is a complete cache clear due to editing a global variable)?

Thanks!

**Comment by Djive** [comment]
Not all entries are always published on all sites, most entries only exists on 1 site.

Cache worked normally in start, even automatic refreshing of the cache after published entry.
Now, even with `concurrency` set to 1, it doesn't work.
Now we are even seeing multiple fails on one `Refreshing Blitz cache` tasks in queue.

Would it help if we did a `Flush Blitz Cache` often?
Guessing that publishing globals and entries only clears and refreshes the cache, but does not flush it?

**Comment by putyourlightson** [comment]
Flushing the cache should not have to be done often. The rows in the `craft_blitz_elementcaches` table keep track of what elements are used on what pages. They are regenerated when the cache is refreshed. 

If you wanted to do some detective work, you could look at the `craft_blitz_elementcaches` along with the the `craft_blitz_caches` table to try and figure out why so many elements are being stored, but your best bet is probably to look in your templates for unnecessary or exaggerated fetching of elements. This could happen if for example you list many entries on each page using a navigation menu or a similar entries section. As I said, with version 2 you will have much more control and predictable cache invalidation.

What errors are you seeing for the failed jobs? The log files should reveal more useful information than the Queue Manager plugin.

**Comment by Djive** [comment]
Not seeing any info about failed `Refreshing Blitz cache` tasks in queue.log but at around the same time of last task I see some errors in phperrors.log, and those are almost always the same:

```
[25-Feb-2019 09:18:17 Europe/Zagreb] An Error occurred while handling another error:
PDOException: SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction in /home/site/vendor/yiisoft/yii2/db/Command.php:1290 ......

Next yii\db\Exception: SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction
The SQL being executed was: DELETE FROM `craft_blitz_caches` WHERE (`siteId`=119) AND (`uri`='aaa/bbb') in /home/site/vendor/yiisoft/yii2/db/Schema.php:664 ......

Previous exception:
PDOException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '123822-497702' for key 'craft_blitz_elementcaches_cacheId_elementId_unq_idx' in /home/site/vendor/yiisoft/yii2/db/Command.php:1290

Next yii\db\IntegrityException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '123822-497702' for key 'craft_blitz_elementcaches_cacheId_elementId_unq_idx'
The SQL being executed was: INSERT INTO `craft_blitz_elementcaches` (`cacheId`, `elementId`) VALUES (123822, 497702), (123822, 14) ......
```
(the amount of these values in the end is 2 pages long so I had to shorten this last part for readability)

Looking forward to version 2 and in meantime we will check to see if the code can be more optimized.

Thanks!

**Comment by putyourlightson** [comment]
Thanks for the details. I've noted the errors and will ensure they are fixed/avoided in version 2.
