### ISSUE TITLE
Missing content on page excluded from caching

### ISSUE THREAD

**Issue by flannelinc** [putyourlightson/craft-blitz#732]
### Support Request

I have a site that utilizes Blitz caching along with Cloudflare. We have a couple content blocks on the home page that are set up to display content randomly from a Super Table field. The standard caching set up did not allow the content from those fields to change with page refresh, so we decided to just exclude the home page from caching. I know there are ways exclude just parts of the page, but we needed a quick fix. This set up worked fine for a while, but then we started having an issue where the editable content on the home page disappeared. The only solution is to go to the Blitz cache section in the utilities and clear the cache for just that page and it immediately fixes the issue. I'm baffled because this page is not cached through Blitz. This site is for a fairly large non-profit and the giving season is quickly appraoching, so hopefully we can get this figured out asap. Thanks in advance! p.s.- current version is 4.23.5, but I did just update it now. It was recently on 4.23.3.

### Plugin Version

4.23.5

**Comment by bencroker** [comment]
> The only solution is to go to the Blitz cache section in the utilities and clear the cache for just that page and it immediately fixes the issue.

This would indicate that the page (or part of it) is being cached by Blitz. Can you share a Blitz diagnostics utility report here or via email to support@putyourlightson.com and I’ll see if I can spot anything obvious?

**Comment by flannelinc** [comment]
Hi Ben,
Thank you so much for the quick response. Attached is the diagnostics report and our blitz.php file.

Thanks,
Dennis

******
Dennis Derammelaere
Creative and Technical Director
Flannel :: www.flannelbrand.com
415-704-5561

**Comment by bencroker** [comment]
Nothing attached, Dennis. Can you please paste into the GitHub issue?

**Comment by flannelinc** [comment]
Here you go. I had to change the config file to .txt in order to upload. Thanks!
[diagnostics-report.md](https://github.com/user-attachments/files/17689587/diagnostics-report.md)
[blitz.txt](https://github.com/user-attachments/files/17689590/blitz.txt)

**Comment by bencroker** [comment]
Everything looks pretty much standard in there. Next time the content doesn’t appear, can you please verify whether the page is cached by Blitz by looking for the [timestamp comment](https://putyourlightson.com/plugins/blitz#debugging) in the source code, and looking for a `cf-cache-status: HIT` response header, which indicates whether Cloudflare has cached the page. If you email me the link immediately once the issue resurfaces, I’ll take a look, but otherwise I’m not sure what to suggest.

**Comment by flannelinc** [comment]
Thank you so much for your willingness to help with this. I just looked at the pages on the site and all but the home page currently have the Blitz timestamp comment. I'm quite baffled by what is going on since the home page is definitely not being cached by Blitz, but when this issue happens, clearing the Blitz cache for that page fixes the issue. I will let you know ASAP when this happens again. Thanks again!

**Comment by bencroker** [comment]
Sure thing!
