### ISSUE TITLE
Index page of upcoming event entries not refreshing upon an expired event

### ISSUE THREAD

**Issue by eclectiv** [putyourlightson/craft-blitz#738]
### Support Request

I have an index page of event entries that publish upcoming events. I have a date field (`endDate`) that controls whether an event is expired, and I have a query param like the following that generates the upcoming events entries:

```
{% set eventsQueryParams = {
	section:		'events',
	endDate:    ('>=' ~ now|date('Y-m-d'))
}
%}
```
The issue I'm having is that if an upcoming event entry becomes a past event, the index page doesn't refresh. I have to manually refresh the page cache. From what I read, Blitz should take care of this automatically rather than setting a cron job to refresh the event index page cache.

If this indeed the case, is there something I'm missing that enables the cache of the index page to automatically refresh upon an event entry that expires?

### Plugin Version

4.23.2

**Comment by bencroker** [comment]
Blitz will track the `endDate` field, but unlike an entry post date or expiry date, it cannot know to check whether cached pages have expired based on a custom field. What you’ll need to do, is either set the duration of the index page cache to X number of hours using the `cacheDuration` option in the [page specific options](https://putyourlightson.com/plugins/blitz#page-specific-options), or manually set an expiry date. Set `cacheDuration` to `P1D` for one day, or `PT12H` for twelve hours. Or, if you need it to be more accurate and you‘re ok with writing some Twig logic, set the `expiryDate` option to the end date of the earliest event.

```twig
{% do craft.blitz.options.cacheDuration('PT12H') %}
```

```twig
{% do craft.blitz.options.expiryDate(earliestEvent.endDate) %}
```

Note that in addition to the above, you’ll also need a [cron job](https://putyourlightson.com/plugins/blitz#cron-jobs) to refresh the expired cached pages on a scheduled interval

**Comment by eclectiv** [comment]
Thanks, Ben! For event type entries where there may be an index page to show upcoming events and another index page to show past events, I guess it would have been easier to just use the Expiry Date instead of a custom end date field. Good to know for future reference.

**Comment by bencroker** [comment]
Agreed.
