### ISSUE TITLE
How to cache JSON

### ISSUE THREAD

**Issue by hiasl** [putyourlightson/craft-blitz#739]
### Support Request

Hi Ben,
we want to introduce a feature where we can render all HTML pages in a certain JSON format. This is realized using a custom route with the normal URL and ".json" at the end. We then generate the JSON with TWIG, set the correct mime type and deliver it. In our current setup Blitz however caches the page like this <whatever.json>/index.html and therefor it is not sent with a JSON mime type anymore.

I found this issue https://github.com/putyourlightson/craft-blitz/issues/443 where you wrote a fix, but in my case it has the same behaviour, although we are on a later version. I did not find anything in the docs pointing me in the right direction.

So my questions:
- Is it possible to cache my .json requests 
- If yes, how can I enable it?

Thanks

### Plugin Version

4.23.7

**Comment by bencroker** [comment]
Can you send me a sample template so I can test locally?

**Comment by matuzo** [comment]
In our routes.php we have:

```
<?php
return [
  '<shareSlug:{slug}>.json' => ['template' => '_entry-json.twig']
];

```

In _entry-json.twig:

```
{% header "Content-Type: application/json; charset=utf-8" -%}

{
    "title": "this is just a test"
}
```

That should be enough to reproduce it. On the first visit you get a JSON file but on all consecutive visits it's HTML.

**Comment by bencroker** [comment]
It works as expected in my local tests. Can you please double check that you’ve enabled the [`cacheNonHtmlResponses`](https://github.com/putyourlightson/craft-blitz/blob/219826db4aceae37e6b3f374455e893d3549b8dc/src/config.php#L207) config setting?

Keep in mind that if you’re using [server rewrites](https://putyourlightson.com/plugins/blitz#server-rewrites), you may need to configure your web server to set the appropriate content type for URIs ending in `.json`.

**Comment by matuzo** [comment]
`cacheNonHtmlResponses` wasn't enabled, thanks, but enabling it didn't change anything. @hiasl, do you think that server rewrites can be an issue?

**Comment by hiasl** [comment]
I double checked @matuzo's try and it also does not work for me with `cacheNonHtmlResponses` enabled.

But maybe our expectations are wrong:
- We actually checked the blitz cache directory after having requested the JSON URL and were looking for a `.json` File in the Cache Dir.
- e.g. when requesting `/this/is/mysample.json` we would expect to see this file `<docRoot>/cache/blitz/our.domain/this/is/mysample.json `
- instead we found `<docRoot>/cache/blitz/our.domain/this/is/mysample.json/index.html`
- and if what we found was actually correct, then maybe @bencroker means that the content type needs to be set based on the requested URI, not the file actual file found....

**Comment by bencroker** [comment]
> maybe @bencroker means that the content type needs to be set based on the requested URI, not the file actual file found....

Yes, the content type should be set based on the URI.

**Comment by hiasl** [comment]
so this cache file `<docRoot>/cache/blitz/our.domain/this/is/mysample.json/index.html` for a JSON is expected?

**Comment by bencroker** [comment]
Yes, because server rewrites always map to the URI path with a `/index.html` suffix.

**Comment by hiasl** [comment]
Then this is the reason for us to believe it does not work. Thanks

P.S.: I am not sure if `cacheNonHtmlResponses` is in your docs, I just found it in the src/ config. I think there is also no hint in the docs for the additional server rewrite, I guess it will be rather similar to the gzip extras.

**Comment by bencroker** [comment]
Great! The docs don’t cover every config setting, instead they say:

> All available settings are listed and documented in the [config file](https://github.com/putyourlightson/craft-blitz/blob/develop/src/config.php).
