### ISSUE TITLE
Respect isSystemLive setting

### ISSUE THREAD

**Issue by carlcs** [putyourlightson/craft-blitz#74]
It would be nice if the plugin would respect Craft’s `isSystemLive` setting. Nothing you can do when server rewrites are used, but I would like to use Blitz over PHP in a staging environment where `isSystemLive` is set to false.

**Comment by putyourlightson** [comment]
It should already respect the `isSystemLive` setting by outputting a 503 error to non-logged in users, provided server rewrites are not being used. Are you seeing otherwise?

**Comment by carlcs** [comment]
Yes I do indeed, with Blitz 1.11.5. I removed the server rewrites on the staging server, but seems like Blitz is doing its thing before Craft has a chance to enforce the `isSystemLive` rule.

**Comment by putyourlightson** [comment]
In Craft 3.1?

**Comment by carlcs** [comment]
3.1.12, will update to latest in a minute and will let you know if this helps.

**Comment by putyourlightson** [comment]
Ok yes, I see how this might happen now when the page has already been cached. I'll add a fix for this in v2. Thanks!
