### ISSUE TITLE
includedQueryStringParams first Approach when try to cache pages with query strings.

### ISSUE THREAD

**Issue by amici-infotech** [putyourlightson/craft-blitz#740]
### Feature Request

First of all, Blitz works great and I love it. in blitz, you can do almost anything that is needed to cache a page. i have just 1 feature request that could be possibly already there but maybe i dont know about that.

So I generally use it with `queryStringCaching` to `1` (Cache URLs with query strings as unique pages)
in that, i pass `.*` in `includedQueryStringParams` and pass params that not needed in `excludedQueryStringParams` that works where for all query params its a new cached page except the ones i pass in exclude list.

but, due to that, when bot hits the site, it generates thousands of new cached pages versions of single page. For example,

`/abc` is one page. now bot attacks with diff query params.
```
/abc?43243=
/abc?43244=
/abc?43245=
...
```

these all should be 1 page but due to our config, it creates new cache each time.

### Tried Solution
So i thought lets reverse this to fix the issue where 
`excludedQueryStringParams` has `.*` and
`includedQueryStringParams` has all the queryParams that we use in our site. sounds simple and doable but when I do that, it doesnt work at all. All query params are excluded because i have `.*` and none of included settings works. then i saw the code and it made it clear to me.

In `vendor/putyourlightson/craft-blitz/src/services/CacheRequestService.php` file under function `getIsAllowedQueryStringParam`, we have exclude code first (line 612 to 615) and include code after (line 617 to 620) as per that, if exclude items matched, it wont go to check for include items. when i switch places for both, my config worked. but i guess that wont be the right way to fix it.

### Requesting feature.
Can we add a feature where you add a setting for exclude first vs include first? and adjust code based on that? that way if someone like me wants only the query params that site uses to be included, we can do that easily?

### Plugin Version

4.23.4

**Comment by amici-infotech** [comment]
ok. so turned out that i could achieve this directly via config file. so there are 3 scenarios.

1. pre decided query param found in url, cache page as new page
2. pre decided query param found in url, not cache the page
3. rest query params to serve cached page and ignore any query param that is not in the decided list.

I just achieved it like this:

> Never ever put `.*` in `includedQueryStringParams`. thats a worst way to setup caching and invites bots to fill server space and database with millions of unused cached pages.

now, on solutions:
1. pre decided query param found in url, cache page as new page
```
'queryStringCaching' => 1,
'includedQueryStringParams' => [
    [
        'siteId' => '',
        'queryStringParam' => 'category',
    ],
]
```

2. pre decided query param found in url, not cache the page
```
'queryStringCaching' => 1,
'excludedUriPatterns' => [
    [
        'siteId' => '',
        'uriPattern' => 'q=',
    ],
],
'includedQueryStringParams' => [
    [
        'siteId' => '',
        'queryStringParam' => 'q',
    ],
]
```
3. rest query params to serve cached page and ignore any query param that is not in the decided list.
this is auto achieve by above setup where we dont pass `.*` in `includedQueryStringParams`

**Comment by bencroker** [comment]
Glad to see you figured it out!
