### ISSUE TITLE
Warning: unlink(/var/www/[...]/web/cache/blitz/domain.tld/path/index.html): No such file or directory

### ISSUE THREAD

**Issue by ul8** [putyourlightson/craft-blitz#741]
### Support Request

We're getting a ton of errors in our logs like the above (I replaced some parts with dummy data)

This can amount to thousands of such errors per day.

We saw the issue first on Craft 4 but it persists after just having updated to Craft 5, so it seems to be independent of specific versions.

Here's the stack trace from Sentry
<img width="602" alt="image" src="https://github.com/user-attachments/assets/22574c7d-cf54-4a29-8f1d-601bb2ca45bf">

It looks this is triggered by a queue refreshSiteUris job. I don't understand though why Blitz would be trying to delete files that do not exist. I can only imagine that it would happen across deployments / releases (i. e. if we replace the craft directory in our build script and files get lost) but this seems to happen even when the last release is days old.

Any other ideas where this could originate from? 

At the moment it's  eating up our Sentry quota so that's a bit annoying :)

Thanks!

**Comment by bencroker** [comment]
Can you show me the specific exception being thrown? And what versions of Blitz and Craft is the site running?

**Comment by ul8** [comment]
It's just an "ErrorException", no further details except the path given in the title.

Craft 5.5.2 + Blitz 5.9.6 (sorry for forgetting to add that)

**Comment by bencroker** [comment]
Can you please send the full stack trace to support@putyourlightson.com, so I can take a closer look? Any exceptions _should_ be caught, which is why this is a bit confusing.

**Comment by bencroker** [comment]
Decided to check for the existence of cached files before deletion, to prevent unnecessarily logged warnings, in https://github.com/putyourlightson/craft-blitz/commit/8676256e7bf61b84707eafc11f04b089a98a2176.
