### ISSUE TITLE
Since Upgrading to Craft5, the "Generating Blitz Cache" Job is Using a Huge Amount of Resources

### ISSUE THREAD

**Issue by daveh-da** [putyourlightson/craft-blitz#744]
### Support Request

Hi team,

We've been using Blitz Cache on our project with very good results up until the upgrade to Craft 5. Unfortunately since upgrading to Craft 5, one of the jobs created, "Generating Blitz cache," usually takes several minutes to complete, often crashing the server by using too many resources.

In my testing, I made a small content update to my homepage but noticed the above job in the queue had 85 `siteIds` in the JSON log, so I believe that means it's trying to regenerate the cache for 85 pages. Does this happen if we reuse entries inside other entries? So for instance we have a call to action "About us", which is used on the home page, so when the home page is updated that triggers a cache regeneration for home page (as expected), which triggers a cache regeneration for the entry "about us", which in turn then triggers a cache regeneration for each page that uses the CTA "About us"?

Our current Refresh Mode is the default "Clear the cache and regenerate the new job" so we are looking at using one of the "Expire..." refresh methods. I did some testing and whilst they didn't crash my site locally (the default refresh mode did intermittently), however, I did notice the same job in the queue was refreshing 85 siteIds when updating only the home page.

Other options we're exploring is reducing the Concurrency from 3 to 1 to use less server resources. Also enabling SSI - I'm not exactly sure of the specifics of this option, but I watched a video from a few months ago on CraftQuest where Ben suggested using this option as it would help with cache generation of things like navigation.

Craft Pro 5.4.6

#### Site Tracking 

- Tracked Pages: 110
- Tracked Includes: 0
- Tracked Query String Params: 0
- Tracked Elements: 2408
	- craft\elements\Entry: 1,507
	- craft\elements\Entry: 430
	- craft\elements\Asset: 360
	- verbb\navigation\elements\Node: 85
	- craft\elements\Category: 26
- Tracked Element Queries: 382
	- verbb\navigation\elements\Node: 185
	- craft\elements\Entry: 176
	- craft\elements\Category: 15
	- craft\elements\Asset: 6
- Tracked Tags: 0

### Plugin Version

5.8.1

**Comment by bencroker** [comment]
As a first step, can you please update to the latest version of the plugin? 

If you output entries in your navigation, then Blitz _has_ to clear and generate many more pages each time any of them are updated, which using cached includes can avoid. So if SSI is enabled on your web server, I’d highly recommend using it.

**Comment by daveh-da** [comment]
Thanks for the prompt response @bencroker - will check out the navigation situation, enable SSI and update versions and report back.

**Comment by daveh-da** [comment]
Have updated the plugin and am using the **SSI enabled** option but still getting the same issues.

Have noticed after clearing the cache and regenerating, in the plugin logs I am getting this error consistently "[2024-12-04 14:42:49] Connection to 'localwebsite.test:443' failed" If I reduce the number of pages to be cached to 5, this error appears five times. If I have 10 pages to cache, it appears 10 times and so on.

We were wondering if it was not playing ball with some DNS settings but nothing appears out of the ordinary (am using laravel valet).

Current Diagnostics

#### Application Info

- PHP version: 8.3.14
- Craft edition & version: Pro 5.4.6
- Database driver & version: MySQL 8.0.33

#### Installed Plugins

- Amazon S3: 2.2.1
- Anchors: 3.4.0
- Asset Usage: 4.1.3
- Blitz: 5.9.6
- CKEditor: 4.2.0
- Colour Swatches: 5.0.3
- Config Values Field: 5.0.0-alpha.1
- Control Panel CSS: 3.0.0
- Entry Count: 4.0.0
- Environment Label: 5.0.0
- Expanded Singles: 3.0.0
- Feed Me: 6.4.0
- Freeform: 5.6.3
- Freeform edit logger: 1.0
- Guide: 4.0.0
- Icon Picker: 3.0.1
- Imager X: 5.0.2
- Jason: 3.1.1
- Linkit: 5.0.0
- Mailgun: 3.1.0
- Mix: v1.7.2
- Navigation: 3.0.4
- Position Fieldtype: 5.0.0
- Redactor: 4.2.0
- Retour: 5.0.3
- Schedule: 0.6.2
- Scout: 5.0.1
- Sentry SDK: 3.0.0
- SEOmatic: 5.1.4
- SmartRecruiters: 0.1
- Star Ratings: 3.0.0
- Super Table: 4.0.2
- Typogrify: 5.0.1
- UI Element fields: 3.0.0

#### Loaded Modules

- module: modules\Module
- codeeditor: nystudio107\codeeditor\CodeEditor
- sprig-core: putyourlightson\sprig\Sprig
- verbb-base: verbb\base\Base

#### Blitz Plugin Settings

```json
{
    "debug": true,
    "hintsEnabled": true,
    "cachingEnabled": true,
    "refreshCacheEnabled": true,
    "refreshMode": 3,
    "includedUriPatterns": [
        {
            "enabled": "1",
            "uriPattern": "\/partners\/business"
        }
    ],
    "excludedUriPatterns": [],
    "cacheStorageType": "putyourlightson\\blitz\\drivers\\storage\\YiiCacheStorage",
    "cacheStorageSettings": [],
    "cacheStorageTypes": [],
    "cacheGeneratorType": "putyourlightson\\blitz\\drivers\\generators\\HttpGenerator",
    "cacheGeneratorSettings": {
        "concurrency": "3"
    },
    "cacheGeneratorTypes": [],
    "customSiteUris": [],
    "cachePurgerType": "putyourlightson\\blitz\\drivers\\purgers\\DummyPurger",
    "cachePurgerSettings": [],
    "cachePurgerTypes": [],
    "deployerType": "putyourlightson\\blitz\\drivers\\deployers\\DummyDeployer",
    "deployerSettings": [],
    "deployerTypes": [],
    "ssiEnabled": true,
    "ssiTagFormat": "<!--#include virtual=\"{uri}\" -->",
    "detectSsiEnabled": true,
    "esiEnabled": false,
    "onlyCacheLowercaseUris": false,
    "queryStringCaching": 0,
    "includedQueryStringParams": [
        {
            "enabled": "1",
            "queryStringParam": ".*"
        }
    ],
    "excludedQueryStringParams": [
        {
            "enabled": "1",
            "queryStringParam": "gclid"
        },
        {
            "enabled": "1",
            "queryStringParam": "fbclid"
        }
    ],
    "apiKey": "",
    "generatePagesWithQueryStringParams": true,
    "purgeAssetImagesWhenChanged": true,
    "refreshCacheAutomaticallyForGlobals": false,
    "refreshCacheWhenElementMovedInStructure": true,
    "refreshCacheWhenElementSavedUnchanged": false,
    "refreshCacheWhenElementSavedNotLive": false,
    "cacheNonHtmlResponses": false,
    "trackElements": true,
    "trackElementQueries": true,
    "excludedTrackedElementQueryParams": [],
    "cacheDuration": null,
    "nonCacheableElementTypes": [],
    "sourceIdAttributes": [],
    "liveStatuses": [],
    "integrations": [
        "putyourlightson\\blitz\\drivers\\integrations\\CommerceIntegration",
        "putyourlightson\\blitz\\drivers\\integrations\\SeomaticIntegration"
    ],
    "defaultCacheControlHeader": "no-store",
    "cacheControlHeader": "public, s-maxage=31536000, max-age=0",
    "cacheControlHeaderExpired": "public, s-maxage=5, max-age=0",
    "sendPoweredByHeader": true,
    "outputComments": true,
    "refreshCacheJobPriority": 10,
    "driverJobBatchSize": 100,
    "driverJobPriority": 100,
    "queueJobTtr": 300,
    "maxRetryAttempts": 10,
    "maxUriLength": 255,
    "mutexTimeout": 1,
    "commands": [],
    "injectScriptEvent": "DOMContentLoaded",
    "injectScriptPosition": 3
}
```

#### Recommendations

- ❌ Queue jobs are configured to run automatically via web requests.
- ❌ The blitz/cache/refresh-expired console command has not been executed within the past 24 hours.
- ✅ Blitz is configured not to refresh cached pages when an element is saved but unchanged.
- ✅ Blitz is configured not to refresh cached pages when an element is saved but not live.
- ✅ Image transforms are configured to be generated before page load.
- ✅ One or more globals exist and refreshCacheAutomaticallyForGlobals is disabled.
- ✅ The @web alias is explicitly defined.
- ✅ The Blitz Hints utility is not reporting any eager-loading opportunities.
- ✅ The Async Queue plugin is not installed or enabled.

#### Site Tracking 

- Tracked Pages: 0
- Tracked Includes: 0
- Tracked Query String Params: 0
- Tracked Elements: 0
- Tracked Element Queries: 0
- Tracked Tags: 0

**Comment by bencroker** [comment]
You'll most likely need to use the Local Generator in a local development environment.

**Comment by daveh-da** [comment]
Thanks, that got us working with a fresh Craft5 install, but not with our project (which started with Craft3, possibly 2 - I'm not sure) so that tells us there is some legacy configuration setting that is causing issues with our local cache generation.

As for the initial issue, after manually generating the cache and doing some testing locally with the option "Clear the cache, regenerate manually or organically" seems to have some promising results. Will report back.

**Comment by daveh-da** [comment]
A few issues were stopping our local cache generation
- Not using Local Generator option (as above).
- Two fields in Super Table didn't migrate from Craft 4 properly for some reason (simply saving the fields worked, so no loss of data).
- An environment variable in a plugin config file was not set (Environment Label, but probably didn't matter what the plugin was).
- We added eagerly() to a number of database calls, but it doesn't always work, so we've removed this for now and will revisit it later. It did work when we did a couple of simple tests so it seems like the data coming from our CMS is not always compatible with eagerly so we need to investigate that separately.

Would recommend to any dev's who come across this to disable all your plugins and bring them back one by one to help isolate the problem.

In the last test we just did the cache wasn't regenerating correctly in the queue but we're definitely getting somewhere.

**Comment by daveh-da** [comment]
The cache not regenerating correctly in the queue proved to be a bit of a false flag as our local databases had gone through all sorts of changes in the last couple of days so after rebuilding our project from scratch and applying the four changes above, we are all good again. Thanks so much for your prompt response @bencroker it was much appreciated. We haven't applied any of the settings around SSI, but plan to do so next week as part of optimising Blitz's performance.

I wish I could give specifics on why two particular Super Table fields were causing problems for Blitz and our other 20 or so Super Table fields didn't cause problems, but sadly we couldn't identify the cause.

**Comment by bencroker** [comment]
Glad to hear you got it working, @daveh-da!
