### ISSUE TITLE
Index (list view) pages don't refresh cache with scheduled articles if user saves them with current date and then reschedule to future.

### ISSUE THREAD

**Issue by petenice** [putyourlightson/craft-blitz#745]
### Bug Report

I'm finding a curious behavior. Here's how to recreate:

1. Start a new entry and save as "draft" or "create entry" with current date and time.
2. Refresh index page (list view) where the entry appears.
3. Modify the entry publication date to a future time.
4. Refresh the index page (list view) and see that the entry is gone, permalink page returns 404.
5. Wait until publication time comes, permalink page is now viewable.
6. However, index page cache does not refresh, entry is not available for viewing on list.

#### Application Info

- PHP version: 8.1.14
- Craft edition & version: Pro 4.11.5
- Database driver & version: MySQL 8.0.40

#### Installed Plugins

- Batch Actions: 1.3.1
- Blitz: 4.23.0
- Breadcrumb: 2.0.0
- CodeMirror: 2.0.0
- Colour Swatches: 4.4.0
- Control Panel CSS: 2.6.0
- Feed Me: 5.5.0
- Google Custom Search: 2.1.4
- ImageOptimize: 4.0.5
- Matrix Colors: 3.0.0
- Navigation: 2.0.21
- Neo: 4.2.12
- Optimum: 1.1.0
- Phone Number: 2.2.0
- Redactor: 3.1.0
- Redactor Custom Styles: 4.0.3
- Redirects: 4.1.13
- Reporter: 2.3.0
- Retcon: 2.8.0
- SEO: 4.2.3
- Simple Text: 3.1.0
- Sprig: 2.8.1
- Tags: 2.0.0
- Typed link field: 2.1.5
- UI Element fields: 2.0.3

#### Loaded Modules

- codeeditor: nystudio107\codeeditor\CodeEditor
- sprig-core: putyourlightson\sprig\Sprig
- blitz-hints: putyourlightson\blitzhints\BlitzHints
- verbb-base: verbb\base\Base
- debug: craft\debug\Module

#### Blitz Plugin Settings

```json
{
    "debug": false,
    "hintsEnabled": true,
    "cachingEnabled": true,
    "refreshCacheEnabled": true,
    "refreshMode": 1,
    "includedUriPatterns": [
        {
            "siteId": "",
            "uriPattern": "*"
        }
    ],
    "excludedUriPatterns": [
        {
            "siteId": "",
            "uriPattern": "dafarm"
        },
        {
            "siteId": "",
            "uriPattern": "search"
        },
        {
            "siteId": "",
            "uriPattern": "cms-uptime-test"
        }
    ],
    "cacheStorageType": "putyourlightson\\blitz\\drivers\\storage\\FileStorage",
    "cacheStorageSettings": {
        "folderPath": "@webroot\/blitz",
        "createGzipFiles": "",
        "createBrotliFiles": ""
    },
    "cacheStorageTypes": [],
    "cacheGeneratorType": "putyourlightson\\blitz\\drivers\\generators\\HttpGenerator",
    "cacheGeneratorSettings": {
        "concurrency": "3"
    },
    "cacheGeneratorTypes": [],
    "customSiteUris": [],
    "cachePurgerType": "putyourlightson\\blitz\\drivers\\purgers\\DummyPurger",
    "cachePurgerSettings": [],
    "cachePurgerTypes": [],
    "deployerType": "putyourlightson\\blitz\\drivers\\deployers\\DummyDeployer",
    "deployerSettings": [],
    "deployerTypes": [],
    "ssiEnabled": false,
    "ssiTagFormat": "<!--#include virtual=\"{uri}\" -->",
    "detectSsiEnabled": true,
    "esiEnabled": false,
    "queryStringCaching": 0,
    "includedQueryStringParams": [
        {
            "queryStringParam": ".*"
        }
    ],
    "excludedQueryStringParams": [
        {
            "queryStringParam": "gclid"
        },
        {
            "queryStringParam": "fbclid"
        }
    ],
    "apiKey": "",
    "generatePagesWithQueryStringParams": true,
    "purgeAssetImagesWhenChanged": true,
    "refreshCacheAutomaticallyForGlobals": true,
    "refreshCacheWhenElementMovedInStructure": true,
    "refreshCacheWhenElementSavedUnchanged": false,
    "refreshCacheWhenElementSavedNotLive": false,
    "cacheNonHtmlResponses": false,
    "trackElements": true,
    "trackElementQueries": true,
    "excludedTrackedElementQueryParams": [],
    "cacheElements": true,
    "cacheElementQueries": true,
    "cacheDuration": null,
    "nonCacheableElementTypes": [],
    "sourceIdAttributes": [],
    "liveStatuses": [],
    "integrations": [
        "putyourlightson\\blitz\\drivers\\integrations\\CommerceIntegration",
        "putyourlightson\\blitz\\drivers\\integrations\\FeedMeIntegration",
        "putyourlightson\\blitz\\drivers\\integrations\\SeomaticIntegration"
    ],
    "defaultCacheControlHeader": "no-store",
    "cacheControlHeader": "public, s-maxage=31536000, max-age=0",
    "cacheControlHeaderExpired": "public, s-maxage=5, max-age=0",
    "sendPoweredByHeader": true,
    "outputComments": true,
    "refreshCacheJobPriority": 10,
    "driverJobBatchSize": 100,
    "driverJobPriority": 100,
    "queueJobTtr": 300,
    "maxRetryAttempts": 10,
    "maxUriLength": 255,
    "mutexTimeout": 1,
    "commands": [],
    "injectScriptEvent": "DOMContentLoaded",
    "injectScriptPosition": 3
}
```

#### Recommendations

- ❌ Image transforms are configured not to be generated before page load.
- ❌ One or more globals exist and refreshCacheAutomaticallyForGlobals is enabled.
- ❌ Queue jobs are configured to run automatically via web requests.
- ❌ The Blitz Hints utility is reporting 44 eager-loading opportunities.
- ✅ Blitz is configured not to refresh cached pages when an element is saved but unchanged.
- ✅ Blitz is configured not to refresh cached pages when an element is saved but not live.
- ✅ The @web alias is explicitly defined.
- ✅ The Async Queue plugin is not installed or enabled.
- ✅ The blitz/cache/refresh-expired console command has been executed within the past 24 hours.

#### Site Tracking 

- Tracked Pages: 20
- Tracked Includes: 0
- Tracked Query String Params: 0
- Tracked Elements: 279
	- craft\elements\Entry: 121
	- craft\elements\Asset: 80
	- verbb\navigation\elements\Node: 62
	- craft\elements\Tag: 12
	- craft\elements\Category: 3
	- craft\elements\User: 1
- Tracked Element Queries: 79
	- verbb\navigation\elements\Node: 56
	- craft\elements\Entry: 23
- Tracked Tags: 0

**Comment by bencroker** [comment]
For the index page to be refreshed, the `refresh-expired` console command must be run. The easiest way to automate this is to create a cron job that runs on a scheduled interval. If entries are generally posted or expire on the hour then a good schedule might be every hour at 5 minutes past the hour. 

See the docs at https://putyourlightson.com/plugins/blitz#cron-jobs
