### ISSUE TITLE
Typed property craft\web\Application::$edition must not be accessed before initialization

### ISSUE THREAD

**Issue by bartrylant** [putyourlightson/craft-blitz#746]
### Bug Report

I've updated Craft and all plugins to the latest available versions. Since I did so, I could edit entries without problems. However, from the moment I try to add a new field, I get this error:

```
Typed property craft\web\Application::$edition must not be accessed before initialization
in /Users/xxx/Sites/xxx/vendor/putyourlightson/craft-blitz/src/Blitz.php
```
It refers to this line:

```
if (Craft::$app->edition === CmsEdition::Pro) {
                $this->registerUserPermissions();
            }
```

One I've had this error, there is no way to see any page on the control panel anymore at all.

### Diagnostics Report

/

**Comment by bencroker** [comment]
Can you please provide the full stack trace of the error being thrown so I can troubleshoot? This might be a bug in Craft, as an edition should _always_ exist. I cannot replicate this using Craft 5.5.5 and Blitz 5.9.6.

**Comment by bencroker** [comment]
Assuming this is resolved, due to lack of a response.
