### ISSUE TITLE
Compress to brotli

### ISSUE THREAD

**Issue by Toni-hr98** [putyourlightson/craft-blitz#748]
### Feature Request

Can we compress to Brotli instead of gzip?

![Scherm­afbeelding 2024-12-18 om 12 02 17](https://github.com/user-attachments/assets/c10248a3-9667-4ac9-a37f-fe10bdcc9393)

### Plugin Version

4.23.7

**Comment by bencroker** [comment]
It’s only possible to use gzip when compressing cached files. If you need Brotli encoding, let the web server (or CDN) handle it.
