### ISSUE TITLE
How to invalidate cache with imgix

### ISSUE THREAD

**Issue by BenParizek** [putyourlightson/craft-blitz#75]
We have Blitz alongside imgix on a site. After images are updated (even with new names) in the Control Panel the images aren't getting updated on the site until we rewarm the Blitz cache.

Imgix URLs are output on the pages and are structured like the following:

```
https://imgixsubdomain.website.com/images/image.jpg?auto=format&domain=imgixsubdomain.website.com&fit=crop&fp-x=0.5&fp-y=0.5&h=2243&ixlib=php-2.1.1&q=61&w=3840
```

I expect Blitz may not know what pages to bust cache on as the image can appear on several pages but I haven't fully diagnosed what is going on.

What behavior should we be expecting here in how Blitz watches or knows about changed images and when it chooses to invalidate cache around images? Right now, each time an image is updated the content manager needs to hit "Rewarm Blitz cache", which isn't ideal.

**Comment by putyourlightson** [comment]
Blitz monitors elements, including assets, for changes, and refreshes any known cached pages that use those elements. Are you using this [Imgix plugin](https://github.com/sjelfull/craft3-imgix) to output the URLs or another method? And can you please elaborate on how images are being updated?
> Right now, each time an image is updated the content manager needs to hit "Rewarm Blitz cache", which isn't ideal.

**Comment by putyourlightson** [comment]
Hi Ben, can you please follow up on this issue so I can ensure it is resolved for the next release?

**Comment by BenParizek** [comment]
@BenParizek I haven't had a chance to dig into this and confirm how things are working yet. I'll follow up when I can or reopen once I have more info if you want to close it out.

**Comment by putyourlightson** [comment]
Ok, if it is an issue with the upcoming v2 then please do reopen the issue.
