### ISSUE TITLE
Option to disable timestamps

### ISSUE THREAD

**Issue by andrewfairlie** [putyourlightson/craft-blitz#76]
It would be great to be able to disable the timestamp comments. We're using Blitz on a site we're building to serve a little JSON feed that gets hit a lot but the html comment being added is breaking things.

Is there a way to disable it? I may have missed it in docs but did try to hunt for it.

**Comment by putyourlightson** [comment]
There is not, but thanks for the suggestion, I'll make sure this gets added in the next release. In the meantime you can simply comment out the line.

**Comment by mijewe** [comment]
Hi - I'm having this same issue; my JSON feed is getting an HTML comment at the bottom which is breaking things.

In the docs it specifies that the comment is only added onto HTML files, so either the docs are wrong or for some reason my .json is being flagged as an .html by Blitz.

What's the recommended solution for this?

**Comment by bencroker** [comment]
Can you please check the conversation in https://github.com/putyourlightson/craft-blitz/issues/194 which is open, and feel free to join in if it applies to your use-case.

**Comment by bencroker** [comment]
On second thought, this issue is probably slightly different. Are you on the latest version of Blitz?

**Comment by bencroker** [comment]
It looks like the comment is not excluded for non html files, we’ll change this in the next release. In the meantime you can disable comments by setting the `outputComments` config setting to `false`.

**Comment by mijewe** [comment]
Ok nice one - I'll do that for now.
Is the outputComments option anywhere in the docs?

**Comment by bencroker** [comment]
It is in the [config file](https://github.com/putyourlightson/craft-blitz/blob/3.6.2/src/config.php#L172-L173), and I've just added to the docs too.

**Comment by mijewe** [comment]
Excellent work, thanks for being so responsive!

**Comment by bencroker** [comment]
Added in https://github.com/putyourlightson/craft-blitz/commit/f1748986818255ec714fb6d024008f612860ac97.
