### ISSUE TITLE
Write cache files only into designated folder

### ISSUE THREAD

**Issue by wbrowar** [putyourlightson/craft-blitz#77]
Hey @putyourlightson,

I've got a route where the URI is dynamically created by user input and the route URI is cached by Blitz.

It looks like if you put a combination of `./`, `../`, and/or `.../` into the input, Blitz allows those files to be written above the specified `cache` folder because somewhere in deciding where to place the `index.html` file for that URI, the directory commands are interpreted.

The way I found this was there was an `index.html` file, `etc/psswd/index.html` in my project root folder put there by Blitz.

On my end, I've patched this by checking for it and redirecting any inputs with those directory commands to a `404`, but it would be good for Blitz to have some kind of check to see if the cache files are going to be placed outside of the designated cache folder and find a way to make sure that the files aren't written.

**Comment by putyourlightson** [comment]
Thanks Will! I've added a check for this in v2.
