### ISSUE TITLE
Solspace freeform integration?

### ISSUE THREAD

**Issue by cmalven** [putyourlightson/craft-blitz#78]
I'm attempting to integrate Solspace Freeform into a site that uses Blitz for caching. I was originally running into CSRF validation errors, but that was fixed by adding a `{{ craft.blitz.csrfInput() }}` as described in the docs.

Now, though, form submission does not throw an error, but it silently fails. I'm redirected to the appropriate post-submit URL, but the submission does not show up in the CP, the form does not submit to MailChimp (via an API integration), and there are no errors in any logs.

The form submits perfectly when Blitz caching is disabled. Here is my approximate form code:

```twig
{% set form = craft.freeform.form('emailNews') %}

{% set email = form.get('email') %}
{% set submit = form.get('OkWWpNKyj') %}

{{ form.renderTag({
  returnUrl: form.returnUrl
}) }}
  {{ craft.blitz.csrfInput() }}

  {# Email input here… #}

  <button type="submit">Submit</button>
{{ form.renderClosingTag }}
```

Has anybody managed to get Freeform successfully-submitting with a Blitz cached page?

**Comment by putyourlightson** [comment]
Have you ensured that the URL that the form redirects to is excluded from being cached? Otherwise you may see a cached success page when in fact there was an error.

**Comment by cmalven** [comment]
Thanks @putyourlightson 

I've ensured that those redirected pages aren't caching, and I'm still not seeing any errors. I don't think it should matter anyway, since those URLs are redirected to by Freeform _after_ a successful submit, not the URL Freeform actually does any form processing on. I could be wrong.

**Comment by putyourlightson** [comment]
Does it perhaps have to do with Freeform's spam protection?
http://docs.solspace.com/craft/freeform/v2/overview/spam-protection.html#javascript-honeypot

**Comment by cmalven** [comment]
Fingers crossed, disabling Freeform spam prevention seems to have solved it. I mistakenly believed spam prevention was opt-in at the form level and thought I had disabled it, but I hadn't. Thank you!

**Comment by putyourlightson** [comment]
Sure thing!
