### ISSUE TITLE
Alias in cache folder path

### ISSUE THREAD

**Issue by Tam** [putyourlightson/craft-blitz#80]
The cache folder path appends the sites base url, but doesn't parse it if it's an alias:

<img width="276" alt="Screenshot 2019-03-14 at 15 23 05" src="https://user-images.githubusercontent.com/977594/54369078-340a9880-466d-11e9-9be3-3bdc5548797b.png">

Resulting in:
<img width="216" alt="Screenshot 2019-03-14 at 15 24 34" src="https://user-images.githubusercontent.com/977594/54369194-63210a00-466d-11e9-9104-6ea404d7e7c7.png">

Plugin Version: 2.0.0
Craft Version: 3.1.17.2

**Comment by putyourlightson** [comment]
Thanks, fixed in 2.0.1 https://github.com/putyourlightson/craft-blitz/commit/aa7cb803eb14f5a0c8f7cf82a4b12eb6d3f0d866.
