### ISSUE TITLE
Config handle `cacheDriverType` should be `cacheStorageType`

### ISSUE THREAD

**Issue by johndwells** [putyourlightson/craft-blitz#82]
In `blitz.php` for configuring via `/config` files, the setting `cacheDriverType` should be `cacheStorageType`.

Also a silly little thing but the values it's set to in the comment isn't a string but should be. Same goes for `cachePurgerType` and `cachePurgerTypes`.

**Comment by putyourlightson** [comment]
Thanks John, fixed in https://github.com/putyourlightson/craft-blitz/commit/31a2128236c2ca6540cc4e8352cd242a51662ea5. 

`$cachePurgerType` can accept the class followed by `::class` but it seems unneccesary so I've replaced it with a string.
