### ISSUE TITLE
Solspace Freeform Hash and CSRF

### ISSUE THREAD

**Issue by IndigoViking** [putyourlightson/craft-blitz#85]
I have a "Main Content" layout that a number of sections use that loops through a matrix and can output any number of forms. The page urls, entries, and sections that use this vary.

Is there a way to output the hash and the csrf for the form(s) selected? Currently I am using form.render() but I can manually output the form as well but I still run into the trouble for the hash from all the forms that pass through.

**Comment by putyourlightson** [comment]
> Currently I am using form.render() but I can manually output the form as well but I still run into the trouble for the hash from all the forms that pass through.

What specifically is the problem when you manually output the form? Placing the Blitz CSRF tag anywhere within the form tags should work. I'm also unclear as to what you mean by the _hash_. Can you perhaps post some code samples?

**Comment by IndigoViking** [comment]
Initial template code:
`{{ form.render() }}`

Adjusted to:
`{{ form.renderTag }}
{{ craft.blitz.csrfInput() }}
...
{{ form.renderClosingTag }}`

In this case it outputs, 
`<input type="hidden" name="formHash" value="someLongValue">`

by the CSRF tag and the hash gets cached and the form doesn't create a new submission. I'm assuming it has to do with the cache per the Solspace docs but I am uncertain.

Am I doing this incorrectly?

**Comment by IndigoViking** [comment]
Nevermind, I read the other closed issue about Solspace forms and turning the honeypot fixed it even though the hash isn't regenerating! Thanks for your time!

**Comment by putyourlightson** [comment]
Ok great!
