### ISSUE TITLE
Accept PRs/support for additional CDNs?

### ISSUE THREAD

**Issue by verbeeksteven** [putyourlightson/craft-blitz#86]
Hello,

We use bunnycdn and are wondering if you accept PRs or are willing to support additional CDNs besides Cloudflare?

**Comment by putyourlightson** [comment]
Yes, one of the ideas behind Blitz 2 is to allow for easy creation of new purgers, see: https://putyourlightson.com/craft-plugins/blitz/docs#/?id=custom-reverse-proxy-purgers

Take a look at the [KeyCDN](https://github.com/putyourlightson/craft-blitz-keycdn) purger for Blitz and let us know if you have any questions.
