### ISSUE TITLE
Cannot save globals after update to Blitz 2

### ISSUE THREAD

**Issue by Djive** [putyourlightson/craft-blitz#88]
We updated Craft and Blitz to newest versions.
Craft Pro 3.1.19
Blitz 2.0.5 
(Running a multi-site setup with 130 sites.)

After that we couldn't save globals anymore.
I just runs untill it time-outs.
We have a lot of memory allocated to the site and max exec time of 512 secs.
We tried to increase it even more, but it didnt matter, it always time-outs.
Before update, globals were updating normally.
After the update globals are updating normally only if we disable Blitz addon.

These are only PHP errors we got in the log
```
[21-Mar-2019 11:01:39 Europe/Zagreb] PHP Fatal error:  Maximum execution time of 512 seconds exceeded in /home/site/vendor/craftcms/cms/src/web/Application.php on line 346
[21-Mar-2019 11:21:57 Europe/Zagreb] PHP Fatal error:  Maximum execution time of 512 seconds exceeded in /home/site/vendor/craftcms/cms/src/elements/db/ElementQuery.php on line 2260
[21-Mar-2019 11:50:09 Europe/Zagreb] PHP Fatal error:  Maximum execution time of 512 seconds exceeded in /home/site/vendor/craftcms/cms/src/helpers/DateTimeHelper.php on line 153
[21-Mar-2019 12:05:39 Europe/Zagreb] PHP Fatal error:  Maximum execution time of 512 seconds exceeded in /home/site/vendor/putyourlightson/craft-blitz/src/helpers/SiteUriHelper.php on line 75
[21-Mar-2019 12:07:40 Europe/Zagreb] PHP Fatal error:  Maximum execution time of 512 seconds exceeded in /home/site/vendor/yiisoft/yii2/base/Event.php on line 312
[21-Mar-2019 12:30:54 Europe/Zagreb] PHP Fatal error:  Maximum execution time of 512 seconds exceeded in /home/site/vendor/yiisoft/yii2/base/BaseObject.php on line 107
[21-Mar-2019 12:30:56 Europe/Zagreb] PHP Fatal error:  Maximum execution time of 512 seconds exceeded in /home/site/vendor/yiisoft/yii2-debug/src/LogTarget.php on line 60
[21-Mar-2019 14:24:30 Europe/Zagreb] PHP Fatal error:  Allowed memory size of 5368709120 bytes exhausted (tried to allocate 20480 bytes) in /home/site/vendor/yiisoft/yii2/base/Event.php on line 294
[21-Mar-2019 14:24:30 Europe/Zagreb] PHP Fatal error:  Allowed memory size of 5368709120 bytes exhausted (tried to allocate 32768 bytes) in /home/site/vendor/twig/twig/src/Extension/CoreExtension.php on line 503
[21-Mar-2019 14:25:50 Europe/Zagreb] PHP Fatal error:  Allowed memory size of 5368709120 bytes exhausted (tried to allocate 2097160 bytes) in /home/site/vendor/yiisoft/yii2/db/ActiveQuery.php on line 291
[21-Mar-2019 14:25:50 Europe/Zagreb] PHP Fatal error:  Uncaught yii\web\HeadersAlreadySentException: Headers already sent. in /home/site/vendor/yiisoft/yii2/web/Response.php:366
Stack trace:
#0 /home/site/vendor/yiisoft/yii2/web/Response.php(339): yii\web\Response->sendHeaders()
#1 /home/site/vendor/yiisoft/yii2/web/ErrorHandler.php(135): yii\web\Response->send()
#2 /home/site/vendor/craftcms/cms/src/web/ErrorHandler.php(137): yii\web\ErrorHandler->renderException(Object(yii\base\ErrorException))
#3 /home/site/vendor/yiisoft/yii2/base/ErrorHandler.php(262): craft\web\ErrorHandler->renderException(Object(yii\base\ErrorException))
#4 [internal function]: yii\base\ErrorHandler->handleFatalError()
#5 {main}
  thrown in /home/site/vendor/yiisoft/yii2/web/Response.php on line 366
[21-Mar-2019 14:51:48 Europe/Zagreb] PHP Fatal error:  Allowed memory size of 5368709120 bytes exhausted (tried to allocate 4194312 bytes) in /home/site/vendor/yiisoft/yii2/db/Command.php on line 1166
[21-Mar-2019 14:51:48 Europe/Zagreb] PHP Fatal error:  Uncaught yii\web\HeadersAlreadySentException: Headers already sent. in /home/site/vendor/yiisoft/yii2/web/Response.php:366
Stack trace:
#0 /home/site/vendor/yiisoft/yii2/web/Response.php(339): yii\web\Response->sendHeaders()
#1 /home/site/vendor/yiisoft/yii2/web/ErrorHandler.php(135): yii\web\Response->send()
#2 /home/site/vendor/craftcms/cms/src/web/ErrorHandler.php(137): yii\web\ErrorHandler->renderException(Object(yii\base\ErrorException))
#3 /home/site/vendor/yiisoft/yii2/base/ErrorHandler.php(262): craft\web\ErrorHandler->renderException(Object(yii\base\ErrorException))
#4 [internal function]: yii\base\ErrorHandler->handleFatalError()
#5 {main}
  thrown in /home/site/vendor/yiisoft/yii2/web/Response.php on line 366
[21-Mar-2019 15:28:04 Europe/Zagreb] PHP Fatal error:  Allowed memory size of 5368709120 bytes exhausted (tried to allocate 69632 bytes) in /home/site/vendor/yiisoft/yii2/db/Command.php on line 1166
[21-Mar-2019 15:28:04 Europe/Zagreb] PHP Fatal error:  Uncaught yii\web\HeadersAlreadySentException: Headers already sent. in /home/site/vendor/yiisoft/yii2/web/Response.php:366
Stack trace:
#0 /home/site/vendor/yiisoft/yii2/web/Response.php(339): yii\web\Response->sendHeaders()
#1 /home/site/vendor/yiisoft/yii2/web/ErrorHandler.php(135): yii\web\Response->send()
#2 /home/site/vendor/craftcms/cms/src/web/ErrorHandler.php(137): yii\web\ErrorHandler->renderException(Object(yii\base\ErrorException))
#3 /home/site/vendor/yiisoft/yii2/base/ErrorHandler.php(262): craft\web\ErrorHandler->renderException(Object(yii\base\ErrorException))
#4 [internal function]: yii\base\ErrorHandler->handleFatalError()
#5 {main}
  thrown in /home/site/vendor/yiisoft/yii2/web/Response.php on line 366
[21-Mar-2019 17:02:07 Europe/Zagreb] PHP Fatal error:  Maximum execution time of 512 seconds exceeded in /home/site/vendor/yiisoft/yii2/base/Event.php on line 229
[21-Mar-2019 17:02:10 Europe/Zagreb] PHP Fatal error:  Maximum execution time of 512 seconds exceeded in /home/site/vendor/yiisoft/yii2-debug/src/LogTarget.php on line 60
```

Thanks

**Comment by putyourlightson** [comment]
With so many sites, I recommend you disable the `warmCacheAutomaticallyForGlobals` setting in the plugin config file if you haven't already.

    // Whether the cache should automatically be warmed after clearing globals.
    'warmCacheAutomaticallyForGlobals' => false,

Also, are you using the [Async Queue](https://github.com/ostark/craft-async-queue) plugin? That should help by removing memory limits and maximum execution times if possible.

**Comment by putyourlightson** [comment]
Oh and after updating to Blitz 2, it probably is a good idea to clear and flush the cache and either warm it (preferably from the console) or allow it to warm organically.

**Comment by Djive** [comment]
`warmCacheAutomaticallyForGlobals` is already set to false. 
We are using both Async Queue plugin and Queue Manager plugin.
Did a `Clear cache` and it successfully deleted all cached pages.
After that tried flushing the cache from both Admin/Utilities and Console but in both cases, it failed.
This is the error from Console:

```
Exception 'yii\db\Exception' with message 'SQLSTATE[HY000]: General error: 1205                                                                                                                                                              Lock wait timeout exceeded; try restarting transaction
The SQL being executed was: DELETE FROM craft_blitz_caches'

in /home/site/vendor/yiisoft/yii2/db/Schema.php:664

Error Info:
Array
(
    [0] => HY000
    [1] => 1205
    [2] => Lock wait timeout exceeded; try restarting transaction
)

Stack trace:
...
```

`craft_blitz_caches ` table has ~110,113 rows and size of 13.1MiB
`craft_blitz_elementcaches ` table has ~277,456,121 rows and size of 29.6 GiB

How would you suggest we proceed about flushing the cache?
Thanks

**Comment by putyourlightson** [comment]
I don't quite understand why your `craft_blitz_elementcaches` table has _so_ many rows. This issue seems to stem from the fact that you have over 110,000 pages in a single Craft install and that they reference elements in over 200 million places. The surest way to flush the cache is to either uninstall the plugin, or failing that to manually empy all rows form the database table directly.

I'm also wondering why the timeout occurs after 512 seconds. Async Queue forces queue jobs to run as background PHP tasks which have a `max_execution_time` time of `0`, meaning unlimited ([source](http://php.net/manual/en/features.commandline.differences.php)). Where and how are you setting it to 512?

**Comment by Djive** [comment]
We manually deleted all rows from the `craft_blitz_elementcaches` table.
Then tried to `flush cache` but it still didn't work.
When we SSH onto server and try the command from there, we get the same response (displayed in the screenshot below)
You can also see those tables are not that big at the time of the attempt.
![flush-via-ssh](https://user-images.githubusercontent.com/1241189/54865043-9d6e6380-4d5f-11e9-9f60-d666e3992d48.jpg)
Then we deleted all rows from all Blitz  cache tables.
Clear and Flush commands now work both in Utilities area and in console.

But we still cannot update Globals, even after the whole cache has been cleared and flushed.
There are no PHP errors, just runs untill it hits 504 Gateway Time-out after about 10 mins.

The only thing we are seeing now regarding Blitz cache plugin are Integrity constraint violations in the web.log

`2019-03-23 11:17:56 [-][-][4d9114190e5211a6695c291b39672a2d][error][yii\db\IntegrityException] PDOException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '7-5707' for key 'craft_blitz_elementcaches_cacheId_elementId_unq_idx' in /home/site/vendor/yiisoft/yii2/db/Command.php:1290`

Regarding the Globals, we use Matrix fields in Globals in which we have the option to pull entries from all channels and categories on that site. It serves as a flexible way for each site to have a custom crafted smaller columns for any part of the site. Will have to rethink and maybe reorganize this part, but we didn't want to go down that road because before using the cache plugin, both frontend and backend were working, only that frontend was running slow. 

Thanks!

**Comment by putyourlightson** [comment]
Ok, I'll do some more investigating. If you send me credentials (info@putyourlightson.net) to a staging environment if you have one, otherwise to the live site, then I can take a closer look.

**Comment by putyourlightson** [comment]
I see that the relationships between the blitz tables do not exist in the database. Can you please uninstall Blitz and then install it again so you get a fresh set of tables? This might explain why the tables have become so huge. Let me know once that is done and I'll check the database again.

**Comment by Djive** [comment]
Blitz has been uninstalled and reinstalled. 
All settings and rules were entered again.
Thanks

**Comment by putyourlightson** [comment]
Excellent, the relationships now look correct in the database. Can you now test what was causing issues before?

**Comment by putyourlightson** [comment]
You may also want to reconsider your global set that contains entries. Since globals are available on _every_ page request (whether they are used or not), putting matrix blocks and entries in them is going to not only hurt the general performance of the site, but result in Blitz storing an enormous amount of relationships as you've seen already.

**Comment by Djive** [comment]
If we put them in entries, does everything will update ok on all pages. After changing data in entry..that replace globals..

**Comment by Djive** [comment]
Tried saving global but it still didn't save.
Just loads for 10 mins and then we get 504 Gateway Time-out.
But when we disable Blitz, then it saves successfully.

**Comment by putyourlightson** [comment]
Ok, I'm checking whether there are any bottlenecks or optimisations we could make to the plugin.

**Comment by Djive** [comment]
One thing I noticed

from 130 sites we have on install any site I visit .. cached page is generated instantly..

 

But not on main  site brinje.info   why is that..

AS other caching metods don’t play well with Blitz
what do you suggest for speeding up.. non cached pages or first load.

As it takes quite time to  10+ seconds
https://brinje.info/web-imenik/

Or
https://brinje.info/savjeti/

thx

**Comment by putyourlightson** [comment]
Any template that takes that long to load uncached must be very inefficiently designed. Without looking at the template in detail I cannot say for sure, but pagination or lack of eager loading elements might be the issue.

**Comment by putyourlightson** [comment]
FYI version 2.0.6 introduced some minor optimisations which might help, although probably not enough to solve the issue.

**Comment by Djive** [comment]
Updated the plugin and tried to `Clear cache` and `Flush cache` from Admin and Console, but `Flush cache` always resulted in a time-out.
Then we manually emptied all Blitz tables in phpMyAdmin.
After that we could normally do `Clear cache` and `Flush cache` from Admin.
But then errors like this one started showing up 
`SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1482295843' for key 'craft_blitz_elementqueries_index_unq_idx'
The SQL being executed was: INSERT INTO `craft_blitz_elementqueries` (`index`, `type`, `params`) VALUES (1482295843, 'craft\\elements\\Category', '{\"groupId\":[\"1\"],\"siteId\":\"119\",\"structureId\":1,\"limit\":17}')`
Then we deinstalled and reinstalled the plugin and are in process of setting up the rules.
Will test everything after and let you know.

**Comment by Djive** [comment]
We managed to save changes to global variable just after reinstalling and setting all rules in Blitz plugin.
But still getting errors like this one:

`PDOException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1152837138' for key 'craft_blitz_elementqueries_index_unq_idx'
  File "/home/site/vendor/yiisoft/yii2/db/Command.php", line 1290, in execute
    $this->pdoStatement->execute();
  File "/home/site/vendor/yiisoft/yii2/db/Command.php", line 1290, in internalExecute
    $this->pdoStatement->execute();
  File "/home/site/vendor/yiisoft/yii2/db/Command.php", line 1091, in execute
    $this->internalExecute($rawSql);
  File "/home/site/vendor/putyourlightson/craft-blitz/src/services/GenerateCacheService.php", line 140, in addElementQuery
    ->execute();
  File "/home/site/vendor/putyourlightson/craft-blitz/src/Blitz.php", line 211, in putyourlightson\blitz\{closure}
    $this->generateCache->addElementQuery($elementQuery);
...
(35 additional frame(s) were not displayed)

yii\db\IntegrityException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '1152837138' for key 'craft_blitz_elementqueries_index_unq_idx'
The SQL being executed was: INSERT INTO `craft_blitz_elementqueries` (`index`, `type`, `params`) VALUES (1152837138, 'craft\\elements\\Tag', '{\"siteId\":\"1\",\"title\":\"miroslav buljan\",\"limit\":1}')
  File "/home/site/vendor/yiisoft/yii2/db/Schema.php", line 664, in convertException
    return new $exceptionClass($message, $errorInfo, (int) $e->getCode(), $e);
  File "/home/site/vendor/yiisoft/yii2/db/Command.php", line 1295, in internalExecute
    $e = $this->db->getSchema()->convertException($e, $rawSql);
  File "/home/site/vendor/yiisoft/yii2/db/Command.php", line 1091, in execute
    $this->internalExecute($rawSql);
  File "/home/site/vendor/putyourlightson/craft-blitz/src/services/GenerateCacheService.php", line 140, in addElementQuery
    ->execute();
  File "/home/site/vendor/putyourlightson/craft-blitz/src/Blitz.php", line 211, in putyourlightson\blitz\{closure}
    $this->generateCache->addElementQuery($elementQuery);
...
(35 additional frame(s) were not displayed)
`

**Comment by putyourlightson** [comment]
Please update to 2.0.7 which should hopefully help prevent this type of error.

**Comment by putyourlightson** [comment]
Any change since using 2.0.7?

**Comment by Djive** [comment]
seems OK now..

But still when i save globalas on 1 site, it clear cache for all 130 sites..

How to set up to clear cache only for that site where globals where saved. only 1 site

**Comment by putyourlightson** [comment]
The issue is that globals, unlike entries, are available for every site. So when you save a global in one site, Craft must update it for every other site. As far as I can tell there's no practical way of getting around this.

**Comment by Djive** [comment]
can we disable that for globals.
and user clears only his site.. manually or any other way posiblle

**Comment by Djive** [comment]
just for info..

Globals are site based..

we made it so each site have their own settings in globals..
so one 1 user change settings on his site..
that does not change other sites just his site... on that domain

**Comment by Djive** [comment]
Ben, can you ask Brandon if he have any insight..on this

**Comment by putyourlightson** [comment]
The nature of global sets is that they are localized on a per site basis, meaning that they are available to all sites. Saving a global set in one site will automatically update it for all other sites. This is how Craft currently works and altering this behaviour in Blitz could have some unforeseen consequences. 

Say for example there is a global set with at least one non translatable field (Heading). Its value may be used by all sites, so in this case when the global set is updated, all sites should be refreshed.

![Screenshot 2019-04-01 at 09 26 46](https://user-images.githubusercontent.com/2318222/55310665-5409cc80-5461-11e9-94bb-1d8f66adebd5.png)

This makes using globals for individual site settings a poor choice. I would think it would be much better to make them Single sections.

I could add a config setting to disable clearing the cache when global sets are saved, but I still think that using Singles for your site settings would be a much better long-term solution.

**Comment by Djive** [comment]
We would very much like a setting to not clear any cache when updating globals.
Thanks

**Comment by Djive** [comment]
Another question

 

Please see image

**Comment by Djive** [comment]
![blitz](https://user-images.githubusercontent.com/1241189/55615948-065ad000-5791-11e9-9b66-ab44f1017f5a.png)

another question, Please can you check image

**Comment by putyourlightson** [comment]
I think I understand your question. The tricky part is that globals can contain non-translatable fields which will be propogated across all sites any time a global is saved, regardless of which site it is saved in. 

Perhaps it makes sense to submit a feature request to Craft CMS to propogate the saving of globals across all sites _only_ if non-translatable fields exist in the global. If you create the issue then I'll back it up which an explanation if necessary.
https://github.com/craftcms/cms/issues/

**Comment by Djive** [comment]
OK thx

**Comment by putyourlightson** [comment]
Added the `clearCacheAutomaticallyForGlobals` config setting in 2.0.8.
https://github.com/putyourlightson/craft-blitz/blob/2.0.8/src/config.php#L56
