### ISSUE TITLE
Code Rendering Out of Place

### ISSUE THREAD

**Issue by brianrivet** [putyourlightson/craft-blitz#89]
Hi Ben,

When I use Blitz to cache my pages I'm noticing that some of my code is rendering  out of place for some reason. Specifically I'm seeing code form the head section that is appearing in the body, etc. However, I'm only seeing this when I look at the code in the browser dev tools. When I look at the code being rendered to the cache (see attached, one file is from the cache and the other is the code rendered with the cache turned off), the code is the same other than csrf tokens which I haven't added the code fixes for yet, so I expect those to not match, etc.

I know that the dev tools show you the browser's dom interpretation and not necessarily the actual code, but when I turn off the caching the problem goes away, so I don't know what is going on. I wouldn't think that Blitz is doing any sort of dom manipulation with code, but I thought I'd check here first. 

I am running Twigpack with webpack to handle deployment and a few other optimizations, so it may be possible that that could be part of it, like critical css etc. but that stuff is running even when Blitz is turned off and it doesn't have an issue with the cache turned off.

I've included the html output from the cache and with the cache turned off along with the relevant templates in the attached zip file. I've turned the caching back on, and if you go to https://myhy.sassoagency.com/our-story-so-far you can see what I mean. If you need credentials to troubleshoot further please let me know. Thanks!

[myhy-blitz-support.zip](https://github.com/putyourlightson/craft-blitz/files/3015417/myhy-blitz-support.zip)

**Comment by putyourlightson** [comment]
Thanks for your message. Blitz prepends a byte-order mark (BOM) to the beginning of the saved value to ensure that it is interpreted as UTF-8 encoded text. Normally the browser picks up on this automatically but that doesn't seem to be the case here. Can you try adding the following meta tag to your HTML to see if it helps?

```
<meta charset="utf-8"/>
```

You may also want to run your mark-up through a validator as there appear to be quite a few issues with it.
https://validator.w3.org/nu/?doc=https%3A%2F%2Fmyhy.sassoagency.com%2Four-story-so-far

**Comment by brianrivet** [comment]
I’ve added the char set meta tag but it didn’t have any effect. I’m looking at the validation, most of the errors I’m seeing are related to my Vue.js code, so I’m not sure there’s anything I can do about those. I read up on it and apparently the validation doesn’t read or execute JavaScript and the Vue syntax gets removed when the JavaScript is run.

**Comment by putyourlightson** [comment]
Hmm ok, I may need to revisit the UTF8 encoding that Blitz does. Can you manually comment out the following line, clear the cache and retest?

```
$value = "\xEF\xBB\xBF".$value;
```

https://github.com/putyourlightson/craft-blitz/blob/2.0.7/src/drivers/storage/FileStorage.php#L104

**Comment by brianrivet** [comment]
That appears to have fixed the problem.

**Comment by putyourlightson** [comment]
Ok great, I'll find an alternative approach for the next release of Blitz. Thanks for your help in getting to the bottom of this!
