### ISSUE TITLE
Live preview displays the cached version of a page.

### ISSUE THREAD

**Issue by tyler-shaw** [putyourlightson/craft-blitz#9]
Hi. I ran into an issue where Live Preview was displaying the cached version of the page, making it difficult to use that feature on a published page.

I assume this isn't the expected behavior, as I see the code avoids caching a page if it's being loaded for Live Preview.

Here are the steps I took:

1. Add a particular page to the list of pages that should be cached.
2. Visit that page on the live website so it will be cached.
3. Go to edit that page, and view it in Live Preview - the cached version should be loading.

Live preview appears to load pages via a post request, so I added to the documented .htaccess rule, making it only work for GET requests:

```
# Blitz cache rewrite
RewriteCond %{REQUEST_METHOD} GET
RewriteCond %{DOCUMENT_ROOT}/cache/blitz/%{HTTP_HOST}/%{REQUEST_URI}/index.html -f
RewriteRule .* /cache/blitz/%{HTTP_HOST}/%{REQUEST_URI}/index.html [L]
```

This corrected my issue, but perhaps there's a reason I shouldn't be doing this - if so, please let me know. Otherwise, would it be reasonable to add this to the documentation in order to help others avoid issues with Live Preview?

Thanks!

**Comment by tyler-shaw** [comment]
Nevermind! Looks like I'm actually a week late on this. (https://github.com/putyourlightson/craft-blitz/commit/4449d5ff94c812601223b1f5ac7cd41d638485c7)

Guess I set everything up before that documentation was changed and didn't notice the updates.

**Comment by putyourlightson** [comment]
Yeah things have been changing rather quickly around these parts :)
