### ISSUE TITLE
Installing the plugin causes an error 'No plugin exists with the handle "blitz"'

### ISSUE THREAD

**Issue by cjativa** [putyourlightson/craft-blitz#90]
I installed the plugin via `composer require putyourlightson/craft-blitz` which completed as expected.

However, when I navigated to Settings > Plugins, I saw the plugin was there in a status of not yet being installed. I clicked `Install` and the following error shows 

![image](https://user-images.githubusercontent.com/41299115/55167874-257db000-5148-11e9-8664-79c68c9ead23.png)

I have tried uninstalling and installing again, but this error continues to show.

**Comment by putyourlightson** [comment]
Thanks for your message. This appears to be an issue in Craft rather than Blitz, but I'm going to investigate a bit further and will let you know what I find. What version of Craft is installed and do you have `useProjectConfigFile` set to `true` in this environment?

**Comment by cjativa** [comment]
> Thanks for your message. This appears to be an issue in Craft rather than Blitz, but I'm going to investigate a bit further and will let you know what I find. What version of Craft is installed and do you have `useProjectConfigFile` set to `true` in this environment?

Yes, it may be a Craft problem -- but I'm unsure where the problem itself might lie. I am using Craft 3.1.20 and `useProjectConfigFile` is set to `true` in my environment.

**Comment by putyourlightson** [comment]
Ok, and did you run `composer require putyourlightson/craft-blitz` in your development environment?

**Comment by cjativa** [comment]
> Ok, and did you run `composer require putyourlightson/craft-blitz` in your development environment?

Yes, when I do it through composer there's no errors or warning shown -- it just appears to have completed. This leads to the same outcome I see when doing the install via the Craft store.

The plugin is still in a state of `Not Installed` in Settings > Plugins, after which I going to install it from that same page and I am shown the same error.

**Comment by putyourlightson** [comment]
Thanks for the reply. I'm going to ask @pixelandtonic to take a quick look and see if they can spot what the issue might be.

**Comment by cjativa** [comment]
Hi, I have an update on this and what might be a tentative fix, but it would be helpful to know what caused this in the first place. 

Rather than run through the installation via the Craft CP, I chose to do the steps I believe that Craft executes for installing a plugin completely 

I believe when Craft installs a plugin that these two steps take place

1. `composer require <package>` 
2. ` craft install/plugin <package-handle>`

I did this so I could see what fails and why. So I entered my Craft web server and executed the following

1. `composer require putyourlightson/craft-blitz`

This completed fine as expected, Composer installed the necessary files for the plugin into the vendor folder and added the package to my `composer.json`. 

![image](https://user-images.githubusercontent.com/41299115/55204549-c484c500-51a5-11e9-8d91-38a7600ce023.png)


2. `craft install/plugin blitz`

This is the command that  _Craft installs a plugin_, which I'm assuming means does the necessary database changes and adds it to the `project.yaml`. 

My Craft database _does_ have the tables used by Blitz -- I had it installed prior and simply removed it 
![image](https://user-images.githubusercontent.com/41299115/55204304-e16cc880-51a4-11e9-9751-35d1b6ac1766.png)

and it does also have the entry for Blitz in the `craft_plugins` table 
![image](https://user-images.githubusercontent.com/41299115/55204348-05c8a500-51a5-11e9-9e5b-e55eaef15d09.png)

but I don't believe this is affecting much if anything. I've tested with removing those corresponding tables and the entry to no avail before. 

Anyhow, running the `craft install/plugin blitz` command produces the following output 

![image](https://user-images.githubusercontent.com/41299115/55204571-e3835700-51a5-11e9-8b23-dfce33e20ab9.png)

which is odd, where does it expect to find some sort of entry for the handle `blitz`? We know the composer files are there, even the database entries for the plugin are there. 

So I decide to check the `project.yaml` of a Craft installation where Blitz does successfully install -- my test environment (the one where this problem is occurring is my development environment). Lo and behold, within the `project.yaml` of my test environment where Blitz **does work**, there's an entry for Blitz in the plugin section that looks something like 

```
  blitz:
    edition: standard
    enabled: true
    schemaVersion: 2.0.0
```
 Within the `project.yaml` of my development environment, there is no such entry. But that's expected, if the plugin is not being installed successfully by Craft, then I don't expect there to be an entry in `project.yaml` for it, since it wasn't technically installed. 

For curiosity, I manually modified my development environment's `project.yaml` and included that `blitz` configuration under the plugin section.

I then ran `craft install/plugin blitz` and it worked. I also ran `craft project-config/sync` to sync it to wherever else it needed to be synced. It completed successfully with the following 

![image](https://user-images.githubusercontent.com/41299115/55204964-5214e480-51a7-11e9-8515-27677f4668c3.png)

This appears to have fixed the problem but leaves me with a daunting question -- why would Craft be looking for an entry for `blitz` in the `project.yaml` when the installation hasn't even technically occurred (i.e. completed successfully)?

I would expect Craft to modify and add the `blitz` configuration entry to `project.yaml` when the installation successfully completes -- **not to look for it there when installing**. It doesn't make sense to me why it needs that entry there or how it would get there in the first place prior to a successful installation.

**Comment by putyourlightson** [comment]
Hmm that is interesting. It sounds like some sort of race condition between the install process and the project config. It seems that the plugin was never uninstalled, considering that the database tables still existed, so perhaps that had something to do with it. I've asked P&T to look into it and am also curious to see what they say.

**Comment by putyourlightson** [comment]
So I received confirmation from Pixel & Tonic that this is likely being caused by project config somehow getting out of sync. Running `./craft project-config/rebuild` and then installing or running updates should hopefully help resolve this for next time.
