### ISSUE TITLE
SQL Exception: 1406 Data too long for column 'params' at row 1 into `craft_blitz_elementqueries`

### ISSUE THREAD

**Issue by Kashkin** [putyourlightson/craft-blitz#92]
I've come across a page that refuses to be cached. It looks like the queries being executed are too complex. This page is grabbing entries from two channels based on related categories.

`SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'params' at row 1 The SQL being executed was: INSERT INTO `craft_blitz_elementqueries` (`index`, `type`, `params`)`

Googling this error, I came across an [old issue with native caching in Craft](https://github.com/craftcms/cms/issues/1862). Perhaps their fix would help here?

- Craft 3.1.20.1
- Blitz 2.0.7
- MySQL 5.7.25

P.S. I'm super impressed with Blitz, so far!

**Comment by putyourlightson** [comment]
Yes, it seems that the query is very long (over 65,535 characters) and therefore does not fit in the `params` column which is a `TEXT` column in the `craft_blitz_elementqueries` table of the database. A quick fix would be to change the column type to `MEDIUMTEXT` but I would be interested to see the contents being saved so I can perhaps optimise it. Using a `TEXT` column requires less space in the DB so this is preferential. If you could send the full query in the error message, or once saved to the database, to info@putyourlightson.net then I'll investigate further. Thanks!

**Comment by putyourlightson** [comment]
I'm closing this issue but if you could send us the query then we can try to figure out why the value of `params` became so large.
