### ISSUE TITLE
Suggested solution for clearing cache on SEOmatic changes.

### ISSUE THREAD

**Issue by cmalven** [putyourlightson/craft-blitz#93]
This may apply more broadly to any plugin that can change page content without using elements in the templates, but I've encountered it most frequently with SEOmatic:

Changes to site-wide metadata in SEOmatic will not automatically clear the Blitz cache, which makes sense given that Blitz doesn't know anything about SEOmatic.

Short of Blitz adding specific support for listening to SEOmatic events (feature request) and automatically clearing the cache, is there any suggested way to handle this other than adding a module to the site that listens for SEOmatic change events and clears the Blitz cache?

**Comment by putyourlightson** [comment]
Thanks for the message and request. I'm checking with @nystudio107 on what events SEOmatic has that could potentially be used to clear the cache. Will post an update here once I know more.

**Comment by khalwat** [comment]
Probably what should happen is SEOmatic should throw an event whenever it clears its own caches, allowing other caches to do their thing as well.

File an issue here and I'll get it done: https://github.com/nystudio107/craft-seomatic/issues

**Comment by cmalven** [comment]
Added! Thanks to you both for your feedback on this.

**Comment by putyourlightson** [comment]
Excellent, I'll implement this once the events are in place.

**Comment by khalwat** [comment]
Implemented in https://github.com/nystudio107/craft-seomatic/commit/604ff36a28edb5044d956a9a902976d9109e9851

@putyourlightson you can pull from `dev-develop` if you want to try it out. Ping me if you have any questions.

**Comment by putyourlightson** [comment]
Thanks @khalwat, will add the logic to Blitz in the next release.

**Comment by putyourlightson** [comment]
Added in 2.1.0.
