### ISSUE TITLE
AWS CloudFront

### ISSUE THREAD

**Issue by cjativa** [putyourlightson/craft-blitz#96]
Hi, I'm just wondering if it would be possible to get the cache purger logic (I would write it myself obviously) working with AWS CloudFront?

We use CloudFront as just a CDN, not necessarily a reverse-proxy. I'm thinking all I would need to do is add the corresponding logic for our custom cache purger to make the corresponding API calls to CloudFront to remove an invalidated file from the cache.

Is this how the cache purger should work in theory?

**Comment by putyourlightson** [comment]
Is CloudFront caching your HTML or just assets like images, CSS, JS, etc? If only the latter then you don't need an extra cache purger.

**Comment by cjativa** [comment]
Hey, CloudFront is caching everything at the moment -- so HTML too. Do you think we shouldn't be caching HTML from Craft?

**Comment by putyourlightson** [comment]
No, you should be caching HTML for optimal speed, I just wanted to be sure. Which storage type are you using in Blitz and how are you currently purging the CloudFront cache when you update content in the CMS?

**Comment by cjativa** [comment]
In Blitz, we're using the default storage type of Blitz File Storage. Currently, we have CloudFront with a TTL on cached objects for 20 minutes. So after 20 minutes, CloudFront will make a request to our Craft server to retrieve the latest version of the document. 

This will pull from Craft regardless of whether or not the file has been updated in Craft because of the TTL I believe.

This works to an extent. But if we can have Craft/Blitz automatically make the necessary API calls to CloudFront to purge content as it gets updated in Craft automatically, that would be best, hence my questions.

I probably won't get started on the necessary code until after this coming week as I am going on vacation, but wanted to confirm that _that_ is how we can ultimately use the cache purger.

**Comment by putyourlightson** [comment]
Yes, that's correct. We have a purger for KeyCDN (https://github.com/putyourlightson/craft-blitz-keycdn) and have one for CloudFront on the roadmap. If you'd like to create your own then I recommend you follow the method used there, otherwise I'll try to prioritise our development.

**Comment by cjativa** [comment]
Yeah I was looking at the code for the KeyCDN purger to understand what's going on behind the scenes. I'm glad you have the CloudFront one on roadmap! 

We use AWS Elastic Beanstalk for hosting our Craft application, hence our using CloudFront.

I won't be able to begin creation our own purger for CloudFront until the 22nd of this month, so sure, if you don't mind prioritizing efforts on that front that would be super great. 

I'm sure we'd be one of your first testers! Our TTL configuration should hold us over for the time being. What do you think an ETA would be like? If it's too far out, I wouldn't mind helping out with a pull request.

**Comment by putyourlightson** [comment]
We'll aim for next week.

**Comment by cjativa** [comment]
Thank you! Much appreciated.

**Comment by putyourlightson** [comment]
Just released the Blitz CloudFront purger. Be sure to read the notice about AWS invalidation costs.
https://github.com/putyourlightson/craft-blitz-cloudfront
