### ISSUE TITLE
Extremally slow cache refresh on resaving entries

### ISSUE THREAD

**Issue by pgrzyb** [putyourlightson/craft-blitz#98]
Hi guys, 
We started using Blitz on one of our client sites, and as much as the load times are amazing, the slowness in the CP is making their editors want to kill us. 
Basically, whenever an editor saves an entry, Blitz triggers a cache refresh, that adds a few (usually around 7-8) tasks to the queue. Each task "hangs" 1/3rd of the way for around 30 seconds and then continues to the end almost instantly. This means that every time an editor saves an entry he fills up the queue with a few minutes of tasks, without the ability to see the changes on the live site. 
This could be considered an inconvenience if we were talking about a single editor, but when there are multiple editors updating the site at the same time, and the Blitz tasks adding up to other Craft tasks, like updating URLs, asset indexes and whatever else - going from saving an entry to seeing the changes live can take an insane amount of time.

I am not sure how to debug this, that's why this issue I'm posting lacks in techy details... How should I proceed? Are there any guidelines regarding server configuration that could help me resolve this issue? It has been happening on both the production server and our homestead dev VM.

**Comment by putyourlightson** [comment]
First off, what version of Blitz and Craft are you running? And if you are using multi-site then how many sites are there?

**Comment by pgrzyb** [comment]
Thanks for the quick reply!
We are on Blitz 2.0.8 right now, but this has been an issue since a much earlier version, the first thing I tried was updating to see if it resolves the issue.
Craft 3.1.21.1 and same as above, it was happening since at least 3.1.17, don't think we ever ran Blitz on anything below that.
We are running multi-site for different locales/languages, and we are at 4 sites at this point.

**Comment by putyourlightson** [comment]
Thanks for the response. With 4 sites, saving an entry in one is going to result in being cleared in all 4 sites if the section is localized. Blitz 2.1 is under development and part of the effort is optimising the refresh cache process utilising the recent additions to Craft. I'll let you know when that is released, aiming for later this month.

**Comment by putyourlightson** [comment]
FYI, using live preview will allow your editors to see how their changes will appear once the cache is cleared, if that is any help.

**Comment by putyourlightson** [comment]
Added improvements for this in the upcoming 2.1.0 release which will become available along with Craft 3.2.0.
