### ISSUE TITLE
How to establish relationships between a Single and Elements?

### ISSUE THREAD

**Issue by petetak** [putyourlightson/craft-blitz#99]
I need to establish a relationship between a Single page and some Elements that are listed via a template on that page so that when the Elements are saved Blitz will flush the cache for the Single (and other Singles too)

I see there is some documentation about tags but I'm not sure if this is the way to go or not.  How does Blitz establish a link between different entities?

**Comment by putyourlightson** [comment]
Blitz will keep track of all elements that are used in each template and refresh the cached pages for you as necessary. Is this what you were asking about or do you have a more specific need?

**Comment by petetak** [comment]
Great news Ben! Mind = blown.
